"""
Partners-tier All-In-One Protocol data — asd.
Auto-split from partners_all_in_one_data.py. Edit this file to modify asd data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['asd'] = {
    'display_name': 'Autism Spectrum Disorder',
    'short': 'ASD',
    'condition_slug': 'asd',
    'icd10': 'F84.0',
    'tps_warning': (
        "TPS use in Autism Spectrum Disorder is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for ASD "
        "is emerging. Informed consent, capacity assessment, and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Social brain network hypofunction / atypical DMN / SN dysregulation / CEN variability',
    'fnon_montage_selection': [
        ['Social communication dominant', 'HDCstim tDCS F3/TP9 anodes / Oz cathode'],
        ['Repetitive behaviors', 'HDCstim F3/Fp2 anode/cathode + SMA Fz cathode'],
        ['Sensory overload', 'tDCS Cz cathode / F3/F4 anodes'],
        ['Executive dysfunction', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Anxiety comorbid', 'tDCS F3/F4 + taVNS extended'],
    ],
    'tps': [
        ['T1', 'DLPFC executive', 'F3/F4 bilateral', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T2', 'DMPFC social', 'F3 medial proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T3', 'TPJ social cognition', 'P3/T5 bilateral', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'SMA repetitive behaviors', 'Fz / SMA-proxy', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T5', 'ACC sensory/social', 'Fz / ACC-proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'Social brain activation', 'Social network hypofunction', 'DMPFC F3 + TPJ P3/T5', 'Social engagement capacity', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT2', 'CEN executive restore', 'CEN variability', 'F3/F4 bilateral', 'Executive function improve', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT3', 'RRB reduction (SMA)', 'SMA hyperactivation', 'Fz SMA-proxy', 'Repetitive behavior reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'DMN calibration', 'Atypical DMN', 'mPFC Fp1 + PCC Pz', 'Self-other processing', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'Sensory modulation SN', 'SN dysregulation', 'Cz + insula C3', 'Sensory threshold normalize', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Language-social', 'Language + social overlap', 'Broca F5 + TPJ', 'Social language capacity', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Anxiety comorbid', 'SN hyperactivation', 'F3/F4 + Cz cathode', 'Anxiety reduction', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Attention joint', 'ATTENTION network', 'IPS P3/P4 + FEF', 'Joint attention support', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT9', 'Comprehensive ASD', 'Multi-network', 'Social + CEN + SN rotating', 'Holistic ASD protocol', '0.20 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Social DLPFC', 'F3/F4 anodes / Oz cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'DMPFC social', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C3', 'RRB SMA', 'Fz cathode / F3 anode', '1.5 mA', '20 min', 'Evidence B'],
        ['C4', 'Sensory modulation', 'Cz cathode / F3/F4 anodes', '1.5 mA', '20 min', 'Emerging'],
        ['C5', 'Executive function', 'F3/F4 bilateral / Oz', '1.5 mA', '20 min', 'Evidence B'],
        ['C6', 'Anxiety comorbid', 'F3 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Language-social', 'F5 anode / F6 cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C8', 'Attention network', 'P3/P4 bilateral / Oz', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'Social brain', 'Social network hypofunction', 'F3/F4 anodes / Oz', 'Social engagement', '1.5 mA', '20 min'],
        ['F2', 'CEN executive', 'CEN variability', 'F3/F4 bilateral / Oz', 'Executive restore', '1.5 mA', '20 min'],
        ['F3', 'SMA RRB', 'SMA hyperactivation', 'Fz cathode / F3 anode', 'Repetitive behavior reduce', '1.5 mA', '20 min'],
        ['F4', 'SN sensory', 'SN dysregulation', 'Cz cathode / F3/F4', 'Sensory threshold', '1.5 mA', '20 min'],
        ['F5', 'Language social', 'Language network', 'F5 anode / F6 cathode', 'Social language', '1.5 mA', '20 min'],
        ['F6', 'Anxiety ASD', 'Anxiety comorbid', 'F3 anode / Cz cathode', 'Anxiety reduction', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Focus social', 'Variant C', 'F3/TP9', '1.2 mA', '20 min', 'Social tasks'],
        ['C2-PS', 'Executive', 'Variant B', 'F3/F4', '1.2 mA', '20 min', 'EF training'],
        ['C3-PS', 'Calm sensory', 'Variant D', 'Cz/F3', '1.2 mA', '20 min', 'Sensory protocol'],
        ['C4-PS', 'Anxiety ASD', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Anxiety comorbid'],
        ['C5-PS', 'Language-social', 'Variant C', 'F5/F3', '1.2 mA', '20 min', 'Language support'],
        ['C6-PS', 'Attention', 'Variant B', 'P3/P4', '1.2 mA', '20 min', 'Joint attention'],
        ['C7-PS', 'RRB reduce', 'Variant D', 'Fz/F3', '1.2 mA', '20 min', 'Repetitive behavior'],
        ['C8-PS', 'Sleep ASD', 'Variant G', 'Fp1/Cz', '1.0 mA', '20 min', 'ASD insomnia'],
    ],
    'fnon_plato': [
        ['FP1', 'Social network', 'Social hypofunction', 'Variant C', 'F3/TP9', '1.2 mA', '20 min'],
        ['FP2', 'CEN executive', 'CEN variability', 'Variant B', 'F3/F4', '1.2 mA', '20 min'],
        ['FP3', 'SMA RRB', 'SMA hyperactivation', 'Variant D', 'Fz/F3', '1.2 mA', '20 min'],
        ['FP4', 'SN sensory', 'SN dysregulation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP5', 'Anxiety ASD', 'Anxiety comorbid', 'Variant D', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP6', 'Sleep ASD', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.0 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Social Communication Difficulties',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/TP9', 'TPS DMPFC+TPJ', 'Social skills task'],
            'card_left': ['Network: Social brain hypofunction', 'Key target: DMPFC, TPJ, STS', 'Priority: Social cognition activation'],
            'card_right': ['TPS: T2+T3 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Social task'],
            'brain_targets': [
                ['DMPFC', 'Social cognition', 'Activate', 'T2 / C2 / FP1', 'Evidence B'],
                ['TPJ', 'Mentalizing', 'Upregulate', 'T3 / C8', 'Emerging'],
                ['STS', 'Biological motion', 'Activate', 'TPS T5/T6', 'Emerging'],
                ['Broca (F5)', 'Social language', 'Support', 'T2 / C7', 'Emerging'],
                ['Amygdala', 'Social emotion', 'Normalize', 'FT4 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1 F3/F4', 'TPS DMPFC', 'Social stories task'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS TPJ', 'Perspective-taking exercises'],
                ['taVNS 20 min', 'tDCS F1', 'TPS STS bilateral', 'Video social scenarios'],
                ['CES 20 min', 'tDCS C7', 'TPS Broca F5', 'Conversation skills practice'],
            ],
            'task_pairing': 'Social stories, perspective-taking exercises, video social scenario analysis, conversation skills practice.',
            'fnon_hypothesis': 'ASD social communication reflects DMPFC-TPJ hypoactivation during social processing. TPS during social tasks drives activity-dependent plasticity in mentalizing network nodes.',
        },
        {
            'code': 'P2', 'name': 'Repetitive & Restricted Behaviors',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz cathode/F3', 'TPS SMA+DLPFC', 'Flexibility task'],
            'card_left': ['Network: SMA hyperactivation + habit circuit', 'Key target: SMA, DLPFC, caudate', 'Priority: Behavioral flexibility'],
            'card_right': ['TPS: T4+T1 + FT3', 'tDCS: C3/F2', 'PlatoScience: C7-PS/FP3', 'Flexibility task'],
            'brain_targets': [
                ['SMA', 'Repetitive urge', 'Inhibit', 'T4 / C3 / FP3', 'Evidence B'],
                ['DLPFC', 'Cognitive flexibility', 'Activate', 'T1 / C5', 'Evidence B'],
                ['ACC', 'Inflexibility monitoring', 'Recalibrate', 'T5 / C4', 'Emerging'],
                ['Caudate', 'Habit circuit', 'Modulate', 'FT3 / lateral F', 'Emerging'],
                ['Putamen', 'Motor routine', 'Normalize', 'TPS C3/C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 Fz cathode', 'TPS SMA', 'Flexibility training'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', 'Set-shifting tasks'],
                ['taVNS 20 min', 'tDCS F2', 'TPS caudate', 'Routine variation program'],
                ['CES 20 min', 'tDCS C5', 'TPS ACC', 'CBT flexibility exercises'],
            ],
            'task_pairing': 'Cognitive flexibility training, set-shifting tasks, routine variation exercises, behavioral flexibility CBT.',
            'fnon_hypothesis': 'RRBs reflect SMA-caudate habit circuit hyperactivation with DLPFC flexibility deficit. SMA TPS + flexibility tasks targets both the compulsive drive and the cognitive control deficit.',
        },
        {
            'code': 'P3', 'name': 'Sensory Processing Difficulties',
            'sozo_bar': ['taVNS 20 min', 'tDCS Cz cathode/F3', 'TPS SN suppress', 'Sensory integration'],
            'card_left': ['Network: SN dysregulation + sensory over/under', 'Key target: SN nodes, insula, Cz', 'Priority: Sensory threshold calibration'],
            'card_right': ['TPS: T5 + FT5', 'tDCS: C4/F4', 'PlatoScience: C3-PS/FP4', 'OT sensory task'],
            'brain_targets': [
                ['SN nodes (Cz)', 'Sensory salience', 'Recalibrate', 'FT5 / C4 / FP4', 'Emerging'],
                ['Insula', 'Sensory integration', 'Normalize', 'T5 / C4', 'Emerging'],
                ['ACC', 'Sensory distress', 'Modulate', 'T5 / C5', 'Emerging'],
                ['S1/S2', 'Sensory cortex', 'Normalize', 'TPS C3/C4', 'Emerging'],
                ['DLPFC', 'Top-down filter', 'Activate', 'T1 / C5', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C4 Cz cathode', 'TPS SN suppress', 'Sensory integration OT'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS insula', 'Sensory desensitization'],
                ['taVNS 20 min', 'tDCS F4', 'TPS S1 bilateral', 'Tactile graduated exposure'],
                ['CES 20 min', 'tDCS C5', 'TPS DLPFC', 'Sensory coping strategies'],
            ],
            'task_pairing': 'Sensory integration OT (occupational therapy), graduated sensory exposure, tactile desensitization, sensory coping strategies.',
            'fnon_hypothesis': 'ASD sensory difficulties reflect SN threshold dysregulation causing atypical salience responses to sensory input. SN-targeted TPS recalibrates sensory gate without suppressing awareness.',
        },
        {
            'code': 'P4', 'name': 'Executive Dysfunction (ASD)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'EF training'],
            'card_left': ['Network: CEN variability / DLPFC inconsistency', 'Key target: DLPFC bilateral', 'Priority: Executive consistency'],
            'card_right': ['TPS: T1 + FT2', 'tDCS: C5/F2', 'PlatoScience: C2-PS/FP2', 'EF task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Executive function', 'Stabilize', 'T1 / C5 / FP2', 'Evidence B'],
                ['ACC', 'Performance monitoring', 'Normalize', 'T5 / C4', 'Emerging'],
                ['OFC', 'Decision flexibility', 'Modulate', 'TPS Fp2', 'Emerging'],
                ['Frontal-parietal', 'WM network', 'Activate', 'TPS F3+P3', 'Emerging'],
                ['Thalamus (CES)', 'Arousal gating', 'Normalize', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Executive function training'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Planning and organization'],
                ['taVNS 20 min', 'tDCS C5', 'TPS frontal-parietal', 'Working memory n-back'],
                ['CES 20 min', 'tDCS F2', 'TPS OFC', 'Flexibility set-shifting'],
            ],
            'task_pairing': 'Executive function training, planning and organization tasks, working memory training, set-shifting exercises.',
            'fnon_hypothesis': 'ASD executive dysfunction reflects CEN variability with inconsistent DLPFC engagement. Bilateral DLPFC TPS increases neural activation consistency supporting executive task performance.',
        },
        {
            'code': 'P5', 'name': 'Anxiety Comorbidity (ASD)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC+vmPFC', 'CBT adapted ASD'],
            'card_left': ['Network: SN hyperactivation + social anxiety', 'Key target: DLPFC, vmPFC, amygdala', 'Priority: Anxiety circuit modulation'],
            'card_right': ['TPS: T1 + FT7', 'tDCS: C6/F1', 'PlatoScience: C4-PS/FP5', 'CBT-A task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety regulation', 'Activate', 'T1 / C6 / FP5', 'Evidence B'],
                ['vmPFC', 'Safety signal', 'Strengthen', 'FT7 / F1', 'Emerging'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT4 / temporal', 'Emerging'],
                ['SN nodes', 'Anxiety salience', 'Reduce', 'FT7 / Cz', 'Emerging'],
                ['ACC', 'Worry circuit', 'Modulate', 'T5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C6 F3/F4', 'TPS DLPFC', 'CBT adapted for ASD'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Worry reduction ASD'],
                ['taVNS 20 min', 'tDCS F1', 'TPS SN suppress', 'Exposure hierarchy ASD'],
                ['CES 20 min', 'tDCS C6', 'TPS amygdala', 'Relaxation ASD-adapted'],
            ],
            'task_pairing': 'CBT adapted for ASD, visual worry reduction tools, graduated exposure hierarchy, ASD-adapted relaxation.',
            'fnon_hypothesis': 'ASD anxiety reflects SN hyperactivation amplified by social prediction error processing. DLPFC TPS strengthens top-down anxiety regulation concurrent with ASD-adapted CBT.',
        },
        {
            'code': 'P6', 'name': 'Attention & ADHD Comorbidity',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Attention task'],
            'card_left': ['Network: ATTENTION hypofunction + CEN', 'Key target: DLPFC bilateral, IPS', 'Priority: Sustained attention'],
            'card_right': ['TPS: T1 + FT8', 'tDCS: C1/F2', 'PlatoScience: C2-PS/FP2', 'Attention task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Attention control', 'Activate', 'T1 / C1 / FP2', 'Evidence B'],
                ['IPS bilateral', 'Spatial attention', 'Upregulate', 'FT8 / C8', 'Emerging'],
                ['ACC', 'Attention monitoring', 'Normalize', 'T5 / C4', 'Emerging'],
                ['FEF', 'Top-down attention', 'Activate', 'TPS F8', 'Emerging'],
                ['SN nodes', 'Attention salience', 'Balance', 'FT5 / Cz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Attention training program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS IPS', 'Sustained attention tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS FEF', 'Visual attention training'],
                ['CES 20 min', 'tDCS F2', 'TPS ACC', 'Mindfulness attention'],
            ],
            'task_pairing': 'Attention training program, sustained attention exercises, visual attention training, mindfulness attention practice.',
            'fnon_hypothesis': 'ASD-ADHD comorbidity reflects dual DLPFC inconsistency and ATTENTION network hypofunction. Bilateral DLPFC TPS stabilizes executive attention while IPS activation supports sustained focus.',
        },
        {
            'code': 'P7', 'name': 'Emotional Regulation Difficulties',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/Fp1', 'TPS DLPFC+vmPFC', 'Emotion task'],
            'card_left': ['Network: LIMBIC hyperactivation + CEN regulation deficit', 'Key target: DLPFC, vmPFC, insula', 'Priority: Emotional regulation capacity'],
            'card_right': ['TPS: T1+T2 + FT7', 'tDCS: C1/F1', 'PlatoScience: C4-PS/FP5', 'ER task'],
            'brain_targets': [
                ['DLPFC', 'ER strategy application', 'Activate', 'T1 / C1 / FP5', 'Evidence B'],
                ['vmPFC', 'Emotion safety', 'Strengthen', 'T2 / F1', 'Emerging'],
                ['Insula', 'Emotional awareness', 'Normalize', 'FT7 / C4', 'Emerging'],
                ['Amygdala', 'Emotional reactivity', 'Downregulate', 'FT4 / temporal', 'Emerging'],
                ['ACC', 'Conflict emotion', 'Modulate', 'T5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C1 F3/Fp1', 'TPS DLPFC+vmPFC', 'Emotion regulation skills'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS insula', 'Emotion recognition training'],
                ['taVNS 20 min', 'tDCS F1', 'TPS amygdala', 'DBT-adapted skills'],
                ['CES 20 min', 'tDCS C6', 'TPS ACC', 'Emotional thermometer task'],
            ],
            'task_pairing': 'Emotion regulation skills program, emotion recognition training, DBT-adapted skills for ASD, emotional thermometer tool.',
            'fnon_hypothesis': 'ASD emotional dysregulation reflects insufficient DLPFC-vmPFC modulation of amygdala reactivity. TPS increases prefrontal capacity for in-the-moment emotion regulation strategy application.',
        },
        {
            'code': 'P8', 'name': 'Sleep Difficulties (ASD)',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Cz low', 'TPS DLPFC low-dose', 'Sleep routine'],
            'card_left': ['Network: Hyperarousal + circadian dysregulation', 'Key target: Thalamus (CES), DLPFC', 'Priority: Sleep onset and maintenance'],
            'card_right': ['TPS: T1 low + FT7', 'tDCS: C8/F6 low', 'PlatoScience: C8-PS/FP6', 'Sleep routine'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep regulation', 'Balance', 'T1 low / C8', 'Emerging'],
                ['Thalamus (CES)', 'Sleep gating', 'Support', 'CES protocol', 'Emerging'],
                ['Hypothalamus', 'Circadian', 'Normalize (CES)', 'CES protocol', 'Emerging'],
                ['ACC', 'Nighttime hyperarousal', 'Reduce', 'T5 / C4', 'Emerging'],
                ['Insula', 'Sensory sleep onset', 'Normalize', 'FT5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C8 low', 'TPS DLPFC low', 'Visual sleep schedule'],
                ['taVNS 20 min low', 'PlatoScience Variant G', 'TPS ACC low', 'Sleep routine ASD-adapted'],
                ['CES 20 min', 'tDCS F6 low', 'TPS Cz thalamus', 'Sensory sleep environment'],
                ['CES 20 min', 'tDCS F3 low', 'TPS mPFC', 'Social story sleep'],
            ],
            'task_pairing': 'Visual sleep schedule, ASD-adapted sleep routine, sensory sleep environment optimization, social story about sleep.',
            'fnon_hypothesis': 'ASD sleep difficulties reflect hyperarousal from SN dysregulation + sensory sensitivity at sleep onset. CES + gentle tDCS reduces cortical arousal without exacerbating sensory sensitivities.',
        },
        {
            'code': 'P9', 'name': 'Minimally Verbal ASD',
            'sozo_bar': ['taVNS 20 min', 'tDCS F5/F3 language', 'TPS language network', 'AAC + SLT task'],
            'card_left': ['Network: Language + social network severe hypofunction', 'Key target: Broca F5, SMA, DMPFC', 'Priority: Communication support'],
            'card_right': ['TPS: FT6 + T4', 'tDCS: C7/F1', 'PlatoScience: C5-PS/FP1', 'AAC task'],
            'brain_targets': [
                ['Broca (F5)', 'Speech output', 'Activate', 'FT6 / C7 / FP1', 'Emerging'],
                ['SMA', 'Speech initiation', 'Support', 'T4 / C3', 'Emerging'],
                ['DMPFC', 'Communicative intent', 'Activate', 'T2 / C2', 'Emerging'],
                ['Premotor', 'Articulatory', 'Activate', 'TPS F3/F4', 'Emerging'],
                ['Cerebellum', 'Speech coordination', 'Support', 'TPS lateral', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C7 F5/F3', 'TPS Broca F5', 'AAC device training'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS SMA', 'SLT intensive'],
                ['taVNS 20 min', 'tDCS F1', 'TPS DMPFC', 'Communicative intent tasks'],
                ['CES 20 min', 'tDCS C5', 'TPS premotor', 'Verbal imitation tasks'],
            ],
            'task_pairing': 'AAC (Augmentative and Alternative Communication) training, SLT intensive, communicative intent tasks, verbal imitation exercises.',
            'fnon_hypothesis': 'Minimally verbal ASD reflects severe language + social network hypofunction. Low-intensity Broca + SMA TPS during AAC/SLT sessions supports residual communication circuit activation.',
        },
    ],
    'task_pairing_rows': [
        ['Social stories', 'Post-TPS', 'Social', 'P1'],
        ['Flexibility training', 'Concurrent tDCS', 'Behavioral', 'P2'],
        ['Sensory OT', 'Concurrent tDCS', 'Sensory', 'P3'],
        ['EF training', 'Post-TPS', 'Cognitive', 'P4'],
        ['CBT-A', 'Post-TPS', 'Anxiety', 'P5'],
        ['Attention program', 'Post-TPS', 'Attention', 'P6'],
        ['ER skills', 'During tDCS', 'Emotional', 'P7'],
        ['Sleep routine', 'Evening CES', 'Sleep', 'P8'],
        ['AAC + SLT', 'Concurrent tDCS', 'Communication', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'VABS, SRS-2', 'Adaptive + social', 'Safety + tolerance check'],
        ['Week 4', 'SRS-2, BRIEF, CGAS', 'Social + executive + function', 'Protocol compliance'],
        ['Week 6', 'Full ASD battery', 'Comprehensive', 'Phase 2 readiness'],
        ['Week 10', 'SRS-2, QoL, family report', 'Social trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment + school', 'All domains', 'Education coordination'],
        ['Month 6', 'Yearly reassessment', 'Developmental trajectory', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(3, 3, 3, 4, 3, 4, 2, 3, 3),
}
