"""
Partners-tier All-In-One Protocol data — chronic_pain.
Auto-split from partners_all_in_one_data.py. Edit this file to modify chronic_pain data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['chronic_pain'] = {
    'display_name': 'Chronic Pain Syndromes',
    'short': 'Chronic Pain',
    'condition_slug': 'chronic_pain',
    'icd10': 'G89.2',
    'tps_warning': (
        "TPS use in Chronic Pain Syndromes is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for central chronic pain "
        "modulation is emerging. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Central sensitization / SN hyperactivation / descending inhibition failure / DMN pain overlap',
    'fnon_montage_selection': [
        ['Fibromyalgia dominant', 'HDCstim tDCS C3/C4 anodes + Cz / Oz cathode'],
        ['CRPS / neuropathic', 'tDCS M1 contralateral C3/C4 anode'],
        ['Central sensitization', 'HDCstim Cz anode + DLPFC F3/F4'],
        ['Pain + depression', 'tDCS F3 anode / F4 cathode + C3 anode'],
        ['Headache / migraine', 'tDCS Oz anode + C3/C4 + CES'],
    ],
    'tps': [
        ['T1', 'M1 pain gate (contralateral)', 'C3/C4 motor cortex', '0.25 mJ/mm²', '1200 pulses', 'Evidence A'],
        ['T2', 'DLPFC descending inhibition', 'F3/F4 DLPFC', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'ACC pain affect', 'Fz / ACCproxy', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'Insula pain integration', 'C3 insula proxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Occipital (migraine)', 'Oz bilateral', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'M1 analgesic', 'Pain gate failure', 'C3/C4 bilateral', 'Cortical pain inhibition', '0.25 mJ/mm²', '1200 pulses', '10 sessions'],
        ['FT2', 'CEN descending inhibition', 'CEN hypofunction', 'F3/F4 DLPFC', 'Top-down pain control', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT3', 'SN desensitization', 'SN hyperactivation', 'Cz + ACC Fz', 'Threat salience reduction', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT4', 'DMN pain rumination', 'DMN-pain overlap', 'mPFC Fp1 + PCC Pz', 'Break pain catastrophizing', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT5', 'Limbic pain-affect', 'LIMBIC pain sensitization', 'Amygdala temporal + vmPFC', 'Emotional pain component', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Occipital migraine', 'Visual cortex sensitization', 'Oz bilateral', 'Migraine prophylaxis', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Spinal facilitation block', 'Ascending facilitation', 'M1 + SMA Fz', 'Descending inhibitory tracts', '0.25 mJ/mm²', '1200 pulses', '10 sessions'],
        ['FT8', 'Autonomic pain modulation', 'Autonomic sensitization', 'Insula C3 + vagal', 'Parasympathetic dominance', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Multimodal pain protocol', 'Multi-network', 'Rotating M1/DLPFC/ACC', 'Comprehensive pain network', '0.22 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'M1 analgesic', 'C3/C4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence A'],
        ['C2', 'DLPFC pain control', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'ACC modulation', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Fibromyalgia protocol', 'C3/C4 bilateral / Oz', '2 mA', '20 min', 'Evidence B'],
        ['C5', 'Neuropathic pain', 'M1 contralateral / shoulder', '2 mA', '20 min', 'Evidence B'],
        ['C6', 'Insula central pain', 'C3 anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Pain + depression', 'F3 anode / Fp2 cathode + C3', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Migraine occipital', 'Oz anode / Cz cathode', '2 mA', '20 min', 'Evidence B'],
    ],
    'fnon_tdcs': [
        ['F1', 'M1 pain gate', 'Pain gate failure', 'C3/C4 anodes / Oz', 'Motor cortex analgesia', '2 mA', '20 min'],
        ['F2', 'Descending inhibition', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Top-down pain inhibition', '2 mA', '20 min'],
        ['F3', 'SN desensitize', 'SN hyperactivation', 'Cz anode / Oz cathode', 'Salience recalibration', '2 mA', '20 min'],
        ['F4', 'DMN pain break', 'DMN-pain rumination', 'Fz cathode / Pz cathode', 'Catastrophizing reduction', '1.5 mA', '20 min'],
        ['F5', 'Insula normalize', 'Insula hyperactivation', 'C3 anode / shoulder', 'Interoceptive recalibration', '2 mA', '20 min'],
        ['F6', 'Migraine prophylaxis', 'Occipital sensitization', 'Oz anode / Cz cathode', 'Visual cortex inhibition', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Pain + focus', 'Variant B', 'C3/C4', '1.6 mA', '20 min', 'M1 analgesic + attention'],
        ['C2-PS', 'Central pain relief', 'Variant E', 'Cz/C3', '1.4 mA', '20 min', 'Central sensitization'],
        ['C3-PS', 'Pain mood comorbid', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Depression + pain'],
        ['C4-PS', 'Sleep-pain', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'Sleep with pain'],
        ['C5-PS', 'Neuropathic', 'Variant E', 'C3/C4', '1.6 mA', '20 min', 'Neuropathic pain'],
        ['C6-PS', 'Catastrophizing', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Pain catastrophizing'],
        ['C7-PS', 'Fibromyalgia', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'Fibromyalgia protocol'],
        ['C8-PS', 'Migraine', 'Variant G', 'Oz/Cz', '1.2 mA', '20 min', 'Migraine prevention'],
    ],
    'fnon_plato': [
        ['FP1', 'M1 analgesic', 'Pain gate failure', 'Variant E', 'C3/C4', '1.6 mA', '20 min'],
        ['FP2', 'CEN pain control', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'SN desensitize', 'SN hyperactivation', 'Variant F', 'Cz/C3', '1.4 mA', '20 min'],
        ['FP4', 'DMN break', 'DMN-pain overlap', 'Variant G', 'F3/Pz', '1.2 mA', '20 min'],
        ['FP5', 'Limbic pain', 'LIMBIC sensitization', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP6', 'Migraine', 'Occipital sensitization', 'Variant G', 'Oz/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Fibromyalgia',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 bilateral', 'TPS M1+DLPFC', 'Graded exercise'],
            'card_left': ['Network: Central sensitization + SN hyperactivation', 'Key target: M1 bilateral, DLPFC', 'Priority: Descending inhibition restore'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C4/F1', 'PlatoScience: C7-PS/FP1', 'Exercise therapy'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C4 / FP1', 'Evidence A'],
                ['DLPFC', 'Descending inhibition', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Pain integration', 'Normalize', 'T4 / C6', 'Emerging'],
                ['ACC', 'Pain affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['Thalamus', 'Pain relay (CES)', 'Modulate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3/C4', 'TPS M1', 'Graded aerobic exercise'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS DLPFC', 'Pain education + exercise'],
                ['taVNS 20 min', 'tDCS C4', 'TPS insula', 'Body scan mindfulness'],
                ['CES 20 min', 'tDCS F1', 'TPS ACC', 'Acceptance pain ACT'],
            ],
            'task_pairing': 'Graded aerobic exercise (aqua therapy or low-impact), pain education, acceptance-based therapy, body scan.',
            'fnon_hypothesis': 'Fibromyalgia reflects widespread central sensitization with M1 analgesic circuit failure. M1 TPS activates endogenous opioid descending inhibitory systems, validated by neuroimaging.',
        },
        {
            'code': 'P2', 'name': 'CRPS / Neuropathic Pain',
            'sozo_bar': ['taVNS 30 min', 'tDCS M1 contralateral', 'TPS M1+DLPFC', 'Graded motor imagery'],
            'card_left': ['Network: Cortical reorganization + SN hyperactivation', 'Key target: M1 contralateral, insula', 'Priority: Cortical map normalization'],
            'card_right': ['TPS: T1 + FT7', 'tDCS: C5/F1', 'PlatoScience: C5-PS/FP1', 'GMI task'],
            'brain_targets': [
                ['M1 contralateral', 'Motor-pain map', 'Normalize', 'T1 / C5 / FP1', 'Evidence A'],
                ['Insula', 'Pain-autonomic', 'Normalize', 'T4 / C6', 'Emerging'],
                ['S1 contralateral', 'Sensory map', 'Reorganize', 'TPS C3/C4', 'Evidence B'],
                ['DLPFC', 'Top-down', 'Activate', 'T2 / C2', 'Evidence B'],
                ['ACC', 'Affective pain', 'Modulate', 'T3 / C3', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C5 M1', 'TPS M1 contralateral', 'Graded motor imagery'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS insula', 'Mirror visual feedback'],
                ['taVNS 20 min', 'tDCS C1', 'TPS S1 contralateral', 'Tactile desensitization'],
                ['CES 20 min', 'tDCS F1', 'TPS DLPFC', 'Pain rehabilitation'],
            ],
            'task_pairing': 'Graded Motor Imagery (GMI), mirror visual feedback therapy, tactile desensitization, pain rehabilitation program.',
            'fnon_hypothesis': 'CRPS reflects maladaptive cortical reorganization with M1/S1 map distortion amplifying pain signals. TPS + GMI drives corrective sensorimotor plasticity.',
        },
        {
            'code': 'P3', 'name': 'Chronic Low Back Pain',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3/C4 anodes', 'TPS M1+SMA', 'Movement therapy'],
            'card_left': ['Network: Motor-pain integration', 'Key target: M1 bilateral, SMA, ACC', 'Priority: Movement fear reduction'],
            'card_right': ['TPS: T1 + T3', 'tDCS: C1/F2', 'PlatoScience: C1-PS/FP1', 'Exercise therapy'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C1 / FP1', 'Evidence A'],
                ['SMA', 'Movement planning', 'Normalize', 'FT7 / Fz', 'Emerging'],
                ['ACC', 'Pain affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['DLPFC', 'Fear-avoidance', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Body perception', 'Normalize', 'T4 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3/C4', 'TPS M1', 'Graded movement therapy'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS SMA', 'Core stabilization'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Fear-avoidance CBT'],
                ['CES 20 min', 'tDCS F2', 'TPS DLPFC', 'Pain education'],
            ],
            'task_pairing': 'Graded movement therapy, core stabilization, fear-avoidance CBT, pain neuroscience education.',
            'fnon_hypothesis': 'Chronic low back pain reflects fear-avoidance behavior driven by SMA-ACC hypervigilance to movement. M1 TPS normalizes motor-pain coupling during movement tasks.',
        },
        {
            'code': 'P4', 'name': 'Migraine / Headache Disorders',
            'sozo_bar': ['CES 20 min', 'tDCS Oz anode', 'TPS occipital', 'Migraine diary'],
            'card_left': ['Network: Occipital hyperexcitability + trigeminovascular', 'Key target: Occipital cortex, ACC', 'Priority: Cortical spreading depression prevention'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C8/F6', 'PlatoScience: C8-PS/FP6', 'Migraine protocol'],
            'brain_targets': [
                ['Occipital cortex', 'Migraine generator', 'Modulate', 'T5 / C8 / FP6', 'Evidence B'],
                ['Trigeminovascular', 'Pain signal', 'Reduce (taVNS)', 'taVNS extended', 'Evidence B'],
                ['ACC', 'Headache affect', 'Modulate', 'T3 / C3', 'Emerging'],
                ['DLPFC', 'Pain control', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Thalamus', 'Pain relay (CES)', 'Modulate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS Oz anode', 'TPS occipital', 'Migraine diary + triggers'],
                ['taVNS 40 min', 'PlatoScience Variant G', 'TPS ACC', 'Relaxation protocol'],
                ['CES 20 min', 'tDCS C8', 'TPS DLPFC', 'Behavioral migraine mgmt'],
                ['taVNS 30 min', 'tDCS F6', 'TPS Oz bilateral', 'Biofeedback thermal'],
            ],
            'task_pairing': 'Migraine diary, trigger avoidance training, thermal biofeedback, relaxation protocol during inter-ictal period.',
            'fnon_hypothesis': 'Migraine reflects occipital cortex hyperexcitability with failure of cortical inhibitory networks. Inter-ictal occipital tDCS + TPS restores inhibitory tone preventing cortical spreading depression.',
        },
        {
            'code': 'P5', 'name': 'Central Sensitization Syndrome',
            'sozo_bar': ['taVNS 30 min', 'tDCS Cz/F3/F4', 'TPS M1+DLPFC+ACC', 'Pain education'],
            'card_left': ['Network: Whole-brain sensitization', 'Key target: M1, DLPFC, ACC, SN nodes', 'Priority: System-wide desensitization'],
            'card_right': ['TPS: FT9 multisite', 'tDCS: C4/F1', 'PlatoScience: C2-PS/FP3', 'CSS protocol'],
            'brain_targets': [
                ['M1 bilateral', 'Analgesic gate', 'Activate', 'T1 / C4 / FP1', 'Evidence A'],
                ['DLPFC', 'Descending inhibition', 'Activate', 'T2 / C2', 'Evidence B'],
                ['SN nodes', 'Sensitization hub', 'Reduce', 'FT3 / F3', 'Emerging'],
                ['ACC', 'Pain amplification', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['Insula', 'Central sensitization', 'Normalize', 'T4 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C4 bilateral', 'TPS M1+DLPFC', 'Pain education program'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS ACC', 'Pacing techniques'],
                ['taVNS 20 min', 'tDCS F1', 'TPS insula', 'Graded activity'],
                ['CES 20 min', 'tDCS Cz', 'TPS SN nodes', 'Acceptance therapy'],
            ],
            'task_pairing': 'Pain neuroscience education, pacing techniques, graded activity program, acceptance-based pain therapy.',
            'fnon_hypothesis': 'Central sensitization reflects network-wide amplification of pain signals with insufficient descending inhibition. Multi-site TPS protocol simultaneously targets M1, DLPFC, and ACC inhibitory pathways.',
        },
        {
            'code': 'P6', 'name': 'Pain + Depression Comorbidity',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode + C3', 'TPS DLPFC+M1', 'BA + movement'],
            'card_left': ['Network: Pain + LIMBIC dysregulation', 'Key target: DLPFC L, M1, amygdala', 'Priority: Unified pain-mood circuit'],
            'card_right': ['TPS: T2+T1 + FT5', 'tDCS: C7/F2', 'PlatoScience: C3-PS/FP5', 'Combined protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood + pain control', 'Activate', 'T2 / C7 / FP5', 'Evidence B'],
                ['M1', 'Pain gate', 'Activate', 'T1 / C1', 'Evidence A'],
                ['ACC', 'Pain-mood junction', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['Amygdala', 'Affect-pain amplify', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['vmPFC', 'Reward + pain', 'Normalize', 'T3 / F3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 F3+C3', 'TPS DLPFC+M1', 'BA + graded movement'],
                ['CES 20 min', 'PlatoScience Variant A+E', 'TPS ACC', 'Pain diary + mood diary'],
                ['taVNS 20 min', 'tDCS F2', 'TPS DLPFC', 'Pleasant activity scheduling'],
                ['CES 20 min', 'tDCS C1', 'TPS M1+amygdala', 'CBT pain-mood'],
            ],
            'task_pairing': 'Behavioral activation combined with graded movement therapy, CBT targeting pain-mood linkages, pleasant activity scheduling.',
            'fnon_hypothesis': 'Pain-depression comorbidity reflects shared DLPFC-ACC circuit dysfunction amplifying both mood and pain signals. Targeting L-DLPFC simultaneously reduces both pain severity and depression.',
        },
        {
            'code': 'P7', 'name': 'Pelvic / Visceral Pain',
            'sozo_bar': ['taVNS 40 min', 'tDCS Cz/insula', 'TPS ACC+insula', 'Pelvic PT'],
            'card_left': ['Network: Visceral-cortical sensitization', 'Key target: Insula, ACC, S1 midline', 'Priority: Visceral cortex desensitization'],
            'card_right': ['TPS: T4 + FT8', 'tDCS: C6/F5', 'PlatoScience: C2-PS/FP5', 'PT + mindfulness'],
            'brain_targets': [
                ['Insula', 'Visceral integration', 'Normalize', 'T4 / C6 / FP5', 'Emerging'],
                ['ACC', 'Visceral affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['S1 midline (Cz)', 'Pelvic somatosensory', 'Normalize', 'TPS Cz', 'Emerging'],
                ['DLPFC', 'Top-down modulation', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Thalamus (CES)', 'Visceral relay', 'Modulate', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C6 insula', 'TPS ACC', 'Pelvic floor PT'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS insula', 'Mindfulness body scan'],
                ['taVNS 40 min', 'tDCS Cz', 'TPS S1 midline', 'Pelvic sensory retraining'],
                ['CES 20 min', 'tDCS F5', 'TPS DLPFC', 'Visceral pain education'],
            ],
            'task_pairing': 'Pelvic floor physiotherapy, mindfulness body scan, visceral pain education, pelvic sensory retraining.',
            'fnon_hypothesis': 'Visceral pain reflects insula-ACC hyperactivation to interoceptive signals. Extended taVNS + insula TPS recalibrates visceral afferent processing threshold.',
        },
        {
            'code': 'P8', 'name': 'Post-Surgical / Cancer Pain',
            'sozo_bar': ['taVNS 30 min', 'tDCS M1 contralateral', 'TPS M1+DLPFC', 'Comfort care task'],
            'card_left': ['Network: Peripheral + central sensitization', 'Key target: M1 contralateral, DLPFC', 'Priority: Analgesic optimization'],
            'card_right': ['TPS: T1+T2 + FT1', 'tDCS: C5/F1', 'PlatoScience: C5-PS/FP1', 'Pain QoL'],
            'brain_targets': [
                ['M1 contralateral', 'Pain gate', 'Activate', 'T1 / C5 / FP1', 'Evidence A'],
                ['DLPFC', 'Opioid-sparing', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Pain affect', 'Normalize', 'T4 / C6', 'Emerging'],
                ['ACC', 'Suffering component', 'Modulate', 'T3 / C3', 'Emerging'],
                ['vmPFC', 'Meaning + hope', 'Support', 'T3 / F3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C5', 'TPS M1', 'Comfort care program'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS DLPFC', 'Meaning-centered therapy'],
                ['taVNS 20 min', 'tDCS F1', 'TPS insula', 'Relaxation + imagery'],
                ['CES 20 min', 'tDCS C1', 'TPS ACC', 'Mindfulness-based pain'],
            ],
            'task_pairing': 'Comfort care program, meaning-centered therapy, relaxation and imagery, mindfulness-based pain management.',
            'fnon_hypothesis': 'Post-surgical pain reflects peripheral sensitization driving central amplification. M1 + DLPFC TPS activates endogenous opioid and serotonergic descending inhibitory pathways.',
        },
        {
            'code': 'P9', 'name': 'Chronic Headache (Tension-Type)',
            'sozo_bar': ['CES 20 min', 'tDCS C3/C4 + Fz', 'TPS M1+ACC', 'Relaxation protocol'],
            'card_left': ['Network: Pericranial sensitization + SN activation', 'Key target: M1, ACC, trigeminovascular', 'Priority: Sensitization reversal'],
            'card_right': ['TPS: T3+T1 + FT3', 'tDCS: C3/F3', 'PlatoScience: C7-PS/FP3', 'Relaxation task'],
            'brain_targets': [
                ['M1 bilateral', 'Pericranial pain gate', 'Activate', 'T1 / C3 / FP3', 'Evidence B'],
                ['ACC', 'Headache affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['SN nodes', 'Sensitization threshold', 'Reduce', 'FT3 / Cz', 'Emerging'],
                ['Trigeminovascular (taVNS)', 'Pain input', 'Block', 'taVNS extended', 'Evidence B'],
                ['DLPFC', 'Analgesic control', 'Activate', 'T2 / C2', 'Evidence B'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C3/Fz', 'TPS M1+ACC', 'Progressive muscle relaxation'],
                ['taVNS 30 min', 'PlatoScience Variant F', 'TPS DLPFC', 'Biofeedback EMG'],
                ['CES 20 min', 'tDCS F3', 'TPS ACC', 'Headache diary + triggers'],
                ['taVNS 20 min', 'tDCS C3', 'TPS M1 bilateral', 'Mindfulness-based stress'],
            ],
            'task_pairing': 'Progressive muscle relaxation, EMG biofeedback, headache diary, trigger identification and avoidance protocol.',
            'fnon_hypothesis': 'Tension-type headache reflects pericranial muscle sensitization with central ACC amplification. M1 TPS + taVNS addresses both peripheral and central components.',
        },
    ],
    'task_pairing_rows': [
        ['Graded exercise', 'Concurrent tDCS', 'Motor', 'P1, P3'],
        ['GMI therapy', 'Post-TPS', 'Motor imagery', 'P2'],
        ['Movement therapy', 'Concurrent tDCS', 'Rehabilitation', 'P3'],
        ['Migraine diary', 'Post-session', 'Monitoring', 'P4'],
        ['Pain education', 'Post-TPS', 'Education', 'P5'],
        ['BA + movement', 'Combined session', 'Dual', 'P6'],
        ['Pelvic PT', 'Concurrent tDCS', 'Physiotherapy', 'P7'],
        ['Comfort care', 'Post-TPS', 'Palliative', 'P8'],
        ['Relaxation', 'During taVNS', 'Behavioral', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'NRS, BPI, PHQ-9', 'Pain intensity + mood', 'Adjust protocol if <20% reduction'],
        ['Week 4', 'NRS, BPI, PSQI', 'Pain + sleep', 'Add sleep protocol if needed'],
        ['Week 6', 'Full pain battery + WHODAS', 'Function + pain', 'Phase 2 decision'],
        ['Week 10', 'NRS, BPI, QoL', 'Long-term pain trajectory', 'Maintenance planning'],
        ['Month 4', 'Full reassessment', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'NRS, BPI, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(3, 2, 3, 4, 3, 3, 5, 3, 4),
}
