"""
Partners-tier All-In-One Protocol data — depression.
Auto-split from partners_all_in_one_data.py. Edit this file to modify depression data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS["depression"] = {
    "display_name": "Major Depressive Disorder (MDD)",
    "short": "Depression",
    "condition_slug": "depression",
    "icd10": "F32 / F33",
    "tps_warning": (
        "TPS use in Major Depressive Disorder is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH® is CE-marked for musculoskeletal indications only. Evidence for depression "
        "is emerging (pilot RCTs, case series). Informed consent and Doctor supervision mandatory."
    ),
    "tps": [
        {"code": "T1", "symptom": "Bilateral DLPFC — Core Mood Regulation",
         "targets": ["F3", "F4", "Fp1"], "evidence": "Level II — Multiple Pilot RCTs",
         "params": "NEUROLITH® · 0.25 mJ/mm² · 1,000 pulses · 5 Hz · bilateral DLPFC",
         "rationale": "Bilateral DLPFC stimulation modulates cortico-limbic mood circuits. Left facilitation + right inhibition mirrors rTMS antidepressant effect. Key evidence: Brunoni 2013 SELECT trial framework."},
        {"code": "T2", "symptom": "sgACC — Anhedonia & Vegetative Features",
         "targets": ["Fz", "Cz", "FCz"], "evidence": "Emerging / Pilot",
         "params": "NEUROLITH® · 0.20 mJ/mm² · 800 pulses · 3 Hz · midline approach",
         "rationale": "Subgenual ACC (Brodmann area 25) is hyperactive in melancholic depression. Midline TPS approach targets sgACC indirectly via mPFC. Reduces anhedonia, vegetative symptoms, and HPA axis dysregulation."},
        {"code": "T3", "symptom": "OFC/vmPFC — Reward Processing & Motivation",
         "targets": ["Fp1", "Fp2", "Fz"], "evidence": "Experimental",
         "params": "NEUROLITH® · 0.20 mJ/mm² · 800 pulses · 3 Hz · orbitofrontal",
         "rationale": "OFC and vmPFC dysfunction underlies reward insensitivity and motivational deficits in MDD. Frontal pole TPS modulates medial prefrontal-limbic loops. Evidence: Padmanabhan 2019 vmPFC review."},
        {"code": "T4", "symptom": "vmPFC / mPFC — Cognitive Reappraisal",
         "targets": ["Fz", "F3", "F4"], "evidence": "Emerging",
         "params": "NEUROLITH® · 0.22 mJ/mm² · 1,000 pulses · 5 Hz · medial frontal",
         "rationale": "vmPFC mediates cognitive reappraisal of negative emotion. Reduced vmPFC-amygdala connectivity perpetuates rumination. TPS at medial frontal scalp promotes top-down emotional regulation."},
        {"code": "T5", "symptom": "Hippocampal Network — Memory & HPA Modulation",
         "targets": ["T3", "T4", "P3"], "evidence": "Experimental / Preliminary",
         "params": "NEUROLITH® · 0.20 mJ/mm² · 600 pulses · 3 Hz · temporal approach",
         "rationale": "Hippocampal volume reduction and neurogenesis impairment are hallmarks of MDD. Temporal TPS targets hippocampal-entorhinal circuits. May support BDNF-mediated neuroplasticity alongside pharmacotherapy."},
    ],
    "fnon_tps": [
        {"code": "FT1", "name": "Melancholic Network Protocol",
         "network": "CEN + LIMBIC", "phenotype": "P1 — Melancholic",
         "targets": ["F3", "F4", "FCz"],
         "params": "0.25 mJ/mm² · 1,200 pulses · 5 Hz · DLPFC bilateral + mPFC",
         "sozo_integration": "tDCS C1 (L-DLPFC anode) → TPS FT1 → taVNS 0.5 mA sustain",
         "rationale": "Melancholic depression is characterised by CEN hypoactivation and LIMBIC hyperconnectivity. FT1 upregulates DLPFC-PPC executive nodes while modulating sgACC-hippocampal limbic loop. Sequential tDCS priming potentiates TPS network effect."},
        {"code": "FT2", "name": "Atypical Mood Reactivity Protocol",
         "network": "LIMBIC + SN", "phenotype": "P2 — Atypical",
         "targets": ["F3", "T3", "T4"],
         "params": "0.22 mJ/mm² · 1,000 pulses · 5 Hz · DLPFC + temporal-limbic",
         "sozo_integration": "CES 100 µA → tDCS C4 (F3-F4) → TPS FT2 → behavioral activation tasks",
         "rationale": "Atypical depression features preserved mood reactivity with rejection sensitivity mediated by SN hyperactivity. FT2 targets temporal-limbic loop to recalibrate SN threat detection and improve interpersonal emotional processing."},
        {"code": "FT3", "name": "Anxious Depression Network Protocol",
         "network": "SN + CEN", "phenotype": "P3 — Anxious",
         "targets": ["F3", "F4", "Cz"],
         "params": "0.22 mJ/mm² · 1,000 pulses · 5 Hz · prefrontal-ACC",
         "sozo_integration": "taVNS 10 min → tDCS C4 → TPS FT3 → mindfulness breathing task",
         "rationale": "Anxious depression involves SN hyperactivity (ACC/insula) co-occurring with CEN dysregulation. FT3 simultaneously targets prefrontal executive and anterior cingulate salience nodes to reduce anxiety-depression overlap."},
        {"code": "FT4", "name": "Treatment-Resistant Depression Protocol",
         "network": "CEN + DMN + LIMBIC", "phenotype": "P4 — Treatment-Resistant",
         "targets": ["F3", "F4", "Fz", "Cz"],
         "params": "0.25 mJ/mm² · 1,200 pulses · 5 Hz · multisite prefrontal",
         "sozo_integration": "CES 300 µA 60 min → tDCS C2 bilateral → TPS FT4 holocranial → taVNS sustain",
         "rationale": "TRD involves widespread network failure across CEN, DMN, and LIMBIC. FT4 uses maximal stimulation with multisite TPS targeting to restore inter-network connectivity. Reserved for confirmed TRD after 2+ failed antidepressant trials."},
        {"code": "FT5", "name": "Psychomotor Retardation Protocol",
         "network": "SMN + CEN", "phenotype": "P5 — Psychomotor-Retarded",
         "targets": ["Cz", "C3", "C4", "F3"],
         "params": "0.25 mJ/mm² · 1,000 pulses · 5 Hz · SMA + M1 + DLPFC",
         "sozo_integration": "tDCS C1 + Cz → TPS FT5 SMA/M1 → motor activation tasks",
         "rationale": "Psychomotor retardation reflects SMA-BG-thalamic circuit hypoactivation. FT5 upregulates SMA and M1 motor initiation circuits alongside DLPFC to restore the cognitive-motor coupling disrupted in this subtype."},
        {"code": "FT6", "name": "Cognitive Depression Protocol",
         "network": "CEN + DMN", "phenotype": "P6 — Cognitive",
         "targets": ["F3", "F4", "P3", "P4"],
         "params": "0.25 mJ/mm² · 1,200 pulses · 5 Hz · DLPFC + PPC",
         "sozo_integration": "tDCS C3 (F3-Pz) → TPS FT6 → cognitive rehabilitation tasks (N-back, verbal fluency)",
         "rationale": "Cognitive depression features DLPFC-PPC CEN hypoactivation with excessive DMN intrusion during task performance. FT6 targets the CEN backbone (DLPFC+PPC) to restore executive-memory function. Pair with neuropsychological rehab tasks."},
        {"code": "FT7", "name": "Insomnia-Depression Protocol",
         "network": "SN + LIMBIC + ATTENTION", "phenotype": "P7 — Insomnia-Predominant",
         "targets": ["Fp1", "Fp2", "Fz"],
         "params": "0.20 mJ/mm² · 800 pulses · 2 Hz · frontal-medial downregulatory",
         "sozo_integration": "CES 100 µA 60 min pre-session → tDCS C6 (sleep montage) → TPS FT7 low-freq · evening only",
         "rationale": "Insomnia-depression involves hyperarousal of SN and limbic circuits preventing sleep initiation. FT7 uses low-frequency TPS (2 Hz inhibitory analog) targeting medial prefrontal-anterior cingulate to downregulate hyperarousal. Evening protocol only."},
        {"code": "FT8", "name": "Anhedonia-Reward Protocol",
         "network": "LIMBIC + CEN", "phenotype": "P8 — Anhedonic",
         "targets": ["Fp1", "Fp2", "F3"],
         "params": "0.22 mJ/mm² · 1,000 pulses · 5 Hz · OFC + vmPFC + DLPFC",
         "sozo_integration": "CES 200 µA → tDCS C8 (motivation montage) → TPS FT8 → reward anticipation tasks",
         "rationale": "Anhedonia reflects OFC-nucleus accumbens reward circuit hypoactivation. FT8 targets OFC and vmPFC to restore reward prediction signalling. Pair with reward anticipation behavioral tasks during the O-outcome phase for conditioned reinforcement."},
        {"code": "FT9", "name": "Somatic-Visceral Depression Protocol",
         "network": "SN + LIMBIC", "phenotype": "P9 — Somatic",
         "targets": ["C3", "C4", "Cz", "Fz"],
         "params": "0.22 mJ/mm² · 1,000 pulses · 5 Hz · insula-ACC-M1",
         "sozo_integration": "taVNS 15 min → tDCS C5 bilateral → TPS FT9 → body-scan mindfulness",
         "rationale": "Somatic depression features insula hyperactivity driving interoceptive amplification of bodily distress. FT9 targets insula (lateral C3/C4 approach) and ACC to downregulate somatic vigilance and fatigue circuits."},
    ],
    "tdcs": [
        {"code": "C1", "symptom": "L-DLPFC — Core Mood Regulation",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params": "2 mA · 30 min | L-DLPFC (F3) anode → R-supraorbital (Fp2) cathode",
         "rationale": "Left DLPFC anodal tDCS (2 mA, 30 min) increases left prefrontal excitability, correcting left-right asymmetry in MDD. Most replicated tDCS antidepressant montage. Evidence: Brunoni 2013 (N=120), Loo 2018 systematic review."},
        {"code": "C2", "symptom": "Bilateral DLPFC — Moderate-Severe Depression",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params": "2 mA · 30 min | Bilateral DLPFC (F3+F4) anode → occipital (Oz) cathode",
         "rationale": "Bilateral DLPFC engagement when unilateral response is insufficient. Occipital cathode placement minimises frontal inhibition. Used for moderate-severe or bilateral affective dysregulation presentations."},
        {"code": "C3", "symptom": "L-DLPFC + PPC — Cognitive Depression",
         "anodes": ["F3"], "cathodes": ["Pz"],
         "params": "2 mA · 25 min | F3 anode → Pz cathode",
         "rationale": "F3-Pz montage targets the CEN backbone, simultaneously facilitating DLPFC and providing mild parietal cathodal inhibition of excess DMN activity. Indicated for cognitive symptoms: impaired concentration, executive dysfunction."},
        {"code": "C4", "symptom": "Asymmetric DLPFC — Anxious Depression",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "2 mA · 25 min | F3 anode, F4 cathode (interhemispheric)",
         "rationale": "Left facilitation with simultaneous right inhibition creates prefrontal asymmetry matching the antidepressant mechanism of rTMS. Particularly effective for anxious depression where right prefrontal hyperactivation drives worry."},
        {"code": "C5", "symptom": "Bilateral DLPFC — Fatigue & Low Energy",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params": "2 mA · 25 min | Bilateral DLPFC → occipital cathode",
         "rationale": "Bilateral prefrontal engagement elevates central arousal and reduces perceived fatigue via corticothalamic upregulation. Evidence supports bilateral montage for energy and motivation deficits in MDD."},
        {"code": "C6", "symptom": "Cathodal Frontal — Insomnia & Hyperarousal",
         "anodes": ["Cz"], "cathodes": ["Fp1", "Fp2"],
         "params": "1.5 mA · 20 min | Cz anode, bilateral frontal cathode | Evening session",
         "rationale": "Bilateral cathodal inhibition of prefrontal hyperarousal circuits reduces rumination-driven insomnia. Lower intensity (1.5 mA) to minimise sleep disruption. Combines with CES Alpha-Stim for enhanced effect."},
        {"code": "C7", "symptom": "Asymmetric Prefrontal — Rumination",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "2 mA · 20 min | F3 anode, F4 cathode | Pair with cognitive defusion tasks",
         "rationale": "Rumination is driven by right DLPFC-mediated DMN hyperconnectivity. Right cathodal inhibition reduces perseverative negative thinking. Pair with acceptance-based cognitive tasks during stimulation for maximal effect."},
        {"code": "C8", "symptom": "L-DLPFC + Cz — Motivation & Reward",
         "anodes": ["F3", "Cz"], "cathodes": ["Oz"],
         "params": "2 mA · 25 min | F3+Cz anode → Oz cathode",
         "rationale": "DLPFC+SMA dual anode upregulates both prefrontal motivational drive and motor initiation circuits. Indicated for psychomotor retardation with pronounced avolition. Pair with behavioral activation tasks."},
    ],
    "fnon_tdcs": [
        {"code": "F1", "name": "CEN Upregulation — Executive & Mood",
         "network": "CEN + LIMBIC",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "2 mA · 30 min | Asymmetric DLPFC | Sessions 1-10 primary",
         "rationale": "CEN upregulation via left DLPFC anodal + right cathodal restores executive-affective balance. The LIMBIC network is secondarily modulated through DLPFC-amygdala top-down connectivity. Core FNON protocol for most MDD phenotypes."},
        {"code": "F2", "name": "DMN Interruption — Rumination Reduction",
         "network": "DMN + CEN",
         "anodes": ["F3", "F4"], "cathodes": ["Pz"],
         "params": "2 mA · 25 min | Bilateral DLPFC anode, parietal cathode",
         "rationale": "DMN hyperconnectivity (especially PCC-mPFC) underlies rumination. Bilateral DLPFC anodal stimulation combined with parietal cathodal inhibition reduces DMN anchoring at PCC. Evidence: Liston 2014 DLPFC-DMN connectivity data."},
        {"code": "F3", "name": "SN Downregulation — Anxiety-Depression",
         "network": "SN + LIMBIC",
         "anodes": ["Fz"], "cathodes": ["Oz"],
         "params": "1.5 mA · 20 min | Medial frontal anode, occipital cathode",
         "rationale": "SN hyperactivity (ACC/anterior insula) drives the anxiety component of mixed anxiety-depression. Medial frontal (vmPFC/ACC approach) anodal tDCS promotes top-down SN regulation while occipital cathode serves as remote reference."},
        {"code": "F4", "name": "LIMBIC Reset — Anhedonia & Reward",
         "network": "LIMBIC + CEN",
         "anodes": ["Fp1", "Fp2"], "cathodes": ["Cz"],
         "params": "1.5 mA · 20 min | Bilateral orbitofrontal anode, vertex cathode",
         "rationale": "OFC and vmPFC (medial limbic nodes) directly modulate nucleus accumbens reward signalling. Bilateral orbitofrontal anodal tDCS with vertex cathode targets the reward circuit for anhedonia. Use with reward-based behavioral tasks."},
        {"code": "F5", "name": "CEN + SMN — Psychomotor Activation",
         "network": "CEN + SMN",
         "anodes": ["F3", "Cz"], "cathodes": ["Oz"],
         "params": "2 mA · 25 min | F3+Cz dual anode, occipital cathode",
         "rationale": "Psychomotor retardation reflects CEN-SMN disconnection. F3+Cz dual anode simultaneously facilitates DLPFC cognitive drive and SMA motor initiation, restoring the motor-executive coupling disrupted by depression."},
        {"code": "F6", "name": "ATTENTION Activation — Concentration Deficit",
         "network": "ATTENTION + CEN",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params": "2 mA · 20 min | R-DLPFC anode (DAN node), left supraorbital cathode",
         "rationale": "Dorsal attention network (DAN: FEF, IPS) hypofunction causes the concentration and sustained attention deficits in cognitive depression. R-DLPFC is a key DAN hub. This montage upregulates right-lateralised attention circuits."},
    ],
    "plato": [
        {"code": "C1-PS", "symptom": "L-DLPFC — Core Mood",
         "variant": "Variant A (Fp1-F3)", "program": "Mood+",
         "anodes": ["F3"], "cathodes": ["Fp1"],
         "params": "1.5 mA · 20 min | PlatoWork Variant A",
         "rationale": "Closest PlatoScience approximation of the gold-standard L-DLPFC antidepressant montage. Variant A positions the active electrode over left prefrontal cortex."},
        {"code": "C2-PS", "symptom": "Bilateral DLPFC — Moderate Depression",
         "variant": "Variant C (F3-F4)", "program": "Mood+",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "1.5 mA · 20 min | PlatoWork Variant C",
         "rationale": "Bilateral prefrontal engagement via PlatoWork Variant C for moderate-severe presentations. Single-channel limitation means sequential sessions (left then right) may be prescribed."},
        {"code": "C3-PS", "symptom": "Cognition — Concentration & Executive",
         "variant": "Variant D (F3-P3)", "program": "Focus",
         "anodes": ["F3"], "cathodes": ["P3"],
         "params": "1.5 mA · 20 min | PlatoWork Variant D",
         "rationale": "Frontoparietal CEN targeting via Variant D for cognitive symptoms. Supports working memory and concentration during cognitive rehabilitation tasks."},
        {"code": "C4-PS", "symptom": "Anxious Depression — SN Modulation",
         "variant": "Variant B (Fp2-F4)", "program": "Calm",
         "anodes": ["Fp2"], "cathodes": ["F4"],
         "params": "1.5 mA · 20 min | PlatoWork Variant B (right frontal, cathodal dominant effect)",
         "rationale": "Right prefrontal cathodal inhibition via Variant B reduces right-lateralised hyperactivation driving anxious depression. Calm program maps closest to the inhibitory montage needed."},
        {"code": "C5-PS", "symptom": "Fatigue & Low Energy",
         "variant": "Variant A (Fp1-F3)", "program": "Energy",
         "anodes": ["F3"], "cathodes": ["Fp1"],
         "params": "1.5 mA · 20 min | PlatoWork Variant A — morning sessions preferred",
         "rationale": "Left prefrontal upregulation with Energy program to combat central fatigue. Morning administration maximises circadian alignment with prefrontal energisation."},
        {"code": "C6-PS", "symptom": "Insomnia & Hyperarousal",
         "variant": "Variant B (Fp2-F4)", "program": "Sleep",
         "anodes": ["Fp2"], "cathodes": ["F4"],
         "params": "1.5 mA · 20 min | PlatoWork Variant B — evening only (90 min before sleep)",
         "rationale": "Evening cathodal frontal inhibition to reduce pre-sleep hyperarousal and rumination. Sleep program provides the appropriate inhibitory parameters. Strict evening-only prescription."},
        {"code": "C7-PS", "symptom": "Rumination Reduction",
         "variant": "Variant C (F3-F4)", "program": "Calm",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "1.5 mA · 20 min | PlatoWork Variant C | Pair with mindfulness task",
         "rationale": "Interhemispheric asymmetric montage to reduce rumination. Pair with guided mindfulness or cognitive defusion task during stimulation for conditioned inhibitory effect."},
        {"code": "C8-PS", "symptom": "Motivation & Avolition",
         "variant": "Variant A (Fp1-F3)", "program": "Performance",
         "anodes": ["F3"], "cathodes": ["Fp1"],
         "params": "1.5 mA · 20 min | PlatoWork Variant A | Pair with behavioral activation",
         "rationale": "Left DLPFC upregulation to restore motivational drive. Performance program maximises anodal current at F3. Mandatory pairing with behavioral activation scheduling during the stimulation session."},
    ],
    "fnon_plato": [
        {"code": "FP1", "name": "CEN Upregulation — Mood/Executive",
         "derived": "F1", "variant": "Variant A", "program": "Mood+",
         "network": "CEN + LIMBIC",
         "params": "1.5 mA · 20 min | PlatoWork Variant A",
         "rationale": "Home-adapted F1 protocol targeting CEN via left DLPFC. Mood+ program provides asymmetric prefrontal facilitation compatible with F1 network goals."},
        {"code": "FP2", "name": "DMN Interruption — Rumination",
         "derived": "F2", "variant": "Variant D", "program": "Focus",
         "network": "DMN + CEN",
         "params": "1.5 mA · 20 min | PlatoWork Variant D",
         "rationale": "Frontoparietal Variant D approximates the bilateral DLPFC + parietal cathode of F2. Focus program drives CEN upregulation to interrupt DMN rumination loop."},
        {"code": "FP3", "name": "SN Downregulation — Anxiety",
         "derived": "F3", "variant": "Variant B", "program": "Calm",
         "network": "SN + LIMBIC",
         "params": "1.5 mA · 20 min | PlatoWork Variant B (right frontal cathodal)",
         "rationale": "Right cathodal via Variant B mimics the SN downregulatory effect of F3. Calm program parameters match the low-intensity inhibitory approach needed for SN modulation."},
        {"code": "FP4", "name": "LIMBIC Reset — Anhedonia",
         "derived": "F4", "variant": "Variant G", "program": "Mood+",
         "network": "LIMBIC + CEN",
         "params": "1.5 mA · 20 min | PlatoWork Variant G (Fz-Cz midline)",
         "rationale": "Midline Variant G approximates medial prefrontal targeting for limbic/OFC reward circuits. Mood+ provides anodal facilitation at the mPFC approach."},
        {"code": "FP5", "name": "CEN+SMN — Psychomotor Activation",
         "derived": "F5", "variant": "Variant E", "program": "Performance",
         "network": "CEN + SMN",
         "params": "1.5 mA · 20 min | PlatoWork Variant E (C3-Cz)",
         "rationale": "Variant E (centroparietal) targets SMA and motor initiation circuits. Performance program drives the motor-executive activation needed for psychomotor retardation subtype."},
        {"code": "FP6", "name": "ATTENTION Activation",
         "derived": "F6", "variant": "Variant B", "program": "Focus",
         "network": "ATTENTION + CEN",
         "params": "1.5 mA · 20 min | PlatoWork Variant B (right prefrontal)",
         "rationale": "Right prefrontal Variant B targets right DAN nodes for attention upregulation. Focus program provides the anodal facilitation needed to restore sustained attention in cognitive depression."},
    ],
    "plato_programs": _plato_programs_default(
        "Attention, concentration, executive function deficits in MDD",
        "Cognitive depression, encoding difficulties",
        "Core MDD, low mood, motivational deficits",
        "Anxious depression, pre-sleep hyperarousal",
        "Fatigue subtype, psychomotor retardation",
        "Insomnia-predominant MDD, evening protocol",
        "Somatic depression, pain comorbidity",
        "Melancholic/anhedonic MDD",
        "Post-session recovery, treatment-resistant MDD adjunct",
    ),
    "phenotypes": [
        {
            "code": "P1", "ft_code": "FT1", "name": "Melancholic",
            "sozo_bar": {
                "S": "taVNS 0.5 mA · 15 min\nDownshift HPA axis; reduce cortical noise; prime limbic system",
                "O": "tDCS C1 (L-DLPFC) · 30 min\nPrefrontal facilitation; LIMBIC top-down priming",
                "Z": "TPS FT1 · 1,200 pulses · 5 Hz\nBilateral DLPFC + mPFC deep network reset",
                "O2": "taVNS sustain + BA tasks · 30 min\nBehavioral activation; reward scheduling; consolidate plasticity",
            },
            "card_left": "P1 — Melancholic\nFT1 Network Protocol\n\nModalities:\ntDCS C1\nTPS FT1\ntaVNS + CES\n\nTargets:\nBilateral DLPFC\nsgACC / mPFC\nHippocampus",
            "card_right": "TPS: 0.25 mJ/mm² · 1,200 pulses · 5 Hz · DLPFC bilateral\ntDCS: C1 — 2 mA · 30 min · F3 anode, Fp2 cathode\ntaVNS: 0.5 mA · 15 min (S-phase) + 30 min (O-outcome)\nCES: 100 µA · 60 min (concurrent with tDCS or stand-alone)\nSession frequency: Daily × 10, then 3×/week\nPrimary scale: MADRS · Secondary: PHQ-9, CGI-S",
            "brain_targets": [
                ("L-DLPFC (F3)", "Primary target: upregulate CEN; restore executive-affective control; replicate rTMS antidepressant effect"),
                ("R-DLPFC (F4)", "Secondary: bilateral facilitation in melancholic subtype; address anhedonic + vegetative features"),
                ("sgACC / mPFC (Fz/FCz)", "Core dysfunction node in melancholic depression; hyperactive sgACC drives vegetative symptoms and HPA dysregulation"),
                ("Hippocampus (temporal approach)", "Neurogenesis support; stress hormone regulation; episodic memory consolidation impaired by chronic cortisol elevation"),
                ("vmPFC / OFC (Fp1-Fp2)", "Reward prediction; motivation; emotional valence assignment — hypoactive in melancholic subtype"),
            ],
            "combinations": [
                ("TPS FT1 + tDCS C1 (sequential)", "Temporal summation: tDCS primes DLPFC excitability; TPS achieves deeper network penetration post-priming", "tDCS 30 min → TPS 20 min (within 5 min)", "Moderate-to-severe melancholic MDD; first-line FNON approach"),
                ("tDCS C1 + taVNS (concurrent)", "Vagal upregulation augments prefrontal anodal effect; anti-inflammatory + LC-NE pathway activation", "Simultaneous 20-30 min", "Melancholic with somatic comorbidity or inflammatory markers"),
                ("TPS FT1 + CES (cross-modal)", "CES Alpha-Stim reduces frontal hyperarousal; TPS provides focal DLPFC reset; non-overlapping mechanisms", "CES 60 min pre-session; TPS same day", "Treatment-resistant melancholic; insufficient response to standard montage"),
                ("Full S-O-Z-O quad", "Complete neuromodulation cascade: ANS stabilisation → cortical priming → deep network reset → plasticity consolidation", "Sequential 90-min session", "Severe melancholic MDD; TRD with preserved insight"),
            ],
            "task_pairing": "Behavioral Activation (BA) tasks during O-outcome phase: activity scheduling, pleasant event identification, reward anticipation exercises. Aim: condition prefrontal reward circuits during post-TPS plasticity window. Duration 30 min. Therapist-guided or app-based.",
            "fnon_hypothesis": "Melancholic depression reflects CEN hypoactivation (reduced DLPFC-PPC connectivity) combined with LIMBIC hyperconnectivity (sgACC-amygdala-hippocampal overdrive). TPS FT1 targets CEN backbone while simultaneously modulating limbic loop via indirect mPFC approach. tDCS C1 pre-priming enhances TPS penetration depth effect. taVNS provides bottom-up vagal-LC-NE augmentation of the top-down stimulation cascade.",
        },
        {
            "code": "P2", "ft_code": "FT2", "name": "Atypical",
            "sozo_bar": {
                "S": "CES 100 µA · 15 min\nStabilise mood reactivity; reduce emotional lability baseline",
                "O": "tDCS C4 (F3-F4 asymmetric) · 25 min\nPrefrontal asymmetry; SN recalibration",
                "Z": "TPS FT2 · 1,000 pulses · 5 Hz\nTemporal-limbic SN + LIMBIC reset",
                "O2": "taVNS + interpersonal tasks · 30 min\nRejection sensitivity retraining; social reward exposure",
            },
            "card_left": "P2 — Atypical\nFT2 Network Protocol\n\nModalities:\ntDCS C4\nTPS FT2\nCES + taVNS\n\nTargets:\nSN (ACC/insula)\nLIMBIC (amygdala)\nDLPFC bilateral",
            "card_right": "TPS: 0.22 mJ/mm² · 1,000 pulses · 5 Hz · temporal-limbic\ntDCS: C4 — 2 mA · 25 min · F3 anode, F4 cathode\nCES: 100 µA · 15 min (S-phase stabilisation)\ntaVNS: 0.5 mA · 30 min (O-outcome phase)\nSession frequency: Daily × 10, then 3×/week\nPrimary scale: HDRS-A · Secondary: IDS-SR, rejection sensitivity scale",
            "brain_targets": [
                ("L-DLPFC (F3)", "Executive control over mood reactivity; prefrontal regulation of limbic responses to rejection"),
                ("R-DLPFC (F4) — cathodal", "Inhibit right prefrontal hyperactivation driving hypersensitivity and excessive social monitoring"),
                ("ACC / SN (Cz/FCz area)", "Salience Network hub — dysregulated in atypical depression; drives rejection sensitivity and mood over-reactivity"),
                ("Amygdala (temporal T3/T4)", "Emotional threat detection hyperactivation; fear of abandonment; interpersonal hypersensitivity"),
                ("Insula (C3/C4 lateral)", "Somatic awareness and rejection pain signal amplification — key interoceptive node in atypical subtype"),
            ],
            "combinations": [
                ("tDCS C4 + taVNS (concurrent)", "Asymmetric prefrontal + vagal anti-rejection effect; reduces autonomic signature of social rejection", "Simultaneous 25 min", "Atypical with prominent rejection sensitivity/interpersonal deficits"),
                ("TPS FT2 + CES (pre+during)", "CES stabilises emotional lability before TPS deep limbic reset", "CES 15 min → TPS 20 min same session", "Atypical with high emotional instability or borderline features"),
                ("tDCS C4 + TPS FT2 (sequential)", "Cortical priming + deep temporal-limbic TPS targeting", "tDCS 25 min → TPS 20 min", "Moderate atypical depression with interpersonal dysfunction"),
                ("Full quad", "Complete FNON cascade with social reward conditioning in O-outcome", "Sequential 90-min session", "Severe atypical MDD with marked functional impairment"),
            ],
            "task_pairing": "Interpersonal reward tasks during O-outcome phase: positive social memory recall, perspective-taking exercises, graduated social exposure hierarchy. Targets rejection sensitivity retraining at peak SN plasticity window. 30 min, guided by clinical psychologist.",
            "fnon_hypothesis": "Atypical depression features preserved mood reactivity mediated by SN hypersensitivity (ACC-amygdala-insula hyperconnectivity) rather than the global hypoactivation of melancholic subtype. TPS FT2 targets temporal-limbic SN nodes to recalibrate threat-detection thresholds. tDCS C4 asymmetric montage restores prefrontal top-down control over limbic emotional reactivity.",
        },
        {
            "code": "P3", "ft_code": "FT3", "name": "Anxious Depression",
            "sozo_bar": {
                "S": "taVNS 0.5 mA · 15 min\nActivate vagal brake; reduce sympathetic tone; lower anxiety baseline",
                "O": "tDCS C4 (F3-F4) · 25 min\nSN downregulation; prefrontal anxiety control",
                "Z": "TPS FT3 · 1,000 pulses · 5 Hz\nPrefrontal-ACC SN reset",
                "O2": "taVNS + breathing tasks · 30 min\nAnxiety habituation; vagal conditioning",
            },
            "card_left": "P3 — Anxious Depression\nFT3 Network Protocol\n\nModalities:\ntDCS C4\nTPS FT3\ntaVNS\n\nTargets:\nSN (ACC/insula)\nCEN (DLPFC)\nLIMBIC (amygdala)",
            "card_right": "TPS: 0.22 mJ/mm² · 1,000 pulses · 5 Hz · prefrontal-ACC\ntDCS: C4 — 2 mA · 25 min · F3 anode, F4 cathode\ntaVNS: 0.5 mA · 15 min pre + 30 min post\nSession frequency: Daily × 10, then 3×/week\nPrimary scale: HADS-A + MADRS · Secondary: GAD-7, PHQ-9",
            "brain_targets": [
                ("L-DLPFC (F3)", "Top-down anxiety control; cognitive reappraisal of threat; executive override of amygdala fear response"),
                ("R-DLPFC (F4) — cathodal", "Reduce right prefrontal hyperactivation fuelling worry and anticipatory anxiety in anxious depression"),
                ("ACC / dACC (Cz/FCz)", "SN hub — hyperactive in anxious depression; conflict monitoring driving excessive worry and ruminative loops"),
                ("Amygdala (temporal)", "Fear conditioning and threat amplification; primary driver of somatic anxiety symptoms"),
                ("Insula (C3/C4)", "Interoceptive amplification of anxiety signals; somatic awareness hyperactivation; panic physiology"),
            ],
            "combinations": [
                ("taVNS + tDCS C4 (concurrent)", "Vagal activation reduces autonomic arousal while prefrontal tDCS increases top-down control", "Simultaneous 25 min", "Anxious depression with somatic anxiety, autonomic instability"),
                ("TPS FT3 + tDCS C4 (sequential)", "tDCS primes DLPFC; TPS achieves ACC/SN deep network reset", "tDCS 25 min → TPS 20 min", "Moderate anxious depression; first-line FNON approach"),
                ("CES + taVNS (pre-session)", "Dual autonomic stabilisation before cortical stimulation", "CES 60 min + taVNS 15 min pre-session", "Severe anxious depression with high somatic burden"),
                ("Full quad", "Complete cascade with anxiety habituation tasks", "Sequential 90-min session", "TRD anxious subtype; panic-prone presentation"),
            ],
            "task_pairing": "Anxiety habituation tasks during O-outcome phase: paced diaphragmatic breathing (4-7-8 pattern), brief interoceptive exposure exercises, worry postponement scheduling. Aim: pair prefrontal upregulation with anxiety reduction conditioning. Duration 30 min.",
            "fnon_hypothesis": "Anxious depression involves co-occurring SN hyperactivity (ACC-insula overdrive generating anxiety) and CEN hypoactivation (DLPFC failure to regulate amygdala/SN). TPS FT3 targets the ACC-prefrontal junction to simultaneously downregulate SN and upregulate CEN. taVNS provides bottom-up vagal brake via nucleus tractus solitarius-LC-prefrontal pathway.",
        },
        {
            "code": "P4", "ft_code": "FT4", "name": "Treatment-Resistant Depression",
            "sozo_bar": {
                "S": "CES 300 µA · 60 min\nMaximal autonomic stabilisation; prepare refractory neural substrate",
                "O": "tDCS C2 (bilateral DLPFC) · 30 min\nBilateral prefrontal priming",
                "Z": "TPS FT4 · 1,200 pulses · 5 Hz · multisite\nComprehensive network reset: CEN + DMN + LIMBIC",
                "O2": "taVNS + CES + motivational tasks · 45 min\nMulti-modal plasticity consolidation",
            },
            "card_left": "P4 — Treatment-Resistant\nFT4 Network Protocol\n\nModalities:\ntDCS C2\nTPS FT4\nCES 300 µA\ntaVNS\n\nTargets:\nCEN + DMN + LIMBIC\nMultisite prefrontal",
            "card_right": "TPS: 0.25 mJ/mm² · 1,200 pulses · 5 Hz · bilateral DLPFC + mPFC\ntDCS: C2 — 2 mA · 30 min · bilateral DLPFC (F3+F4), Oz cathode\nCES: Alpha-Stim 300 µA · 60 min (pre-session + concurrent)\ntaVNS: 0.5 mA · 15 min + 45 min (full O2 phase)\nSessions: Daily × 20 intensive; reassess at 10-session midpoint\nPrimary scale: MADRS · Require ≥2 failed antidepressants for TRD classification",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Simultaneous bilateral CEN facilitation to overcome treatment resistance; mirror ECT's bilateral effect with safety of NIBS"),
                ("sgACC / mPFC (Fz)", "Core TRD node — hyperactive sgACC maintains depressogenic state despite pharmacotherapy; requires deep reset"),
                ("Anterior cingulate (Cz/FCz)", "ACC mediates treatment response; ACC dysfunction predicts non-response to antidepressants"),
                ("Hippocampus (T3/T4)", "Chronic cortisol-mediated hippocampal atrophy in TRD; neurogenesis support via BDNF pathway stimulation"),
                ("vmPFC / OFC (Fp1-Fp2)", "Reward and motivation circuits — severely impaired in TRD; OFC-sgACC hyperloop perpetuates depression"),
            ],
            "combinations": [
                ("TPS FT4 + bilateral tDCS C2", "Bilateral network approach for TRD: maximal CEN upregulation with deep multisite TPS", "tDCS 30 min → TPS 25 min", "Confirmed TRD (≥2 failed antidepressant trials); severe MDD"),
                ("CES 300 µA + taVNS (pre + concurrent)", "Dual autonomic + vagal pathway activation to prime refractory brain for cortical stimulation", "CES 60 min pre + taVNS concurrent with tDCS", "TRD with inflammatory/autonomic features; augmentation of pharmacotherapy"),
                ("Ketamine + NIBS (same-day protocol)", "Ketamine NMDA antagonism + cortical NIBS during enhanced plasticity window", "NIBS within 4 hours of IV/IN ketamine", "TRD with ketamine responders; specialist setting only — Doctor decision"),
                ("Full quad × 20 sessions intensive", "Complete 90-min multimodal cascade daily for 4 weeks", "Daily × 20 sessions", "Severe TRD; inpatient or intensive outpatient programme"),
            ],
            "task_pairing": "Motivational interviewing + behavioral activation tasks during O-outcome phase. Graduated activity scheduling targeting highest reward-to-effort ratio activities. Pair with positive future-directed imagery. Duration 45 min. Psychologist supervision required for TRD protocol.",
            "fnon_hypothesis": "TRD reflects multi-network failure: CEN hypoactivation, DMN hyperconnectivity, LIMBIC dysregulation, and SN miscalibration creating a self-reinforcing depressogenic state. FT4 applies maximal bilateral stimulation to break the network lock. CES + taVNS address the bottom-up autonomic and neuroimmune components that pharmacotherapy alone cannot reach.",
        },
        {
            "code": "P5", "ft_code": "FT5", "name": "Psychomotor Retardation",
            "sozo_bar": {
                "S": "taVNS 0.5 mA · 10 min\nActivate LC-NE system; increase cortical arousal",
                "O": "tDCS C8 (F3+Cz) · 25 min\nDLPFC + SMA dual activation; motor initiation priming",
                "Z": "TPS FT5 · 1,000 pulses · 5 Hz · SMA+M1+DLPFC\nMotor-executive circuit reset",
                "O2": "Motor activation tasks · 30 min\nWalking, tapping tasks; condition motor initiation during plasticity",
            },
            "card_left": "P5 — Psychomotor Retarded\nFT5 Network Protocol\n\nModalities:\ntDCS C8\nTPS FT5\ntaVNS\n\nTargets:\nSMN (SMA/M1)\nCEN (DLPFC)\nBG-thalamic circuit",
            "card_right": "TPS: 0.25 mJ/mm² · 1,000 pulses · 5 Hz · SMA+M1+DLPFC\ntDCS: C8 — 2 mA · 25 min · F3+Cz anode, Oz cathode\ntaVNS: 0.5 mA · 10 min (S-phase arousal activation)\nSession: Daily × 10; pair with physiotherapy tasks\nPrimary scale: UPDRS-III (motor items) + MADRS-motor items",
            "brain_targets": [
                ("SMA (Cz/FCz)", "Supplementary motor area — primary motor initiation and planning; hypoactive in psychomotor retardation"),
                ("M1 bilateral (C3/C4)", "Primary motor output; reduced corticospinal drive in psychomotor depression"),
                ("L-DLPFC (F3)", "Executive motivation and action initiation; DLPFC-SMA pathway disrupted in psychomotor retardation"),
                ("Basal ganglia circuit (frontal approach)", "BG-thalamic loop hypofunction drives bradyphrenia and akinesia in severe MDD"),
                ("Cerebellum (indirect)", "Timing and rhythm of motor sequences; cerebellar-thalamic-cortical loop modulation via SMA stimulation"),
            ],
            "combinations": [
                ("tDCS C8 + motor tasks (concurrent)", "Cortical facilitation during active motor rehearsal maximises use-dependent plasticity", "tDCS 25 min during treadmill/walking task", "Psychomotor retardation with bradyphrenia; avolition"),
                ("TPS FT5 + tDCS C8 (sequential)", "SMA/M1 deep TPS after tDCS priming for maximal motor circuit activation", "tDCS 25 min → TPS 20 min", "Moderate-severe psychomotor retardation"),
                ("taVNS + tDCS C8 (concurrent)", "LC-NE pathway activation augments motor cortex excitability", "Simultaneous 25 min", "Psychomotor retardation with fatigue and low arousal"),
                ("Full quad with physiotherapy", "Motor rehabilitation integrated into O-outcome phase", "90 min session with physiotherapist in O-outcome", "Severe psychomotor retardation; functional impairment"),
            ],
            "task_pairing": "Motor activation tasks during O-outcome: rhythmic tapping to metronome (1 Hz), treadmill walking at comfortable pace, arm swing exercises. Goal: condition motor initiation circuits during peak plasticity window. 30 min with physiotherapist or structured protocol.",
            "fnon_hypothesis": "Psychomotor retardation in MDD reflects CEN-SMN disconnection: DLPFC fails to drive SMA motor initiation, and reduced BG dopaminergic signalling compounds the deficit. FT5 directly targets the SMA-DLPFC motor-executive junction. taVNS activates the LC-NE system to provide catecholaminergic support for motor circuit restoration.",
        },
        {
            "code": "P6", "ft_code": "FT6", "name": "Cognitive Depression",
            "sozo_bar": {
                "S": "CES 100 µA · 15 min\nReduce cognitive noise; stabilise frontal alpha",
                "O": "tDCS C3 (F3-Pz) · 25 min\nCEN upregulation; DLPFC-PPC priming",
                "Z": "TPS FT6 · 1,200 pulses · 5 Hz\nDLPFC+PPC network reset; DMN suppression",
                "O2": "Cognitive rehab tasks · 35 min\nN-back, verbal fluency, attention training",
            },
            "card_left": "P6 — Cognitive Depression\nFT6 Network Protocol\n\nModalities:\ntDCS C3\nTPS FT6\nCES\n\nTargets:\nCEN (DLPFC+PPC)\nDMN suppression\nAttention networks",
            "card_right": "TPS: 0.25 mJ/mm² · 1,200 pulses · 5 Hz · DLPFC+PPC\ntDCS: C3 — 2 mA · 25 min · F3 anode, Pz cathode\nCES: 100 µA · 15 min (pre-session cognitive noise reduction)\nSession: 3–5×/week × 4 weeks\nPrimary scale: CANTAB cognitive battery + MADRS-cognition items",
            "brain_targets": [
                ("L-DLPFC (F3)", "CEN hub — working memory, attention, executive control; consistently hypoactive in cognitive depression"),
                ("PPC / parietal (Pz/P3)", "Posterior CEN node — spatial attention, task-set maintenance; cathodal inhibition reduces DMN-PCC anchor"),
                ("DMN — PCC (indirect via parietal cathode)", "Posterior cingulate cortex over-activation in cognitive depression competes with task-positive CEN; parietal cathode disrupts PCC-DMN coupling"),
                ("Anterior cingulate (Cz)", "Task-monitoring and error detection; ACC hypofunction underlies poor cognitive effort allocation"),
                ("Hippocampus (temporal approach T3)", "Episodic memory encoding failure; hippocampal hypoactivation in depressive cognitive impairment"),
            ],
            "combinations": [
                ("tDCS C3 + cognitive tasks (concurrent)", "CEN facilitation during active cognitive challenge — use-dependent DLPFC plasticity", "tDCS 25 min concurrent with N-back or verbal fluency", "Cognitive depression; pseudodementia presentation"),
                ("TPS FT6 + tDCS C3 (sequential)", "DLPFC+PPC deep network reset after cortical priming", "tDCS 25 min → TPS 20 min", "Moderate-severe cognitive MDD"),
                ("CES + tDCS C3 (pre + concurrent)", "CES reduces cognitive noise; tDCS directs facilitation to CEN", "CES 15 min pre → tDCS 25 min", "Cognitive MDD with high ruminative interference during tasks"),
                ("Full quad with neuropsychological rehab", "Complete FNON cascade with structured cognitive rehabilitation", "90-min session with neuropsychologist", "Moderate-severe cognitive depression; pseudodementia differential"),
            ],
            "task_pairing": "Neuropsychological rehabilitation tasks during O-outcome: N-back (2-back standard), verbal fluency (category and letter), Trails B, brief attention training (sustained attention reaction time). 35 min structured cognitive rehabilitation programme. Neuropsychologist supervision recommended.",
            "fnon_hypothesis": "Cognitive depression represents CEN hypoactivation with pathological DMN intrusion during task performance. Patients cannot suppress default mode rumination to engage executive circuits. TPS FT6 targets the DLPFC-PPC CEN backbone while tDCS C3 parietal cathode disrupts the PCC-DMN anchor. CES pre-session reduces background cognitive noise to maximise signal-to-noise of CEN stimulation.",
        },
        {
            "code": "P7", "ft_code": "FT7", "name": "Insomnia-Predominant",
            "sozo_bar": {
                "S": "CES 100 µA · 60 min (evening)\nMaximal pre-sleep autonomic stabilisation",
                "O": "tDCS C6 (cathodal frontal) · 20 min\nReduce prefrontal hyperarousal; slow oscillation induction",
                "Z": "TPS FT7 · 800 pulses · 2 Hz (low-freq) · evening\nDownregulatory frontal-medial TPS; SN inhibition",
                "O2": "Sleep hygiene + relaxation · 30 min\nSleep onset conditioning; cognitive-somatic relaxation",
            },
            "card_left": "P7 — Insomnia-Predominant\nFT7 Network Protocol\n\nModalities:\ntDCS C6\nTPS FT7\nCES 100 µA\n\nTargets:\nFrontal hyperarousal\nSN downregulation\nSleep onset circuits",
            "card_right": "TPS: 0.20 mJ/mm² · 800 pulses · 2 Hz · medial frontal · EVENING ONLY\ntDCS: C6 — 1.5 mA · 20 min · bilateral frontal cathode, Cz anode · evening\nCES: 100 µA · 60 min (concurrent with tDCS or pre-sleep stand-alone)\nSession: 5×/week × 3 weeks; evening administration mandatory (90 min before sleep)\nPrimary scale: ISI · Secondary: PSQI, sleep diary actigraphy",
            "brain_targets": [
                ("Bilateral prefrontal (Fp1+Fp2)", "Hyperarousal hub — cathodal inhibition reduces pre-sleep cognitive activation and rumination"),
                ("ACC / dACC (Fz/Cz)", "Sleep-wake conflict monitoring; ACC hyperactivity prevents sleep onset in MDD-insomnia"),
                ("Thalamus (midline approach)", "Thalamocortical arousal regulation; indirect modulation via midline stimulation"),
                ("mPFC / vmPFC (Fz)", "SN anchor node — vmPFC inhibition reduces self-referential hyperarousal maintaining insomnia"),
                ("LC-NE system (taVNS indirect)", "Noradrenergic arousal system — taVNS modulates LC activity to support sleep transition"),
            ],
            "combinations": [
                ("CES + cathodal tDCS C6 (concurrent, evening)", "Dual downregulatory approach: CES general arousal reduction + cathodal prefrontal inhibition", "Evening: CES 60 min; tDCS last 20 min concurrent", "Insomnia-MDD; hyperarousal phenotype; sleep onset difficulty"),
                ("TPS FT7 (low-freq) + CES (same evening)", "Low-frequency TPS inhibitory analog + CES; do not combine with standard antidepressant TPS same session", "TPS first; CES 30 min before sleep", "Severe insomnia-MDD; treatment-resistant insomnia component"),
                ("taVNS evening + CES", "Vagal brake activation to reduce autonomic arousal before sleep", "taVNS 15 min + CES 45 min, 90 min pre-sleep", "Insomnia with autonomic hyperarousal, elevated heart rate variability deficit"),
                ("Sleep restriction + NIBS combo", "Sleep consolidation protocol: tDCS C6 on sleep restriction nights to enhance slow-wave induction", "Evening NIBS on sleep restriction nights", "Paradoxical insomnia; sleep state misperception"),
            ],
            "task_pairing": "Sleep hygiene + relaxation tasks during O-outcome phase: progressive muscle relaxation (PMR), stimulus control instruction, sleep hygiene checklist review, cognitive defusion for sleep-related worry. No screens. Dim lighting. Duration 30 min. CBT-I framework integration recommended.",
            "fnon_hypothesis": "Insomnia-predominant MDD involves SN hyperactivation (ACC-insula arousal loop) and frontal hyperarousal preventing sleep onset. Unlike primary insomnia, the driving force is depressogenic rumination maintaining default-mode hyperconnectivity at sleep time. TPS FT7 uses low-frequency parameters to inhibit (rather than facilitate) medial frontal-ACC SN nodes. Evening-only protocol respects circadian biology.",
        },
        {
            "code": "P8", "ft_code": "FT8", "name": "Anhedonic",
            "sozo_bar": {
                "S": "CES 200 µA · 15 min\nBaseline hedonic stabilisation; reduce anhedonic affect",
                "O": "tDCS C8 (F3+Cz motivation) · 25 min\nOFC/DLPFC reward circuit priming",
                "Z": "TPS FT8 · 1,000 pulses · 5 Hz · OFC+DLPFC\nReward circuit deep reset; NAc pathway modulation",
                "O2": "Reward anticipation tasks · 30 min\nConditioning reward prediction; behavioral activation",
            },
            "card_left": "P8 — Anhedonic\nFT8 Network Protocol\n\nModalities:\ntDCS C8\nTPS FT8\nCES\n\nTargets:\nLIMBIC (OFC/NAc)\nCEN (DLPFC)\nmPFC reward loop",
            "card_right": "TPS: 0.22 mJ/mm² · 1,000 pulses · 5 Hz · OFC+vmPFC+DLPFC\ntDCS: C8 — 2 mA · 25 min · F3+Cz anode, Oz cathode\nCES: 200 µA · 15 min (hedonic stabilisation pre-session)\nSession: Daily × 10, then 3×/week\nPrimary scale: SHAPS (Snaith-Hamilton Anhedonia Scale) + MADRS-anhedonia items",
            "brain_targets": [
                ("OFC / vmPFC (Fp1-Fp2/Fz)", "Primary reward valuation node — hypoactive in anhedonia; TPS FT8 frontal pole approach targets OFC"),
                ("L-DLPFC (F3)", "Motivational drive and goal-directed behavior; DLPFC-OFC connectivity impaired in anhedonic MDD"),
                ("SMA/Cz", "Action initiation component of reward-driven behavior; SMA hypofunction contributes to avolition"),
                ("Nucleus accumbens (indirect via OFC TPS)", "Striatal reward processing node; OFC-NAc pathway modulation via frontal TPS"),
                ("Hippocampus (temporal approach)", "Reward memory and context encoding; episodic memories of pleasure lost in anhedonia"),
            ],
            "combinations": [
                ("tDCS C8 + reward tasks (concurrent)", "Reward-conditioned tDCS: stimulate DLPFC during pleasurable activity engagement for use-dependent reward circuit plasticity", "tDCS 25 min during reward task", "Anhedonic MDD; loss of interest; inability to experience pleasure"),
                ("TPS FT8 + tDCS C8 (sequential)", "Deep OFC+DLPFC reward reset after tDCS priming", "tDCS 25 min → TPS 20 min", "Moderate-severe anhedonic MDD"),
                ("CES + reward engagement (pre-session)", "CES increases baseline hedonic tone before cortical stimulation", "CES 15 min → tDCS+TPS session", "Severe anhedonia; flat affect; treatment-resistant reward deficit"),
                ("Full quad with positive psychology tasks", "Complete cascade with structured positive affect induction", "90-min session", "Chronic anhedonic MDD; post-antidepressant residual anhedonia"),
            ],
            "task_pairing": "Reward anticipation and positive affect induction tasks during O-outcome phase: anticipatory pleasure imagery (imagining upcoming positive events), savoring exercises, gratitude journalling, brief engagement with personally meaningful activity (music, nature images). Duration 30 min. Positive psychology framework.",
            "fnon_hypothesis": "Anhedonia in MDD represents a failure of the OFC-DLPFC-nucleus accumbens reward prediction circuit. OFC hypoactivation prevents accurate reward valuation; DLPFC-OFC disconnection impairs goal-directed motivation toward rewards. TPS FT8 uses the frontal pole approach to target OFC and vmPFC directly, while tDCS C8 dual anode (F3+Cz) restores the DLPFC-SMA motivational execution pathway.",
        },
        {
            "code": "P9", "ft_code": "FT9", "name": "Somatic Depression",
            "sozo_bar": {
                "S": "taVNS 0.5 mA · 15 min\nVagal anti-inflammatory pathway; reduce interoceptive amplification",
                "O": "tDCS C5 bilateral DLPFC · 25 min\nFrontal-insula top-down pain modulation",
                "Z": "TPS FT9 · 1,000 pulses · 5 Hz · insula-ACC-M1\nSomatic symptom network reset",
                "O2": "taVNS + body-scan mindfulness · 30 min\nInteroceptive recalibration; somatic defusion",
            },
            "card_left": "P9 — Somatic Depression\nFT9 Network Protocol\n\nModalities:\ntDCS C5\nTPS FT9\ntaVNS\n\nTargets:\nSN (insula/ACC)\nLIMBIC (interoception)\nM1 pain gate",
            "card_right": "TPS: 0.22 mJ/mm² · 1,000 pulses · 5 Hz · insula-ACC-M1\ntDCS: C5 — 2 mA · 25 min · bilateral F3+F4 anode, Oz cathode\ntaVNS: 0.5 mA · 15 min + 30 min outcome phase\nSession: 3–5×/week × 4 weeks\nPrimary scale: PHQ-15 (somatic symptoms) + MADRS · Secondary: pain VAS",
            "brain_targets": [
                ("Anterior insula (C3/C4 lateral)", "Interoceptive amplification of somatic signals — key node in somatic depression; insula hyperactivity drives fatigue, pain, GI symptoms"),
                ("ACC (Cz/FCz)", "Pain affect and suffering component; ACC mediates the distressing quality of somatic depressive symptoms"),
                ("Bilateral DLPFC (F3+F4)", "Top-down pain gate control; prefrontal modulation of insula and ACC somatic signal processing"),
                ("M1 (C3/C4)", "Descending pain modulation via motor cortex; M1 TPS inhibits spinal nociception via corticospinal pathways"),
                ("Vagal-NTS circuit (taVNS)", "Nucleus tractus solitarius — vagal anti-inflammatory pathway; reduces neuro-inflammatory contribution to somatic depression"),
            ],
            "combinations": [
                ("taVNS + tDCS C5 (concurrent)", "Dual vagal+prefrontal approach to somatic symptoms: anti-inflammatory + top-down pain control", "Simultaneous 25 min", "Somatic MDD with pain, fatigue, GI symptoms; elevated CRP/inflammatory markers"),
                ("TPS FT9 + tDCS C5 (sequential)", "Insula-ACC deep TPS after bilateral DLPFC priming", "tDCS 25 min → TPS 20 min", "Moderate somatic depression; medically unexplained symptoms"),
                ("CES + taVNS (pre-session)", "Combined autonomic stabilisation: CES reduces central sensitisation; taVNS activates vagal anti-inflammatory pathway", "CES 60 min + taVNS 15 min pre-session", "Somatic MDD with central sensitisation; fibromyalgia comorbidity"),
                ("Full quad with body-scan mindfulness", "Complete cascade with interoceptive recalibration in O-outcome", "90-min session", "Severe somatic MDD; pain-depression comorbidity"),
            ],
            "task_pairing": "Body-scan mindfulness and interoceptive recalibration tasks during O-outcome phase: guided body-scan (30 min, neutral/accepting stance), somatic defusion exercises (observing without amplifying sensations), gentle movement (seated yoga). Aim: recalibrate insula hypervigilance during peak plasticity. Duration 30 min.",
            "fnon_hypothesis": "Somatic depression is driven by anterior insula hyperactivity amplifying interoceptive signals (pain, fatigue, GI distress) and translating them into depressive affect via insula-amygdala-ACC circuits. TPS FT9 targets lateral insula (C3/C4 approach) and ACC to downregulate the somatic amplification network. taVNS provides the critical vagal anti-inflammatory component, addressing the neuroimmune substrate of somatic depression.",
        },
    ],
    "task_pairing_rows": [
        ("C1 L-DLPFC 2mA 30min", "Core mood regulation", "Behavioral activation scheduling; pleasant event log", "Left prefrontal facilitation conditions mood improvement during task engagement"),
        ("C3 F3-Pz", "Cognitive symptoms", "N-back (2-back); verbal fluency; Trails B", "CEN upregulation during active cognitive challenge — use-dependent DLPFC plasticity"),
        ("C4 F3-F4 asymmetric", "Anxious depression", "Paced breathing; worry postponement; cognitive reappraisal", "Prefrontal asymmetry + anxiety habituation task conditioning"),
        ("C6 cathodal frontal", "Insomnia / hyperarousal", "Progressive muscle relaxation; stimulus control", "Cathodal inhibition + sleep conditioning during evening session"),
        ("C8 F3+Cz motivation", "Anhedonia / psychomotor", "Reward anticipation imagery; activity scheduling", "Dual anode reward circuit priming + behavioral activation coupling"),
        ("F1-F6 FNON protocols", "Network-specific targets", "FNON-matched tasks per phenotype", "Network-level plasticity via phenotype-conditioned stimulation and task pairing"),
    ],
    "followup_rows": [
        ("Phase 1 — Induction (Sessions 1–10)", "Daily or 5×/week", "MADRS, PHQ-9, CGI-S at baseline and session 10", "Confirm phenotype; adjust montage if <15% improvement; add taVNS if needed"),
        ("Phase 2 — Consolidation (Sessions 11–20)", "3–5×/week", "MADRS mid-treatment; CANTAB cognitive battery", "Switch to bilateral C2 if unilateral insufficient; introduce FNON protocols"),
        ("Phase 3 — Maintenance (Month 2–3)", "2–3×/week", "PHQ-9 weekly; full MADRS at 8 weeks", "Begin PlatoScience home protocols; taper in-clinic to 2×/week"),
        ("Phase 4 — Long-Term (Month 3+)", "Weekly booster or PRN", "Quarterly MADRS + CANTAB + CGI", "Maintain with lowest effective frequency; re-induce if MADRS rises >10 points"),
    ],
    "fnon_classification": [
        ("CEN", "Executive/motivational hypoactivation", "Cognitive impairment, avolition, psychomotor slowing", "F1 — CEN Upregulation (F3 anode, F4 cathode)"),
        ("DMN", "Hyperconnectivity / rumination", "Persistent negative thinking, self-referential ideation, poor task engagement", "F2 — DMN Interruption (bilateral DLPFC anode, Pz cathode)"),
        ("SN", "Hyperactivity", "Anxiety, emotional reactivity, threat over-detection", "F3 — SN Downregulation (Fz anode, Oz cathode)"),
        ("SMN", "CEN-SMN disconnection", "Psychomotor retardation, reduced motor spontaneity", "F5 — CEN+SMN Activation (F3+Cz dual anode)"),
        ("LIMBIC", "OFC/vmPFC hypoactivation", "Anhedonia, reward insensitivity, motivational deficits", "F4 — LIMBIC Reset (bilateral OFC anode)"),
        ("ATTENTION", "DAN hypofunction", "Poor concentration, impaired sustained attention", "F6 — ATTENTION Activation (F4 anode, Fp1 cathode)"),
    ],
    "fnon_montage_selection": [
        ("Melancholic / vegetative features", "C1: F3 anode, Fp2 cathode (2 mA, 30 min)", "CEN upregulation + LIMBIC modulation"),
        ("Anxious / rumination dominant", "C4: F3 anode, F4 cathode (interhemispheric)", "SN downregulation + prefrontal asymmetry"),
        ("Cognitive / executive dominant", "C3: F3 anode, Pz cathode (2 mA, 25 min)", "CEN backbone DLPFC-PPC"),
        ("Anhedonic / motivational deficit", "C8: F3+Cz dual anode, Oz cathode", "LIMBIC + SMN reward-motivation circuit"),
        ("Insomnia / hyperarousal", "C6: bilateral frontal cathode, Cz anode (1.5 mA, 20 min evening)", "SN downregulation — inhibitory approach"),
        ("Somatic / pain comorbid", "C5: bilateral F3+F4 anode, Oz cathode (2 mA, 25 min)", "Dual CEN + top-down pain modulation"),
    ],
}


# ════════════════════════════════════════════════════════════════════════════════
# 3. ADHD
# ════════════════════════════════════════════════════════════════════════════════
