"""
Partners-tier All-In-One Protocol data — insomnia.
Auto-split from partners_all_in_one_data.py. Edit this file to modify insomnia data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['insomnia'] = {
    'display_name': 'Insomnia & Sleep Disorders',
    'short': 'Insomnia',
    'condition_slug': 'insomnia',
    'icd10': 'G47.0',
    'tps_warning': (
        "TPS use in Insomnia & Sleep Disorders is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for insomnia "
        "is investigational. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Cortical hyperarousal / thalamic sleep gating failure / DMN pre-sleep activation / CEN-sleep overlap',
    'fnon_montage_selection': [
        ['Cortical hyperarousal dominant', 'HDCstim F3/F4 anodes / Cz cathode'],
        ['Pre-sleep rumination', 'tDCS Fp1 cathode / F3 anode'],
        ['Circadian-thalamic', 'CES extended + tDCS Fz'],
        ['Comorbid anxiety-insomnia', 'tDCS F3/F4 anodes + taVNS'],
        ['Depression-insomnia', 'tDCS F3 anode / F4 cathode + CES'],
    ],
    'tps': [
        ['T1', 'DLPFC pre-sleep', 'F3/F4 bilateral', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T2', 'ACC hyperarousal', 'Fz / ACC-proxy', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T3', 'mPFC rumination', 'Fp1 / mPFC-proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'Occipital slow wave', 'Oz bilateral', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T5', 'Thalamus proxy (Cz)', 'Cz / thalamic proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'Cortical arousal reduce', 'Cortical hyperarousal', 'F3/F4 + Cz', 'Pre-sleep excitability down', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT2', 'DMN pre-sleep quiet', 'DMN activation at sleep', 'mPFC Fp1 + PCC Pz', 'Rumination cessation', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT3', 'CEN sleep modulate', 'CEN pre-sleep overactivation', 'F3/F4 bilateral', 'Executive quiet mode', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT4', 'SN arousal suppress', 'SN hyperactivation', 'Cz + insula C3', 'Threat salience bedtime', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT5', 'LIMBIC bedtime anxiety', 'LIMBIC hyperactivation', 'vmPFC + amygdala temporal', 'Bedtime fear reduce', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT6', 'Circadian anchor', 'Circadian dysregulation', 'Oz + thalamus Cz', 'Sleep drive strengthen', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT7', 'Depression-insomnia', 'LIMBIC + sleep overlap', 'DLPFC L + Cz', 'Mood-sleep unified', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Hyperarousal maximize', 'Severe hyperarousal', 'Multisite F3+Cz+Oz', 'Maximum arousal reduce', '0.20 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT9', 'Comprehensive insomnia', 'Multi-network', 'Rotating DMN+CEN+SN+thalamus', 'Holistic sleep protocol', '0.20 mJ/mm²', '1000 pulses', '12 sessions'],
    ],
    'tdcs': [
        ['C1', 'Pre-sleep cortical', 'F3/F4 anodes / Cz cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'ACC hyperarousal', 'Fz anode / Oz cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C3', 'mPFC rumination', 'Fp1 cathode / F3 anode', '1.5 mA', '20 min', 'Emerging'],
        ['C4', 'Slow-wave induction', 'Oz anode / Fz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C5', 'Anxiety-insomnia', 'F3/F4 anodes / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Depression-insomnia', 'F3 anode / Fp2 cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C7', 'Circadian support', 'Fz anode / Oz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C8', 'Treatment-resistant', 'F3/F4+Oz bilateral', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'Cortical down', 'Cortical hyperarousal', 'F3/F4 anodes / Cz cathode', 'Pre-sleep calming', '1.5 mA', '20 min'],
        ['F2', 'DMN quiet', 'DMN pre-sleep', 'Fp1 cathode / Pz cathode', 'Rumination stop', '1.5 mA', '20 min'],
        ['F3', 'ACC settle', 'ACC hyperarousal', 'Fz anode / Oz cathode', 'Arousal reduction', '1.5 mA', '20 min'],
        ['F4', 'SN bedtime', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Threat bedtime reduce', '1.5 mA', '20 min'],
        ['F5', 'LIMBIC calm', 'LIMBIC bedtime anxiety', 'Fp1 anode / mastoid', 'Fear reduce', '1.5 mA', '20 min'],
        ['F6', 'Circadian', 'Circadian disruption', 'Fz anode / Oz cathode', 'Circadian support', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Sleep onset', 'Variant G', 'F3/Cz', '1.0 mA', '20 min', 'Evening protocol'],
        ['C2-PS', 'Rumination stop', 'Variant G', 'Fp1/Cz', '1.0 mA', '20 min', 'Pre-bed'],
        ['C3-PS', 'Anxiety calm', 'Variant D', 'F3/Cz', '1.0 mA', '20 min', 'Bedtime anxiety'],
        ['C4-PS', 'Mood-sleep', 'Variant A', 'F3/F4', '1.2 mA', '20 min', 'Depression-insomnia'],
        ['C5-PS', 'Circadian', 'Variant G', 'Oz/Cz', '1.0 mA', '20 min', 'Circadian support'],
        ['C6-PS', 'Hyperarousal', 'Variant G', 'F3/Fz', '1.0 mA', '20 min', 'Severe hyperarousal'],
        ['C7-PS', 'Maintenance wake', 'Variant G', 'Fp1/Cz', '1.0 mA', '20 min', 'Middle insomnia'],
        ['C8-PS', 'Early morning', 'Variant G', 'F3/Oz', '1.0 mA', '20 min', 'EMA insomnia'],
    ],
    'fnon_plato': [
        ['FP1', 'Cortical down', 'Cortical hyperarousal', 'Variant G', 'F3/Cz', '1.0 mA', '20 min'],
        ['FP2', 'DMN quiet', 'DMN pre-sleep', 'Variant G', 'Fp1/Pz', '1.0 mA', '20 min'],
        ['FP3', 'SN bedtime', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.0 mA', '20 min'],
        ['FP4', 'LIMBIC calm', 'LIMBIC bedtime', 'Variant D', 'Fp1/Cz', '1.0 mA', '20 min'],
        ['FP5', 'Mood-sleep', 'LIMBIC depression', 'Variant A', 'F3/F4', '1.2 mA', '20 min'],
        ['FP6', 'Circadian', 'Circadian dysregulation', 'Variant G', 'Oz/Cz', '1.0 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Sleep Onset Insomnia',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Fz evening', 'TPS FT1 arousal', 'Sleep onset protocol'],
            'card_left': ['Network: Cortical hyperarousal at bedtime', 'Key target: DLPFC, Cz, ACC', 'Priority: Pre-sleep arousal reduction'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'CBT-I onset'],
            'brain_targets': [
                ['Cz (cortical arousal)', 'Generalized arousal', 'Reduce (cathode)', 'FT1 / C1 / FP1', 'Evidence B'],
                ['ACC', 'Pre-sleep monitoring', 'Suppress', 'T2 / C2', 'Evidence B'],
                ['Thalamus (CES)', 'Sleep gate open', 'Support', 'CES protocol', 'Emerging'],
                ['mPFC', 'Pre-sleep worry', 'Quiet', 'T3 / C3', 'Emerging'],
                ['DLPFC', 'Cognitive hyperarousal', 'Balance', 'T1 / C1', 'Evidence B'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C1 F3/Fz', 'TPS arousal reduce', 'Stimulus control protocol'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction therapy'],
                ['CES 20 min', 'tDCS F1', 'TPS mPFC', 'Cognitive shuffle technique'],
                ['taVNS 20 min', 'tDCS C2', 'TPS Cz cathode', 'Progressive muscle relaxation'],
            ],
            'task_pairing': 'Stimulus control, sleep restriction therapy, cognitive shuffle for sleep onset, progressive muscle relaxation.',
            'fnon_hypothesis': 'Sleep onset insomnia reflects cortical hyperarousal preventing the thalamic sleep gate from opening. CES + Cz cathodal tDCS reduces cortical excitability, lowering the threshold for sleep onset.',
        },
        {
            'code': 'P2', 'name': 'Sleep Maintenance Insomnia',
            'sozo_bar': ['CES 20 min', 'tDCS Fp1 cathode/Fz', 'TPS DMN suppress', 'Sleep consolidation'],
            'card_left': ['Network: DMN hyperactivation during sleep', 'Key target: mPFC, PCC, thalamus', 'Priority: Sleep continuity'],
            'card_right': ['TPS: T3+T5 + FT2', 'tDCS: C3/F2', 'PlatoScience: C7-PS/FP2', 'Consolidation'],
            'brain_targets': [
                ['mPFC', 'DMN wake intrusion', 'Suppress', 'T3 / C3 / FP2', 'Emerging'],
                ['PCC', 'Default mode active', 'Reduce', 'FT2 / Pz cathode', 'Emerging'],
                ['Thalamus (CES)', 'NREM maintenance', 'Support', 'CES protocol', 'Emerging'],
                ['ACC', 'Arousal threshold', 'Normalize', 'T2 / C2', 'Evidence B'],
                ['Hypothalamus', 'Sleep drive', 'Support (CES)', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C3 Fp1 cathode', 'TPS DMN mPFC', 'Sleep restriction + compression'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS PCC', 'Paradoxical intention'],
                ['CES 20 min', 'tDCS F2', 'TPS Cz thalamus', 'Sleep consolidation protocol'],
                ['taVNS 20 min', 'tDCS C3', 'TPS mPFC+PCC', 'Cognitive defusion night wake'],
            ],
            'task_pairing': 'Sleep restriction and consolidation, paradoxical intention, cognitive defusion for night waking, sleep scheduling.',
            'fnon_hypothesis': 'Sleep maintenance insomnia reflects mPFC-PCC default mode network spontaneous reactivation during sleep. DMN TPS + sleep restriction drives sleep consolidation by strengthening homeostatic pressure.',
        },
        {
            'code': 'P3', 'name': 'Early Morning Awakening',
            'sozo_bar': ['CES 20 min', 'tDCS Oz/F3 evening', 'TPS FT6 circadian', 'Light therapy + CBT-I'],
            'card_left': ['Network: Circadian phase advance + depression', 'Key target: Hypothalamus (CES), Oz', 'Priority: Circadian phase reset'],
            'card_right': ['TPS: T4+T5 + FT6', 'tDCS: C7/F6', 'PlatoScience: C8-PS/FP6', 'Light + CBT-I'],
            'brain_targets': [
                ['Hypothalamus (CES)', 'Circadian clock', 'Delay (CES timing)', 'CES evening', 'Emerging'],
                ['Occipital (Oz)', 'Circadian light input', 'Modulate', 'T4 / C7', 'Emerging'],
                ['DLPFC', 'Depression-EMA', 'Activate L', 'T1 / C6', 'Evidence B'],
                ['SCN proxy (Cz)', 'Circadian anchor', 'Normalize', 'FT6 / Cz', 'Emerging'],
                ['Thalamus (CES)', 'Sleep timing', 'Modulate', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C7 Oz', 'TPS Oz circadian', 'Evening bright light delay'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS DLPFC', 'CBT-I sleep timing'],
                ['CES 20 min', 'tDCS F6', 'TPS Cz circadian', 'Chronotherapy adjustment'],
                ['taVNS 20 min', 'tDCS C6', 'TPS ACC', 'Mood + sleep combined CBT'],
            ],
            'task_pairing': 'Evening bright light delay therapy, chronotherapy sleep timing adjustment, CBT-I adapted for EMA, mood-sleep combined CBT.',
            'fnon_hypothesis': 'Early morning awakening reflects circadian phase advance with sleep pressure dissipating early. Evening CES + occipital TPS modulates circadian timing signals to delay sleep offset.',
        },
        {
            'code': 'P4', 'name': 'Insomnia + Anxiety',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4 evening', 'TPS FT5 LIMBIC', 'CBT-I + CBT anxiety'],
            'card_left': ['Network: LIMBIC hyperactivation + hyperarousal', 'Key target: DLPFC, vmPFC, amygdala', 'Priority: Anxiety-sleep cycle'],
            'card_right': ['TPS: T2+T1 + FT5', 'tDCS: C5/F4', 'PlatoScience: C3-PS/FP4', 'Dual CBT'],
            'brain_targets': [
                ['DLPFC', 'Anxiety + sleep control', 'Activate', 'T1 / C5 / FP4', 'Evidence B'],
                ['vmPFC', 'Safety + sleep signal', 'Strengthen', 'FT5 / F4', 'Emerging'],
                ['Amygdala', 'Bedtime fear', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['ACC', 'Worry + arousal', 'Suppress', 'T2 / C2', 'Evidence B'],
                ['Thalamus (CES)', 'Sleep gate', 'Support', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C5 F3/F4', 'TPS DLPFC+LIMBIC', 'Combined CBT-I + anxiety CBT'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Worry postponement + sleep'],
                ['taVNS 20 min', 'tDCS F4', 'TPS amygdala', 'Bedtime relaxation protocol'],
                ['CES 20 min', 'tDCS C2', 'TPS ACC', 'Mindfulness-based stress + sleep'],
            ],
            'task_pairing': 'Combined CBT-I and anxiety CBT, worry postponement diary, bedtime relaxation, mindfulness-based stress reduction.',
            'fnon_hypothesis': 'Anxiety-insomnia reflects mutual amplification of LIMBIC hyperactivation and cortical arousal. Targeting vmPFC + amygdala during evening relaxation breaks the anxiety-hyperarousal-insomnia cycle.',
        },
        {
            'code': 'P5', 'name': 'Insomnia + Depression',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode evening', 'TPS FT7 depression-sleep', 'BA + CBT-I'],
            'card_left': ['Network: LIMBIC dysregulation + hyperarousal', 'Key target: DLPFC L, Cz, vmPFC', 'Priority: Mood-sleep unified'],
            'card_right': ['TPS: T1+T5 + FT7', 'tDCS: C6/F5', 'PlatoScience: C4-PS/FP5', 'BA + CBT-I'],
            'brain_targets': [
                ['DLPFC L', 'Mood + sleep regulation', 'Activate', 'T1 / C6 / FP5', 'Evidence B'],
                ['vmPFC', 'Positive affect + sleep', 'Restore', 'FT7 / F5', 'Emerging'],
                ['ACC', 'Depression + arousal', 'Modulate', 'T2 / C2', 'Evidence B'],
                ['Thalamus (CES)', 'Sleep architecture', 'Support', 'CES protocol', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C6 F3', 'TPS DLPFC L', 'BA morning + CBT-I evening'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasant activity + sleep hygiene'],
                ['taVNS 20 min', 'tDCS F5', 'TPS ACC', 'Mood + sleep diary combined'],
                ['CES 20 min', 'tDCS C6', 'TPS DLPFC+Cz', 'Unified BA-CBT-I protocol'],
            ],
            'task_pairing': 'Behavioral activation (morning) + CBT-I (evening), pleasant activity + sleep hygiene, unified mood-sleep diary.',
            'fnon_hypothesis': 'Depression-insomnia reflects shared DLPFC-vmPFC dysregulation disrupting both mood regulation and sleep architecture. L-DLPFC TPS morning session targets mood; evening CES targets sleep.',
        },
        {
            'code': 'P6', 'name': 'Chronic Insomnia Disorder',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Fz + Cz cathode', 'TPS FT9 rotating', 'Full CBT-I'],
            'card_left': ['Network: Conditioned arousal + multi-network', 'Key target: DLPFC, ACC, thalamus, DMN', 'Priority: Full CBT-I augmentation'],
            'card_right': ['TPS: FT1+FT2 + FT9', 'tDCS: C8/F1', 'PlatoScience: C6-PS/FP1', 'Full CBT-I'],
            'brain_targets': [
                ['Cz (arousal)', 'Conditioned arousal', 'Suppress', 'FT1 / C8 / FP1', 'Evidence B'],
                ['DLPFC', 'Sleep misconceptions', 'Activate', 'T1 / C1', 'Evidence B'],
                ['DMN (mPFC+PCC)', 'Rumination', 'Suppress', 'FT2 / C3', 'Emerging'],
                ['Thalamus (CES)', 'Sleep gating', 'Restore', 'CES protocol', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Reduce', 'T2 / C2', 'Evidence B'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C8 F3/Cz', 'TPS arousal + DMN', 'Full CBT-I 6-session'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction intensive'],
                ['CES 20 min', 'tDCS F1', 'TPS DLPFC', 'Cognitive therapy insomnia'],
                ['taVNS 20 min', 'tDCS C2', 'TPS Cz thalamus', 'Stimulus control strict'],
            ],
            'task_pairing': 'Full CBT-I (6-component): sleep restriction, stimulus control, relaxation, cognitive therapy, sleep hygiene, relapse prevention.',
            'fnon_hypothesis': 'Chronic insomnia disorder reflects conditioned cortical arousal to sleep-related stimuli with multi-network hyperactivation. SOZO augments CBT-I by directly reducing cortical excitability during behavioral intervention.',
        },
        {
            'code': 'P7', 'name': 'Circadian Rhythm Disorder (Delayed)',
            'sozo_bar': ['CES morning 20 min', 'tDCS F3/Fz morning', 'TPS FT6 circadian', 'Chronotherapy'],
            'card_left': ['Network: Circadian phase delay + thalamic timing', 'Key target: Hypothalamus (CES), Oz morning', 'Priority: Phase advance'],
            'card_right': ['TPS: T4+FT6', 'tDCS: C7/F6', 'PlatoScience: C5-PS/FP6', 'Chronotherapy'],
            'brain_targets': [
                ['Hypothalamus (CES)', 'SCN phase reset', 'Advance (morning CES)', 'CES morning protocol', 'Emerging'],
                ['Occipital (Oz)', 'Light-circadian input', 'Activate morning', 'T4 / C7 morning', 'Emerging'],
                ['DLPFC', 'Wakefulness drive', 'Activate morning', 'T1 / C1 morning', 'Emerging'],
                ['Thalamus', 'Arousal morning', 'Activate (morning CES)', 'CES morning', 'Emerging'],
                ['Reticular system', 'Wake drive', 'Support (taVNS morning)', 'taVNS morning', 'Emerging'],
            ],
            'combinations': [
                ['CES morning 20 min', 'tDCS C7 morning', 'TPS Oz morning', 'Morning bright light 10,000 lux'],
                ['taVNS morning 20 min', 'PlatoScience Variant B', 'TPS DLPFC morning', 'Chronotherapy advance'],
                ['CES morning', 'tDCS F6 morning', 'TPS circadian Cz', 'Fixed wake time protocol'],
                ['taVNS morning', 'tDCS F3 morning', 'TPS mPFC morning', 'Melatonin timing coordination'],
            ],
            'task_pairing': 'Morning bright light therapy (10,000 lux), chronotherapy phase advance, fixed wake time protocol, melatonin timing coordination.',
            'fnon_hypothesis': 'Delayed sleep phase reflects SCN circadian oscillator phase delay. Morning CES activates thalamic arousal circuits while morning occipital TPS amplifies the phase-advancing effect of morning light.',
        },
        {
            'code': 'P8', 'name': 'Insomnia + Chronic Pain',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 + Fz', 'TPS M1+ACC+sleep', 'Pain + sleep protocol'],
            'card_left': ['Network: Pain + hyperarousal co-activation', 'Key target: M1 bilateral, ACC, Cz', 'Priority: Pain-sleep cycle'],
            'card_right': ['TPS: T2+T1 + FT8', 'tDCS: C5/F3', 'PlatoScience: C2-PS/FP1', 'Pain-sleep task'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C5 / FP1', 'Evidence A'],
                ['ACC', 'Pain + arousal', 'Modulate', 'T2 / C2', 'Evidence B'],
                ['Cz (arousal)', 'Pre-sleep arousal', 'Suppress', 'FT1 / C1', 'Emerging'],
                ['Insula', 'Pain at night', 'Normalize', 'FT4 / C3', 'Emerging'],
                ['Thalamus (CES)', 'Sleep + pain relay', 'Modulate', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C5 M1 + Fz', 'TPS M1+ACC', 'Pain management + CBT-I'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS Cz sleep', 'Pain-sleep combined protocol'],
                ['taVNS 20 min', 'tDCS F3', 'TPS insula night', 'Relaxation + pain acceptance'],
                ['CES 20 min', 'tDCS C2', 'TPS ACC', 'Sleep hygiene + pain education'],
            ],
            'task_pairing': 'Pain management + CBT-I combined, pain-sleep diary, relaxation and pain acceptance, sleep hygiene adapted for chronic pain.',
            'fnon_hypothesis': 'Insomnia-pain comorbidity reflects mutual amplification: pain increases cortical arousal, arousal lowers pain threshold. M1 TPS + CES simultaneously addresses both pain gate and sleep gating.',
        },
        {
            'code': 'P9', 'name': 'Treatment-Resistant Insomnia',
            'sozo_bar': ['CES 30 min', 'HDCstim F3/Fz+Cz cathode', 'TPS FT9 rotating', 'Intensive CBT-I'],
            'card_left': ['Network: Maximum conditioned hyperarousal', 'Key target: All sleep-wake nodes', 'Priority: Maximum arousal disruption'],
            'card_right': ['TPS: FT9 full rotating', 'tDCS: C8/F1+F2', 'PlatoScience: C6-PS/FP1', 'Intensive CBT-I'],
            'brain_targets': [
                ['Cortical arousal (Cz)', 'Conditioned maximum', 'Maximum suppress', 'FT1+FT8 / C8 / FP1', 'Evidence B'],
                ['DMN nodes', 'Rumination maximum', 'Suppress', 'FT2 / C3', 'Emerging'],
                ['Thalamus (CES extended)', 'Sleep gate maximal', 'Open', 'CES extended 30 min', 'Emerging'],
                ['ACC', 'Hyperarousal maximum', 'Reduce', 'T2 / C2', 'Evidence B'],
                ['vmPFC', 'Sleep safety signal', 'Strengthen', 'FT5 / F4', 'Emerging'],
            ],
            'combinations': [
                ['CES 30 min', 'HDCstim F3/Cz cathode', 'TPS rotating arousal', 'Intensive CBT-I daily'],
                ['taVNS 30 min', 'PlatoScience Variant G', 'TPS DMN suppress', 'Sleep restriction maximal'],
                ['CES 30 min', 'tDCS C8 bilateral', 'TPS ACC+Cz', 'Stimulus control intensive'],
                ['taVNS 20 min', 'HDCstim Fz/Oz', 'TPS vmPFC + thalamus', 'Paradoxical intention + CBT'],
            ],
            'task_pairing': 'Intensive CBT-I (daily sessions), sleep restriction maximal, stimulus control intensive, paradoxical intention with SOZO augmentation.',
            'fnon_hypothesis': 'Treatment-resistant insomnia reflects maximum conditioned cortical hyperarousal with multi-network entrainment. Rotating SOZO protocol disrupts arousal from CEN, DMN, SN, and LIMBIC angles simultaneously.',
        },
    ],
    'task_pairing_rows': [
        ['Stimulus control', 'Evening session', 'CBT-I', 'P1, P6'],
        ['Sleep restriction', 'Evening session', 'CBT-I', 'P2, P6, P9'],
        ['Chronotherapy', 'Morning session', 'Circadian', 'P3, P7'],
        ['Worry postponement', 'Evening session', 'Anxiety', 'P4'],
        ['BA + CBT-I', 'Day + evening', 'Depression', 'P5'],
        ['Full CBT-I', 'Evening sessions', 'Chronic', 'P6'],
        ['Light therapy', 'Morning session', 'Circadian', 'P7'],
        ['Pain + sleep diary', 'Daily', 'Pain-sleep', 'P8'],
        ['Intensive CBT-I', 'Daily sessions', 'Resistant', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'ISI, PSQI, sleep diary', 'Insomnia severity + diary', 'CBT-I compliance check'],
        ['Week 4', 'ISI, PSQI, PHQ-9, GAD-7', 'Sleep + mood + anxiety', 'Phase 2 intensification'],
        ['Week 6', 'Full sleep battery + actigraphy', 'Objective + subjective', 'Sleep efficiency target >85%'],
        ['Week 10', 'ISI, PSQI, QoL', 'Long-term trajectory', 'Maintenance planning'],
        ['Month 4', 'ISI, PSQI, daily diary', 'Sleep stability', 'Maintenance protocol'],
        ['Month 6', 'ISI, QoL, PHQ-9', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(3, 2, 3, 5, 3, 5, 2, 3, 4),
}

# ════════════════════════════════════════════════════════════════════════════════
# 15. PARKINSON'S DISEASE
# ════════════════════════════════════════════════════════════════════════════════
