"""
Partners-tier All-In-One Protocol data — long_covid.
Auto-split from partners_all_in_one_data.py. Edit this file to modify long_covid data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['long_covid'] = {
    'display_name': 'Long COVID — Neurological & Cognitive Symptoms',
    'short': 'Long COVID',
    'condition_slug': 'long_covid',
    'icd10': 'U09.9',
    'tps_warning': (
        "TPS use in Long COVID is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for Long COVID neurological symptoms "
        "is preliminary. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Neuroinflammation-driven CEN hypofunction / DMN disruption / fatigue circuit / autonomic dysregulation',
    'fnon_montage_selection': [
        ['Brain fog dominant', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Fatigue dominant', 'HDCstim tDCS F3/Fz + CES protocol'],
        ['Autonomic (POTS)', 'tDCS C3/C4 + taVNS extended'],
        ['Mood dysregulation', 'tDCS F3 anode / F4 cathode'],
        ['Pain long COVID', 'tDCS C3/C4 + CES bilateral'],
    ],
    'tps': [
        ['T1', 'DLPFC brain fog', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T2', 'Fatigue circuit', 'F3 + Fz', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T3', 'Autonomic insula', 'C3 insula proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'Mood long COVID', 'DLPFC L F3', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T5', 'ACC attention', 'Fz / ACC-proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN reactivation', 'CEN hypofunction (neuroinflam)', 'F3/F4 bilateral', 'Cognitive circuit restore', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT2', 'Fatigue network', 'Fatigue circuit disruption', 'F3/Fz bilateral', 'Neural efficiency restore', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT3', 'DMN normalize', 'DMN disruption', 'mPFC + PCC', 'Default mode reset', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'SN dysregulation', 'SN hyperactivation', 'Cz + insula C3', 'Symptom salience reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'Autonomic restoration', 'Autonomic dysregulation', 'Insula C3 + C4', 'HRV and POTS support', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT6', 'Mood circuit', 'LIMBIC dysregulation', 'DLPFC L + vmPFC', 'Long COVID depression', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Sleep disruption', 'Sleep-wake dysregulation', 'F3 + Cz', 'Sleep restoration', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT8', 'Headache long COVID', 'Central sensitization', 'Cz + Oz bilateral', 'Headache circuit', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Comprehensive long COVID', 'Multi-network', 'Rotating CEN+fatigue+autonomic', 'Holistic protocol', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Brain fog cognitive', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C2', 'Fatigue', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Emerging'],
        ['C3', 'Autonomic POTS', 'C3/C4 bilateral / Oz', '2 mA', '20 min', 'Emerging'],
        ['C4', 'Mood', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Pain long COVID', 'C3/C4 anodes / Oz', '2 mA', '20 min', 'Emerging'],
        ['C6', 'Sleep', 'Fz anode / Oz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Headache', 'Oz anode / Cz cathode', '2 mA', '20 min', 'Emerging'],
        ['C8', 'Anxiety long COVID', 'F3/F4 anodes / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN brain fog', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Cognitive circuit restore', '2 mA', '20 min'],
        ['F2', 'Fatigue circuit', 'Fatigue network', 'F3 anode / Cz cathode', 'Neural efficiency', '2 mA', '20 min'],
        ['F3', 'Autonomic', 'Autonomic dysregulation', 'C3/C4 anodes / Oz', 'HRV support', '2 mA', '20 min'],
        ['F4', 'SN suppress', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Symptom salience reduce', '2 mA', '20 min'],
        ['F5', 'Mood long COVID', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Mood restoration', '2 mA', '20 min'],
        ['F6', 'Sleep', 'Sleep disruption', 'Fz anode / Oz cathode', 'Sleep circuit', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Cognitive fog', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Brain fog tasks'],
        ['C2-PS', 'Energy', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Fatigue long COVID'],
        ['C3-PS', 'Mood', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Long COVID depression'],
        ['C4-PS', 'Sleep', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'Long COVID insomnia'],
        ['C5-PS', 'Autonomic', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'POTS + HRV'],
        ['C6-PS', 'Pain', 'Variant E', 'C3/C4', '1.4 mA', '20 min', 'Long COVID pain'],
        ['C7-PS', 'Anxiety', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Long COVID anxiety'],
        ['C8-PS', 'Headache', 'Variant G', 'Oz/Cz', '1.2 mA', '20 min', 'Post-COVID headache'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN brain fog', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'Fatigue', 'Fatigue circuit', 'Variant D', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP3', 'Autonomic', 'Autonomic dysregulation', 'Variant F', 'C3/C4', '1.4 mA', '20 min'],
        ['FP4', 'SN symptom', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP5', 'LIMBIC mood', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP6', 'Sleep', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Brain Fog / Cognitive Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Cognitive rehab'],
            'card_left': ['Network: CEN neuroinflammatory disruption', 'Key target: DLPFC bilateral', 'Priority: Cognitive circuit reactivation'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Working memory', 'Activate', 'T1 / C1 / FP1', 'Emerging'],
                ['ACC', 'Attention/processing', 'Activate', 'T5 / C2', 'Emerging'],
                ['Hippocampus', 'Memory encoding', 'Support (taVNS)', 'taVNS', 'Emerging'],
                ['Thalamus (CES)', 'Arousal gating', 'Normalize', 'CES', 'Emerging'],
                ['PFC bilateral', 'Executive', 'Upregulate', 'FT1 / C8', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Cognitive rehabilitation program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS bilateral', 'Working memory tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Processing speed training'],
                ['CES 20 min', 'tDCS C8', 'TPS hippocampus', 'Memory encoding exercises'],
            ],
            'task_pairing': 'Cognitive rehabilitation program, working memory n-back, processing speed training, memory encoding tasks.',
            'fnon_hypothesis': 'Long COVID brain fog reflects neuroinflammatory disruption of CEN white matter and synaptic efficiency. DLPFC TPS bypasses inflammatory downregulation by directly activating cortical circuits.',
        },
        {
            'code': 'P2', 'name': 'Post-COVID Fatigue',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fz', 'TPS FT2 fatigue', 'Pacing program'],
            'card_left': ['Network: Fatigue circuit + CEN inefficiency', 'Key target: DLPFC, SMA, ACC', 'Priority: Energy regulation'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C2/F2', 'PlatoScience: C2-PS/FP2', 'Pacing task'],
            'brain_targets': [
                ['DLPFC', 'Effort regulation', 'Activate', 'T2 / C2 / FP2', 'Emerging'],
                ['ACC', 'Fatigue monitoring', 'Normalize', 'T5 / C5', 'Emerging'],
                ['Insula', 'Fatigue perception', 'Normalize', 'T3 / C3', 'Emerging'],
                ['Thalamus (CES)', 'Arousal level', 'Support', 'CES protocol', 'Emerging'],
                ['SMA', 'Motor effort', 'Upregulate', 'FT2 / Fz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/Fz', 'TPS fatigue DLPFC', 'Energy pacing program'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', 'Activity management'],
                ['taVNS 20 min', 'tDCS C2', 'TPS insula', 'Graded return to activity'],
                ['CES 20 min', 'tDCS F2', 'TPS SMA', 'Fatigue diary optimization'],
            ],
            'task_pairing': 'Energy pacing program, activity management, graded return to activity (avoid PEM), fatigue diary.',
            'fnon_hypothesis': 'Post-COVID fatigue reflects insula hypervigilance to exertion combined with ACC metabolic dysregulation. Graduated pacing + tDCS reduces perceived effort while avoiding post-exertional malaise.',
        },
        {
            'code': 'P3', 'name': 'Autonomic Dysregulation (POTS)',
            'sozo_bar': ['taVNS 40 min', 'tDCS C3/C4 insula', 'TPS insula FT5', 'HRV biofeedback'],
            'card_left': ['Network: Autonomic + insula dysregulation', 'Key target: Insula, vagal axis, C3/C4', 'Priority: HRV and POTS management'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C3/F3', 'PlatoScience: C5-PS/FP3', 'HRV task'],
            'brain_targets': [
                ['Insula', 'Autonomic integration', 'Normalize', 'T3 / C3 / FP3', 'Emerging'],
                ['ACC', 'Autonomic control', 'Activate', 'T5 / C5', 'Emerging'],
                ['vmPFC', 'Cardiac safety', 'Strengthen', 'FT6 / F5', 'Emerging'],
                ['Brainstem (taVNS)', 'Vagal tone', 'Increase', 'taVNS extended', 'Evidence B'],
                ['Hypothalamus', 'Autonomic balance', 'Normalize (CES)', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C3/C4', 'TPS insula', 'HRV biofeedback daily'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS ACC', 'Cardiac coherence breathing'],
                ['taVNS 40 min', 'tDCS F3', 'TPS vmPFC', 'Orthostatic training program'],
                ['CES 20 min', 'tDCS C3', 'TPS insula bilateral', 'Compression + conditioning'],
            ],
            'task_pairing': 'HRV biofeedback, cardiac coherence breathing (6 cpm), orthostatic conditioning program, compression garments during sessions.',
            'fnon_hypothesis': 'Long COVID POTS reflects autonomic nervous system dysregulation with impaired vagal tone. Extended taVNS directly targets vagal-cardiac axis while insula TPS normalizes cortical autonomic representation.',
        },
        {
            'code': 'P4', 'name': 'Mood Dysregulation (Long COVID)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood circuit support'],
            'card_right': ['TPS: T4 + FT6', 'tDCS: C4/F5', 'PlatoScience: C3-PS/FP5', 'BA task'],
            'brain_targets': [
                ['DLPFC L', 'Mood regulation', 'Activate', 'T4 / C4 / FP5', 'Emerging'],
                ['vmPFC', 'Positive affect', 'Restore', 'FT6 / F5', 'Emerging'],
                ['ACC', 'Mood monitoring', 'Modulate', 'T5 / C5', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['Hippocampus', 'Mood circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Meaning + illness acceptance'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'Mood diary'],
                ['CES 20 min', 'tDCS F5', 'TPS amygdala', 'CBT for illness'],
            ],
            'task_pairing': 'Behavioral activation, illness acceptance therapy, mood diary, CBT for chronic illness adaptation.',
            'fnon_hypothesis': 'Long COVID mood dysregulation reflects neuroinflammatory LIMBIC circuit disruption. L-DLPFC TPS provides mood uplift while taVNS supports neuroplasticity recovery.',
        },
        {
            'code': 'P5', 'name': 'Headache & Pain (Post-COVID)',
            'sozo_bar': ['taVNS 30 min', 'tDCS Oz/C3/C4', 'TPS FT8 headache', 'Pain education'],
            'card_left': ['Network: Central sensitization post-COVID', 'Key target: Cz, Oz, M1 bilateral', 'Priority: Pain gate restoration'],
            'card_right': ['TPS: T5+T3 + FT8', 'tDCS: C7/F6', 'PlatoScience: C8-PS/FP6', 'Pain mgmt'],
            'brain_targets': [
                ['Occipital (Oz)', 'Headache', 'Modulate', 'T5 / C7 / FP6', 'Emerging'],
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C5', 'Emerging'],
                ['Insula', 'Pain integration', 'Normalize', 'T3 / C3', 'Emerging'],
                ['ACC', 'Pain affect', 'Modulate', 'T5 / C5', 'Emerging'],
                ['DLPFC', 'Top-down pain', 'Activate', 'T1 / C1', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 Oz anode', 'TPS Oz bilateral', 'Headache management plan'],
                ['CES 20 min', 'PlatoScience Variant G', 'TPS M1', 'Pain pacing'],
                ['taVNS 20 min', 'tDCS C5', 'TPS insula', 'Body scan ACT pain'],
                ['CES 20 min', 'tDCS F6', 'TPS DLPFC', 'Pain education long COVID'],
            ],
            'task_pairing': 'Headache management plan, pain pacing program, body scan ACT for pain, long COVID pain education.',
            'fnon_hypothesis': 'Post-COVID pain reflects central sensitization driven by neuroinflammation. M1 + occipital TPS activates analgesic pathways while taVNS reduces neuroinflammatory cytokine signaling.',
        },
        {
            'code': 'P6', 'name': 'Sleep Disruption (Long COVID)',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Fz', 'TPS FT7 sleep', 'CBT-I adapted'],
            'card_left': ['Network: Hyperarousal + circadian disruption', 'Key target: Thalamus (CES), DLPFC', 'Priority: Sleep architecture repair'],
            'card_right': ['TPS: T2+T5 + FT7', 'tDCS: C6/F6', 'PlatoScience: C4-PS/FP6', 'CBT-I'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep control', 'Balance', 'T2 / C6 / FP6', 'Emerging'],
                ['Thalamus (CES)', 'Sleep gating', 'Support', 'CES protocol', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Suppress', 'T5 / C5', 'Emerging'],
                ['mPFC', 'Rumination', 'Downregulate', 'FT3 / F3', 'Emerging'],
                ['Hypothalamus', 'Circadian reset', 'Normalize (CES)', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C6', 'TPS DLPFC sleep', 'CBT-I adapted long COVID'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction protocol'],
                ['CES 20 min', 'tDCS F6', 'TPS thalamus Cz', 'Stimulus control'],
                ['taVNS 20 min', 'tDCS F3', 'TPS mPFC', 'Progressive relaxation'],
            ],
            'task_pairing': 'CBT-I adapted for long COVID, sleep restriction therapy, stimulus control, progressive muscle relaxation.',
            'fnon_hypothesis': 'Long COVID sleep disruption reflects thalamic function impairment by neuroinflammation. CES directly targets thalamic sleep gating circuits while prefrontal tDCS reduces hyperarousal.',
        },
        {
            'code': 'P7', 'name': 'Anxiety & Mental Health (Long COVID)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC+vmPFC', 'Illness CBT'],
            'card_left': ['Network: SN + LIMBIC dysregulation', 'Key target: DLPFC, vmPFC, SN', 'Priority: Illness-related anxiety'],
            'card_right': ['TPS: T1 + FT4', 'tDCS: C8/F1', 'PlatoScience: C7-PS/FP4', 'CBT task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety regulation', 'Activate', 'T1 / C8 / FP4', 'Emerging'],
                ['vmPFC', 'Safety signal', 'Strengthen', 'FT6 / F1', 'Emerging'],
                ['SN nodes', 'Symptom anxiety', 'Reduce', 'FT4 / Cz', 'Emerging'],
                ['Amygdala', 'Health fear', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['ACC', 'Worry circuit', 'Modulate', 'T5 / C5', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC', 'CBT illness anxiety'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Illness acceptance ACT'],
                ['taVNS 20 min', 'tDCS F1', 'TPS SN suppress', 'Symptom diary rational'],
                ['CES 20 min', 'tDCS C8', 'TPS amygdala', 'Breathing + grounding'],
            ],
            'task_pairing': 'CBT for illness anxiety, illness acceptance ACT, rational symptom diary, breathing and grounding exercises.',
            'fnon_hypothesis': 'Long COVID anxiety reflects illness-specific SN hyperactivation amplifying symptom fear. DLPFC TPS during illness acceptance work strengthens reappraisal pathways.',
        },
        {
            'code': 'P8', 'name': 'Dyspnea & Breathlessness',
            'sozo_bar': ['taVNS 40 min', 'tDCS C3 insula', 'TPS insula FT5', 'Breathing retraining'],
            'card_left': ['Network: Insula + autonomic dyspnea circuit', 'Key target: Insula, ACC, brainstem', 'Priority: Dyspnea threshold recalibration'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C3/F3', 'PlatoScience: C5-PS/FP3', 'Breathing task'],
            'brain_targets': [
                ['Insula', 'Dyspnea integration', 'Normalize', 'T3 / C3 / FP3', 'Emerging'],
                ['ACC', 'Dyspnea distress', 'Modulate', 'T5 / C5', 'Emerging'],
                ['vmPFC', 'Safety breathing', 'Strengthen', 'FT6 / F3', 'Emerging'],
                ['Brainstem (taVNS)', 'Respiratory-vagal', 'Modulate', 'taVNS extended', 'Evidence B'],
                ['M1 respiratory', 'Breathing motor', 'Support', 'TPS Cz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C3 insula', 'TPS insula', 'Breathing retraining physio'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS ACC', 'Dysfunctional breathing CBT'],
                ['taVNS 40 min', 'tDCS F3', 'TPS vmPFC', 'Paced breathing 6 cpm'],
                ['CES 20 min', 'tDCS C3', 'TPS insula bilateral', 'Respiratory physiotherapy'],
            ],
            'task_pairing': 'Breathing retraining physiotherapy, dysfunctional breathing CBT, paced breathing 6 cpm, respiratory physiotherapy.',
            'fnon_hypothesis': 'Post-COVID dyspnea reflects insula hypervigilance to respiratory sensations with ACC amplification. Insula TPS recalibrates dyspnea threshold while taVNS modulates vagal-respiratory coupling.',
        },
        {
            'code': 'P9', 'name': 'Comprehensive Long COVID',
            'sozo_bar': ['taVNS 30 min', 'HDCstim F3/F4+C3/C4', 'TPS FT9 rotating', 'Holistic rehab'],
            'card_left': ['Network: Multi-system neurological disruption', 'Key target: Full network rehabilitation', 'Priority: Holistic recovery'],
            'card_right': ['TPS: FT9 comprehensive', 'tDCS: C1+C3/F1+F3', 'PlatoScience: C1-PS/FP1', 'Holistic program'],
            'brain_targets': [
                ['DLPFC bilateral', 'Cognitive + mood', 'Maximize', 'T1 / C1 / FP1', 'Emerging'],
                ['Insula', 'Autonomic + fatigue', 'Normalize', 'T3 / C3', 'Emerging'],
                ['ACC', 'Attention + pain', 'Modulate', 'T5 / C5', 'Emerging'],
                ['vmPFC', 'Mood + safety', 'Strengthen', 'FT6 / F3', 'Emerging'],
                ['Hippocampus', 'Memory recovery', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'HDCstim F3/F4', 'TPS DLPFC rotating', 'Long COVID rehab program'],
                ['CES 20 min', 'PlatoScience Variant B+D', 'TPS rotating cognitive+autonomic', 'Multi-disciplinary MDT'],
                ['taVNS 20 min', 'tDCS C1+C3', 'TPS comprehensive rotating', 'Pacing + cognitive'],
                ['CES 20 min', 'HDCstim C3/C4', 'TPS insula+DLPFC', 'Holistic wellness protocol'],
            ],
            'task_pairing': 'Long COVID comprehensive rehabilitation, multi-disciplinary team approach, pacing + cognitive + autonomic combined.',
            'fnon_hypothesis': 'Comprehensive long COVID reflects multi-system neurological disruption requiring holistic network targeting. Rotating SOZO protocol addresses CEN, autonomic, fatigue, and mood circuits in coordinated sessions.',
        },
    ],
    'task_pairing_rows': [
        ['Cognitive rehab', 'Post-TPS', 'Cognitive', 'P1'],
        ['Pacing program', 'Post-session', 'Fatigue', 'P2'],
        ['HRV biofeedback', 'During taVNS', 'Autonomic', 'P3'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P4'],
        ['Pain education', 'Post-TPS', 'Pain', 'P5'],
        ['CBT-I sleep', 'Evening CES', 'Sleep', 'P6'],
        ['Illness CBT', 'Post-TPS', 'Anxiety', 'P7'],
        ['Breathing retraining', 'Concurrent tDCS', 'Respiratory', 'P8'],
        ['MDT rehab', 'Full session', 'Comprehensive', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'PCFS, PROMIS fatigue', 'Function + fatigue', 'PEM monitoring'],
        ['Week 4', 'PCFS, MoCA, PHQ-9', 'Cognition + mood + function', 'Adjust if PEM triggered'],
        ['Week 6', 'Full long COVID battery', 'All domains', 'Phase 2 decision'],
        ['Week 10', 'PCFS, PROMIS, QoL', 'Long-term trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment', 'All domains', 'Recovery trajectory'],
        ['Month 6', 'Full reassessment + work capacity', 'Return to function', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(4, 3, 3, 3, 5, 4, 3, 3, 4),
}
