"""
Partners-tier All-In-One Protocol data — ms.
Auto-split from partners_all_in_one_data.py. Edit this file to modify ms data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['ms'] = {
    'display_name': 'Multiple Sclerosis — Symptom Management',
    'short': 'MS',
    'condition_slug': 'ms',
    'icd10': 'G35',
    'tps_warning': (
        "TPS use in Multiple Sclerosis is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for MS symptom management "
        "is emerging. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Demyelination-driven network inefficiency / CEN hypofunction / SMN asymmetry / LIMBIC-fatigue overlap',
    'fnon_montage_selection': [
        ['Cognitive impairment dominant', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Fatigue dominant', 'HDCstim tDCS F3/Fz / CES protocol'],
        ['Spasticity / motor', 'tDCS C3/C4 anodes bilateral'],
        ['Depression MS', 'tDCS F3 anode / F4 cathode'],
        ['Pain MS', 'tDCS C3/C4 + CES'],
    ],
    'tps': [
        ['T1', 'DLPFC cognitive', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T2', 'M1 motor (spasticity)', 'C3/C4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'Fatigue circuit', 'F3 + Fz', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'ACC attention', 'Fz / ACC-proxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Post-MS depression', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN cognitive restore', 'CEN hypofunction', 'F3/F4 bilateral', 'Cognitive compensation', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT2', 'SMN spasticity', 'SMN hyperexcitability', 'C3/C4 bilateral', 'Spasticity reduction', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT3', 'Fatigue-CEN overlap', 'Fatigue circuit', 'F3/Fz bilateral', 'Neural efficiency', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT4', 'DMN normalize', 'DMN disruption', 'mPFC + PCC', 'Default mode stability', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'SN dysregulation', 'SN hyperactivation', 'Cz + insula', 'Fatigue salience reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Depression-MS', 'LIMBIC dysregulation', 'DLPFC + vmPFC', 'Mood restoration', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Pain MS central', 'Central sensitization', 'M1 bilateral Cz', 'Pain modulation', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT8', 'Bladder/autonomic', 'Autonomic dysregulation', 'Cz + C3/C4', 'Cortical bladder control', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Comprehensive MS', 'Multi-network', 'Rotating cognitive+motor', 'Holistic MS protocol', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Cognitive MS', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C2', 'Fatigue', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Spasticity M1', 'C3/C4 bilateral / Oz', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Depression MS', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C5', 'Pain MS', 'C3/C4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C6', 'Attention', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Walking/balance', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C8', 'Bladder function', 'Cz anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Cognitive compensation', '2 mA', '20 min'],
        ['F2', 'Fatigue circuit', 'Fatigue network', 'F3 anode / Cz cathode', 'Neural efficiency', '2 mA', '20 min'],
        ['F3', 'SMN spasticity', 'SMN hyperexcitability', 'C3/C4 bilateral', 'Motor tone normalize', '2 mA', '20 min'],
        ['F4', 'Depression-MS', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Mood restoration', '2 mA', '20 min'],
        ['F5', 'Pain central MS', 'Central pain', 'C3/C4 anodes / Oz', 'Pain gate activation', '2 mA', '20 min'],
        ['F6', 'Autonomic', 'Autonomic dysregulation', 'Cz anode / shoulder', 'Bladder + autonomic', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Cognitive boost', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'MS cognitive tasks'],
        ['C2-PS', 'Energy management', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'MS fatigue'],
        ['C3-PS', 'Mood uplift', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'MS depression'],
        ['C4-PS', 'Focus', 'Variant B', 'F3/Cz', '1.4 mA', '20 min', 'Attention MS'],
        ['C5-PS', 'Pain support', 'Variant E', 'C3/C4', '1.4 mA', '20 min', 'MS pain'],
        ['C6-PS', 'Sleep MS', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'MS insomnia'],
        ['C7-PS', 'Spasticity support', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'Spasticity + tDCS'],
        ['C8-PS', 'Balance/gait', 'Variant E', 'Cz/C3', '1.4 mA', '20 min', 'Gait MS'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN cognitive', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'Fatigue', 'Fatigue circuit', 'Variant D', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP3', 'SMN motor', 'SMN dysfunction', 'Variant F', 'C3/C4', '1.4 mA', '20 min'],
        ['FP4', 'LIMBIC mood', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP5', 'Pain MS', 'Central pain', 'Variant E', 'C3/C4', '1.4 mA', '20 min'],
        ['FP6', 'Sleep MS', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Cognitive Impairment (MS)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Cognitive rehab'],
            'card_left': ['Network: CEN white matter inefficiency', 'Key target: DLPFC bilateral', 'Priority: Cognitive compensation'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Working memory', 'Activate', 'T1 / C1 / FP1', 'Evidence B'],
                ['PFC bilateral', 'Executive function', 'Upregulate', 'FT1 / C6', 'Emerging'],
                ['Hippocampus', 'Learning', 'Support (taVNS)', 'taVNS', 'Emerging'],
                ['ACC', 'Attention', 'Activate', 'T4 / C6', 'Emerging'],
                ['Thalamus', 'Arousal (CES)', 'Normalize', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Computerized cognitive rehab'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS bilateral PFC', 'Working memory training'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Attention and processing speed'],
                ['CES 20 min', 'tDCS C6', 'TPS hippocampus', 'Memory encoding tasks'],
            ],
            'task_pairing': 'Computerized cognitive rehabilitation, working memory n-back, processing speed training, memory encoding tasks.',
            'fnon_hypothesis': 'MS cognitive impairment reflects white matter disconnection reducing CEN efficiency. Bilateral DLPFC TPS compensates by activating residual cortical tissue and promoting alternative neural routing.',
        },
        {
            'code': 'P2', 'name': 'MS-Related Fatigue',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fz', 'TPS FT3 fatigue', 'Energy pacing'],
            'card_left': ['Network: Fatigue-CEN overlap / neural inefficiency', 'Key target: DLPFC, SMA, ACC', 'Priority: Neural efficiency restoration'],
            'card_right': ['TPS: T3 + FT3', 'tDCS: C2/F2', 'PlatoScience: C2-PS/FP2', 'Pacing task'],
            'brain_targets': [
                ['DLPFC', 'Effort regulation', 'Activate', 'T3 / C2 / FP2', 'Evidence B'],
                ['SMA', 'Motor effort', 'Upregulate', 'FT2 / Fz', 'Emerging'],
                ['ACC', 'Fatigue monitoring', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Thalamus (CES)', 'Arousal', 'Activate', 'CES protocol', 'Emerging'],
                ['Insula', 'Fatigue perception', 'Normalize', 'FT5 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/Fz', 'TPS DLPFC fatigue', 'Energy conservation training'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', 'Pacing program'],
                ['taVNS 20 min', 'tDCS C2', 'TPS SMA', 'Graded exercise program'],
                ['CES 20 min', 'tDCS F2', 'TPS insula', 'Fatigue diary'],
            ],
            'task_pairing': 'Energy conservation training, pacing program, graded exercise therapy, fatigue diary with activity optimization.',
            'fnon_hypothesis': 'MS fatigue reflects increased neural effort required for routine tasks due to demyelination. DLPFC TPS reduces perceived effort cost, while CES restores thalamic arousal tone.',
        },
        {
            'code': 'P3', 'name': 'Spasticity (MS)',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3/C4 bilateral', 'TPS M1 bilateral', 'Stretching program'],
            'card_left': ['Network: SMN hyperexcitability bilateral', 'Key target: M1 bilateral, SMA', 'Priority: Motor tone normalization'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C3/F3', 'PlatoScience: C7-PS/FP3', 'Stretch + physio'],
            'brain_targets': [
                ['M1 bilateral', 'Spasticity drive', 'Normalize', 'T2 / C3 / FP3', 'Evidence B'],
                ['SMA', 'Tonic motor', 'Balance', 'FT2 / Fz', 'Emerging'],
                ['Cerebellum', 'Coordination', 'Activate', 'TPS lateral', 'Emerging'],
                ['Thalamus (taVNS)', 'Motor relay', 'Modulate', 'taVNS', 'Emerging'],
                ['Spinal (descending)', 'Inhibitory tracts', 'Activate (TPS)', 'TPS M1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3/C4 bilateral', 'TPS M1 bilateral', 'Stretching + physiotherapy'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS SMA', 'Active movement tasks'],
                ['taVNS 20 min', 'tDCS C3', 'TPS cerebellum', 'Balance training'],
                ['CES 20 min', 'tDCS F3', 'TPS M1+SMA', 'Constraint movement'],
            ],
            'task_pairing': 'Passive and active stretching, physiotherapy, balance training, active movement tasks.',
            'fnon_hypothesis': 'MS spasticity reflects demyelination of descending inhibitory tracts allowing unchecked M1 excitability. Bilateral M1 TPS restores cortical-spinal inhibitory balance.',
        },
        {
            'code': 'P4', 'name': 'Depression (MS)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood circuit support'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C4/F4', 'PlatoScience: C3-PS/FP4', 'BA protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood upregulation', 'Activate', 'T5 / C4 / FP4', 'Evidence B'],
                ['vmPFC', 'Positive affect', 'Restore', 'FT6 / F4', 'Emerging'],
                ['ACC', 'Mood monitoring', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasant activity planning'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'CBT for MS mood'],
                ['CES 20 min', 'tDCS F4', 'TPS amygdala', 'Meaning-focused therapy'],
            ],
            'task_pairing': 'Behavioral activation schedule, pleasant activity planning, CBT adapted for MS, meaning-focused intervention.',
            'fnon_hypothesis': 'MS depression reflects both disease burden and direct LIMBIC circuit disruption from lesion load. L-DLPFC TPS provides mood uplift independent of pharmacological pathways.',
        },
        {
            'code': 'P5', 'name': 'Pain (MS — Central)',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 bilateral', 'TPS M1+DLPFC', 'Pain education'],
            'card_left': ['Network: Central sensitization + demyelination', 'Key target: M1 bilateral, DLPFC, ACC', 'Priority: Pain gate restoration'],
            'card_right': ['TPS: T2+T1 + FT7', 'tDCS: C5/F5', 'PlatoScience: C5-PS/FP5', 'Pain mgmt'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T2 / C5 / FP5', 'Evidence B'],
                ['DLPFC', 'Top-down pain', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Pain affect', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Insula', 'Pain integration', 'Normalize', 'FT7 / C6', 'Emerging'],
                ['Thalamus (CES)', 'Pain relay', 'Modulate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3/C4', 'TPS M1', 'Pain management program'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS DLPFC', 'Acceptance pain ACT'],
                ['taVNS 20 min', 'tDCS C5', 'TPS ACC', 'Graded motor imagery'],
                ['CES 20 min', 'tDCS F5', 'TPS insula', 'Pain education MS'],
            ],
            'task_pairing': 'Pain management program, acceptance-based pain therapy, graded motor imagery, MS-specific pain education.',
            'fnon_hypothesis': 'MS central pain reflects demyelination disrupting descending inhibitory tracts. M1 TPS activates remaining corticospinal inhibitory pathways compensating for tract damage.',
        },
        {
            'code': 'P6', 'name': 'Walking & Balance (MS)',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz/C3/C4', 'TPS SMA+M1', 'Gait therapy'],
            'card_left': ['Network: SMN + cerebellar disruption', 'Key target: SMA, M1 bilateral', 'Priority: Gait efficiency'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C7/F3', 'PlatoScience: C8-PS/FP3', 'Gait task'],
            'brain_targets': [
                ['SMA', 'Gait initiation', 'Activate', 'FT2 / Fz / FP3', 'Evidence B'],
                ['M1 bilateral', 'Leg motor', 'Upregulate', 'T2 / C3', 'Evidence B'],
                ['Cerebellum', 'Balance', 'Activate', 'TPS lateral', 'Emerging'],
                ['PMC', 'Gait planning', 'Activate', 'TPS F3/F4', 'Emerging'],
                ['Basal ganglia', 'Rhythm', 'Support', 'TPS frontal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS Fz/C3/C4', 'TPS SMA', 'Treadmill gait therapy'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS cerebellum', 'Balance training'],
                ['taVNS 20 min', 'tDCS C7', 'TPS M1 bilateral', 'FES-gait combined'],
                ['CES 20 min', 'tDCS F3', 'TPS PMC', 'Rhythmic cue walking'],
            ],
            'task_pairing': 'Treadmill gait therapy, balance training, FES-gait combined therapy, rhythmic auditory cue walking.',
            'fnon_hypothesis': 'MS gait impairment reflects SMA-M1 circuit disruption from lesion load. SMA TPS during treadmill training maximizes gait program benefit through activity-dependent plasticity.',
        },
        {
            'code': 'P7', 'name': 'Anxiety (MS-Related)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC+vmPFC', 'CBT MS-anxiety'],
            'card_left': ['Network: SN hyperactivation + disease anxiety', 'Key target: DLPFC, vmPFC, amygdala', 'Priority: MS-specific worry'],
            'card_right': ['TPS: T1 + FT5', 'tDCS: C1/F1', 'PlatoScience: C4-PS/FP1', 'CBT task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety regulation', 'Activate', 'T1 / C1 / FP1', 'Evidence B'],
                ['vmPFC', 'Safety signal', 'Strengthen', 'FT6 / F4', 'Emerging'],
                ['SN nodes', 'Disease worry', 'Reduce', 'FT5 / Cz', 'Emerging'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['ACC', 'Worry monitoring', 'Modulate', 'T4 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC', 'MS-specific CBT anxiety'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Acceptance MS condition'],
                ['taVNS 20 min', 'tDCS C1', 'TPS SN suppress', 'Worry postponement'],
                ['CES 20 min', 'tDCS F1', 'TPS amygdala', 'Disease-anxiety exposure'],
            ],
            'task_pairing': 'MS-specific CBT for health anxiety, acceptance of disease condition, worry postponement, disease-related exposure tasks.',
            'fnon_hypothesis': 'MS anxiety reflects SN hyperactivation amplifying disease-specific fears. DLPFC + vmPFC TPS provides cognitive reappraisal capacity for illness-related anxiety.',
        },
        {
            'code': 'P8', 'name': 'Bladder / Autonomic Dysfunction',
            'sozo_bar': ['taVNS 40 min', 'tDCS Cz/C3', 'TPS FT8 bladder', 'Pelvic floor PT'],
            'card_left': ['Network: Cortical bladder control + autonomic', 'Key target: Cz, insula, SMA', 'Priority: Cortical bladder pathway'],
            'card_right': ['TPS: FT8 + T2', 'tDCS: C8/F6', 'PlatoScience: C6-PS/FP6', 'Bladder PT'],
            'brain_targets': [
                ['Cz (bladder M1)', 'Bladder motor control', 'Activate', 'FT8 / C8 / FP6', 'Emerging'],
                ['Insula', 'Bladder sensation', 'Normalize', 'FT5 / C6', 'Emerging'],
                ['SMA', 'Voiding planning', 'Regulate', 'FT2 / Fz', 'Emerging'],
                ['ACC', 'Urgency control', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Brainstem (taVNS)', 'Vagal-bladder', 'Modulate', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS Cz bilateral', 'TPS bladder Cz', 'Pelvic floor PT'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS insula', 'Bladder training protocol'],
                ['taVNS 40 min', 'tDCS C8', 'TPS SMA', 'Timed voiding schedule'],
                ['CES 20 min', 'tDCS F6', 'TPS ACC urgency', 'Urgency suppression training'],
            ],
            'task_pairing': 'Pelvic floor physiotherapy, bladder training protocol, timed voiding schedule, urgency suppression techniques.',
            'fnon_hypothesis': 'MS bladder dysfunction reflects demyelination of cortical bladder pathways. Cortical bladder area (Cz) TPS activates residual descending bladder control circuits.',
        },
        {
            'code': 'P9', 'name': 'Progressive MS — Comprehensive',
            'sozo_bar': ['taVNS 20 min', 'HDCstim multisite', 'TPS FT9 rotating', 'Adaptive rehab'],
            'card_left': ['Network: Multi-network progressive disruption', 'Key target: Full network compensation', 'Priority: Functional preservation'],
            'card_right': ['TPS: FT9 comprehensive', 'tDCS: C1+C3/F1+F3', 'PlatoScience: C1-PS/FP1', 'Adaptive rehab'],
            'brain_targets': [
                ['DLPFC bilateral', 'Cognitive preservation', 'Maximize', 'T1 / C1 / FP1', 'Evidence B'],
                ['M1 bilateral', 'Motor preservation', 'Support', 'T2 / C3', 'Evidence B'],
                ['SMA', 'Functional motor', 'Upregulate', 'FT2 / Fz', 'Emerging'],
                ['Hippocampus', 'Memory preservation', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
                ['vmPFC', 'Quality of life', 'Maintain', 'FT6 / F4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'HDCstim F3/F4+C3/C4', 'TPS rotating cognitive+motor', 'Adaptive rehabilitation'],
                ['CES 20 min', 'PlatoScience Variant B+E', 'TPS DLPFC+M1 alternating', 'Goal-directed therapy'],
                ['taVNS 20 min', 'tDCS C1+C3', 'TPS comprehensive rotating', 'Quality of life focus'],
                ['CES 20 min', 'HDCstim Cz+F3', 'TPS multisite', 'Functional preservation program'],
            ],
            'task_pairing': 'Adaptive rehabilitation, goal-directed therapy, quality of life focus program, functional preservation training.',
            'fnon_hypothesis': 'Progressive MS requires preservation strategy across all networks. SOZO comprehensive rotating protocol maintains maximal functional capacity against progressive demyelination.',
        },
    ],
    'task_pairing_rows': [
        ['Cognitive rehab', 'Post-TPS', 'Cognitive', 'P1'],
        ['Energy pacing', 'Post-session', 'Fatigue', 'P2'],
        ['Stretching', 'Concurrent tDCS', 'Spasticity', 'P3'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P4'],
        ['Pain education', 'Post-TPS', 'Pain', 'P5'],
        ['Gait therapy', 'Concurrent tDCS', 'Motor', 'P6'],
        ['CBT anxiety', 'Post-TPS', 'Anxiety', 'P7'],
        ['Bladder training', 'Post-TPS', 'Autonomic', 'P8'],
        ['Adaptive rehab', 'Full session', 'Comprehensive', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'MFIS, MSSS, MoCA', 'Fatigue + symptoms + cognition', 'Adjust fatigue protocol'],
        ['Week 4', 'MFIS, T25FW, PHQ-9', 'Fatigue + walk + mood', 'Motor protocol review'],
        ['Week 6', 'Full MS battery + QoL', 'Comprehensive assessment', 'Phase 2 decision'],
        ['Week 10', 'MFIS, MSSS, EDSS', 'Disability trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'MRI review + QoL', 'Disease activity + function', 'Annual neuro review'],
    ],
    'plato_programs': _plato_programs_default(4, 3, 3, 3, 5, 4, 4, 4, 4),
}
