"""
Partners-tier All-In-One Protocol data — ocd.
Auto-split from partners_all_in_one_data.py. Edit this file to modify ocd data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['ocd'] = {
    'display_name': 'Obsessive-Compulsive Disorder',
    'short': 'OCD',
    'condition_slug': 'ocd',
    'icd10': 'F42',
    'tps_warning': (
        "TPS use in Obsessive-Compulsive Disorder is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for OCD "
        "is emerging. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Cortico-striato-thalamo-cortical (CSTC) hyperactivation / OFC-ACC error signal / DLPFC hypofunction',
    'fnon_montage_selection': [
        ['OFC dominant', 'HDCstim tDCS Fp2 cathode / F3 anode'],
        ['ACC dominant', 'HDCstim Cz cathode / F3/F4 anodes'],
        ['DLPFC augmentation', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Caudate-SMA circuit', 'tDCS Fz cathode + F3 anode'],
        ['Contamination OCD', 'tDCS F3/Fp2 + TPS OFC'],
    ],
    'tps': [
        ['T1', 'SMA/pre-SMA inhibition', 'Fz / SMA-proxy', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T2', 'OFC modulation', 'Fp2 / OFC-proxy', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T3', 'DLPFC activation', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'ACC modulation', 'Fz / ACC-proxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Bilateral DLPFC', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'OFC error signal suppress', 'OFC hyperactivation', 'Fp2 bilateral', 'Obsessive appraisal reduction', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT2', 'SMA-compulsion disrupt', 'SMA hyperactivation', 'Fz SMA-proxy', 'Compulsive urge inhibition', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT3', 'DLPFC augment', 'CEN hypofunction', 'F3/F4 bilateral', 'Inhibitory control restore', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT4', 'ACC error normalize', 'ACC hyperactivation', 'Fz ACC-proxy', 'Error signal recalibration', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT5', 'Caudate circuit', 'Caudate hyperactivation', 'Lateral frontal C3/C4', 'Habit-compulsion break', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Thalamic gating', 'CSTC loop', 'SMA + Cz bilateral', 'Thalamic loop disruption', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT7', 'Insula contamination', 'Disgust-insula', 'C3 insula proxy', 'Disgust response reduction', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT8', 'Checking compulsions', 'OFC-DLPFC mismatch', 'Fp2 + F3', 'Certainty signal restore', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT9', 'Treatment-resistant OCD', 'Full CSTC', 'Rotating OFC/SMA/DLPFC', 'Multi-node CSTC targeting', '0.22 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'OFC inhibit', 'Fp2 cathode / F3 anode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'DLPFC augment', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'SMA suppress', 'Fz cathode / F3 anode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'ACC modulation', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Bilateral inhibitory', 'Fp2 cathode / F3/F4 anodes', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Contamination insula', 'C3 cathode / F3 anode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Comorbid depression', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Hoarding phenotype', 'F3/F4 bilateral anodes', '2 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'OFC suppress', 'OFC hyperactivation', 'Fp2 cathode / F3 anode', 'Obsessive appraisal down', '1.5 mA', '20 min'],
        ['F2', 'SMA break', 'SMA compulsion', 'Fz cathode / F3 anode', 'Compulsive urge inhibition', '2 mA', '20 min'],
        ['F3', 'DLPFC control', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Inhibitory control', '2 mA', '20 min'],
        ['F4', 'Insula disgust', 'Insula hyperactivation', 'C3 cathode / F3 anode', 'Disgust reduction', '2 mA', '20 min'],
        ['F5', 'ACC normalize', 'ACC error signal', 'Fz anode / Oz cathode', 'Error recalibration', '2 mA', '20 min'],
        ['F6', 'Comorbid anxiety', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Anxiety component', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Focus + inhibit', 'Variant B', 'F3/Fp2', '1.4 mA', '20 min', 'ERP augmentation'],
        ['C2-PS', 'OFC calm', 'Variant D', 'Fp2/F3', '1.2 mA', '20 min', 'Pre-ERP session'],
        ['C3-PS', 'Mood comorbid', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Depression comorbid'],
        ['C4-PS', 'Anxiety calm', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Anxiety comorbid'],
        ['C5-PS', 'Cognitive control', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Inhibitory tasks'],
        ['C6-PS', 'Insula calm', 'Variant F', 'C3/F3', '1.4 mA', '20 min', 'Contamination OCD'],
        ['C7-PS', 'Checking circuit', 'Variant B', 'F3/Fp2', '1.4 mA', '20 min', 'Checking rituals'],
        ['C8-PS', 'Hoarding', 'Variant C', 'F3/F4', '1.4 mA', '20 min', 'Hoarding phenotype'],
    ],
    'fnon_plato': [
        ['FP1', 'OFC suppress', 'OFC hyperactivation', 'Variant D', 'Fp2/F3', '1.2 mA', '20 min'],
        ['FP2', 'DLPFC control', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'SMA break', 'SMA compulsion', 'Variant D', 'Fz/F3', '1.2 mA', '20 min'],
        ['FP4', 'Insula disgust', 'Insula hyperactivation', 'Variant F', 'C3/F3', '1.4 mA', '20 min'],
        ['FP5', 'Anxiety comorbid', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP6', 'Mood comorbid', 'LIMBIC', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Contamination OCD',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp2 cathode/F3', 'TPS OFC+insula', 'ERP contamination'],
            'card_left': ['Network: OFC + insula disgust circuit', 'Key target: OFC Fp2, insula C3', 'Priority: Disgust-obsession circuit'],
            'card_right': ['TPS: T2 + FT7', 'tDCS: C1/F4', 'PlatoScience: C6-PS/FP4', 'ERP task'],
            'brain_targets': [
                ['OFC', 'Contamination appraisal', 'Suppress', 'T2 / C1 / FP1', 'Evidence B'],
                ['Insula', 'Disgust signal', 'Downregulate', 'FT7 / C6 / FP4', 'Emerging'],
                ['DLPFC', 'Inhibitory control', 'Activate', 'T3 / C2', 'Evidence B'],
                ['ACC', 'Error monitoring', 'Modulate', 'T4 / C4', 'Emerging'],
                ['Caudate', 'Compulsive habit', 'Disrupt', 'FT5 / lateral frontal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1 Fp2 cathode', 'TPS OFC', 'ERP contamination hierarchy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS insula', 'Disgust habituation'],
                ['taVNS 20 min', 'tDCS F4', 'TPS OFC+insula', 'Ritual prevention 30 min'],
                ['CES 20 min', 'tDCS C6', 'TPS DLPFC', 'Cognitive defusion'],
            ],
            'task_pairing': 'ERP contamination hierarchy, disgust habituation tasks, ritual prevention, cognitive defusion for contamination thoughts.',
            'fnon_hypothesis': 'Contamination OCD reflects OFC-insula disgust circuit hyperactivation creating false-alarm contamination signals. TPS + ERP drives habituation through direct neural desensitization.',
        },
        {
            'code': 'P2', 'name': 'Checking Compulsions',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp2 cathode/F3', 'TPS OFC+DLPFC', 'ERP checking'],
            'card_left': ['Network: OFC-DLPFC mismatch / certainty failure', 'Key target: OFC, DLPFC, ACC', 'Priority: Certainty signal restoration'],
            'card_right': ['TPS: T2+T3 + FT8', 'tDCS: C1/F3', 'PlatoScience: C7-PS/FP2', 'Checking ERP'],
            'brain_targets': [
                ['OFC', 'False incomplete signal', 'Suppress', 'T2 / C1 / FP1', 'Evidence B'],
                ['DLPFC', 'Certainty recall', 'Activate', 'T3 / C2 / FP2', 'Evidence B'],
                ['ACC', 'Incompleteness', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['SMA', 'Action urge', 'Inhibit', 'T1 / C3', 'Evidence B'],
                ['Memory circuits', 'Reality monitoring', 'Strengthen', 'taVNS + TPS T5', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1', 'TPS OFC+DLPFC', 'Checking ERP with memory'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Certainty tolerance exercise'],
                ['taVNS 20 min', 'tDCS F3', 'TPS SMA', 'Action urge surfing'],
                ['CES 20 min', 'tDCS C5', 'TPS bilateral', 'Reality monitoring tasks'],
            ],
            'task_pairing': 'Checking ERP with memory confidence tasks, certainty tolerance exercises, urge surfing, reality monitoring training.',
            'fnon_hypothesis': 'Checking OCD reflects OFC false-incomplete signals overwhelming DLPFC certainty recall. DLPFC TPS strengthens memory confidence to resist re-checking urges.',
        },
        {
            'code': 'P3', 'name': 'Intrusive Thoughts (Pure O)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fp2', 'TPS DLPFC+OFC', 'ACT defusion'],
            'card_left': ['Network: Thought-action fusion / ACC hyperactivation', 'Key target: DLPFC, OFC, ACC', 'Priority: Thought-reality distinction'],
            'card_right': ['TPS: T3+T2 + FT3', 'tDCS: C2/F1', 'PlatoScience: C5-PS/FP2', 'Defusion task'],
            'brain_targets': [
                ['DLPFC', 'Thought inhibition', 'Activate', 'T3 / C2 / FP2', 'Evidence B'],
                ['OFC', 'Thought danger appraisal', 'Suppress', 'T2 / C1', 'Evidence B'],
                ['ACC', 'Thought monitoring', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['mPFC', 'Self-referential thought', 'Normalize', 'FT6 / Fp1', 'Emerging'],
                ['Amygdala', 'Thought-affect fusion', 'Downregulate', 'FT3 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C2', 'TPS DLPFC', 'ACT defusion exercises'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS OFC', 'Intrusive thought ERP'],
                ['taVNS 20 min', 'tDCS F1', 'TPS ACC', 'Thought-record CBT'],
                ['CES 20 min', 'tDCS C5', 'TPS mPFC', 'Mindfulness thought labeling'],
            ],
            'task_pairing': 'ACT defusion exercises, intrusive thought ERP (imaginal), CBT thought records, mindfulness thought labeling.',
            'fnon_hypothesis': 'Pure-O OCD reflects thought-action fusion driven by OFC danger appraisal and ACC hypermonitoring. DLPFC TPS during defusion tasks weakens the thought-threat linkage.',
        },
        {
            'code': 'P4', 'name': 'Hoarding Disorder',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC+vmPFC', 'Sorting task'],
            'card_left': ['Network: DLPFC decision deficit + vmPFC over-attachment', 'Key target: DLPFC bilateral, vmPFC', 'Priority: Decision-making restoration'],
            'card_right': ['TPS: T5 + FT3', 'tDCS: C8/F3', 'PlatoScience: C8-PS/FP2', 'Sorting task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Decision making', 'Activate', 'T5 / C8 / FP2', 'Evidence B'],
                ['vmPFC', 'Object attachment', 'Normalize', 'T2 / F1', 'Emerging'],
                ['ACC', 'Discarding distress', 'Modulate', 'T4 / C4', 'Emerging'],
                ['Insula', 'Loss aversion', 'Normalize', 'FT7 / C6', 'Emerging'],
                ['OFC', 'Acquisition urge', 'Suppress', 'T2 / C1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C8 bilateral', 'TPS DLPFC', 'Sorting and discarding ERP'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS vmPFC', 'Decision-making training'],
                ['taVNS 20 min', 'tDCS F3', 'TPS OFC', 'Acquisition ban ERP'],
                ['CES 20 min', 'tDCS C4', 'TPS insula', 'Loss tolerance exercise'],
            ],
            'task_pairing': 'Sorting and discarding ERP, decision-making training, acquisition ban exercises, loss tolerance practice.',
            'fnon_hypothesis': 'Hoarding reflects DLPFC decision-making deficit combined with vmPFC over-attribution of emotional value to objects. Bilateral DLPFC TPS during sorting tasks improves discarding decisions.',
        },
        {
            'code': 'P5', 'name': 'Symmetry / Ordering OCD',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz cathode/F3', 'TPS SMA+DLPFC', 'ERP ordering'],
            'card_left': ['Network: SMA hyperactivation + incompleteness', 'Key target: SMA, DLPFC, ACC', 'Priority: "Not just right" signal'],
            'card_right': ['TPS: T1+T3 + FT2', 'tDCS: C3/F3', 'PlatoScience: C1-PS/FP3', 'Asymmetry ERP'],
            'brain_targets': [
                ['SMA', 'Action urge generation', 'Inhibit', 'T1 / C3 / FP3', 'Evidence B'],
                ['DLPFC', 'Resist urge', 'Activate', 'T3 / C2', 'Evidence B'],
                ['ACC', '"Not just right"', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['Somatosensory', 'Tactile incompleteness', 'Normalize', 'TPS C3/C4', 'Emerging'],
                ['Caudate', 'Habit ordering', 'Disrupt', 'FT5 / lateral', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 Fz cathode', 'TPS SMA', 'Asymmetry tolerance ERP'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', '"Good enough" cognitive task'],
                ['taVNS 20 min', 'tDCS F3', 'TPS ACC', 'Urge surfing symmetry'],
                ['CES 20 min', 'tDCS C5', 'TPS bilateral SMA', 'Incompleteness habituation'],
            ],
            'task_pairing': 'Asymmetry tolerance ERP, "good enough" cognitive training, urge surfing, incompleteness habituation exercises.',
            'fnon_hypothesis': 'Symmetry OCD reflects SMA hyperactivation generating persistent "not just right" incompleteness signals. SMA TPS + ERP extinguishes the sensorimotor incompleteness circuit.',
        },
        {
            'code': 'P6', 'name': 'OCD + Depression Comorbidity',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode/Fp2', 'TPS DLPFC+OFC', 'BA + ERP combined'],
            'card_left': ['Network: OFC + LIMBIC dysregulation', 'Key target: DLPFC L, OFC, ACC', 'Priority: Mood-OCD unified protocol'],
            'card_right': ['TPS: T3+T2 + FT3', 'tDCS: C7/F1', 'PlatoScience: C3-PS/FP6', 'Combined task'],
            'brain_targets': [
                ['DLPFC L', 'Mood + inhibitory', 'Activate', 'T3 / C7 / FP6', 'Evidence B'],
                ['OFC', 'Obsessive appraisal', 'Suppress', 'T2 / C1', 'Evidence B'],
                ['ACC', 'Mood-OCD junction', 'Modulate', 'T4 / C4', 'Emerging'],
                ['Amygdala', 'Affective amplification', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['vmPFC', 'Reward restoration', 'Activate', 'FT1 / F1', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 F3+Fp2', 'TPS DLPFC+OFC', 'BA + ERP session'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS ACC', 'Combined mood-OCD CBT'],
                ['taVNS 20 min', 'tDCS F1', 'TPS DLPFC', 'Pleasant activity + ERP'],
                ['CES 20 min', 'tDCS C3', 'TPS OFC', 'Thought record + ritual prevention'],
            ],
            'task_pairing': 'Combined BA + ERP sessions, mood-OCD CBT integration, pleasant activity scheduling with ritual prevention.',
            'fnon_hypothesis': 'OCD-depression comorbidity shares DLPFC hypofunction as common substrate. L-DLPFC TPS simultaneously augments ERP effectiveness and behavioral activation outcomes.',
        },
        {
            'code': 'P7', 'name': 'OCD with Tic Disorder',
            'sozo_bar': ['taVNS 20 min', 'tDCS SMA cathode/F3', 'TPS SMA+caudate', 'HRT protocol'],
            'card_left': ['Network: SMA-basal ganglia hyperactivation', 'Key target: SMA Fz, caudate proxy', 'Priority: Motor urge suppression'],
            'card_right': ['TPS: T1 + FT2', 'tDCS: C3/F3', 'PlatoScience: C3-PS/FP3', 'HRT task'],
            'brain_targets': [
                ['SMA', 'Tic + compulsion urge', 'Inhibit', 'T1 / C3 / FP3', 'Evidence B'],
                ['Caudate', 'Habit-motor circuit', 'Modulate', 'FT5 / lateral frontal', 'Emerging'],
                ['DLPFC', 'Urge control', 'Activate', 'T3 / C2', 'Evidence B'],
                ['ACC', 'Monitoring both', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['Putamen', 'Motor sequence', 'Normalize', 'TPS C3/C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 SMA cathode', 'TPS SMA', 'HRT habit reversal'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS caudate', 'Competing response training'],
                ['taVNS 20 min', 'tDCS F3', 'TPS DLPFC', 'ERP + tic suppression'],
                ['CES 20 min', 'tDCS C5', 'TPS ACC', 'CBIT comprehensive behavioral'],
            ],
            'task_pairing': 'HRT (Habit Reversal Training), CBIT (Comprehensive Behavioral Intervention for Tics), competing response training, ERP combined.',
            'fnon_hypothesis': 'OCD + Tourette reflects shared SMA-basal ganglia hyperactivation driving both tic and compulsion urges. SMA TPS + HRT addresses both motor symptoms simultaneously.',
        },
        {
            'code': 'P8', 'name': 'Scrupulosity / Religious OCD',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp2 cathode/F3', 'TPS OFC+mPFC', 'Scrupulosity ERP'],
            'card_left': ['Network: OFC moral + mPFC self-judgment', 'Key target: OFC, mPFC, ACC', 'Priority: Moral error signal reduction'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C2-PS/FP1', 'ERP task'],
            'brain_targets': [
                ['OFC', 'Moral transgression fear', 'Suppress', 'T2 / C1 / FP1', 'Evidence B'],
                ['mPFC', 'Self-condemnation', 'Normalize', 'FT6 / Fp1', 'Emerging'],
                ['ACC', 'Moral monitoring', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['DLPFC', 'Cognitive flexibility', 'Activate', 'T3 / C2', 'Evidence B'],
                ['Amygdala', 'Fear of divine punishment', 'Downregulate', 'FT3 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1', 'TPS OFC', 'Scrupulosity ERP with clergy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS mPFC', 'ACT values clarification'],
                ['taVNS 20 min', 'tDCS F1', 'TPS ACC', 'Cognitive defusion for guilt'],
                ['CES 20 min', 'tDCS C5', 'TPS DLPFC', 'Flexible thinking training'],
            ],
            'task_pairing': 'Scrupulosity ERP, ACT values clarification, cognitive defusion for guilt thoughts, flexible religious interpretation exercises.',
            'fnon_hypothesis': 'Scrupulosity reflects OFC moral appraisal hyperactivation with mPFC self-condemnation loop. OFC TPS during ERP reduces false-alarm moral threat signals.',
        },
        {
            'code': 'P9', 'name': 'Treatment-Resistant OCD',
            'sozo_bar': ['taVNS 20 min', 'HDCstim F3/Fp2', 'TPS FT9 rotating', 'Intensive ERP'],
            'card_left': ['Network: Full CSTC hyperactivation', 'Key target: All CSTC nodes', 'Priority: Maximum CSTC disruption'],
            'card_right': ['TPS: FT9 multisite', 'tDCS: C5/F1+F2', 'PlatoScience: C5-PS/FP2', 'Intensive ERP'],
            'brain_targets': [
                ['OFC bilateral', 'Error signal maximal', 'Suppress bilateral', 'T2 bilateral / C5', 'Evidence B'],
                ['SMA', 'Compulsion drive', 'Inhibit', 'T1 / C3', 'Evidence B'],
                ['DLPFC bilateral', 'Inhibitory deficit', 'Maximize', 'T5 / C2', 'Evidence B'],
                ['Caudate bilateral', 'Habit loop', 'Disrupt', 'FT5+FT6 rotating', 'Emerging'],
                ['Thalamus (taVNS)', 'CSTC relay', 'Modulate', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'HDCstim F3/Fp2', 'TPS OFC+SMA', 'Intensive ERP daily'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS DLPFC bilateral', 'Meta-cognitive therapy'],
                ['taVNS 20 min', 'tDCS C5', 'TPS rotating CSTC', 'ACT + ERP combined'],
                ['CES 20 min', 'HDCstim Cz cathode', 'TPS caudate + thalamus', 'D-cycloserine adjunct protocol'],
            ],
            'task_pairing': 'Intensive daily ERP, meta-cognitive therapy, ACT + ERP combined, consider adjunct pharmacological support.',
            'fnon_hypothesis': 'Treatment-resistant OCD requires maximum CSTC circuit disruption. Rotating multisite TPS across OFC, SMA, DLPFC, and caudate provides comprehensive loop disruption not achievable with single-site approaches.',
        },
    ],
    'task_pairing_rows': [
        ['ERP hierarchy', 'Post-TPS', 'Behavioral', 'All phenotypes'],
        ['ACT defusion', 'During tDCS', 'ACT', 'P3, P6, P8'],
        ['HRT tic', 'Post-TPS', 'Behavioral', 'P7'],
        ['Sorting task', 'Concurrent tDCS', 'Behavioral', 'P4'],
        ['Asymmetry tolerance', 'Post-TPS', 'Behavioral', 'P5'],
        ['Scrupulosity ERP', 'Post-TPS', 'Behavioral', 'P8'],
        ['Urge surfing', 'During taVNS', 'Mindfulness', 'P2, P5'],
        ['Decision training', 'During tDCS', 'Cognitive', 'P4'],
    ],
    'followup_rows': [
        ['Week 2', 'Y-BOCS, GAD-7', 'OCD severity + anxiety', 'ERP compliance check'],
        ['Week 4', 'Y-BOCS, PHQ-9, QOLI', 'OCD + function', 'Intensify if <25% reduction'],
        ['Week 6', 'Y-BOCS, CGI', 'Clinical global improvement', 'Phase 2 decision'],
        ['Week 10', 'Y-BOCS + QoL', 'Long-term OCD trajectory', 'Maintenance planning'],
        ['Month 4', 'Full OCD battery', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'Y-BOCS, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(4, 3, 3, 4, 3, 3, 2, 4, 3),
}
