"""
Partners-tier All-In-One Protocol data — ptsd.
Auto-split from partners_all_in_one_data.py. Edit this file to modify ptsd data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['ptsd'] = {
    'display_name': 'Post-Traumatic Stress Disorder',
    'short': 'PTSD',
    'condition_slug': 'ptsd',
    'icd10': 'F43.1',
    'tps_warning': (
        "TPS use in Post-Traumatic Stress Disorder is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for PTSD "
        "is emerging. Trauma-informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'LIMBIC hyperactivation / vmPFC hypofunction / CEN hypo / amygdala dysregulation',
    'fnon_montage_selection': [
        ['vmPFC extinction dominant', 'HDCstim tDCS Fp1 anode / Cz cathode'],
        ['DLPFC executive control', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Hyperarousal dominant', 'tDCS Cz cathode + taVNS extended'],
        ['Flashback/intrusion', 'tDCS Fp1 + F4 bilateral'],
        ['Sleep PTSD', 'tDCS F3/Fz + CES protocol'],
    ],
    'tps': [
        ['T1', 'vmPFC extinction recall', 'Fp1 / vmPFC', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T2', 'DLPFC cognitive control', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'ACC threat monitoring', 'Fz / ACCproxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T4', 'Amygdala via temporal', 'T3/T4 temporal', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T5', 'Hippocampal contextual', 'T5/T6 hippocampus', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'vmPFC extinction strengthen', 'vmPFC hypofunction', 'Fp1 / Fpz bilateral', 'Fear extinction memory', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT2', 'CEN activation', 'CEN hypofunction', 'F3/F4 DLPFC', 'Cognitive reappraisal capacity', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT3', 'Amygdala inhibition', 'LIMBIC hyperactivation', 'Temporal T3/T4 bilateral', 'Fear response dampening', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'Hippocampal context', 'Memory contextualization failure', 'T5/T6 hippocampus proxy', 'Trauma context discrimination', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT5', 'Hyperarousal SN suppress', 'SN hyperactivation', 'Cz + insula C3', 'Threat salience reduction', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT6', 'DMN intrusion break', 'DMN-trauma rumination', 'mPFC Fp1 + PCC Pz', 'Intrusive memory reduction', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Autonomic regulation', 'Autonomic hyperarousal', 'Insula C3 + vagal', 'HRV restoration', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Sleep-PTSD circuit', 'Nightmare-hyperarousal', 'F3 + Cz', 'Sleep architecture repair', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Trauma processing enhancement', 'Multi-network', 'vmPFC+DLPFC+amygdala rotating', 'CPT/PE augmentation', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'vmPFC strengthen', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'DLPFC cognitive', 'F3/F4 anodes / Oz', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Hyperarousal reduce', 'Cz cathode / F3 anode', '2 mA', '20 min', 'Emerging'],
        ['C4', 'Amygdala indirect', 'F4 anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Sleep PTSD', 'F3 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Emotional regulation', 'Fp1 anode / mastoid cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Depression comorbid', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Dissociation', 'F4 anode / F3 cathode', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'vmPFC extinction', 'vmPFC hypofunction', 'Fp1 anode / Cz cathode', 'Fear extinction strengthen', '1.5 mA', '20 min'],
        ['F2', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Cognitive control restore', '2 mA', '20 min'],
        ['F3', 'Amygdala inhibit', 'LIMBIC hyperactivation', 'F4 anode / shoulder', 'Emotional dampening', '2 mA', '20 min'],
        ['F4', 'SN suppress hyperarousal', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Arousal threshold', '2 mA', '20 min'],
        ['F5', 'DMN intrusion', 'DMN rumination', 'Fp1 cathode / Pz cathode', 'Intrusive thought reduction', '1.5 mA', '20 min'],
        ['F6', 'Sleep circuit', 'PTSD-insomnia', 'F3 anode / Cz cathode', 'Nightmare reduction', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Calm regulation', 'Variant D', 'Fp1/Cz', '1.2 mA', '20 min', 'Pre-trauma therapy'],
        ['C2-PS', 'Cognitive control', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'CPT/PE augmentation'],
        ['C3-PS', 'Mood stabilize', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Comorbid depression'],
        ['C4-PS', 'Sleep', 'Variant G', 'F3/Cz', '1.2 mA', '20 min', 'PTSD nightmares'],
        ['C5-PS', 'Grounding', 'Variant D', 'F3/Fp1', '1.2 mA', '20 min', 'Grounding exercises'],
        ['C6-PS', 'Autonomic balance', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'HRV support'],
        ['C7-PS', 'Social reconnection', 'Variant C', 'F3/TP9', '1.4 mA', '20 min', 'Social engagement'],
        ['C8-PS', 'Dissociation support', 'Variant B', 'F4/F3', '1.4 mA', '20 min', 'Grounding + present'],
    ],
    'fnon_plato': [
        ['FP1', 'vmPFC support', 'vmPFC hypofunction', 'Variant D', 'Fp1/Cz', '1.2 mA', '20 min'],
        ['FP2', 'CEN activate', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'LIMBIC calm', 'LIMBIC hyperactivation', 'Variant F', 'F3/C3', '1.2 mA', '20 min'],
        ['FP4', 'SN suppress', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP5', 'DMN break', 'DMN intrusion', 'Variant G', 'Fp1/Pz', '1.2 mA', '20 min'],
        ['FP6', 'Sleep-PTSD', 'PTSD insomnia', 'Variant G', 'F3/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Hyperarousal Dominant',
            'sozo_bar': ['taVNS 40 min', 'tDCS Cz cathode/F3 anode', 'TPS FT5 SN suppress', 'Grounding task'],
            'card_left': ['Network: SN hyperactivation + autonomic', 'Key target: SN nodes, insula, ACC', 'Priority: Arousal threshold normalization'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C3/F4', 'PlatoScience: C1-PS/FP4', 'Grounding'],
            'brain_targets': [
                ['SN nodes (Cz)', 'Threat detection', 'Suppress', 'FT5 / C3 / FP4', 'Emerging'],
                ['Insula', 'Autonomic', 'Normalize', 'T3 / C6', 'Emerging'],
                ['Amygdala', 'Fear hyperreactivity', 'Downregulate', 'FT3 / T4', 'Emerging'],
                ['ACC', 'Threat monitoring', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Brainstem (taVNS)', 'Autonomic tone', 'Activate vagal', 'taVNS extended', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C3 cathode', 'TPS SN suppress Cz', 'Grounding exercises'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', '5-4-3-2-1 sensory grounding'],
                ['taVNS 40 min', 'tDCS F4', 'TPS insula', 'HRV biofeedback'],
                ['CES 20 min', 'tDCS F4', 'TPS amygdala temporal', 'Breathing 4-7-8'],
            ],
            'task_pairing': 'Grounding exercises (5-4-3-2-1 sensory), HRV biofeedback, diaphragmatic breathing, body-based stabilization.',
            'fnon_hypothesis': 'Hyperarousal PTSD reflects SN hyperactivation with lowered threat detection threshold. Extended taVNS restores vagal brake while tDCS reduces SN excitability.',
        },
        {
            'code': 'P2', 'name': 'Re-experiencing / Intrusions',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1 anode', 'TPS vmPFC+hippocampus', 'Trauma narrative'],
            'card_left': ['Network: vmPFC hypo + hippocampal context failure', 'Key target: vmPFC, hippocampus, PCC', 'Priority: Extinction memory + context'],
            'card_right': ['TPS: T1 + FT4', 'tDCS: C1/F1', 'PlatoScience: C2-PS/FP1', 'CPT session'],
            'brain_targets': [
                ['vmPFC', 'Extinction recall', 'Strengthen', 'T1 / C1 / FP1', 'Evidence B'],
                ['Hippocampus', 'Context memory', 'Activate', 'T5 / FT4', 'Emerging'],
                ['PCC', 'Self-referential', 'Modulate', 'FT6 / Pz', 'Emerging'],
                ['ACC', 'Conflict monitoring', 'Activate', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Fear tag removal', 'Downregulate', 'FT3 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS Fp1 anode', 'TPS vmPFC', 'CPT written accounts'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS hippocampus', 'Trauma narrative'],
                ['taVNS 30 min', 'tDCS C1', 'TPS vmPFC+hippo', 'Extinction exposure'],
                ['CES 20 min', 'tDCS F1', 'TPS PCC', 'Memory reconsolidation'],
            ],
            'task_pairing': 'CPT written accounts, prolonged exposure narrative, extinction learning tasks, memory reconsolidation exercises.',
            'fnon_hypothesis': 'Re-experiencing reflects vmPFC failure to inhibit amygdala during trauma cue encounters. vmPFC TPS during extinction tasks strengthens fear inhibition pathways.',
        },
        {
            'code': 'P3', 'name': 'Avoidance & Emotional Numbing',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC+vmPFC', 'Approach task'],
            'card_left': ['Network: CEN hypo + emotional blunting', 'Key target: DLPFC bilateral, vmPFC', 'Priority: Emotional processing reactivation'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C2/F2', 'PlatoScience: C5-PS/FP2', 'Approach task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Approach motivation', 'Activate', 'T2 / C2 / FP2', 'Evidence B'],
                ['vmPFC', 'Positive affect', 'Restore', 'T1 / F1', 'Emerging'],
                ['Striatum', 'Reward processing', 'Activate (TPS)', 'TPS frontal lateral', 'Emerging'],
                ['Insula', 'Emotional sensing', 'Normalize', 'T3 / C6', 'Emerging'],
                ['ACC', 'Emotional engagement', 'Activate', 'T3 / C3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS vmPFC', 'Approach hierarchy'],
                ['taVNS 20 min', 'tDCS C2', 'TPS striatal', 'Pleasant activities'],
                ['CES 20 min', 'tDCS F2', 'TPS insula', 'Emotion labeling task'],
            ],
            'task_pairing': 'Behavioral activation, approach behavior hierarchy, emotion labeling tasks, positive experience scheduling.',
            'fnon_hypothesis': 'Avoidance/numbing reflects CEN hypofunction reducing approach motivation and vmPFC suppression of positive affect. DLPFC activation restores approach-avoidance balance.',
        },
        {
            'code': 'P4', 'name': 'Negative Cognitions & Mood',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L+vmPFC', 'CPT cognitive task'],
            'card_left': ['Network: CEN hypo + LIMBIC dysregulation', 'Key target: DLPFC L, vmPFC, ACC', 'Priority: Negative belief restructuring'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C7/F2', 'PlatoScience: C3-PS/FP2', 'CPT task'],
            'brain_targets': [
                ['DLPFC L', 'Cognitive restructuring', 'Activate', 'T2 / C7 / FP2', 'Evidence B'],
                ['vmPFC', 'Self-concept', 'Normalize', 'T1 / F1', 'Emerging'],
                ['ACC', 'Negative monitoring', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['Hippocampus', 'Episodic reframing', 'Support', 'FT4 / taVNS', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'CPT stuck point worksheets'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Cognitive challenging task'],
                ['taVNS 20 min', 'tDCS C7', 'TPS ACC', 'Thought records'],
                ['CES 20 min', 'tDCS F2', 'TPS amygdala', 'Self-compassion exercise'],
            ],
            'task_pairing': 'CPT stuck point worksheets, cognitive challenging tasks, thought records, self-compassion exercises.',
            'fnon_hypothesis': 'Negative cognitions in PTSD reflect DLPFC L hypofunction allowing unchecked negative belief schemas. L-DLPFC TPS during CPT enhances cognitive restructuring capacity.',
        },
        {
            'code': 'P5', 'name': 'Complex PTSD (C-PTSD)',
            'sozo_bar': ['taVNS 40 min', 'tDCS F3/Fp1', 'TPS vmPFC+DLPFC', 'Phase-based therapy'],
            'card_left': ['Network: Multi-network chronic dysregulation', 'Key target: vmPFC, DLPFC, amygdala, insula', 'Priority: Safety-first stabilization'],
            'card_right': ['TPS: T1+T2 + FT9', 'tDCS: C6/F1+F2', 'PlatoScience: C1-PS/FP1', 'Phase 1 safety'],
            'brain_targets': [
                ['vmPFC', 'Safety signal', 'Strengthen', 'T1 / C1 / FP1', 'Evidence B'],
                ['DLPFC bilateral', 'Executive regulation', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Body safety', 'Normalize', 'FT7 / C6', 'Emerging'],
                ['Amygdala', 'Chronic fear', 'Progressively inhibit', 'FT3 / temporal', 'Emerging'],
                ['Hippocampus', 'Autobiographic memory', 'Restore', 'FT4 / taVNS', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS Fp1 anode', 'TPS vmPFC', 'Phase 1: stabilization'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', 'Distress tolerance skills'],
                ['taVNS 30 min', 'tDCS F1', 'TPS amygdala (gradual)', 'Phase 2: trauma processing'],
                ['CES 20 min', 'tDCS C6', 'TPS insula', 'Body-based therapy'],
            ],
            'task_pairing': 'Phase-based trauma therapy (stabilization → processing → integration), distress tolerance DBT skills, body-based therapy.',
            'fnon_hypothesis': 'C-PTSD reflects chronic multi-network dysregulation requiring phase-based approach. vmPFC stabilization must precede trauma processing to avoid retraumatization.',
        },
        {
            'code': 'P6', 'name': 'PTSD with Dissociation',
            'sozo_bar': ['taVNS 20 min', 'tDCS F4/Fp1', 'TPS DLPFC R+vmPFC', 'Grounding + present'],
            'card_left': ['Network: Excessive limbic inhibition + derealization', 'Key target: DLPFC R, insula, temporal', 'Priority: Present-moment anchoring'],
            'card_right': ['TPS: FT1 + FT4', 'tDCS: C8/F2', 'PlatoScience: C8-PS/FP2', 'Grounding task'],
            'brain_targets': [
                ['DLPFC R', 'Present orientation', 'Activate', 'T2 R / C8 / FP2', 'Emerging'],
                ['Insula', 'Body awareness', 'Activate', 'FT7 / C6', 'Emerging'],
                ['Temporal cortex', 'Time orientation', 'Activate', 'FT4 / T5 area', 'Emerging'],
                ['vmPFC', 'Reality monitoring', 'Normalize', 'T1 / F1', 'Emerging'],
                ['ACC', 'Self-monitoring', 'Activate', 'T3 / C3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F4', 'TPS DLPFC R', 'Grounding + orientation tasks'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS insula', 'Body sensation scan'],
                ['taVNS 20 min', 'tDCS C8', 'TPS temporal', 'Present-focus mindfulness'],
                ['CES 20 min', 'tDCS Fp1', 'TPS vmPFC', 'Reality anchoring exercises'],
            ],
            'task_pairing': 'Grounding and orientation tasks, body sensation awareness, present-focus mindfulness, reality anchoring exercises.',
            'fnon_hypothesis': 'Dissociative PTSD reflects excessive limbic inhibition reducing emotional engagement with reality. R-DLPFC + insula activation restores present-moment embodied awareness.',
        },
        {
            'code': 'P7', 'name': 'PTSD-Insomnia / Nightmares',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Cz', 'TPS FT8 sleep circuit', 'IRT protocol'],
            'card_left': ['Network: Hyperarousal + REM disruption', 'Key target: DLPFC, ACC, thalamus', 'Priority: Sleep architecture + nightmare'],
            'card_right': ['TPS: FT8 + T3', 'tDCS: C5/F6', 'PlatoScience: C4-PS/FP6', 'IRT task'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep control', 'Activate', 'T2 / C5 / FP6', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Suppress', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Nightmare generation', 'Downregulate', 'FT8 / temporal', 'Emerging'],
                ['Thalamus', 'REM gating (CES)', 'Normalize', 'CES protocol', 'Emerging'],
                ['vmPFC', 'Nightmare content', 'Modulate', 'T1 / F1', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C5', 'TPS FT8 sleep', 'IRT nightmare rescripting'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction protocol'],
                ['CES 20 min', 'tDCS F6', 'TPS DLPFC', 'CBT-I adapted PTSD'],
                ['taVNS 20 min', 'tDCS F3', 'TPS thalamus proxy', 'Relaxation pre-sleep'],
            ],
            'task_pairing': 'Image Rehearsal Therapy (IRT) for nightmares, CBT-I adapted for PTSD, relaxation protocol pre-sleep.',
            'fnon_hypothesis': 'PTSD nightmares reflect amygdala-REM hyperactivation replaying fear memories. Evening CES + amygdala TPS reduces fear network activity during REM sleep.',
        },
        {
            'code': 'P8', 'name': 'Moral Injury / Guilt',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp1/F3', 'TPS vmPFC+mPFC', 'Adaptive disclosure'],
            'card_left': ['Network: mPFC self-judgment + LIMBIC', 'Key target: mPFC, vmPFC, ACC', 'Priority: Self-referential processing'],
            'card_right': ['TPS: T1 + FT6', 'tDCS: C6/F1', 'PlatoScience: C3-PS/FP1', 'AD task'],
            'brain_targets': [
                ['mPFC', 'Self-evaluation', 'Normalize', 'FT6 / Fp1 / FP1', 'Emerging'],
                ['vmPFC', 'Self-forgiveness', 'Activate', 'T1 / C6', 'Emerging'],
                ['ACC', 'Moral monitoring', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Guilt/shame affect', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['Insula', 'Shame embodiment', 'Normalize', 'FT7 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS Fp1', 'TPS vmPFC', 'Adaptive Disclosure therapy'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS mPFC', 'Self-compassion letter'],
                ['taVNS 20 min', 'tDCS F1', 'TPS ACC', 'Moral injury narrative'],
                ['CES 20 min', 'tDCS C6', 'TPS insula', 'Forgiveness meditation'],
            ],
            'task_pairing': 'Adaptive Disclosure Therapy (ADT), self-compassion exercises, moral injury narrative processing, forgiveness meditation.',
            'fnon_hypothesis': 'Moral injury reflects hyperactivated self-judgment circuits in mPFC-insula with failure of vmPFC self-compassion pathways. vmPFC TPS during forgiveness tasks activates self-acceptance networks.',
        },
        {
            'code': 'P9', 'name': 'Combat/First Responder PTSD',
            'sozo_bar': ['taVNS 40 min', 'tDCS F3/Fp1', 'TPS vmPFC+amygdala', 'PE augmentation'],
            'card_left': ['Network: Severe LIMBIC hyperactivation + CEN collapse', 'Key target: vmPFC, amygdala, DLPFC', 'Priority: Full SOZO trauma protocol'],
            'card_right': ['TPS: FT9 full + T1+T2', 'tDCS: C2/F1+F2', 'PlatoScience: C2-PS/FP2', 'PE/CPT combined'],
            'brain_targets': [
                ['vmPFC', 'Fear extinction', 'Maximize', 'T1 / F1 / FP1', 'Evidence B'],
                ['DLPFC bilateral', 'Executive regulation', 'Maximize', 'T2 / C2 / FP2', 'Evidence B'],
                ['Amygdala bilateral', 'Combat fear', 'Progressively inhibit', 'FT3 / bilateral temporal', 'Emerging'],
                ['Hippocampus', 'Memory contextualization', 'Restore', 'FT4 / taVNS extended', 'Emerging'],
                ['Insula', 'Embodied safety', 'Normalize', 'FT7 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS F3/Fp1', 'TPS vmPFC+DLPFC', 'PE intensive protocol'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS amygdala bilateral', 'CPT + EMDR combined'],
                ['taVNS 30 min', 'tDCS C2', 'TPS hippocampus', 'Context discrimination tasks'],
                ['CES 20 min', 'HDCstim F3/F4', 'TPS rotating multisite', 'Trauma narrative intensive'],
            ],
            'task_pairing': 'PE (Prolonged Exposure) intensive, CPT + EMDR combined protocol, context discrimination tasks, unit cohesion group therapy.',
            'fnon_hypothesis': 'Combat PTSD reflects maximal LIMBIC hyperactivation with CEN collapse. Full SOZO sequence targeting vmPFC, DLPFC, and amygdala simultaneously provides the strongest neurobiological augmentation of PE/CPT.',
        },
    ],
    'task_pairing_rows': [
        ['Grounding exercises', 'During taVNS', 'Stabilization', 'P1, P6'],
        ['CPT worksheets', 'Post-TPS', 'Trauma processing', 'P2, P4'],
        ['Behavioral activation', 'Post-TPS', 'Approach', 'P3'],
        ['PE narrative', 'Post-TPS', 'Exposure', 'P2, P9'],
        ['IRT nightmares', 'Evening session', 'Sleep', 'P7'],
        ['Adaptive disclosure', 'Post-TPS', 'Moral injury', 'P8'],
        ['Distress tolerance', 'During tDCS', 'DBT skills', 'P5'],
        ['HRV biofeedback', 'During taVNS', 'Autonomic', 'P1'],
    ],
    'followup_rows': [
        ['Week 2', 'PCL-5, PHQ-9', 'PTSD severity + mood', 'Safety check + protocol adjust'],
        ['Week 4', 'PCL-5, CAPS, sleep diary', 'Full PTSD + sleep', 'Phase 2 readiness'],
        ['Week 6', 'PCL-5, WHO-5, GAF', 'Functional assessment', 'Therapy integration check'],
        ['Week 10', 'PCL-5 + PTSD remission', 'Remission trajectory', 'Maintenance planning'],
        ['Month 4', 'Full battery + QoL', 'Long-term recovery', 'Maintenance protocol'],
        ['Month 6', 'PCL-5, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(3, 2, 3, 5, 3, 5, 2, 3, 3),
}
