"""
Partners-tier All-In-One Protocol data — stroke_rehab.
Auto-split from partners_all_in_one_data.py. Edit this file to modify stroke_rehab data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['stroke_rehab'] = {
    'display_name': 'Stroke Rehabilitation & Motor Recovery',
    'short': 'Stroke',
    'condition_slug': 'stroke_rehab',
    'icd10': 'I63 / I69',
    'tps_warning': (
        "TPS use in Stroke Rehabilitation is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for stroke rehab "
        "is emerging. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'SMN asymmetry / CEN hypofunction / LIMBIC depression-overlap',
    'fnon_montage_selection': [
        ['Motor dominant (UE paresis)', 'HDCstim tDCS C3 anode (ipsilesional M1)'],
        ['Language (Broca/Wernicke)', 'HDCstim tDCS F5 anode / cathodal contra'],
        ['Cognitive impairment', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Depression post-stroke', 'tDCS F3 anode / F4 cathode DLPFC LH'],
        ['Pain post-stroke', 'tDCS C3/C4 anodes + CES'],
    ],
    'tps': [
        ['T1', 'Motor cortex excitability (ipsilesional)', 'M1 ipsilesional (C3/C4)', '0.25 mJ/mm²', '1200 pulses', 'Evidence A'],
        ['T2', 'M1 contralateral suppression', 'M1 contralesional', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T3', 'Language recovery (Broca)', 'F5 / Broca area', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'DLPFC cognitive recovery', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Post-stroke depression', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'SMN ipsilesional activation', 'SMN hypofunction', 'M1/SMA ipsilesional', 'Motor re-recruitment', '0.25 mJ/mm²', '1200 pulses', '15 sessions'],
        ['FT2', 'Contralesional inhibition', 'SMN asymmetry', 'M1 contralesional cathode', 'Interhemispheric balance', '0.20 mJ/mm²', '800 pulses', '15 sessions'],
        ['FT3', 'CEN cognitive restoration', 'CEN hypofunction', 'DLPFC F3/F4', 'Executive recovery', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT4', 'Language network', 'Language network damage', 'Broca F5 + Wernicke T5', 'Aphasia rehabilitation', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
        ['FT5', 'Attention network', 'ATTENTION hypofunction', 'IPS P3/P4', 'Neglect + attention', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT6', 'Post-stroke depression', 'LIMBIC dysregulation', 'DLPFC L + vmPFC', 'Mood recovery', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT7', 'Spasticity modulation', 'SMN hyperexcitability', 'M1 contralesional', 'Spasticity reduction', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Visual field recovery', 'Visual network', 'O1/O2 occipital', 'Visual cortex activation', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT9', 'Gait and balance', 'SMN + CEN', 'SMA Fz + M1 bilateral', 'Gait pattern restoration', '0.25 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Motor excitability', 'C3 anode (ipsilesional) / C4 cathode', '2 mA', '20 min', 'Evidence A'],
        ['C2', 'Bihemispheric motor', 'C3 anode / C4 cathode (cross)', '2 mA', '20 min', 'Evidence A'],
        ['C3', 'Language (Broca)', 'F5 anode / F6 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Post-stroke depression', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C5', 'Cognitive rehab', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C6', 'Neglect (attention)', 'P4 anode / P3 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C7', 'Pain post-stroke', 'C3/C4 bilateral / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C8', 'Swallowing (dysphagia)', 'Pharyngeal M1 / C5 electrode', '2 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'SMN rebalance', 'SMN asymmetry', 'C3 anode / C4 cathode', 'Ipsilesional motor boost', '2 mA', '20 min'],
        ['F2', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz cathode', 'Cognitive recovery', '2 mA', '20 min'],
        ['F3', 'Language network', 'Language deficit', 'F5 anode / contralateral cathode', 'Aphasia support', '2 mA', '20 min'],
        ['F4', 'Mood recovery', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Post-stroke depression', '2 mA', '20 min'],
        ['F5', 'Attention/neglect', 'ATTENTION lateralized', 'P4 anode / P3 cathode', 'Unilateral neglect', '2 mA', '20 min'],
        ['F6', 'Pain modulation', 'SN/pain network', 'C3/C4 / Oz cathode', 'Post-stroke pain', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Motor priming', 'Variant E', 'C3/C4', '1.6 mA', '20 min', 'Pre-physiotherapy'],
        ['C2-PS', 'Cognitive rehab', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Cognitive exercises'],
        ['C3-PS', 'Language support', 'Variant C', 'F5/F6', '1.4 mA', '20 min', 'Speech therapy'],
        ['C4-PS', 'Mood uplift', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Post-stroke depression'],
        ['C5-PS', 'Attention rehab', 'Variant B', 'P3/P4', '1.4 mA', '20 min', 'Neglect therapy'],
        ['C6-PS', 'Fatigue reduction', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Post-stroke fatigue'],
        ['C7-PS', 'Spasticity support', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'Combined spasticity'],
        ['C8-PS', 'Pain modulation', 'Variant E', 'Cz/C3', '1.4 mA', '20 min', 'Central pain'],
    ],
    'fnon_plato': [
        ['FP1', 'SMN activation', 'SMN hypofunction', 'Variant E', 'C3/C4', '1.6 mA', '20 min'],
        ['FP2', 'CEN recovery', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'Language', 'Language network', 'Variant C', 'F5/F6', '1.4 mA', '20 min'],
        ['FP4', 'LIMBIC mood', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP5', 'Attention network', 'ATTENTION deficit', 'Variant B', 'P3/P4', '1.4 mA', '20 min'],
        ['FP6', 'Fatigue-SMN', 'Post-stroke fatigue', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Hemiparesis (Upper Limb)',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3 ipsilesional', 'TPS M1 ipsilesional', 'Arm rehab task'],
            'card_left': ['Network: SMN asymmetry', 'Key target: M1 ipsilesional, SMA', 'Priority: Motor reactivation'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'taVNS: 20 min pre'],
            'brain_targets': [
                ['M1 ipsilesional', 'Motor output', 'Activate', 'T1 / C1 / FP1', 'Evidence A'],
                ['SMA', 'Motor planning', 'Upregulate', 'FT9 / Fz', 'Evidence B'],
                ['M1 contralesional', 'Inhibitory balance', 'Suppress', 'T2 / C2 cathode', 'Evidence A'],
                ['Cerebellum', 'Motor coordination', 'TPS bilateral', 'TPS lateral', 'Emerging'],
                ['PMC', 'Premotor', 'Activate', 'TPS F3/F4', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 ipsilesional', 'TPS M1', 'Arm physio 30 min'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS SMA', 'Mirror therapy'],
                ['taVNS 20 min', 'tDCS bihemispheric', 'TPS M1+PMC', 'Robot-assisted arm'],
                ['CES 20 min', 'tDCS C1', 'TPS M1 bilateral', 'FES combined'],
            ],
            'task_pairing': 'Arm physiotherapy, mirror therapy, robot-assisted rehabilitation, FES (functional electrical stimulation).',
            'fnon_hypothesis': 'Hemiparesis reflects SMN ipsilesional silencing with contralesional hyperexcitability. Paired tDCS + TPS + motor task drives Hebbian re-recruitment of paretic motor cortex.',
        },
        {
            'code': 'P2', 'name': 'Aphasia (Language)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F5 Broca anode', 'TPS Broca + Wernicke', 'Speech therapy task'],
            'card_left': ['Network: Language network damage', 'Key target: Broca F5, Wernicke T5', 'Priority: Language network reactivation'],
            'card_right': ['TPS: T3 + FT4', 'tDCS: C3/F3', 'PlatoScience: C3-PS/FP3', 'SLT concurrent'],
            'brain_targets': [
                ['Broca area', 'Speech production', 'Activate', 'T3 / C3 / FP3', 'Evidence B'],
                ['Wernicke area', 'Comprehension', 'Activate', 'TPS T5/T6', 'Evidence B'],
                ['SMA', 'Speech initiation', 'Support', 'TPS Fz', 'Emerging'],
                ['Right IFG', 'Compensation', 'Modulate', 'TPS F6', 'Emerging'],
                ['DLPFC', 'Verbal working mem', 'Activate', 'C5 / FP2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F5 anode', 'TPS Broca', 'SLT naming tasks'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS Wernicke', 'Comprehension exercises'],
                ['taVNS 20 min', 'tDCS C3', 'TPS Broca+SMA', 'CIAT intensive'],
                ['CES 20 min', 'tDCS F3', 'TPS bilateral language', 'Reading aloud'],
            ],
            'task_pairing': 'Constraint-Induced Aphasia Therapy (CIAT), naming tasks, reading aloud, comprehension exercises during stimulation.',
            'fnon_hypothesis': 'Aphasia reflects language network node damage with perilesional suppression. tDCS + TPS applied concurrent with SLT maximizes activity-dependent plasticity in remaining language nodes.',
        },
        {
            'code': 'P3', 'name': 'Post-Stroke Cognitive Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC', 'Cognitive rehab task'],
            'card_left': ['Network: CEN hypofunction + DMN disruption', 'Key target: DLPFC, PFC bilateral', 'Priority: Cognitive reactivation'],
            'card_right': ['TPS: T4 + FT3', 'tDCS: C5/F2', 'PlatoScience: C2-PS/FP2', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC', 'Working memory', 'Activate', 'T4 / C5 / FP2', 'Emerging'],
                ['PFC bilateral', 'Executive function', 'Upregulate', 'T1+T2 / C5', 'Emerging'],
                ['Hippocampus', 'Episodic memory', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
                ['ACC', 'Attention', 'Activate', 'TPS Fz', 'Emerging'],
                ['Parietal', 'Visuospatial', 'Activate', 'TPS P3/P4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Cognitive rehab program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS DLPFC bilateral', 'Memory training'],
                ['taVNS 20 min', 'tDCS C5', 'TPS ACC', 'Attention tasks'],
                ['CES 20 min', 'tDCS F3', 'TPS parietal', 'Visuospatial exercises'],
            ],
            'task_pairing': 'Cognitive rehabilitation program, working memory training, attention tasks, visuospatial exercises.',
            'fnon_hypothesis': 'Post-stroke cognitive impairment reflects CEN node damage reducing prefrontal executive capacity. Bilateral DLPFC stimulation rebuilds functional connectivity supporting cognitive recovery.',
        },
        {
            'code': 'P4', 'name': 'Post-Stroke Depression',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood recovery'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C4/F4', 'PlatoScience: C4-PS/FP4', 'BA protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood regulation', 'Activate', 'T5 / C4 / FP4', 'Evidence B'],
                ['vmPFC', 'Reward processing', 'Normalize', 'T3 / F3', 'Emerging'],
                ['ACC', 'Emotional processing', 'Modulate', 'T4 / C5', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation schedule'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasant events planning'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'Activity monitoring'],
                ['CES 20 min', 'tDCS F4', 'TPS bilateral DLPFC', 'Mood diary'],
            ],
            'task_pairing': 'Behavioral activation schedule, pleasant events planning, activity monitoring, mood diary.',
            'fnon_hypothesis': 'Post-stroke depression reflects LIMBIC disinhibition due to prefrontal damage. L-DLPFC tDCS + TPS rebuilds top-down mood regulation capacity.',
        },
        {
            'code': 'P5', 'name': 'Unilateral Neglect',
            'sozo_bar': ['taVNS 20 min', 'tDCS P4 anode', 'TPS parietal R', 'Neglect scanning task'],
            'card_left': ['Network: ATTENTION lateralized (R parietal)', 'Key target: IPS R, P4', 'Priority: Attention rebalancing'],
            'card_right': ['TPS: FT5 + T4', 'tDCS: C6/F5', 'PlatoScience: C5-PS/FP5', 'Scanning task'],
            'brain_targets': [
                ['IPS R (P4)', 'Spatial attention', 'Activate', 'FT5 / C6 / FP5', 'Evidence B'],
                ['IPS L (P3)', 'Competing attention', 'Inhibit (cathode)', 'C6 cathode', 'Evidence B'],
                ['FEF R', 'Eye movement', 'Activate', 'TPS F8', 'Emerging'],
                ['DLPFC R', 'Attention top-down', 'Activate', 'T2 / C2', 'Emerging'],
                ['TPJ R', 'Attention reorienting', 'Activate', 'TPS T6', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS P4 anode', 'TPS IPS R', 'Scanning training'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS FEF R', 'Prism adaptation'],
                ['taVNS 20 min', 'tDCS C6', 'TPS TPJ R', 'Visual search tasks'],
                ['CES 20 min', 'tDCS bihemispheric P', 'TPS IPS bilateral', 'Limb activation'],
            ],
            'task_pairing': 'Visual scanning training, prism adaptation therapy, limb activation exercises, visual search tasks.',
            'fnon_hypothesis': 'Unilateral neglect reflects right parietal network silencing post-stroke. Activating IPS/TPJ R while inhibiting contralesional parietal restores attentional balance.',
        },
        {
            'code': 'P6', 'name': 'Gait and Balance Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS SMA/M1 bilateral', 'TPS SMA + cerebellum', 'Gait therapy'],
            'card_left': ['Network: SMN bilateral + cerebellar', 'Key target: SMA, M1 bilateral', 'Priority: Gait pattern restoration'],
            'card_right': ['TPS: FT9 + T1', 'tDCS: C1+C2/F1', 'PlatoScience: C1-PS/FP1', 'Gait task'],
            'brain_targets': [
                ['SMA', 'Gait initiation', 'Activate', 'FT9 / Fz', 'Evidence B'],
                ['M1 bilateral', 'Leg motor', 'Activate', 'T1 / C1+C2', 'Evidence B'],
                ['Cerebellum', 'Balance/coordination', 'Activate', 'TPS lateral', 'Emerging'],
                ['Basal ganglia', 'Gait rhythm', 'Modulate (TPS)', 'TPS frontal', 'Emerging'],
                ['PMC', 'Gait planning', 'Activate', 'TPS F3/F4', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS SMA bilateral', 'TPS SMA', 'Treadmill gait therapy'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS cerebellum', 'Balance board training'],
                ['taVNS 20 min', 'tDCS C1+C2', 'TPS M1 bilateral', 'Overground gait'],
                ['CES 20 min', 'tDCS Fz', 'TPS SMA+basal G', 'Rhythmic cue gait'],
            ],
            'task_pairing': 'Treadmill gait therapy, balance board training, rhythmic auditory cue gait, overground walking tasks.',
            'fnon_hypothesis': 'Post-stroke gait impairment reflects SMA-M1 bilateral circuit disruption. SMA TPS during treadmill training restores gait initiation programming.',
        },
        {
            'code': 'P7', 'name': 'Dysphagia (Swallowing)',
            'sozo_bar': ['taVNS 20 min', 'tDCS pharyngeal M1', 'TPS Cz swallowing', 'Swallowing therapy'],
            'card_left': ['Network: Swallowing motor network', 'Key target: Pharyngeal M1, Cz', 'Priority: Swallowing reflex restoration'],
            'card_right': ['TPS: T1 bilateral + FT1', 'tDCS: C8/F1', 'PlatoScience: C1-PS/FP1', 'SLP task'],
            'brain_targets': [
                ['Pharyngeal M1', 'Swallowing motor', 'Activate', 'T1 Cz / C8', 'Evidence B'],
                ['Insula', 'Swallowing integration', 'Activate', 'TPS C3', 'Emerging'],
                ['SMA', 'Swallowing planning', 'Support', 'TPS Fz', 'Emerging'],
                ['Brainstem', 'Reflex arc (taVNS)', 'Modulate', 'taVNS protocol', 'Emerging'],
                ['M1 ipsilesional', 'Compensation', 'Activate', 'T1 / C1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS Cz bilateral', 'TPS pharyngeal M1', 'Swallowing exercises SLP'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS insula', 'Texture progression'],
                ['taVNS 20 min', 'tDCS C8', 'TPS Cz', 'Neuromuscular E-stim'],
                ['CES 20 min', 'tDCS F1', 'TPS SMA', 'Pharyngeal maneuvers'],
            ],
            'task_pairing': 'SLP swallowing exercises, texture progression protocols, neuromuscular electrical stimulation, pharyngeal maneuvers.',
            'fnon_hypothesis': 'Dysphagia reflects pharyngeal motor cortex silencing. Bilateral Cz tDCS + TPS during SLP exercises activates both hemispheric swallowing representations.',
        },
        {
            'code': 'P8', 'name': 'Spasticity & Tone Management',
            'sozo_bar': ['taVNS 20 min', 'tDCS M1 contralesional', 'TPS contralesional M1', 'Stretching program'],
            'card_left': ['Network: SMN hyperexcitability contralesional', 'Key target: M1 contralesional', 'Priority: Interhemispheric balance'],
            'card_right': ['TPS: T2 + FT7', 'tDCS: C2/F1', 'PlatoScience: C7-PS/FP6', 'Stretch + splint'],
            'brain_targets': [
                ['M1 contralesional', 'Spasticity drive', 'Suppress', 'T2 / C2 cathode', 'Evidence B'],
                ['M1 ipsilesional', 'Voluntary control', 'Activate', 'T1 / C1', 'Evidence B'],
                ['SMA', 'Movement initiation', 'Balance', 'FT9 / Fz', 'Emerging'],
                ['Thalamus', 'Motor relay', 'Modulate (taVNS)', 'taVNS', 'Emerging'],
                ['Cerebellum', 'Tone modulation', 'Activate', 'TPS lateral', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS M1 contra cathode', 'TPS contralesional', 'Stretching + splinting'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS M1 balance', 'Botox timing support'],
                ['taVNS 20 min', 'tDCS C2', 'TPS SMA', 'Active movement practice'],
                ['CES 20 min', 'tDCS bihemispheric', 'TPS cerebellum', 'Constraint therapy'],
            ],
            'task_pairing': 'Passive stretching, splinting program, constraint-induced movement therapy, active range of motion exercises.',
            'fnon_hypothesis': 'Spasticity reflects contralesional M1 disinhibition dominating the paretic limb. Suppressing contralesional M1 via cathodal tDCS + inhibitory TPS restores interhemispheric balance.',
        },
        {
            'code': 'P9', 'name': 'Post-Stroke Fatigue',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Energy conservation'],
            'card_left': ['Network: CEN hypofunction + DMN overlap', 'Key target: DLPFC bilateral, SMA', 'Priority: Fatigue circuit modulation'],
            'card_right': ['TPS: T4 + FT3', 'tDCS: C5/F2', 'PlatoScience: C6-PS/FP6', 'Graded activity'],
            'brain_targets': [
                ['DLPFC bilateral', 'Effort regulation', 'Activate', 'T4 / C5 / FP2', 'Emerging'],
                ['SMA', 'Motor effort', 'Upregulate', 'FT9 / Fz', 'Emerging'],
                ['ACC', 'Effort monitoring', 'Modulate', 'T4 / C5', 'Emerging'],
                ['Thalamus', 'Arousal gating', 'Support (CES)', 'CES protocol', 'Emerging'],
                ['Insula', 'Fatigue perception', 'Normalize', 'T5 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Graded activity therapy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS SMA', 'Energy conservation training'],
                ['taVNS 20 min', 'tDCS C5', 'TPS ACC', 'Pacing techniques'],
                ['CES 20 min', 'tDCS Fz', 'TPS insula', 'Fatigue diary'],
            ],
            'task_pairing': 'Graded activity therapy, energy conservation training, pacing techniques, fatigue diary.',
            'fnon_hypothesis': 'Post-stroke fatigue reflects CEN inefficiency with excessive effort required for routine cognitive and motor tasks. DLPFC stimulation reduces perceived effort cost.',
        },
    ],
    'task_pairing_rows': [
        ['Motor physio', 'Concurrent tDCS', 'Motor rehab', 'P1, P6'],
        ['Speech therapy', 'Concurrent tDCS', 'Language', 'P2'],
        ['Cognitive rehab', 'Post-TPS', 'Cognitive', 'P3'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P4'],
        ['Visual scanning', 'Concurrent tDCS', 'Neglect', 'P5'],
        ['Gait therapy', 'Concurrent tDCS', 'Motor', 'P6'],
        ['SLP exercises', 'Concurrent tDCS', 'Swallowing', 'P7'],
        ['Stretching', 'Post-TPS', 'Spasticity', 'P8'],
        ['Graded activity', 'Post-TPS', 'Fatigue', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'FMA, NIHSS', 'Motor + stroke severity', 'Adjust motor protocol'],
        ['Week 4', 'FMA, MoCA, PHQ-9', 'Motor + cognition + mood', 'Add cognitive track if needed'],
        ['Week 6', 'FMA, WAB, BBS', 'Motor + language + balance', 'Phase 2 intensification'],
        ['Week 10', 'Full battery + FIM', 'Function + ADL', 'Discharge planning'],
        ['Month 4', 'FMA, MoCA, QoL', 'Long-term recovery', 'Maintenance protocol'],
        ['Month 6', 'Full reassessment', 'All domains', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(3, 3, 3, 3, 5, 4, 4, 5, 4),
}
