"""
Partners-tier All-In-One Protocol data — tbi.
Auto-split from partners_all_in_one_data.py. Edit this file to modify tbi data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['tbi'] = {
    'display_name': 'Traumatic Brain Injury Rehabilitation',
    'short': 'TBI',
    'condition_slug': 'tbi',
    'icd10': 'S06',
    'tps_warning': (
        "TPS use in Traumatic Brain Injury Rehabilitation is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for TBI rehab "
        "is emerging. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Diffuse axonal injury / CEN hypofunction / DMN disruption / LIMBIC dysregulation',
    'fnon_montage_selection': [
        ['Cognitive dominant', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Attention/executive', 'HDCstim tDCS F3 anode / Fpz'],
        ['Post-TBI depression', 'tDCS F3 anode / F4 cathode'],
        ['Sleep-TBI overlap', 'tDCS F3/Fz + CES protocol'],
        ['Chronic pain TBI', 'tDCS C3/C4 + CES'],
    ],
    'tps': [
        ['T1', 'DLPFC cognitive recovery', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T2', 'Bilateral PFC', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T3', 'mPFC mood regulation', 'Fpz / mPFC', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'ACC attention', 'Fz / ACC', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Post-TBI depression', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN reactivation', 'CEN hypofunction', 'F3/F4 bilateral', 'Restore executive network', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT2', 'DMN disruption repair', 'DMN dysregulation', 'mPFC Fp1 + PCC Pz', 'Default mode reset', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT3', 'SN threshold restore', 'SN dysregulation', 'Cz + insula', 'Salience recalibration', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT4', 'Attention network', 'ATTENTION hypofunction', 'IPS P3/P4', 'Sustained attention', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT5', 'Limbic stabilize', 'LIMBIC dysregulation', 'vmPFC + amygdala temporal', 'Emotional regulation', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT6', 'Sleep-wake circuit', 'Hyperarousal insomnia', 'F3 + Cz', 'Sleep architecture', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT7', 'Post-TBI pain', 'Central sensitization', 'M1 bilateral Cz', 'Pain modulation', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT8', 'Social cognition', 'Social network damage', 'DMPFC + TPJ', 'Social reintegration', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT9', 'Neuroplasticity max', 'Multi-network', 'Rotating multisite', 'Global recovery', '0.22 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Cognitive recovery', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C2', 'Attention', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Post-TBI depression', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Working memory', 'F3/F4 bilateral / Oz', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Sleep', 'Fz anode / Oz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Pain central', 'C3/C4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C7', 'PTSD comorbid', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C8', 'Fatigue TBI', 'F3/F4 anodes / Cz', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Executive recovery', '2 mA', '20 min'],
        ['F2', 'DMN reset', 'DMN dysregulation', 'Fp1 cathode / Pz cathode', 'Default mode calm', '1.5 mA', '20 min'],
        ['F3', 'Attention network', 'ATTENTION hypofunction', 'F3 anode / Cz cathode', 'Sustained attention', '2 mA', '20 min'],
        ['F4', 'Limbic stabilize', 'LIMBIC dysregulation', 'Fp1 anode / mastoid', 'Emotion regulation', '1.5 mA', '20 min'],
        ['F5', 'Sleep circuit', 'Sleep disruption', 'Fz anode / Oz cathode', 'Sleep restoration', '1.5 mA', '20 min'],
        ['F6', 'Pain modulation', 'Central pain', 'C3/C4 anodes / Oz', 'Pain suppression', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Cognitive boost', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'TBI cognitive tasks'],
        ['C2-PS', 'Focus', 'Variant B', 'F3/Cz', '1.4 mA', '20 min', 'Attention rehab'],
        ['C3-PS', 'Mood', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Post-TBI depression'],
        ['C4-PS', 'Memory', 'Variant C', 'F3/F4', '1.4 mA', '20 min', 'Memory training'],
        ['C5-PS', 'Sleep prep', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'TBI insomnia'],
        ['C6-PS', 'Pain relief', 'Variant E', 'C3/C4', '1.4 mA', '20 min', 'Central pain'],
        ['C7-PS', 'Social cognition', 'Variant C', 'F3/TP9', '1.4 mA', '20 min', 'Social reintegration'],
        ['C8-PS', 'Fatigue', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'TBI fatigue'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN activate', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'DMN calm', 'DMN dysregulation', 'Variant G', 'Fp1/Pz', '1.2 mA', '20 min'],
        ['FP3', 'Attention', 'ATTENTION deficit', 'Variant B', 'F3/Cz', '1.4 mA', '20 min'],
        ['FP4', 'Limbic', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP5', 'Sleep', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min'],
        ['FP6', 'Pain', 'Central sensitization', 'Variant E', 'C3/C4', '1.4 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Cognitive Impairment (Post-TBI)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC bilateral', 'Cognitive rehab'],
            'card_left': ['Network: CEN diffuse hypofunction', 'Key target: DLPFC bilateral', 'Priority: Executive reactivation'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Working memory', 'Activate', 'T2 / C1 / FP1', 'Evidence B'],
                ['ACC', 'Attention', 'Activate', 'T4 / C2', 'Emerging'],
                ['PFC lateral', 'Executive function', 'Upregulate', 'T1 / C4', 'Emerging'],
                ['Hippocampus', 'New learning', 'Support (taVNS)', 'taVNS', 'Emerging'],
                ['Thalamus', 'Arousal gating', 'Normalize (CES)', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Cognitive training program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Working memory tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS bilateral PFC', 'Attention training'],
                ['CES 20 min', 'tDCS C4', 'TPS hippocampus proxy', 'Memory encoding tasks'],
            ],
            'task_pairing': 'Computerized cognitive rehabilitation, working memory n-back tasks, attention training, memory encoding exercises.',
            'fnon_hypothesis': 'Post-TBI cognitive impairment reflects diffuse axonal injury disrupting CEN white matter integrity. Bilateral DLPFC stimulation compensates for reduced network efficiency.',
        },
        {
            'code': 'P2', 'name': 'Post-TBI Depression',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood circuit restoration'],
            'card_right': ['TPS: T5 + FT5', 'tDCS: C3/F4', 'PlatoScience: C3-PS/FP4', 'BA protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood upregulation', 'Activate', 'T5 / C3 / FP4', 'Evidence B'],
                ['vmPFC', 'Reward', 'Normalize', 'T3 / F3', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['ACC', 'Emotional control', 'Modulate', 'T4 / C2', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasurable activity'],
                ['taVNS 20 min', 'tDCS C3', 'TPS ACC', 'Mood diary'],
                ['CES 20 min', 'tDCS F4', 'TPS amygdala temporal', 'CBT negative thoughts'],
            ],
            'task_pairing': 'Behavioral activation schedule, pleasurable activity planning, mood diary, CBT for negative cognitions.',
            'fnon_hypothesis': 'Post-TBI depression reflects LIMBIC circuit dysregulation compounded by PFC damage. L-DLPFC TPS + taVNS rebuilds mood regulation while taVNS supports hippocampal neuroplasticity.',
        },
        {
            'code': 'P3', 'name': 'Post-Concussion Syndrome',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 low intensity', 'TPS low-dose DLPFC', 'Graded return'],
            'card_left': ['Network: Multi-network sensitivity', 'Key target: DLPFC, Cz, mild protocol', 'Priority: Gradual neural recalibration'],
            'card_right': ['TPS: T1 low + FT1 reduced', 'tDCS: C8/F1 low', 'PlatoScience: C6-PS/FP6', 'REST protocol'],
            'brain_targets': [
                ['DLPFC', 'Cognitive function', 'Gentle activate', 'T1 reduced / C1', 'Emerging'],
                ['SN nodes', 'Symptom sensitivity', 'Normalize', 'FT3 low / Cz', 'Emerging'],
                ['Vestibular cortex', 'Dizziness', 'Modulate', 'TPS T3/T4', 'Emerging'],
                ['ACC', 'Headache circuit', 'Modulate', 'T4 / C5', 'Emerging'],
                ['Brainstem', 'Autonomic', 'Modulate (taVNS)', 'taVNS protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C8 low', 'TPS DLPFC low-dose', 'Graded return to activity'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS Cz low', 'Symptom monitoring'],
                ['taVNS 20 min', 'tDCS F1 low', 'TPS vestibular', 'Vestibular rehab'],
                ['CES 20 min', 'tDCS low 1 mA', 'TPS ACC low', 'Headache diary'],
            ],
            'task_pairing': 'Graded return-to-activity protocol, symptom monitoring diary, vestibular rehabilitation, paced activity.',
            'fnon_hypothesis': 'Post-concussion syndrome reflects neural hypersensitivity with SN threshold lowering. Low-dose graduated stimulation recalibrates network thresholds without provoking symptoms.',
        },
        {
            'code': 'P4', 'name': 'Post-TBI PTSD',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1/F4', 'TPS vmPFC+amygdala', 'Trauma-focused task'],
            'card_left': ['Network: LIMBIC hyperactivation + CEN hypo', 'Key target: vmPFC, amygdala, DLPFC', 'Priority: Fear extinction'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C7/F4', 'PlatoScience: C3-PS/FP4', 'CPT task'],
            'brain_targets': [
                ['vmPFC', 'Fear extinction', 'Strengthen', 'T3 / C7', 'Evidence B'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['Hippocampus', 'Context memory', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
                ['DLPFC', 'Top-down control', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Conflict monitoring', 'Modulate', 'T4 / C2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7', 'TPS vmPFC', 'CPT trauma processing'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS amygdala', 'Grounding exercises'],
                ['taVNS 30 min', 'tDCS F4', 'TPS DLPFC', 'Safety cue conditioning'],
                ['CES 20 min', 'tDCS Fp1', 'TPS ACC', 'Trauma narrative'],
            ],
            'task_pairing': 'Cognitive Processing Therapy (CPT), grounding exercises, safety signal conditioning, trauma narrative reprocessing.',
            'fnon_hypothesis': 'TBI-comorbid PTSD reflects dual pathology: structural vmPFC damage reducing fear inhibition + traumatic hyperactivation of amygdala. Combined TPS + taVNS targets both mechanisms.',
        },
        {
            'code': 'P5', 'name': 'Post-TBI Insomnia',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz/F3', 'TPS DLPFC+ACC', 'Sleep hygiene'],
            'card_left': ['Network: Hyperarousal + sleep circuit damage', 'Key target: Thalamus, DLPFC, ACC', 'Priority: Sleep architecture repair'],
            'card_right': ['TPS: T4 + FT6', 'tDCS: C5/F5', 'PlatoScience: C5-PS/FP5', 'CBT-I'],
            'brain_targets': [
                ['DLPFC', 'Sleep cognitive control', 'Balance', 'T4 / C5', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Suppress', 'T4 / C2', 'Emerging'],
                ['Thalamus', 'Sleep gating', 'Support (CES)', 'CES', 'Emerging'],
                ['Hypothalamus', 'Circadian', 'Normalize (CES)', 'CES', 'Emerging'],
                ['mPFC', 'Pre-sleep rumination', 'Downregulate', 'FT2 / F2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C5', 'TPS DLPFC', 'CBT-I protocol'],
                ['CES 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction'],
                ['taVNS 20 min', 'tDCS F5', 'TPS thalamus proxy Cz', 'Stimulus control'],
                ['CES 20 min', 'tDCS Fz', 'TPS mPFC', 'Progressive relaxation'],
            ],
            'task_pairing': 'CBT-I (cognitive behavioral therapy for insomnia), sleep restriction, stimulus control protocol, relaxation training.',
            'fnon_hypothesis': 'Post-TBI insomnia reflects hyperarousal from thalamic damage + cortical hyperexcitability. CES-thalamic protocol + prefrontal tDCS reduces arousal threshold for sleep onset.',
        },
        {
            'code': 'P6', 'name': 'Chronic Pain (Post-TBI)',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 bilateral', 'TPS M1 bilateral', 'Pain management'],
            'card_left': ['Network: Central sensitization', 'Key target: M1 bilateral, ACC', 'Priority: Pain gate modulation'],
            'card_right': ['TPS: FT7 + T4', 'tDCS: C6/F6', 'PlatoScience: C6-PS/FP6', 'Pain rehab'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'FT7 / C6 / FP6', 'Evidence B'],
                ['DLPFC', 'Pain modulation', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Pain affect', 'Modulate', 'T4 / C2', 'Emerging'],
                ['Insula', 'Pain integration', 'Normalize', 'T5 / C6', 'Emerging'],
                ['Thalamus', 'Pain relay (CES)', 'Modulate', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3/C4', 'TPS M1', 'Pain management program'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS ACC', 'Acceptance pain ACT'],
                ['taVNS 20 min', 'tDCS C6', 'TPS insula', 'Graded motor imagery'],
                ['CES 20 min', 'tDCS F6', 'TPS DLPFC', 'Pain education'],
            ],
            'task_pairing': 'Pain management program, graded motor imagery, acceptance-based pain therapy (ACT), pain education.',
            'fnon_hypothesis': 'Post-TBI central pain reflects sensitized pain networks without adequate descending inhibition. M1 TPS activates corticospinal pain inhibitory pathways.',
        },
        {
            'code': 'P7', 'name': 'Executive Dysfunction (Severe)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Executive tasks'],
            'card_left': ['Network: CEN severe hypofunction', 'Key target: DLPFC bilateral, OFC', 'Priority: Frontal executive circuit'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Problem-solving task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Executive planning', 'Activate', 'T2 / C1 / FP1', 'Evidence B'],
                ['OFC', 'Decision making', 'Modulate', 'TPS Fp2', 'Emerging'],
                ['ACC', 'Error monitoring', 'Activate', 'T4 / C2', 'Emerging'],
                ['Frontal-striatal', 'Response inhibition', 'Restore', 'TPS frontal lateral', 'Emerging'],
                ['PFC medial', 'Goal-directed', 'Activate', 'TPS Fz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC bilateral', 'Problem-solving therapy'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS OFC', 'Planning tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Stop-signal task'],
                ['CES 20 min', 'tDCS C4', 'TPS frontal', 'Goal management training'],
            ],
            'task_pairing': 'Goal Management Training (GMT), problem-solving therapy, planning tasks, response inhibition training.',
            'fnon_hypothesis': 'Severe executive dysfunction post-TBI reflects bilateral frontal network disruption. Bilateral DLPFC + OFC stimulation during GMT tasks promotes goal-directed behavior recovery.',
        },
        {
            'code': 'P8', 'name': 'Social Cognition Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/TP9', 'TPS DMPFC+TPJ', 'Social task'],
            'card_left': ['Network: Social brain network', 'Key target: DMPFC, TPJ, STS', 'Priority: Theory of mind recovery'],
            'card_right': ['TPS: FT8 + FT4', 'tDCS: C7/F6', 'PlatoScience: C7-PS/FP6', 'Social interaction'],
            'brain_targets': [
                ['DMPFC', 'Mentalizing', 'Activate', 'FT8 / C7 / FP6', 'Emerging'],
                ['TPJ', 'Theory of mind', 'Activate', 'TPS P3/T5', 'Emerging'],
                ['STS', 'Social perception', 'Activate', 'TPS T5/T6', 'Emerging'],
                ['Amygdala', 'Social emotion', 'Normalize', 'FT5 / temporal', 'Emerging'],
                ['OFC', 'Social reward', 'Activate', 'TPS Fp2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C7', 'TPS DMPFC', 'Emotion recognition training'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS TPJ', 'Perspective-taking tasks'],
                ['taVNS 20 min', 'tDCS F6', 'TPS STS', 'Social video scenarios'],
                ['CES 20 min', 'tDCS F3/TP9', 'TPS bilateral social', 'Role-play therapy'],
            ],
            'task_pairing': 'Emotion recognition training, perspective-taking exercises, role-play social scenarios, social video analysis.',
            'fnon_hypothesis': 'TBI social cognition impairment reflects DMPFC-TPJ network damage disrupting mentalizing. TPS during social tasks drives activity-dependent plasticity in remaining social nodes.',
        },
        {
            'code': 'P9', 'name': 'Fatigue & Motivation Deficit',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fz', 'TPS DLPFC+ACC', 'Graded activation'],
            'card_left': ['Network: CEN inefficiency + motivation circuit', 'Key target: DLPFC, mPFC, ACC', 'Priority: Effort-reward recalibration'],
            'card_right': ['TPS: T4 + FT9', 'tDCS: C8/F1', 'PlatoScience: C8-PS/FP6', 'Activation task'],
            'brain_targets': [
                ['DLPFC', 'Effort regulation', 'Activate', 'T4 / C8 / FP6', 'Emerging'],
                ['ACC', 'Motivation monitoring', 'Modulate', 'T4 / C2', 'Emerging'],
                ['Striatum', 'Reward processing', 'Activate (TPS)', 'TPS lateral frontal', 'Emerging'],
                ['mPFC', 'Motivation drive', 'Upregulate', 'T3 / F4', 'Emerging'],
                ['Thalamus', 'Arousal (CES)', 'Activate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/Fz', 'TPS DLPFC', 'Graded activity therapy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', 'Motivation diary'],
                ['taVNS 20 min', 'tDCS C8', 'TPS mPFC', 'Pleasant activity schedule'],
                ['CES 20 min', 'tDCS F1', 'TPS striatal proxy', 'Goal-setting session'],
            ],
            'task_pairing': 'Graded activity therapy, goal-setting sessions, motivation diary, pleasant activity scheduling.',
            'fnon_hypothesis': 'Post-TBI fatigue reflects disrupted effort-reward valuation circuits. DLPFC + striatal TPS during graded activation recalibrates perceived effort cost.',
        },
    ],
    'task_pairing_rows': [
        ['Cognitive training', 'Post-TPS', 'Cognitive', 'P1, P7'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P2'],
        ['Graded return', 'During tDCS', 'Activity', 'P3'],
        ['CPT trauma', 'Post-TPS', 'PTSD', 'P4'],
        ['CBT-I sleep', 'Evening session', 'Sleep', 'P5'],
        ['Pain management', 'Concurrent tDCS', 'Pain', 'P6'],
        ['GMT executive', 'Concurrent tDCS', 'Executive', 'P7'],
        ['Social training', 'Post-TPS', 'Social', 'P8'],
        ['Graded activation', 'Post-TPS', 'Fatigue', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'MoCA, PHQ-9, NSI', 'Cognitive + mood + symptoms', 'Adjust protocol if <15% improvement'],
        ['Week 4', 'Full TBI battery', 'All domains', 'Phase 2 consideration'],
        ['Week 6', 'MoCA, PCSS, GAS', 'Comprehensive assessment', 'Goal attainment check'],
        ['Week 10', 'Full battery + FIM', 'Function + ADL', 'Discharge planning'],
        ['Month 4', 'MoCA, QoL, return-to-work', 'Long-term recovery', 'Maintenance protocol'],
        ['Month 6', 'Full reassessment', 'All domains', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(4, 4, 3, 3, 3, 4, 4, 4, 3),
}
