"""
Partners-tier All-In-One Protocol data — tinnitus.
Auto-split from partners_all_in_one_data.py. Edit this file to modify tinnitus data.
"""
from ._shared import _plato_programs_default  # noqa: F401

PARTNERS_CONDITIONS = {}

PARTNERS_CONDITIONS['tinnitus'] = {
    'display_name': 'Tinnitus & Auditory Processing Disorders',
    'short': 'Tinnitus',
    'condition_slug': 'tinnitus',
    'icd10': 'H93.1',
    'tps_warning': (
        "TPS use in Tinnitus is INVESTIGATIONAL / OFF-LABEL. "
        "NEUROLITH\u00ae is CE-marked for musculoskeletal indications only. Evidence for tinnitus "
        "is investigational. Informed consent and Doctor supervision mandatory."
    ),
    'fnon_classification': 'Auditory cortex hyperactivation / CEN distress modulation / LIMBIC-tinnitus loop / DMN rumination',
    'fnon_montage_selection': [
        ['Auditory hyperactivation dominant', 'HDCstim tDCS T3/T4 cathodes / C3/C4 anodes'],
        ['DLPFC distress modulation', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['mPFC-auditory loop', 'tDCS Fp1 anode / T3/T4 cathodes'],
        ['Sleep-tinnitus overlap', 'tDCS F3/Fz + CES protocol'],
        ['Hyperacusis dominant', 'tDCS C3/C4 + T3 cathode'],
    ],
    'tps': [
        ['T1', 'Auditory cortex modulation', 'T3/T4 bilateral', '0.20 mJ/mm²', '800 pulses', 'Evidence A'],
        ['T2', 'DLPFC distress', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'ACC tinnitus distress', 'Fz / ACC-proxy', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'Temporal-parietal junction', 'T5/T6 bilateral', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T5', 'vmPFC habituation', 'Fp1 / vmPFC-proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'Auditory cortex suppress', 'Auditory hyperactivation', 'T3/T4 bilateral suppress', 'Phantom sound source reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT2', 'CEN distress reduce', 'CEN tinnitus distress', 'F3/F4 bilateral', 'Tinnitus handicap reduce', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT3', 'LIMBIC-tinnitus loop', 'LIMBIC hyperactivation', 'Temporal T3 + vmPFC Fp1', 'Emotional tinnitus response', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'DMN habituation', 'DMN rumination', 'mPFC + PCC', 'Tinnitus intrusion reduce', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT5', 'ACC distress modulate', 'SN hyperactivation', 'Fz ACC-proxy', 'Suffering component reduce', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT6', 'Hyperacusis', 'Auditory SN sensitivity', 'C3/C4 + T3/T4', 'Sound tolerance increase', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT7', 'Sleep-tinnitus', 'Sleep disruption', 'F3 + Cz', 'Nighttime tinnitus', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT8', 'Depression-tinnitus', 'LIMBIC dysregulation', 'DLPFC L + vmPFC', 'Tinnitus-depression loop', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT9', 'Chronic severe tinnitus', 'Multi-network', 'Rotating auditory+CEN+LIMBIC', 'Comprehensive tinnitus', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Auditory cortex', 'T3/T4 cathodes / C3/C4 anodes', '1.5 mA', '20 min', 'Evidence A'],
        ['C2', 'DLPFC distress', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Temporal-frontal', 'T3 cathode / F3 anode', '1.5 mA', '20 min', 'Evidence B'],
        ['C4', 'mPFC habituation', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C5', 'Hyperacusis', 'C3/C4 anodes / T3/T4 cathodes', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Sleep-tinnitus', 'F3 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Depression comorbid', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Bilateral temporal', 'T3/T4 cathodes / F3/F4 anodes', '1.5 mA', '20 min', 'Evidence B'],
    ],
    'fnon_tdcs': [
        ['F1', 'Auditory suppress', 'Auditory hyperactivation', 'T3/T4 cathodes / C3/C4 anodes', 'Phantom sound reduce', '1.5 mA', '20 min'],
        ['F2', 'CEN distress', 'CEN tinnitus modulation', 'F3/F4 anodes / Oz', 'Distress reduce', '2 mA', '20 min'],
        ['F3', 'Temporal-frontal', 'Temporal-frontal loop', 'T3 cathode / F3 anode', 'Loop disruption', '1.5 mA', '20 min'],
        ['F4', 'LIMBIC loop', 'LIMBIC-tinnitus', 'Fp1 anode / T3 cathode', 'Emotional response reduce', '1.5 mA', '20 min'],
        ['F5', 'Sleep circuit', 'Sleep-tinnitus overlap', 'F3 anode / Cz cathode', 'Nighttime relief', '1.5 mA', '20 min'],
        ['F6', 'Mood-tinnitus', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Mood-tinnitus combined', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Tinnitus focus', 'Variant B', 'F3/T3', '1.2 mA', '20 min', 'Distraction task'],
        ['C2-PS', 'Calm auditory', 'Variant D', 'T3/F3', '1.0 mA', '20 min', 'Relaxation tinnitus'],
        ['C3-PS', 'Mood tinnitus', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Depression comorbid'],
        ['C4-PS', 'Sleep tinnitus', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'Nighttime protocol'],
        ['C5-PS', 'Habituation', 'Variant D', 'F3/Fp1', '1.2 mA', '20 min', 'Habituation training'],
        ['C6-PS', 'Anxiety tinnitus', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Anxiety comorbid'],
        ['C7-PS', 'Hyperacusis', 'Variant F', 'C3/T3', '1.0 mA', '20 min', 'Sound tolerance'],
        ['C8-PS', 'Chronic severe', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Severe tinnitus'],
    ],
    'fnon_plato': [
        ['FP1', 'Auditory calm', 'Auditory hyperactivation', 'Variant D', 'T3/F3', '1.0 mA', '20 min'],
        ['FP2', 'CEN distress', 'CEN tinnitus', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'LIMBIC loop', 'LIMBIC-tinnitus', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP4', 'DMN habit', 'DMN rumination', 'Variant G', 'Fp1/Pz', '1.2 mA', '20 min'],
        ['FP5', 'Sleep tinnitus', 'Sleep disruption', 'Variant G', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP6', 'Hyperacusis', 'Sound sensitivity', 'Variant F', 'C3/T3', '1.0 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Tonal Tinnitus (Chronic)',
            'sozo_bar': ['taVNS 20 min', 'tDCS T3/T4 cathodes', 'TPS auditory bilateral', 'Sound therapy'],
            'card_left': ['Network: Auditory cortex hyperactivation', 'Key target: T3/T4 bilateral', 'Priority: Phantom sound reduction'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C2-PS/FP1', 'Sound therapy'],
            'brain_targets': [
                ['Auditory cortex T3/T4', 'Phantom sound generator', 'Suppress', 'T1 / C1 / FP1', 'Evidence A'],
                ['Belt areas', 'Auditory association', 'Normalize', 'TPS T5/T6', 'Emerging'],
                ['DLPFC', 'Distress modulation', 'Activate', 'T2 / C2', 'Evidence B'],
                ['ACC', 'Salience of sound', 'Reduce', 'T3 / C3', 'Evidence B'],
                ['vmPFC', 'Habituation support', 'Strengthen', 'T5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1 T3/T4 cathode', 'TPS auditory bilateral', 'Sound therapy concurrent'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', 'TRT tinnitus retraining'],
                ['taVNS 20 min', 'tDCS C8', 'TPS T3/T4 + DLPFC', 'Notched music therapy'],
                ['CES 20 min', 'tDCS C3', 'TPS ACC', 'Tinnitus diary CBT'],
            ],
            'task_pairing': 'Sound therapy (broadband noise), Tinnitus Retraining Therapy (TRT), notched music therapy, tinnitus diary CBT.',
            'fnon_hypothesis': 'Chronic tonal tinnitus reflects auditory cortex tonotopic reorganization generating persistent phantom sound. Bilateral auditory cortex TPS disrupts maladaptive synchrony in deafferented zones.',
        },
        {
            'code': 'P2', 'name': 'Tinnitus with High Distress',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 + T3 cathode', 'TPS DLPFC+auditory', 'CBT tinnitus'],
            'card_left': ['Network: DLPFC + LIMBIC distress amplification', 'Key target: DLPFC bilateral, ACC', 'Priority: Tinnitus handicap reduction'],
            'card_right': ['TPS: T2+T3 + FT2', 'tDCS: C2/F2', 'PlatoScience: C8-PS/FP2', 'CBT task'],
            'brain_targets': [
                ['DLPFC', 'Distress regulation', 'Activate', 'T2 / C2 / FP2', 'Evidence B'],
                ['ACC', 'Suffering signal', 'Reduce', 'T3 / C3', 'Evidence B'],
                ['Amygdala', 'Emotional tinnitus', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['vmPFC', 'Habituation memory', 'Strengthen', 'T5 / C4', 'Emerging'],
                ['Auditory T3/T4', 'Source signal', 'Modulate', 'T1 / C1', 'Evidence A'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C2 F3/F4', 'TPS DLPFC', 'Tinnitus CBT structured'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Acceptance tinnitus ACT'],
                ['taVNS 20 min', 'tDCS F2', 'TPS auditory+DLPFC', 'TRT + CBT combined'],
                ['CES 20 min', 'tDCS C3', 'TPS vmPFC', 'Habituation training'],
            ],
            'task_pairing': 'Tinnitus CBT, acceptance-based tinnitus therapy (ACT), TRT + CBT combined, habituation training.',
            'fnon_hypothesis': 'High-distress tinnitus reflects DLPFC failure to attenuate auditory-limbic tinnitus loop. DLPFC TPS concurrent with CBT strengthens the distress modulation pathway.',
        },
        {
            'code': 'P3', 'name': 'Tinnitus + Sleep Disturbance',
            'sozo_bar': ['CES 20 min', 'tDCS C6 F3/Cz', 'TPS FT7 sleep', 'Sleep + TRT'],
            'card_left': ['Network: Sleep-tinnitus hyperarousal loop', 'Key target: DLPFC, Cz thalamus proxy', 'Priority: Sleep onset with tinnitus'],
            'card_right': ['TPS: FT7 + T3', 'tDCS: C6/F5', 'PlatoScience: C4-PS/FP5', 'Sleep + sound'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep regulation', 'Balance', 'T2 / C6 / FP5', 'Emerging'],
                ['Thalamus (CES)', 'Sleep gating', 'Support', 'CES protocol', 'Emerging'],
                ['Auditory T3/T4', 'Nocturnal tinnitus', 'Suppress', 'T1 / C8', 'Evidence A'],
                ['ACC', 'Hyperarousal', 'Reduce', 'T3 / C3', 'Emerging'],
                ['mPFC', 'Pre-sleep worry', 'Downregulate', 'FT4 / F3', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C6', 'TPS DLPFC sleep', 'Sleep + sound masking'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'CBT-I + TRT'],
                ['CES 20 min', 'tDCS F5', 'TPS auditory bilateral', 'Sound therapy at bedtime'],
                ['taVNS 20 min', 'tDCS F3', 'TPS mPFC', 'Sleep restriction tinnitus'],
            ],
            'task_pairing': 'Sleep + sound masking therapy, CBT-I adapted for tinnitus, sound therapy at bedtime, sleep restriction protocol.',
            'fnon_hypothesis': 'Tinnitus-insomnia reflects auditory hyperactivation preventing sleep onset combined with cortical hyperarousal. Evening CES + auditory tDCS reduces both tinnitus prominence and arousal threshold.',
        },
        {
            'code': 'P4', 'name': 'Tinnitus + Depression',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode + T3 cathode', 'TPS DLPFC+auditory', 'BA + TRT'],
            'card_left': ['Network: LIMBIC-tinnitus-depression loop', 'Key target: DLPFC L, auditory, ACC', 'Priority: Combined mood-tinnitus'],
            'card_right': ['TPS: T2+T1 + FT8', 'tDCS: C7/F3', 'PlatoScience: C3-PS/FP3', 'BA + TRT'],
            'brain_targets': [
                ['DLPFC L', 'Mood + tinnitus distress', 'Activate', 'T2 / C7 / FP3', 'Evidence B'],
                ['Auditory T3/T4', 'Phantom sound', 'Modulate', 'T1 / C1', 'Evidence A'],
                ['Amygdala', 'Tinnitus-depression affect', 'Downregulate', 'FT8 / temporal', 'Emerging'],
                ['vmPFC', 'Positive affect restore', 'Activate', 'T5 / F3', 'Emerging'],
                ['ACC', 'Combined distress', 'Modulate', 'T3 / C3', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 F3+T3', 'TPS DLPFC+auditory', 'BA + TRT combined'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasant activity + TRT'],
                ['taVNS 20 min', 'tDCS F3', 'TPS DLPFC L', 'Mood diary + tinnitus diary'],
                ['CES 20 min', 'tDCS C3', 'TPS ACC', 'CBT mood + tinnitus'],
            ],
            'task_pairing': 'Behavioral activation combined with TRT, pleasant activity scheduling with sound therapy, mood + tinnitus diary.',
            'fnon_hypothesis': 'Tinnitus-depression comorbidity reflects shared DLPFC hypofunction amplifying both phantom sound distress and mood symptoms. L-DLPFC TPS targets both via shared neural substrate.',
        },
        {
            'code': 'P5', 'name': 'Hyperacusis',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3/C4+T3 cathode', 'TPS FT6 hyperacusis', 'Sound desensitization'],
            'card_left': ['Network: Auditory SN hyperactivation', 'Key target: Auditory cortex, SN, ACC', 'Priority: Sound tolerance restoration'],
            'card_right': ['TPS: FT6 + T3', 'tDCS: C5/F6', 'PlatoScience: C7-PS/FP6', 'Desensitization'],
            'brain_targets': [
                ['Auditory cortex', 'Sound amplification', 'Normalize', 'T1 / C5 / FP6', 'Emerging'],
                ['SN nodes (Cz)', 'Sound salience', 'Reduce', 'FT6 / Cz', 'Emerging'],
                ['ACC', 'Sound distress', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Insula', 'Sound-body response', 'Normalize', 'FT5 / C3', 'Emerging'],
                ['DLPFC', 'Top-down filter', 'Activate', 'T2 / C2', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C5 T3 cathode', 'TPS auditory normalize', 'Graduated sound exposure'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS SN suppress', 'Sound desensitization protocol'],
                ['taVNS 20 min', 'tDCS F6', 'TPS ACC', 'Tolerance hierarchy'],
                ['CES 20 min', 'tDCS C3', 'TPS insula', 'Relaxation during sound'],
            ],
            'task_pairing': 'Graduated sound exposure (desensitization hierarchy), relaxation during sound exposure, sound tolerance tracking.',
            'fnon_hypothesis': 'Hyperacusis reflects auditory cortex gain increase combined with SN hypersensitivity to sound. Auditory TPS + graduated exposure drives habituation through direct cortical + behavioral mechanisms.',
        },
        {
            'code': 'P6', 'name': 'Somatic / Pulsatile Tinnitus',
            'sozo_bar': ['taVNS 30 min', 'tDCS T3/T4 + Cz', 'TPS auditory+insula', 'Body awareness task'],
            'card_left': ['Network: Somatosensory-auditory coupling', 'Key target: Auditory, insula, SMA', 'Priority: Somatosensory modulation'],
            'card_right': ['TPS: T1+T3 + FT3', 'tDCS: C3/F3', 'PlatoScience: C2-PS/FP1', 'Somatic task'],
            'brain_targets': [
                ['Auditory T3/T4', 'Phantom sound', 'Modulate', 'T1 / C1 / FP1', 'Evidence A'],
                ['Insula', 'Somatosensory-auditory', 'Normalize', 'T3 / C3', 'Emerging'],
                ['SMA', 'Motor-auditory coupling', 'Modulate', 'TPS Fz', 'Emerging'],
                ['DLPFC', 'Control signal', 'Activate', 'T2 / C2', 'Evidence B'],
                ['ACC', 'Awareness modulation', 'Reduce', 'T3 / C3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3 T3/T4', 'TPS auditory+insula', 'Somatic tinnitus tasks'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS SMA', 'Jaw/neck relaxation'],
                ['taVNS 20 min', 'tDCS F3', 'TPS DLPFC', 'Somatosensory retraining'],
                ['CES 20 min', 'tDCS C3', 'TPS ACC', 'Body awareness mindfulness'],
            ],
            'task_pairing': 'Somatic tinnitus tasks (jaw/neck), somatosensory retraining, body awareness mindfulness, relaxation of somatic triggers.',
            'fnon_hypothesis': 'Somatic tinnitus reflects abnormal somatosensory-auditory coupling allowing jaw/neck inputs to generate phantom sound. Insula TPS normalizes cross-modal sensory integration.',
        },
        {
            'code': 'P7', 'name': 'Tinnitus + Anxiety',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4 + T3', 'TPS DLPFC+auditory', 'CBT anxiety + TRT'],
            'card_left': ['Network: SN hyperactivation + tinnitus fear', 'Key target: DLPFC, vmPFC, auditory', 'Priority: Tinnitus anxiety cycle'],
            'card_right': ['TPS: T2+T1 + FT3', 'tDCS: C8/F2', 'PlatoScience: C6-PS/FP2', 'CBT+TRT task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety + distress', 'Activate', 'T2 / C8 / FP2', 'Evidence B'],
                ['vmPFC', 'Tinnitus safety signal', 'Strengthen', 'T5 / F2', 'Emerging'],
                ['SN nodes', 'Tinnitus threat', 'Reduce', 'FT5 / Cz', 'Emerging'],
                ['Amygdala', 'Tinnitus fear', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['Auditory T3/T4', 'Sound source', 'Modulate', 'T1 / C1', 'Evidence A'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C8 F3+T3', 'TPS DLPFC+auditory', 'CBT anxiety + TRT'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Tinnitus fear exposure'],
                ['taVNS 20 min', 'tDCS F2', 'TPS SN suppress', 'Acceptance tinnitus'],
                ['CES 20 min', 'tDCS C3', 'TPS amygdala', 'Relaxation with sound'],
            ],
            'task_pairing': 'CBT for tinnitus anxiety, tinnitus fear exposure hierarchy, acceptance-based tinnitus therapy, relaxation with sound therapy.',
            'fnon_hypothesis': 'Tinnitus-anxiety reflects SN hyperactivation treating tinnitus as persistent threat signal. DLPFC TPS + vmPFC strengthening during TRT builds tinnitus-as-neutral-signal habituation.',
        },
        {
            'code': 'P8', 'name': 'Post-Noise Trauma Tinnitus',
            'sozo_bar': ['taVNS 20 min', 'tDCS T3/T4 cathodes', 'TPS auditory bilateral', 'Sound protection + TRT'],
            'card_left': ['Network: Acute-on-chronic auditory damage', 'Key target: Auditory cortex bilateral', 'Priority: Early intervention'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Early TRT'],
            'brain_targets': [
                ['Auditory cortex bilateral', 'Reorganization prevention', 'Normalize early', 'T1 / C1 / FP1', 'Evidence A'],
                ['Belt areas', 'Secondary changes', 'Limit', 'TPS T5/T6', 'Emerging'],
                ['DLPFC', 'Distress prevention', 'Activate', 'T2 / C2', 'Evidence B'],
                ['ACC', 'Early distress', 'Modulate', 'T3 / C3', 'Emerging'],
                ['vmPFC', 'Habituation early', 'Prime', 'T5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1 T3/T4', 'TPS auditory early', 'Early TRT intervention'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', 'Tinnitus psychoeducation'],
                ['taVNS 20 min', 'tDCS F1', 'TPS T3/T4+DLPFC', 'Sound therapy broadband'],
                ['CES 20 min', 'tDCS C8', 'TPS bilateral', 'Ear protection + TRT'],
            ],
            'task_pairing': 'Early TRT intervention, tinnitus psychoeducation, broadband sound therapy, ear protection counseling.',
            'fnon_hypothesis': 'Post-noise trauma tinnitus benefits most from early auditory cortex intervention before maladaptive reorganization consolidates. Early TPS + TRT prevents LIMBIC loop establishment.',
        },
        {
            'code': 'P9', 'name': 'Severe Chronic Tinnitus (Treatment-Resistant)',
            'sozo_bar': ['taVNS 20 min', 'HDCstim T3/T4+F3/F4', 'TPS FT9 rotating', 'Intensive TRT'],
            'card_left': ['Network: Multi-network chronic tinnitus entrainment', 'Key target: All tinnitus network nodes', 'Priority: Maximum network disruption'],
            'card_right': ['TPS: FT9 full rotating', 'tDCS: C8/F2+F6', 'PlatoScience: C8-PS/FP2', 'Intensive TRT'],
            'brain_targets': [
                ['Auditory bilateral', 'Phantom sound maximal', 'Suppress rotating', 'T1 bilateral / C8', 'Evidence A'],
                ['DLPFC bilateral', 'Distress maximum', 'Maximize activation', 'T2 / C2 / FP2', 'Evidence B'],
                ['ACC', 'Chronic suffering', 'Reduce', 'T3 / C3', 'Evidence B'],
                ['LIMBIC', 'Emotional entrainment', 'Disrupt', 'FT3+FT8 rotating', 'Emerging'],
                ['vmPFC', 'Habituation maximize', 'Prime', 'T5 / F2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'HDCstim T3/T4', 'TPS auditory rotating', 'Intensive TRT daily'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS DLPFC+ACC', 'Acceptance + mindfulness'],
                ['taVNS 20 min', 'tDCS C8', 'TPS LIMBIC temporal', 'ACT tinnitus intensive'],
                ['CES 20 min', 'HDCstim F3/F4', 'TPS vmPFC habituation', 'Comprehensive CBT-T'],
            ],
            'task_pairing': 'Intensive daily TRT, comprehensive CBT for tinnitus (CBT-T), ACT tinnitus intensive, mindfulness-based tinnitus stress reduction.',
            'fnon_hypothesis': 'Treatment-resistant tinnitus reflects multi-network entrainment with auditory-LIMBIC-CEN co-activation. Rotating multisite TPS disrupts network synchrony from multiple angles simultaneously.',
        },
    ],
    'task_pairing_rows': [
        ['Sound therapy (TRT)', 'Concurrent tDCS', 'Sound', 'All phenotypes'],
        ['CBT tinnitus', 'Post-TPS', 'Psychological', 'P2, P4, P7'],
        ['Sleep + TRT', 'Evening CES', 'Sleep', 'P3'],
        ['BA + TRT', 'Post-TPS', 'Mood', 'P4'],
        ['Sound desensitization', 'Concurrent tDCS', 'Hyperacusis', 'P5'],
        ['Somatic tasks', 'Post-TPS', 'Somatic', 'P6'],
        ['Mindfulness tinnitus', 'During taVNS', 'Mindfulness', 'P9'],
        ['Psychoeducation', 'Pre-session', 'Education', 'P8'],
    ],
    'followup_rows': [
        ['Week 2', 'THI, TFI', 'Tinnitus handicap + function', 'Check distress trajectory'],
        ['Week 4', 'THI, TFI, PHQ-9', 'Tinnitus + mood', 'Adjust protocol'],
        ['Week 6', 'Full tinnitus battery', 'Comprehensive', 'Phase 2 decision'],
        ['Week 10', 'THI, TFI, sleep', 'Long-term trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'THI, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default(3, 2, 3, 5, 3, 5, 2, 3, 3),
}
