"""Append Chronic Pain, PTSD, OCD condition data to generate_fellow_protocols.py"""
import os
OUTFILE = os.path.join(os.path.dirname(__file__), "generate_fellow_protocols.py")

BLOCK = '''
# ---------------------------------------------------------------------------
# CONDITION: CHRONIC PAIN
# ---------------------------------------------------------------------------
CONDITIONS["chronic_pain"] = dict(
    name="Chronic Pain Syndrome",
    icd10="G89.29",
    doc_num="SPG-CP-001",
    tps_status="Investigational",
    tdcs_class="Class IIa",
    tps_class="Investigational",
    tavns_class="Class IIb",
    ces_class="Class IIa",
    inclusion=[
        "Chronic pain ≥3 months duration meeting IASP criteria",
        "Diagnosis of chronic pain syndrome (ICD-10 G89.29) confirmed by pain specialist",
        "NRS pain score ≥4/10 at baseline on at least 3 consecutive days",
        "Inadequate response to ≥2 pharmacological treatments (anticonvulsants, SNRIs, opioids)",
        "Age 18–75 years; capable of informed consent",
        "Stable medication regimen for ≥4 weeks prior to enrollment",
    ],
    exclusion=[
        "Active malignancy or cancer-related pain",
        "Metallic implants in head/neck region (TPS/tDCS contraindication)",
        "Severe psychiatric comorbidity (active psychosis, suicide attempt <6 months)",
        "Pregnancy or planned pregnancy",
        "Active substance use disorder (excluding cannabis with stable use)",
        "Implanted neurostimulator or cardiac pacemaker",
        "Fibromyalgia as sole diagnosis without central sensitization evidence",
    ],
    discussion=[
        "Chronic pain involves maladaptive neuroplasticity across nociceptive and central sensitization pathways.",
        "The anterior cingulate cortex (ACC) and insula are primary hubs for pain affect and interoception.",
        "Thalamocortical dysrhythmia and reduced descending inhibition are core pathophysiological features.",
        "tDCS targeting M1 (anodal) reduces pain intensity through cortical excitability modulation.",
        "TPS over ACC and prefrontal regions addresses the affective-motivational dimension of pain.",
        "taVNS activates the nucleus tractus solitarius and locus coeruleus, enhancing descending inhibition.",
        "CES (Alpha-Stim) modulates thalamic relay nuclei and reduces central sensitization.",
        "Combination NIBS produces synergistic analgesia through convergent network normalization.",
    ],
    overview=[
        "Chronic pain syndrome represents a complex biopsychosocial condition characterized by persistent pain lasting beyond expected tissue healing time (>3 months), accompanied by neurobiological, psychological, and social consequences. Globally, chronic pain affects 20-30% of adults, generating immense disability and healthcare burden.",
        "The SOZO NIBS protocol targets the neurobiological underpinnings of chronic pain: maladaptive central sensitization, thalamocortical dysrhythmia, impaired descending pain inhibition, and dysfunctional salience processing. The protocol integrates tDCS (M1/DLPFC), TPS (ACC/insula), taVNS (vagus nerve), and CES (Alpha-Stim) in a phenotype-guided multimodal framework.",
        "Treatment is organized around six clinical phenotypes: neuropathic dominant, central sensitization dominant, affective-pain dominant, musculoskeletal-central mixed, catastrophizing dominant, and sleep-pain comorbid. Each phenotype receives a tailored NIBS combination targeting the most relevant neural circuits.",
    ],
    pathophysiology=[
        "Central sensitization: wind-up of spinal and supraspinal nociceptive neurons via NMDA-receptor-mediated LTP leads to hyperalgesia and allodynia.",
        "Thalamocortical dysrhythmia: abnormal alpha/theta oscillations in somatosensory thalamus maintain persistent pain percept independent of peripheral input.",
        "Reduced descending inhibition: impaired noradrenergic and serotonergic projections from PAG, RVM, and locus coeruleus reduce endogenous analgesia.",
        "ACC and insula hyperactivation: affective-motivational pain processing is amplified, driving catastrophizing and pain-related fear.",
        "DLPFC hypoactivity: reduced cognitive control over pain allows salience network dominance and rumination.",
        "DMN-SN dysconnection: default mode network is invaded by salience network, perpetuating pain catastrophizing and self-referential suffering.",
    ],
    std_treatment=[
        "Pharmacological: SNRIs (duloxetine), anticonvulsants (gabapentin, pregabalin), tricyclic antidepressants, opioids (limited), topical agents",
        "Interventional: nerve blocks, spinal cord stimulation, intrathecal therapy",
        "Psychological: CBT-based pain management, acceptance and commitment therapy (ACT), mindfulness",
        "Physical rehabilitation: graded motor imagery, pain neuroscience education, exercise therapy",
        "Multidisciplinary pain programs: integrated biopsychosocial rehabilitation",
    ],
    symptoms=[
        ["Spontaneous Pain", "Ongoing, burning, aching, stabbing", "100%", "IASP 2020"],
        ["Hyperalgesia", "Exaggerated response to painful stimuli", "75%", "Woolf 2011"],
        ["Allodynia", "Pain from non-painful stimuli (touch, pressure)", "60%", "Costigan 2009"],
        ["Sleep Disturbance", "Insomnia, non-restorative sleep", "80%", "Moldofsky 2010"],
        ["Fatigue", "Persistent fatigue disproportionate to activity", "75%", "Cleeland 2010"],
        ["Depression", "Comorbid major depression or dysthymia", "50%", "McWilliams 2003"],
        ["Anxiety", "Pain-related fear, health anxiety, GAD features", "45%", "Asmundson 2009"],
        ["Cognitive Dysfunction", "Reduced attention, memory, processing speed (pain fog)", "55%", "Moriarty 2011"],
        ["Catastrophizing", "Magnification, rumination, helplessness", "60%", "Sullivan 2001"],
        ["Reduced Mobility", "Activity avoidance, deconditioning", "70%", "Vlaeyen 2000"],
    ],
    brain_regions=[
        ["Primary Somatosensory Cortex (S1)", "Sensory-discriminative pain processing", "tDCS anodal M1 adjacent", "Fregni 2006"],
        ["Motor Cortex (M1)", "Descending motor-pain modulation, excitability regulation", "tDCS anodal M1", "Lefaucheur 2016"],
        ["Anterior Cingulate Cortex (ACC)", "Affective-motivational pain processing, catastrophizing", "TPS, tDCS cathodal", "Rainville 1997"],
        ["Insula", "Interoception, pain salience, autonomic integration", "TPS", "Craig 2002"],
        ["DLPFC", "Cognitive modulation of pain, placebo analgesia", "tDCS anodal", "Seminowicz 2013"],
        ["PAG/RVM", "Descending inhibitory control", "taVNS indirect", "Fields 2004"],
        ["Thalamus", "Thalamocortical relay, dysrhythmia hub", "CES", "Llinás 1999"],
        ["Basal Ganglia", "Reward-pain interaction, motivation-pain coupling", "TPS", "Navratilova 2012"],
    ],
    brainstem=[
        ["Periaqueductal Gray (PAG)", "Origin of descending inhibition, opioidergic modulation", "taVNS", "Basbaum 1984"],
        ["Rostral Ventromedial Medulla (RVM)", "ON/OFF cell balance for facilitation vs inhibition", "taVNS", "Fields 2004"],
        ["Locus Coeruleus (LC)", "Noradrenergic descending inhibition", "taVNS/CES", "Jones 1991"],
        ["Nucleus Raphe Magnus", "Serotonergic descending modulation", "taVNS", "Basbaum 1984"],
        ["Nucleus Tractus Solitarius (NTS)", "Vagal integration, pain gating", "taVNS direct", "Tracey 2002"],
    ],
    phenotypes=[
        ["Neuropathic Dominant", "Burning, lancinating pain; allodynia; positive sensory signs", "Hyperalgesia, paresthesias, sleep disruption", "tDCS M1 anodal + TPS"],
        ["Central Sensitization", "Widespread pain; fatigue; cognitive fog; no peripheral lesion", "Allodynia, hyperalgesia, fibromyalgia features", "tDCS DLPFC + TPS ACC + CES"],
        ["Affective-Pain Dominant", "High catastrophizing; depression-pain comorbidity; pain affect disproportionate", "Low mood, pain rumination, social withdrawal", "tDCS DLPFC anodal + TPS ACC + taVNS"],
        ["Musculoskeletal-Central Mixed", "Structural pathology + central amplification; inconsistent response to local treatment", "MSK pain + central features", "tDCS M1 + TPS + CES"],
        ["Catastrophizing Dominant", "High PCS scores; extreme disability relative to objective findings", "Helplessness, magnification, fear-avoidance", "tDCS DLPFC + taVNS + CBT co-treatment"],
        ["Sleep-Pain Comorbid", "Insomnia drives pain amplification; bidirectional relationship", "Non-restorative sleep, fatigue, pain escalation", "CES primary + tDCS M1 + taVNS"],
    ],
    symptom_map=[
        ["Spontaneous pain", "M1/S1", "tDCS anodal M1", "Lefaucheur 2016 Class IIa"],
        ["Allodynia/Hyperalgesia", "Thalamus/S1", "CES + tDCS", "Antal 2010 Class IIb"],
        ["Affective pain (suffering)", "ACC/Insula", "TPS + taVNS", "Rainville 1997"],
        ["Catastrophizing", "DLPFC/ACC", "tDCS DLPFC anodal", "Seminowicz 2013"],
        ["Sleep disruption", "Thalamus/Cortex", "CES Alpha-Stim", "Lande 2018"],
        ["Fatigue", "CEN/SN", "taVNS + tDCS DLPFC", "Vonck 2014"],
        ["Depression comorbidity", "DLPFC/SGC", "tDCS DLPFC + taVNS", "Brunoni 2013"],
        ["Cognitive fog", "DLPFC/CEN", "tDCS DLPFC anodal", "Brunoni 2016"],
        ["Descending inhibition deficit", "PAG/LC/RVM", "taVNS", "Busch 2013"],
    ],
    montage=[
        ["Neuropathic Dominant", "Anodal M1 contralateral (2mA, 20min)", "ACC (300 pulses)", "Gabapentin co-treatment"],
        ["Central Sensitization", "Anodal DLPFC (2mA, 20min)", "ACC + S1 (400 pulses)", "CES Alpha-Stim nightly"],
        ["Affective-Pain", "Anodal DLPFC (2mA, 20min)", "ACC (300 pulses)", "taVNS 30min pre-session"],
        ["Musculoskeletal-Central", "Anodal M1 (2mA) + DLPFC", "S1/M1 (300 pulses)", "CES 3x/week"],
        ["Catastrophizing Dominant", "Anodal DLPFC (2mA, 20min)", "ACC (300 pulses)", "Concurrent CBT sessions"],
        ["Sleep-Pain Comorbid", "Anodal M1 (1.5mA, 20min)", "None initial", "CES Alpha-Stim primary nightly"],
        ["Refractory Pain", "Bifrontal tDCS (2mA)", "Full protocol (500 pulses)", "taVNS 4x/day"],
        ["Elderly/Fragile", "Anodal M1 (1mA, 15min)", "TPS low (200 pulses)", "CES primary; taVNS standard"],
        ["Pediatric (off-label)", "Not recommended <18", "Not recommended <18", "CES only per specialist"],
        ["Post-Surgical", "DLPFC anodal (2mA, 20min)", "None acute phase", "taVNS + CES"],
    ],
    tdcs_protocols=[
        ["CP-tDCS-01", "M1 Anodal (Neuropathic)", "C3/C4 contralateral", "Fp2", "2mA, 20min, 10 sessions", "Lefaucheur 2016"],
        ["CP-tDCS-02", "DLPFC Anodal (Affective/Catastrophizing)", "F3 (left DLPFC)", "F4", "2mA, 20min, 10 sessions", "Brunoni 2013"],
        ["CP-tDCS-03", "Bifrontal (Refractory)", "F3 anodal", "F4 cathodal", "2mA, 20min, 10–20 sessions", "Fregni 2006"],
        ["CP-tDCS-04", "M1 + DLPFC Combined", "C3 anodal; F3 anodal sequential", "Fp2; F4", "2mA each, 20min, 15 sessions", "Roizenblatt 2007"],
        ["CP-tDCS-05", "S1 Cathodal (Central Sensitization)", "Fp2", "C3/C4", "1.5mA, 20min, 10 sessions", "Antal 2010"],
        ["CP-tDCS-06", "Maintenance Phase", "F3 anodal (DLPFC)", "F4", "1.5mA, 20min, 2x/week", "Bikson 2016"],
        ["CP-tDCS-07", "Elderly Adjusted", "C3 anodal M1", "Fp2", "1mA, 15min, 10 sessions", "Lefaucheur 2016"],
        ["CP-tDCS-08", "Sham Protocol", "F3 anodal", "F4", "30s ramp, 0mA active, 20min", "Brunoni 2013"],
    ],
    plato_protocols=[
        ["CP-PLATO-01", "Neuropathic M1", "C3/C4", "M1 contralateral", "C3", "2.0mA", "N/A", "Continuous 20min"],
        ["CP-PLATO-02", "DLPFC Anodal", "F3/F4", "Left DLPFC", "F3", "2.0mA", "N/A", "Continuous 20min"],
        ["CP-PLATO-03", "HD-tDCS Pain Ring", "C3 center", "4-electrode ring", "C3", "1.0mA", "N/A", "HD mode 20min"],
        ["CP-PLATO-04", "Bifrontal", "F3/F4", "Bifrontal", "F3", "2.0mA", "N/A", "Sequential F3 then F4"],
        ["CP-PLATO-05", "Maintenance", "F3", "DLPFC", "F3", "1.5mA", "N/A", "2x/week 20min"],
        ["CP-PLATO-06", "Gamma tACS Pain", "C3", "M1", "C3", "1.5mA", "40Hz", "tACS mode 20min"],
        ["CP-PLATO-07", "Elderly Adjusted", "C3", "M1", "C3", "1.0mA", "N/A", "15min continuous"],
        ["CP-PLATO-08", "Sham", "F3", "DLPFC", "F3", "0mA", "N/A", "Ramp only 30s"],
    ],
    tps_protocols=[
        ["CP-TPS-01", "ACC Affective Pain", "ACC (BA24/32)", "300 pulses, 0.25Hz, 0.2mJ/mm²", "3 sessions/week", "Leinenga 2022"],
        ["CP-TPS-02", "S1/M1 Sensory-Discriminative", "S1, M1 contralateral", "300 pulses, 0.25Hz", "3 sessions/week", "Fregni 2006"],
        ["CP-TPS-03", "DLPFC Cognitive Pain", "DLPFC (BA46)", "250 pulses, 0.2Hz", "2 sessions/week", "Seminowicz 2013"],
        ["CP-TPS-04", "Insula Interoceptive", "Posterior Insula", "200 pulses, 0.2Hz", "2 sessions/week", "Craig 2002"],
        ["CP-TPS-05", "Full Protocol (Refractory)", "ACC + S1 + DLPFC sequential", "500 pulses total", "5 sessions/week x2 weeks", "Mulak 2023"],
    ],
    ces_role=[
        ["Central Sensitization", "Primary modality to reduce thalamic dysrhythmia and sensitization", "Nightly 60min + NIBS daytime"],
        ["Sleep-Pain Comorbid", "Primary modality; improves sleep architecture and pain threshold", "Nightly 60min; titrate to sleep quality"],
        ["Adjunct Analgesia", "Additive analgesia with tDCS M1 or TPS", "Prior to or concurrent with tDCS/TPS"],
        ["Maintenance Phase", "Sustain gains; reduce relapse; patient self-administered", "3–5x/week; patient-managed"],
    ],
    tavns_role="taVNS (tragus, 25Hz, 200µs, 0.5mA, 30min) activates the nucleus tractus solitarius, projecting to PAG and locus coeruleus to enhance descending noradrenergic inhibition. Particularly effective in affective-pain and catastrophizing phenotypes. Administered prior to tDCS/TPS sessions. Home device (Nemos/TENS) 2x daily for maintenance.",
    combinations=[
        ("Neuropathic Dominant", [
            ["tDCS M1 + TPS S1", "Convergent sensory-motor cortex normalization", "TPS first 20min, tDCS immediately after", "Peripheral neuropathic pain with central features"],
            ["tDCS M1 + CES", "M1 excitability + thalamic dysrhythmia correction", "Concurrent or sequential same session", "Neuropathic pain with sleep disruption"],
            ["tDCS M1 + taVNS", "Cortical excitability + descending inhibition", "taVNS 30min before tDCS", "Refractory neuropathic pain"],
        ]),
        ("Central Sensitization", [
            ["tDCS DLPFC + TPS ACC + CES", "Cognitive + affective + thalamic — triple-network", "TPS → tDCS → CES nightly", "Widespread pain, fibromyalgia features"],
            ["CES + taVNS", "Thalamic + vagal anti-sensitization", "Concurrent or taVNS before CES", "Severe sensitization, allodynia"],
        ]),
        ("Affective-Pain Dominant", [
            ["tDCS DLPFC + TPS ACC + taVNS", "Cognitive control + affective hub + vagal", "taVNS → TPS → tDCS sequential", "Depression-pain comorbidity, catastrophizing"],
            ["tDCS DLPFC + taVNS", "Anti-depressant + vagal anti-nociception", "taVNS 30min before tDCS", "High catastrophizing, depression-pain"],
        ]),
        ("Musculoskeletal-Central", [
            ["tDCS M1 + TPS S1 + CES", "MSK pain control + sensitization reversal", "TPS → tDCS → CES nightly", "MSK pain with central amplification"],
        ]),
        ("Catastrophizing Dominant", [
            ["tDCS DLPFC + taVNS + CBT", "Prefrontal upregulation + vagal + psychological", "CBT session day; taVNS + tDCS other days", "High PCS scores, disability-pain mismatch"],
        ]),
        ("Sleep-Pain Comorbid", [
            ["CES + tDCS M1 + taVNS", "Sleep architecture + pain threshold + vagal", "CES nightly; tDCS + taVNS daytime", "Insomnia driving pain amplification"],
        ]),
    ],
    combination_summary=[
        ["Neuropathic", "tDCS M1 + TPS S1", "Sensory-motor convergence", "TPS → tDCS", "Peripheral neuropathic", "IIa"],
        ["Central Sensitization", "tDCS DLPFC + TPS ACC + CES", "Triple-network sensitization reversal", "TPS → tDCS → CES nightly", "Widespread/fibromyalgia", "IIb"],
        ["Affective-Pain", "tDCS DLPFC + TPS ACC + taVNS", "Cognitive-affective-vagal", "taVNS → TPS → tDCS", "Depression-pain comorbid", "IIb"],
        ["MSK-Central", "tDCS M1 + TPS S1 + CES", "MSK + sensitization", "TPS → tDCS → CES", "Structural + central", "IIb"],
        ["Catastrophizing", "tDCS DLPFC + taVNS + CBT", "Prefrontal + vagal + psychological", "Integrated schedule", "High PCS, fear-avoidance", "IIb"],
        ["Sleep-Pain", "CES + tDCS M1 + taVNS", "Sleep + analgesia + vagal", "CES nightly + daytime NIBS", "Insomnia-pain cycle", "IIb"],
    ],
    outcomes=[
        ["NRS Pain Score", "Pain Intensity", "Weekly", "≥30% reduction from baseline"],
        ["Brief Pain Inventory (BPI)", "Pain Interference", "Baseline, 4wk, 8wk", "≥30% improvement in interference subscale"],
        ["Pain Catastrophizing Scale (PCS)", "Catastrophizing", "Baseline, 4wk, 8wk", "≥30% reduction in total score"],
        ["PROMIS Pain Interference", "Functional impact", "Baseline, 4wk, 8wk", "≥5-point T-score improvement"],
        ["Pittsburgh Sleep Quality Index (PSQI)", "Sleep quality", "Baseline, 4wk, 8wk", "≥3-point reduction (score <5 target)"],
        ["DASS-21", "Depression/Anxiety/Stress", "Baseline, 4wk, 8wk", "≥30% reduction in depression subscale"],
        ["Quantitative Sensory Testing (QST)", "Central sensitization markers", "Baseline, 8wk", "Normalization of pressure pain threshold"],
        ["Patient Global Impression of Change (PGIC)", "Overall treatment response", "4wk, 8wk", "Rating ≥5/7 (much improved or better)"],
        ["Medication Use Log", "Opioid/analgesic use", "Weekly", "≥20% reduction in morphine equivalents"],
    ],
    outcomes_abbrev=[
        "NRS: Numeric Rating Scale",
        "BPI: Brief Pain Inventory",
        "PCS: Pain Catastrophizing Scale",
        "PROMIS: Patient-Reported Outcomes Measurement Information System",
        "PSQI: Pittsburgh Sleep Quality Index",
        "DASS-21: Depression Anxiety Stress Scales",
        "QST: Quantitative Sensory Testing",
        "PGIC: Patient Global Impression of Change",
        "PPT: Pressure Pain Threshold",
    ],
)

# ---------------------------------------------------------------------------
# CONDITION: PTSD
# ---------------------------------------------------------------------------
CONDITIONS["ptsd"] = dict(
    name="Post-Traumatic Stress Disorder",
    icd10="F43.10",
    doc_num="SPG-PT-001",
    tps_status="Investigational",
    tdcs_class="Class IIb",
    tps_class="Investigational",
    tavns_class="Class IIa",
    ces_class="Class IIa",
    inclusion=[
        "DSM-5 PTSD diagnosis confirmed by structured clinical interview (CAPS-5 score ≥33)",
        "Trauma exposure at least 3 months prior; symptom onset after trauma",
        "PCL-5 score ≥33 at baseline",
        "Inadequate response to ≥1 evidence-based psychotherapy (PE, CPT, EMDR) or SSRI/SNRI",
        "Age 18–70; capable of informed consent and trauma narrative engagement",
        "Stable medication regimen for ≥4 weeks if on pharmacotherapy",
    ],
    exclusion=[
        "Active suicidality or self-harm within 3 months",
        "Active psychosis or dissociative identity disorder with frequent switching",
        "Metallic implants in head/neck or implanted neurostimulator",
        "Pregnancy",
        "Active substance use disorder (alcohol or illicit stimulants)",
        "Inability to tolerate trauma-focused content (extreme dissociation)",
        "Severe traumatic brain injury as primary etiology",
    ],
    discussion=[
        "PTSD is characterized by hyperactivated fear circuits (amygdala), impaired extinction (vmPFC/hippocampus), and dysregulated arousal (locus coeruleus/SNS).",
        "The ventromedial prefrontal cortex (vmPFC) fails to inhibit amygdala hyperreactivity, maintaining conditioned fear responses.",
        "DLPFC hypoactivity impairs working memory, emotional regulation, and top-down control of trauma memories.",
        "taVNS directly modulates the locus coeruleus and amygdala via NTS projections, reducing hyperarousal and fear generalization.",
        "tDCS targeting DLPFC (anodal) enhances extinction learning and reduces intrusive symptom burden.",
        "TPS over vmPFC and ACC addresses fear extinction deficits and affective dysregulation.",
        "CES (Alpha-Stim) reduces hyperarousal, improves sleep architecture, and attenuates HPA axis overdrive.",
        "NIBS is best applied as an augmentation to trauma-focused psychotherapy (PE, CPT, EMDR), not as monotherapy.",
    ],
    overview=[
        "Post-Traumatic Stress Disorder (PTSD) is a debilitating psychiatric disorder arising from exposure to traumatic events, characterized by four symptom clusters: re-experiencing (intrusions, nightmares), avoidance, negative cognitions/mood, and hyperarousal. The disorder affects approximately 3.9% of the global population and is disproportionately prevalent in veterans, first responders, and survivors of interpersonal violence.",
        "The SOZO NIBS protocol for PTSD targets dysregulated fear circuitry—amygdala hyperactivation, vmPFC/hippocampal extinction failure, DLPFC hypoactivity, and locus coeruleus-mediated hyperarousal—through a phenotype-guided multimodal neuromodulation framework integrated with evidence-based psychotherapy.",
        "Six clinical phenotypes are recognized: hyperarousal dominant, re-experiencing dominant, avoidance/emotional numbing, cognitive/negative cognition dominant, complex PTSD (C-PTSD), and dissociative subtype. Each receives a tailored NIBS protocol optimized for the dominant neural circuit dysfunction.",
    ],
    pathophysiology=[
        "Amygdala hyperreactivity: exaggerated fear conditioning and generalization; failure of habituation to trauma cues; drives intrusions and hyperarousal.",
        "vmPFC/hippocampal extinction failure: impaired fear extinction memory consolidation; re-experiencing persists because safety signals are not encoded.",
        "DLPFC hypoactivity: reduced working memory capacity, emotional regulation, and top-down modulation of amygdala and intrusive memories.",
        "Locus coeruleus hyperactivation: chronic noradrenergic overdrive drives hypervigilance, exaggerated startle, sleep disruption, and intrusive re-experiencing.",
        "HPA axis dysregulation: low baseline cortisol with exaggerated glucocorticoid reactivity; impairs hippocampal neurogenesis and extinction consolidation.",
        "Default Mode Network disruption: trauma-related self-referential processing invades DMN; impairs sense of safety, present-moment awareness, and identity.",
    ],
    std_treatment=[
        "First-line psychotherapy: Prolonged Exposure (PE), Cognitive Processing Therapy (CPT), EMDR",
        "Pharmacotherapy: SSRIs (sertraline, paroxetine FDA-approved), SNRIs (venlafaxine); prazosin for nightmares",
        "Adjunct: sleep hygiene, prazosin for trauma nightmares, buspirone for anxiety",
        "Emerging: MDMA-assisted psychotherapy (Phase 3), ketamine, stellate ganglion block",
        "Multimodal: integrated trauma-focused therapy with medication management",
    ],
    symptoms=[
        ["Intrusions/Flashbacks", "Involuntary trauma memory re-experiencing", "100%", "APA DSM-5 2013"],
        ["Nightmares", "Trauma-related disturbing dreams", "70%", "Levin 2002"],
        ["Hypervigilance", "Persistent threat monitoring, exaggerated startle", "85%", "Pole 2007"],
        ["Avoidance", "Trauma cue avoidance (internal and external)", "90%", "Foa 2009"],
        ["Emotional Numbing", "Anhedonia, detachment, restricted affect", "60%", "King 1998"],
        ["Negative Cognitions", "Guilt, shame, self-blame, hopelessness", "80%", "Ehlers 2000"],
        ["Concentration Difficulties", "Impaired attention and working memory", "75%", "Scott 2015"],
        ["Sleep Disturbance", "Insomnia, fragmented sleep, nightmares", "90%", "Germain 2013"],
        ["Dissociation", "Depersonalization, derealization (dissociative subtype)", "30%", "Lanius 2010"],
        ["Irritability/Aggression", "Anger outbursts, irritable mood", "70%", "Teten 2010"],
    ],
    brain_regions=[
        ["Amygdala", "Fear conditioning, threat detection, hyperreactivity", "taVNS, TPS", "LeDoux 2000"],
        ["vmPFC (BA11/10)", "Fear extinction, safety signal encoding, amygdala inhibition", "TPS, tDCS anodal", "Milad 2007"],
        ["Hippocampus", "Contextual fear memory, extinction consolidation", "taVNS, TPS", "Quirk 2006"],
        ["DLPFC", "Working memory, emotional regulation, top-down control", "tDCS anodal", "Morey 2009"],
        ["ACC (Rostral)", "Fear extinction, conflict monitoring, emotional regulation", "TPS", "Shin 2006"],
        ["Insula", "Interoception, body-based fear, threat prediction", "TPS", "Paulus 2006"],
        ["Locus Coeruleus", "Noradrenergic hyperarousal, startle, fight-or-flight", "taVNS, CES", "Southwick 1997"],
        ["Posterior Parietal Cortex", "Spatial context, threat localization", "tDCS", "Gilbertson 2002"],
    ],
    brainstem=[
        ["Locus Coeruleus (LC)", "Hyperactive noradrenergic arousal; drives hypervigilance and exaggerated startle", "taVNS/CES direct", "Southwick 1997"],
        ["Nucleus Tractus Solitarius (NTS)", "Vagal input integration; modulates LC and amygdala", "taVNS direct", "Porges 2007"],
        ["Periaqueductal Gray (PAG)", "Freeze/fight-or-flight control; hyperactivated in PTSD", "taVNS indirect", "Mobbs 2007"],
        ["Raphe Nuclei", "Serotonergic tone regulation; impaired in PTSD", "taVNS", "Drevets 1999"],
        ["Superior Colliculus", "Threat detection, orienting; hyperactivated", "None direct", "Öhman 2005"],
    ],
    phenotypes=[
        ["Hyperarousal Dominant", "Hypervigilance, exaggerated startle, insomnia, irritability; LC overdrive", "Sleep disruption, anger, concentration loss", "taVNS + CES + tDCS DLPFC"],
        ["Re-experiencing Dominant", "Intrusions, flashbacks, nightmares; amygdala-vmPFC dysfunction", "Distress, avoidance triggered by intrusions", "TPS vmPFC + tDCS DLPFC + taVNS"],
        ["Avoidance/Numbing", "Emotional constriction, social withdrawal, detachment; blunted amygdala-DLPFC", "Anhedonia, relationship impairment", "tDCS DLPFC anodal + taVNS + TPS"],
        ["Cognitive/Negative Cognition", "Guilt, shame, self-blame; negative worldview; DLPFC-DMN dysfunction", "Depression comorbidity, hopelessness", "tDCS DLPFC + TPS ACC + taVNS"],
        ["Complex PTSD (C-PTSD)", "Prolonged/repeated trauma; affect dysregulation, identity disturbance, relational difficulties", "All 4 clusters + affect storms", "tDCS DLPFC + TPS ACC + taVNS + CES"],
        ["Dissociative Subtype", "Depersonalization/derealization; over-modulated prefrontal suppression of amygdala", "Emotional detachment, unreality", "Specialized protocol; TPS insula + taVNS"],
    ],
    symptom_map=[
        ["Hypervigilance/startle", "Locus Coeruleus/Amygdala", "taVNS + CES", "Vonck 2014, Lande 2018"],
        ["Intrusions/flashbacks", "Amygdala/vmPFC", "TPS vmPFC + tDCS DLPFC", "Milad 2007"],
        ["Nightmares", "Amygdala/Thalamus", "CES nightly + taVNS", "Germain 2013"],
        ["Avoidance", "DLPFC/vmPFC", "tDCS DLPFC anodal", "Morey 2009"],
        ["Emotional numbing", "DLPFC/Striatum", "tDCS DLPFC + TPS", "Bryant 2010"],
        ["Negative cognitions", "DLPFC/ACC", "tDCS DLPFC + TPS ACC", "Seminowicz 2013"],
        ["Sleep disruption", "Thalamus/LC", "CES Alpha-Stim nightly", "Lande 2018"],
        ["Dissociation", "Insula/mPFC", "TPS insula; specialized", "Lanius 2010"],
        ["Concentration impairment", "DLPFC/CEN", "tDCS DLPFC anodal", "Brunoni 2016"],
    ],
    montage=[
        ["Hyperarousal Dominant", "Anodal DLPFC (F3, 2mA, 20min)", "None initial", "taVNS 30min daily + CES nightly"],
        ["Re-experiencing Dominant", "Anodal DLPFC (F3, 2mA, 20min)", "vmPFC (300 pulses)", "taVNS before sessions; integrate PE/CPT"],
        ["Avoidance/Numbing", "Anodal DLPFC (F3, 2mA, 20min)", "ACC (250 pulses)", "taVNS + combined psychotherapy"],
        ["Cognitive/Negative", "Anodal DLPFC (F3, 2mA, 20min)", "ACC/vmPFC (300 pulses)", "taVNS + CES"],
        ["Complex PTSD", "Anodal DLPFC (F3, 2mA, 20min)", "ACC + vmPFC (400 pulses)", "taVNS + CES nightly; trauma therapy essential"],
        ["Dissociative Subtype", "Cathodal DLPFC (F3, 1.5mA)", "Insula (200 pulses, low)", "taVNS only; specialized trauma program"],
        ["With Comorbid MDD", "Anodal left DLPFC (F3, 2mA, 20min)", "ACC (300 pulses)", "taVNS + CES; antidepressant maintained"],
        ["Veteran Population", "Anodal DLPFC (F3, 2mA, 20min)", "vmPFC (300 pulses)", "taVNS + CES; veteran-specific trauma protocol"],
        ["Elderly Adjusted", "Anodal DLPFC (F3, 1.5mA, 20min)", "vmPFC (200 pulses)", "CES primary; taVNS standard"],
        ["Maintenance", "Anodal DLPFC (F3, 1.5mA, 20min)", "None", "CES 3x/week; taVNS 2x daily home"],
    ],
    tdcs_protocols=[
        ["PT-tDCS-01", "DLPFC Anodal Left", "F3 (left DLPFC)", "F4", "2mA, 20min, 10 sessions", "Boggio 2010"],
        ["PT-tDCS-02", "Bifrontal Augmentation", "F3 anodal", "F4 cathodal", "2mA, 20min, 10–20 sessions", "Fregni 2006"],
        ["PT-tDCS-03", "vmPFC Anodal (Extinction Enhancement)", "Fpz", "Oz", "1.5mA, 20min, 10 sessions", "Milad 2007"],
        ["PT-tDCS-04", "Dissociative Subtype Cathodal DLPFC", "F4", "F3", "1.5mA, 20min, specialized", "Lanius 2010"],
        ["PT-tDCS-05", "Maintenance Protocol", "F3 anodal", "F4", "1.5mA, 20min, 2x/week", "Bikson 2016"],
        ["PT-tDCS-06", "Combined with PE Therapy", "F3 anodal", "F4", "2mA, 20min before PE session", "Rosenbaum 2019"],
        ["PT-tDCS-07", "Elderly Adjusted", "F3 anodal", "F4", "1.5mA, 20min, 10 sessions", "Lefaucheur 2016"],
        ["PT-tDCS-08", "Sham", "F3", "F4", "30s active, 0mA, 20min", "Boggio 2010"],
    ],
    plato_protocols=[
        ["PT-PLATO-01", "DLPFC Anodal Left", "F3/F4", "Left DLPFC", "F3", "2.0mA", "N/A", "Continuous 20min"],
        ["PT-PLATO-02", "vmPFC Anodal", "Fpz/Oz", "vmPFC", "Fpz", "1.5mA", "N/A", "Continuous 20min"],
        ["PT-PLATO-03", "Bifrontal", "F3/F4", "Bifrontal", "F3", "2.0mA", "N/A", "Sequential"],
        ["PT-PLATO-04", "HD-tDCS DLPFC", "F3 center", "4-electrode ring", "F3", "1.0mA", "N/A", "HD mode 20min"],
        ["PT-PLATO-05", "Maintenance", "F3", "DLPFC", "F3", "1.5mA", "N/A", "2x/week 20min"],
        ["PT-PLATO-06", "Theta Burst Mode", "F3", "DLPFC", "F3", "1.0mA", "5Hz", "tACS 20min"],
        ["PT-PLATO-07", "Elderly", "F3", "DLPFC", "F3", "1.5mA", "N/A", "15min"],
        ["PT-PLATO-08", "Sham", "F3", "DLPFC", "F3", "0mA", "N/A", "30s ramp"],
    ],
    tps_protocols=[
        ["PT-TPS-01", "vmPFC Extinction Enhancement", "vmPFC (BA10/11)", "300 pulses, 0.25Hz, 0.2mJ/mm²", "3 sessions/week", "Milad 2007"],
        ["PT-TPS-02", "ACC Conflict/Affect Regulation", "ACC (BA24/32)", "250 pulses, 0.2Hz", "3 sessions/week", "Shin 2006"],
        ["PT-TPS-03", "Insula (Dissociative Subtype)", "Posterior Insula", "200 pulses, 0.2Hz, low intensity", "2 sessions/week", "Lanius 2010"],
        ["PT-TPS-04", "DLPFC Working Memory", "DLPFC (BA46)", "250 pulses, 0.2Hz", "3 sessions/week", "Morey 2009"],
        ["PT-TPS-05", "Full Protocol (C-PTSD)", "vmPFC + ACC sequential", "400 pulses total", "5 sessions/week x2 weeks", "Expert consensus 2024"],
    ],
    ces_role=[
        ["Hyperarousal", "Primary modality for LC downregulation and startle reduction", "Daily 60min; before sleep or as needed"],
        ["Sleep Disruption", "Improves sleep onset, continuity, nightmare frequency", "Nightly 60min; titrate to sleep quality"],
        ["HPA Axis Dysregulation", "Modulates cortisol reactivity and autonomic balance", "Daily 60min; concurrent with psychotherapy"],
        ["Maintenance", "Sustain arousal reduction; patient self-administered", "3–5x/week; home device program"],
    ],
    tavns_role="taVNS (tragus, 25Hz, 200µs, 0.5mA, 30min) activates the NTS → LC → amygdala pathway, directly reducing noradrenergic hyperarousal and fear generalization. Particularly effective for hyperarousal and re-experiencing phenotypes. Administered before NIBS sessions and as home device 2x daily. Evidence supports extinction memory facilitation via hippocampal theta enhancement (Vonck 2014, Hulsey 2019).",
    combinations=[
        ("Hyperarousal Dominant", [
            ["taVNS + CES", "Dual LC downregulation via vagal and thalamic pathways", "taVNS 30min → CES nightly", "Hypervigilance, sleep disruption, startle"],
            ["taVNS + tDCS DLPFC", "Arousal reduction + prefrontal regulatory upregulation", "taVNS 30min before tDCS", "Hyperarousal with concentration impairment"],
        ]),
        ("Re-experiencing Dominant", [
            ["tDCS DLPFC + TPS vmPFC + taVNS", "Top-down fear control + extinction + vagal fear modulation", "taVNS → TPS → tDCS, pre-therapy", "Intrusions, flashbacks; integrates with PE/EMDR"],
            ["tDCS DLPFC + TPS ACC", "Prefrontal + conflict resolution for trauma memory", "TPS → tDCS pre-session", "Intrusion-dominant without severe dissociation"],
        ]),
        ("Complex PTSD", [
            ["tDCS DLPFC + TPS ACC + taVNS + CES", "Quadruple modality for complex multi-domain dysfunction", "taVNS → TPS → tDCS daytime; CES nightly", "C-PTSD with affect storms and insomnia"],
        ]),
        ("Avoidance/Numbing", [
            ["tDCS DLPFC + taVNS", "Motivational activation + vagal engagement", "taVNS 30min before tDCS", "Emotional numbing, social withdrawal"],
        ]),
        ("Cognitive/Negative Cognition", [
            ["tDCS DLPFC + TPS ACC + taVNS", "Cognitive + conflict + vagal triple approach", "taVNS → TPS → tDCS", "Guilt, shame, hopelessness"],
        ]),
        ("Dissociative Subtype", [
            ["TPS insula + taVNS", "Interoceptive reintegration + vagal grounding", "TPS → taVNS; no tDCS anodal DLPFC", "Depersonalization, derealization"],
        ]),
    ],
    combination_summary=[
        ["Hyperarousal", "taVNS + CES", "LC downregulation dual pathway", "taVNS → CES nightly", "Hypervigilance, insomnia", "IIa"],
        ["Re-experiencing", "tDCS DLPFC + TPS vmPFC + taVNS", "Fear control + extinction + vagal", "taVNS → TPS → tDCS", "Intrusions, flashbacks", "IIb"],
        ["Avoidance/Numbing", "tDCS DLPFC + taVNS", "Motivational + vagal activation", "taVNS before tDCS", "Numbing, withdrawal", "IIb"],
        ["Cognitive/Negative", "tDCS DLPFC + TPS ACC + taVNS", "Prefrontal + conflict + vagal", "taVNS → TPS → tDCS", "Guilt, hopelessness", "IIb"],
        ["Complex PTSD", "All four modalities", "Multi-domain circuit normalization", "taVNS → TPS → tDCS + CES", "C-PTSD multi-cluster", "IIb"],
        ["Dissociative", "TPS insula + taVNS", "Interoceptive reintegration", "TPS → taVNS", "Depersonalization/derealization", "IIb"],
    ],
    outcomes=[
        ["CAPS-5 Total Score", "PTSD symptom severity", "Baseline, 4wk, 8wk", "≥15-point reduction (response); <11 (remission)"],
        ["PCL-5 Score", "PTSD symptom self-report", "Weekly", "≥10-point reduction from baseline"],
        ["PHQ-9", "Depression comorbidity", "Baseline, 4wk, 8wk", "≥5-point reduction"],
        ["Pittsburgh Sleep Quality Index (PSQI)", "Sleep quality", "Baseline, 4wk, 8wk", "≥3-point improvement"],
        ["Heart Rate Variability (HRV)", "Autonomic regulation (vagal tone)", "Baseline, 4wk, 8wk", "≥10% increase in RMSSD"],
        ["Connor-Davidson Resilience Scale", "Resilience", "Baseline, 8wk", "≥5-point increase"],
        ["Dissociative Experiences Scale (DES)", "Dissociation (dissociative subtype)", "Baseline, 4wk, 8wk", "≥30% reduction"],
        ["Extinction Recall Test", "vmPFC extinction function", "Baseline, 8wk", "Improved safety signal recall"],
        ["Patient Global Impression of Change (PGIC)", "Overall improvement", "4wk, 8wk", "≥5/7 (much improved)"],
    ],
    outcomes_abbrev=[
        "CAPS-5: Clinician-Administered PTSD Scale for DSM-5",
        "PCL-5: PTSD Checklist for DSM-5",
        "PHQ-9: Patient Health Questionnaire-9",
        "PSQI: Pittsburgh Sleep Quality Index",
        "HRV: Heart Rate Variability",
        "RMSSD: Root Mean Square of Successive RR Differences",
        "DES: Dissociative Experiences Scale",
        "PGIC: Patient Global Impression of Change",
        "vmPFC: Ventromedial Prefrontal Cortex",
        "LC: Locus Coeruleus",
    ],
)

# ---------------------------------------------------------------------------
# CONDITION: OCD
# ---------------------------------------------------------------------------
CONDITIONS["ocd"] = dict(
    name="Obsessive-Compulsive Disorder",
    icd10="F42.2",
    doc_num="SPG-OC-001",
    tps_status="Investigational",
    tdcs_class="Class IIb",
    tps_class="Investigational",
    tavns_class="Class IIb",
    ces_class="Class IIb",
    inclusion=[
        "DSM-5 OCD diagnosis confirmed by structured interview (YBOCS score ≥16 at baseline)",
        "Symptom duration ≥6 months with significant functional impairment (CGI-S ≥4)",
        "Inadequate response to ≥2 adequate SSRI trials (≥12 weeks at therapeutic dose) or prior ERP failure",
        "Age 18–70; capable of informed consent and ERP engagement",
        "Stable medication for ≥8 weeks prior to enrollment",
        "Willing to maintain concurrent ERP throughout NIBS protocol",
    ],
    exclusion=[
        "Active suicidality or self-harm within 3 months",
        "Metallic implants in head/neck or implanted neurostimulator",
        "Pregnancy",
        "Active psychosis or bipolar disorder (manic phase)",
        "Hoarding disorder as sole presentation without classic OCD circuitry involvement",
        "Prior neurosurgical procedure for OCD (DBS, ablation)",
        "Seizure disorder or epilepsy",
    ],
    discussion=[
        "OCD is characterized by hyperactivation of the cortico-striato-thalamo-cortical (CSTC) loop — specifically the OFC-caudate-thalamo-OFC circuit driving compulsive urges.",
        "The orbitofrontal cortex (OFC) and anterior cingulate cortex (ACC) are hyperactive, generating excessive error signals and harm-avoidance urges.",
        "The supplementary motor area (SMA) and pre-SMA are involved in motor initiation of compulsions and response inhibition failure.",
        "tDCS targeting SMA (cathodal) reduces compulsion urgency by downregulating motor preparation circuits.",
        "tDCS targeting DLPFC (anodal) enhances top-down regulation of OFC and supports ERP-based response prevention.",
        "TPS over OFC and ACC directly modulates the hyperactive error-monitoring circuitry.",
        "taVNS activates the LC and raphe, enhancing serotonergic tone that is pharmacologically targeted by SSRIs.",
        "CES provides supplementary anxiolytic benefit and augments SSRI response through thalamic modulation.",
    ],
    overview=[
        "Obsessive-Compulsive Disorder (OCD) is a chronic, often disabling neuropsychiatric condition characterized by intrusive, ego-dystonic obsessions and repetitive compulsions performed to neutralize distress. With a lifetime prevalence of 2-3%, OCD ranks among the top 10 causes of disability worldwide. Core pathophysiology involves hyperactivity of the OFC-caudate-thalamo-OFC (CSTC) circuit, generating a pathological alarm signal that drives compulsive behavior.",
        "The SOZO NIBS protocol targets OCD's CSTC hyperactivation through a phenotype-guided multimodal neuromodulation framework: tDCS (SMA cathodal / DLPFC anodal), TPS (OFC/ACC/SMA), taVNS (serotonergic augmentation), and CES (Alpha-Stim, anxiolytic adjunct). All NIBS is integrated with concurrent ERP (Exposure and Response Prevention) as the required psychotherapy backbone.",
        "Five clinical phenotypes guide protocol selection: contamination/washing dominant, harm obsession/checking dominant, symmetry/ordering dominant, intrusive thought dominant, and treatment-refractory OCD. Each phenotype targets the most implicated circuit nodes within the shared CSTC architecture.",
    ],
    pathophysiology=[
        "CSTC hyperactivation: orbitofrontal cortex → caudate nucleus → thalamus → OFC loop is hyperactive; generates persistent false alarm error signals driving compulsion.",
        "OFC error monitoring: hyperactive OFC produces excessive harm-appraisal and contamination threat signals; direct TPS target.",
        "ACC conflict monitoring: hyperactivated dACC amplifies uncertainty intolerance; drives compulsive checking behavior.",
        "SMA/pre-SMA hyperactivation: excessive motor preparation for compulsive rituals; cathodal tDCS target.",
        "Impaired top-down regulatory control: DLPFC hypoactivity reduces capacity for volitional response inhibition; anodal tDCS target.",
        "Serotonergic deficit: reduced 5-HT tone impairs OFC-caudate inhibitory balance; addressed by SSRI + taVNS serotonergic augmentation.",
    ],
    std_treatment=[
        "First-line: SSRIs at high doses (fluoxetine, fluvoxamine, paroxetine, sertraline, escitalopram) + ERP psychotherapy",
        "Augmentation: antipsychotics (risperidone, aripiprazole) for partial responders",
        "Intensive ERP: residential or intensive outpatient programs",
        "Advanced: rTMS (FDA-cleared for OCD — dTMS OFC/ACC), DBS (anterior limb internal capsule/ventral striatum)",
        "Emerging: glutamatergic agents (NAC, riluzole), ketamine, psilocybin-assisted therapy",
    ],
    symptoms=[
        ["Contamination Obsessions", "Fear of contamination, germs, disease", "38%", "Abramowitz 2009"],
        ["Washing Compulsions", "Hand washing, cleaning rituals", "38%", "Rasmussen 1991"],
        ["Harm Obsessions", "Fear of harming self/others, moral guilt", "28%", "Abramowitz 2009"],
        ["Checking Compulsions", "Door, stove, lock checking rituals", "28%", "Rasmussen 1991"],
        ["Symmetry Obsessions", "Need for order, exactness, symmetry", "20%", "Leckman 1997"],
        ["Ordering/Arranging", "Arranging objects precisely until 'just right'", "20%", "Miguel 2000"],
        ["Intrusive Thoughts", "Taboo, sexual, religious, violent thoughts", "20%", "Purdon 1999"],
        ["Neutralizing Compulsions", "Mental rituals, prayers, counting", "20%", "Clark 2004"],
        ["Hoarding (OCD-type)", "Pathological saving when ego-dystonic", "14%", "Frost 2010"],
        ["Insight Impairment", "Poor/absent insight in severe cases", "15%", "Kozak 2000"],
    ],
    brain_regions=[
        ["Orbitofrontal Cortex (OFC)", "Error signal generation, contamination/harm appraisal", "TPS, tDCS cathodal indirect", "Saxena 2001"],
        ["Caudate Nucleus", "CSTC relay; hyperactive in OCD", "TPS indirect", "Rauch 1994"],
        ["Anterior Cingulate Cortex (ACC)", "Conflict monitoring, uncertainty intolerance", "TPS", "Carter 2000"],
        ["Thalamus", "CSTC gating; hyperactive relay in OCD", "CES, TPS indirect", "Rosenberg 1997"],
        ["DLPFC", "Response inhibition, top-down OFC regulation", "tDCS anodal", "Chamberlain 2008"],
        ["Supplementary Motor Area (SMA)", "Motor preparation for compulsions; pre-SMA response inhibition", "tDCS cathodal", "Nachev 2008"],
        ["Insula", "Disgust processing, body-based threat signals", "TPS", "Husted 2006"],
        ["Subthalamic Nucleus", "Impulsivity regulation; DBS target in refractory OCD", "None direct NIBS", "Mallet 2008"],
    ],
    brainstem=[
        ["Raphe Nuclei", "Serotonergic output; reduced 5-HT drives CSTC disinhibition", "taVNS indirect", "Saxena 2001"],
        ["Locus Coeruleus", "Noradrenergic anxiety component; hyperarousal in OCD", "taVNS, CES", "Southwick 1997"],
        ["Nucleus Tractus Solitarius", "Vagal input; relays to raphe and LC", "taVNS direct", "Porges 2007"],
        ["Substantia Nigra", "Dopaminergic-CSTC interaction; striatal modulation", "None direct", "Gottesman 2002"],
        ["Parabrachial Nucleus", "Disgust and interoceptive relay to insula", "None direct", "Husted 2006"],
    ],
    phenotypes=[
        ["Contamination/Washing", "Contamination obsessions + washing compulsions; disgust-driven OFC-insula circuit", "Skin damage from washing, anxiety", "tDCS SMA cathodal + TPS OFC + taVNS"],
        ["Harm/Checking", "Harm obsessions + checking compulsions; dACC hyperactivity", "Checking rituals, doubt, guilt", "tDCS SMA cathodal + TPS ACC + tDCS DLPFC"],
        ["Symmetry/Ordering", "Symmetry obsessions + ordering compulsions; sensorimotor CSTC involvement", "Just-right phenomenology, motor rituals", "tDCS SMA cathodal + TPS + tDCS DLPFC"],
        ["Intrusive Thought Dominant", "Taboo/moral/sexual/violent intrusive thoughts; ACC-DLPFC dysfunction", "Moral guilt, mental neutralizing", "tDCS DLPFC anodal + TPS ACC + taVNS"],
        ["Treatment-Refractory OCD", "≥3 SSRI failures + ERP failure; severe CSTC pathology", "All symptom dimensions; severe impairment", "Full protocol: tDCS SMA + DLPFC + TPS OFC/ACC + taVNS + CES"],
        ["OCD + Tic Comorbidity", "OCD + Tourette/chronic tics; SMA-striatal circuit predominance", "Tic + compulsion interaction", "tDCS SMA cathodal primary + TPS SMA + specialized"],
    ],
    symptom_map=[
        ["Contamination obsessions", "OFC/Insula", "TPS OFC + tDCS SMA cathodal", "Saxena 2001, Rauch 1994"],
        ["Washing compulsions", "SMA/OFC", "tDCS SMA cathodal", "Nachev 2008"],
        ["Checking compulsions", "ACC/SMA", "tDCS SMA cathodal + TPS ACC", "Carter 2000"],
        ["Harm obsessions", "ACC/OFC", "TPS ACC/OFC + tDCS DLPFC", "Abramowitz 2009"],
        ["Symmetry/ordering", "SMA/Sensorimotor", "tDCS SMA cathodal + TPS", "Leckman 1997"],
        ["Intrusive thoughts", "DLPFC/ACC", "tDCS DLPFC anodal + TPS ACC", "Purdon 1999"],
        ["Anxiety/arousal", "Amygdala/Thalamus", "CES + taVNS", "Lande 2018"],
        ["Response inhibition failure", "DLPFC/pre-SMA", "tDCS DLPFC anodal + SMA cathodal", "Chamberlain 2008"],
        ["Serotonergic deficit", "Raphe/CSTC", "taVNS serotonergic augmentation", "Vonck 2014"],
    ],
    montage=[
        ["Contamination/Washing", "Cathodal SMA (Cz area, 1.5mA, 20min) + Anodal DLPFC", "OFC (250 pulses)", "taVNS + ERP concurrent"],
        ["Harm/Checking", "Cathodal SMA (1.5mA, 20min) + Anodal DLPFC (F3)", "ACC (250 pulses)", "taVNS + CES + ERP"],
        ["Symmetry/Ordering", "Cathodal SMA (Cz, 1.5mA, 20min)", "SMA + OFC (300 pulses)", "ERP concurrent; CES adjunct"],
        ["Intrusive Thought", "Anodal DLPFC (F3, 2mA, 20min)", "ACC (250 pulses)", "taVNS + ERP essential"],
        ["Refractory OCD", "Cathodal SMA + Anodal DLPFC bilateral", "OFC + ACC (400 pulses)", "All 4 modalities + intensive ERP"],
        ["OCD + Tics", "Cathodal SMA (Cz, 1.5mA, 20min)", "SMA (200 pulses)", "Specialized; tic management concurrent"],
        ["Maintenance Phase", "Anodal DLPFC (F3, 1.5mA, 20min)", "None", "CES 3x/week; taVNS daily"],
        ["Elderly Adjusted", "Anodal DLPFC (F3, 1.5mA, 15min)", "OFC (200 pulses)", "CES primary; taVNS standard"],
        ["With MDD Comorbidity", "Anodal left DLPFC (F3, 2mA, 20min)", "ACC (250 pulses)", "taVNS + CES; SSRI maintained"],
        ["Sham Protocol", "F3 anodal (30s ramp, 0mA, 20min)", "None", "Sham ERP control condition"],
    ],
    tdcs_protocols=[
        ["OC-tDCS-01", "SMA Cathodal (Compulsion Inhibition)", "Fp1/Fp2", "Cz (SMA)", "1.5mA, 20min, 10 sessions", "Narayanan 2016"],
        ["OC-tDCS-02", "DLPFC Anodal Left (Top-Down Regulation)", "F3", "F4", "2mA, 20min, 10 sessions", "Bation 2016"],
        ["OC-tDCS-03", "Combined SMA Cathodal + DLPFC Anodal", "F3 anodal; Cz cathodal", "F4; Fp2", "1.5–2mA, sequential, 10 sessions", "Expert consensus 2023"],
        ["OC-tDCS-04", "OFC Cathodal (Refractory)", "Fp1 cathodal", "Oz", "1mA, 20min, 10 sessions", "Bation 2016"],
        ["OC-tDCS-05", "Maintenance", "F3 anodal", "F4", "1.5mA, 20min, 2x/week", "Bikson 2016"],
        ["OC-tDCS-06", "Pre-ERP Augmentation", "F3 anodal", "F4", "2mA, 20min before ERP", "Narayanan 2016"],
        ["OC-tDCS-07", "Elderly Adjusted", "F3 anodal", "F4", "1.5mA, 15min, 10 sessions", "Lefaucheur 2016"],
        ["OC-tDCS-08", "Sham", "F3", "F4", "30s active, 0mA, 20min", "Bation 2016"],
    ],
    plato_protocols=[
        ["OC-PLATO-01", "SMA Cathodal", "Cz/Fpz", "SMA", "Cz", "1.5mA", "N/A", "Cathodal 20min"],
        ["OC-PLATO-02", "DLPFC Anodal", "F3/F4", "Left DLPFC", "F3", "2.0mA", "N/A", "Continuous 20min"],
        ["OC-PLATO-03", "Combined SMA+DLPFC", "F3; Cz", "DLPFC + SMA", "F3; Cz", "2.0; 1.5mA", "N/A", "Sequential"],
        ["OC-PLATO-04", "HD-tDCS DLPFC", "F3 center", "4-electrode ring", "F3", "1.0mA", "N/A", "HD 20min"],
        ["OC-PLATO-05", "Maintenance", "F3", "DLPFC", "F3", "1.5mA", "N/A", "2x/week"],
        ["OC-PLATO-06", "Beta tACS (SMA)", "Cz", "SMA", "Cz", "1.0mA", "20Hz", "tACS 20min"],
        ["OC-PLATO-07", "Elderly", "F3", "DLPFC", "F3", "1.5mA", "N/A", "15min"],
        ["OC-PLATO-08", "Sham", "F3", "DLPFC", "F3", "0mA", "N/A", "30s ramp"],
    ],
    tps_protocols=[
        ["OC-TPS-01", "OFC Error Signal Reduction", "OFC (BA11/47)", "250 pulses, 0.2Hz, 0.2mJ/mm²", "3 sessions/week", "Saxena 2001"],
        ["OC-TPS-02", "ACC Conflict Monitoring", "dACC (BA24)", "250 pulses, 0.2Hz", "3 sessions/week", "Carter 2000"],
        ["OC-TPS-03", "SMA Compulsion Inhibition", "Pre-SMA (BA6)", "200 pulses, 0.2Hz", "3 sessions/week", "Nachev 2008"],
        ["OC-TPS-04", "Insula Disgust Processing", "Posterior Insula", "200 pulses, 0.2Hz", "2 sessions/week", "Husted 2006"],
        ["OC-TPS-05", "Full Protocol (Refractory)", "OFC + ACC + SMA sequential", "400 pulses total", "5 sessions/week x2 weeks", "Expert consensus 2024"],
    ],
    ces_role=[
        ["Anxiety Augmentation", "Reduces obsessional anxiety and arousal; enhances ERP tolerance", "Daily 60min; before ERP sessions"],
        ["SSRI Augmentation", "Thalamic modulation may augment SSRI response", "Daily 60min concurrent with pharmacotherapy"],
        ["Sleep Disruption", "Addresses OCD-related sleep problems", "Nightly 60min if sleep-onset difficulty"],
        ["Maintenance", "Sustain anxiety reduction between sessions", "3x/week; patient self-administered"],
    ],
    tavns_role="taVNS (tragus, 25Hz, 200µs, 0.5mA, 30min) augments serotonergic tone via NTS → raphe nuclei pathway, complementing SSRI pharmacotherapy. Also reduces hyperarousal and anxiety comorbidity. Administered before NIBS and ERP sessions. Evidence for serotonergic augmentation positions taVNS as a pharmacological enhancer for SSRI-partial responders (Vonck 2014, Straube 2015).",
    combinations=[
        ("Contamination/Washing", [
            ["tDCS SMA cathodal + TPS OFC + taVNS", "Compulsion inhibition + error signal reduction + serotonergic augmentation", "taVNS → TPS → tDCS, before ERP", "Contamination obsessions with washing compulsions"],
            ["tDCS SMA cathodal + CES", "Motor inhibition + anxiolytic adjunct", "tDCS then CES post-session", "Washing compulsions with high anxiety"],
        ]),
        ("Harm/Checking", [
            ["tDCS SMA cathodal + tDCS DLPFC anodal + TPS ACC", "Compulsion inhibition + top-down control + conflict monitoring", "TPS → tDCS SMA → tDCS DLPFC, before ERP", "Checking compulsions, harm obsessions"],
        ]),
        ("Intrusive Thought Dominant", [
            ["tDCS DLPFC + TPS ACC + taVNS", "Cognitive control + conflict + serotonergic", "taVNS → TPS → tDCS, before ERP", "Moral/sexual/violent intrusive thoughts"],
        ]),
        ("Refractory OCD", [
            ["tDCS SMA cathodal + tDCS DLPFC + TPS OFC/ACC + taVNS + CES", "Full circuit attack — all nodes", "taVNS → TPS → tDCS; CES nightly", "≥3 SSRI failures, ERP failure"],
        ]),
        ("Symmetry/Ordering", [
            ["tDCS SMA cathodal + TPS OFC/SMA", "Motor + sensorimotor CSTC inhibition", "TPS → tDCS, before ERP", "Just-right phenomenology, ordering rituals"],
        ]),
        ("OCD + Tics", [
            ["tDCS SMA cathodal + TPS SMA", "Convergent SMA inhibition for tic-compulsion complex", "TPS → tDCS; specialized program", "Tourette + OCD comorbidity"],
        ]),
    ],
    combination_summary=[
        ["Contamination/Washing", "tDCS SMA cathodal + TPS OFC + taVNS", "Compulsion + error signal + serotonergic", "taVNS → TPS → tDCS + ERP", "Contamination/washing", "IIb"],
        ["Harm/Checking", "tDCS SMA + DLPFC + TPS ACC", "Motor + top-down + conflict", "TPS → tDCS × 2 + ERP", "Harm/checking", "IIb"],
        ["Intrusive Thought", "tDCS DLPFC + TPS ACC + taVNS", "Cognitive + conflict + serotonergic", "taVNS → TPS → tDCS + ERP", "Intrusive thoughts", "IIb"],
        ["Refractory OCD", "All 4 modalities", "Full CSTC circuit normalization", "taVNS → TPS → tDCS + CES", "Refractory OCD", "IIb"],
        ["Symmetry/Ordering", "tDCS SMA cathodal + TPS OFC/SMA", "SMA inhibition + sensorimotor", "TPS → tDCS + ERP", "Ordering compulsions", "IIb"],
        ["OCD + Tics", "tDCS SMA cathodal + TPS SMA", "Convergent SMA inhibition", "TPS → tDCS; specialized", "Tic-OCD comorbid", "IIb"],
    ],
    outcomes=[
        ["Y-BOCS Total Score", "OCD severity (obsessions + compulsions)", "Baseline, 4wk, 8wk", "≥35% reduction (response); ≤7 (remission)"],
        ["Y-BOCS Obsession Subscale", "Obsession severity", "Baseline, 4wk, 8wk", "≥35% reduction"],
        ["Y-BOCS Compulsion Subscale", "Compulsion severity", "Baseline, 4wk, 8wk", "≥35% reduction"],
        ["CGI-Severity (CGI-S)", "Clinical global severity", "Baseline, 4wk, 8wk", "Reduction ≥2 points (much improved)"],
        ["PHQ-9", "Depression comorbidity", "Baseline, 4wk, 8wk", "≥5-point reduction"],
        ["GAD-7", "Anxiety comorbidity", "Baseline, 4wk, 8wk", "≥5-point reduction"],
        ["OCD-Related Disability (WHODAS 2.0)", "Functional impairment", "Baseline, 8wk", "≥20% improvement"],
        ["ERP Homework Completion", "Treatment engagement", "Weekly", "≥80% completion rate"],
        ["Patient Global Impression of Change", "Overall response", "4wk, 8wk", "≥5/7 (much improved)"],
    ],
    outcomes_abbrev=[
        "Y-BOCS: Yale-Brown Obsessive Compulsive Scale",
        "CGI-S: Clinical Global Impressions - Severity",
        "PHQ-9: Patient Health Questionnaire-9",
        "GAD-7: Generalized Anxiety Disorder 7",
        "WHODAS: World Health Organization Disability Assessment Schedule",
        "ERP: Exposure and Response Prevention",
        "CSTC: Cortico-Striato-Thalamo-Cortical",
        "OFC: Orbitofrontal Cortex",
        "SMA: Supplementary Motor Area",
        "DLPFC: Dorsolateral Prefrontal Cortex",
    ],
)
print("Chronic Pain + PTSD + OCD appended OK")
'''

with open(OUTFILE, "a", encoding="utf-8") as f:
    f.write(BLOCK)

print("Chronic Pain + PTSD + OCD appended OK")
