# DEPRECATED: This script is superseded by the canonical generation pipeline.
# Use instead: GenerationService.generate(condition="...", tier="...", doc_type="...")
# Or CLI: PYTHONPATH=src python -m sozo_generator.cli.main build condition --condition <slug> --tier <tier> --doc-type <type>
# See docs/MIGRATION_PLAN.md for details.

"""Append MS, ASD, Long COVID condition data to generate_fellow_protocols.py"""
import os
OUTFILE = os.path.join(os.path.dirname(__file__), "generate_fellow_protocols.py")

BLOCK = '''
# ---------------------------------------------------------------------------
# CONDITION: MULTIPLE SCLEROSIS
# ---------------------------------------------------------------------------
CONDITIONS["ms"] = dict(
    name="Multiple Sclerosis",
    icd10="G35",
    doc_num="SPG-MS-001",
    tps_status="Investigational",
    tdcs_class="Class IIb",
    tps_class="Investigational",
    tavns_class="Class IIb",
    ces_class="Class IIb",
    inclusion=[
        "Confirmed MS diagnosis per McDonald 2017 criteria (RRMS, SPMS, or PPMS)",
        "EDSS score 2.0–7.0 at baseline",
        "Stable disease-modifying therapy (DMT) for ≥3 months or no DMT planned",
        "Age 18–70; capable of informed consent",
        "Symptom burden including fatigue (MFIS ≥38), cognitive impairment (SDMT <55), spasticity, or mood symptoms",
        "No relapse within 3 months of enrollment",
    ],
    exclusion=[
        "Metallic implants in head/neck or implanted neurostimulator",
        "Active relapse or corticosteroid treatment within 3 months",
        "Severe cognitive impairment precluding consent (MMSE <18)",
        "Pregnancy",
        "History of seizures not controlled with medication",
        "Rapidly progressive disease course (EDSS change >1.0 in past 6 months)",
        "Active cancer or severe systemic illness",
    ],
    discussion=[
        "MS-related neurological dysfunction arises from demyelination and axonal loss disrupting large-scale brain network connectivity.",
        "Fatigue in MS involves thalamo-cortical circuit dysfunction, reduced cortico-spinal efficiency, and hypothalamic-pituitary-adrenal axis dysregulation.",
        "Cognitive impairment (particularly processing speed and working memory) correlates with DMN-CEN disconnection and thalamic atrophy.",
        "Spasticity results from corticospinal tract demyelination reducing inhibitory tone over spinal motor circuits.",
        "tDCS targeting M1 (anodal) improves motor function, reduces fatigue, and temporarily enhances corticospinal conduction efficiency.",
        "tDCS over DLPFC augments cognitive processing speed and working memory in MS.",
        "taVNS exerts anti-inflammatory effects via the vagal cholinergic anti-inflammatory pathway, potentially modulating neuroinflammation.",
        "CES addresses MS-related insomnia, fatigue, and mood symptoms through thalamic and brainstem modulation.",
    ],
    overview=[
        "Multiple Sclerosis (MS) is a chronic autoimmune demyelinating disease of the central nervous system affecting approximately 2.8 million people worldwide. Characterized by inflammatory demyelination and progressive axonal loss, MS produces diverse neurological symptoms including fatigue, cognitive impairment, spasticity, pain, mood disorders, and disability accumulation across four disease courses (RRMS, SPMS, PPMS, CIS).",
        "The SOZO NIBS protocol addresses MS symptom burden rather than disease modification. By targeting the neurophysiological consequences of demyelination — corticospinal inefficiency, cognitive network dysfunction, central sensitization, and fatigue circuits — NIBS offers symptomatic benefit complementary to disease-modifying therapies.",
        "Five clinical phenotypes guide protocol selection: fatigue-dominant, cognitive-dominant, spasticity-dominant, pain-dominant, and mood/depression-dominant. Each phenotype receives a tailored NIBS combination targeting the most impaired neural network.",
    ],
    pathophysiology=[
        "Demyelination and axonal loss: focal white matter lesions disrupt myelinated fiber conduction velocity and axonal integrity; cortical and deep gray matter atrophy contributes to network dysfunction.",
        "Corticospinal tract impairment: demyelination of descending motor pathways reduces cortical drive, increases spasticity, and impairs voluntary motor control.",
        "Fatigue circuit dysfunction: thalamocortical and cortico-striatal-thalamic circuits show hyperactivation as compensatory burden; fatigue reflects neural inefficiency.",
        "Cognitive impairment: processing speed loss correlates with corpus callosum integrity and thalamic volume; working memory deficit involves DLPFC-CEN disruption.",
        "Neuroinflammation: CNS-infiltrating T-cells, microglia activation, and demyelinating plaques in periventricular, cortical, and brainstem regions.",
        "Central sensitization and pain: MS-related central sensitization amplifies nociception through thalamic and cortical pain network dysregulation.",
    ],
    std_treatment=[
        "Disease-modifying therapies: interferons, glatiramer, natalizumab, ocrelizumab, siponimod, ozanimod (by disease course)",
        "Symptom management: baclofen/tizanidine (spasticity), modafinil/amantadine (fatigue), fampridine (walking speed)",
        "Cognitive rehabilitation: computerized cognitive training, compensatory strategy training",
        "Physical/occupational therapy: progressive resistance training, aquatic therapy, assistive devices",
        "Psychological support: CBT for depression and adjustment, MS-specific mindfulness",
    ],
    symptoms=[
        ["Fatigue", "Overwhelming fatigue disproportionate to activity (Uhthoff variant with heat)", "80%", "Krupp 1988"],
        ["Cognitive Impairment", "Processing speed, working memory, episodic memory deficits", "65%", "Chiaravalloti 2008"],
        ["Spasticity", "Velocity-dependent resistance to passive movement; cramps", "60%", "Rizzo 2004"],
        ["Pain", "Central neuropathic pain, trigeminal neuralgia, Lhermitte sign", "55%", "Foley 2013"],
        ["Depression", "Comorbid MDD; partly biologically driven by neuroinflammation", "50%", "Feinstein 2011"],
        ["Walking/Balance Impairment", "Reduced gait speed, balance deficits, fall risk", "70%", "Kalron 2016"],
        ["Bladder Dysfunction", "Urgency, frequency, retention", "75%", "Fowler 2009"],
        ["Visual Disturbance", "Optic neuritis, diplopia, nystagmus", "55%", "Petzold 2018"],
        ["Tremor", "Cerebellar intention tremor", "40%", "Koch 2007"],
        ["Sleep Disturbance", "Insomnia, restless legs, sleep fragmentation", "50%", "Braley 2014"],
    ],
    brain_regions=[
        ["Primary Motor Cortex (M1)", "Corticospinal drive; compensatory hyperactivation in MS", "tDCS anodal M1", "Fregni 2006"],
        ["DLPFC", "Cognitive processing speed, working memory, fatigue regulation", "tDCS anodal", "Mattioli 2010"],
        ["Cerebellum", "Tremor, ataxia, coordination; direct NIBS difficult", "TPS indirect", "Koch 2007"],
        ["Thalamus", "Fatigue relay, sensory gating, thalamocortical dysrhythmia", "CES", "Filippi 2013"],
        ["ACC", "Fatigue perception, effort-cost computation, cognitive-motor integration", "TPS", "Yaldizli 2011"],
        ["Supplementary Motor Area", "Motor sequence, fatigue-motor interaction", "tDCS", "Leavitt 2014"],
        ["Posterior Parietal Cortex", "Visuospatial, somatosensory integration disrupted by MS", "tDCS, TPS", "Chiaravalloti 2008"],
        ["Hippocampus", "Episodic memory; directly affected by MS pathology", "taVNS", "Sicotte 2008"],
    ],
    brainstem=[
        ["Pons/Brainstem", "Frequent MS lesion location; affects cranial nerves, gait, dysarthria", "taVNS indirect", "Filippi 2002"],
        ["Locus Coeruleus", "Fatigue and arousal regulation; noradrenergic impairment in MS", "taVNS, CES", "Feinstein 2011"],
        ["Nucleus Tractus Solitarius", "Vagal input; anti-inflammatory relay", "taVNS direct", "Tracey 2002"],
        ["Raphe Nuclei", "Serotonergic tone; depression in MS partly serotonergic", "taVNS", "Feinstein 2011"],
        ["Vestibular Nuclei", "Balance and gaze stabilization; affected by MS brainstem lesions", "None direct", "Frohman 2005"],
    ],
    phenotypes=[
        ["Fatigue-Dominant", "Severe MS fatigue (MFIS ≥38); thalamocortical and cortico-striatal inefficiency", "Fatigue limiting daily function; activity avoidance", "tDCS M1 + DLPFC + CES"],
        ["Cognitive-Dominant", "Processing speed, working memory, attention impairment (SDMT <45)", "Cognitive fog, occupational/social impairment", "tDCS DLPFC + TPS + taVNS"],
        ["Spasticity-Dominant", "Moderate-severe spasticity (MAS 2–3); corticospinal demyelination", "Cramps, gait limitation, pain from spasticity", "tDCS M1 anodal + TPS M1/SMA"],
        ["Pain-Dominant", "Central neuropathic pain ≥4/10 NRS; trigeminal neuralgia; Lhermitte", "Burning, electric, shooting pain; sleep disruption", "tDCS M1 + TPS + CES"],
        ["Mood/Depression-Dominant", "MS-related depression (PHQ-9 ≥10); partly neuroinflammatory", "Low mood, fatigue-depression interaction, reduced adherence", "tDCS DLPFC + taVNS + CES"],
    ],
    symptom_map=[
        ["MS Fatigue", "Thalamus/M1/DLPFC", "tDCS M1 + DLPFC + CES", "Fregni 2006, Lande 2018"],
        ["Cognitive impairment", "DLPFC/CEN/Thalamus", "tDCS DLPFC anodal", "Mattioli 2010"],
        ["Spasticity", "M1/Corticospinal", "tDCS M1 anodal", "Lefaucheur 2016"],
        ["Central pain", "Thalamus/M1/ACC", "tDCS M1 + CES", "Fregni 2006"],
        ["Depression", "DLPFC/Limbic", "tDCS DLPFC + taVNS", "Brunoni 2013"],
        ["Walking impairment", "M1/SMA", "tDCS M1 + TPS", "Otal 2016"],
        ["Sleep disruption", "Thalamus/LC", "CES Alpha-Stim", "Braley 2014"],
        ["Neuroinflammation", "Systemic/CNS", "taVNS cholinergic anti-inflammatory", "Tracey 2002"],
        ["Tremor", "Cerebellum/Thalamus", "TPS cerebellar indirect", "Koch 2007"],
    ],
    montage=[
        ["Fatigue-Dominant", "Anodal M1 (C3/C4, 2mA, 20min) + Anodal DLPFC (F3)", "None initial", "CES nightly; taVNS 2x daily"],
        ["Cognitive-Dominant", "Anodal DLPFC (F3, 2mA, 20min)", "DLPFC (250 pulses)", "taVNS before sessions; CES adjunct"],
        ["Spasticity-Dominant", "Anodal M1 (C3/C4, 2mA, 20min)", "M1/SMA (300 pulses)", "Baclofen maintained; physio concurrent"],
        ["Pain-Dominant", "Anodal M1 (C3, 2mA, 20min)", "ACC (250 pulses)", "CES nightly; taVNS 2x daily"],
        ["Mood/Depression", "Anodal DLPFC left (F3, 2mA, 20min)", "None initial", "taVNS + CES nightly; DMT maintained"],
        ["RRMS Active Symptoms", "Anodal DLPFC (F3, 2mA) + M1 (C3, 2mA)", "DLPFC + M1 (300 pulses)", "taVNS + CES; DMT maintained"],
        ["SPMS/PPMS Progressive", "Anodal M1 (C3, 1.5mA, 20min)", "M1 (200 pulses)", "CES primary; taVNS 2x daily"],
        ["Elderly/High EDSS (5–7)", "Anodal M1 (C3, 1mA, 15min)", "TPS low (150 pulses)", "CES + taVNS; adapted physio"],
        ["Maintenance Phase", "Anodal DLPFC (F3, 1.5mA, 20min)", "None", "CES 3x/week; taVNS daily home"],
        ["Sham Protocol", "F3 anodal (30s ramp, 0mA, 20min)", "None", "Sham control condition"],
    ],
    tdcs_protocols=[
        ["MS-tDCS-01", "M1 Anodal (Fatigue/Spasticity/Motor)", "C3/C4 contralateral", "Fp2", "2mA, 20min, 10 sessions", "Fregni 2006"],
        ["MS-tDCS-02", "DLPFC Anodal Left (Cognitive/Depression)", "F3", "F4", "2mA, 20min, 10 sessions", "Mattioli 2010"],
        ["MS-tDCS-03", "Combined M1 + DLPFC", "C3 + F3 anodal sequential", "Fp2 + F4", "2mA each, 20min, 15 sessions", "Otal 2016"],
        ["MS-tDCS-04", "Bifrontal (Fatigue/Mood)", "F3 anodal", "F4 cathodal", "2mA, 20min, 10 sessions", "Brunoni 2013"],
        ["MS-tDCS-05", "M1 Anodal (PPMS/SPMS Progressive)", "C3/C4", "Fp2", "1.5mA, 20min, 10 sessions", "Lefaucheur 2016"],
        ["MS-tDCS-06", "Maintenance", "F3 anodal", "F4", "1.5mA, 20min, 2x/week", "Bikson 2016"],
        ["MS-tDCS-07", "Elderly/High EDSS Adjusted", "C3 anodal", "Fp2", "1mA, 15min, 10 sessions", "Lefaucheur 2016"],
        ["MS-tDCS-08", "Sham", "F3 anodal", "F4", "30s ramp, 0mA, 20min", "Mattioli 2010"],
    ],
    plato_protocols=[
        ["MS-PLATO-01", "M1 Anodal", "C3/Fp2", "M1 contralateral", "C3", "2.0mA", "N/A", "Continuous 20min"],
        ["MS-PLATO-02", "DLPFC Anodal", "F3/F4", "Left DLPFC", "F3", "2.0mA", "N/A", "Continuous 20min"],
        ["MS-PLATO-03", "Combined M1+DLPFC", "C3; F3", "M1 + DLPFC", "C3; F3", "2.0mA each", "N/A", "Sequential"],
        ["MS-PLATO-04", "HD-tDCS M1", "C3 center", "4-electrode ring", "C3", "1.0mA", "N/A", "HD 20min"],
        ["MS-PLATO-05", "Maintenance", "F3", "DLPFC", "F3", "1.5mA", "N/A", "2x/week"],
        ["MS-PLATO-06", "Gamma tACS Fatigue", "C3", "M1", "C3", "1.5mA", "40Hz", "tACS 20min"],
        ["MS-PLATO-07", "Elderly/High EDSS", "C3", "M1", "C3", "1.0mA", "N/A", "15min"],
        ["MS-PLATO-08", "Sham", "F3", "DLPFC", "F3", "0mA", "N/A", "30s ramp"],
    ],
    tps_protocols=[
        ["MS-TPS-01", "M1 Motor Facilitation", "M1 bilateral or contralateral", "300 pulses, 0.25Hz, 0.2mJ/mm²", "3 sessions/week", "Otal 2016"],
        ["MS-TPS-02", "DLPFC Cognitive", "DLPFC (BA46)", "250 pulses, 0.2Hz", "3 sessions/week", "Mattioli 2010"],
        ["MS-TPS-03", "ACC Fatigue-Cognitive", "ACC (BA24/32)", "200 pulses, 0.2Hz", "2 sessions/week", "Yaldizli 2011"],
        ["MS-TPS-04", "SMA Motor Sequence", "SMA (BA6)", "200 pulses, 0.2Hz", "2 sessions/week", "Leavitt 2014"],
        ["MS-TPS-05", "Full Protocol", "M1 + DLPFC + ACC sequential", "450 pulses total", "5 sessions/week x2 weeks", "Expert consensus 2024"],
    ],
    ces_role=[
        ["MS Fatigue", "Reduces fatigue severity via thalamic-reticular network modulation", "Daily 60min; morning or pre-activity"],
        ["Sleep Disruption", "Improves sleep quality and reduces nocturnal awakening", "Nightly 60min"],
        ["Depression Comorbidity", "Adjunct anxiolytic-antidepressant effect in MS depression", "Daily 60min concurrent with pharmacotherapy"],
        ["Maintenance", "Long-term fatigue and mood maintenance", "3–5x/week; patient self-administered home device"],
    ],
    tavns_role="taVNS (tragus, 25Hz, 200µs, 0.5mA, 30min) activates the cholinergic anti-inflammatory pathway via NTS → vagal efferents → spleen, potentially modulating CNS neuroinflammation. Also addresses MS fatigue and depression through LC-noradrenergic and raphe-serotonergic activation. Administered before NIBS sessions and as home device (2x daily). While disease modification is not expected, symptomatic anti-inflammatory benefits are documented in autoimmune conditions (Tracey 2002, Bonaz 2016).",
    combinations=[
        ("Fatigue-Dominant", [
            ["tDCS M1 + tDCS DLPFC + CES", "Motor efficiency + cognitive fatigue + thalamic dysrhythmia", "tDCS sequential → CES nightly", "MS fatigue affecting motor and cognitive function"],
            ["tDCS DLPFC + taVNS + CES", "Cognitive fatigue + anti-inflammatory + thalamic", "taVNS before tDCS; CES nightly", "Cognitive-fatigue dominant with neuroinflammation concern"],
        ]),
        ("Cognitive-Dominant", [
            ["tDCS DLPFC + TPS DLPFC + taVNS", "Convergent prefrontal enhancement + serotonergic/noradrenergic", "taVNS → TPS → tDCS", "Processing speed and working memory deficits"],
        ]),
        ("Spasticity-Dominant", [
            ["tDCS M1 + TPS M1/SMA", "Convergent motor cortex facilitation for spasticity", "TPS → tDCS immediately after", "Spasticity with motor impairment"],
        ]),
        ("Pain-Dominant", [
            ["tDCS M1 + TPS ACC + CES", "Pain threshold elevation + affective pain + thalamic", "TPS → tDCS; CES nightly", "Central neuropathic pain in MS"],
        ]),
        ("Mood/Depression", [
            ["tDCS DLPFC + taVNS + CES", "Antidepressant + vagal-serotonergic + anxiolytic", "taVNS before tDCS; CES nightly", "MS-related depression"],
        ]),
        ("PPMS/SPMS Progressive", [
            ["tDCS M1 + CES + taVNS", "Motor maintenance + fatigue + anti-inflammatory", "tDCS + taVNS daytime; CES nightly", "Progressive MS — symptom maintenance focus"],
        ]),
    ],
    combination_summary=[
        ["Fatigue-Dominant", "tDCS M1 + DLPFC + CES", "Motor + cognitive fatigue + thalamic", "tDCS sequential → CES nightly", "MS fatigue", "IIb"],
        ["Cognitive-Dominant", "tDCS DLPFC + TPS + taVNS", "Prefrontal + serotonergic", "taVNS → TPS → tDCS", "Processing speed deficit", "IIb"],
        ["Spasticity-Dominant", "tDCS M1 + TPS M1/SMA", "Convergent motor facilitation", "TPS → tDCS", "Spasticity/motor", "IIb"],
        ["Pain-Dominant", "tDCS M1 + TPS ACC + CES", "Pain + affective + thalamic", "TPS → tDCS + CES", "Central neuropathic pain", "IIb"],
        ["Mood/Depression", "tDCS DLPFC + taVNS + CES", "Antidepressant triple", "taVNS → tDCS + CES", "MS depression", "IIb"],
        ["Progressive MS", "tDCS M1 + CES + taVNS", "Motor + fatigue + anti-inflammatory", "tDCS + taVNS + CES nightly", "SPMS/PPMS", "IIb"],
    ],
    outcomes=[
        ["Modified Fatigue Impact Scale (MFIS)", "MS-specific fatigue", "Baseline, 4wk, 8wk", "≥5-point reduction (MCID)"],
        ["Symbol Digit Modalities Test (SDMT)", "Processing speed (cognitive primary)", "Baseline, 4wk, 8wk", "≥4-point improvement (MCID)"],
        ["Modified Ashworth Scale (MAS)", "Spasticity", "Baseline, 4wk, 8wk", "≥1-point reduction"],
        ["Timed 25-Foot Walk (T25FW)", "Walking speed", "Baseline, 4wk, 8wk", "≥20% improvement"],
        ["NRS Pain Score", "Central pain intensity", "Weekly", "≥30% reduction"],
        ["PHQ-9", "Depression", "Baseline, 4wk, 8wk", "≥5-point reduction"],
        ["Pittsburgh Sleep Quality Index (PSQI)", "Sleep quality", "Baseline, 4wk, 8wk", "≥3-point improvement"],
        ["9-Hole Peg Test (9HPT)", "Upper limb dexterity", "Baseline, 4wk, 8wk", "≥20% improvement in dominant hand"],
        ["Patient Global Impression of Change", "Overall response", "4wk, 8wk", "≥5/7 (much improved)"],
    ],
    outcomes_abbrev=[
        "MFIS: Modified Fatigue Impact Scale",
        "SDMT: Symbol Digit Modalities Test",
        "MAS: Modified Ashworth Scale",
        "T25FW: Timed 25-Foot Walk",
        "9HPT: 9-Hole Peg Test",
        "EDSS: Expanded Disability Status Scale",
        "PSQI: Pittsburgh Sleep Quality Index",
        "PHQ-9: Patient Health Questionnaire-9",
        "RRMS/SPMS/PPMS: Relapsing-Remitting/Secondary Progressive/Primary Progressive MS",
        "DMT: Disease-Modifying Therapy",
    ],
)

# ---------------------------------------------------------------------------
# CONDITION: AUTISM SPECTRUM DISORDER (ASD)
# ---------------------------------------------------------------------------
CONDITIONS["asd"] = dict(
    name="Autism Spectrum Disorder",
    icd10="F84.0",
    doc_num="SPG-AU-001",
    tps_status="Investigational",
    tdcs_class="Class IIb",
    tps_class="Investigational",
    tavns_class="Class IIb",
    ces_class="Class IIb",
    inclusion=[
        "DSM-5 ASD diagnosis confirmed by ADOS-2 and ADI-R",
        "Age 12–45 years; Level 1 or Level 2 ASD (not requiring substantial support for communication)",
        "Baseline ADOS-2 Social Affect score ≥8 or RRB score ≥3",
        "Capable of informed consent (or assent with guardian consent)",
        "Target symptoms including social cognition deficits, repetitive behaviors, anxiety, or executive dysfunction",
        "Stable behavioral/pharmacological intervention for ≥4 weeks prior to enrollment",
    ],
    exclusion=[
        "Level 3 ASD (requiring very substantial support); nonverbal without AAC",
        "Active seizure disorder not controlled with medication (10–30% ASD comorbidity)",
        "Metallic implants in head/neck or implanted neurostimulator",
        "Active psychiatric crisis (psychosis, suicidality)",
        "Pregnancy",
        "Severe intellectual disability (IQ <50) precluding consent/assent and participation",
        "Recent medication change (<4 weeks) that could confound outcomes",
    ],
    discussion=[
        "ASD involves atypical development of large-scale brain networks: reduced long-range connectivity (social brain) and enhanced local connectivity (repetitive behavior networks).",
        "The social brain network — mPFC, TPJ, STS, amygdala — shows hypoconnectivity and atypical activation during social information processing.",
        "Mirror neuron system dysfunction in IFG and inferior parietal lobule contributes to social imitation and empathy deficits.",
        "Frontal lobe executive dysfunction (DLPFC hypoactivation) drives cognitive inflexibility, repetitive behaviors, and poor set-shifting.",
        "tDCS targeting DLPFC (anodal) improves cognitive flexibility, social cognition, and response inhibition.",
        "TPS over mPFC and DLPFC targets social brain network nodes and executive control regions.",
        "taVNS modulates autonomic nervous system dysregulation (common in ASD) and may improve social engagement via polyvagal mechanisms.",
        "CES addresses comorbid anxiety and sleep disruption, which are highly prevalent and functionally impairing in ASD.",
    ],
    overview=[
        "Autism Spectrum Disorder (ASD) is a neurodevelopmental condition characterized by persistent deficits in social communication and interaction, and restricted/repetitive patterns of behavior, interests, or activities. With a global prevalence of approximately 1-2%, ASD spans a wide spectrum of functional abilities and support needs. Core neurobiological features include atypical large-scale brain network organization: hypoconnectivity of long-range social brain networks and hyperconnectivity of local sensorimotor networks.",
        "The SOZO NIBS protocol for ASD targets core symptom domains through network-specific neuromodulation: social cognition (mPFC/TPJ/STS), executive function (DLPFC), repetitive behaviors (SMA/striatum), anxiety (taVNS/CES), and sensory processing. All NIBS is embedded within a behavioral/therapeutic framework (social skills training, CBT, ABA).",
        "Four clinical phenotypes guide protocol selection: social cognition and communication dominant, executive dysfunction and rigidity dominant, anxiety and sensory-overload dominant, and repetitive behavior dominant. The protocol is designed for adolescents and adults (12+) with Level 1 or Level 2 ASD capable of engaging with behavioral therapy.",
    ],
    pathophysiology=[
        "Atypical large-scale network organization: reduced long-range cortico-cortical connectivity between frontal and posterior social brain regions; overconnected local networks underlying repetitive behaviors.",
        "Social brain network hypoactivation: mPFC, TPJ, and superior temporal sulcus show reduced activity during social cognition tasks; mirror neuron system (IFG/IPL) shows atypical activation.",
        "DLPFC executive dysfunction: reduced activation during set-shifting, inhibitory control, and cognitive flexibility tasks; drives rigid, inflexible behavior.",
        "Amygdala hyperreactivity: exaggerated arousal response to social stimuli; contributes to social anxiety and avoidance in ASD.",
        "Autonomic dysregulation: reduced parasympathetic tone (low HRV); heightened sympathetic arousal; impaired social engagement via polyvagal system.",
        "Sensory processing differences: atypical sensory gating and integration in S1, S2, and sensory association areas; drives sensory over/under-reactivity.",
    ],
    std_treatment=[
        "Behavioral: Applied Behavior Analysis (ABA), Naturalistic Developmental Behavioral Interventions (NDBI)",
        "Communication: speech-language therapy, AAC (augmentative and alternative communication)",
        "Social skills: social skills training groups, social cognition interventions",
        "Pharmacological (comorbidities): risperidone/aripiprazole (irritability, aggression; FDA-approved), SSRIs (anxiety, repetitive behaviors), stimulants (ADHD comorbidity)",
        "Psychological: CBT for anxiety, Cognitive Behavioral Social Skills Training (CBSST)",
    ],
    symptoms=[
        ["Social Communication Deficits", "Reduced reciprocal social interaction, nonverbal communication difficulties", "100% (defining)", "APA DSM-5 2013"],
        ["Restricted Interests", "Intense, narrow special interests; rigid adherence to routines", "100% (defining)", "APA DSM-5 2013"],
        ["Repetitive Behaviors", "Stereotypies, echolalia, self-stimulatory behaviors (stimming)", "100% (defining)", "APA DSM-5 2013"],
        ["Anxiety", "Comorbid anxiety disorders (GAD, social anxiety, specific phobias)", "40–50%", "White 2009"],
        ["ADHD Features", "Inattention, hyperactivity, impulsivity (comorbid ADHD 50–70%)", "50–70%", "Simonoff 2008"],
        ["Sensory Reactivity", "Hyper/hyposensitivity across sensory modalities", "90%", "Marco 2011"],
        ["Executive Dysfunction", "Rigid thinking, poor set-shifting, cognitive inflexibility", "70%", "Hill 2004"],
        ["Sleep Disturbance", "Insomnia, irregular sleep-wake rhythm (60–80%)", "60–80%", "Mannion 2014"],
        ["Irritability/Aggression", "Meltdowns, self-injurious behavior (in more affected individuals)", "25%", "Sukhodolsky 2008"],
        ["Intellectual Disability", "Comorbid ID (~30%); does not preclude NIBS at Level 1–2", "30%", "Baio 2018"],
    ],
    brain_regions=[
        ["mPFC (BA10/11)", "Social cognition, mentalizing, theory of mind; hypoactive in ASD", "tDCS anodal, TPS", "Castelli 2002"],
        ["Temporoparietal Junction (TPJ)", "Theory of mind, perspective-taking; hypoconnected", "TPS, tDCS", "Saxe 2003"],
        ["Superior Temporal Sulcus (STS)", "Biological motion, face processing, social perception", "TPS", "Pelphrey 2005"],
        ["DLPFC", "Executive function, cognitive flexibility, working memory", "tDCS anodal", "Hill 2004"],
        ["Inferior Frontal Gyrus (IFG)", "Mirror neuron system, language, social imitation", "tDCS anodal, TPS", "Iacoboni 2006"],
        ["Amygdala", "Social-emotional arousal, threat detection; hyperreactive in ASD", "taVNS", "Baron-Cohen 2000"],
        ["Supplementary Motor Area", "Repetitive motor behaviors, stereotypies", "tDCS cathodal", "Mostofsky 2009"],
        ["Inferior Parietal Lobule (IPL)", "Mirror system, imitation, somatosensory social", "TPS", "Iacoboni 2006"],
    ],
    brainstem=[
        ["Locus Coeruleus", "Arousal, alertness, noradrenergic tone; dysregulated in ASD", "taVNS, CES", "Mehler 2009"],
        ["Nucleus Tractus Solitarius", "Vagal integration; autonomic-social interface (polyvagal)", "taVNS direct", "Porges 2007"],
        ["Raphe Nuclei", "Serotonergic tone; serotonin synthesis atypical in ASD", "taVNS", "Chugani 1997"],
        ["Superior Colliculus", "Visual orienting, joint attention; atypical in ASD", "None direct", "Senju 2005"],
        ["Cerebellum (Dentate)", "Social prediction errors, sensorimotor integration; affected in ASD", "TPS indirect", "Fatemi 2012"],
    ],
    phenotypes=[
        ["Social Cognition Dominant", "Core social-communication deficits; mPFC/TPJ/STS hypoactivation", "Limited reciprocity, eye contact, ToM deficits", "tDCS DLPFC + TPS mPFC/STS + taVNS"],
        ["Executive Dysfunction/Rigidity", "Cognitive inflexibility, perseveration, rigid routines; DLPFC deficit", "Meltdowns at transitions, restricted problem-solving", "tDCS DLPFC anodal + TPS DLPFC"],
        ["Anxiety/Sensory-Overload", "Comorbid anxiety (40%); sensory hypersensitivity driving overwhelm", "Meltdowns, avoidance, sensory distress", "taVNS + CES + tDCS DLPFC"],
        ["Repetitive Behavior Dominant", "Stereotypies, compulsions, restricted interests; SMA/striatal hyperactivation", "Motor and verbal stereotypies, rigid routines", "tDCS SMA cathodal + TPS SMA + behavioral"],
    ],
    symptom_map=[
        ["Social cognition deficits", "mPFC/TPJ/STS", "tDCS DLPFC + TPS mPFC", "Fecteau 2011, Schneider 2017"],
        ["Theory of mind deficit", "TPJ/mPFC", "TPS TPJ + tDCS DLPFC", "Saxe 2003"],
        ["Executive dysfunction", "DLPFC", "tDCS DLPFC anodal", "Hill 2004"],
        ["Repetitive behaviors", "SMA/Striatum", "tDCS SMA cathodal", "Mostofsky 2009"],
        ["Anxiety", "Amygdala/DLPFC", "taVNS + CES + tDCS DLPFC", "White 2009"],
        ["Sleep disruption", "Thalamus/LC", "CES Alpha-Stim nightly", "Mannion 2014"],
        ["Sensory reactivity", "S1/S2/STS", "tDCS cathodal S1 (investigational)", "Marco 2011"],
        ["Autonomic dysregulation", "Brainstem/Vagal", "taVNS polyvagal", "Porges 2007"],
        ["Irritability", "Amygdala/OFC", "taVNS + CES", "Sukhodolsky 2008"],
    ],
    montage=[
        ["Social Cognition Dominant", "Anodal DLPFC (F3, 1.5mA, 20min)", "mPFC/STS (250 pulses)", "taVNS 30min before; social skills concurrent"],
        ["Executive Dysfunction", "Anodal DLPFC (F3, 1.5mA, 20min)", "DLPFC (250 pulses)", "Behavioral flexibility training concurrent"],
        ["Anxiety/Sensory-Overload", "Anodal DLPFC (F3, 1.5mA, 20min)", "None initial", "taVNS primary + CES nightly; sensory desensitization"],
        ["Repetitive Behavior", "Cathodal SMA (Cz, 1.5mA, 20min)", "SMA (200 pulses)", "Behavioral support concurrent; habit reversal"],
        ["Combined Social + Executive", "Anodal DLPFC (F3, 1.5mA) + TPS", "mPFC + DLPFC (300 pulses)", "taVNS before; comprehensive behavioral program"],
        ["Comorbid ADHD", "Anodal DLPFC (F3, 1.5mA, 20min)", "DLPFC (200 pulses)", "Stimulant maintained if on; structured routine"],
        ["Adolescent (12–17)", "Anodal DLPFC (F3, 1mA, 15min)", "None initial (TPS later)", "taVNS + CES; parent-involved therapy"],
        ["Maintenance Phase", "Anodal DLPFC (F3, 1.5mA, 20min)", "None", "CES 3x/week; taVNS daily home"],
        ["High Anxiety/Meltdowns", "Anodal DLPFC (F3, 1.5mA, 20min)", "None", "taVNS primary; CES nightly; crisis plan"],
        ["Sham Protocol", "F3 anodal (30s ramp, 0mA, 20min)", "None", "Sham control condition"],
    ],
    tdcs_protocols=[
        ["AU-tDCS-01", "DLPFC Anodal (Social Cognition/Executive)", "F3", "F4", "1.5mA, 20min, 10 sessions", "Schneider 2017"],
        ["AU-tDCS-02", "SMA Cathodal (Repetitive Behaviors)", "Fp1", "Cz (SMA)", "1.5mA, 20min, 10 sessions", "Amatachaya 2014"],
        ["AU-tDCS-03", "Combined DLPFC + SMA", "F3 anodal; Cz cathodal", "F4; Fpz", "1.5mA each, 15 sessions", "Expert consensus 2023"],
        ["AU-tDCS-04", "mPFC Anodal (Social Brain)", "Fpz anodal", "Oz", "1mA, 20min, 10 sessions", "Fecteau 2011"],
        ["AU-tDCS-05", "Maintenance", "F3 anodal", "F4", "1.5mA, 20min, 2x/week", "Bikson 2016"],
        ["AU-tDCS-06", "Adolescent Adjusted", "F3 anodal", "F4", "1mA, 15min, 10 sessions", "Schneider 2017"],
        ["AU-tDCS-07", "Cathodal S1 (Sensory Reactivity — Research)", "C3/C4 cathodal", "Fpz", "1mA, 15min, investigational", "Marco 2011"],
        ["AU-tDCS-08", "Sham", "F3", "F4", "30s ramp, 0mA, 20min", "Schneider 2017"],
    ],
    plato_protocols=[
        ["AU-PLATO-01", "DLPFC Anodal", "F3/F4", "Left DLPFC", "F3", "1.5mA", "N/A", "Continuous 20min"],
        ["AU-PLATO-02", "SMA Cathodal", "Cz/Fpz", "SMA", "Cz", "1.5mA", "N/A", "Cathodal 20min"],
        ["AU-PLATO-03", "Combined DLPFC+SMA", "F3; Cz", "DLPFC + SMA", "F3; Cz", "1.5mA each", "N/A", "Sequential"],
        ["AU-PLATO-04", "mPFC Anodal", "Fpz/Oz", "mPFC", "Fpz", "1.0mA", "N/A", "Continuous 20min"],
        ["AU-PLATO-05", "Maintenance", "F3", "DLPFC", "F3", "1.5mA", "N/A", "2x/week"],
        ["AU-PLATO-06", "Theta tACS Social", "F3", "DLPFC", "F3", "1.0mA", "6Hz", "tACS 20min"],
        ["AU-PLATO-07", "Adolescent", "F3", "DLPFC", "F3", "1.0mA", "N/A", "15min"],
        ["AU-PLATO-08", "Sham", "F3", "DLPFC", "F3", "0mA", "N/A", "30s ramp"],
    ],
    tps_protocols=[
        ["AU-TPS-01", "mPFC Social Brain", "mPFC (BA10/11)", "250 pulses, 0.2Hz, 0.2mJ/mm²", "3 sessions/week", "Castelli 2002"],
        ["AU-TPS-02", "DLPFC Executive", "DLPFC (BA46)", "250 pulses, 0.2Hz", "3 sessions/week", "Hill 2004"],
        ["AU-TPS-03", "STS Social Perception", "Superior Temporal Sulcus", "200 pulses, 0.2Hz", "2 sessions/week", "Pelphrey 2005"],
        ["AU-TPS-04", "SMA Repetitive Behavior", "SMA (BA6)", "200 pulses, 0.2Hz", "2 sessions/week", "Mostofsky 2009"],
        ["AU-TPS-05", "Full Social Brain Protocol", "mPFC + DLPFC + STS sequential", "400 pulses total", "5 sessions/week x2 weeks", "Expert consensus 2024"],
    ],
    ces_role=[
        ["Anxiety Comorbidity", "Primary modality for comorbid anxiety in ASD; reduces arousal and reactivity", "Daily 60min; before stressful activities"],
        ["Sleep Disruption", "Improves sleep onset and continuity; highly prevalent in ASD", "Nightly 60min; titrate to sleep quality"],
        ["Sensory Overload Recovery", "Reduces post-meltdown hyperarousal and sensory distress", "As needed after sensory overload events"],
        ["Maintenance", "Long-term anxiety and arousal management", "3–5x/week; patient/caregiver managed"],
    ],
    tavns_role="taVNS (tragus, 25Hz, 200µs, 0.5mA, 30min) targets the polyvagal system: activating NTS → vagal efferents → amygdala/LC pathway to enhance parasympathetic tone (measured by HRV), reduce social anxiety, and support the social engagement system. Low HRV is a documented biomarker of autonomic dysregulation in ASD. Administered before NIBS sessions and as home device (2x daily). Social engagement facilitation via polyvagal normalization is the primary mechanism (Porges 2007, Patriquin 2019).",
    combinations=[
        ("Social Cognition Dominant", [
            ["tDCS DLPFC + TPS mPFC/STS + taVNS", "DLPFC executive + social brain nodes + polyvagal engagement", "taVNS → TPS → tDCS; pre-social skills session", "Social communication deficits, ToM impairment"],
        ]),
        ("Executive Dysfunction/Rigidity", [
            ["tDCS DLPFC + TPS DLPFC", "Convergent prefrontal excitability enhancement", "TPS → tDCS; pre-behavioral flexibility training", "Cognitive rigidity, perseveration"],
        ]),
        ("Anxiety/Sensory-Overload", [
            ["taVNS + CES + tDCS DLPFC", "Polyvagal + thalamic + prefrontal anxiety management", "taVNS → tDCS; CES nightly", "Comorbid anxiety, sensory meltdowns"],
        ]),
        ("Repetitive Behavior Dominant", [
            ["tDCS SMA cathodal + TPS SMA + behavioral", "SMA inhibition — motor and behavioral level", "TPS → tDCS; habit reversal concurrent", "Stereotypies, repetitive motor behaviors"],
        ]),
        ("Comprehensive ASD Protocol", [
            ["tDCS DLPFC + TPS mPFC/STS + taVNS + CES", "Social + executive + polyvagal + anxiolytic", "taVNS → TPS → tDCS + CES nightly", "Multi-domain ASD with anxiety"],
        ]),
        ("Adolescent Protocol", [
            ["tDCS DLPFC (low) + taVNS + CES", "Conservative: DLPFC + polyvagal + anxiolytic", "taVNS before tDCS; CES nightly", "Age 12–17 ASD with anxiety/executive deficit"],
        ]),
    ],
    combination_summary=[
        ["Social Cognition", "tDCS DLPFC + TPS mPFC/STS + taVNS", "Social brain + polyvagal", "taVNS → TPS → tDCS + social skills", "Social-communication deficits", "IIb"],
        ["Executive/Rigidity", "tDCS DLPFC + TPS DLPFC", "Convergent prefrontal", "TPS → tDCS + behavioral", "Cognitive inflexibility", "IIb"],
        ["Anxiety/Sensory", "taVNS + CES + tDCS DLPFC", "Polyvagal + thalamic + prefrontal", "taVNS → tDCS + CES nightly", "Anxiety, sensory overload", "IIb"],
        ["Repetitive Behaviors", "tDCS SMA cathodal + TPS SMA", "SMA inhibition convergent", "TPS → tDCS + behavioral", "Stereotypies, rituals", "IIb"],
        ["Comprehensive", "All four modalities", "Multi-domain network normalization", "taVNS → TPS → tDCS + CES", "Multi-domain ASD", "IIb"],
        ["Adolescent", "tDCS DLPFC (low) + taVNS + CES", "Conservative comprehensive", "taVNS → tDCS + CES", "Age 12–17 ASD", "IIb"],
    ],
    outcomes=[
        ["ADOS-2 Social Affect Score", "Social communication severity", "Baseline, 8wk, 16wk", "≥3-point reduction"],
        ["Social Responsiveness Scale-2 (SRS-2)", "Social responsiveness (parent/self-report)", "Baseline, 4wk, 8wk", "≥10-point T-score reduction"],
        ["BRIEF-2 Executive Composite", "Executive function", "Baseline, 4wk, 8wk", "≥10-point reduction in T-score"],
        ["Repetitive Behavior Scale-Revised (RBS-R)", "Repetitive behavior frequency/severity", "Baseline, 4wk, 8wk", "≥15% reduction in total score"],
        ["SCARED (Anxiety)", "Comorbid anxiety", "Baseline, 4wk, 8wk", "≥10-point reduction"],
        ["Pittsburgh Sleep Quality Index (PSQI)", "Sleep quality", "Baseline, 4wk, 8wk", "≥3-point improvement"],
        ["Heart Rate Variability (RMSSD)", "Autonomic/polyvagal regulation", "Baseline, 4wk, 8wk", "≥10% increase"],
        ["Vineland Adaptive Behavior Scales-3", "Adaptive functioning", "Baseline, 8wk", "≥5-point increase in composite"],
        ["Caregiver Stress Index (CSI)", "Caregiver burden", "Baseline, 8wk", "≥20% reduction"],
    ],
    outcomes_abbrev=[
        "ADOS-2: Autism Diagnostic Observation Schedule-2",
        "SRS-2: Social Responsiveness Scale-2",
        "BRIEF-2: Behavior Rating Inventory of Executive Function-2",
        "RBS-R: Repetitive Behavior Scale-Revised",
        "SCARED: Screen for Child Anxiety Related Disorders",
        "PSQI: Pittsburgh Sleep Quality Index",
        "HRV/RMSSD: Heart Rate Variability / Root Mean Square of Successive Differences",
        "ToM: Theory of Mind",
        "mPFC: Medial Prefrontal Cortex",
        "STS: Superior Temporal Sulcus",
    ],
)

# ---------------------------------------------------------------------------
# CONDITION: LONG COVID (Post-Acute Sequelae of SARS-CoV-2)
# ---------------------------------------------------------------------------
CONDITIONS["long_covid"] = dict(
    name="Long COVID (Post-Acute Sequelae of SARS-CoV-2)",
    icd10="U09.9",
    doc_num="SPG-LC-001",
    tps_status="Investigational",
    tdcs_class="Class IIb",
    tps_class="Investigational",
    tavns_class="Class IIb",
    ces_class="Class IIb",
    inclusion=[
        "WHO-defined Long COVID: symptoms persisting ≥12 weeks post-SARS-CoV-2 infection not explained by alternative diagnosis",
        "Symptom burden including cognitive impairment, fatigue, autonomic dysfunction, or mood symptoms",
        "Cognitive domain: MoCA ≤25 or MFIS ≥38 at baseline",
        "Age 18–65; capable of informed consent",
        "Confirmed prior SARS-CoV-2 infection (PCR, antigen, or serology)",
        "Stable symptoms for ≥4 weeks (not in acute post-COVID relapse)",
    ],
    exclusion=[
        "Active SARS-CoV-2 infection (acute phase)",
        "Metallic implants in head/neck or implanted neurostimulator",
        "Pregnancy",
        "Pre-existing neurological or psychiatric diagnosis that adequately explains symptoms",
        "Severe post-exertional malaise precluding protocol participation (energy envelope too limited)",
        "Active myocarditis or pericarditis (POTS screening required)",
        "EDSS >6 equivalent disability from Long COVID",
    ],
    discussion=[
        "Long COVID involves multisystem pathology including neuroinflammation, cerebrovascular microangiopathy, autonomic nervous system dysfunction (POTS), mast cell activation, and mitochondrial impairment.",
        "Cognitive impairment (brain fog) reflects frontal-network disruption, thalamic microstructural damage, and neuroinflammatory cytokine effects on synaptic function.",
        "Autonomic dysfunction (POTS, orthostatic intolerance) is a dominant mechanism of fatigue and exercise intolerance; taVNS targets the autonomic-cardiovascular interface.",
        "tDCS targeting DLPFC addresses cognitive fog through direct prefrontal excitability enhancement and network normalization.",
        "TPS over the frontal and thalamic projections targets network-level cognitive recovery.",
        "taVNS offers anti-inflammatory, autonomic regulatory, and direct cognitive-fatigue benefits in Long COVID.",
        "CES addresses the insomnia, anxiety, and thalamic dysrhythmia components of Long COVID symptom burden.",
        "Pacing and energy conservation are essential co-treatment principles; NIBS intensity must be calibrated to individual energy envelope.",
    ],
    overview=[
        "Long COVID (Post-Acute Sequelae of SARS-CoV-2, PASC) is defined by the WHO as symptoms persisting for ≥12 weeks following SARS-CoV-2 infection, not explained by an alternative diagnosis. Affecting an estimated 10-30% of COVID-19 survivors, Long COVID represents a major global health burden with neurological symptoms — cognitive impairment, fatigue, autonomic dysfunction, headache, and mood disorders — among the most prevalent and disabling.",
        "The SOZO NIBS protocol for Long COVID targets the neurological and autonomic mechanisms underlying the most common symptom domains: prefrontal-thalamic cognitive network disruption (brain fog), autonomic dysregulation (POTS/HRV impairment), neuroinflammatory fatigue, and insomnia/mood comorbidity.",
        "Four clinical phenotypes are identified: cognitive-dominant (brain fog), autonomic-dominant (POTS/fatigue), neuropsychiatric (anxiety/depression/insomnia), and post-exertional malaise (PEM)-dominant. Energy envelope management is mandatory across all phenotypes.",
    ],
    pathophysiology=[
        "Neuroinflammation: activated microglia, astrogliosis, and inflammatory cytokine (IL-6, TNF-alpha) effects on synaptic function; white matter microstructural damage on advanced MRI.",
        "Thalamic microangiopathy: COVID-19-related cerebrovascular endotheliopathy and microclot formation disrupt thalamo-cortical relay networks, causing cognitive fog.",
        "Autonomic nervous system dysfunction: reduced HRV, POTS, sympathetic overdrive, and impaired baroreceptor reflex; primary driver of fatigue and exercise intolerance.",
        "Mitochondrial dysfunction: impaired cellular energy production amplifies fatigue, cognitive impairment, and post-exertional malaise.",
        "Reactivated viral reservoirs: persistent spike protein or viral RNA in CNS/gut may maintain ongoing neuroinflammatory signaling.",
        "DLPFC-CEN hypoactivation: direct neuroinflammatory and vascular effects reduce frontal network efficiency, producing cognitive fog and executive dysfunction.",
    ],
    std_treatment=[
        "Symptom management: pacing/activity management (energy envelope), graded exercise (POTS subtypes only — not PEM-dominant)",
        "Autonomic: compression garments, salt/fluid loading, beta-blockers or ivabradine (POTS)",
        "Cognitive rehabilitation: cognitive training, compensatory strategies, occupational therapy",
        "Pharmacological: low-dose naltrexone (LDN, anti-inflammatory), antihistamines (mast cell activation), SSRIs for mood/autonomic",
        "Research interventions: Paxlovid extended (viral reservoir), BC007 (autoantibodies), hyperbaric oxygen therapy",
    ],
    symptoms=[
        ["Cognitive Impairment (Brain Fog)", "Concentration, memory, word-finding, mental fatigue", "50–70%", "Taquet 2021"],
        ["Fatigue", "Debilitating, disproportionate fatigue; post-exertional malaise", "58–70%", "Davis 2021"],
        ["Post-Exertional Malaise (PEM)", "Symptom worsening ≥24h after minimal physical/mental exertion", "40–60%", "Davis 2021"],
        ["Dyspnea", "Breathlessness persisting beyond acute illness", "25%", "Nalbandian 2021"],
        ["Sleep Disturbance", "Insomnia, hypersomnia, unrefreshing sleep", "40%", "Huang 2021"],
        ["Headache", "Persistent new-onset or worsened headache", "30%", "Nalbandian 2021"],
        ["Anxiety/Depression", "Comorbid mood disorders (partly neuroinflammatory)", "30%", "Taquet 2021"],
        ["Autonomic Dysfunction (POTS)", "Orthostatic tachycardia, palpitations, dizziness", "20–30%", "Blitshteyn 2021"],
        ["Sensory Symptoms", "Paresthesias, dysesthesias, anosmia, parosmia", "30%", "Nalbandian 2021"],
        ["Pain", "Myalgia, arthralgia, headache; central sensitization features", "35%", "Davis 2021"],
    ],
    brain_regions=[
        ["DLPFC", "Cognitive control, working memory; hypoactivated in brain fog", "tDCS anodal", "Taquet 2021"],
        ["Thalamus", "Cognitive relay; microangiopathy-damaged; thalamocortical dysrhythmia", "CES, TPS", "Qin 2021"],
        ["ACC", "Fatigue perception, cognitive effort, conflict; hyperactivated in Long COVID", "TPS", "Yaldizli 2011"],
        ["Default Mode Network", "Self-referential processing; disrupted DMN-CEN anticorrelation", "tDCS DLPFC", "Taquet 2021"],
        ["Hippocampus", "Episodic memory; neuroinflammatory vulnerability", "taVNS", "Heneka 2020"],
        ["Insula", "Interoception, autonomic integration, dyspnea; hyperactivated", "TPS", "Craig 2002"],
        ["Brainstem (NTS/LC)", "Autonomic regulation; COVID-19 direct brainstem pathology", "taVNS", "Guedj 2021"],
        ["White Matter Networks", "CEN and DMN connectivity reduced by microangiopathy", "tDCS DLPFC indirect", "Lu 2022"],
    ],
    brainstem=[
        ["Locus Coeruleus", "Autonomic arousal, fatigue, noradrenergic tone; COVID-19 direct target", "taVNS, CES", "Guedj 2021"],
        ["Nucleus Tractus Solitarius", "Vagal integration, autonomic relay; COVID-19 brainstem pathology", "taVNS direct", "Tracey 2002"],
        ["Dorsal Vagal Complex", "Autonomic-inflammatory interface; key Long COVID target", "taVNS direct", "Bonaz 2016"],
        ["Raphe Nuclei", "Serotonergic tone; anxiety/mood in Long COVID", "taVNS", "Feinstein 2011"],
        ["Nucleus Ambiguus", "Vagal cardiac efferents; HRV generation; POTS-relevant", "taVNS indirect", "Porges 2007"],
    ],
    phenotypes=[
        ["Cognitive-Dominant (Brain Fog)", "Processing speed, memory, word-finding deficits; DLPFC-thalamic network disruption", "Cognitive impairment, work/study incapacity", "tDCS DLPFC + TPS + CES"],
        ["Autonomic-Dominant (POTS/Fatigue)", "Orthostatic intolerance, tachycardia, fatigue; ANS dysregulation primary", "Exercise intolerance, palpitations, dizziness", "taVNS primary + CES + tDCS DLPFC low"],
        ["Neuropsychiatric (Anxiety/Depression/Insomnia)", "Mood disorders, anxiety, insomnia; neuroinflammatory-serotonergic", "Depression, panic, sleep disruption", "tDCS DLPFC + taVNS + CES"],
        ["PEM-Dominant", "Post-exertional malaise >24h with minimal exertion; mitochondrial/metabolic", "Activity restriction, severe fatigue crashes", "CES primary + taVNS; tDCS only if tolerated"],
    ],
    symptom_map=[
        ["Brain fog/cognitive impairment", "DLPFC/Thalamus", "tDCS DLPFC + CES", "Taquet 2021"],
        ["Fatigue", "ACC/Thalamus/Brainstem", "CES + taVNS", "Davis 2021"],
        ["Autonomic dysfunction/POTS", "Brainstem/NTS/LC", "taVNS primary", "Blitshteyn 2021"],
        ["Anxiety/Depression", "DLPFC/Limbic", "tDCS DLPFC + taVNS + CES", "Taquet 2021"],
        ["Sleep disruption", "Thalamus/LC", "CES nightly", "Huang 2021"],
        ["Headache", "Thalamus/Cortical", "TPS investigational; CES", "Nalbandian 2021"],
        ["Neuroinflammation", "CNS-wide", "taVNS anti-inflammatory", "Bonaz 2016"],
        ["PEM", "Systemic/Mitochondrial", "CES only; strict pacing", "Davis 2021"],
        ["Sensory symptoms", "Insula/Thalamus", "TPS insula + CES", "Nalbandian 2021"],
    ],
    montage=[
        ["Cognitive-Dominant", "Anodal DLPFC (F3, 1.5–2mA, 20min)", "DLPFC + Thalamic (250 pulses)", "CES nightly; pacing essential"],
        ["Autonomic-Dominant", "Anodal DLPFC (F3, 1mA, 15min) — low dose", "None initial", "taVNS primary 2x daily; CES nightly; POTS management concurrent"],
        ["Neuropsychiatric", "Anodal DLPFC (F3, 1.5mA, 20min)", "None initial", "taVNS + CES nightly; SSRI if prescribed maintained"],
        ["PEM-Dominant", "Avoid tDCS if causes PEM — start CES only", "None", "CES primary; taVNS only (ultra-low dose); strict energy management"],
        ["Cognitive + Autonomic Combined", "Anodal DLPFC (F3, 1mA, 15min)", "DLPFC (150 pulses max)", "taVNS before tDCS; CES nightly"],
        ["Maintenance Phase", "Anodal DLPFC (F3, 1mA, 15min)", "None", "CES 3x/week; taVNS daily home"],
        ["Severe PEM (Research)", "Not recommended — defer", "Not recommended", "CES only; monitor energy envelope weekly"],
        ["Elderly Adjusted", "Anodal DLPFC (F3, 1mA, 15min)", "TPS very low (100 pulses)", "CES + taVNS; conservative approach"],
        ["Headache Subtype", "Anodal DLPFC (F3, 1.5mA, 20min)", "None initial", "CES; TPS future consideration"],
        ["Sham Protocol", "F3 anodal (30s ramp, 0mA, 20min)", "None", "Sham control condition"],
    ],
    tdcs_protocols=[
        ["LC-tDCS-01", "DLPFC Anodal (Brain Fog/Cognitive)", "F3", "F4", "1.5–2mA, 20min, 10 sessions", "Expert consensus 2023"],
        ["LC-tDCS-02", "DLPFC Low Dose (Autonomic/PEM-sensitive)", "F3", "F4", "1mA, 15min, 10 sessions", "Pacing-adapted protocol"],
        ["LC-tDCS-03", "Bifrontal (Neuropsychiatric)", "F3 anodal", "F4 cathodal", "1.5mA, 20min, 10 sessions", "Brunoni 2013"],
        ["LC-tDCS-04", "PEM Monitoring Protocol", "F3", "F4", "Start 0.5mA, escalate if tolerated", "Energy envelope-adaptive"],
        ["LC-tDCS-05", "Maintenance", "F3 anodal", "F4", "1mA, 15min, 2x/week", "Bikson 2016"],
        ["LC-tDCS-06", "Combined DLPFC + CES adjunct", "F3 anodal", "F4", "1.5mA, 20min + CES concurrent", "Expert consensus 2024"],
        ["LC-tDCS-07", "Elderly Adjusted", "F3 anodal", "F4", "1mA, 15min, 10 sessions", "Lefaucheur 2016"],
        ["LC-tDCS-08", "Sham", "F3", "F4", "30s ramp, 0mA, 20min", "Sham control"],
    ],
    plato_protocols=[
        ["LC-PLATO-01", "DLPFC Anodal Standard", "F3/F4", "Left DLPFC", "F3", "1.5mA", "N/A", "Continuous 20min"],
        ["LC-PLATO-02", "DLPFC Low Dose", "F3/F4", "Left DLPFC", "F3", "1.0mA", "N/A", "15min continuous"],
        ["LC-PLATO-03", "Bifrontal", "F3/F4", "Bifrontal", "F3", "1.5mA", "N/A", "Sequential"],
        ["LC-PLATO-04", "HD-tDCS DLPFC", "F3 center", "4-electrode ring", "F3", "0.5mA", "N/A", "HD 15min — low dose"],
        ["LC-PLATO-05", "Maintenance", "F3", "DLPFC", "F3", "1.0mA", "N/A", "2x/week 15min"],
        ["LC-PLATO-06", "Gamma tACS Cognitive", "F3", "DLPFC", "F3", "1.0mA", "40Hz", "tACS 15min"],
        ["LC-PLATO-07", "Elderly/PEM-Sensitive", "F3", "DLPFC", "F3", "0.5mA", "N/A", "10min"],
        ["LC-PLATO-08", "Sham", "F3", "DLPFC", "F3", "0mA", "N/A", "30s ramp"],
    ],
    tps_protocols=[
        ["LC-TPS-01", "DLPFC Cognitive Network", "DLPFC (BA46)", "200 pulses, 0.2Hz, 0.15mJ/mm²", "2 sessions/week", "Expert consensus 2023"],
        ["LC-TPS-02", "ACC Fatigue Hub", "ACC (BA24/32)", "150 pulses, 0.15Hz", "2 sessions/week", "Yaldizli 2011"],
        ["LC-TPS-03", "Insula Autonomic/Sensory", "Posterior Insula", "150 pulses, 0.15Hz", "1 session/week — cautious", "Craig 2002"],
        ["LC-TPS-04", "Thalamic Projection (Indirect)", "Frontal projections to thalamus", "200 pulses, 0.2Hz", "2 sessions/week", "Expert consensus 2024"],
        ["LC-TPS-05", "PEM-Adapted Protocol", "DLPFC only — minimal exposure", "100 pulses, 0.15Hz", "1 session/week — monitor PEM", "Expert consensus 2024"],
    ],
    ces_role=[
        ["Primary Fatigue/Sleep", "Primary NIBS modality for fatigue and insomnia in Long COVID; safest in PEM-dominant", "Daily 60min; nightly for sleep"],
        ["PEM-Dominant", "Only recommended NIBS in severe PEM; monitor energy response", "Start 20min; escalate if tolerated"],
        ["Neuropsychiatric", "Anxiolytic and sleep-normalizing adjunct", "Daily 60min; before bedtime"],
        ["Maintenance", "Long-term symptom management; patient self-administered", "3–5x/week; home device program"],
    ],
    tavns_role="taVNS (tragus, 25Hz, 200µs, 0.5mA, 30min) is a cornerstone of Long COVID NIBS treatment through three mechanisms: (1) Cholinergic anti-inflammatory pathway activation — reduces neuroinflammatory cytokine burden; (2) Autonomic normalization — increases HRV, reduces sympathetic overdrive, directly addresses POTS pathophysiology; (3) Cognitive-fatigue modulation via LC-noradrenergic and raphe-serotonergic activation. Twice-daily home device use (Nemos/TENS tragus) is the recommended maintenance regimen. PEM monitoring is essential — if taVNS worsens PEM, reduce session duration to 15min or less (Bonaz 2016, Tracey 2002, Clancy 2022).",
    combinations=[
        ("Cognitive-Dominant", [
            ["tDCS DLPFC + TPS DLPFC + CES", "Convergent prefrontal + thalamic cognitive network", "TPS → tDCS; CES nightly; pacing", "Brain fog, cognitive impairment"],
            ["tDCS DLPFC + taVNS + CES", "Prefrontal + anti-inflammatory + thalamic", "taVNS before tDCS; CES nightly", "Brain fog with neuroinflammation/fatigue"],
        ]),
        ("Autonomic-Dominant", [
            ["taVNS + CES", "Dual autonomic normalization; safe in POTS", "taVNS 2x daily; CES nightly; POTS concurrent", "POTS, orthostatic intolerance, fatigue"],
            ["taVNS + tDCS DLPFC (low)", "Autonomic + minimal cognitive support", "taVNS before low-dose tDCS", "POTS with cognitive fog — energy-adapted"],
        ]),
        ("Neuropsychiatric", [
            ["tDCS DLPFC + taVNS + CES", "Antidepressant + vagal + anxiolytic-thalamic", "taVNS → tDCS + CES nightly", "Anxiety/depression/insomnia in Long COVID"],
        ]),
        ("PEM-Dominant", [
            ["CES only", "Safest modality; no exertional demand", "CES nightly 60min; strict energy management", "Severe PEM — defer other modalities"],
            ["CES + taVNS (ultra-low)", "Minimal dual anti-inflammatory + sleep", "CES nightly; taVNS 15min once daily max", "PEM with neuroinflammation"],
        ]),
        ("Headache Subtype", [
            ["tDCS DLPFC + CES", "Prefrontal + thalamic headache modulation", "tDCS daytime; CES nightly", "Persistent headache subtype"],
        ]),
        ("Comprehensive Stable Long COVID", [
            ["tDCS DLPFC + TPS + taVNS + CES", "Full neurological Long COVID protocol", "taVNS → TPS → tDCS + CES nightly", "Stable multi-domain Long COVID — not PEM-dominant"],
        ]),
    ],
    combination_summary=[
        ["Cognitive-Dominant", "tDCS DLPFC + TPS + CES", "Prefrontal + thalamic cognitive", "TPS → tDCS + CES nightly", "Brain fog", "IIb"],
        ["Autonomic-Dominant", "taVNS + CES", "Dual autonomic normalization", "taVNS 2x daily + CES nightly", "POTS/fatigue", "IIb"],
        ["Neuropsychiatric", "tDCS DLPFC + taVNS + CES", "Antidepressant + vagal + anxiolytic", "taVNS → tDCS + CES nightly", "Anxiety/depression/insomnia", "IIb"],
        ["PEM-Dominant", "CES only (± taVNS ultra-low)", "Safest; minimal exertion demand", "CES nightly; strict pacing", "Severe PEM", "IIb"],
        ["Headache Subtype", "tDCS DLPFC + CES", "Prefrontal + thalamic headache", "tDCS daytime + CES nightly", "Persistent headache", "IIb"],
        ["Comprehensive Stable", "All four modalities", "Multi-domain Long COVID", "taVNS → TPS → tDCS + CES", "Stable multi-domain", "IIb"],
    ],
    outcomes=[
        ["MoCA Score", "Cognitive screening", "Baseline, 4wk, 8wk", "≥2-point improvement"],
        ["MFIS Total Score", "Fatigue severity", "Baseline, 4wk, 8wk", "≥5-point reduction (MCID)"],
        ["Heart Rate Variability (RMSSD)", "Autonomic/vagal tone", "Baseline, 4wk, 8wk", "≥10% increase"],
        ["Orthostatic Heart Rate Test", "POTS assessment (10-min stand test)", "Baseline, 4wk, 8wk", "HR increase <30bpm at 10min stand"],
        ["PHQ-9", "Depression", "Baseline, 4wk, 8wk", "≥5-point reduction"],
        ["Pittsburgh Sleep Quality Index (PSQI)", "Sleep quality", "Baseline, 4wk, 8wk", "≥3-point improvement"],
        ["Post-Exertional Malaise (DSQ-PEM)", "PEM frequency/severity", "Baseline, 4wk, 8wk", "≥30% reduction in PEM frequency"],
        ["PROMIS Cognitive Function", "Self-reported cognitive function", "Baseline, 4wk, 8wk", "≥5-point T-score improvement"],
        ["Patient Global Impression of Change", "Overall improvement", "4wk, 8wk", "≥5/7 (much improved)"],
    ],
    outcomes_abbrev=[
        "MoCA: Montreal Cognitive Assessment",
        "MFIS: Modified Fatigue Impact Scale",
        "HRV/RMSSD: Heart Rate Variability / Root Mean Square of Successive RR Differences",
        "POTS: Postural Orthostatic Tachycardia Syndrome",
        "PHQ-9: Patient Health Questionnaire-9",
        "PSQI: Pittsburgh Sleep Quality Index",
        "DSQ-PEM: DePaul Symptom Questionnaire — Post-Exertional Malaise",
        "PROMIS: Patient-Reported Outcomes Measurement Information System",
        "PEM: Post-Exertional Malaise",
        "ANS: Autonomic Nervous System",
    ],
)
print("MS + ASD + Long COVID appended OK")
'''

with open(OUTFILE, "a", encoding="utf-8") as f:
    f.write(BLOCK)

print("MS + ASD + Long COVID appended OK")
