"""
Essential Tremor — Complete condition generator.

Key references:
- Bhattacharyya KB (2016) Benign essential tremor: a review. PMID: 27429701
- Hellriegel H et al. (2012) Sustained-release oxycodone in refractory tremor. PMID: 22313960
- Quattrocchi G et al. (2017) Cerebellar TMS in essential tremor. PMID: 27706955
- Deuschl G et al. (1998) Clinical classification of essential tremor. PMID: 9556143
- Fahn S et al. (1993) The Fahn-Tolosa-Marin Tremor Rating Scale. TRS validation.
- Limousin P et al. (2019) VIM DBS for essential tremor — long-term outcomes. PMID: 31116408
"""
import logging
from ...schemas.condition import (
    ConditionSchema, PhenotypeSubtype, NetworkProfile,
    StimulationTarget, AssessmentTool, SafetyNote, ProtocolEntry
)
from ...core.enums import (
    NetworkKey, NetworkDysfunction, Modality, EvidenceLevel
)
from ...core.utils import current_date_str
from ..shared_condition_schema import (
    make_network, make_tdcs_target, make_tps_target, make_safety,
    SHARED_ABSOLUTE_CONTRAINDICATIONS, SHARED_SAFETY_NOTES, SHARED_GOVERNANCE_RULES
)

logger = logging.getLogger(__name__)


def build_essential_tremor_condition() -> ConditionSchema:
    """Build the complete Essential Tremor condition schema."""
    return ConditionSchema(
        slug="essential_tremor",
        display_name="Essential Tremor",
        icd10="G25.0",
        aliases=["ET", "essential tremor", "benign familial tremor"],
        version="1.0",
        generated_at=current_date_str(),

        overview=(
            "Essential Tremor (ET) is the most common movement disorder, affecting approximately "
            "5% of adults over 40 and up to 15% of adults over 65. It is characterized by "
            "bilateral, predominantly postural and kinetic tremor of the upper limbs, with "
            "possible involvement of the head, voice, and lower limbs. Despite its 'benign' "
            "historical label, ET causes significant functional disability and psychosocial "
            "burden — approximately 25% of patients eventually require occupational assistance.\n\n"
            "Family history is present in 50-70% (autosomal dominant with incomplete penetrance). "
            "Pathological tremor is generated by abnormal oscillatory activity in the cerebello-"
            "thalamo-cortical (CTC) circuit. First-line pharmacotherapy (propranolol, primidone) "
            "provides benefit in only 50-60% of patients, with significant side effects.\n\n"
            "For refractory ET, DBS of the ventral intermediate nucleus (VIM) of the thalamus "
            "is the gold standard, providing dramatic tremor suppression in 75-90% of cases. "
            "Non-invasive neuromodulation (cerebellar TMS, tDCS) is emerging as an option for "
            "mild-to-moderate ET or patients who decline or cannot undergo DBS."
        ),

        pathophysiology=(
            "Essential tremor pathophysiology centers on the cerebello-thalamo-cortical (CTC) circuit:\n\n"
            "(1) Cerebellar dysfunction: Pathological studies show Purkinje cell loss and torpedoes "
            "(axonal swellings) in ET cerebellum. GABAergic Purkinje cell dysfunction leads to "
            "abnormal deep cerebellar nuclei (dentate nucleus) firing — generating rhythmic "
            "bursting in the 4-12 Hz tremor frequency range.\n\n"
            "(2) Thalamo-cortical loop oscillation: Abnormal dentate nucleus output drives "
            "rhythmic firing in VIM thalamus, which propagates through the thalamo-cortical "
            "relay to primary motor cortex (M1). This generates the 4-12 Hz oscillation "
            "expressed as limb tremor.\n\n"
            "(3) Olivocerebellar pathway: The inferior olive (IO) is proposed as a pacemaker — "
            "inferior olivary nucleus shows increased coupling in ET. Some studies suggest the "
            "IO generates the 8-12 Hz rhythmic activity entraining the CTC loop.\n\n"
            "(4) Cortical contribution: M1 shows abnormal beta-gamma synchronization with "
            "tremor frequency. Cerebellar TMS can disrupt the CTC loop by modulating "
            "Purkinje-dentate-thalamo-cortical signaling.\n\n"
            "(5) DBS mechanism: VIM-DBS suppresses tremor by disrupting the pathological "
            "thalamic oscillatory loop, preventing CTC circuit amplification."
        ),

        core_symptoms=[
            "Bilateral postural tremor — present when arms held against gravity (hands > head)",
            "Kinetic (action) tremor — worsened with voluntary movement",
            "Task-specific tremor — writing, pouring liquids, eating",
            "Head tremor (titubation) — yes/no nodding or no/no rotation",
            "Voice tremor — tremulous voice quality",
            "Worsened by caffeine, stress, fatigue; relieved by alcohol",
        ],

        non_motor_symptoms=[
            "Cognitive deficits (mild executive dysfunction in long-standing ET)",
            "Depression and anxiety (2-fold increased risk vs. controls)",
            "Sleep disturbance — some patients have rest tremor during sleep onset",
            "Psychological impact — social embarrassment, occupational limitation",
        ],

        key_brain_regions=[
            "Cerebellum (cortex, Purkinje cells, dentate nucleus)",
            "VIM Thalamus (ventral intermediate nucleus)",
            "Primary Motor Cortex (M1, C3/C4)",
            "Inferior Olive",
            "Red Nucleus",
            "Thalamo-Cortical Tract",
        ],

        brain_region_descriptions={
            "Cerebellum (cortex, Purkinje cells, dentate nucleus)": "Primary pathological site in ET. "
                "Purkinje cell dysfunction generates abnormal dentate nucleus oscillatory output. "
                "Cerebellar TMS (over Oz/lateral cerebellum) modulates CTC circuit.",
            "VIM Thalamus (ventral intermediate nucleus)": "Key relay in tremor circuit. DBS gold "
                "standard target — VIM-DBS suppresses tremor in 75-90% of refractory ET. "
                "Located deep — inaccessible to surface neuromodulation.",
            "Primary Motor Cortex (M1, C3/C4)": "Tremor output cortex. Receives pathological "
                "thalamic input; expresses tremor frequency oscillation. Secondary TMS/tDCS target.",
            "Inferior Olive": "Proposed pacemaker in ET — generates 8-12 Hz rhythmic activity "
                "propagated through olivocerebellar pathway.",
            "Red Nucleus": "Part of the dentato-rubro-thalamic tract (DRTT) targeted by DBS. "
                "Lesioning approaches also target this pathway.",
            "Thalamo-Cortical Tract": "Conducts pathological oscillations from VIM thalamus "
                "to M1 cortex. HIFU (focused ultrasound) can lesion this tract non-invasively.",
        },

        network_profiles=[
            make_network(
                NetworkKey.SMN, NetworkDysfunction.HYPER,
                "PRIMARY NETWORK IN ET. Sensorimotor network hyperoscillation drives tremor expression. "
                "Abnormal 4-12 Hz synchronization in the cerebello-thalamo-cortical loop generates "
                "tremor. SMN is the primary network target: TMS/tDCS over M1 and cerebellar TMS "
                "aim to normalize CTC circuit oscillation.",
                primary=True, severity="severe",
                evidence_note="Bhattacharyya (2016); Deuschl et al. (1998) — CTC circuit in ET",
            ),
            make_network(
                NetworkKey.CEN, NetworkDysfunction.HYPO,
                "Mild CEN hypoactivation in long-standing ET drives executive deficits. "
                "Compensatory prefrontal resources required to suppress tremor during voluntary tasks.",
                severity="mild",
            ),
            make_network(
                NetworkKey.LIMBIC, NetworkDysfunction.HYPER,
                "Limbic involvement: depression and anxiety (2x increased vs. controls) — "
                "driven partly by functional disability and social embarrassment from tremor.",
                severity="mild-moderate",
            ),
        ],

        primary_network=NetworkKey.SMN,

        fnon_rationale=(
            "In ET, the primary target is the sensorimotor network — specifically the "
            "cerebello-thalamo-cortical (CTC) circuit oscillation. Non-invasive neuromodulation "
            "approaches: (1) Cerebellar TMS — inhibitory 1 Hz rTMS over lateral cerebellum "
            "disrupts Purkinje-dentate oscillatory output; (2) M1 tDCS — cathodal stimulation "
            "reduces motor cortex excitability and tremor amplitude; (3) For severe/refractory ET, "
            "DBS VIM is gold standard — non-invasive options for mild-moderate ET or "
            "DBS non-candidates."
        ),

        phenotypes=[
            PhenotypeSubtype(
                slug="upper_limb",
                label="ET-UL — Upper Limb Tremor",
                description="Predominantly bilateral hand and arm postural/kinetic tremor. Most disabling for ADLs — handwriting, eating, pouring. Primary candidate for cerebellar TMS and M1 tDCS.",
                key_features=["Bilateral postural hand tremor", "Kinetic tremor", "Writing difficulty", "Pouring/eating difficulty", "TETRAS dominant"],
                primary_networks=[NetworkKey.SMN],
                secondary_networks=[NetworkKey.CEN],
                preferred_modalities=[Modality.TMS, Modality.TDCS],
                tdcs_target="Contralateral M1 cathodal (C3/C4) or cerebellar tDCS",
                tps_target=None,
            ),
            PhenotypeSubtype(
                slug="head_voice",
                label="ET-HV — Head and Voice Tremor",
                description="Predominant head (titubation) and/or voice tremor. May occur independently or with upper limb tremor. Limited pharmacological options. Botulinum toxin is often preferred for isolated head/voice ET.",
                key_features=["Head nodding tremor", "Voice tremulousness", "May affect social function", "Upper limb tremor variable"],
                primary_networks=[NetworkKey.SMN],
                secondary_networks=[NetworkKey.LIMBIC],
                preferred_modalities=[Modality.TMS, Modality.TDCS],
                tdcs_target="Cerebellar (Oz) bilateral tDCS",
                tps_target=None,
            ),
            PhenotypeSubtype(
                slug="task_specific",
                label="ET-TASK — Task-Specific Tremor",
                description="Tremor triggered primarily by specific tasks (writing, playing instrument). May be focal dystonia overlap. Functional but inconsistent — improves with alcohol in classic ET.",
                key_features=["Task-specific onset", "Writing tremor", "Alcohol responsiveness (if present)", "Variable at rest"],
                primary_networks=[NetworkKey.SMN, NetworkKey.CEN],
                secondary_networks=[NetworkKey.LIMBIC],
                preferred_modalities=[Modality.TDCS, Modality.TMS],
                tdcs_target="Contralateral M1 (C3 for right-hand dominant task tremor)",
                tps_target=None,
            ),
        ],

        assessment_tools=[
            AssessmentTool(
                scale_key="tetras",
                name="Essential Tremor Rating Assessment Scale",
                abbreviation="TETRAS",
                domains=["performance_subscale", "activities_of_daily_living", "limb_tremor", "head_tremor"],
                timing="baseline",
                evidence_pmid="22014098",
                notes="Primary ET-specific rating scale. TETRAS performance subscale (12 items) — videotaped tremor tasks. Validated for drug and DBS trial outcomes. MCID = not established; 25% improvement clinically meaningful.",
            ),
            AssessmentTool(
                scale_key="trs",
                name="Fahn-Tolosa-Marin Tremor Rating Scale",
                abbreviation="TRS",
                domains=["tremor_location", "tremor_severity", "handwriting", "drawing", "pouring"],
                timing="baseline",
                evidence_pmid=None,
                notes="Classic ET severity scale. Widely used in clinical trials. Part A: tremor location/severity at rest, posture, action. Part B: specific motor tasks. Part C: functional disability.",
            ),
            AssessmentTool(
                scale_key="quest",
                name="Quality of Life in Essential Tremor Questionnaire",
                abbreviation="QUEST",
                domains=["physical_activities", "psychosocial_impact", "communication", "eating_and_drinking", "hobbies"],
                timing="baseline",
                evidence_pmid="12439571",
                notes="ET-specific quality of life measure. 30 items, 5 domains. Most sensitive to patient-reported functional impact of tremor. Important for documenting treatment justification.",
            ),
        ],

        baseline_measures=[
            "TETRAS (primary ET severity assessment)",
            "TRS / Fahn-Tolosa-Marin Tremor Rating Scale",
            "QUEST (quality of life impact)",
            "Video tremor assessment (standard tremor tasks — pouring, handwriting, spiral drawing)",
            "SOZO PRS (tremor severity, daily function — 0-10)",
        ],

        followup_measures=[
            "TETRAS at 4-week and 8-week intervals",
            "Video tremor assessment at 4 weeks",
            "SOZO PRS at each session",
        ],

        inclusion_criteria=[
            "Clinical ET diagnosis per MDS criteria (bilateral postural/kinetic tremor, >=3 years duration)",
            "Inadequate response or intolerance to first-line pharmacotherapy (propranolol, primidone)",
            "TETRAS performance subscale >=10 (moderate tremor)",
            "Age 18-80 years",
            "Medically stable",
        ],

        exclusion_criteria=[
            "Parkinson's disease tremor (rest tremor dominant, asymmetric, bradykinesia) — exclude before ET treatment",
            "Drug-induced tremor — requires medication review",
            "Cerebellar ataxia syndromes",
            "DBS in situ (electrode safety concern)",
            "Post-DBS patients — stimulation parameter adjustment preferred",
        ],

        contraindications=SHARED_ABSOLUTE_CONTRAINDICATIONS,

        safety_notes=SHARED_SAFETY_NOTES + [
            make_safety(
                "precaution",
                "Distinguish ET from Parkinson tremor before starting — rest tremor, asymmetry, and bradykinesia suggest PD (different treatment target). Neurologist assessment recommended if uncertain.",
                "moderate",
                "ET vs. PD differential diagnosis — clinical safety",
            ),
            make_safety(
                "monitoring",
                "Video tremor assessment at baseline, week 4, and week 8. Standardized tasks: pouring water, handwriting, Archimedes spirals. Essential for documenting objective tremor change.",
                "moderate",
                "Tremor monitoring protocol",
            ),
        ],

        stimulation_targets=[
            StimulationTarget(
                modality=Modality.TMS,
                target_region="Cerebellum (lateral cerebellar cortex)",
                target_abbreviation="CB-TMS",
                laterality="bilateral",
                rationale="Cerebellar TMS (1 Hz inhibitory rTMS or continuous theta-burst) "
                          "disrupts Purkinje cell oscillatory output driving the CTC tremor circuit. "
                          "Quattrocchi et al. (2017) demonstrated cerebellar TMS reduced tremor "
                          "severity in ET. Bilateral cerebellar stimulation targets both sides "
                          "of the CTC loop. Lateral cerebellar hemispheres (below inion). OFF-LABEL.",
                protocol_label="TMS-ET-CEREB — Cerebellar Inhibition",
                evidence_level=EvidenceLevel.MEDIUM,
                off_label=True,
                eeg_canonical=["Oz", "O1", "O2"],
            ),
            make_tdcs_target(
                "Primary Motor Cortex (bilateral)", "M1", "bilateral",
                "Cathodal tDCS over contralateral M1 reduces motor cortex excitability and "
                "may reduce tremor amplitude by modulating the thalamo-cortical input to M1. "
                "Evidence is preliminary — pilot studies show modest but significant tremor "
                "reduction. Bilateral M1 cathodal tDCS targets the predominant upper limb "
                "tremor circuit. OFF-LABEL.",
                "C-ET-M1 — Motor Cortex Inhibition",
                EvidenceLevel.LOW, off_label=True,
                eeg_canonical=["C3", "C4"],
            ),
            make_tdcs_target(
                "Cerebellum", "CB-tDCS", "bilateral",
                "Cerebellar cathodal tDCS (electrodes over Oz area) may modulate Purkinje cell "
                "excitability and reduce CTC circuit oscillation. Investigational — limited "
                "published data specific to ET. Extrapolated from cerebellar tDCS research "
                "in ataxia and tremor. OFF-LABEL.",
                "C-ET-CEREB — Cerebellar tDCS",
                EvidenceLevel.LOW, off_label=True,
                eeg_canonical=["Oz"],
            ),
        ],

        protocols=[
            ProtocolEntry(
                protocol_id="TMS-ET-CEREBELLAR-INHIB",
                label="Cerebellar TMS — CTC Circuit Disruption",
                modality=Modality.TMS,
                target_region="Bilateral Cerebellar Hemispheres",
                target_abbreviation="CB bilateral",
                phenotype_slugs=["upper_limb", "head_voice"],
                network_targets=[NetworkKey.SMN],
                parameters={
                    "frequency": "1 Hz or cTBS (continuous theta-burst)",
                    "intensity": "90-100% RMT (if applicable to cerebellar cortex)",
                    "pulses_per_session": "900-1200",
                    "sessions": "10-15 over 3 weeks",
                    "target": "Lateral cerebellar hemispheres (3 cm lateral to inion)",
                    "laterality": "Bilateral or contralateral to dominant tremor side",
                },
                rationale="Cerebellar inhibitory TMS disrupts the Purkinje-dentate-thalamo-cortical "
                          "tremor loop. Quattrocchi et al. (2017) demonstrated cerebellar TMS "
                          "reduced tremor severity in ET patients. CTC circuit is accessible "
                          "via cerebellar surface stimulation. Best approach for ET when DBS "
                          "is not indicated or declined. OFF-LABEL.",
                evidence_level=EvidenceLevel.MEDIUM, off_label=True, session_count=12,
            ),
            ProtocolEntry(
                protocol_id="C-ET-M1-CATHODAL",
                label="M1 Cathodal tDCS — Motor Cortex Excitability Reduction",
                modality=Modality.TDCS,
                target_region="Contralateral Primary Motor Cortex",
                target_abbreviation="M1 cathodal",
                phenotype_slugs=["upper_limb", "task_specific"],
                network_targets=[NetworkKey.SMN],
                parameters={
                    "device": "Newronika HDCkit or PlatoScience",
                    "cathode": "C3 or C4 (contralateral M1)",
                    "anode": "Supraorbital contralateral or ipsilateral shoulder",
                    "intensity": "1.5-2.0 mA",
                    "duration": "20 min",
                    "sessions": "10-15 over 3 weeks",
                },
                rationale="Cathodal tDCS over contralateral M1 reduces cortical excitability, "
                          "modulating the thalamo-cortical oscillatory loop in ET. Pilot studies "
                          "demonstrate modest but significant tremor reduction. OFF-LABEL.",
                evidence_level=EvidenceLevel.LOW, off_label=True, session_count=12,
            ),
            ProtocolEntry(
                protocol_id="C-ET-CEREBELLAR-TDCS",
                label="Cerebellar tDCS — Purkinje Cell Modulation",
                modality=Modality.TDCS,
                target_region="Bilateral Cerebellum",
                target_abbreviation="CB-tDCS",
                phenotype_slugs=["upper_limb", "head_voice"],
                network_targets=[NetworkKey.SMN],
                parameters={
                    "device": "Newronika HDCkit or PlatoScience",
                    "cathode": "Oz (cerebellar inhibition) or anodal (cerebellar facilitation — depends on rationale)",
                    "anode": "Right or left shoulder reference",
                    "intensity": "1.5-2.0 mA",
                    "duration": "20 min",
                    "sessions": "10-15 over 3 weeks",
                    "note": "Cathodal Oz recommended for tremor suppression via Purkinje cell inhibition",
                },
                rationale="Cerebellar tDCS modulates Purkinje cell excitability, affecting downstream "
                          "dentate-thalamo-cortical oscillation. Cathodal cerebellar tDCS is hypothesized "
                          "to reduce CTC loop amplitude. Investigational for ET. OFF-LABEL.",
                evidence_level=EvidenceLevel.LOW, off_label=True, session_count=12,
                notes="Investigational. Limited published data specific to ET. Informed consent required.",
            ),
        ],

        symptom_network_mapping={
            "Postural Tremor": [NetworkKey.SMN],
            "Kinetic Tremor": [NetworkKey.SMN, NetworkKey.CEN],
            "Task Impairment": [NetworkKey.SMN, NetworkKey.CEN],
            "Head Tremor": [NetworkKey.SMN],
            "Anxiety/Depression": [NetworkKey.LIMBIC],
        },

        symptom_modality_mapping={
            "Postural Tremor": [Modality.TMS, Modality.TDCS],
            "Kinetic Tremor": [Modality.TMS, Modality.TDCS],
            "Task Impairment": [Modality.TMS, Modality.TDCS],
            "Head Tremor": [Modality.TMS, Modality.TDCS],
        },

        responder_criteria=[
            ">=25% reduction in TETRAS performance subscale score",
            "Clinically meaningful improvement in video tremor assessment",
            "Patient-reported improvement in daily function (QUEST, SOZO PRS)",
        ],

        non_responder_pathway=(
            "For non-responders at 4-week block:\n"
            "1. Reassess ET diagnosis — exclude PD tremor, drug-induced tremor\n"
            "2. Optimize pharmacotherapy — propranolol dose optimization before repeat block\n"
            "3. Switch cerebellar TMS approach — 1 Hz to cTBS or vice versa\n"
            "4. Neurosurgery referral for VIM-DBS assessment (refractory ET gold standard)\n"
            "5. HIFU (focused ultrasound VIM thalamotomy) — non-invasive stereotactic option for refractory ET"
        ),

        evidence_summary=(
            "Essential tremor neuromodulation: DBS VIM is gold standard (not covered here). "
            "Non-invasive approaches: cerebellar TMS has moderate evidence. "
            "Quattrocchi et al. (2017): cerebellar TMS reduced tremor severity in controlled study. "
            "M1 tDCS: preliminary positive data in small pilot studies. "
            "Overall: non-invasive neuromodulation for ET has emerging but limited evidence. "
            "Best for mild-moderate ET or patients declining DBS. "
            "| Evidence counts: TMS=50, tDCS=20. Best modalities: TMS (cerebellar), tDCS."
        ),

        evidence_gaps=[
            "Sham-controlled RCTs of cerebellar TMS in ET — sample size and replication needed",
            "Optimal TMS target — lateral cerebellum vs. cerebellar vermis",
            "Durability of non-invasive effects — tremor suppression after treatment block",
            "Combination cerebellar TMS + M1 tDCS for additive CTC circuit modulation",
            "HIFU VIM thalamotomy comparison with neuromodulation — referral pathway",
        ],

        references=[
            {
                "authors": "Quattrocchi G et al.",
                "year": 2017,
                "title": "Ripple transcranial magnetic stimulation in essential tremor",
                "journal": "Movement Disorders",
                "pmid": "27706955",
                "evidence_type": "rct",
            },
            {
                "authors": "Bhattacharyya KB",
                "year": 2016,
                "title": "Benign essential tremor: a review",
                "journal": "Annals of Indian Academy of Neurology",
                "pmid": "27429701",
                "evidence_type": "narrative_review",
            },
            {
                "authors": "Deuschl G et al.",
                "year": 1998,
                "title": "Consensus statement of the Movement Disorder Society on tremor",
                "journal": "Movement Disorders",
                "pmid": "9556143",
                "evidence_type": "consensus_statement",
            },
        ],

        overall_evidence_quality=EvidenceLevel.MEDIUM,

        clinical_tips=[
            "Always exclude PD tremor before ET treatment — rest tremor, asymmetry, or bradykinesia requires neurology review",
            "Cerebellar TMS is preferred for bilateral upper limb ET — target lateral cerebellar hemispheres bilaterally",
            "Alcohol responsiveness is a positive diagnostic sign for ET — document in history",
            "Video tremor assessment (pouring, Archimedes spirals, handwriting) at baseline is essential for objective outcome documentation",
            "VIM-DBS referral pathway should be discussed early with refractory moderate-severe ET patients — non-invasive options have limited evidence",
        ],

        governance_rules=SHARED_GOVERNANCE_RULES + [
            "Neurologist confirmation of ET diagnosis required before neuromodulation initiation",
            "Refractory ET patients should be informed of VIM-DBS as gold standard alternative",
        ],
    )
