'use strict';
module.exports = {
  conditionFull: "Attention-Deficit/Hyperactivity Disorder (ADHD)",
  conditionShort: "ADHD",
  conditionSlug: "adhd",
  documentNumber: "SOZO-ADHD-PROT-001",
  offLabelCoverText: "tDCS and TPS use in ADHD is INVESTIGATIONAL / OFF-LABEL. Emerging evidence supports tDCS targeting DLPFC with Level C evidence; TPS is exploratory.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level C emerging evidence for ADHD', 'Standard informed consent + off-label note'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; exploratory evidence for attention/ADHD', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/insomnia; off-label for ADHD', 'Standard informed consent + off-label note'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of ADHD (DSM-5 / ICD-11) by a qualified psychiatrist or neuropsychologist",
    "ADHD-RS-5 score or Conners-3 score indicating moderate-to-severe symptom burden at baseline",
    "Age 18–65 years (exceptions at Doctor discretion with documented rationale)",
    "Stable pharmacological treatment for ≥4 weeks prior to enrolment, or actively managed by prescribing Doctor",
    "Capacity to provide informed consent",
    "Willing and able to attend sessions as prescribed (note: session engagement strategies may be needed)",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Current active psychotic episode requiring urgent management",
    "Active mania or hypomanic episode (bipolar comorbidity — stabilise first)",
    "Active substance use disorder — sobriety and capacity assessment required",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Comorbid bipolar disorder — consult psychiatrist; avoid stimulant escalation; tDCS parameters with care",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment by Doctor",
    "Epilepsy or seizure history — formal risk assessment; note stimulant-seizure threshold interaction",
    "Pregnancy — taVNS/CES preferred; tDCS/TPS at Doctor discretion",
    "Autism spectrum disorder comorbidity — sensory considerations; adapted protocol",
    "Tic disorder (Tourette's) — monitor for tic exacerbation; tDCS parameters with care",
    "Substance use history — assess current use and its interaction with ADHD pharmacotherapy",
    "Anxiety comorbidity — adapt montage toward right hemisphere / combined bilateral approach",
    "Significant cardiovascular disease — coordination with cardiologist for stimulant use and vagal stimulation",
  ],

  overviewParagraph: "Attention-Deficit/Hyperactivity Disorder (ADHD) is a neurodevelopmental disorder characterised by persistent and impairing patterns of inattention, hyperactivity, and impulsivity. With a worldwide prevalence of approximately 5% in children and 2.5–3% in adults, ADHD represents one of the most common neurodevelopmental conditions affecting adults seeking clinical care. Core symptoms include sustained attention deficits, working memory impairment, executive dysfunction, impulse control deficits, and in many adults, emotional dysregulation. ADHD is associated with significant functional impairment in occupational performance, academic achievement, interpersonal relationships, and driving safety. Approximately 60% of childhood ADHD persists into adulthood. Stimulant medications (methylphenidate, amphetamine derivatives) are first-line evidence-based treatments, but 20–30% of patients are non-responders, and a substantial proportion experience intolerable side effects, poor tolerability with comorbidities, or are contraindicated — creating a significant unmet need for adjunctive neuromodulation approaches.",
  fnonNetworkParagraph: "ADHD is fundamentally a disorder of prefrontal-subcortical network dysregulation — specifically, hypoactivation of the Central Executive Network (CEN) driving insufficient top-down cognitive control, combined with hyperreactivity of the Default Mode Network (DMN) that inappropriately intrudes on goal-directed cognition. The FNON framework targets this core CEN-DMN dysregulation by upregulating left DLPFC excitability via tDCS and TPS, suppressing DMN intrusion via cathodal stimulation, and modulating the dopaminergic-noradrenergic axis via taVNS. This network dysregulation model is supported by Minzenberg et al. 2018 (289 citations) and Widge et al. 2025 (4 citations).",
  networkDisorderParagraphs: [
    "Neuroimaging research has robustly established ADHD as a disorder of prefrontal-striatal-cerebellar-parietal network organisation. Structural MRI studies demonstrate reduced cortical thickness and volume in DLPFC, ACC, caudate, and cerebellar regions — areas critical for executive function, inhibitory control, and timing. Functional connectivity analyses reveal impaired CEN activation during cognitive tasks, with the DLPFC showing insufficient recruitment during working memory, response inhibition, and sustained attention demands.",
    "The hallmark neuroimaging finding in ADHD is failure to appropriately suppress the Default Mode Network (DMN) during cognitive task performance. In healthy individuals, the CEN and DMN exhibit anti-correlated activity — task-positive CEN activation coincides with DMN deactivation. In ADHD, this anti-correlation is disrupted: DMN activity persists (or intrudes) during cognitive tasks, directly competing with executive processing and producing the characteristic attention lapses and mind-wandering of ADHD.",
    "Neurochemically, ADHD is characterised by hypodopaminergic and hypoadrenergic tone in prefrontal circuits — specifically, suboptimal D1/D2 receptor signalling in DLPFC that impairs signal-to-noise ratio for cognitive processing, and reduced NE modulation of prefrontal alpha-2A receptors that normally enhance sustained attention. The taVNS-LC-NE pathway directly addresses the noradrenergic component of ADHD, while tDCS DLPFC targets the cortical excitability deficit.",
  ],

  networkCitationKeys: [
    { authors: "Minzenberg et al.", year: 2018, citations: 289, title: "Neuromodulation of Attention", doi: "" },
    { authors: "Widge et al.", year: 2025, citations: 4, title: "Personalized EEG-guided brain stimulation targeting in major depression", doi: "" },
  ],
  fnonEvidenceStrength: "Strong",

  pathophysiologyText: "ADHD pathophysiology involves complex neurodevelopmental and neurochemical dysregulation. Core mechanisms include: (1) hypodopaminergic prefrontal-striatal circuitry — reduced D1 receptor stimulation in DLPFC impairs working memory and cognitive control; (2) hypoadrenergic PFC modulation — reduced NE alpha-2A receptor signalling impairs signal-to-noise ratio and sustained attention; (3) frontostriatal structural differences — reduced volume/thickness in caudate, DLPFC, ACC, and inferior frontal gyrus; (4) cerebellar timing deficits — impaired interval timing and motor coordination; (5) DMN dysregulation — failure to suppress default mode activity during cognitive demands; (6) reward circuitry hyposensitivity — reduced striatal dopaminergic reward signalling producing preference for immediate over delayed reward; and (7) emotional regulation deficits mediated by amygdala-prefrontal connectivity impairment. These mechanisms produce the heterogeneous inattentive, hyperactive-impulsive, and combined presentations of ADHD.",
  cardinalSymptoms: [
    ["Inattention", "Difficulty sustaining attention to tasks, making careless mistakes, difficulty organising, easily distracted by irrelevant stimuli, losing items", "Core criterion — inattentive/combined types (100% inattentive type)", "American Psychiatric Association, 2022"],
    ["Working Memory Deficits", "Reduced ability to hold and manipulate information in mind; forgetting instructions; losing track of ongoing activities; most consistent neuropsychological finding", "~85–90% of ADHD", "Martinussen et al., 2005; Willcutt et al., 2005"],
    ["Executive Dysfunction", "Impaired planning, organisation, time management, prioritisation, cognitive flexibility; metacognitive deficits affecting daily function", "~80–85%", "Willcutt et al., 2005; Barkley, 1997"],
    ["Impulsivity", "Acting without thinking; interrupting others; difficulty waiting; poor impulse inhibition; response inhibition deficits on neuropsychological testing", "Core criterion — hyperactive-impulsive/combined types", "American Psychiatric Association, 2022"],
    ["Hyperactivity", "Excessive motor restlessness; difficulty sitting still; fidgeting; in adults, may manifest as inner restlessness, excessive talking, difficulty relaxing", "Core criterion (children > adults)", "American Psychiatric Association, 2022"],
    ["Emotional Dysregulation", "Emotional impulsivity; low frustration tolerance; mood lability; quick temper; rejection sensitivity dysphoria; not in DSM-5 criteria but highly prevalent", "~70–80% of ADHD adults", "Barkley & Fischer, 2010; Shaw et al., 2014"],
    ["Sustained Attention Deficit", "Difficulty maintaining attention over time; performance variability (good in short bursts, poor over extended tasks); hyperfocus-inattention paradox", "~85%", "Sergeant, 2005"],
    ["Time Management Deficits", "Difficulty estimating time; chronic lateness; poor task prioritisation; 'time blindness'; impaired prospective memory", "~75% adults", "Barkley, 2011"],
    ["Procrastination", "Task avoidance especially for effortful or boring tasks; difficulty initiating tasks despite knowing importance; executive initiation deficit", "~70%", "Barkley et al., 2008"],
    ["Sleep Problems", "Difficulty falling asleep, irregular sleep-wake cycles, phase-delay tendency; sleep onset insomnia most common; associated with circadian rhythm dysregulation", "~70%", "Cortese et al., 2006"],
    ["Social/Interpersonal Difficulties", "Impulsive interruptions; missed social cues; poor turn-taking; relationship conflicts; difficulty reading long-term consequences", "~60–70%", "Nijmeijer et al., 2008"],
    ["Mind-Wandering", "Spontaneous task-unrelated thought during cognitive demands; DMN intrusion during goal-directed tasks; 'zoning out'", "~75%", "Smallwood et al., 2012"],
    ["Motivation Deficit", "Reduced intrinsic motivation for non-stimulating tasks; difficulty maintaining effort without immediate reward; delay aversion; dopaminergic reward circuit", "~70%", "Sonuga-Barke, 2003"],
  ],
  standardGuidelinesText: [
    "Current evidence-based guidelines for ADHD in adults (NICE 2018, BAP 2014, CADDRA 2020, WFADHD 2021) position stimulant medications as first-line pharmacotherapy. Methylphenidate (Ritalin, Concerta) and amphetamine-based medications (lisdexamfetamine, mixed amphetamine salts) have robust evidence for reducing core ADHD symptoms with large effect sizes (Cohen's d ≈ 0.7–0.9). Non-stimulant alternatives include atomoxetine (SNRI mechanism, Level A evidence), guanfacine XR (alpha-2A agonist, particularly for emotional dysregulation and hyperactivity), and bupropion (Level B).",
    "Cognitive-behavioural therapy adapted for adult ADHD (CBT-ADHD) is recommended as an adjunct to medication, particularly targeting organisation, time management, and emotional regulation. NICE recommends structured ADHD coaching and psychological interventions alongside pharmacotherapy. Environmental accommodations, psychoeducation, and occupational therapy input are important components of comprehensive care.",
    "SOZO FNON protocols target the neurophysiological underpinnings of ADHD — specifically DLPFC hypoactivation and CEN-DMN dysregulation — to complement pharmacotherapy. The Doctor coordinates FNON timing with medication schedules (particularly stimulant peak plasma levels) to optimise synergistic effects. Session activities paired with tDCS/TPS involve working memory and executive function tasks to leverage stimulation-enhanced neuroplasticity for functional gains.",
  ],

  fnonFrameworkParagraph: "The FNON framework for ADHD targets the CEN-DMN dysregulation that underpins inattention and executive dysfunction. Left DLPFC anodal tDCS is the evidence-based primary target, upregulating prefrontal excitability to enhance working memory, sustained attention, and inhibitory control. TPS provides deep penetration into the prefrontal-striatal circuit. DMN suppression via cathodal Pz reduces the inappropriate default mode intrusion characteristic of ADHD. taVNS augments noradrenergic modulation of prefrontal circuits via the LC pathway, mimicking one mechanism of action of atomoxetine.",
  keyBrainRegions: [
    ["Left Dorsolateral Prefrontal Cortex (DLPFC)", "Hypoactivation; impaired working memory, sustained attention, cognitive flexibility; primary ADHD cortical target", "PRIMARY TARGET: anodal tDCS F3 (left DLPFC) — primary evidence-based approach for ADHD across multiple studies; TPS F3 region", "Bikson et al., 2016; Breitling et al., 2016; Salehinejad et al., 2019"],
    ["Right Inferior Frontal Gyrus (rIFG)", "Impaired response inhibition; reduced stop-signal capacity; impulsivity substrate; go/no-go task deficits", "Anodal tDCS F4/F8 region for inhibition; combined with response inhibition tasks during stimulation", "Aron & Poldrack, 2006; Rubia et al., 2011"],
    ["Anterior Cingulate Cortex (ACC)", "Impaired conflict monitoring; reduced error detection; diminished cognitive control signal; theta deficit", "tDCS Fz montage; taVNS modulates ACC via vagal-cingulate pathway; important for inhibitory control", "Bush et al., 1999; Posner et al., 2014"],
    ["Caudate Nucleus / Striatum", "Reduced volume and dopaminergic activation; impaired reward learning; delay aversion; timing impairment; motivation deficit", "Indirect modulation via DLPFC-striatal upregulation; TPS deep targeting of fronto-striatal circuit", "Castellanos et al., 2002; Nigg & Casey, 2005"],
    ["Posterior Parietal Cortex (PPC)", "Impaired spatial attention; reduced parietal CEN activation during working memory; attentional control network deficit", "Cathodal Pz for DMN suppression; combined with attention tasks; bilateral DLPFC-PPC protocol for combined-type ADHD", "Dosenbach et al., 2008"],
    ["Supplementary Motor Area (SMA)", "Motor response inhibition; impaired motor timing and sequencing; hyperactivity substrate; motor impulsivity", "TPS SMA targeting for hyperactive-impulsive phenotype; combined with motor inhibition tasks", "Mostofsky & Simmonds, 2008"],
    ["Cerebellum", "Timing deficits; impaired interval timing; motor coordination; cognitive-affective cerebellar contributions", "TPS cerebellar targeting for timing-prominent phenotype; tDCS Cbz for cerebellar-frontal modulation", "Durston et al., 2007; Stoodley, 2014"],
    ["Orbitofrontal Cortex (OFC)", "Impaired reward valuation; poor consequence estimation; decision-making deficits; delay discounting", "TPS OFC/vmPFC targeting for reward and motivation phenotype; combined with reward-based working memory tasks", "Barkley, 1997; Volkow et al., 2011"],
    ["Default Mode Network Hubs (mPFC/PCC)", "Failure to deactivate during cognitive tasks; DMN intrusion competes with CEN task-positive processing; primary source of inattention", "Cathodal tDCS Pz (PCC hub suppression) combined with anodal F3 (simultaneous CEN-DMN push-pull)", "Castellanos et al., 2008; Weissman et al., 2006"],
  ],
  additionalBrainStructures: [
    ["Locus Coeruleus (LC)", "Hypoadrenergic NE tone in prefrontal circuits; reduced alpha-2A receptor stimulation; impaired signal-to-noise for attention", "taVNS activates NTS→LC pathway — noradrenergic mechanism paralleling atomoxetine; enhances prefrontal S/N ratio", "Berridge & Waterhouse, 2003; Arnsten, 2011"],
    ["Ventral Tegmental Area (VTA)", "Hypodopaminergic mesolimbic pathway; reduced reward anticipation; delay aversion; motivation deficit", "Indirect modulation via DLPFC upregulation and taVNS; TPS deep mesolimbic targeting for motivational phenotype", "Volkow et al., 2011; Sagvolden et al., 2005"],
    ["Basal Ganglia (Caudate/Putamen/GPi)", "Reduced volume; impaired motor inhibition; habit learning deficits; timing impairment; critical fronto-striatal ADHD circuit", "DLPFC anodal tDCS modulates fronto-striatal circuit; TPS deep caudate targeting", "Castellanos et al., 2002"],
    ["Thalamus", "Impaired thalamo-cortical filtering; reduced gating of irrelevant stimuli; hyperarousal paradox (underdampened thalamic relay)", "TPS thalamic indirect targeting; taVNS modulates thalamo-cortical synchrony; combined reduces irrelevant stimulus intrusion", "Sarter et al., 2001"],
    ["Amygdala", "Emotional dysregulation substrate; impaired prefrontal-amygdala top-down regulation; rejection sensitivity dysphoria; heightened emotional reactivity", "Indirect modulation via DLPFC anodal tDCS; TPS limbic targeting for emotional dysregulation phenotype", "Shaw et al., 2014"],
    ["Cerebellum Dentate Nucleus", "Timing circuit; coordination of attention network; cerebello-thalamo-cortical pathway impaired in ADHD", "TPS cerebellar deep targeting; tDCS Cbz electrode; addresses timing and sequencing deficits", "Durston et al., 2007"],
    ["Frontal Eye Fields (FEF)", "Oculomotor control; impaired sustained visual attention; saccadic inhibition deficits in ADHD", "Indirect modulation via DLPFC stimulation; combined with continuous performance tasks using visual attention demands", "Ross et al., 1994"],
  ],
  keyFunctionalNetworks: [
    ["Central Executive Network (CEN)", "DLPFC, PPC, lateral PFC, anterior PFC, FEF", "Hypoactivation; impaired working memory, task switching, inhibitory control; primary ADHD network deficit", "PRIMARY TARGET: anodal tDCS F3 (left DLPFC); TPS DLPFC; bilateral F3/F4 for combined type; HDCkit for TRD-ADHD", "Barkley, 1997; Arnsten, 2011"],
    ["Default Mode Network (DMN)", "mPFC, PCC, precuneus, angular gyrus, hippocampus", "Failure to deactivate during cognitive tasks; inappropriate intrusion during goal-directed processing; primary inattention substrate", "Cathodal tDCS Pz (PCC suppression); TPS DMN hubs; concurrent cognitive tasks to amplify DMN suppression", "Castellanos et al., 2008; Weissman et al., 2006"],
    ["Salience Network (SN)", "dACC, insula, amygdala", "Impaired task-relevance detection; failure to trigger appropriate CEN-DMN switching; hyperactivity in emotional subtype", "tDCS Fz (dACC); taVNS modulates SN-insula via NTS pathway; combined CEN upregulation + SN normalisation", "Menon & Uddin, 2010"],
    ["Fronto-Parietal Network (FPN)", "Lateral PFC, inferior parietal lobule, dACC, precuneus", "Reduced moment-to-moment cognitive control; impaired dynamic task adjustment; variable attention performance", "Combined bilateral DLPFC tDCS + parietal TPS; concurrent sustained attention tasks", "Dosenbach et al., 2008"],
    ["Reward/Motivation Network", "Ventral striatum, OFC, vmPFC, VTA, amygdala", "Hyposensitivity to delayed reward; impaired value-based decision-making; delay aversion; insufficient intrinsic motivation", "TPS deep mesolimbic + OFC; indirect DLPFC tDCS modulation; reward-contingent task pairing", "Sonuga-Barke, 2003; Volkow et al., 2011"],
    ["Attention Network", "FEF, IPS, TPJ, right DLPFC, right inferior frontal gyrus", "Sustained attention deficit; impaired alerting, orienting, and executive attention components", "Right DLPFC anodal (F4) for alerting/orienting attention; combined with continuous performance tasks during tDCS", "Posner & Petersen, 1990"],
    ["Cerebellar-Frontal Network", "Cerebellum, thalamus, DLPFC, SMA, motor cortex", "Timing deficits; impaired interval timing; motor coordination; cerebellar-thalamo-cortical dysfunction", "TPS cerebellar + DLPFC combined; tDCS Cbz + F3; timing-based tasks concurrent", "Stoodley, 2014; Durston et al., 2007"],
  ],
  networkAbnormalities: "ADHD is characterised by CEN hypoactivation (insufficient prefrontal executive control), DMN failure-to-deactivate (inappropriate default mode intrusion during tasks), disrupted CEN-DMN anti-correlation (core inattention mechanism), and hypodopaminergic/hypoadrenergic prefrontal-striatal-cerebellar circuits.",
  conceptualFramework: "SOZO FNON ADHD protocol targets: (1) Upregulate left DLPFC CEN via anodal tDCS/TPS; (2) Suppress DMN intrusion via cathodal Pz; (3) Augment noradrenergic LC modulation via taVNS; (4) Pair stimulation with working memory and executive function cognitive tasks to leverage stimulation-enhanced plasticity.",

  clinicalPhenotypes: [
    ["Inattentive-Predominant (ADHD-I)", "Predominantly inattentive; working memory and CEN deficit primary; mild hyperactivity; responds to left DLPFC upregulation + cognitive training", "American Psychiatric Association, 2022"],
    ["Hyperactive-Impulsive Dominant (ADHD-HI)", "Motor hyperactivity and impulsivity dominant; rIFG inhibition deficit; SMA/motor circuit; responds to inhibitory control tasks + rIFG/SMA targeting", "American Psychiatric Association, 2022"],
    ["Combined Type (ADHD-C)", "Full symptom profile; bilateral CEN-DMN dysregulation; requires bilateral DLPFC + DMN suppression; most common adult presentation", "American Psychiatric Association, 2022"],
    ["Emotional Dysregulation Dominant", "Rejection sensitivity dysphoria, emotional impulsivity, mood lability; amygdala-prefrontal disconnect; bilateral tDCS + taVNS for limbic modulation", "Barkley & Fischer, 2010; Shaw et al., 2014"],
    ["Motivation-Anhedonia Subtype", "Profound motivation deficit, delay aversion, anhedonia; reward circuit hyposensitivity primary; TPS deep mesolimbic targeting required", "Sonuga-Barke, 2003"],
    ["Sleep-Disrupted Subtype", "Phase-delay sleep disorder; severe sleep onset insomnia; chronobiology disruption; CES evening protocol; circadian intervention co-managed", "Cortese et al., 2006"],
    ["Treatment-Resistant ADHD", "Non-responder to ≥2 stimulant trials; non-stimulant failure; requires maximal bilateral DLPFC + deep TPS; consider comorbidity review", "Pliszka, 2007"],
    ["ADHD with Anxiety Comorbidity", "Both ADHD and anxiety features; right DLPFC combined; care with stimulant dosing; taVNS + CES for autonomic regulation", "van Steensel et al., 2011"],
    ["ADHD with Autism Spectrum Features", "Neurodevelopmental overlap; sensory sensitivities; adapted parameters; longer acclimatisation; lower intensity; structured predictable sessions", "Leitner, 2014"],
  ],
  symptomNetworkMapping: [
    ["Inattention", "CEN hypoactivation", "DMN intrusion failure-to-deactivate", "tDCS F3 anodal + Pz cathodal", "Sustained attention task concurrent"],
    ["Working Memory Deficit", "CEN hypoactivation", "DLPFC-PPC circuit hypofunction", "tDCS F3 anodal (primary)", "N-back or verbal working memory task during stimulation"],
    ["Impulsivity", "rIFG inhibition deficit", "SN-SMA hyperreactivity", "tDCS F4/F8 anodal", "Stop-signal or go/no-go task concurrent"],
    ["Emotional Dysregulation", "Amygdala-PFC disconnect", "Limbic hyperreactivity", "tDCS bilateral + taVNS", "Emotion regulation training concurrent"],
    ["Hyperactivity", "Motor circuit overactivation", "SMA/basal ganglia hyperactivity", "tDCS SMA cathodal or rIFG anodal", "Motor inhibition task concurrent"],
    ["Mind-Wandering", "DMN failure-to-deactivate", "CEN-DMN anti-correlation loss", "Cathodal Pz + anodal F3 (push-pull)", "Mindfulness attention task concurrent"],
    ["Motivation Deficit", "Reward network hyposensitivity", "Mesolimbic dopamine deficit", "TPS deep mesolimbic + DLPFC", "Reward-contingent working memory training"],
    ["Time Management", "Cerebellar-frontal timing deficit", "SMA/caudate impairment", "tDCS F3 + TPS cerebellar", "Interval timing task concurrent"],
    ["Sleep Disturbance", "Circadian + autonomic dysregulation", "LC hyperactivation at night", "CES evening protocol", "Sleep hygiene protocol concurrent"],
    ["Executive Dysfunction", "CEN hypoactivation", "Fronto-parietal network deficit", "tDCS bilateral DLPFC + TPS", "Planning/organisation task concurrent"],
  ],
  montageSelectionRows: [
    ["Inattentive-predominant (left DLPFC focus)", "Anodal F3, cathodal Pz — 2mA 20min"],
    ["Combined type (bilateral DLPFC + DMN)", "Anodal F3+F4, cathodal Pz bilateral — HDCkit 2mA"],
    ["Hyperactive-impulsive (rIFG inhibition)", "Anodal F4/F8, cathodal Fz — 2mA 20min"],
    ["Emotional dysregulation (limbic-prefrontal)", "tDCS bilateral + taVNS — combined session"],
    ["Treatment-resistant ADHD (maximal)", "HDCkit bilateral F3+F4 anodal + TPS DLPFC"],
    ["TPS — inattentive phenotype", "NEUROLITH® left DLPFC — 0.2mJ/mm² 4000 pulses"],
    ["TPS — combined type / bilateral", "NEUROLITH® bilateral DLPFC — 0.2mJ/mm² 4000 pulses each"],
    ["taVNS — noradrenergic augmentation", "Left cymba conchae 0.5mA 30min (pre-session)"],
    ["CES — sleep-disrupted subtype", "Alpha-Stim AID 0.5mA 60min evening"],
    ["DMN suppression add-on", "Cathodal Pz combined with any frontal anodal montage"],
    ["Motivation-anhedonia phenotype", "TPS bilateral DLPFC + deep mesolimbic 6000 pulses"],
    ["Anxiety-comorbid ADHD", "Bilateral tDCS F3+F4 + taVNS (CEN + autonomic)"],
    ["Maintenance phase", "Reduce to 2× weekly; home tDCS device or daily CES"],
  ],
  polarityPrincipleText: "In ADHD, polarity selection prioritises left DLPFC anodal upregulation as primary (CEN excitability enhancement) combined with Pz cathodal (DMN suppression). For hyperactive-impulsive phenotype, right inferior frontal gyrus (F4/F8) anodal targeting enhances inhibitory control. The push-pull montage (anodal frontal + cathodal Pz) is the most physiologically coherent ADHD approach.",
  polarityTable: [
    ["Anodal F3 (left DLPFC)", "Upregulates left prefrontal CEN; working memory, sustained attention, cognitive flexibility — primary ADHD target"],
    ["Cathodal Pz", "Suppresses DMN posterior hub (PCC/precuneus); reduces inappropriate default mode intrusion during cognitive tasks"],
    ["Anodal F4 (right DLPFC)", "Enhances inhibitory control for hyperactive-impulsive phenotype; right IFG and SMA inhibition circuit upregulation"],
    ["Anodal bilateral F3+F4", "Combined type ADHD and treatment-resistant cases; maximises bilateral CEN upregulation"],
    ["taVNS left cymba", "Noradrenergic augmentation via NTS→LC pathway; enhances prefrontal signal-to-noise; mimics atomoxetine mechanism"],
  ],

  classicTdcsProtocols: [
    ["C1", "Inattention / working memory", "F3 (left DLPFC)", "Pz", "2mA 20min, 10 sessions", "Level C"],
    ["C2", "Inhibition / impulsivity", "F4/F8 (right IFG)", "Fz", "2mA 20min, 10 sessions", "Emerging"],
    ["C3", "Combined type bilateral", "F3+F4 bilateral anodal", "Bilateral temporal cathodal", "2mA 20min, 10 sessions", "Emerging"],
    ["C4", "DMN suppression focus", "F3 anodal", "Pz cathodal (push-pull)", "2mA 20min", "Level C"],
    ["C5", "Emotional dysregulation", "F3+F4 bilateral", "Temporal bilateral", "2mA 20min + taVNS", "Exploratory"],
    ["C6", "Motivation / reward", "F3 anodal", "Pz cathodal", "2mA 20min + reward task", "Exploratory"],
    ["C7", "Hyperactivity-motor", "F4 anodal + SMA cathodal", "Fz", "1.5mA 20min", "Exploratory"],
    ["C8", "Anxiety-comorbid ADHD", "F3+F4 bilateral", "Bilateral temporal", "1.5mA 20min", "Exploratory"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Inattentive-Predominant", "CEN hypoactivation + DMN intrusion", "F3 anodal + Pz cathodal (push-pull)", "Simultaneous CEN upregulation and DMN suppression"],
    ["F2", "Hyperactive-Impulsive", "rIFG inhibition deficit", "F4/F8 anodal + Fz cathodal", "Upregulate right inhibitory control network"],
    ["F3", "Combined Type", "Bilateral CEN hypoactivation", "HDCkit F3+F4 bilateral anodal + Pz cathodal", "Maximal bilateral CEN upregulation with DMN suppression"],
    ["F4", "Emotional Dysregulation", "Amygdala-PFC disconnect", "F3+F4 bilateral + taVNS", "Bilateral PFC + limbic-autonomic combined modulation"],
    ["F5", "Motivation-Anhedonia", "Reward circuit hyposensitivity", "F3 anodal + TPS deep mesolimbic", "Prefrontal + subcortical reward circuit targeting"],
    ["F6", "Treatment-Resistant ADHD", "Bilateral CEN + reward deficit", "HDCkit bilateral + TPS bilateral DLPFC + taVNS", "Maximal multi-modal targeting"],
  ],
  classicTpsProtocols: [
    ["T1", "Inattention / working memory", "Left DLPFC (F3 region)", "0.2mJ/mm²", "4000 pulses", "Emerging"],
    ["T2", "Combined type", "Bilateral DLPFC", "0.2mJ/mm²", "4000 pulses per side", "Exploratory"],
    ["T3", "Inhibition / impulsivity", "Right DLPFC/IFG (F4 region)", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T4", "Reward/motivation deficit", "DLPFC + deep mesolimbic", "0.25mJ/mm²", "5000 pulses combined", "Exploratory"],
    ["T5", "TRD-ADHD / holocranial", "Bilateral DLPFC + deep", "0.2mJ/mm²", "6000 pulses", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Inattentive-Predominant", "CEN hypoactivation", "Left DLPFC (F3) 0.2mJ/mm² × 4000 pulses", "Deep left prefrontal — sustained attention and working memory circuit"],
    ["FT2", "Hyperactive-Impulsive", "rIFG inhibition deficit", "Right DLPFC/IFG (F4/F8) 0.2mJ/mm² × 3000 pulses", "Deep right inhibitory control network targeting"],
    ["FT3", "Combined Type", "Bilateral CEN", "Bilateral DLPFC 0.2mJ/mm² × 4000 pulses each", "Bilateral deep prefrontal CEN targeting"],
    ["FT4", "Emotional Dysregulation", "Amygdala-PFC + CEN deficit", "Bilateral DLPFC + limbic deep 0.2mJ/mm² × 5000", "Deep prefrontal-limbic combined targeting for emotional dysregulation"],
    ["FT5", "Motivation-Anhedonia", "Reward network", "DLPFC + deep mesolimbic 0.25mJ/mm² × 5000", "Deep reward circuit targeting — striatum/OFC/mPFC"],
    ["FT6", "Treatment-Resistant", "Multi-network", "Bilateral DLPFC + deep limbic 0.2mJ/mm² × 6000 holocranial", "Maximum multi-network normalisation"],
    ["FT7", "Sleep-Disrupted Subtype", "Circadian + CEN combined", "Left DLPFC 0.15mJ/mm² × 3000 (daytime) + evening CES", "Daytime prefrontal priming + evening autonomic regulation"],
    ["FT8", "ADHD with Anxiety", "Bilateral CEN + autonomic", "Bilateral DLPFC 0.2mJ/mm² × 4000 + taVNS", "Combined ADHD and anxiety network targeting"],
    ["FT9", "Maintenance Protocol", "Sustained CEN upregulation", "Left DLPFC 0.2mJ/mm² × 2000 monthly", "Monthly deep maintenance stimulation"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Inattentive-Predominant (ADHD-I)",
      combinations: [
        ["S — Stabilise", "taVNS 30min (pre-session) — noradrenergic priming via NTS-LC pathway", "Enhance prefrontal signal-to-noise ratio before cortical stimulation; atomoxetine-like mechanism"],
        ["O — Optimise", "tDCS F3 anodal + Pz cathodal 2mA 20min — push-pull CEN-DMN", "Simultaneously upregulate left DLPFC and suppress PCC; maximum push-pull for inattention"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 4000 pulses — deep CEN penetration", "Deep left prefrontal working memory and sustained attention circuit"],
        ["O — Outcome", "N-back task concurrent during tDCS + CES evening — consolidate", "Working memory training during primed state; evening CES for sleep and next-day attention readiness"],
      ],
    },
    {
      phenotype: "Hyperactive-Impulsive (ADHD-HI)",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 30min — reduce motor restlessness baseline", "Lower sympathetic arousal; reduce hyperactivity threshold before targeted stimulation"],
        ["O — Optimise", "tDCS F4/F8 anodal 2mA 20min — right IFG inhibitory control", "Upregulate right hemisphere inhibition network; response inhibition enhancement"],
        ["Z — Zone", "TPS right DLPFC/IFG 0.2mJ/mm² 3000 pulses — deep inhibitory circuit", "Deep right prefrontal inhibitory control network"],
        ["O — Outcome", "Stop-signal task concurrent + taVNS after session — consolidate", "Response inhibition training during primed state; taVNS for noradrenergic consolidation"],
      ],
    },
    {
      phenotype: "Combined Type (ADHD-C)",
      combinations: [
        ["S — Stabilise", "taVNS 30min — noradrenergic priming for bilateral stimulation", "Prepare LC-PFC axis for maximal bilateral cortical stimulation"],
        ["O — Optimise", "HDCkit F3+F4 bilateral anodal 2mA 20min + Pz cathodal", "Maximal bilateral CEN upregulation with DMN suppression"],
        ["Z — Zone", "TPS bilateral DLPFC 0.2mJ/mm² 4000 pulses each side", "Deep bilateral prefrontal CEN targeting"],
        ["O — Outcome", "Dual N-back task concurrent + CES evening — daily home practice", "High-demand cognitive training during bilateral priming; daily home CES"],
      ],
    },
    {
      phenotype: "Emotional Dysregulation Dominant",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 30min — combined autonomic-limbic stabilisation", "Establish autonomic equilibrium before limbic-prefrontal stimulation"],
        ["O — Optimise", "tDCS F3+F4 bilateral anodal 2mA 20min — bilateral PFC", "Upregulate bilateral prefrontal control of amygdala and limbic reactivity"],
        ["Z — Zone", "TPS bilateral DLPFC + deep limbic 0.2mJ/mm² 5000 pulses", "Deep bilateral prefrontal-limbic circuit normalisation"],
        ["O — Outcome", "DBT emotion regulation skills concurrent — mindfulness + distress tolerance", "Emotion regulation therapy paired with primed limbic-prefrontal circuit"],
      ],
    },
    {
      phenotype: "Motivation-Anhedonia Subtype",
      combinations: [
        ["S — Stabilise", "taVNS 30min — noradrenergic + dopaminergic priming via LC", "Prepare reward circuit via NTS-LC-VTA indirect pathway"],
        ["O — Optimise", "tDCS F3 anodal + Pz cathodal 2mA 20min", "Primary prefrontal-reward pathway upregulation"],
        ["Z — Zone", "TPS DLPFC + deep mesolimbic 0.25mJ/mm² 5000 pulses", "Deep reward circuit — OFC/vmPFC/ventral striatum indirect targeting"],
        ["O — Outcome", "Reward-contingent N-back task + behavioural activation plan — consolidate", "Pair stimulation with explicit reward to reinforce dopaminergic reward learning"],
      ],
    },
    {
      phenotype: "Sleep-Disrupted Subtype",
      combinations: [
        ["S — Stabilise", "taVNS afternoon 20min — pre-evening autonomic preparation", "Shift autonomic balance toward parasympathetic dominance before sleep window"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min (daytime) — address daytime inattention", "Daytime DLPFC priming; improve daytime function to reduce evening hyperarousal from task accumulation"],
        ["Z — Zone", "CES 0.5mA 60min evening — primary sleep facilitation modality", "Evening autonomic downregulation; chronobiological reset"],
        ["O — Outcome", "Sleep restriction therapy + chronotherapy concurrent — consolidate", "Evidence-based sleep consolidation with phase advance for ADHD circadian delay"],
      ],
    },
    {
      phenotype: "Treatment-Resistant ADHD",
      combinations: [
        ["S — Stabilise", "taVNS 40min + CES 30min — maximal autonomic-noradrenergic priming", "Establish maximal noradrenergic and autonomic baseline for intensive bilateral stimulation"],
        ["O — Optimise", "HDCkit bilateral F3+F4 anodal 2mA 20min + Pz cathodal", "Maximum bilateral CEN upregulation with DMN suppression"],
        ["Z — Zone", "TPS bilateral DLPFC 0.2mJ/mm² 6000 pulses total + deep limbic", "Maximum deep bilateral network normalisation"],
        ["O — Outcome", "Intensive cognitive training concurrent + daily home CES + coaching", "Maximum dose cognitive training; daily home CES; ADHD coaching for functional generalisation"],
      ],
    },
    {
      phenotype: "ADHD with Anxiety Comorbidity",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — anxiety-first stabilisation before cognitive stimulation", "Reduce anxiety arousal to prevent anxiety exacerbation during DLPFC stimulation"],
        ["O — Optimise", "tDCS F3+F4 bilateral 1.5mA 20min — bilateral but moderate intensity", "Balanced bilateral approach addressing both attention (left) and anxiety (right)"],
        ["Z — Zone", "TPS bilateral DLPFC 0.15mJ/mm² 3000 pulses — conservative for anxiety", "Conservative deep stimulation; avoid intensity levels that worsen anxiety"],
        ["O — Outcome", "CBT-ADHD with anxiety module concurrent + taVNS", "Integrated ADHD and anxiety CBT; taVNS for combined noradrenergic modulation"],
      ],
    },
    {
      phenotype: "ADHD with Autism Spectrum Features",
      combinations: [
        ["S — Stabilise", "CES 0.25mA 30min — gentle autonomic stabilisation; sensory acclimatisation", "Low-intensity approach; allow acclimatisation to sensation; extended preparatory phase"],
        ["O — Optimise", "tDCS F3 anodal 1mA 15min — reduced parameters for sensory sensitivity", "Conservative stimulation; slower parameter build-up; assess tolerance each session"],
        ["Z — Zone", "TPS left DLPFC 0.15mJ/mm² 2000 pulses — adapted parameters", "Conservative TPS adapted for sensory processing differences"],
        ["O — Outcome", "Social communication training + structured predictable session format — consolidate", "Structured, predictable, sensory-adapted session with social skills targeting"],
      ],
    },
  ],

  taskPairingRows: [
    ["N-back Working Memory Task", "Inattentive / combined type", "tDCS F3 anodal active", "1-3 back verbal/spatial; increases with performance"],
    ["Stop-Signal Task", "Hyperactive-impulsive", "tDCS F4 anodal active", "Response inhibition training during primed rIFG"],
    ["Sustained Attention (Continuous Performance)", "Inattentive / combined", "tDCS F3 active + Pz cathodal", "Sustained vigilance decrement reduction with DLPFC priming"],
    ["Dual N-Back (Combined Demand)", "Combined type / TRD-ADHD", "TPS post-session", "High-demand dual task; maximises post-TPS plasticity window"],
    ["Reward-Contingent Working Memory", "Motivation-anhedonia subtype", "tDCS F3 active", "Explicit reward tied to performance; reinforces dopaminergic learning"],
    ["Emotion Regulation Task (IERT)", "Emotional dysregulation", "tDCS bilateral active", "Explicit emotion labelling and regulation strategy practice"],
  ],
  outcomeMeasures: "Primary: ADHD-RS-5 (Adult; session 1, 5, 10, 1-month follow-up), Conners' Adult ADHD Rating Scale (CAARS). Secondary: digit span forward/backward (working memory), Trail Making Test A/B (processing speed/shifting), Continuous Performance Test (CPT; sustained attention), GAD-7 (anxiety comorbidity monitoring), PSQI (sleep quality), Sheehan Disability Scale (functional impairment), patient self-report on daily ADHD impact. Neurophysiological (optional): resting-state EEG theta/alpha ratios, go/no-go ERP P3 amplitude.",

  medicationSectionTitle: "Pharmacotherapy Context for ADHD",
  medicationSectionText: "First-line pharmacotherapy for adult ADHD includes stimulant medications: methylphenidate (Ritalin LA, Concerta) and amphetamine derivatives (lisdexamfetamine/Vyvanse, mixed amphetamine salts). Non-stimulant alternatives include atomoxetine (SNRI mechanism; Level A evidence; particularly useful for anxiety comorbidity or stimulant intolerance), guanfacine XR (alpha-2A agonist; particularly for emotional dysregulation and hyperactivity), and bupropion XL (Level B). The Doctor coordinates FNON timing with stimulant schedules — tDCS during stimulant peak plasma concentration may show synergistic DLPFC upregulation effects. Atomoxetine has a mechanistic parallel with taVNS (both augment LC-NE prefrontal signalling), making their combination a theoretically well-grounded complementary approach. Monitor cardiovascular parameters in patients on stimulants receiving taVNS.",

  references: {
    foundational: [
      "Barkley RA. (1997). Behavioral inhibition, sustained attention, and executive functions: Constructing a unifying theory of ADHD. Psychol Bull, 121(1), 65–94. doi:10.1037/0033-2909.121.1.65",
      "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR). APA Publishing.",
      "Willcutt EG, Doyle AE, Nigg JT, Faraone SV, Pennington BF. (2005). Validity of the executive function theory of attention-deficit/hyperactivity disorder: A meta-analytic review. Biol Psychiatry, 57(11), 1336–1346. doi:10.1016/j.biopsych.2005.02.006",
      "Castellanos FX, Lee PP, Sharp W, et al. (2002). Developmental trajectories of brain volume abnormalities in children and adolescents with attention-deficit/hyperactivity disorder. JAMA, 288(14), 1740–1748. doi:10.1001/jama.288.14.1740",
      "Sonuga-Barke EJ. (2003). The dual pathway model of AD/HD: An elaboration of neuro-developmental characteristics. Neurosci Biobehav Rev, 27(7), 593–604. doi:10.1016/j.neubiorev.2003.08.005",
      "Arnsten AF. (2011). Catecholamine influences on dorsolateral prefrontal cortical networks. Biol Psychiatry, 69(12), e89–99. doi:10.1016/j.biopsych.2011.01.027",
    ],
    tdcs: [
      "Salehinejad MA, Ghanavati E, Rashid MH, Nitsche MA. (2021). Hot and cold executive functions in the brain: A prefrontal-cingular network. Brain Neurosci Adv, 5, 23982128211007769. doi:10.1177/23982128211007769",
      "Breitling C, Zaehle T, Dannhauer M, et al. (2016). Improving interference control in ADHD patients with transcranial direct current stimulation (tDCS). Front Cell Neurosci, 10, 72. doi:10.3389/fncel.2016.00072",
      "Allenby C, Falcone M, Wileyto EP, et al. (2018). Transcranial direct current stimulation reduces impulsive choice for nicotine and money in tobacco-dependent adults. Brain Stimul, 11(2), 616–623. doi:10.1016/j.brs.2018.01.001",
      "Nejati V, Salehinejad MA, Nitsche MA, Najian A, Javadi AH. (2020). Transcranial direct current stimulation improves executive dysfunctions in ADHD: Implications for inhibitory control, interference control, working memory, and cognitive flexibility. J Atten Disord, 24(13), 1928–1943. doi:10.1177/1087054717730611",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with non-invasive brain stimulation. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Weissman DH, Roberts KC, Visscher KM, Woldorff MG. (2006). The neural bases of momentary lapses in attention. Nat Neurosci, 9(7), 971–978. doi:10.1038/nn1727",
      "Nitsche MA, Paulus W. (2000). Excitability changes induced in the human motor cortex by weak transcranial direct current stimulation. J Physiol, 527(3), 633–639. doi:10.1111/j.1469-7793.2000.t01-1-00633.x",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with transcranial direct current stimulation (tDCS): Challenges and future directions. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease — a new navigated focal brain therapy. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and non-invasive brain stimulation: A tale of two loops. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Peterchev AV, Wagner TA, Miranda PC, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335. doi:10.1111/j.1525-1403.2011.00378.x",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930. doi:10.1016/j.tics.2016.09.007",
    ],
    tavns: [
      "Steenbergen L, Sellaro R, Stock AK, Verkuil B, Beste C, Colzato LS. (2015). Transcutaneous vagus nerve stimulation (tVNS) enhances response inhibition via action of norepinephrine on the prefrontal cortex. Brain Stimul, 8(6), 1155–1160. doi:10.1016/j.brs.2015.09.001",
      "Berridge CW, Waterhouse BD. (2003). The locus coeruleus-noradrenergic system: Modulation of behavioral state and state-dependent cognitive processes. Brain Res Rev, 42(1), 33–84. doi:10.1016/S0165-0173(03)00143-7",
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network in major depressive disorder. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Farmer AD, Strzelczyk A, Finisguerra A, et al. (2020). International consensus based review and recommendations for minimum reporting standards in research on transcutaneous vagus nerve stimulation. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Colzato LS, Ritter SM, Steenbergen L. (2018). Transcutaneous vagus nerve stimulation (tVNS) enhances divergent thinking. Neuropsychologia, 111, 74–79. doi:10.1016/j.neuropsychologia.2018.01.003",
      "Manta S, Dong J, Debonnel G, Bhagya V. (2012). Enhancement of the function of rat serotonin and norepinephrine neurons by sustained vagus nerve stimulation. J Psychiatry Neurosci, 37(3), 181–191. doi:10.1503/jpn.110132",
      "Burger AM, Van der Does W, Brosschot JF, Verkuil B. (2020). Transcutaneous vagus nerve stimulation reduces the startle response in anxious individuals. Biol Psychol, 149, 107800. doi:10.1016/j.biopsycho.2019.107800",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of the brain-gut axis in psychiatric and inflammatory disorders. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of cranial electrotherapy stimulation for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review: A safer alternative to psychopharmaceuticals in the treatment of depression. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Kavirajan HC, Lueck K, Cho K. (2014). Alternating current cranial electrotherapy stimulation (CES) use in outpatient psychiatric and pain treatment: A retrospective analysis. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Overcash SJ. (2005). Narrative literature review: CES for anxiety, insomnia, depression. Am J Electromed, 22(2), 22–28.",
    ],
    network: [
      "Castellanos FX, Margulies DS, Kelly C, et al. (2008). Cingulate-precuneus interactions: A new locus of dysfunction in adult attention-deficit/hyperactivity disorder. Biol Psychiatry, 63(3), 332–337. doi:10.1016/j.biopsych.2007.06.025",
      "Weissman DH, Roberts KC, Visscher KM, Woldorff MG. (2006). The neural bases of momentary lapses in attention. Nat Neurosci, 9(7), 971–978. doi:10.1038/nn1727",
      "Dosenbach NU, Fair DA, Miezin FM, et al. (2007). Distinct brain networks for adaptive and stable task control in humans. Proc Natl Acad Sci USA, 104(26), 11073–11078. doi:10.1073/pnas.0704320104",
      "Menon V, Uddin LQ. (2010). Saliency, switching, attention and control: A network model of insula function. Brain Struct Funct, 214(5–6), 655–667. doi:10.1007/s00429-010-0262-0",
      "Volkow ND, Wang GJ, Newcorn JH, et al. (2011). Motivation deficit in ADHD is associated with dysfunction of the dopamine reward pathway. Mol Psychiatry, 16(11), 1147–1154. doi:10.1038/mp.2010.97",
    ],
  },
  // ── FNON Protocol Data (SOZO_Brain_Networks_qEEG_FNON.xlsx, April 2026) ──
  fnonPrimaryNetwork: 'ECN + DAN + DMN suppression',
  fnonSecondaryNetwork: 'DMN suppress',
  fnonFBand: 'TBR correction (Theta/Beta ratio)',
  fnonEegNodes: 'Fz/F3/F4(prefrontal)+Cz/Pz(central-parietal)+P3/P4(parietal attention)',
  fnonOscillationGoal: 'Correct TBR excess (canonical ADHD qEEG biomarker); suppress DMN intrusion; facilitate ECN-DAN coupling',
  fnonPrimaryModalityParams: 'TPS: 6000 pulses, EFD 0.20 mJ/mm², 5 Hz PRF, 6 sessions bilateral prefrontal — RCT 2024 Frontiers (11 cit)',
  fnonAddonModality: 'tACS (7Hz theta-alpha border, Fz/FCz); CES (Alpha-Stim frontal alpha); PBM (F3/F4 bilateral)',
  fnonSessions: '6–12',
  fnonEvidenceLevel: 'Pilot RCT 2024 (TPS); Investigational',
  fnonLitCount: '2+ TPS RCT; 20+ tDCS; 10+ tACS',
  fnonKeyReferences: 'TPS adolescent RCT 2024 Frontiers (11 cit); ADHD tACS 2020-2024; Meinzer tDCS ADHD',
  fnonNotes: 'TBR (theta/beta) = primary ADHD qEEG biomarker. NF (neurofeedback) complements TPS for TBR training.',
  fnonQeegBiomarker: '↑TBR; ↓Beta frontal',
  fnonPaperCounts: {
    tps: 2, tms: 30, tdcs: 20,
    tavns: 5, ces: 5, tacs: 10,
    pbm: 5, lifu: 3, pemf: 5, dbs: null,
  },
  fnonBestFirstLine: 'TMS L-DLPFC + tDCS',
  fnonBestSecondLine: 'TPS bilateral + tACS 7Hz',
  fnonScore: 3,

};
