'use strict';
module.exports = {
  conditionFull: "Alzheimer's Disease / Mild Cognitive Impairment (AD/MCI)",
  conditionShort: "Alzheimer's",
  conditionSlug: "alzheimers",
  documentNumber: "SOZO-AD-PROT-001",
  offLabelCoverText: "tDCS and TPS use in Alzheimer's Disease / MCI is INVESTIGATIONAL / OFF-LABEL. TPS has CE-mark supported evidence for Alzheimer's; tDCS has Level C–B evidence for cognitive enhancement in AD/MCI.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level C–B evidence for AD/MCI cognitive enhancement', 'Standard informed consent + off-label note; capacity assessment if needed'],
    ['TPS', 'CE-marked (Class IIa)', 'CE-mark with Alzheimer\'s indication; Level B evidence', 'Standard informed consent; Doctor sign-off for AD severity'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; exploratory evidence for neurodegeneration and cognition', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia; off-label for AD cognition', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of Alzheimer's Disease (mild-moderate) or Mild Cognitive Impairment (MCI-AD) by qualified neurologist or geriatric psychiatrist",
    "MMSE ≥15 (mild-moderate AD) or MoCA ≥15 at baseline assessment",
    "Age 55–85 years (exceptions at Doctor discretion with documented rationale)",
    "Stable pharmacological treatment for ≥4 weeks (cholinesterase inhibitor and/or memantine) or Doctor-documented decision re: pharmacotherapy",
    "Capacity to provide informed consent, or accompanied by legal guardian/proxy for supported consent",
    "Willing and able to attend sessions as prescribed (carer/family participation strongly encouraged)",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Severe dementia (MMSE <10 or FAST Stage ≥6) — cognitive burden; limited benefit; safety and consent concerns",
    "Active delirium — defer until resolved",
    "Uncontrolled epilepsy (AD patients have elevated seizure risk — formal assessment required)",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Moderate dementia (MMSE 10–18) — individual benefit-risk; carer-supported consent; adapted protocol",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment by Doctor",
    "History of seizures or epilepsy in AD — formal neurological risk assessment required; cholinesterase inhibitor + stimulation interaction",
    "Active severe agitation/BPSD — stabilise neuropsychiatric symptoms before enrolment",
    "Significant cerebrovascular disease (multi-infarct dementia component) — imaging review required",
    "Current anticoagulation therapy — no direct clinical contraindication but review for electrode skin care",
    "Parkinson's disease-dementia overlap — adapted montage; consult movement disorder team",
    "Vascular dementia comorbidity — adapted protocol emphasising frontal-executive targets",
    "Recent hospitalisation — medical clearance required",
  ],

  overviewParagraph: "Alzheimer's Disease (AD) is the most common form of dementia, accounting for 60–80% of all dementia cases and affecting approximately 55 million people worldwide. It is a progressive neurodegenerative disorder characterised by episodic memory impairment, language difficulties, executive dysfunction, visuospatial deficits, and behavioural and psychological symptoms of dementia (BPSD). Mild Cognitive Impairment (MCI) represents the transitional stage between normal ageing and AD, with amnestic MCI carrying a 10–15% annual conversion rate to AD. Despite significant research investment, pharmacological treatments provide only modest symptomatic benefit (cholinesterase inhibitors, memantine), and no disease-modifying therapy has achieved regulatory approval except recently approved anti-amyloid antibodies (lecanemab, donanemab) with restricted indications. This creates a substantial opportunity for non-invasive neuromodulation — particularly tDCS and TPS — to complement pharmacotherapy by directly upregulating neural circuits impaired in AD and MCI.",
  fnonNetworkParagraph: "Alzheimer's Disease is fundamentally a disorder of network-level neurodegeneration. The FNON framework identifies progressive disconnection within the DMN (the first and most severely affected network in AD), degeneration of hippocampal-prefrontal memory circuits, and progressive loss of CEN, SN, and corticothalamic integrity as the neurophysiological landscape for intervention. SOZO targets residual neuroplasticity in early-stage AD and MCI via direct stimulation of the temporoparietal-prefrontal memory consolidation axis, combined with autonomic-brainstem modulation to promote neurotrophic factor release.",
  networkDisorderParagraphs: [
    "The Default Mode Network (DMN) is paradoxically the first and most severely affected network in AD — the same network that is hyperactive in healthy individuals during rest becomes progressively disconnected and atrophied in AD. The characteristic early AD involvement of the hippocampus, entorhinal cortex, posterior cingulate cortex, and medial temporal lobe regions corresponds precisely to the core nodes of the DMN memory encoding and consolidation circuit. Amyloid-beta accumulation follows this pattern, with posterior cingulate and medial prefrontal regions showing the earliest PET-detectable amyloid deposition.",
    "Structural and functional connectivity analyses demonstrate progressive disconnection along the hippocampal-entorhinal-parahippocampal-posterior cingulate axis, with reduced default mode network integrity correlating with memory performance, cognitive reserve, and rate of clinical decline. The temporoparietal junction (TPJ), angular gyrus, and lateral temporal cortex — which support semantic memory and language — show atrophy and reduced connectivity in the mid-stages of AD. CEN integrity (DLPFC, PPC) is reduced in proportion to executive and working memory decline.",
    "The neurotrophic hypothesis of AD proposes that loss of BDNF, NGF, and other trophic factors in hippocampal and basal forebrain circuits contributes to progressive synaptic and neuronal loss. taVNS stimulates BDNF release via NTS-LC-hippocampal pathways and promotes anti-inflammatory cytokine profiles that may reduce neuroinflammatory progression. TPS has mechanistic evidence for stimulating BDNF expression and promoting synaptic plasticity in the temporal and hippocampal regions targeted by its focused ultrasound energy.",
  ],

  pathophysiologyText: "AD pathophysiology involves amyloid-beta plaque accumulation (extracellular), neurofibrillary tangle formation from hyperphosphorylated tau (intracellular), progressive synaptic loss, neuroinflammation mediated by activated microglia and astrocytes, mitochondrial dysfunction, cholinergic basal forebrain degeneration, and progressive neurodegeneration along the medial temporal-parietal-frontal axis. The amyloid cascade hypothesis remains the dominant framework but is complemented by neuroinflammatory, vascular, and metabolic mechanisms. In MCI, synaptic dysfunction precedes neurodegeneration, creating an important therapeutic window. The cholinergic deficit (nucleus basalis of Meynert degeneration) provides the mechanistic basis for cholinesterase inhibitor pharmacotherapy and is directly relevant to FNON: upregulating frontal and temporal cortical excitability via tDCS may enhance the signal-to-noise ratio for cholinergic-dependent memory encoding processes.",
  cardinalSymptoms: [
    ["Episodic Memory Impairment", "Difficulty learning and retaining new information; forgetting recent conversations, appointments, and events; repeating questions; primarily hippocampal-entorhinal degeneration", "Core criterion — earliest and most prominent in AD (~100%)", "Albert et al., 2011; McKhann et al., 2011"],
    ["Language Difficulties", "Word-finding difficulties (anomia); reduced verbal fluency; simplified grammar; difficulty understanding complex language; temporal lobe degeneration", "~60–70% AD; prominent in logopenic variant", "Mesulam et al., 2014"],
    ["Executive Dysfunction", "Impaired planning, problem-solving, complex task management; difficulty with financial tasks, medication management; frontal-subcortical involvement", "~60–70% as AD progresses", "Perry & Hodges, 1999"],
    ["Visuospatial Deficits", "Difficulty judging distances, navigating environments, recognising faces; parietal-occipital cortical degeneration", "~50–60%, prominent in posterior cortical atrophy variant", "Mendez & Cummings, 2003"],
    ["Disorientation", "Temporal and spatial disorientation; getting lost in familiar environments; difficulty tracking date and time", "~80–90% moderate AD", "Mendez & Cummings, 2003"],
    ["BPSD — Apathy", "Loss of motivation, initiative, and goal-directed behaviour; social withdrawal; flat affect; most common BPSD in AD", "~50–70%", "Lyketsos et al., 2011"],
    ["BPSD — Depression/Anxiety", "Depressive symptoms (early stages particularly); anxiety about memory loss; catastrophic reactions; premorbid personality amplification", "~30–50%", "Lyketsos et al., 2011"],
    ["BPSD — Agitation/Irritability", "Restlessness, pacing, verbal/physical aggression; typically moderate-severe stage; limbic network involvement", "~40–60% moderate-severe", "Lyketsos et al., 2011"],
    ["Sleep Disturbance", "Sundowning; irregular sleep-wake cycles; REM sleep behaviour disorder in DLB overlap; circadian rhythm disruption", "~40–60%", "Mander et al., 2016"],
    ["Functional Decline", "Progressive loss of independence in IADLs (finances, cooking, medication management) then BADLs (dressing, hygiene)", "Defining feature of dementia (100%)", "American Psychiatric Association, 2022"],
    ["Semantic Memory Loss", "Loss of general knowledge and word meanings; temporal lobe degeneration; difficulty naming objects, famous people, historical events", "~60% mild-moderate AD", "Hodges & Patterson, 1995"],
    ["Attention Deficits", "Reduced sustained and selective attention; susceptibility to distraction; impaired dual-task performance", "~60–70%", "Parasuraman & Haxby, 1993"],
    ["Social Cognition Impairment", "Reduced empathy, theory of mind, and social judgment; frontal-temporal network degeneration", "~40% moderate AD", "Gregory et al., 2002"],
  ],
  standardGuidelinesText: [
    "Current evidence-based guidelines for AD and MCI (NICE 2018, AAN 2018, EAN 2020, AAGP 2023) position cholinesterase inhibitors (donepezil, rivastigmine, galantamine) as first-line symptomatic treatment for mild-moderate AD, with memantine approved for moderate-severe AD and as an add-on to cholinesterase inhibitors. The recently approved anti-amyloid monoclonal antibodies (lecanemab — Leqembi; donanemab — Kisunla) are approved for early AD with confirmed amyloid pathology (MCI-AD and mild AD) and represent the first disease-modifying treatments, though access is currently limited and administered via IV infusion.",
    "Non-pharmacological approaches including cognitive stimulation therapy (CST), cognitive rehabilitation, physical exercise, and multimodal interventions are recommended alongside pharmacotherapy across all guidelines for their quality-of-life and functional benefits. These approaches are particularly valuable for BPSD management as alternatives to antipsychotic medications.",
    "SOZO FNON protocols for AD/MCI are designed to directly upregulate the degraded hippocampal-prefrontal memory circuits using tDCS and TPS, promote neurotrophic factor release via taVNS, and provide complementary cognitive stimulation concurrent with stimulation sessions. The Doctor coordinates FNON with pharmacotherapy — combining tDCS/TPS with cholinesterase inhibitor peak effect timing where possible — and provides regular cognitive assessments to monitor trajectory.",
  ],

  fnonFrameworkParagraph: "The FNON framework for AD/MCI targets the progressive disconnection of the hippocampal-prefrontal memory circuit with direct neuromodulation at the key network hubs remaining functional. Temporoparietal junction (TPJ) and left DLPFC anodal tDCS target the semantic and episodic memory encoding networks. TPS provides the unique capability to deliver focused acoustic energy directly to temporal and hippocampal regions inaccessible to conventional tDCS, mechanistically driving neuroplasticity where it is most needed. taVNS promotes BDNF release and anti-inflammatory processes via the NTS-LC-hippocampal axis, providing a neurotrophic foundation for stimulation-induced plasticity.",
  keyBrainRegions: [
    ["Temporoparietal Junction (TPJ) / Angular Gyrus", "Semantic memory hub; primary tDCS target for AD; reduced cortical thickness and connectivity; language-memory interface", "PRIMARY TARGET: anodal tDCS T3/P3 region (left TPJ) — most replicated tDCS target for episodic and semantic memory in AD; TPS temporal", "Boggio et al., 2012; Ferrucci et al., 2008"],
    ["Hippocampus", "Episodic memory encoding and consolidation; earliest and most severe neurodegeneration in AD; bilateral volume reduction", "TPS hippocampal region — primary TPS target for AD; unique ability to reach medial temporal depth; stimulates BDNF-neuroplasticity", "Beisteiner et al., 2020; Jack et al., 2018"],
    ["Dorsolateral Prefrontal Cortex (DLPFC)", "Working memory, executive function, cognitive control; relatively preserved in early AD; supports compensatory encoding strategies", "Anodal tDCS F3 (left DLPFC) — enhances prefrontal working memory and executive compensation; TPS DLPFC", "Cotelli et al., 2012; Ferrucci et al., 2008"],
    ["Posterior Cingulate Cortex (PCC)", "DMN core hub; earliest site of amyloid-beta PET positivity; memory consolidation; autobiographical memory", "TPS PCC targeting — stimulate residual function; cathodal tDCS Pz may be excessive; TPS more nuanced PCC engagement", "Buckner et al., 2005; Minoshima et al., 1997"],
    ["Entorhinal Cortex", "Gateway to hippocampus; grid cell navigation; primary site of early tau pathology (Braak stages I-II); memory input relay", "TPS medial temporal targeting to engage entorhinal-hippocampal circuit; most accessible via temporal TPS trajectory", "Braak & Braak, 1991; Insausti et al., 1998"],
    ["Left Inferior Frontal Gyrus (Broca's Area)", "Language production and verbal memory encoding; typically preserved until moderate-severe AD; semantic fluency; verbal learning", "Anodal tDCS F7 region (left IFG); TPS Broca's area for language-memory phenotype", "Cotelli et al., 2012"],
    ["Precuneus", "Visuospatial processing; self-referential memory; early amyloid deposition; part of posterior DMN", "TPS precuneus targeting for visuospatial variant; combined with PCC TPS for posterior DMN engagement", "Buckner et al., 2008"],
    ["Lateral Temporal Cortex", "Semantic memory storage; language comprehension; middle temporal gyrus; progressive atrophy in temporal variant AD", "Anodal tDCS temporal electrodes (T3/T5 region); TPS lateral temporal for semantic memory phenotype", "Hodges & Patterson, 1995"],
    ["Prefrontal Medial Cortex (vmPFC/mPFC)", "Autobiographical memory retrieval; self-referential processing; consolidation support for personal memories", "TPS mPFC targeting combined with DLPFC; indirect tDCS F3-mPFC", "Cabeza & St Jacques, 2007"],
  ],
  additionalBrainStructures: [
    ["Nucleus Basalis of Meynert (NBM)", "Primary cholinergic nucleus; early degeneration in AD; projects to hippocampus, cortex; cholinergic hypothesis of AD", "Indirect upregulation via cortical tDCS/TPS enhances ACh signal effectiveness; taVNS may modulate basal forebrain via NTS projections", "Perry et al., 1977; Whitehouse et al., 1982"],
    ["Locus Coeruleus (LC)", "Primary noradrenergic nucleus; significant neuronal loss in AD (precedes cortical changes); reduced NE modulation of cortex", "taVNS activates NTS→LC pathway — preserves and enhances residual NE modulation; promotes BDNF release via LC projections", "Grudzien et al., 2007; Mather & Harley, 2016"],
    ["Nucleus Tractus Solitarius (NTS)", "Primary vagal afferent relay; mediates all taVNS effects; BDNF release pathway entry point for AD neuroprotection", "taVNS NTS activation — BDNF-mediated neuroprotection; anti-inflammatory cytokine profile; NTS-LC-hippocampal circuit", "Fang et al., 2016"],
    ["Basal Forebrain Cholinergic Complex", "NBM + medial septum + diagonal band; progressive degeneration in AD; critical for cortical ACh tone and attention", "Indirect enhancement via tDCS/TPS cortical upregulation; taVNS NTS-basal forebrain projections", "Mesulam, 2013"],
    ["Amygdala", "Emotional memory; fear conditioning; BPSD substrate; amygdala-hippocampal connectivity for emotional episodic memory", "TPS temporal-amygdala region for BPSD phenotype; taVNS modulates amygdala via NTS pathway", "LaBar & Cabeza, 2006"],
    ["Thalamus", "Memory relay; hippocampal-thalamic-cortical circuit; anterior thalamus for spatial memory; mediodorsal for working memory", "TPS deep thalamic targeting (indirect); combined with hippocampal TPS for memory consolidation circuit", "Aggleton & Brown, 1999"],
    ["Cerebellum", "Emerging evidence for cerebellar-cognitive-affective contributions in AD; preserved relatively late; compensatory potential", "TPS cerebellar for later-stage compensatory stimulation; tDCS Cbz for cerebellar-frontal pathway engagement", "Schmahmann, 2019"],
  ],
  keyFunctionalNetworks: [
    ["Default Mode Network (DMN)", "mPFC, hippocampus, PCC, precuneus, angular gyrus, entorhinal cortex", "Progressive disconnection and atrophy; earliest affected network in AD; amyloid deposition follows DMN topology; memory circuit degeneration", "TPS hippocampal + PCC targeting of residual DMN function; anodal tDCS TPJ/angular gyrus; combined memory consolidation tasks", "Buckner et al., 2005; Sperling et al., 2011"],
    ["Central Executive Network (CEN)", "DLPFC, PPC, lateral PFC, ACC", "Progressively impaired as AD advances beyond mild stage; executive compensation important in early stages; working memory deficit", "Anodal tDCS F3 (DLPFC); TPS DLPFC for CEN upregulation; working memory training concurrent", "Grady et al., 2003"],
    ["Memory Encoding Network", "Hippocampus, entorhinal cortex, parahippocampal gyrus, perirhinal cortex, TPJ", "Earliest and most severe network failure; episodic memory encoding and consolidation circuit; primary target for AD neuromodulation", "TPS hippocampal/entorhinal PRIMARY; anodal tDCS TPJ; memory encoding tasks concurrent with stimulation", "Jack et al., 2018; Braak & Braak, 1991"],
    ["Language Network", "Left IFG (Broca's), left STG (Wernicke's), lateral temporal cortex, TPJ", "Impaired verbal fluency, naming, and comprehension; temporal lobe degeneration; language-memory interface", "Anodal tDCS F7 (Broca's) + T3 (temporal); TPS left temporal for semantic memory preservation", "Mesulam et al., 2014"],
    ["Salience Network (SN)", "dACC, insula, amygdala", "Relatively preserved but dysregulated; BPSD (agitation, anxiety) involve SN hyperreactivity; emotion-memory interface", "taVNS for SN-limbic modulation; TPS temporal for amygdala-SN engagement in BPSD phenotype", "Seeley et al., 2007"],
    ["Cholinergic Network", "NBM projections to hippocampus, neocortex, amygdala; Meynert-cortical pathway", "Progressive degeneration parallel to clinical decline; provides mechanistic basis for cholinesterase inhibitor synergy with tDCS", "tDCS cortical upregulation enhances ACh-mediated signal; taVNS basal forebrain projections via NTS; timed with cholinesterase inhibitor peak", "Mesulam, 2013"],
    ["Visual Association Network", "V4, V5, occipito-temporal, parietal", "Impaired in posterior cortical atrophy variant; visuospatial deficits; agnosia; late-stage involvement in typical AD", "TPS occipito-parietal for visuospatial variant; anodal tDCS parieto-occipital for agnosia phenotype", "Mendez & Cummings, 2003"],
  ],
  networkAbnormalities: "AD is characterised by progressive DMN disconnection (hippocampus-PCC-angular gyrus axis), early entorhinal-hippocampal tau pathology, amyloid deposition in DMN hubs, cholinergic basal forebrain degeneration, and loss of LC noradrenergic modulation. The FNON approach targets residual plasticity in early-stage disease.",
  conceptualFramework: "SOZO FNON AD protocol targets: (1) Direct upregulation of hippocampal-temporal memory circuit via TPS deep targeting; (2) Enhance cortical excitability in TPJ and DLPFC via anodal tDCS; (3) Promote BDNF/neurotrophic factor release via taVNS NTS-LC-hippocampal pathway; (4) Pair stimulation with cognitive training to leverage stimulation-enhanced neuroplasticity for memory encoding.",

  clinicalPhenotypes: [
    ["Amnestic-Predominant MCI/early AD", "Classic memory-first presentation; hippocampal-entorhinal dominant; best response window for TPS; maximum neurotrophic support via taVNS", "Albert et al., 2011"],
    ["Executive-Dominant AD", "Frontal-executive impairment prominent; DLPFC network degeneration; left DLPFC tDCS primary; TPS prefrontal; combined with cognitive training", "Perry & Hodges, 1999"],
    ["Language-Variant AD (Logopenic)", "Word-finding, naming, verbal fluency deficit primary; left temporal dominant; tDCS T3/F7; TPS left temporal; semantic tasks concurrent", "Gorno-Tempini et al., 2011"],
    ["Posterior Cortical Atrophy (PCA)", "Visuospatial and visual processing deficit dominant; occipito-parietal primary; TPS parieto-occipital; visuospatial tasks concurrent", "Crutch et al., 2012"],
    ["BPSD-Dominant AD", "Neuropsychiatric symptoms (agitation, depression, anxiety, apathy) primary management challenge; taVNS/CES for limbic modulation; combined pharmacotherapy coordination", "Lyketsos et al., 2011"],
    ["Apathy-Dominant AD", "Profound apathy and lack of initiative; vmPFC/anterior cingulate involvement; anodal tDCS F3/Fz; TPS frontal for motivational circuit", "Robert et al., 2009"],
    ["Sleep-Disrupted AD", "Severe sleep disturbance, sundowning, circadian rhythm disruption; CES evening + taVNS for autonomic-circadian modulation", "Mander et al., 2016"],
    ["Rapid-Progression AD", "Faster-than-expected cognitive decline; maximise neurotrophic support via taVNS; TPS hippocampal intensive; consider anti-amyloid therapy referral", "Jack et al., 2018"],
    ["Mild Cognitive Impairment (MCI-AD)", "Pre-dementia stage; maximum neuroplasticity window; most favourable intervention opportunity; full TPS + tDCS + taVNS protocol at full intensity", "Petersen et al., 2018"],
  ],
  symptomNetworkMapping: [
    ["Episodic Memory Impairment", "DMN disconnection", "Hippocampal-entorhinal degeneration", "TPS hippocampal PRIMARY + tDCS TPJ", "Memory encoding/recall task concurrent"],
    ["Language Difficulties", "Language network — left temporal", "Left IFG-temporal degeneration", "tDCS T3/F7 anodal", "Verbal fluency/naming task concurrent"],
    ["Executive Dysfunction", "CEN hypoactivation", "DLPFC-PFC progressive atrophy", "tDCS F3 anodal", "Working memory/planning task concurrent"],
    ["Visuospatial Deficits", "Visual association network", "Parieto-occipital atrophy (PCA)", "TPS parieto-occipital + anodal tDCS P3/P4", "Visuospatial task concurrent"],
    ["Apathy", "Prefrontal motivational circuit", "vmPFC-striatal degeneration", "tDCS F3/Fz anodal + TPS frontal", "Goal-directed activity concurrent"],
    ["BPSD — Agitation", "SN/Limbic hyperreactivity", "Amygdala-frontal disconnection", "taVNS + CES for limbic modulation", "Carer-guided calm engagement concurrent"],
    ["Sleep Disturbance", "Circadian + autonomic circuit", "LC-raphe degeneration; SCN involvement", "CES evening + taVNS", "Sleep hygiene + light therapy concurrent"],
    ["Attention Deficits", "CEN + cholinergic network", "Cholinergic basal forebrain degeneration", "tDCS F3 anodal (timed with ChEI peak)", "Selective attention task concurrent"],
    ["Semantic Memory Loss", "Language/temporal DMN", "Lateral temporal cortex atrophy", "tDCS T3/T5 anodal + TPS temporal", "Semantic categorisation tasks concurrent"],
    ["Social Cognition", "Frontal-temporal network", "Right frontal-temporal involvement", "TPS bilateral temporal + right frontal tDCS", "Social recognition tasks concurrent"],
  ],
  montageSelectionRows: [
    ["Amnestic MCI / early AD (primary memory)", "TPS hippocampal-temporal + anodal tDCS T3/P3"],
    ["Language-variant AD (left temporal)", "Anodal tDCS T3/F7 (left temporal-frontal) — 2mA 20min"],
    ["Executive-dominant AD (frontal)", "Anodal tDCS F3 (left DLPFC) + TPS DLPFC — 2mA 20min"],
    ["Posterior cortical atrophy (visuospatial)", "Anodal tDCS P3/P4 bilateral parietal + TPS parieto-occipital"],
    ["BPSD / agitation (limbic)", "taVNS 40min + CES 60min (primary modalities for BPSD)"],
    ["Apathy dominant (motivational)", "Anodal tDCS F3/Fz + TPS mPFC/frontal medial"],
    ["Sleep-disrupted AD", "CES 0.5mA 60min evening + taVNS pre-sleep"],
    ["Combined memory + executive (most common)", "TPS hippocampal + anodal tDCS T3+F3 bilateral"],
    ["taVNS neurotrophic protocol (all phenotypes)", "taVNS bilateral cymba 0.5mA 30min — neurotrophic and anti-inflammatory"],
    ["Comprehensive AD protocol (MCI/mild AD)", "TPS hippocampal + tDCS T3+F3 + taVNS (full S-O-Z-O)"],
    ["Moderate AD (reduced parameters)", "tDCS 1mA 15min; CES primary; TPS 0.15mJ/mm²; carer support"],
    ["Memory consolidation focused", "tDCS T3/P3 anodal 2mA 20min during encoding task"],
    ["Maintenance phase (after 10 sessions)", "TPS monthly + tDCS 2×/week + daily home CES"],
  ],
  polarityPrincipleText: "In AD/MCI, polarity selection prioritises temporoparietal anodal stimulation (T3/P3 — left hemisphere dominant) for episodic and semantic memory circuit upregulation. Left DLPFC anodal (F3) is added for executive and attention enhancement. Cathodal stimulation is used sparingly — avoiding suppression of already-degenerated cortical regions. TPS is preferred over cathodal tDCS for posterior regions where downregulation risks are highest.",
  polarityTable: [
    ["Anodal T3/P3 (left temporoparietal)", "Upregulates semantic and episodic memory circuit — most replicated tDCS target for AD memory enhancement"],
    ["Anodal F3 (left DLPFC)", "Executive function and working memory enhancement; compensatory prefrontal upregulation in AD"],
    ["Anodal T5 (left posterior temporal)", "Semantic memory and language network — logopenic/language variant AD primary"],
    ["taVNS bilateral cymba", "Neurotrophic: BDNF release via NTS-LC-hippocampal pathway; anti-inflammatory; neuroprotective foundation for all AD protocols"],
    ["TPS hippocampal/temporal", "Deep medial temporal targeting — not achievable with tDCS; primary TPS contribution unique to this modality"],
  ],

  classicTdcsProtocols: [
    ["C1", "Episodic memory / AD", "T3/P3 (left TPJ anodal)", "T4/P4 cathodal", "2mA 20min, 10 sessions", "Level C-B"],
    ["C2", "Semantic memory / naming", "T3/F7 anodal", "T4 cathodal", "2mA 20min", "Level C"],
    ["C3", "Executive function / working memory", "F3 anodal (DLPFC)", "Pz cathodal", "2mA 20min", "Level C"],
    ["C4", "Combined memory + executive", "T3+F3 anodal (bilateral temporal-frontal)", "T4+F4 cathodal", "2mA 20min", "Emerging"],
    ["C5", "Attention / cholinergic", "F3 anodal (timed with donepezil peak)", "Pz cathodal", "2mA 20min", "Exploratory"],
    ["C6", "Language variant AD", "F7/T3 left anodal", "Right temporal cathodal", "1.5mA 20min", "Exploratory"],
    ["C7", "Visuospatial / PCA", "P3+P4 bilateral parietal anodal", "Frontal bilateral cathodal", "1.5mA 20min", "Exploratory"],
    ["C8", "Mild-moderate AD (reduced)", "T3 anodal", "T4 cathodal", "1mA 15min", "Exploratory"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Amnestic MCI/early AD", "DMN memory circuit disconnection", "T3/P3 anodal + F3 anodal (bilateral)", "Temporoparietal + prefrontal memory network upregulation"],
    ["F2", "Language-variant AD", "Left temporal network degeneration", "F7+T3 anodal (left frontal-temporal)", "Language-memory circuit upregulation"],
    ["F3", "Executive-dominant AD", "CEN hypoactivation", "F3 anodal + Pz cathodal", "Prefrontal CEN upregulation with posterior suppression"],
    ["F4", "BPSD / agitation", "Limbic-SN dysregulation", "taVNS + CES (primary modalities)", "Autonomic-limbic stabilisation — tDCS secondary for BPSD"],
    ["F5", "Apathy-dominant AD", "vmPFC-frontal circuit deficit", "Fz/F3 anodal medial-left frontal", "Motivational circuit upregulation"],
    ["F6", "Comprehensive MCI protocol", "Multi-network early decline", "T3+F3+Fz triple-electrode montage + taVNS", "Maximum memory and executive network upregulation"],
  ],
  classicTpsProtocols: [
    ["T1", "Episodic memory / hippocampus", "Hippocampal-entorhinal region", "0.25mJ/mm²", "4000 pulses", "Level B (CE-marked for AD)"],
    ["T2", "Temporal memory network", "Lateral temporal cortex", "0.2mJ/mm²", "4000 pulses", "Level C-B"],
    ["T3", "DLPFC / executive function", "Left DLPFC", "0.2mJ/mm²", "3000 pulses", "Emerging"],
    ["T4", "Combined memory + executive", "Hippocampal + DLPFC sequential", "0.2mJ/mm²", "5000 pulses total", "Level B (Beisteiner protocol)"],
    ["T5", "PCC / posterior DMN", "Posterior cingulate cortex", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Amnestic MCI / early AD", "Hippocampal-entorhinal circuit", "Hippocampal deep target 0.25mJ/mm² × 4000 pulses — PRIMARY AD TPS protocol", "Deep medial temporal neuroplasticity induction; BDNF stimulation"],
    ["FT2", "Memory consolidation phenotype", "Hippocampal + PCC circuit", "Hippocampal 0.25mJ/mm² × 4000 + PCC 0.2mJ/mm² × 2000", "Sequential hippocampal then PCC — memory encoding and consolidation circuit"],
    ["FT3", "Language-variant AD", "Left temporal network", "Left temporal/Broca's 0.2mJ/mm² × 4000 pulses", "Language-memory circuit deep stimulation"],
    ["FT4", "Comprehensive MCI protocol (Beisteiner)", "Multi-focal memory circuit", "Hippocampal + DLPFC 0.2mJ/mm² × 5000 total (Beisteiner et al. protocol)", "Evidence-based multi-focal TPS sequence for AD based on clinical trial data"],
    ["FT5", "Executive-dominant AD", "DLPFC circuit", "Left DLPFC 0.2mJ/mm² × 3000 + hippocampal 0.2mJ/mm² × 2000", "Prefrontal then hippocampal — executive-memory combined"],
    ["FT6", "BPSD-dominant AD", "Temporal-limbic circuit", "Temporal-amygdala region 0.2mJ/mm² × 3000 + taVNS", "Deep temporal-limbic for BPSD; combined with autonomic modulation"],
    ["FT7", "Posterior cortical atrophy", "Parieto-occipital", "Parieto-occipital 0.2mJ/mm² × 4000 pulses", "Visuospatial circuit deep stimulation"],
    ["FT8", "Moderate AD maintenance", "Hippocampal only (conservative)", "Hippocampal 0.15mJ/mm² × 2500 — reduced for moderate AD", "Conservative maintenance stimulation for moderate AD"],
    ["FT9", "Monthly maintenance protocol", "Hippocampal + temporal", "Hippocampal 0.2mJ/mm² × 2000 monthly", "Monthly neurotrophic maintenance stimulation"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Amnestic MCI / Early AD",
      combinations: [
        ["S — Stabilise", "taVNS 40min bilateral — neurotrophic priming via NTS-LC-hippocampal BDNF pathway", "Establish maximum neurotrophic baseline before targeted memory circuit stimulation"],
        ["O — Optimise", "tDCS T3/P3 anodal 2mA 20min + F3 anodal — memory and executive upregulation", "Prime temporal and prefrontal cortical excitability for TPS deep penetration and cognitive tasks"],
        ["Z — Zone", "TPS hippocampal 0.25mJ/mm² 4000 pulses — deep medial temporal neuroplasticity", "Direct hippocampal circuit activation; BDNF induction; primary disease-modifying mechanism"],
        ["O — Outcome", "Memory encoding/recall task concurrent + CES evening — consolidate", "Explicit memory training during primed state; evening CES for sleep quality and memory consolidation"],
      ],
    },
    {
      phenotype: "Executive-Dominant AD",
      combinations: [
        ["S — Stabilise", "taVNS 30min — noradrenergic-neurotrophic priming", "LC-NE preparation for prefrontal cortical upregulation"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min + Pz cathodal — DLPFC CEN upregulation", "Prime left prefrontal excitability for executive function tasks"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 3000 + hippocampal 0.2mJ/mm² 2000", "Sequential prefrontal then hippocampal deep stimulation"],
        ["O — Outcome", "Working memory and planning task concurrent + CES", "Executive training tasks (Tower of London, N-back) during primed state"],
      ],
    },
    {
      phenotype: "Language-Variant AD (Logopenic)",
      combinations: [
        ["S — Stabilise", "taVNS 30min — neurotrophic preparation", "Prepare language network for targeted left temporal stimulation"],
        ["O — Optimise", "tDCS F7+T3 anodal 2mA 20min — left frontal-temporal language circuit", "Prime Broca's-temporal language-memory circuit"],
        ["Z — Zone", "TPS left temporal 0.2mJ/mm² 4000 pulses — deep language network", "Deep left temporal language-memory circuit stimulation"],
        ["O — Outcome", "Verbal fluency / naming tasks concurrent — picture naming, semantic fluency", "Language training during primed state; semantic category tasks"],
      ],
    },
    {
      phenotype: "Posterior Cortical Atrophy (PCA)",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 30min — anxiety reduction (PCA patients often anxious about visual symptoms)", "Reduce anxiety and stabilise before parieto-occipital stimulation"],
        ["O — Optimise", "tDCS P3/P4 bilateral anodal 1.5mA 20min — parieto-occipital circuit", "Prime bilateral parietal visuospatial processing circuit"],
        ["Z — Zone", "TPS parieto-occipital 0.2mJ/mm² 4000 — deep visuospatial network", "Deep posterior network stimulation for visuospatial functions"],
        ["O — Outcome", "Visuospatial tasks concurrent (clock drawing, Rey figure) + taVNS", "Visuospatial training with explicit parietal demands during primed state"],
      ],
    },
    {
      phenotype: "BPSD-Dominant AD",
      combinations: [
        ["S — Stabilise", "taVNS 40min + CES 60min — primary BPSD management modalities; limbic-autonomic stabilisation", "Autonomic-limbic downregulation for agitation/anxiety/depression; primary modalities for BPSD"],
        ["O — Optimise", "tDCS F3 anodal 1mA 15min (conservative) — frontal modulation only", "Conservative frontal upregulation; avoid overstimulation that may worsen agitation"],
        ["Z — Zone", "TPS temporal-limbic region 0.15mJ/mm² 2500 — conservative deep targeting", "Conservative deep temporal-limbic modulation for BPSD circuit"],
        ["O — Outcome", "Carer-guided cognitive stimulation + CES home daily — consolidate", "Non-pharmacological BPSD management concurrent with neural modulation"],
      ],
    },
    {
      phenotype: "Apathy-Dominant AD",
      combinations: [
        ["S — Stabilise", "taVNS 30min — motivational circuit priming via NTS-LC-VTA pathway", "Dopaminergic-noradrenergic priming for motivational frontal circuit"],
        ["O — Optimise", "tDCS F3/Fz anodal 2mA 20min — medial and left frontal motivational circuit", "Prime anterior cingulate and DLPFC for activity-engagement"],
        ["Z — Zone", "TPS mPFC/frontal 0.2mJ/mm² 3000 — deep frontal motivational circuit", "Deep medial-left frontal motivation circuit stimulation"],
        ["O — Outcome", "Goal-directed activity (pleasurable activity scheduling) concurrent + carer involvement", "Behavioural activation approaches with carer support during primed state"],
      ],
    },
    {
      phenotype: "Sleep-Disrupted AD",
      combinations: [
        ["S — Stabilise", "taVNS afternoon session 20min — pre-sleep autonomic preparation", "Shift autonomic balance; prepare for evening CES sleep facilitation"],
        ["O — Optimise", "tDCS T3/F3 anodal 2mA 20min (morning) — daytime cognitive maintenance", "Daytime cognitive circuit upregulation; avoid evening cognitive stimulation"],
        ["Z — Zone", "CES 0.5mA 60min evening — primary sleep facilitation modality", "Evening autonomic downregulation; circadian reset support"],
        ["O — Outcome", "Light therapy morning + structured daytime activity — consolidate", "Circadian anchor via morning bright light; structured daily routine to support sleep-wake cycling"],
      ],
    },
    {
      phenotype: "Rapid-Progression AD",
      combinations: [
        ["S — Stabilise", "taVNS 40min bilateral — maximum neurotrophic and anti-inflammatory support", "Maximum BDNF and anti-inflammatory cytokine support for rapid progression"],
        ["O — Optimise", "tDCS T3/P3+F3 combined 2mA 20min — maximum temporal-frontal upregulation", "Prime maximum cortical area before TPS deep stimulation"],
        ["Z — Zone", "TPS hippocampal + DLPFC combined 0.25mJ/mm² 5000 total — maximal circuit", "Maximum deep circuit stimulation; weekly sessions recommended"],
        ["O — Outcome", "Intensive cognitive stimulation therapy (CST) concurrent — group or individual", "Evidence-based CST alongside maximum neuromodulation; consider anti-amyloid therapy referral"],
      ],
    },
    {
      phenotype: "Mild Cognitive Impairment (MCI-AD)",
      combinations: [
        ["S — Stabilise", "taVNS 40min — maximum neurotrophic window; MCI is prime intervention point", "Maximum BDNF support in highest neuroplasticity window"],
        ["O — Optimise", "tDCS T3/P3 anodal + F3 anodal 2mA 20min full protocol — optimal in MCI", "Full memory and executive circuit upregulation at maximum intensity"],
        ["Z — Zone", "TPS hippocampal 0.25mJ/mm² 4000 + temporal 0.2mJ/mm² 2000", "Full hippocampal and temporal deep stimulation; best response in MCI"],
        ["O — Outcome", "Memory training + omega-3 + exercise programme concurrent — multimodal", "Maximum multimodal intervention at prime opportunity window; lifestyle co-intervention"],
      ],
    },
  ],

  taskPairingRows: [
    ["Memory Encoding/Recall Task", "Amnestic MCI/early AD", "tDCS T3/P3 anodal active", "Word list learning, face-name association, story recall"],
    ["Verbal Fluency Task", "Language-variant AD", "tDCS F7/T3 anodal active", "Letter and category fluency; picture naming"],
    ["N-back Working Memory", "Executive-dominant AD", "tDCS F3 anodal active", "1-back verbal; cognitive flexibility tasks"],
    ["Cognitive Stimulation Therapy (CST)", "All AD phenotypes", "TPS post-session", "Structured CST activities in post-stimulation plasticity window"],
    ["Visuospatial Reasoning", "PCA variant", "tDCS P3/P4 anodal active", "Block design, clock drawing, route navigation"],
    ["Goal-Directed Activity", "Apathy dominant", "tDCS Fz/F3 anodal active", "Personally meaningful activities; activity scheduling with carer"],
  ],
  outcomeMeasures: "Primary: MMSE and MoCA (baseline, 5-session, 10-session, 1-month, 3-month follow-up). Secondary: ADAS-Cog 13 (primary clinical trial outcome measure); verbal fluency (letter and category); digit span; Clinical Dementia Rating (CDR) Sum of Boxes; Neuropsychiatric Inventory (NPI) for BPSD; PSQI for sleep; Alzheimer's Disease Cooperative Study — ADL scale (functional independence); carer-rated burden (ZBI). Safety: seizure monitoring; skin inspection at electrode sites each session.",

  medicationSectionTitle: "Pharmacotherapy Context for Alzheimer's Disease",
  medicationSectionText: "Standard pharmacotherapy for AD includes cholinesterase inhibitors (donepezil 5–10mg daily; rivastigmine 6–12mg daily or 9.5mg/24h patch; galantamine 8–24mg daily) for mild-moderate AD, and memantine 10–20mg daily for moderate-severe AD (also used as combination therapy with cholinesterase inhibitors). Anti-amyloid monoclonal antibodies lecanemab (Leqembi, 10mg/kg biweekly IV) and donanemab (Kisunla) are approved for early AD with confirmed amyloid pathology — FNON protocols may complement these agents by addressing the downstream network dysfunction. BPSD pharmacotherapy includes low-dose antipsychotics (risperidone — only approved BPSD agent in many markets), SSRIs for depression/anxiety (sertraline, citalopram), and mirtazapine for insomnia-prominent BPSD. The Doctor coordinates FNON stimulation timing with cholinesterase inhibitor peak plasma concentration (typically 4–6 hours post-dose for donepezil) to maximise synergistic cholinergic-tDCS effects on cortical excitability.",

  references: {
    foundational: [
      "Jack CR Jr, Bennett DA, Blennow K, et al. (2018). NIA-AA Research Framework: Toward a biological definition of Alzheimer's disease. Alzheimers Dement, 14(4), 535–562. doi:10.1016/j.jalz.2018.02.018",
      "McKhann GM, Knopman DS, Chertkow H, et al. (2011). The diagnosis of dementia due to Alzheimer's disease: Recommendations from the National Institute on Aging-Alzheimer's Association workgroups. Alzheimers Dement, 7(3), 263–269. doi:10.1016/j.jalz.2011.03.005",
      "Braak H, Braak E. (1991). Neuropathological stageing of Alzheimer-related changes. Acta Neuropathol, 82(4), 239–259. doi:10.1007/BF00308809",
      "Buckner RL, Andrews-Hanna JR, Schacter DL. (2008). The brain's default network: Anatomy, function, and relevance to disease. Ann N Y Acad Sci, 1124, 1–38. doi:10.1196/annals.1440.011",
      "Sperling RA, Aisen PS, Beckett LA, et al. (2011). Toward defining the preclinical stages of Alzheimer's disease. Alzheimers Dement, 7(3), 280–292. doi:10.1016/j.jalz.2011.03.003",
      "Petersen RC, Lopez O, Armstrong MJ, et al. (2018). Practice guideline update summary: Mild cognitive impairment. Neurology, 90(3), 126–135. doi:10.1212/WNL.0000000000004826",
    ],
    tdcs: [
      "Boggio PS, Fregni F, Valasek C, et al. (2009). Temporal lobe cortical electrical stimulation during the encoding and retrieval phase reduces false memories. PLoS ONE, 4(3), e4959. doi:10.1371/journal.pone.0004959",
      "Ferrucci R, Mameli F, Guidi I, et al. (2008). Transcranial direct current stimulation improves recognition memory in Alzheimer disease. Neurology, 71(7), 493–498. doi:10.1212/01.wnl.0000317060.43722.a3",
      "Cotelli M, Manenti R, Cappa SF, et al. (2012). Effect of transcranial direct current stimulation on language and memory in Alzheimer's disease and mild cognitive impairment. Front Psychiatry, 3, 42. doi:10.3389/fpsyt.2012.00042",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with transcranial direct current stimulation (tDCS): Challenges and future directions. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Nitsche MA, Cohen LG, Wassermann EM, et al. (2008). Transcranial direct current stimulation: State of the art 2008. Brain Stimul, 1(3), 206–223. doi:10.1016/j.brs.2008.06.004",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Nozari N, Thompson-Schill SL. (2013). More attention when speaking: Does it help or does it hurt? Neuropsychologia, 51(13), 2770–2780. doi:10.1016/j.neuropsychologia.2013.09.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with non-invasive brain stimulation. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Woods AJ, Antal A, Bikson M, et al. (2016). A technical guide to tDCS, and related non-invasive brain stimulation tools. Clin Neurophysiol, 127(2), 1031–1048. doi:10.1016/j.clinph.2015.11.012",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease — a new navigated focal brain therapy. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Beisteiner R, Lozano AM. (2022). Is transcranial ultrasound pulse stimulation (TPS) clinically effective for Alzheimer's disease? Front Neurol, 13, 911796. doi:10.3389/fneur.2022.911796",
      "Hsu WY, Ku Y, Zanto TP, Gazzaley A. (2015). Effects of noninvasive brain stimulation on cognitive function in healthy aging and Alzheimer's disease. Neurobiol Aging, 36(8), 2348–2359. doi:10.1016/j.neurobiolaging.2015.04.016",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and non-invasive brain stimulation: A tale of two loops. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Daulatzai MA. (2017). Cerebral hypoperfusion and glucose hypometabolism: Key pathophysiological modulators promote neurodegeneration in Alzheimer's disease. J Neurosci Res, 95(4), 943–972. doi:10.1002/jnr.23777",
    ],
    tavns: [
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network in major depressive disorder. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Mather M, Harley CW. (2016). The locus coeruleus: Essential for maintaining cognitive function and the aging brain. Trends Cogn Sci, 20(3), 214–226. doi:10.1016/j.tics.2016.01.001",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of the brain-gut axis in psychiatric and inflammatory disorders. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Rong P, Liu J, Wang L, et al. (2016). Effect of transcutaneous auricular vagus nerve stimulation on major depressive disorder: A nonrandomized controlled pilot study. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
      "Farmer AD, Strzelczyk A, Finisguerra A, et al. (2020). International consensus based review and recommendations for minimum reporting standards in research on transcutaneous vagus nerve stimulation. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Jiang Y, Li Q, Shi X, et al. (2022). A systematic review of transcutaneous auricular vagus nerve stimulation for treating neuropsychiatric disorders. Neurosci Biobehav Rev, 133, 104500. doi:10.1016/j.neubiorev.2021.11.032",
      "Grudzien A, Shaw P, Weintraub S, Bigio E, Mash DC, Mesulam MM. (2007). Locus coeruleus neurofibrillary degeneration in aging, mild cognitive impairment and early Alzheimer's disease. Neurobiol Aging, 28(3), 327–335. doi:10.1016/j.neurobiolaging.2006.02.007",
      "Hsu WY, Ku Y, Zanto TP, Gazzaley A. (2015). Effects of noninvasive brain stimulation on cognitive function in healthy aging and Alzheimer's disease. Neurobiol Aging, 36(8), 2348–2359. doi:10.1016/j.neurobiolaging.2015.04.016",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review: A safer alternative to psychopharmaceuticals in the treatment of depression. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of cranial electrotherapy stimulation for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Kavirajan HC, Lueck K, Cho K. (2014). Alternating current cranial electrotherapy stimulation (CES) use in outpatient psychiatric and pain treatment: A retrospective analysis. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Mander BA, Winer JR, Walker MP. (2017). Sleep and human aging. Neuron, 94(1), 19–36. doi:10.1016/j.neuron.2017.02.004",
    ],
    network: [
      "Buckner RL, Snyder AZ, Shannon BJ, et al. (2005). Molecular, structural, and functional characterization of Alzheimer's disease: Evidence for a relationship between default activity, amyloid, and memory. J Neurosci, 25(34), 7709–7717. doi:10.1523/JNEUROSCI.2177-05.2005",
      "Grady CL, Furey ML, Pietrini P, Horwitz B, Rapoport SI. (2001). Altered brain functional connectivity and impaired short-term memory in Alzheimer's disease. Brain, 124(4), 739–756. doi:10.1093/brain/124.4.739",
      "Seeley WW, Menon V, Schatzberg AF, et al. (2007). Dissociable intrinsic connectivity networks for salience processing and executive control. J Neurosci, 27(9), 2349–2356. doi:10.1523/JNEUROSCI.5587-06.2007",
      "Mander BA, Winer JR, Jagust WJ, Walker MP. (2016). Sleep: A novel mechanistic pathway, biomarker, and treatment target in the pathology of Alzheimer's disease? Trends Neurosci, 39(8), 552–566. doi:10.1016/j.tins.2016.05.002",
      "Mesulam MM. (2013). Cholinergic circuitry of the human nucleus basalis and its fate in Alzheimer's disease. J Comp Neurol, 521(18), 4124–4144. doi:10.1002/cne.23415",
    ],
  },
};
