'use strict';
module.exports = {
  conditionFull: "Generalized Anxiety Disorder (GAD)",
  conditionShort: "Anxiety",
  conditionSlug: "anxiety",
  documentNumber: "SOZO-GAD-PROT-001",
  offLabelCoverText: "tDCS and TPS use in Generalized Anxiety Disorder is INVESTIGATIONAL / OFF-LABEL. Evidence is emerging with Level C–B evidence for anxiety-spectrum conditions.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level C–B emerging evidence for GAD/anxiety', 'Standard informed consent + off-label note'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; growing evidence base for anxiety disorders', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety, depression and insomnia', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of Generalized Anxiety Disorder (DSM-5 / ICD-11) by a qualified psychiatrist or physician",
    "GAD-7 score ≥10 or HAM-A ≥18 at baseline assessment",
    "Age 18–75 years (exceptions at Doctor discretion with documented rationale)",
    "Stable pharmacological treatment for ≥4 weeks prior to enrolment, or actively managed by prescribing Doctor",
    "Capacity to provide informed consent",
    "Willing and able to attend sessions as prescribed",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Current active psychotic episode requiring urgent management",
    "Active suicidal ideation with intent or plan requiring inpatient management",
    "Primary panic disorder with frequent severe attacks (uncontrolled) — stabilise first",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Comorbid MDD — assess which condition is primary and adapt montage accordingly",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment by Doctor",
    "Epilepsy or seizure history — formal risk assessment required",
    "Pregnancy — taVNS/CES preferred; tDCS/TPS at Doctor discretion with documented rationale",
    "Active dermatological conditions at electrode sites — assessment and protocol modification required",
    "PTSD comorbidity — trauma-informed approach required; coordinate with trauma therapist",
    "Substance misuse — sobriety and capacity assessment required",
    "Recent major surgery (within 3 months) — surgical team clearance required",
    "Thyroid disorders — ensure thyroid function optimised prior to enrolment",
  ],

  overviewParagraph: "Generalized Anxiety Disorder (GAD) is among the most prevalent anxiety disorders globally, affecting approximately 6.2% of the population over their lifetime. It is characterised by excessive, uncontrollable worry across multiple domains of life, accompanied by somatic symptoms including muscle tension, fatigue, sleep disturbance, concentration difficulties, restlessness, and irritability. GAD produces substantial functional impairment, particularly affecting occupational performance, interpersonal relationships, and quality of life. It is frequently comorbid with major depression (approximately 60% lifetime comorbidity), other anxiety disorders, and chronic pain conditions. First-line pharmacological treatments (SSRIs, SNRIs, buspirone) and psychotherapy (CBT) are effective for many patients, but up to 40–50% do not achieve full remission, highlighting the need for adjunctive neuromodulation approaches.",
  fnonNetworkParagraph: "GAD is fundamentally a disorder of threat prediction and top-down cognitive control over limbic hyperreactivity. The FNON framework identifies a core circuit-level imbalance: hyperactive Salience Network (SN) and Limbic Network driving excessive threat detection and sustained autonomic arousal, coupled with insufficient Central Executive Network (CEN) suppression of worry and prefrontal inhibition of amygdala reactivity. SOZO targets this imbalance by upregulating prefrontal cognitive control via tDCS/TPS and downregulating limbic-autonomic hyperarousal via taVNS and CES.",
  networkDisorderParagraphs: [
    "Neuroimaging studies consistently demonstrate that GAD is associated with aberrant interactions between prefrontal control regions and limbic threat-processing circuits. Amygdala hyperreactivity to ambiguous or threat-related stimuli is one of the most replicated findings in GAD, reflecting a failure of prefrontal inhibitory control. The right DLPFC, vmPFC, and OFC — which normally regulate amygdala reactivity through top-down suppression — show reduced activation and impaired connectivity with limbic regions in GAD patients.",
    "Functional connectivity analyses reveal hyperconnectivity within the Salience Network (SN), particularly between the anterior insula and dACC, consistent with heightened interoceptive awareness and somatic amplification of anxiety symptoms. Reduced anti-correlation between the SN and default mode network is associated with intrusive worry and difficulty disengaging from threat-related cognition. Resting-state EEG demonstrates elevated frontal alpha asymmetry (reduced left frontal activation) as a stable neurophysiological biomarker of GAD.",
    "The autonomic nervous system dysregulation in GAD — characterised by reduced heart rate variability (HRV), sustained sympathetic dominance, and impaired parasympathetic recovery — reflects brainstem-limbic circuit dysfunction amenable to taVNS modulation. CES provides complementary broad-spectrum modulation of arousal pathways via low-frequency transcranial current application. The FNON multi-modal approach simultaneously targets cortical control (tDCS/TPS) and subcortical-autonomic regulation (taVNS/CES).",
  ],

  pathophysiologyText: "GAD pathophysiology involves dysregulated interactions across the corticolimbic axis. Key mechanisms include: (1) amygdala hyperreactivity and impaired prefrontal-amygdala inhibitory regulation, particularly in the right hemisphere; (2) reduced GABA-ergic inhibitory tone — GAD is associated with reduced GABA in the anterior cortex and impaired GABAergic modulation of amygdala activity; (3) hyperactive HPA axis with cortisol dysregulation and altered stress reactivity; (4) autonomic nervous system imbalance with chronically elevated sympathetic tone, reduced parasympathetic activity, and reduced HRV; (5) elevated CRF (corticotropin-releasing factor) and NE signalling; (6) glutamatergic excess in amygdalar and hippocampal circuits; and (7) serotonergic and noradrenergic dysregulation affecting both mood and somatic symptom expression. These mechanisms converge to produce the characteristic cognitive, somatic, and autonomic features of GAD.",
  cardinalSymptoms: [
    ["Excessive Worry", "Persistent, uncontrollable worry across multiple life domains; worry is difficult to suppress and disproportionate to actual risk", "Core criterion (100% by DSM-5 definition)", "American Psychiatric Association, 2022"],
    ["Restlessness / Keyed-Up", "Feeling on edge, restless, or keyed-up; inability to relax; inner tension and agitation; difficulty settling", "Core criterion (>90%)", "American Psychiatric Association, 2022"],
    ["Fatigue", "Easy fatigability; tiredness not explained by exertion; associated with chronic sympathetic activation and poor sleep", "~90%", "Brawman-Mintzer & Lydiard, 1996"],
    ["Concentration Difficulty", "Difficulty concentrating; mind going blank; impaired sustained attention and working memory under anxious rumination", "~85%", "Airaksinen et al., 2005"],
    ["Muscle Tension", "Persistent muscle tension, aching, or soreness; particularly neck, shoulders, jaw; may present as headache or TMJ pain", "~80%", "Kessler et al., 2005"],
    ["Sleep Disturbance", "Difficulty falling or staying asleep; unrefreshing sleep; hyperarousal at bedtime; nocturnal anxiety awakening", "~80%", "Benca et al., 1992"],
    ["Irritability", "Heightened irritability; low frustration tolerance; reactive anger; interpersonal friction; emotional lability", "~75%", "Kessler et al., 2005"],
    ["Somatic Symptoms", "Headache, GI symptoms (IBS, nausea), palpitations, sweating, dry mouth, dizziness; somatic amplification of arousal", "~70%", "Barsky & Borus, 1999"],
    ["Autonomic Arousal", "Elevated heart rate, palpitations, shortness of breath, chest tightness, flushing; sympathetic hyperactivation at rest", "~65%", "Thayer et al., 2012"],
    ["Avoidance Behaviour", "Avoiding anxiety-provoking situations, responsibilities, or decisions; safety behaviours that maintain anxiety cycle", "~70%", "Borkovec & Ruscio, 2001"],
    ["Catastrophising", "Automatic worst-case-scenario thinking; overestimation of threat probability and severity; negative expectancy", "~80%", "Behar et al., 2009"],
    ["Social Anxiety Features", "Social evaluation concerns, performance anxiety, fear of negative judgment; often comorbid or overlapping with GAD", "~60%", "Mennin et al., 2004"],
    ["Hypervigilance", "Heightened alertness to potential threat; excessive monitoring of environment and body sensations; SN hypersensitivity", "~75%", "Eysenck et al., 2007"],
  ],
  standardGuidelinesText: [
    "Current evidence-based guidelines for GAD position SSRIs (sertraline, escitalopram, paroxetine) and SNRIs (venlafaxine, duloxetine) as first-line pharmacological treatments, alongside structured psychotherapy — particularly cognitive behavioural therapy (CBT) with worry exposure components and relaxation training. NICE guidelines (2011, updated 2019), BAP guidelines (2014), WFSBP guidelines (2012), and CANMAT (2014) support this stepped-care framework, beginning with brief psychological interventions and escalating to combination pharmacotherapy and therapy for non-responders.",
    "For treatment-resistant GAD, augmentation with buspirone, pregabalin (particularly for somatic symptoms), or low-dose benzodiazepines (short-term) may be considered. Pregabalin has Level A evidence for GAD and is widely used where first-line agents are insufficient. Third-wave CBT approaches (ACT, metacognitive therapy) show additional benefit for worry-dominated presentations. Neuromodulation, including tDCS and TMS, is emerging as an adjunctive approach with growing evidence particularly for anxiety-depression comorbidity.",
    "SOZO FNON protocols are designed to complement and enhance standard-of-care treatments for GAD. The Doctor coordinates FNON neuromodulation with pharmacological management and psychotherapy, with particular attention to avoiding over-stimulation in anxious patients. Session-by-session monitoring with GAD-7 or HAM-A and documentation of any increase in anxiety or restlessness is standard protocol.",
  ],

  fnonFrameworkParagraph: "The FNON framework for GAD targets the corticolimbic imbalance at its core: insufficient prefrontal inhibitory control of hyperactive limbic threat circuits. Anodal tDCS and TPS to the right DLPFC preferentially augment prefrontal regulation of the amygdala, while cathodal stimulation of the right parietal-occipital region reduces posterior hypervigilance. taVNS and CES simultaneously modulate the autonomic-brainstem axis to reduce sympathetic dominance and restore vagal tone, directly addressing the HRV deficit that characterises GAD.",
  keyBrainRegions: [
    ["Right Dorsolateral Prefrontal Cortex (rDLPFC)", "Preferentially involved in emotional regulation and threat appraisal; hypoactivation fails to suppress amygdala reactivity; impaired worry inhibition", "RIGHT-sided anodal tDCS (F4) preferentially targets right-hemisphere emotional regulatory circuits for GAD; TPS rDLPFC", "Hilbert et al., 2014; Mennin et al., 2004"],
    ["Amygdala", "Bilateral hyperreactivity; excessive threat detection; impaired fear extinction; sustained negative affect; threat generalisation", "Indirect suppression via anodal right DLPFC top-down pathway; TPS deep limbic targeting; taVNS NTS-amygdala modulation", "Etkin & Wager, 2007; Shin & Liberzon, 2010"],
    ["Anterior Cingulate Cortex (ACC)", "Hyperactive dACC drives conflict monitoring; excessive error detection; impaired switching from threat to safety signals; worry perpetuation", "tDCS Fz montage for ACC engagement; taVNS modulates ACC via vagal-cingulate projections; TPS dACC targeting", "Bishop, 2007; Nitschke et al., 2009"],
    ["Ventromedial Prefrontal Cortex (vmPFC)", "Reduced extinction recall; impaired safety signal processing; deficient regulation of amygdala fear response during safety conditions", "tDCS F3/F4-Pz montage modulates mPFC-limbic axis; TPS mPFC targeting for extinction consolidation", "Milad & Quirk, 2012; Etkin et al., 2011"],
    ["Anterior Insula", "Interoceptive amplification; excessive monitoring of body signals; somatic anxiety substrate; SN node hyperactivation", "TPS insular targeting; taVNS modulates insula via visceral-NTS-insular pathway; body-focused relaxation enhances effect", "Paulus & Stein, 2006; Simmons et al., 2008"],
    ["Hippocampus", "Context fear generalisation; impaired contextual safety discrimination; reduced hippocampal volume associated with chronic stress", "TPS hippocampal deep targeting; taVNS via NTS-LC-hippocampal pathway promotes neuroplasticity and extinction memory", "Bhagya et al., 2015"],
    ["Orbitofrontal Cortex (OFC)", "Impaired flexible appraisal of threat vs. safety; negative expectancy bias; perseverative threat evaluation in OFC-amygdala loop", "TPS OFC-mPFC combined targeting; anodal tDCS bilateral prefrontal montage includes OFC modulation", "Grupe & Nitschke, 2013"],
    ["Posterior Parietal Cortex (PPC)", "Hypervigilance substrate; excessive attentional capture by threat stimuli; impaired disengagement from threat-related stimuli", "Cathodal tDCS Pz for posterior hypervigilance reduction; combined with attentional training tasks", "Fox et al., 2001"],
    ["Locus Coeruleus (LC)", "Noradrenergic hyperactivation; excessive NE tone driving arousal, restlessness, and somatic anxiety; autonomic dysregulation", "taVNS activates NTS→LC pathway to modulate NE tone; paradoxical normalisation via adaptive LC downregulation with regular stimulation", "Berridge & Waterhouse, 2003"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Primary vagal afferent relay; mediates all taVNS effects on brainstem, limbic, and cortical circuits; anxiety modulation entry point", "Primary target of taVNS for anxiety; NTS→LC→amygdala pathway modulates threat reactivity", "Fang et al., 2016"],
    ["Bed Nucleus of Stria Terminalis (BNST)", "Extended amygdala; mediates sustained anxiety (as opposed to phasic fear); responsible for sustained apprehensive state in GAD", "Indirect modulation via amygdala-taVNS and DLPFC-amygdala pathways; TPS deep targeting of extended amygdala region", "Davis et al., 2010"],
    ["Striatum / Ventral Striatum", "Impaired reward prediction and safety signal encoding; reduced positive reward anticipation in anxious individuals", "Indirect modulation via DLPFC-striatal pathway; TPS deep ventral striatum targeting for reward deficit", "Levita et al., 2012"],
    ["Thalamus", "Sensory gating impairment; excessive relay of threat-relevant signals; disrupted thalamo-cortical inhibitory regulation", "TPS thalamic targeting; taVNS modulates thalamo-cortical synchrony via brainstem-thalamic relays", "Strawn et al., 2012"],
    ["Periaqueductal Gray (PAG)", "Defensive response centre; active in anxiety states; mediates freeze, flight, fight, and immobility responses", "Indirect modulation via taVNS NTS-PAG pathway; reduces defensive behavioural states during stimulation", "Bandler et al., 2000"],
    ["Basal Ganglia", "Habit formation of anxious safety behaviours; impaired updating of threat contingencies; anxiety habit perpetuation", "Indirect modulation via prefrontal-striatal pathway upregulation via anodal DLPFC tDCS", "Pitman et al., 2012"],
    ["Raphe Nuclei", "Serotonergic regulation of anxiety; 5-HT1A receptor hypofunction linked to GAD; mood-anxiety interface", "taVNS modulates serotonergic raphe via brainstem connections; CES may enhance 5-HT tone", "Nichols & Nichols, 2008"],
  ],
  keyFunctionalNetworks: [
    ["Salience Network (SN)", "Anterior insula, dACC, amygdala, BNST, brainstem", "Hyperactivity; excessive threat detection and interoceptive amplification; failure to habituate to non-threatening stimuli; GAD core circuit", "Cathodal right anterior insula tDCS (indirect via temporal); TPS SN hubs; taVNS reduces SN hyperactivity via vagal-insular pathway", "Seeley et al., 2007; Paulus & Stein, 2006"],
    ["Central Executive Network (CEN)", "DLPFC, PPC, lateral PFC, anterior PFC", "Hypoactivation; impaired top-down suppression of worry; reduced prefrontal cognitive control of amygdala and SN", "PRIMARY TARGET: anodal tDCS F4 (right DLPFC) or bilateral F3/F4; TPS DLPFC; HDCkit bilateral for severe GAD", "Mohlman & Gorman, 2005; Dolcos et al., 2011"],
    ["Default Mode Network (DMN)", "mPFC, PCC, precuneus, angular gyrus, hippocampus", "Hyperconnectivity associated with rumination and worry; impaired deactivation during external task demands", "Cathodal tDCS Pz (DMN suppression); TPS PCC; combined cognitive engagement tasks to reduce DMN activity", "Broyd et al., 2009"],
    ["Limbic Network", "Amygdala, hippocampus, hypothalamus, OFC, sgACC, BNST, PAG", "Hyperreactivity; sustained threat state; impaired extinction; autonomic dysregulation; HPA axis overactivation", "taVNS for limbic-autonomic downregulation; TPS deep limbic targeting; CES broad spectrum limbic modulation", "Price & Drevets, 2010; Etkin & Wager, 2007"],
    ["Autonomic Regulatory Network", "Brainstem (NTS, LC, DMV), insula, ACC, vmPFC, hypothalamus", "Chronically elevated sympathetic tone; reduced HRV; impaired parasympathetic recovery; cardiac vagal tone deficit", "taVNS PRIMARY for autonomic regulation — restores vagal tone; CES reduces arousal; combined S-O-Z-O sequence optimises autonomic balance", "Thayer et al., 2012; Koenig et al., 2016"],
    ["Attention Network", "FEF, IPS, TPJ, right DLPFC, right inferior frontal gyrus", "Attentional bias to threat; impaired disengagement from threat stimuli; excessive vigilance scanning; hyperarousal", "Anodal right DLPFC tDCS enhances right-hemisphere attentional inhibitory control; combined attentional retraining tasks", "Eysenck et al., 2007; Bar-Haim et al., 2007"],
    ["Frontoparietal Control Network", "Lateral PFC, inferior parietal lobule, dACC, precuneus", "Impaired metacognitive control of worry; difficulty recognising and stopping worry cycles; reduced cognitive flexibility", "TPS frontoparietal targeting; tDCS bilateral DLPFC for metacognitive control enhancement", "Wells, 2011; Hu et al., 2017"],
  ],
  networkAbnormalities: "GAD is characterised by Salience Network hyperactivity (excessive threat detection), CEN hypoactivation (insufficient worry suppression), DMN-SN hyperconnectivity (rumination-threat perpetuation loop), and autonomic nervous system dysregulation with chronically reduced HRV. The core circuit-level target is restoring CEN dominance over SN and limbic reactivity.",
  conceptualFramework: "SOZO FNON GAD protocol targets: (1) Upregulate right DLPFC CEN control via anodal tDCS/TPS; (2) Suppress SN/limbic hyperreactivity via cathodal stimulation and taVNS; (3) Restore autonomic balance and HRV via taVNS CES combination; (4) Consolidate extinction memory via TPS hippocampal/vmPFC stimulation paired with cognitive therapeutic tasks.",

  clinicalPhenotypes: [
    ["Cognitive-Worry Dominant", "Excessive cognitive worry, catastrophising, mental reviewing; CEN hypoactivation prominent; responds to CBT + DLPFC upregulation", "Mohlman & Gorman, 2005"],
    ["Somatic-Autonomic Dominant", "Physical symptoms predominant: muscle tension, palpitations, GI symptoms, fatigue; SN/autonomic dysregulation core; responds to taVNS/CES + somatic therapies", "Barsky & Borus, 1999"],
    ["Hypervigilance Dominant", "Excessive environmental threat monitoring; attentional bias; right hemisphere hyperactivation; responds to attentional retraining + right hemisphere modulation", "Eysenck et al., 2007"],
    ["Sleep-Disrupted Dominant", "Severe sleep onset insomnia; nocturnal hyperarousal; worry at bedtime; strong autonomic dysregulation; taVNS/CES evening protocol + sleep hygiene", "Benca et al., 1992"],
    ["Comorbid Depression-Anxiety", "Mixed anxious-depressive presentation; both anhedonia and anxiety; combined DLPFC bilateral + limbic targeting; pharmacotherapy co-management", "Fava et al., 2000"],
    ["Social Anxiety Overlap", "Social evaluation fears alongside generalised worry; right frontal asymmetry; right DLPFC upregulation + social exposure combined", "Mennin et al., 2004"],
    ["Treatment-Resistant GAD", "Failure of ≥2 adequate pharmacotherapy trials; high SN activation; bilateral DLPFC + deep TPS targeting required; maximise taVNS/CES", "Pittenger & Bhartiya, 2019"],
    ["Panic-Comorbid GAD", "Panic attacks alongside chronic worry; high SN/LC reactivity; careful stimulation parameters; TPS over DLPFC not insula; taVNS moderate intensity", "Craske & Barlow, 2007"],
    ["Elderly GAD", "Late-onset or persisting GAD in older adults; white matter hyperintensities; lower stimulation parameters; CES preferred; close monitoring", "Wetherell et al., 2013"],
  ],
  symptomNetworkMapping: [
    ["Excessive Worry", "CEN hypoactivation", "DMN hyperactivity", "tDCS F4 anodal (rDLPFC)", "Metacognitive therapy + tDCS"],
    ["Restlessness / Keyed-Up", "SN hyperactivity", "LC/NE excess", "taVNS + CES arousal reduction", "Progressive muscle relaxation task"],
    ["Fatigue", "CEN hypoactivation", "HPA dysregulation", "tDCS F3/F4 bilateral", "Behavioural activation"],
    ["Concentration Difficulty", "CEN hypoactivation", "SN attentional capture", "tDCS DLPFC bilateral", "Attention training concurrent"],
    ["Muscle Tension", "SN/Autonomic hyperactivity", "Insula hyperactivation", "taVNS + CES", "Biofeedback + body scan"],
    ["Sleep Disturbance", "Autonomic dysregulation", "LC hyperactivation", "CES evening protocol", "Sleep restriction therapy"],
    ["Autonomic Arousal", "Autonomic network dysregulation", "SN-insula hyperactivity", "taVNS PRIMARY target", "HRV biofeedback concurrent"],
    ["Avoidance", "CEN-vmPFC deficit", "Limbic threat overrides PFC", "tDCS vmPFC + TPS", "Exposure therapy concurrent"],
    ["Hypervigilance", "Right DLPFC-parietal network", "SN excessive gating", "Cathodal Pz + anodal F4", "Attentional retraining concurrent"],
    ["Catastrophising", "CEN hypoactivation", "DMN-SN loop", "tDCS bilateral DLPFC", "CBT worry restructuring concurrent"],
  ],
  montageSelectionRows: [
    ["Cognitive-Worry dominant (right DLPFC focus)", "Anodal F4, cathodal Pz — 2mA 20min"],
    ["Somatic-Autonomic dominant (taVNS primary)", "taVNS bilateral cymba conchae — 0.5mA 30–60min"],
    ["Bilateral DLPFC (treatment-resistant / severe)", "HDCkit anodal F3+F4 bilateral — 2mA 20min each"],
    ["DMN suppression add-on", "Cathodal Pz combined with anodal F3/F4"],
    ["CES for global arousal reduction", "Alpha-Stim AID earclip — 0.5mA 60min"],
    ["TPS rDLPFC (phenotype-specific)", "NEUROLITH® F4 region — 0.2mJ/mm² 4000 pulses"],
    ["TPS prefrontal-limbic (TRG phenotype)", "NEUROLITH® DLPFC + deep limbic — 6000 pulses"],
    ["taVNS + CES combination (autonomic phenotype)", "Sequential: taVNS 30min then CES 60min"],
    ["Sleep-disrupted phenotype — evening protocol", "CES 0.5mA 60min evenings; taVNS before sleep"],
    ["Hypervigilance phenotype (right lateralised)", "Anodal F4 only, cathodal Fz — 1.5mA 20min"],
    ["Comorbid depression-anxiety (bilateral)", "Anodal F3+F4, cathodal bilateral temporal — 2mA"],
    ["Elderly protocol (reduced parameters)", "tDCS 1mA 15min; CES 0.25mA; TPS 0.15mJ/mm²"],
    ["Maintenance phase (after 10 sessions)", "Reduce to 2× weekly; CES daily home use"],
  ],
  polarityPrincipleText: "In GAD, polarity selection prioritises restoring right-hemisphere prefrontal inhibitory control while reducing posterior hypervigilance. Right DLPFC anodal stimulation is the primary approach. For bilateral presentations or TRD-GAD, bilateral DLPFC anodal is used. Cathodal stimulation over posterior parietal (Pz) or right temporal regions reduces hypervigilance and posterior threat-vigilance networks.",
  polarityTable: [
    ["Anodal F4 (right DLPFC)", "Upregulates right prefrontal inhibitory control of amygdala; primary GAD cognitive worry target"],
    ["Anodal F3 (left DLPFC)", "Bilateral combined for TRD-GAD; addresses comorbid depression component"],
    ["Cathodal Pz", "Suppresses posterior hypervigilance/DMN; combined with anodal frontal"],
    ["Cathodal right temporal", "Reduces right hemisphere SN hyperactivity for somatic-autonomic phenotype"],
    ["taVNS left cymba", "Primarily autonomic — restores vagal tone, reduces LC/NE excess, modulates amygdala via NTS pathway"],
  ],

  classicTdcsProtocols: [
    ["C1", "Anxiety / cognitive worry", "F4 (right DLPFC)", "Pz", "2mA 20min, 10 sessions", "Level C-B"],
    ["C2", "Anxiety / bilateral", "F3+F4 bilateral anodal", "Bilateral temporal cathodal", "2mA 20min, 10 sessions", "Emerging"],
    ["C3", "Anxiety / left frontal asymmetry", "F3 (left DLPFC)", "F4 cathodal", "1.5mA 20min", "Level C"],
    ["C4", "Comorbid anxiety-depression", "F3 anodal", "Pz cathodal", "2mA 20min, 10 sessions", "Level B (depression component)"],
    ["C5", "Somatic anxiety / insula", "Temporal anodal near T3", "Contralateral temporal", "1.5mA 20min", "Exploratory"],
    ["C6", "Sleep-disrupted anxiety", "F4 anodal", "Pz cathodal (evening)", "1.5mA 15min", "Exploratory"],
    ["C7", "Attention bias reduction", "F4 anodal", "Pz cathodal", "2mA 20min + attention retraining", "Emerging"],
    ["C8", "Elderly GAD", "F4 anodal", "Pz cathodal", "1mA 15min", "Exploratory"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Cognitive-worry dominant", "CEN hypoactivation + DMN hyperactivity", "F4 anodal + Pz cathodal", "Upregulate right PFC control; suppress DMN rumination"],
    ["F2", "Somatic-autonomic dominant", "SN/autonomic hyperreactivity", "taVNS bilateral + CES (primary modalities)", "Restore vagal tone; downregulate SN-insula axis"],
    ["F3", "Hypervigilance dominant", "Right hemisphere threat hyperactivation", "F4 anodal + right temporal cathodal", "Lateralised PFC upregulation; right posterior suppression"],
    ["F4", "TRG-GAD", "Bilateral CEN-SN imbalance", "HDCkit F3+F4 bilateral anodal", "Maximal bilateral prefrontal cognitive control restoration"],
    ["F5", "Sleep-disrupted anxiety", "Autonomic nocturnal hyperarousal", "CES 60min evening + taVNS pre-sleep", "Evening autonomic downregulation; sleep onset facilitation"],
    ["F6", "Comorbid depression-anxiety", "Bilateral CEN + Limbic", "F3+F4 bilateral + TPS limbic", "Address both depressive anhedonia and anxiety network imbalance"],
  ],
  classicTpsProtocols: [
    ["T1", "Core anxiety / DLPFC", "Right DLPFC", "0.2mJ/mm²", "4000 pulses", "Emerging"],
    ["T2", "Worry / prefrontal", "Bilateral DLPFC", "0.2mJ/mm²", "4000 pulses per side", "Exploratory"],
    ["T3", "Deep limbic / amygdala indirect", "Temporal-limbic region", "0.25mJ/mm²", "3000 pulses", "Exploratory"],
    ["T4", "TRG-GAD / holocranial", "DLPFC + deep regions", "0.2mJ/mm²", "6000 pulses", "Exploratory"],
    ["T5", "Comorbid anxiety-depression", "DLPFC bilateral + limbic", "0.2mJ/mm²", "5000 pulses", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Cognitive-worry dominant", "CEN hypoactivation", "Right DLPFC (F4 region)", "0.2mJ/mm² × 4000 pulses — upregulate right PFC worry inhibition"],
    ["FT2", "Hypervigilance dominant", "Right frontoparietal hyperactivation", "Right DLPFC + posterior parietal", "0.2mJ/mm² × 4000 pulses — lateralised PFC + parietal modulation"],
    ["FT3", "Somatic-autonomic dominant", "Insula / SN hyperactivity", "Left DLPFC + insula region (indirect)", "0.2mJ/mm² × 3000 pulses — indirect SN modulation"],
    ["FT4", "Treatment-resistant GAD", "Bilateral CEN + limbic", "DLPFC bilateral + deep limbic (6000 pulses)", "0.2mJ/mm² bilateral — maximal network normalisation"],
    ["FT5", "Sleep-disrupted phenotype", "Autonomic + prefrontal combined", "F4 + temporal TPS then CES", "0.15mJ/mm² × 3000 + evening CES 60min sequence"],
    ["FT6", "Comorbid depression-anxiety", "Bilateral CEN + DMN suppression", "Bilateral DLPFC + PCC holocranial", "0.2mJ/mm² × 5000 — combined depression and anxiety network targets"],
    ["FT7", "Panic-comorbid GAD", "SN hyperactivity (not direct insula)", "Right DLPFC only (avoid insula direct)", "Conservative 0.15mJ/mm² × 3000 — careful SN modulation"],
    ["FT8", "Elderly GAD", "Age-related white matter changes", "Right DLPFC reduced intensity", "0.15mJ/mm² × 2500 — adapted for elderly parameters"],
    ["FT9", "Maintenance protocol", "Sustained CEN upregulation", "Right DLPFC monthly maintenance", "0.2mJ/mm² × 2000 — monthly consolidation sessions"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Cognitive-Worry Dominant",
      combinations: [
        ["S — Stabilise", "taVNS 30min (pre-session) — reduce baseline arousal before cognitive stimulation", "Normalise autonomic baseline; prevent stimulation-induced anxiety increase"],
        ["O — Optimise", "tDCS F4 anodal 2mA 20min — upregulate right DLPFC excitability", "Enhance prefrontal cognitive control readiness for cognitive task engagement"],
        ["Z — Zone", "TPS right DLPFC 0.2mJ/mm² 4000 pulses — deep right prefrontal penetration", "Deep CEN upregulation; worry inhibition circuit engagement"],
        ["O — Outcome", "CBT worry restructuring concurrent + CES 60min evening — consolidate", "Pair stimulation with metacognitive therapy; evening CES for daily anxiety reduction"],
      ],
    },
    {
      phenotype: "Somatic-Autonomic Dominant",
      combinations: [
        ["S — Stabilise", "CES Alpha-Stim 0.5mA 60min — primary autonomic stabilisation for somatic phenotype", "Reduce sympathetic hyperarousal; improve HRV; address somatic baseline"],
        ["O — Optimise", "taVNS bilateral cymba 0.5mA 30min — primary vagal upregulation", "Restore parasympathetic dominance; normalise HRV; modulate insula-NTS pathway"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 3000 pulses — indirect SN modulation", "Top-down modulation of insula-SN via prefrontal pathway"],
        ["O — Outcome", "Biofeedback + body scan concurrent — somatic awareness retraining", "Body-focused attention training with normalised autonomic state"],
      ],
    },
    {
      phenotype: "Hypervigilance Dominant",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 30min — reduce hyperarousal baseline", "Lower vigilance threshold before targeted stimulation"],
        ["O — Optimise", "tDCS F4 anodal + right temporal cathodal 2mA 20min", "Lateralised upregulation right PFC; simultaneous right posterior suppression"],
        ["Z — Zone", "TPS right DLPFC + posterior parietal 0.2mJ/mm² 4000 pulses", "Right frontoparietal network rebalancing"],
        ["O — Outcome", "Attentional retraining concurrent (dot probe modification) + taVNS", "Pair neural priming with evidence-based attentional bias modification"],
      ],
    },
    {
      phenotype: "Sleep-Disrupted Dominant",
      combinations: [
        ["S — Stabilise", "taVNS afternoon session 0.5mA 20min — pre-evening autonomic preparation", "Shift autonomic balance toward parasympathetic dominance before sleep window"],
        ["O — Optimise", "tDCS F4 anodal 2mA 20min (daytime) — address cognitive worry component", "Daytime prefrontal upregulation; reduce daytime worry that feeds nocturnal hyperarousal"],
        ["Z — Zone", "CES 0.5mA 60min evening — primary sleep-onset facilitation", "Evening autonomic downregulation; melatonin-promoting low-frequency current"],
        ["O — Outcome", "Sleep restriction therapy concurrent + taVNS pre-sleep", "Pair neural priming with evidence-based sleep consolidation protocol"],
      ],
    },
    {
      phenotype: "Comorbid Depression-Anxiety",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — address overlapping autonomic and mood dysregulation", "Broad-spectrum stabilisation for mixed anxious-depressive state"],
        ["O — Optimise", "tDCS F3+F4 bilateral anodal 2mA 20min — bilateral DLPFC", "Address both left frontal depression deficit and right frontal anxiety control"],
        ["Z — Zone", "TPS bilateral DLPFC 0.2mJ/mm² 5000 pulses — deep bilateral CEN", "Maximal bilateral network normalisation for mixed presentation"],
        ["O — Outcome", "Integrated CBT-BA protocol concurrent + taVNS", "Combined worry and depression-focused therapy with neural priming"],
      ],
    },
    {
      phenotype: "Treatment-Resistant GAD",
      combinations: [
        ["S — Stabilise", "taVNS 40min + CES 60min combination — maximal autonomic stabilisation", "Establish strong autonomic baseline for intensive bilateral stimulation"],
        ["O — Optimise", "HDCkit bilateral F3+F4 anodal 2mA 20min each — maximal bilateral CEN", "Maximum bilateral prefrontal upregulation for treatment-resistant cases"],
        ["Z — Zone", "TPS bilateral DLPFC + deep limbic 0.2mJ/mm² 6000 pulses", "Deep bilateral prefrontal + limbic network normalisation"],
        ["O — Outcome", "ACT (Acceptance and Commitment Therapy) concurrent + maintenance CES", "Third-wave therapy paired with maximal neural priming; daily home CES"],
      ],
    },
    {
      phenotype: "Panic-Comorbid GAD",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — primary stabilisation; avoid strong taVNS initially", "Gentle autonomic stabilisation; avoid rapid vagal activation that may paradoxically trigger panic"],
        ["O — Optimise", "tDCS F4 anodal 1.5mA 15min (conservative) — right DLPFC only", "Cautious prefrontal upregulation; reduced parameters to avoid over-stimulation"],
        ["Z — Zone", "TPS right DLPFC only 0.15mJ/mm² 3000 pulses — conservative", "Conservative deep stimulation; avoid insula or direct SN targeting"],
        ["O — Outcome", "Interoceptive exposure concurrent — gradual panic tolerance training", "Pair primed PFC control with graduated exposure to bodily sensations"],
      ],
    },
    {
      phenotype: "Social Anxiety Overlap",
      combinations: [
        ["S — Stabilise", "taVNS 20min — autonomic stabilisation before social exposure tasks", "Reduce baseline sympathetic arousal for social situations"],
        ["O — Optimise", "tDCS F4 anodal 2mA 20min + left frontal cathodal", "Right-lateralised approach for social anxiety right frontal asymmetry reversal"],
        ["Z — Zone", "TPS right DLPFC 0.2mJ/mm² 4000 pulses", "Right prefrontal deep stimulation for social-evaluative anxiety circuit"],
        ["O — Outcome", "Social exposure therapy concurrent + CES for maintenance", "Social anxiety hierarchy exposure with neural priming; CES for daily generalisation"],
      ],
    },
    {
      phenotype: "Elderly GAD",
      combinations: [
        ["S — Stabilise", "CES 0.25mA 30min — gentle autonomic stabilisation for elderly", "Age-appropriate low-intensity autonomic modulation; assess tolerance"],
        ["O — Optimise", "tDCS F4 anodal 1mA 15min — reduced parameters for elderly", "Conservative prefrontal stimulation adapted for age-related cortical changes"],
        ["Z — Zone", "TPS right DLPFC 0.15mJ/mm² 2500 pulses — reduced for elderly", "Age-adapted deep stimulation parameters; longer recovery intervals"],
        ["O — Outcome", "Mindfulness-based stress reduction concurrent + daily low-dose CES", "Evidence-based psychological approach combined with gentle daily home practice"],
      ],
    },
  ],

  taskPairingRows: [
    ["Worry Postponement Task", "Cognitive-worry dominant", "tDCS F4 anodal active", "Schedule structured worry time; metacognitive exposure"],
    ["Attentional Retraining (Dot Probe)", "Hypervigilance dominant", "tDCS F4 anodal active", "Modify attentional bias away from threat stimuli"],
    ["HRV Biofeedback", "Somatic-autonomic dominant", "taVNS active", "Real-time autonomic regulation training"],
    ["Progressive Muscle Relaxation", "Muscle tension / somatic", "CES active", "Somatic tension reduction task concurrent with CES"],
    ["Behavioural Activation", "Comorbid depression-anxiety", "tDCS F3+F4 bilateral active", "Increase approach behaviour and positive reinforcement"],
    ["Exposure Hierarchy (worry)", "TRG-GAD / avoidance", "TPS post-session priming", "Graduated exposure to avoided situations or worry content"],
  ],
  outcomeMeasures: "Primary: GAD-7 (session-by-session) and HAM-A (baseline, 5-session, 10-session, 1-month). Secondary: Penn State Worry Questionnaire (PSWQ), HRV measurement (autonomic phenotype), State-Trait Anxiety Inventory (STAI), Pittsburgh Sleep Quality Index (PSQI) for sleep phenotype, WHO-5 Wellbeing Index, Sheehan Disability Scale (functional impairment). Safety: monitor for increased anxiety, panic symptoms, or sleep disturbance.",

  medicationSectionTitle: "Pharmacotherapy Context for GAD",
  medicationSectionText: "First-line pharmacotherapy for GAD includes SSRIs (sertraline, escitalopram, paroxetine) and SNRIs (venlafaxine XR, duloxetine). Pregabalin has Level A evidence for GAD and may be particularly effective for somatic-autonomic phenotype. Buspirone is a non-sedating option for mild-moderate GAD. Benzodiazepines may be used short-term for acute anxiety but are not recommended for maintenance. Hydroxyzine is an antihistamine with anxiolytic properties useful for short-term management. The treating Doctor coordinates pharmacotherapy with FNON neuromodulation; particular attention is paid to serotonergic agents (may have delayed onset) and the potential synergistic effects of pregabalin with taVNS autonomic modulation. Patients on benzodiazepines chronically should be reviewed — gradual tapering strategies may be facilitated by FNON intervention.",

  references: {
    foundational: [
      "Kessler RC, Berglund P, Demler O, et al. (2005). Lifetime prevalence and age-of-onset distributions of DSM-IV disorders in the National Comorbidity Survey Replication. Arch Gen Psychiatry, 62(6), 593–602. doi:10.1001/archpsyc.62.6.593",
      "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR). APA Publishing.",
      "Thayer JF, Åhs F, Fredrikson M, Sollers JJ, Wager TD. (2012). A meta-analysis of heart rate variability and neuroimaging studies: Implications for heart rate variability as a marker of stress and health. Neurosci Biobehav Rev, 36(2), 747–756. doi:10.1016/j.neubiorev.2011.11.009",
      "Etkin A, Wager TD. (2007). Functional neuroimaging of anxiety: A meta-analysis of emotional processing in PTSD, social anxiety disorder, and specific phobia. Am J Psychiatry, 164(10), 1476–1488. doi:10.1176/appi.ajp.2007.07030504",
      "Mennin DS, Heimberg RG, Turk CL, Fresco DM. (2005). Preliminary evidence for an emotion dysregulation model of generalized anxiety disorder. Behav Res Ther, 43(10), 1281–1310. doi:10.1016/j.brat.2004.08.008",
      "Borkovec TD, Ruscio AM. (2001). Psychotherapy for generalized anxiety disorder. J Clin Psychiatry, 62(Suppl 11), 37–45.",
    ],
    tdcs: [
      "Sagliano L, Atripaldi D, De Vita D, D'Olimpio F, Trojano L. (2019). Non-invasive brain stimulation in generalized anxiety disorder: A systematic review. J Affect Disord, 255, 7–14. doi:10.1016/j.jad.2019.05.011",
      "Thibaut F, Faber G, Benadhira R, et al. (2014). Transcranial direct current stimulation in the treatment of generalized anxiety disorder. Eur Psychiatry, 29(Suppl 1), 1. doi:10.1016/S0924-9338(14)77770-7",
      "Nitsche MA, Cohen LG, Wassermann EM, et al. (2008). Transcranial direct current stimulation: State of the art 2008. Brain Stimul, 1(3), 206–223. doi:10.1016/j.brs.2008.06.004",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with transcranial direct current stimulation (tDCS): Challenges and future directions. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Palm U, Hasan A, Strube W, Padberg F. (2016). tDCS for the treatment of depression: A comprehensive review. Eur Arch Psychiatry Clin Neurosci, 266(8), 681–694. doi:10.1007/s00406-016-0674-9",
      "Loo CK, Sachdev P, Martin D, et al. (2010). A double-blind, sham-controlled trial of transcranial direct current stimulation for the treatment of depression. Int J Neuropsychopharmacol, 13(1), 61–69. doi:10.1017/S1461145709990411",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Ironside M, O'Shea J, Cowen PJ, Harmer CJ. (2016). Frontal cortex stimulation reduces vigilance to threat: Implications for the treatment of depression and anxiety. Biol Psychiatry, 79(10), 823–830. doi:10.1016/j.biopsych.2015.06.012",
      "Fregni F, Boggio PS, Nitsche MA, Marcolin MA, Rigonatti SP, Pascual-Leone A. (2006). Treatment of major depression with transcranial direct current stimulation. Bipolar Disord, 8(2), 203–204. doi:10.1111/j.1399-5618.2006.00291.x",
      "Boggio PS, Rigonatti SP, Ribeiro RB, et al. (2008). A randomized, double-blind clinical trial on the efficacy of cortical direct current stimulation for the treatment of major depression. Int J Neuropsychopharmacol, 11(2), 249–254. doi:10.1017/S1461145707007833",
    ],
    tps: [
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and non-invasive brain stimulation: A tale of two loops. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease — a new navigated focal brain therapy. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930. doi:10.1016/j.tics.2016.09.007",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Peterchev AV, Wagner TA, Miranda PC, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335. doi:10.1111/j.1525-1403.2011.00378.x",
    ],
    tavns: [
      "Farmer AD, Strzelczyk A, Finisguerra A, et al. (2020). International consensus based review and recommendations for minimum reporting standards in research on transcutaneous vagus nerve stimulation. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network in major depressive disorder. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Hsu WY, Ku Y, Zanto TP, Gazzaley A. (2015). Effects of noninvasive brain stimulation on cognitive function in healthy aging and Alzheimer's disease: A systematic review and meta-analysis. Neurobiol Aging, 36(8), 2348–2359. doi:10.1016/j.neurobiolaging.2015.04.016",
      "Burger AM, Van der Does W, Brosschot JF, Verkuil B. (2020). Transcutaneous vagus nerve stimulation reduces the startle response in anxious individuals. Biol Psychol, 149, 107800. doi:10.1016/j.biopsycho.2019.107800",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of the brain-gut axis in psychiatric and inflammatory disorders. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Rong P, Liu J, Wang L, et al. (2016). Effect of transcutaneous auricular vagus nerve stimulation on major depressive disorder: A nonrandomized controlled pilot study. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
      "Steenbergen L, Sellaro R, Stock AK, Verkuil B, Beste C, Colzato LS. (2015). Transcutaneous vagus nerve stimulation (tVNS) enhances response inhibition via action of norepinephrine on the prefrontal cortex. Brain Stimul, 8(6), 1155–1160. doi:10.1016/j.brs.2015.09.001",
      "Borges U, Laborde S, Raab M. (2019). Influence of transcutaneous vagus nerve stimulation on cardiac vagal activity: not all targets are equal. Brain Stimul, 12(3), 727–729. doi:10.1016/j.brs.2019.01.015",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of cranial electrotherapy stimulation for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Kavirajan HC, Lueck K, Cho K. (2014). Alternating current cranial electrotherapy stimulation (CES) use in outpatient psychiatric and pain treatment: A retrospective analysis. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review: A safer alternative to psychopharmaceuticals in the treatment of depression. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Cork RC, Wood P, Ming N, Shepherd C, Eddy J, Price L. (2004). The effect of cranial electrotherapy stimulation (CES) on pain associated with fibromyalgia. Internet J Anesthesiol, 8(2).",
    ],
    network: [
      "Seeley WW, Menon V, Schatzberg AF, et al. (2007). Dissociable intrinsic connectivity networks for salience processing and executive control. J Neurosci, 27(9), 2349–2356. doi:10.1523/JNEUROSCI.5587-06.2007",
      "Broyd SJ, Demanuele C, Debener S, Helps SK, James CJ, Sonuga-Barke EJ. (2009). Default-mode brain dysfunction in mental disorders: A systematic review. Neurosci Biobehav Rev, 33(3), 279–296. doi:10.1016/j.neubiorev.2008.09.002",
      "Mohlman J, Gorman JM. (2005). The role of executive functioning in CBT: A pilot study with anxious older adults. Behav Res Ther, 43(4), 447–465. doi:10.1016/j.brat.2004.03.007",
      "Bishop SJ. (2007). Neurocognitive mechanisms of cognitive control: The significance of the ventral PFC. Trends Cogn Sci, 11(12), 506–511. doi:10.1016/j.tics.2007.10.001",
      "Hilbert K, Lueken U, Beesdo-Baum K. (2014). Neural structures, functioning and connectivity in generalized anxiety disorder and interaction with neuroendocrine systems: A systematic review. J Affect Disord, 158, 114–126. doi:10.1016/j.jad.2014.01.022",
    ],
  },
};
