'use strict';
module.exports = {
  conditionFull: "Chronic Pain / Fibromyalgia",
  conditionShort: "Chronic Pain",
  conditionSlug: "chronic_pain",
  documentNumber: "SOZO-CP-PROT-001",
  offLabelCoverText: "tDCS and TPS use in Chronic Pain / Fibromyalgia is INVESTIGATIONAL / OFF-LABEL in some applications. tDCS has Level A evidence for fibromyalgia pain reduction; Level B for other chronic pain conditions.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level A evidence (fibromyalgia); Level B (chronic neuropathic pain)', 'Standard informed consent + off-label note'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; growing evidence for chronic pain neuromodulation', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia; growing evidence for pain', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of chronic pain condition (fibromyalgia, chronic widespread pain, CRPS Type I, neuropathic pain, central sensitisation syndrome) by qualified physician or pain specialist",
    "Pain duration ≥3 months; moderate-to-severe pain intensity (NRS ≥5/10 average) at baseline",
    "Age 18–70 years (exceptions at Doctor discretion with documented rationale)",
    "Stable pain medication regimen for ≥4 weeks prior to enrolment, or actively managed by prescribing Doctor",
    "Capacity to provide informed consent",
    "Willing and able to attend sessions as prescribed",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Identified reversible structural cause of pain not yet treated (tumour, compressive myelopathy, etc.)",
    "CRPS Type II (causalgia) — nerve injury-based; specialist pain team co-management required",
    "Current active psychosis or severe psychiatric decompensation",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Comorbid psychiatric disorders (depression, anxiety, PTSD) — address comorbidities; adapt montage to address both pain and mood",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment by Doctor",
    "Epilepsy or seizure history — formal risk assessment required",
    "Pregnancy — taVNS/CES preferred; tDCS/TPS at Doctor discretion",
    "Chronic opioid use — risk of opioid-taVNS interaction (opioid-vagal interactions); pain specialist co-management",
    "Complex Regional Pain Syndrome (CRPS) — specialist pain team co-management required",
    "Severe fibromyalgia with significant cognitive impairment ('fibrofog') — adapted pacing",
    "Peripheral neuropathy with electrode site involvement — adapt electrode placement",
    "Recent major surgery or trauma — medical clearance before commencing pain protocol",
  ],

  overviewParagraph: "Chronic pain is one of the most prevalent and disabling conditions globally, affecting approximately 20% of adults in high-income countries. Fibromyalgia, affecting approximately 2–5% of the population (predominantly women), is characterised by widespread musculoskeletal pain, fatigue, cognitive disturbances ('fibrofog'), sleep disturbance, and affective symptoms. Chronic pain conditions share a common pathophysiological substrate of central sensitisation — a state of amplified and dysregulated nociceptive processing in the central nervous system — distinct from peripheral tissue damage. This central sensitisation provides the neurophysiological rationale for brain-targeted neuromodulation: correcting the dysfunctional cortical pain processing networks rather than targeting peripheral nociceptors. tDCS targeting the primary motor cortex has Level A evidence for fibromyalgia pain reduction from multiple RCTs, and tDCS/TPS targeting broader pain networks is an evidence-based adjunct to comprehensive pain management.",
  fnonNetworkParagraph: "Chronic pain and fibromyalgia are network disorders of pain processing amplification. The FNON framework identifies the corticothalamic pain matrix abnormalities — increased SN and insula excitability, disrupted descending pain inhibitory pathways, and aberrant DMN-pain network hyperconnectivity — as the core circuit-level targets. SOZO addresses central sensitisation by upregulating the primary motor cortex (M1-DLPFC) to enhance descending inhibitory control, modulating the insula and ACC pain salience circuits via TPS, and activating descending pain inhibitory pathways via taVNS. This network pain model is supported by Tan et al. 2023 (16 citations) and Bhatt et al. 2020 (269 citations).",
  networkDisorderParagraphs: [
    "Neuroimaging studies of fibromyalgia and chronic pain consistently demonstrate amplified pain-related brain activation — reduced thresholds for nociceptive stimulus processing, expanded cortical pain representations, and altered functional connectivity within the pain matrix. The insula (particularly anterior insula), ACC, and somatosensory cortex show increased activation to non-painful mechanical stimuli in fibromyalgia patients compared to healthy controls — a direct neuroimaging correlate of allodynia and central sensitisation.",
    "Resting-state connectivity analyses reveal that fibromyalgia is associated with increased functional connectivity between the default mode network and pain-processing regions (particularly the insula). This DMN-pain network hyperconnectivity means that even at rest, pain-relevant circuits are hyperconnected to the self-referential processing networks, amplifying pain catastrophising and affective pain. The anti-correlation between the insula and DMN — normally protective — is disrupted in fibromyalgia.",
    "The descending pain modulatory system — comprising the PAG, RVM (rostral ventromedial medulla), LC, raphe nuclei, and spinal dorsal horn — is chronically dysfunctional in fibromyalgia, with impaired diffuse noxious inhibitory control (DNIC) and conditioned pain modulation (CPM) deficits measured quantitative sensory testing. tDCS M1 upregulation enhances descending inhibitory control via the corticospinal-spinal projection, and taVNS activates the NTS-brainstem descending inhibitory pathway directly.",
  ],

  networkCitationKeys: [
    { authors: "Tan et al.", year: 2023, citations: 16, title: "Network targets for therapeutic brain stimulation: towards personalized therapy for pain", doi: "" },
    { authors: "Bhatt et al.", year: 2020, citations: 269, title: "Cellular circuits in the brain and their modulation in acute and chronic pain", doi: "" },
    { authors: "Lim & Ghosh", year: 2021, citations: 6, title: "Neuromodulation for Pain: comprehensive survey", doi: "" },
  ],
  fnonEvidenceStrength: "Strong",

  pathophysiologyText: "Chronic pain/fibromyalgia pathophysiology centres on central sensitisation mechanisms: (1) spinal dorsal horn wind-up and long-term potentiation of nociceptive synapses via NMDA receptor activation and AMPA trafficking; (2) impaired descending pain inhibition from the PAG-RVM-LC-raphe descending inhibitory system; (3) neuroinflammation — activated spinal microglia and astrocytes release pro-inflammatory mediators perpetuating sensitisation; (4) HPA axis dysregulation — abnormal cortisol awakening response and impaired stress-pain modulation; (5) serotonin-noradrenaline deficit in descending inhibitory pathways (mechanistic basis for duloxetine/milnacipran efficacy); (6) small fibre neuropathy in a subgroup of fibromyalgia patients; (7) corticothalamic dysrhythmia — altered thalamic gating and aberrant alpha oscillation intrusion on somatosensory processing; and (8) altered brain network connectivity with DMN-pain network hyperconnectivity.",
  cardinalSymptoms: [
    ["Widespread Musculoskeletal Pain", "Pain above and below waist, bilateral, axial; burning, aching, stabbing; allodynia; pressure hyperalgesia at tender points; most defining fibromyalgia feature", "Core criterion (100% fibromyalgia)", "Wolfe et al., 2010"],
    ["Fatigue", "Severe fatigue unrefreshing sleep; exercise-exacerbated; central mechanism; profound impact on function and quality of life", "~90% fibromyalgia", "Bennett et al., 2007"],
    ["Sleep Disturbance", "Non-restorative sleep; alpha-EEG anomaly in NREM sleep; impaired slow-wave sleep; sleep onset insomnia; fatigue-pain perpetuation cycle", "~80%", "Moldofsky, 2008"],
    ["Cognitive Dysfunction ('Fibrofog')", "Memory lapses, concentration difficulties, word-finding problems, slowed processing; impairs daily function significantly", "~70%", "Leavitt & Katz, 2006"],
    ["Allodynia", "Pain from normally non-painful stimuli (light touch, pressure, temperature); primary central sensitisation manifestation; widespread distribution", "~80%", "Mease, 2005"],
    ["Hyperalgesia", "Enhanced pain response to painful stimuli; lowered pain threshold; quantitative sensory testing (QST) confirmed", "~90%", "Gracely et al., 2002"],
    ["Headache", "Tension-type headache or migraine pattern; central sensitisation mechanism; highly prevalent in fibromyalgia", "~50–70%", "Ifergane et al., 2006"],
    ["IBS / GI Symptoms", "Irritable bowel syndrome overlap; visceral hypersensitivity; gut-brain axis disruption; central sensitisation in visceral processing", "~30–40%", "Chang et al., 2000"],
    ["Mood Disturbance (Depression/Anxiety)", "Depressive and anxiety symptoms; highly comorbid; bidirectional with pain amplification; SN-limbic circuit overlap", "~30–50%", "Häuser et al., 2008"],
    ["Tender Points / Widespread Hyperalgesia", "Classic 18-point fibromyalgia tender points (now replaced by WPI/SS score); bilateral symmetrical pressure pain hypersensitivity", "~80% historical tender points", "Wolfe et al., 1990"],
    ["Temperature Sensitivity", "Cold hypersensitivity; heat allodynia; thermal hyperalgesia; insula-thalamic thermoregulatory abnormality", "~70%", "Mease, 2005"],
    ["Morning Stiffness", "Significant joint and muscle stiffness on waking; improving through the day; shared with inflammatory arthropathies but non-inflammatory in fibromyalgia", "~70%", "Bennett et al., 2007"],
    ["Bladder/Urinary Symptoms", "Interstitial cystitis overlap; urinary frequency and urgency; visceral hypersensitivity in pelvic region", "~20–30%", "Arnold et al., 2006"],
  ],
  standardGuidelinesText: [
    "Current evidence-based guidelines for fibromyalgia (EULAR 2017, OARSI 2020, Canadian Fibromyalgia Guidelines 2012) recommend a multimodal, stepped-care approach. Non-pharmacological interventions have the strongest evidence: aerobic exercise (Level 1A), CBT for pain (Level 1A), multimodal pain rehabilitation programmes (Level 1A), and patient education. Pharmacological agents with regulatory approval or strong evidence include pregabalin (FDA-approved; Level A), duloxetine (FDA-approved; Level A), milnacipran (FDA-approved USA; Level A), low-dose amitriptyline for sleep and pain (Level B), and cyclobenzaprine for sleep.",
    "For chronic neuropathic pain more broadly, NICE, NeuPSIG, and EFNS guidelines recommend anticonvulsants (pregabalin, gabapentin), SNRIs (duloxetine, venlafaxine), tricyclic antidepressants (amitriptyline, nortriptyline), and topical lidocaine or capsaicin as first-line pharmacotherapy. Opioids are generally not recommended for fibromyalgia and have limited evidence for chronic non-cancer neuropathic pain.",
    "SOZO FNON protocols for chronic pain/fibromyalgia are designed to complement multimodal pain management by directly targeting the central sensitisation mechanisms. M1 tDCS (Level A evidence) is the anchor intervention, supported by TPS for deeper pain matrix access, and taVNS for descending pain inhibitory pathway activation. The Doctor coordinates FNON with the pain management team, emphasising that FNON is an adjunct to — not replacement of — evidence-based pain rehabilitation.",
  ],

  fnonFrameworkParagraph: "The FNON framework for chronic pain targets three primary mechanisms: (1) M1 anodal tDCS upregulates the primary motor cortex to enhance descending pain inhibitory control — the most evidence-based pain tDCS target; (2) TPS targeting insula and ACC addresses the pain salience and affective pain components at depth; (3) taVNS activates the NTS-brainstem descending inhibitory pathway (NTS→PAG→RVM→spinal dorsal horn) directly, enhancing endogenous opioid and serotonin-noradrenaline mediated pain inhibition.",
  keyBrainRegions: [
    ["Primary Motor Cortex (M1)", "Descending motor-pain inhibitory control; M1 stimulation activates corticospinal pain modulatory projections; most evidence-based tDCS pain target", "PRIMARY TARGET: anodal tDCS M1 (C3/C4 hand area; or Cz for widespread pain); Level A evidence for fibromyalgia pain reduction", "Fregni et al., 2006; Riberto et al., 2011; Lefaucheur et al., 2017"],
    ["Anterior Insula", "Pain salience; interoception; affective pain processing; central sensitisation hub; hyperactivation in fibromyalgia and chronic pain", "TPS anterior insula targeting; taVNS modulates insula via NTS-insular pathway; key for affective pain and somatic amplification", "Gracely et al., 2002; Napadow et al., 2010"],
    ["Dorsal Anterior Cingulate Cortex (dACC)", "Pain unpleasantness; affective-motivational pain dimension; hyperactivation in chronic pain; overlaps with cognitive-emotional distress circuit", "tDCS Fz montage for dACC; taVNS ACC modulation; combined dACC-insula TPS for affective pain phenotype", "Rainville et al., 1997"],
    ["Dorsolateral Prefrontal Cortex (DLPFC)", "Top-down cognitive pain control; pain catastrophising regulation; hypoactivation reduces descending inhibitory control; pain reappraisal", "Anodal tDCS F3 (left DLPFC) for cognitive-emotional pain control; combined M1+DLPFC for comprehensive protocol", "Lorenz et al., 2003; Fregni et al., 2006"],
    ["Somatosensory Cortex S1/S2", "Sensory-discriminative pain processing; expanded representations in chronic pain; allodynia substrate; central sensitisation cortical component", "Cathodal tDCS S1 can reduce hyperalgesia; anodal M1 adjacent provides indirect normalisation", "Ploner et al., 1999"],
    ["Thalamus", "Central pain gating; thalamo-cortical dysrhythmia in fibromyalgia; impaired descending inhibitory relay; alpha oscillation anomaly", "TPS thalamic deep targeting; taVNS thalamo-cortical synchrony modulation via brainstem-thalamic projections", "Bhagya et al., 2015; Leuchter et al., 2014"],
    ["Periaqueductal Gray (PAG)", "Descending pain inhibitory control centre; PAG-RVM axis mediates opioid and NE/5-HT descending inhibition; impaired in fibromyalgia", "taVNS NTS→LC→PAG pathway activates descending inhibitory system; TPS indirect brainstem targeting", "Heinricher et al., 2009"],
    ["Prefrontal Medial / vmPFC", "Pain catastrophising regulation; negative affect in chronic pain; interoceptive-pain integration; pain catastrophising rumination", "TPS vmPFC/mPFC for catastrophising phenotype; anodal F3 includes mPFC; combined with pain acceptance CBT", "Wiech & Tracey, 2009"],
    ["Nucleus Accumbens / Striatum", "Motivational aspects of pain; reward system impairment in chronic pain; chronic pain 'hijacks' reward circuit; anhedonia-pain interface", "TPS deep mesolimbic for motivational pain phenotype; combined DLPFC-striatal tDCS", "Baliki et al., 2010"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Vagal afferent relay; entry point for taVNS descending pain inhibitory pathway activation; direct brainstem pain modulation", "taVNS NTS activation — NTS→PAG→RVM→spinal descending inhibition; activates endogenous opioid and 5-HT pain inhibitory systems", "Fang et al., 2016; Napadow et al., 2010"],
    ["Locus Coeruleus (LC)", "Noradrenergic descending pain inhibitory control; spinal NE release inhibits dorsal horn nociception; duloxetine mechanism parallels taVNS", "taVNS→NTS→LC→spinal NE descending inhibition — mimics SNRI analgesic mechanism; synergistic with duloxetine", "Millan, 2002"],
    ["Raphe Nuclei", "Serotonergic descending pain inhibitory control; spinal 5-HT release modulates nociception; milnacipran mechanism", "taVNS modulates serotonergic raphe via brainstem connections; CES may enhance 5-HT tone", "Millan, 2002"],
    ["Periaqueductal Gray (PAG)", "Opioid and non-opioid pain inhibitory system; stimulation activates analgesia; target via NTS pathway", "taVNS indirectly activates PAG via NTS-LC pathway; CES may modulate PAG endorphin release", "Heinricher et al., 2009"],
    ["Spinal Dorsal Horn", "Central sensitisation locus; wind-up and LTP of nociceptive circuits; NMDA-mediated; primary target of descending inhibitory system", "Descending inhibitory projections activated by M1 tDCS, taVNS, and TPS reduce dorsal horn sensitisation indirectly", "Woolf, 2011"],
    ["Hypothalamus", "HPA axis dysregulation in fibromyalgia; cortisol and CRF abnormalities; stress-pain amplification; autonomic regulation", "taVNS modulates hypothalamic-pituitary axis via NTS projections; CES for HPA normalisation", "McLean et al., 2004"],
    ["Amygdala", "Fear-pain interaction; catastrophising; affective pain memory; anxiety-pain perpetuation cycle", "TPS temporal-amygdala; taVNS NTS-amygdala modulation; combined pain exposure therapy", "Neugebauer et al., 2009"],
  ],
  keyFunctionalNetworks: [
    ["Pain Matrix / Salience Network", "Insula, dACC, S1/S2, thalamus, amygdala, PAG", "Hyperactivation and hypersensitivity; amplified pain salience; reduced threshold for pain response; central sensitisation network", "TPS insula/ACC targeting; taVNS for SN-pain modulation; cathodal S1 tDCS; combined pain exposure tasks", "Gracely et al., 2002; Napadow et al., 2010"],
    ["Descending Pain Inhibitory Network", "PAG, RVM, LC, raphe nuclei, ACC, vmPFC, spinal cord", "Impaired descending inhibition; deficient conditioned pain modulation (CPM); reduced DNIC; opioid and NE/5-HT deficit", "taVNS PRIMARY for descending inhibitory pathway activation; M1 anodal tDCS enhances corticospinal inhibitory projections", "Millan, 2002; Heinricher et al., 2009"],
    ["Default Mode Network (DMN)", "mPFC, PCC, hippocampus, angular gyrus", "Hyperconnected with pain processing regions in fibromyalgia; pain catastrophising; rumination; DMN-insula hyperconnectivity", "Cathodal Pz (DMN suppression); TPS PCC; pain acceptance mindfulness tasks to disrupt DMN-pain coupling", "Napadow et al., 2010; Baliki et al., 2008"],
    ["Central Executive Network (CEN)", "DLPFC, PPC, lateral PFC", "Hypoactivation reduces top-down cognitive pain control; impaired pain reappraisal; cognitive analgesic deficit", "Anodal tDCS F3 (DLPFC); TPS DLPFC for top-down pain control; pain reappraisal CBT concurrent", "Lorenz et al., 2003"],
    ["Interoceptive Network", "Anterior insula, mid-insula, ACC, brainstem", "Amplified interoceptive awareness; somatic amplification; visceral hypersensitivity; altered body awareness", "TPS insula; taVNS via NTS-insular pathway; body scan and mindfulness tasks to normalise interoceptive processing", "Paulus & Stein, 2006"],
    ["Autonomic Regulatory Network", "NTS, LC, insula, ACC, hypothalamus, brainstem", "HPA dysregulation; autonomic imbalance; reduced HRV; impaired stress response; pain-stress amplification", "taVNS PRIMARY for autonomic normalisation; CES for global arousal reduction; HRV biofeedback concurrent", "McLean et al., 2004"],
    ["Reward/Motivation Network", "Striatum, OFC, vmPFC, VTA, ACC", "Chronic pain impairs reward processing; anhedonia-pain interaction; motivational deficit; pain 'hijacks' reward circuit", "TPS deep mesolimbic; tDCS DLPFC-striatal pathway; reward-contingent activities concurrent", "Baliki et al., 2010"],
  ],
  networkAbnormalities: "Chronic pain/fibromyalgia is characterised by pain matrix hyperactivation (insula, ACC, thalamus), impaired descending pain inhibition (PAG-RVM-LC-raphe), DMN-pain network hyperconnectivity, and CEN hypoactivation reducing top-down pain control. Central sensitisation is the unifying mechanism.",
  conceptualFramework: "SOZO FNON Chronic Pain protocol: (1) M1 anodal tDCS (Level A evidence) enhances descending pain inhibitory control; (2) TPS insula/ACC targets pain salience network deep structures; (3) taVNS activates NTS-PAG-descending inhibitory pathway directly; (4) CES provides broad-spectrum pain-relevant arousal modulation; (5) concurrent pain CBT, graded exercise, and mindfulness potentiate effects.",

  clinicalPhenotypes: [
    ["Central Sensitisation — Widespread Pain", "Classic fibromyalgia widespread pain, allodynia; M1 tDCS primary (Level A); taVNS descending inhibitory; pain programme concurrent", "Wolfe et al., 2010"],
    ["Affective Pain Dominant", "Pain catastrophising, depression, anxiety driving pain experience; DLPFC + insula target; taVNS limbic modulation; CBT pain primary", "Sullivan et al., 2001"],
    ["Sleep-Fatigue-Pain Cycle", "Disrupted sleep perpetuating pain and fatigue cycle; CES evening + taVNS; sleep intervention primary alongside pain treatment", "Moldofsky, 2008"],
    ["Cognitive Pain (Fibrofog)", "Cognitive dysfunction (fibrofog) alongside pain; DLPFC tDCS for cognitive component; combined M1+F3 protocol", "Leavitt & Katz, 2006"],
    ["Neuropathic Pain Component", "Central or peripheral neuropathic features; burning, shooting, paresthesia; DLPFC + M1 combined; pregabalin coordination", "Backonja & Galer, 1998"],
    ["CRPS Type I", "Complex regional pain syndrome; vasomotor and sudomotor changes; motor cortex stimulation approach; specialist team co-management", "Marinus et al., 2011"],
    ["Visceral Hypersensitivity / IBS Overlap", "Gut-pain axis; visceral central sensitisation; taVNS primary (vagal gut-brain modulation); CES for ANS regulation", "Chang et al., 2000"],
    ["Treatment-Resistant Fibromyalgia", "Inadequate response to ≥2 pharmacological trials; maximum M1+DLPFC bilateral; intensive taVNS; comprehensive pain programme", "Clauw, 2014"],
    ["Musculoskeletal-Dominant Chronic Pain", "Mechanical low back pain, neck pain, myofascial pain with central sensitisation component; M1 tDCS + physiotherapy concurrent", "Moseley & Butler, 2015"],
  ],
  symptomNetworkMapping: [
    ["Widespread Pain / Allodynia", "Pain matrix hyperactivation", "Descending inhibitory impairment", "tDCS M1 anodal (Cz/C3) PRIMARY", "Graded exercise concurrent during stimulation"],
    ["Fatigue", "Autonomic + descending regulation deficit", "HPA + LC dysregulation", "taVNS + CES (primary for fatigue)", "Graded activity pacing concurrent"],
    ["Sleep Disturbance", "Autonomic + thalamo-cortical dysrhythmia", "Alpha-EEG anomaly; HPA", "CES 60min evening + taVNS", "Sleep hygiene + CBT-I concurrent"],
    ["Cognitive Dysfunction (Fibrofog)", "CEN hypoactivation", "DLPFC circuit deficit", "tDCS F3 anodal + M1 combined", "Cognitive training concurrent"],
    ["Affective Pain / Catastrophising", "DMN-pain hyperconnectivity", "CEN hypoactivation + ACC dysregulation", "tDCS F3 + Pz cathodal + taVNS", "Pain CBT / acceptance concurrent"],
    ["Neuropathic Features", "Central sensitisation + thalamic gating", "Spinal-thalamo-cortical dysrhythmia", "tDCS M1 + TPS thalamic", "Sensory graded exposure concurrent"],
    ["Anxiety/Depression Comorbidity", "SN/limbic hyperreactivity", "Frontal-limbic circuit disruption", "CES + taVNS + anodal F3", "CBT pain-mood integration concurrent"],
    ["IBS / Visceral Pain", "Vagal-gut-brain axis dysregulation", "Insula-NTS visceral hypersensitivity", "taVNS PRIMARY (gut-brain modulation)", "Mindfulness gut-directed therapy concurrent"],
    ["Headache", "Trigeminocortical sensitisation", "Cortical spreading depression mechanism", "tDCS M1 anodal (C3/C4)", "Headache diary + trigger management"],
    ["Autonomic Dysregulation", "ANS imbalance; reduced HRV", "LC/brainstem axis dysfunction", "taVNS PRIMARY + CES", "HRV biofeedback concurrent"],
  ],
  montageSelectionRows: [
    ["Widespread pain / fibromyalgia (M1 primary)", "Anodal M1 (Cz or C3) + cathodal contralateral SO — 2mA 20min (Level A)"],
    ["Affective pain / catastrophising (DLPFC add-on)", "Anodal F3 + Pz cathodal — 2mA 20min (combined M1+DLPFC)"],
    ["Bilateral M1 (severe widespread)", "Anodal bilateral C3+C4 — 2mA 20min (HDCkit bilateral M1)"],
    ["taVNS descending inhibition (all phenotypes)", "taVNS bilateral cymba 0.5mA 30–40min (primary descending inhibitory activation)"],
    ["CES for sleep + fatigue", "Alpha-Stim AID 0.5mA 60min (evening for sleep; daytime for fatigue)"],
    ["TPS insula/ACC (affective pain)", "NEUROLITH® anterior insula region 0.2mJ/mm² 3000 pulses"],
    ["TPS M1 (motor cortex deep)", "NEUROLITH® M1 0.2mJ/mm² 4000 pulses — deep M1 cortical stimulation"],
    ["Neuropathic pain (DLPFC + M1)", "Anodal F3 + C3 dual-electrode — 2mA 20min combined"],
    ["CRPS (specialist protocol)", "tDCS M1 contralateral to affected limb anodal — 1.5mA 20min; specialist team co-managed"],
    ["Visceral pain / IBS phenotype", "taVNS 40min (primary); CES 60min; tDCS F3 secondary"],
    ["Sleep-fatigue-pain cycle (evening)", "CES 0.5mA 60min evening + taVNS pre-sleep"],
    ["TRF (treatment-resistant fibromyalgia)", "HDCkit bilateral M1+DLPFC + TPS M1 + taVNS 40min"],
    ["Maintenance phase", "tDCS M1 2×/week; home CES daily; taVNS 3×/week"],
  ],
  polarityPrincipleText: "In chronic pain/fibromyalgia, M1 anodal stimulation is the evidence-based primary approach — upregulating primary motor cortex excitability enhances corticospinal descending pain inhibitory projections. For affective pain, left DLPFC anodal adds cognitive pain control. Cathodal somatosensory cortex (S1) may reduce allodynia but is less studied than anodal M1. Bilateral M1 is appropriate for widespread bilateral fibromyalgia pain.",
  polarityTable: [
    ["Anodal M1 (C3/Cz)", "Primary evidence-based pain target — Level A for fibromyalgia; enhances descending pain inhibitory control via corticospinal pathway"],
    ["Anodal F3 (left DLPFC)", "Top-down cognitive pain control; pain catastrophising regulation; combined with M1 for comprehensive pain protocol"],
    ["Cathodal SO (supraorbital contralateral)", "Reference electrode; standard tDCS pain montage (M1 anodal + SO cathodal reference)"],
    ["Cathodal S1 (somatosensory)", "Reduces somatosensory hyperalgesia and allodynia; can be combined with anodal M1 for sensory gain reduction"],
    ["taVNS bilateral cymba", "Descending pain inhibitory pathway activation — NTS→PAG→RVM→LC→spinal dorsal horn; primary pharmacological-level mechanism"],
  ],

  classicTdcsProtocols: [
    ["C1", "Fibromyalgia — primary M1", "M1 anodal (Cz or C3)", "Contralateral SO cathodal", "2mA 20min, 10–15 sessions", "Level A"],
    ["C2", "Fibromyalgia — bilateral M1", "Bilateral C3+C4 anodal", "Bilateral SO cathodal", "2mA 20min", "Level A (bilateral variant)"],
    ["C3", "Chronic pain + depression", "F3 anodal (DLPFC)", "Pz cathodal", "2mA 20min", "Level B"],
    ["C4", "Combined M1 + DLPFC", "C3 anodal + F3 anodal (dual)", "Contralateral SO + Pz cathodal", "2mA 20min each", "Level A/B combined"],
    ["C5", "Neuropathic pain", "M1 anodal (C3)", "Contralateral SO cathodal", "2mA 20min", "Level B"],
    ["C6", "CRPS Type I (specialist)", "Contralateral M1 anodal", "Ipsilateral SO cathodal", "1.5mA 20min (specialist)", "Level B"],
    ["C7", "Fibrofog / cognitive", "F3 anodal + C3 anodal dual", "Pz + SO cathodal", "2mA 20min", "Emerging"],
    ["C8", "Maintenance pain", "M1 anodal (Cz)", "Contralateral SO", "1.5mA 15min", "Level A (maintenance)"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Central sensitisation / widespread pain", "Pain matrix + descending inhibition", "M1 anodal (Cz/C3) + taVNS concurrent — primary analgesic protocol", "Upregulate descending pain inhibitory control; paired with exercise"],
    ["F2", "Affective pain / catastrophising", "CEN hypoactivation + DMN-pain hyperconnectivity", "F3 anodal + Pz cathodal + M1 anodal (triple montage)", "Top-down cognitive pain control + DMN suppression + M1 analgesic"],
    ["F3", "Sleep-fatigue-pain cycle", "Autonomic + sleep + pain circuit", "CES evening + taVNS + M1 anodal daytime (split session)", "Pain and sleep addressed in integrated daily protocol"],
    ["F4", "Visceral/IBS phenotype", "Vagal-gut-brain dysregulation", "taVNS PRIMARY 40min + CES 60min (primary vagal modality)", "Gut-brain axis targeted primarily via taVNS"],
    ["F5", "Neuropathic pain component", "Central sensitisation + thalamic gating", "M1 anodal + F3 anodal dual + taVNS", "Combined descending inhibition + cognitive pain control + taVNS"],
    ["F6", "Treatment-resistant fibromyalgia", "Multi-network pain amplification", "HDCkit bilateral M1+DLPFC + TPS M1 + taVNS 40min (maximum protocol)", "Maximum multi-modal analgesic network intervention"],
  ],
  classicTpsProtocols: [
    ["T1", "Fibromyalgia M1 deep", "M1 cortex", "0.2mJ/mm²", "4000 pulses", "Emerging"],
    ["T2", "Affective pain (insula/ACC)", "Anterior insula / ACC region", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T3", "DLPFC pain control", "Left DLPFC", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T4", "Combined M1 + DLPFC", "M1 + DLPFC sequential", "0.2mJ/mm²", "5000 pulses total", "Emerging"],
    ["T5", "Thalamic deep (neuropathic)", "Thalamus (indirect)", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Widespread pain / fibromyalgia", "M1 descending pain inhibitory circuit", "M1 (Cz) 0.2mJ/mm² × 4000 pulses — deep motor cortex for enhanced descending pain inhibition", "Primary deep analgesic target"],
    ["FT2", "Affective pain / catastrophising", "Insula-ACC pain salience circuit", "Anterior insula 0.2mJ/mm² × 3000 + F3 DLPFC 0.2mJ/mm² × 2000", "Deep insula then prefrontal — pain salience + cognitive pain control"],
    ["FT3", "Neuropathic pain component", "M1 + thalamic circuit", "M1 0.2mJ/mm² × 3000 + thalamic indirect 0.2mJ/mm² × 2000", "Deep motor cortex + thalamic targeting for neuropathic central sensitisation"],
    ["FT4", "Treatment-resistant fibromyalgia", "Multi-network pain amplification", "M1 bilateral 0.2mJ/mm² × 4000 + DLPFC 0.2mJ/mm² × 2000 + taVNS", "Maximum deep bilateral pain network normalisation"],
    ["FT5", "CRPS Type I (specialist)", "Motor cortex + somatosensory", "Contralateral M1 0.2mJ/mm² × 3000 (specialist team)", "Deep contralateral motor cortex for CRPS — specialist co-managed"],
    ["FT6", "Cognitive fibrofog + pain", "DLPFC + M1 combined", "F3 DLPFC 0.2mJ/mm² × 3000 + M1 0.2mJ/mm² × 3000", "Sequential cognitive then analgesic deep stimulation"],
    ["FT7", "Sleep-fatigue-pain cycle", "Autonomic + M1 combined", "M1 0.2mJ/mm² × 2000 (daytime) + CES 60min evening", "Daytime analgesic deep stimulation + evening autonomic"],
    ["FT8", "Visceral pain / IBS", "Insula-NTS circuit", "Anterior insula 0.15mJ/mm² × 2000 + taVNS 40min primary", "Conservative insula with primary taVNS for gut-brain axis"],
    ["FT9", "Maintenance pain protocol", "M1 monthly maintenance", "M1 0.2mJ/mm² × 2000 monthly — pain maintenance", "Monthly deep analgesic maintenance stimulation"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Central Sensitisation — Widespread Pain",
      combinations: [
        ["S — Stabilise", "taVNS 30min — activate descending pain inhibitory pathway (NTS→PAG→spinal)", "Prime endogenous pain inhibitory system before cortical stimulation"],
        ["O — Optimise", "tDCS M1 anodal 2mA 20min (Cz/C3) — Level A analgesic tDCS", "Upregulate M1 descending pain inhibitory control — primary evidence-based pain tDCS"],
        ["Z — Zone", "TPS M1 0.2mJ/mm² 4000 pulses — deep motor cortex analgesic circuit", "Deep primary motor cortex activation for sustained descending pain inhibitory enhancement"],
        ["O — Outcome", "Graded aerobic exercise concurrent (Level A evidence for fibromyalgia) — consolidate", "Pair neural priming with exercise-induced analgesia; synergistic analgesic mechanisms"],
      ],
    },
    {
      phenotype: "Affective Pain Dominant",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — reduce anxiety and catastrophising baseline", "Lower affective pain threshold via broad-spectrum arousal modulation"],
        ["O — Optimise", "tDCS F3 anodal + Pz cathodal 2mA 20min — DLPFC cognitive pain control", "Upregulate top-down cognitive pain appraisal and catastrophising regulation"],
        ["Z — Zone", "TPS anterior insula 0.2mJ/mm² 3000 + F3 DLPFC 2000 — affective pain circuit", "Deep insula-prefrontal pain salience and cognitive control circuit"],
        ["O — Outcome", "Pain CBT (acceptance and commitment therapy for pain) concurrent + taVNS", "Evidence-based pain psychological intervention concurrent with primed cognitive pain circuits"],
      ],
    },
    {
      phenotype: "Sleep-Fatigue-Pain Cycle",
      combinations: [
        ["S — Stabilise", "taVNS afternoon 30min — pre-evening autonomic preparation", "Shift autonomic balance; prepare descending pain inhibitory system for daily pain reduction"],
        ["O — Optimise", "tDCS M1 anodal 2mA 20min (daytime) — daily analgesic circuit upregulation", "Daily daytime M1 stimulation to maintain pain inhibitory control"],
        ["Z — Zone", "CES 0.5mA 60min evening — primary sleep-fatigue intervention modality", "Evening autonomic downregulation; sleep onset facilitation; pain cycle interruption"],
        ["O — Outcome", "Sleep hygiene programme + graded exercise plan — consolidate", "CBT-I sleep therapy + pacing plan to interrupt the sleep-fatigue-pain cycle"],
      ],
    },
    {
      phenotype: "Cognitive Pain (Fibrofog)",
      combinations: [
        ["S — Stabilise", "taVNS 30min — noradrenergic + descending pain priming", "Combined cognitive and analgesic preparation via NTS-LC pathway"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min + M1 anodal (dual montage)", "Combined DLPFC cognitive and M1 analgesic upregulation simultaneously"],
        ["Z — Zone", "TPS F3 DLPFC 3000 + M1 2000 pulses — cognitive + analgesic combined", "Sequential deep cognitive then analgesic stimulation"],
        ["O — Outcome", "Cognitive tasks concurrent (attention, working memory) + graded activity", "Cognitive rehabilitation paired with analgesic neural priming"],
      ],
    },
    {
      phenotype: "Neuropathic Pain Component",
      combinations: [
        ["S — Stabilise", "taVNS 30min — NE and 5-HT descending inhibitory activation (SNRI-like mechanism)", "Activate serotonin-noradrenaline descending pain inhibitory pathways"],
        ["O — Optimise", "tDCS M1 anodal + F3 anodal 2mA 20min combined — analgesic + cognitive", "Primary motor cortex analgesic combined with DLPFC cognitive pain control"],
        ["Z — Zone", "TPS M1 0.2mJ/mm² 3000 + thalamic indirect 2000 — neuropathic pain circuit", "Deep motor cortex + thalamic targeting for neuropathic central sensitisation"],
        ["O — Outcome", "Sensory graded exposure (TENS or manual desensitisation) concurrent + pain education", "Pain neuroscience education + sensory graded exposure therapy concurrent"],
      ],
    },
    {
      phenotype: "Visceral Hypersensitivity / IBS Overlap",
      combinations: [
        ["S — Stabilise", "taVNS 40min — primary gut-brain vagal modulation (primary modality for visceral pain)", "Vagal afferent gut-brain axis modulation — taVNS is primary for visceral/IBS pain phenotype"],
        ["O — Optimise", "CES 0.5mA 60min — broad-spectrum ANS regulation supporting gut motility", "Autonomic nervous system regulation supports gut-brain axis normalisation"],
        ["Z — Zone", "tDCS F3 anodal 2mA 15min — secondary prefrontal pain control (conservative)", "Mild prefrontal upregulation for top-down visceral pain control"],
        ["O — Outcome", "Gut-directed CBT / mindfulness-based stress reduction (MBSR) concurrent", "Evidence-based gut-directed psychological therapy concurrent with vagal modulation"],
      ],
    },
    {
      phenotype: "Treatment-Resistant Fibromyalgia",
      combinations: [
        ["S — Stabilise", "taVNS 40min bilateral — maximum descending inhibitory and anti-inflammatory", "Maximum endogenous pain inhibitory system activation"],
        ["O — Optimise", "HDCkit bilateral M1+F3 anodal 2mA 20min — maximum bilateral analgesic+cognitive", "Maximal bilateral M1 and DLPFC analgesic upregulation"],
        ["Z — Zone", "TPS bilateral M1 0.2mJ/mm² 4000 + DLPFC 2000 = 6000 total pulses", "Maximum deep bilateral analgesic circuit stimulation"],
        ["O — Outcome", "Intensive multidisciplinary pain programme concurrent + CES daily home", "Comprehensive pain rehabilitation — psychology, physiotherapy, occupational therapy + daily home CES"],
      ],
    },
    {
      phenotype: "CRPS Type I (Specialist)",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 60min — autonomic regulation (CRPS has autonomic component)", "Address vasomotor and sympathetic dysregulation of CRPS via autonomic modulation"],
        ["O — Optimise", "tDCS contralateral M1 anodal 1.5mA 20min — specialist co-managed", "Conservative contralateral motor cortex targeting for CRPS — specialist team co-management"],
        ["Z — Zone", "TPS contralateral M1 0.2mJ/mm² 3000 — specialist deep stimulation", "Deep motor cortex contralateral to affected limb — specialist protocol"],
        ["O — Outcome", "Graded motor imagery (GMI) concurrent — CRPS-specific rehabilitation", "Evidence-based CRPS rehabilitation (GMI, mirror therapy) concurrent with neural priming"],
      ],
    },
    {
      phenotype: "Musculoskeletal-Dominant Chronic Pain",
      combinations: [
        ["S — Stabilise", "taVNS 30min — descending inhibitory priming before physiotherapy", "Prime endogenous pain inhibition before active physiotherapy session"],
        ["O — Optimise", "tDCS M1 anodal 2mA 20min — primary analgesic M1 upregulation", "Primary motor cortex analgesic stimulation paired with physiotherapy"],
        ["Z — Zone", "TPS M1 0.2mJ/mm² 3000 — deep motor cortex for musculoskeletal pain", "Deep primary motor cortex analgesic for musculoskeletal central sensitisation"],
        ["O — Outcome", "Active physiotherapy concurrent (McKenzie, graded exercise) + pain education", "Pain neuroscience education + active musculoskeletal rehabilitation paired with analgesic priming"],
      ],
    },
  ],

  taskPairingRows: [
    ["Graded Aerobic Exercise", "Widespread pain / fibromyalgia", "tDCS M1 anodal active + taVNS concurrent", "Light-moderate aerobic exercise during M1 stimulation — exercise-induced analgesia synergy"],
    ["Pain CBT / ACT", "Affective pain / catastrophising", "tDCS F3 anodal + Pz cathodal active", "Pain acceptance and reappraisal exercises during primed DLPFC"],
    ["Sensory Desensitisation", "Allodynia / neuropathic", "tDCS M1 anodal active", "Graded tactile exposure to normalise allodynia during analgesic stimulation"],
    ["Gut-Directed Mindfulness", "Visceral/IBS phenotype", "taVNS active", "Mindfulness body scan focused on gut during taVNS vagal modulation"],
    ["Graded Motor Imagery (GMI)", "CRPS Type I", "tDCS contralateral M1 anodal active", "Progressive GMI sequence during contralateral motor cortex stimulation"],
    ["Energy Pacing Activity", "Sleep-fatigue-pain phenotype", "CES active", "Activity pacing and energy management during CES arousal modulation"],
  ],
  outcomeMeasures: "Primary: Numeric Rating Scale (NRS) for pain intensity (0–10, average and worst; daily and session-by-session); Fibromyalgia Impact Questionnaire Revised (FIQ-R) at baseline, 5-session, 10-session, 1-month. Secondary: Patient Global Impression of Change (PGIC); PSQI (sleep quality); Fatigue Severity Scale (FSS); PHQ-9 (depression comorbidity); Pain Catastrophising Scale (PCS); Quantitative Sensory Testing (QST — pressure pain threshold) where available; Sheehan Disability Scale. Safety: monitor for pain flare post-session; skin inspection at electrode sites; blood pressure pre/post-session.",

  medicationSectionTitle: "Pharmacotherapy Context for Chronic Pain / Fibromyalgia",
  medicationSectionText: "Fibromyalgia pharmacotherapy: FDA-approved agents include pregabalin (Lyrica), duloxetine (Cymbalta), and milnacipran (Savella). Low-dose amitriptyline (10–50mg nocte) has strong evidence for pain and sleep in fibromyalgia. The Doctor coordinates FNON with pharmacotherapy: duloxetine/milnacipran (SNRIs) are mechanistically synergistic with taVNS (both enhance NE-mediated descending pain inhibition — additive analgesic effects expected); pregabalin reduces central sensitisation at the spinal level complementing cortical M1 tDCS targeting. For neuropathic pain: gabapentinoids (pregabalin, gabapentin), duloxetine, amitriptyline. For CRPS: high-dose vitamin C (prophylaxis), physiotherapy-led desensitisation programme, specialist pain team. CES (Alpha-Stim) has its own FDA-clearance for anxiety/depression/insomnia — it is used within FNON protocol as part of the autonomic-analgesic multimodal approach alongside tDCS/TPS.",

  references: {
    foundational: [
      "Wolfe F, Clauw DJ, Fitzcharles MA, et al. (2010). The American College of Rheumatology preliminary diagnostic criteria for fibromyalgia and measurement of symptom severity. Arthritis Care Res, 62(5), 600–610. doi:10.1002/acr.20140",
      "Woolf CJ. (2011). Central sensitization: Implications for the diagnosis and treatment of pain. Pain, 152(3 Suppl), S2–15. doi:10.1016/j.pain.2010.09.030",
      "Clauw DJ. (2014). Fibromyalgia: A clinical review. JAMA, 311(15), 1547–1555. doi:10.1001/jama.2014.3266",
      "Gracely RH, Petzke F, Wolf JM, Clauw DJ. (2002). Functional magnetic resonance imaging evidence of augmented pain processing in fibromyalgia. Arthritis Rheum, 46(5), 1333–1343. doi:10.1002/art.10225",
      "Millan MJ. (2002). Descending control of pain. Prog Neurobiol, 66(6), 355–474. doi:10.1016/S0301-0082(02)00009-6",
      "Napadow V, LaCount L, Park K, et al. (2010). Intrinsic brain connectivity in fibromyalgia is associated with chronic pain intensity. Arthritis Rheum, 62(8), 2545–2555. doi:10.1002/art.27497",
    ],
    tdcs: [
      "Fregni F, Gimenes R, Valle AC, et al. (2006). A randomized, sham-controlled, proof of principle study of transcranial direct current stimulation for the treatment of pain in fibromyalgia. Arthritis Rheum, 54(12), 3988–3998. doi:10.1002/art.22195",
      "Riberto M, Marcon Alfieri F, Monteiro Benedetti Pace do Prado C, et al. (2011). Efficacy of transcranial direct current stimulation coupled with a multidisciplinary rehabilitation program for the treatment of fibromyalgia. Open Rheumatol J, 5, 45–50. doi:10.2174/1874312901105010045",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Nitsche MA, Cohen LG, Wassermann EM, et al. (2008). Transcranial direct current stimulation: State of the art 2008. Brain Stimul, 1(3), 206–223. doi:10.1016/j.brs.2008.06.004",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with non-invasive brain stimulation. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with transcranial direct current stimulation (tDCS): Challenges and future directions. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Antal A, Terney D, Kühnl S, Paulus W. (2010). Anodal transcranial direct current stimulation of the motor cortex ameliorates chronic pain and reduces short intracortical inhibition. J Pain Symptom Manage, 39(5), 890–903. doi:10.1016/j.jpainsymman.2009.09.023",
      "Vaseghi B, Zoghi M, Jaberzadeh S. (2014). Does anodal transcranial direct current stimulation modulate sensory perception and pain? A meta-analysis study. Clin Neurophysiol, 125(9), 1847–1858. doi:10.1016/j.clinph.2014.01.020",
      "Valle A, Roizenblatt S, Botte S, et al. (2009). Efficacy of anodal transcranial direct current stimulation (tDCS) for the treatment of fibromyalgia: Results of a randomized, sham-controlled longitudinal clinical trial. J Pain Manag, 2(3), 353–361.",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and non-invasive brain stimulation. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Bikson M, et al. (2016). Safety of transcranial direct current stimulation. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Peterchev AV, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335. doi:10.1111/j.1525-1403.2011.00378.x",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930.",
    ],
    tavns: [
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Napadow V, Edwards RR, Cahalan CM, et al. (2012). Evoked pain analgesia in chronic low back pain patients: A randomized controlled pilot study. Pain Med, 13(3), 402–411. doi:10.1111/j.1526-4637.2012.01314.x",
      "Farmer AD, et al. (2020). International consensus on minimum reporting standards in research on taVNS. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of brain-gut axis. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Rong P, et al. (2016). Effect of transcutaneous auricular vagus nerve stimulation on major depressive disorder. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
      "Burger AM, et al. (2020). Transcutaneous vagus nerve stimulation reduces startle response in anxious individuals. Biol Psychol, 149, 107800. doi:10.1016/j.biopsycho.2019.107800",
      "Millan MJ. (2002). Descending control of pain. Prog Neurobiol, 66(6), 355–474. doi:10.1016/S0301-0082(02)00009-6",
      "Heinricher MM, Tavares I, Leith JL, Lumb BM. (2009). Descending control of nociception: Specificity, recruitment and plasticity. Brain Res Rev, 60(1), 214–225. doi:10.1016/j.brainresrev.2008.12.009",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Cork RC, Wood P, Ming N, Shepherd C, Eddy J, Price L. (2004). The effect of cranial electrotherapy stimulation (CES) on pain associated with fibromyalgia. Internet J Anesthesiol, 8(2).",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Kavirajan HC, Lueck K, Cho K. (2014). CES use in outpatient psychiatric and pain treatment. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of CES for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
    ],
    network: [
      "Napadow V, LaCount L, Park K, et al. (2010). Intrinsic brain connectivity in fibromyalgia. Arthritis Rheum, 62(8), 2545–2555. doi:10.1002/art.27497",
      "Baliki MN, Geha PY, Apkarian AV, Chialvo DR. (2008). Beyond feeling: Chronic pain hurts the brain, disrupting the default-mode network dynamics. J Neurosci, 28(6), 1398–1403. doi:10.1523/JNEUROSCI.4123-07.2008",
      "Woolf CJ. (2011). Central sensitization: Implications for the diagnosis and treatment of pain. Pain, 152(3 Suppl), S2–15. doi:10.1016/j.pain.2010.09.030",
      "Gracely RH, Petzke F, Wolf JM, Clauw DJ. (2002). Functional MRI evidence of augmented pain processing in fibromyalgia. Arthritis Rheum, 46(5), 1333–1343. doi:10.1002/art.10225",
      "Heinricher MM, et al. (2009). Descending control of nociception: Specificity, recruitment and plasticity. Brain Res Rev, 60(1), 214–225. doi:10.1016/j.brainresrev.2008.12.009",
    ],
  },
  // ── FNON Protocol Data (SOZO_Brain_Networks_qEEG_FNON.xlsx, April 2026) ──
  fnonPrimaryNetwork: 'Pain Matrix + Sensorimotor',
  fnonSecondaryNetwork: 'Limbic insula-amygdala',
  fnonFBand: 'Gamma suppression + Alpha restoration',
  fnonEegNodes: 'Cz/C3/C4(M1/S1)+T3/T4(insula/limbic)+Fz(ACC)+Pz(parietal attention)',
  fnonOscillationGoal: 'Suppress neuropathic gamma; restore M1 alpha+beta (mu); reduce ACC theta; suppress insula-SN hyperactivation',
  fnonPrimaryModalityParams: 'tDCS anodal M1 (C3/C4, 2mA, 20min, 10 sessions — strongest evidence); TMS high-freq M1 (10Hz); taVNS (100Hz analgesia mode)',
  fnonAddonModality: 'TPS multi-site (M1+ACC+insula); LIFU (thalamic VPL nucleus); CES (Alpha-Stim MET probes); PBM bilateral M1',
  fnonSessions: '5–20',
  fnonEvidenceLevel: 'RCT + Meta-analysis',
  fnonLitCount: '150+ tDCS; 60+ TMS; 40+ taVNS; 15+ LIFU',
  fnonKeyReferences: 'Fregni 2006; Lefaucheur 2017 IFCNS; Napadow 2012 taVNS; Lee 2015 LIFU thalamic; Network targets pain 2023',
  fnonNotes: 'FNON: Pain gamma signature = suppression target. LIFU unique for thalamic pain relay. taVNS 100Hz (not 25Hz) for pain — frequency specific.',
  fnonQeegBiomarker: '↑Gamma; ↓Mu; ↓Alpha',
  fnonPaperCounts: {
    tps: 5, tms: 60, tdcs: 150,
    tavns: 40, ces: 35, tacs: 10,
    pbm: 10, lifu: 15, pemf: 15, dbs: 10,
  },
  fnonBestFirstLine: 'tDCS M1 anodal (150 papers)',
  fnonBestSecondLine: 'TPS multi-site + LIFU',
  fnonScore: 4,

};
