'use strict';
module.exports = {
  conditionFull: "Major Depressive Disorder (MDD)",
  conditionShort: "Depression",
  conditionSlug: "depression",
  documentNumber: "SOZO-MDD-PROT-001",
  offLabelCoverText: "tDCS and TPS use in Major Depressive Disorder is INVESTIGATIONAL / OFF-LABEL in some applications. tDCS has Level B evidence for MDD.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level B evidence for MDD', 'Standard informed consent'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; growing evidence base for depression', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of Major Depressive Disorder (DSM-5 / ICD-11) by a qualified psychiatrist or physician",
    "PHQ-9 score ≥10 or HDRS-17 ≥14 at baseline assessment",
    "Age 18–75 years (exceptions at Doctor discretion with documented rationale)",
    "Stable pharmacological treatment for ≥4 weeks prior to enrolment, or actively managed by prescribing Doctor",
    "Capacity to provide informed consent",
    "Willing and able to attend sessions as prescribed",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Current active psychotic episode or psychotic features requiring urgent management",
    "Active suicidal ideation with intent or plan requiring inpatient psychiatric management",
    "Bipolar I disorder — current manic or hypomanic episode",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Bipolar II disorder or cyclothymia — consult prescribing psychiatrist before enrolment",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment by Doctor",
    "Epilepsy or seizure history — formal risk assessment required",
    "Pregnancy — taVNS/CES may be considered; tDCS/TPS at Doctor discretion with documented rationale",
    "Active dermatological conditions at electrode sites — assessment and protocol modification required",
    "Severe personality disorder — stability assessment and psychological input required",
    "Substance misuse — sobriety and capacity assessment required",
    "Recent major surgery (within 3 months) — surgical team clearance required",
    "Significant cognitive impairment affecting consent capacity — supported consent process",
  ],

  overviewParagraph: "Major Depressive Disorder (MDD) is one of the most prevalent and disabling psychiatric conditions worldwide, affecting approximately 280 million people globally according to WHO estimates. It is characterised by persistent low mood, anhedonia, cognitive dysfunction, psychomotor changes, neurovegetative symptoms (sleep and appetite disturbance), and in severe cases, suicidal ideation. MDD accounts for substantial disability-adjusted life years and is a leading cause of work absence and reduced quality of life across all age groups. The lifetime prevalence is approximately 15–18% in high-income countries. Despite the availability of effective pharmacological and psychological treatments, approximately 30–40% of patients do not achieve remission with first-line interventions, underscoring the need for adjunctive approaches such as FNON neuromodulation.",
  fnonNetworkParagraph: "Depression is not only a neurochemical imbalance — it is a large-scale network dysregulation condition. The FNON framework identifies disrupted interactions between the Default Mode Network (hyperactive rumination circuit), Central Executive Network (hypoactive prefrontal control), Salience Network (aberrant threat gating), and Limbic Network (dysregulated affective processing) as the core circuit-level pathology in MDD. SOZO targets these network abnormalities directly, moving beyond single-region stimulation to address the distributed architecture of depressive psychopathology.",
  networkDisorderParagraphs: [
    "Contemporary neuroscience frames MDD as a disorder of large-scale brain network organisation rather than localised pathology. Converging evidence from resting-state fMRI, diffusion tensor imaging, EEG, and PET demonstrates that depressive symptoms arise from dysregulated interactions among key brain networks. The DMN-CEN anti-correlation — which reflects healthy suppression of self-referential thought during goal-directed activity — is consistently disrupted in MDD, manifesting as intrusive rumination during cognitive tasks and impaired emotional regulation.",
    "Functional connectivity studies consistently demonstrate hyperconnectivity within the DMN (particularly between the subgenual ACC and PCC), hypoactivation of the DLPFC and CEN, and aberrant salience network gating that impairs appropriate network switching. These findings are replicated across MDD severity levels and in meta-analyses of neuroimaging studies, and partially normalise with effective pharmacological or psychological treatment.",
    "The FNON framework leverages these network abnormalities to guide precise, personalised neuromodulation: upregulating hypoactive DLPFC-CEN circuits via anodal tDCS, engaging deep limbic and subcortical nodes via TPS, and modulating autonomic-brainstem-limbic pathways via taVNS and CES. The multi-modal, multi-network approach addresses the heterogeneous network pathology of MDD phenotypes.",
  ],

  pathophysiologyText: "MDD pathophysiology involves complex interactions across multiple neurobiological systems. The monoamine hypothesis (serotonin, noradrenaline, dopamine deficits) remains clinically relevant but is insufficient to explain the full picture. Contemporary models emphasise: (1) dysregulation of the HPA axis with cortisol hypersecretion and hippocampal volume reduction via glucocorticoid neurotoxicity; (2) neuroinflammatory processes with elevated IL-6, TNF-α, and CRP that impair neuroplasticity and monoamine synthesis; (3) impaired BDNF signalling and synaptic plasticity in hippocampal and prefrontal circuits; (4) glutamatergic dysfunction including reduced NMDA tone and impaired long-term potentiation; and (5) large-scale brain network dysregulation. These mechanisms co-occur in varying combinations, producing the heterogeneous clinical presentations that map onto distinct FNON phenotypes. The HPA-neuroplasticity-network framework provides the integrated biological rationale for multi-modal FNON intervention.",
  cardinalSymptoms: [
    ["Depressed Mood", "Persistent sad, empty, or irritable mood; tearfulness; sense of hopelessness; most of the day, nearly every day", "Core criterion (100% by DSM-5 definition)", "American Psychiatric Association, 2022"],
    ["Anhedonia", "Markedly diminished interest or pleasure in previously enjoyable activities; motivational loss; reward processing deficit", "Core criterion (100% by DSM-5 definition)", "Treadway & Zald, 2011; Husain & Roiser, 2018"],
    ["Cognitive Dysfunction", "Poor concentration, indecisiveness, slowed processing speed, working memory impairment; subjective and objective", "~85–90% of MDD patients", "McIntyre et al., 2013; Rock et al., 2014"],
    ["Psychomotor Changes", "Psychomotor retardation (slowed movement, speech, thinking) or psychomotor agitation (restlessness, hand-wringing)", "~60% retardation; ~30% agitation", "Sobin & Sackeim, 1997"],
    ["Fatigue / Energy Loss", "Persistent fatigue, low energy, feeling slowed down even without exertion; anergia; tiredness on wakening", "~95%", "Fava et al., 2014"],
    ["Sleep Disturbance", "Insomnia (most common: middle or terminal insomnia) or hypersomnia; poor sleep quality; unrefreshing sleep", "~80%", "Nutt et al., 2008"],
    ["Appetite / Weight Change", "Decreased or increased appetite; significant weight change (≥5% body weight in one month)", "~70%", "American Psychiatric Association, 2022"],
    ["Worthlessness / Guilt", "Excessive or inappropriate guilt; feelings of worthlessness; self-blame; harsh self-criticism; rumination on past failures", "~70%", "Beck et al., 1979"],
    ["Suicidal Ideation", "Recurrent thoughts of death; passive suicidal ideation; active suicidal ideation with or without plan", "~50% passive; ~20% active ideation", "Hawton et al., 2013"],
    ["Social Withdrawal", "Reduced social interaction; avoidance of previously valued relationships and activities; interpersonal isolation", "~85%", "Rottenberg, 2007"],
    ["Somatic Symptoms", "Headache, GI symptoms, musculoskeletal pain, chest heaviness; somatic presentation especially common cross-culturally", "~60–80% with somatic component", "Simon et al., 1999"],
    ["Rumination", "Persistent, repetitive negative thinking about mood, its causes, and consequences; difficulty disengaging from negative thought", "~75%", "Nolen-Hoeksema et al., 2008"],
    ["Executive Dysfunction", "Impaired planning, cognitive flexibility, inhibitory control, decision-making; DLPFC-driven deficits affecting daily function", "~80–85%", "Snyder, 2013"],
  ],
  standardGuidelinesText: [
    "Current evidence-based clinical guidance for MDD positions antidepressant pharmacotherapy (SSRIs and SNRIs) as first-line treatment for moderate-to-severe depression, combined with structured psychotherapy (CBT, IPT, or behavioural activation) where available and indicated. NICE guidelines (2022), APA practice guidelines (2023), and CANMAT (2023) all support stepped-care models beginning with the least intensive effective interventions and escalating based on clinical response and patient preference.",
    "For treatment-resistant depression (TRD), defined as failure of ≥2 adequate antidepressant trials at therapeutic doses, evidence-based options include augmentation strategies (lithium, atypical antipsychotics such as aripiprazole and quetiapine, T3 thyroid), switching antidepressants, ketamine/esketamine (FDA-approved for TRD as Spravato), ECT (gold standard for severe or life-threatening refractory cases), and repetitive TMS (rTMS, FDA-cleared for MDD). Transcranial direct current stimulation (tDCS) is increasingly recognised as an evidence-based adjunct with Level B evidence from multiple RCTs and meta-analyses.",
    "SOZO FNON protocols are designed to complement and enhance standard-of-care treatments, not replace them. The treating Doctor coordinates FNON neuromodulation with the patient's pharmacological and psychotherapeutic treatment plan, with shared care documentation and regular outcome review at prescribed intervals.",
  ],

  fnonFrameworkParagraph: "The FNON framework is built on the principle that MDD symptoms arise from dysfunction within interconnected brain networks. SOZO's approach targets the specific network nodes most implicated in each patient's dominant symptom profile — moving beyond single-region DLPFC stimulation to address the multi-network architecture of depression, including the DMN-CEN anti-correlation, limbic-prefrontal regulation, and autonomic-brainstem-limbic modulation.",
  keyBrainRegions: [
    ["Dorsolateral Prefrontal Cortex (DLPFC)", "Hypoactivation; impaired executive control; reduced cognitive flexibility; DLPFC-ACC disconnection in MDD", "Anodal tDCS (F3/F4) increases DLPFC excitability; primary evidence-based target for MDD across ≥15 RCTs", "Lefaucheur et al., 2017; Brunoni et al., 2016"],
    ["Subgenual Anterior Cingulate Cortex (sgACC)", "Hyperactivity; central hub of DMN rumination circuit; key deep target for neuromodulation in TRD", "TPS targets sgACC/ACC region indirectly via DLPFC-sgACC pathway; taVNS modulates sgACC via NTS-vagal projections", "Mayberg et al., 2005; Fox et al., 2012"],
    ["Ventromedial Prefrontal Cortex (vmPFC)", "Excessive self-referential processing; impaired emotional valuation; reward devaluation; negative self-schema maintenance", "tDCS F3-Pz montage modulates mPFC; TPS mPFC targeting for reward network and emotional valuation circuits", "Price & Drevets, 2010"],
    ["Hippocampus", "Volume reduction (chronic stress / glucocorticoid neurotoxicity); impaired memory consolidation; spatial navigation deficits", "TPS deep targeting in hippocampal region; taVNS promotes BDNF/neurogenesis via NTS-LC-hippocampal pathways", "MacQueen & Frodl, 2011; Bremner, 2006"],
    ["Amygdala", "Hyperreactivity to negative stimuli; impaired extinction learning; sustained negative affect; fear generalisation", "Indirect modulation via anodal DLPFC tDCS (top-down regulatory pathway); TPS deep limbic targeting", "Drevets et al., 2008"],
    ["Anterior Cingulate Cortex (ACC)", "Impaired error monitoring, conflict detection; reduced cognitive control signal; theta oscillation abnormalities", "tDCS Fz montage engages ACC; taVNS ACC modulation via vagal-cingulate afferent pathways", "Pizzagalli, 2011"],
    ["Posterior Cingulate Cortex (PCC)", "DMN core node; hyperconnected in MDD; self-referential rumination anchor; deactivation failure during tasks", "Cathodal tDCS Pz; TPS holocranial with posterior cingulate targeting; combination reverses DMN hyperactivity", "Sheline et al., 2009"],
    ["Caudate / Striatum", "Reduced reward anticipation signal; impaired dopaminergic reward circuit; anhedonia substrate; reduced striatal activation to positive stimuli", "Indirect modulation via DLPFC-striatal prefrontal-subcortical pathway; TPS deep targeting of ventral striatum region", "Pizzagalli et al., 2009"],
    ["Insula", "Interoceptive amplification of negative body states; catastrophic interpretation of somatic symptoms; somatic depression substrate", "TPS insular targeting; taVNS modulates insula via visceral afferent projections through NTS-insula pathway", "Nummenmaa et al., 2014"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Primary relay for vagal afferents; mediates all taVNS effects on brainstem and limbic circuits; key entry point for autonomic modulation", "Direct target of taVNS; NTS→LC→cortex noradrenergic pathway is the primary mechanism of taVNS antidepressant effect", "Fang et al., 2016; Butt et al., 2020"],
    ["Locus Coeruleus (LC)", "Noradrenergic nucleus; reduced firing rate in depression; impaired arousal, attention, and emotional regulation via noradrenaline", "taVNS activates LC via NTS pathway; modulates noradrenaline release throughout cortex; enhances prefrontal signal-to-noise", "Manta et al., 2012"],
    ["Raphe Nuclei", "Serotonergic origin; impaired serotonin tone in MDD; mood, sleep, and appetite regulation; connectivity to amygdala and hippocampus", "taVNS modulates serotonergic raphe via brainstem connections; CES may enhance serotonergic tone through low-frequency current", "Schlaepfer et al., 2014"],
    ["Thalamus", "Relay station disrupted in MDD; altered thalamo-cortical rhythms; impaired cognitive gating; reduced spindle activity in depressed patients", "TPS thalamic targeting (indirect via DLPFC projections); taVNS modulates thalamo-cortical synchrony via brainstem-thalamic relays", "Papouin et al., 2017"],
    ["Ventral Tegmental Area (VTA)", "Dopaminergic reward pathway origin; reduced activity in anhedonic depression; impaired motivational drive", "Indirect modulation via DLPFC-NAcc-VTA loop upregulation; TPS deep mesolimbic targeting for anhedonic phenotype", "Russo & Nestler, 2013"],
    ["Habenula", "Anti-reward centre; hyperactive in depression; suppresses monoamine release; encodes negative reward prediction errors", "TPS deep targeting — habenula is an emerging target for TRD; indirect DLPFC modulation reduces habenular hyperactivity", "Sartorius et al., 2010"],
    ["Cerebellum", "Cognitive-affective cerebellar networks implicated in emotional timing, regulation, and prediction; cerebellar-limbic connections", "TPS cerebellar targeting for emotional-cognitive integration; tDCS Cbz electrode for cerebellar-prefrontal modulation", "Schmahmann, 2019"],
  ],
  keyFunctionalNetworks: [
    ["Default Mode Network (DMN)", "mPFC, sgACC, PCC, precuneus, angular gyrus, hippocampus", "Hyperconnectivity; pathological rumination; self-referential perseveration; impaired deactivation during goal-directed tasks", "Cathodal tDCS Pz (DMN hub suppression); TPS PCC/mPFC targeting; combined with cognitive engagement tasks to suppress DMN", "Sheline et al., 2009; Hamilton et al., 2015"],
    ["Central Executive Network (CEN)", "DLPFC, posterior parietal cortex (PPC), anterior PFC, lateral PFC", "Hypoactivation; impaired working memory, cognitive flexibility, decision-making; disrupted DLPFC-ACC executive-emotional regulation", "PRIMARY TARGET: anodal tDCS F3/F4; TPS DLPFC; dual-channel bilateral HDCkit for TRD; concurrent cognitive tasks", "Harvey et al., 2004; Barch et al., 2012"],
    ["Salience Network (SN)", "ACC, anterior insula, amygdala, basal ganglia, brainstem nuclei", "Aberrant saliency assignment to negative stimuli; excessive threat detection; impaired DMN-CEN network switching; anxiety-depression overlap", "tDCS Fz-Cz montage (ACC/mPFC); taVNS for insula-ACC modulation via NTS; TPS ACC and insula targeting", "Seeley et al., 2007; Menon, 2011"],
    ["Limbic Network", "Amygdala, hippocampus, vmPFC, OFC, sgACC, hypothalamus, parahippocampal gyrus", "Amygdala hyperreactivity; impaired vmPFC-amygdala regulatory connectivity; reward circuit dysfunction; HPA dysregulation cascade", "TPS deep limbic targets (most relevant for TRD); taVNS limbic modulation via brainstem; anodal DLPFC for top-down amygdala regulation", "Price & Drevets, 2010; Quirk & Beer, 2006"],
    ["Attention Network (DAN/VAN)", "FEF, IPS, TPJ, ACC, anterior insula, right hemisphere bias", "Impaired sustained attention; difficulty directing attention away from negative internal content; attentional bias to threat", "tDCS F3/P3 montage for attentional control; TPS PPC + DLPFC; sustained attention training as concurrent task", "Disner et al., 2011"],
    ["Sensorimotor Network (SMN)", "M1, SMA, premotor cortex, somatosensory cortex, cerebellum", "Psychomotor retardation and slowing; reduced motor initiation and execution; heaviness; slowed movement, speech, and response times", "tDCS C3/C4 + Fz montage for psychomotor retarded phenotype; TPS motor cortex and SMA targeting", "Buyukdura et al., 2011"],
    ["Reward / Mesolimbic Network", "VTA, nucleus accumbens, caudate, putamen, OFC, vmPFC, habenula", "Reduced reward anticipation (blunted striatal BOLD response); impaired effort-cost computation; anhedonia and motivational deficit substrate", "TPS deep mesolimbic targeting; DLPFC anodal tDCS (striatal modulation via PFC-striatal efferents); reward activation tasks", "Pizzagalli et al., 2009; Treadway & Zald, 2011"],
  ],
  networkAbnormalities: [
    "Default Mode Network (DMN): Hyperconnectivity within the DMN — particularly between the subgenual ACC, PCC, and medial PFC — is the most replicated neuroimaging finding in MDD across more than 50 independent studies. This manifests clinically as persistent rumination, self-critical thinking, and difficulty disengaging from negative self-referential thought during tasks. DMN hyperactivity during rest and failure to adequately suppress during externally-directed tasks is a distinguishing characteristic of MDD compared to healthy controls and other psychiatric conditions.",
    "Central Executive Network (CEN): Hypoactivation of the DLPFC and associated dorsal CEN is consistently associated with impaired working memory, cognitive flexibility, attentional control, and emotion regulation in MDD. Meta-analyses of neuroimaging studies confirm reduced DLPFC activation during cognitive tasks. The CEN-DMN anti-correlation is disrupted, allowing DMN rumination activity to intrude into task-directed cognitive states and perpetuating the cognitive symptoms of depression.",
    "Salience Network (SN): The SN shows altered coupling and aberrant gating function in MDD. Rather than appropriately switching between DMN (rest/self-referential) and CEN (task/goal-directed) states based on environmental demands, the SN maintains a persistent bias toward negative salience detection and fails to adequately suppress ruminative DMN activity. This manifests as heightened emotional reactivity, threat hypervigilance, and anxiety-depressive comorbidity.",
    "Limbic Network: Amygdala hyperreactivity and impaired vmPFC-amygdala regulatory connectivity underlie affective dysregulation, negative bias, and fear generalisation in MDD. Hippocampal volume reduction (averaging 8–10% in chronic MDD meta-analyses) reduces contextual discrimination and promotes overgeneralised fear responses, hopelessness, and impaired reward memory. The HPA-limbic axis dysregulation perpetuates glucocorticoid neurotoxicity and neuroinflammation.",
    "Reward / Mesolimbic Network: Blunted striatal activation to reward anticipation, measured by fMRI reward paradigms, is a robust and reproducible biomarker of anhedonia in MDD. Reduced DLPFC-striatal functional connectivity impairs effortful reward-seeking behaviour and motivational engagement. This network-level anhedonia is partially dissociable from core mood symptoms and represents a specific target for FNON intervention in the anhedonic phenotype.",
  ],
  conceptualFramework: "MDD is best understood as a network excitability and connectivity disorder characterised by three core circuit-level abnormalities: (1) DMN hyperactivity driving rumination and negative self-reference; (2) CEN hypoactivity impairing cognitive control and emotion regulation; and (3) Limbic-SN dysregulation perpetuating threat bias and blunted reward processing. The FNON framework targets these abnormalities simultaneously using multi-modal neuromodulation, with the S-O-Z-O sequence designed to stabilise autonomic arousal, upregulate prefrontal control, engage deep limbic circuits, and consolidate network changes through activity-dependent behavioural practice.",

  clinicalPhenotypes: [
    ["Melancholic Depression", "CEN hypofunction + Limbic hyperactivity + Reward network suppression + SMN retardation; loss of mood reactivity", "Fried & Nesse, 2015; Taylor & Fink, 2006"],
    ["Atypical Depression", "Limbic network hyperreactivity + reward circuit hypersensitivity (interpersonal rejection); SN dysregulation with preserved mood reactivity", "Asnis & McGinn, 2014; Parker, 2007"],
    ["Anxious Depression", "SN hyperactivity + Amygdala-ACC hyperconnectivity + DMN-SN overlap; high autonomic arousal; worry comorbidity", "Fava et al., 2004; Ionescu et al., 2013"],
    ["Treatment-Resistant Depression (TRD)", "Multi-network dysfunction; impaired neuroplasticity; deep limbic and sgACC pathology; CEN and Limbic network failure", "Bauer et al., 2013; Mayberg et al., 2005"],
    ["Psychomotor-Retarded Depression", "SMN hypofunction + DLPFC-SMA disconnection + Basal ganglia–cortical circuit slowing; pronounced motor and speech slowing", "Sobin & Sackeim, 1997; Buyukdura et al., 2011"],
    ["Cognitive / Executive Phenotype", "CEN hypofunction (DLPFC-PPC) dominant; working memory deficit; frontal processing speed reduction; mild cognitive impairment risk", "McIntyre et al., 2013; Snyder, 2013"],
    ["Insomnia-Predominant Depression", "SN-DMN dysregulation + thalamo-cortical hyperarousal + HPA axis dysregulation; sleep continuity severely disrupted", "Nutt et al., 2008; Harvey, 2002"],
    ["Anhedonic Depression", "Reward network hypofunction (VTA-NAcc-striatum) + DLPFC-striatal disconnection + blunted dopaminergic reward signalling dominant", "Husain & Roiser, 2018; Pizzagalli et al., 2009"],
    ["Somatic / Pain-Predominant Depression", "Insula hyperactivity + SN dysfunction + altered interoceptive processing + descending pain modulation failure", "Simon et al., 1999; Nummenmaa et al., 2014"],
  ],
  symptomNetworkMapping: [
    ["Low mood / hopelessness", "Limbic (sgACC-vmPFC)", "DMN; SN", "TPS limbic targeting + taVNS V2 (NTS-LC-raphe) + tDCS F3 anodal L-DLPFC", "Moderate (Brunoni 2016; Lefaucheur 2017; Fregni 2020)"],
    ["Anhedonia / motivational deficit", "Reward/Mesolimbic (VTA-NAcc-striatum)", "DLPFC-striatal; Limbic", "TPS deep limbic + tDCS DLPFC bilateral F3/F4 + taVNS V2 + reward activation tasks", "Emerging (Pizzagalli 2009; Burkhouse 2020)"],
    ["Rumination / negative thought", "DMN (PCC-mPFC-sgACC)", "SN; Limbic", "Cathodal tDCS Pz + anodal F3 (anti-correlation restoration) + TPS DMN nodes + cognitive engagement task", "Moderate (Hamilton 2015; Hecht 2010)"],
    ["Cognitive dysfunction / concentration", "CEN (DLPFC-PPC)", "SMN; Attention network", "tDCS F3/F4 bilateral anode + TPS DLPFC + working memory / n-back training concurrent", "Moderate (Brunoni 2016; McIntyre 2013)"],
    ["Psychomotor retardation", "SMN + CEN", "Basal ganglia; SN", "tDCS C3/C4 + Fz dual anodal + TPS motor cortex + SMA + movement exercises concurrent", "Emerging (Buyukdura 2011; Brunoni 2016)"],
    ["Anxiety / hyperarousal", "SN (ACC-insula-amygdala)", "DMN; Limbic", "taVNS V1 + CES Alpha-Stim + tDCS Fz/F3 + relaxation/mindfulness tasks concurrent", "Moderate (Fang 2016; Kavirajan 2014)"],
    ["Sleep disturbance", "Thalamo-cortical oscillations; SN hyperarousal", "DMN; Limbic; HPA", "taVNS V4 low-frequency + CES Alpha-Stim + tDCS F4 right DLPFC + sleep hygiene tasks", "Emerging (Nutt 2008; Shekelle 2018)"],
    ["Somatic symptoms / pain", "Insula; SN", "Limbic; Descending pain modulation", "taVNS V5 + tDCS Fz-Pz + TPS insular targeting + body awareness / graded activity tasks", "Emerging (Simon 1999; Nummenmaa 2014)"],
    ["Social withdrawal", "SN + Limbic (amygdala-vmPFC)", "DMN; CEN", "tDCS F3/F4 + TPS ACC + social engagement / activation tasks during stimulation window", "Emerging (Rottenberg 2007)"],
    ["Fatigue / anergia", "Reward network; CEN", "SMN; Limbic", "tDCS F3 + Cbz dual anodal (energising montage) + taVNS V1 + graded activity scheduling", "Emerging (Fava 2014; Brunoni 2016)"],
  ],

  montageSelectionRows: [
    ["Low mood / anhedonia dominant (Melancholic, Anhedonic phenotype)", "tDCS F3 anode (L-DLPFC) Pz cathode + TPS DLPFC + limbic + taVNS V2; standard S-O-Z-O sequence"],
    ["Rumination / DMN dominant (Melancholic, Cognitive phenotype)", "tDCS F3 anode + Pz cathode (anti-correlation DMN suppression) + TPS PCC/mPFC + cognitive engagement concurrent task"],
    ["Anxious depression / SN dominant (Anxious, Insomnia-Predominant phenotype)", "taVNS V1 pre-session + CES Alpha-Stim + tDCS Fz/F3 anode + relaxation during stimulation"],
    ["Treatment-resistant / multi-network failure (TRD phenotype)", "Full SOZO protocol: taVNS V2 → tDCS F3+F4 dual bilateral → TPS DLPFC+Limbic+Holocranial → taVNS/CES consolidation"],
    ["Psychomotor retardation dominant (Psychomotor phenotype)", "tDCS C3/Cz anode (SMN) + Fz/F4 dual + TPS motor cortex + SMA + movement exercises concurrent"],
    ["Cognitive / executive dominant (Cognitive phenotype)", "tDCS F3/F4 bilateral anode (HDCkit dual-channel) + PPC + TPS DLPFC + PPC + n-back/WM tasks concurrent"],
    ["Insomnia-predominant / hyperarousal (Insomnia-Predominant phenotype)", "taVNS V4 low-frequency + CES Alpha-Stim pre-sleep + tDCS F4 right DLPFC + sleep hygiene education"],
    ["Anhedonia / reward circuit dominant (Anhedonic phenotype)", "tDCS F3+F4 bilateral anodes + TPS deep limbic/mesolimbic + reward-seeking behavioural activation tasks"],
    ["Somatic / pain-predominant (Somatic phenotype)", "taVNS V5 + tDCS Fz-Pz + TPS insula targeting + body awareness / somatosensory training tasks"],
    ["Post-antidepressant augmentation (partial responder — any phenotype)", "tDCS F3 (standard 2mA 30min) + taVNS V2 concurrent + TPS DLPFC 6,000 pulses; optimise timing to medication peak"],
    ["Severe / TRD escalation (TRD with multiple failures)", "HDCkit dual F3+F4 bilateral 2mA each + TPS 10,000–12,000 pulses DLPFC+ACC+Limbic+Holocranial + full taVNS/CES sequence"],
    ["Maintenance / prevention of relapse (remitted MDD)", "PlatoScience home tDCS F3 1mA 20min 3×/week + weekly taVNS V1 + behavioural activation programme"],
    ["Depression with marked fatigue / anergia (Melancholic, Somatic phenotype)", "tDCS F3+Cbz anodes (energising configuration) + TPS DLPFC+motor+PPC + graded activity scheduling concurrent"],
  ],

  polarityPrincipleText: "In MDD according to the SOZO FNON concept: Anode is applied over the left DLPFC (F3) to increase hypoactive prefrontal excitability — this is the most replicated and evidence-based montage across all MDD subtypes. Cathode over right DLPFC (F4) for classical unilateral configuration, or over Pz for DMN suppression effects, or extracephalic to minimise inhibition of the therapeutic network. Bilateral DLPFC anodal stimulation (HDCkit dual-channel F3+F4) is used for treatment-resistant and cognitive phenotypes requiring maximum bilateral prefrontal engagement. Right DLPFC anodal (F4) is preferred for insomnia-predominant and hyperarousal presentations where right-hemisphere prefrontal modulation reduces nocturnal arousal.",
  polarityTable: [
    ["Hypoactive L-DLPFC (executive, cognitive, mood dominant)", "Anode F3; Cathode F4 or Pz or extracephalic"],
    ["DMN hyperactivity / rumination dominant", "Anode F3 + Cathode Pz (anti-correlation restoration target)"],
    ["Bilateral prefrontal deficit (TRD, Cognitive phenotype)", "Bilateral anodes F3+F4 (HDCkit dual-channel at 2mA each)"],
    ["Insomnia / hyperarousal phenotype dominant", "Anode F4 (right DLPFC arousal modulation); Cathode F3 or Fz"],
    ["Somatic / insula-dominant phenotype", "Anode Fz + Cathode Pz; combined with taVNS V5 for insula-SN modulation"],
  ],
  classicTdcsProtocols: [
    ["C1", "Low mood / anhedonia (primary MDD)", "F3 (L-DLPFC)", "F4 (R-DLPFC) or Pz or extracephalic", "2 mA, 20–30 min, 1–2× daily for 10–20 sessions", "Level B; supported by >10 RCTs and multiple meta-analyses (Brunoni 2016; Lefaucheur 2017; Razza 2020)"],
    ["C2", "Treatment-resistant depression (TRD)", "F3 + F4 bilateral (HDCkit dual-channel)", "Extracephalic (shoulder) or Pz", "2 mA/channel, 30 min, daily × 10–20 sessions", "Emerging; bilateral superior to unilateral in TRD phenotype (Brunoni 2013; Palm 2017)"],
    ["C3", "Cognitive dysfunction in MDD", "F3 (L-DLPFC) + P3 (L-PPC optional)", "F4 or extracephalic", "2 mA, 20–30 min, 10 sessions", "Level B; improves working memory and processing speed (Brunoni 2016; Fregni 2020)"],
    ["C4", "Anxious depression / SN dominant", "Fz (medial PFC / ACC region)", "Pz or extracephalic", "1.5–2 mA, 20 min; combine with taVNS V1 pre-session", "Level C; anxiety-depression comorbidity (Loo 2012; Berlim 2013)"],
    ["C5", "Anhedonia / reward deficit dominant", "F3 + F4 bilateral anode (HDCkit dual-channel)", "Extracephalic (both channels)", "2 mA/channel (HDCkit), 30 min, 15 sessions", "Emerging (Burkhouse 2020; Pizzagalli 2009)"],
    ["C6", "Psychomotor retardation dominant", "C3/C4 (M1 bilateral) + Fz (SMA/DLPFC) — HDCkit dual", "Extracephalic or contralateral shoulder", "2 mA, 20 min; combine with movement-based tasks", "Emerging (Sobin & Sackeim 1997; Brunoni 2016; Buyukdura 2011)"],
    ["C7", "Insomnia-predominant MDD", "F4 (R-DLPFC)", "F3 or Pz", "1–2 mA, 20–30 min; afternoon or early evening session preferred", "Emerging (Kalu 2012; Fregni 2020)"],
    ["C8", "Maintenance / relapse prevention (home-based)", "F3 (L-DLPFC) — PlatoScience home device", "Pz or extracephalic (contra shoulder)", "1 mA, 20 min, 3× per week (home protocol prescribed by Doctor)", "Level C; maintenance after acute course (Palm 2017; Meron 2015)"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Executive dysfunction ± mood (Cognitive/Melancholic phenotype)", "CEN hypofunction with DMN intrusion — bilateral prefrontal deficit", "Anodes F3+F4 (bilateral DLPFC HDCkit dual-channel 2mA each); Cathode Pz (DMN suppression via P-occipital reference)", "Restore CEN-DMN anti-correlation; improve cognitive control and suppress rumination network"],
    ["F2", "Anhedonia / reward deficit (Anhedonic phenotype)", "Reward network hypofunction — DLPFC-striatal disconnection + mesolimbic hypoactivation", "Anode F3+F4 + Cz (HDCkit dual-channel); Cathode extracephalic both channels; reward activation tasks concurrent", "Upregulate DLPFC-striatal pathway; increase reward anticipation signal; reduce motivational deficit"],
    ["F3", "Anxious depression / SN dominant (Anxious, Insomnia-Predominant)", "SN hyperactivity + DMN-SN coupling excess + high autonomic arousal", "Anode Fz (mPFC/ACC region); Cathode Cz or extracephalic; taVNS V1 concurrent; relaxation task", "Modulate SN-ACC activity; reduce threat bias; restore SN gating function; reduce anxiety-depression comorbidity"],
    ["F4", "Psychomotor retardation / SMN dominant (Psychomotor phenotype)", "SMN hypofunction + DLPFC-SMA disconnection — corticospinal slowing", "Anodes Fz+C3/C4 (HDCkit dual: DLPFC+M1 bilateral); Cathode extracephalic; movement tasks concurrent during stimulation", "Increase corticospinal and SMA excitability; reduce psychomotor slowing; enhance motor initiation"],
    ["F5", "Somatic / pain phenotype (Somatic phenotype)", "Insula-SN hyperactivity + altered interoceptive processing + descending pain modulation failure", "Anode Fz + Cathode Pz (insula-mPFC modulation); taVNS V5 concurrent; body awareness tasks", "Modulate insula-SN circuit; improve interoceptive regulation; reduce somatic amplification"],
    ["F6", "TRD / multi-network failure (all TRD subphenotypes)", "Pan-network dysfunction; impaired neuroplasticity across CEN, Limbic, and Reward networks", "HDCkit dual F3+F4 bilateral anodes at maximum (2mA each); CES pre-session for state preparation; TPS escalation indicated for non-responders", "Maximum prefrontal bilateral engagement; facilitate plasticity window for subsequent TPS intervention"],
  ],
  classicTpsProtocols: [
    ["T1", "Low mood / anhedonia (core MDD)", "DLPFC bilateral + mPFC/sgACC region", "0.20–0.25 mJ/mm²; 1–6 Hz; 10–12 sessions over 4 weeks", "4,000 DLPFC bilateral (2K each) ± 4,000 mPFC; 6,000–10,000 total", "Emerging (Feusner 2023; George 2024)"],
    ["T2", "Treatment-resistant depression (TRD)", "DLPFC bilateral + sgACC + Limbic + Holocranial", "0.20–0.25 mJ/mm²; 3–6 Hz; 12–16 sessions", "2,500 DLPFC×2 + 2,000 mPFC/sgACC + 1,500 limbic + 1,500 holocranial = 10,000 total", "Emerging (Hausmann 2020; Fox 2012)"],
    ["T3", "Cognitive / executive phenotype", "DLPFC bilateral + PPC + Hippocampus region", "0.15–0.20 mJ/mm²; 1–4 Hz; 10 sessions", "3,000 DLPFC + 2,000 PPC + 2,000 hippocampus + 3,000 holocranial = 10,000 total", "Emerging (Feusner 2023)"],
    ["T4", "Anhedonia / reward dominant", "DLPFC bilateral + Limbic (amygdala/ventral striatum region) + Holocranial", "0.20 mJ/mm²; 3–6 Hz; 10 sessions", "4,000 DLPFC bilateral + 3,000 limbic + 3,000 holocranial = 10,000 total", "Emerging"],
    ["T5", "Somatic / pain-predominant depression", "Insula + DLPFC + Holocranial", "0.15–0.20 mJ/mm²; 1–4 Hz; 10 sessions", "3,000 insula bilateral + 3,000 DLPFC + 4,000 holocranial = 10,000 total", "Emerging"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Melancholic / anhedonic", "CEN hypofunction + Limbic hyperactivity + Reward deficit (DLPFC-sgACC-striatum loop)", "DLPFC bilat + sgACC/mPFC + Limbic + Holocranial", "3,000 DLPFC (1,500 each) + 2,000 mPFC/sgACC + 2,000 limbic + 3,000 holocranial = 10,000", "12 sessions/4 wks (3/wk)"],
    ["FT2", "Anxious depression", "SN hyperactivity + Amygdala-ACC dysregulation + high autonomic tone", "DLPFC + ACC + Insula bilateral + PRE (retroauricular bilateral)", "3,000 DLPFC + 2,000 ACC + 2,000 insula + 3,000 PRE = 10,000", "10 sessions/3–4 wks"],
    ["FT3", "Treatment-resistant / multi-network", "Pan-network failure; sgACC hyperactivity; deep limbic and CEN pathology", "DLPFC bilat + mPFC/sgACC + Limbic + PPC + Holocranial", "2,000 DLPFC each + 2,000 mPFC + 2,000 limbic + 2,000 PPC = 10,000", "12–16 sessions/5–6 wks"],
    ["FT4", "Psychomotor retardation dominant", "SMN hypofunction + CEN-SMN disconnection + corticospinal slowing", "DLPFC bilateral + M1/SMA + PPC + Holocranial", "3,000 DLPFC + 2,000 M1/SMA + 2,000 PPC + 3,000 holocranial = 10,000", "10 sessions/3–4 wks"],
    ["FT5", "Cognitive / executive dysfunction dominant", "CEN hypofunction; DLPFC-PPC disconnection; working memory network", "DLPFC bilat + PPC bilat + Hippocampus + Holocranial", "2,000 DLPFC×2 + 2,000 PPC + 2,000 hippocampus + 2,000 holocranial = 10,000", "12 sessions/4 wks"],
    ["FT6", "Insomnia / hyperarousal dominant", "SN-DMN dysregulation; thalamo-cortical hyperarousal; frontal beta excess", "R-DLPFC + mPFC + ACC + PRE bilateral (mastoid/retroauricular) + Holocranial", "2,000 R-DLPFC + 2,000 mPFC + 2,000 ACC + 2,000 PRE + 2,000 holocranial = 10,000", "10 sessions/3–4 wks"],
    ["FT7", "Anhedonic / reward deficit", "Reward network hypofunction; DLPFC-striatal disconnection; mesolimbic hypoactivation", "DLPFC bilat + Limbic (ventral striatum/amygdala region) + mPFC + Holocranial", "2,500 DLPFC×2 + 2,500 limbic + 2,500 mPFC + 2,500 holocranial = 10,000", "12 sessions/4 wks"],
    ["FT8", "Somatic / pain-predominant", "Insula-SN hyperactivity; descending pain modulation failure; interoceptive amplification", "DLPFC + Insula bilateral + mPFC + PRE + Holocranial", "2,000 DLPFC + 2,500 insula + 2,000 mPFC + 1,500 PRE + 2,000 holocranial = 10,000", "10 sessions/3–4 wks"],
    ["FT9", "Somatic / grief / moral injury (Somatic, complex grief variant)", "DMN-Limbic hyperconnectivity; PCC-mPFC perseveration; loss-related network activation", "mPFC + PCC + ACC + DLPFC bilateral + Holocranial", "2,000 mPFC + 2,000 PCC + 2,000 ACC + 2,000 DLPFC + 2,000 holocranial = 10,000", "10 sessions/3–4 wks"],
  ],

  multimodalPhenotypes: [
    {
      name: "Melancholic / Anhedonic",
      combinations: [
        ["TPS + tDCS", "O→Z: tDCS primes DLPFC-CEN excitability and limbic top-down control; TPS FT1 drives deep sgACC/limbic network engagement for anhedonia/melancholia", "tDCS F3/F4 bilateral 20–25 min before TPS FT1; behavioural activation/reward-seeking task in 30-min post-stimulation plasticity window", "Core melancholic features: anhedonia, diurnal variation, psychomotor changes; anhedonic phenotype; low mood with severe loss of pleasure"],
        ["TPS + tVNS", "S→Z→O: taVNS V2 stabilises autonomic tone and activates NTS-LC noradrenergic pathway pre-TPS; post-TPS taVNS consolidates limbic network changes", "taVNS V2 10–15 min pre-TPS; optional 10–20 min post-TPS for neuroplasticity consolidation", "Melancholic with autonomic features; poor stress tolerance; severe blunted reactivity; vegetative features prominent"],
        ["tDCS + tVNS + CES", "S→O: CES pre-session reduces arousal baseline; taVNS V2 activates brainstem-limbic noradrenaline axis; tDCS F3/F4 bilateral optimises DLPFC-CEN", "CES 20 min → taVNS V2 concurrent with tDCS F3/F4; total ~50 min session", "Non-TPS days; home-based continuation protocol; maintenance phase; step-down from intensive TPS block"],
        ["Full SOZO S-O-Z-O (taVNS→tDCS→TPS→taVNS/CES)", "Complete S-O-Z-O cycle: maximum multi-level network engagement for melancholic/TRD presentations requiring intensive intervention", "taVNS V2 20 min → tDCS F3/F4 dual 30 min → TPS FT1 10,000 pulses → taVNS/CES 20 min; ~100–120 min total; Doctor-supervised only", "Intensive in-clinic block for TRD-melancholic; non-responders to standard tDCS; maximum intervention protocol before ECT consideration"],
      ]
    },
    {
      name: "Atypical Depression",
      combinations: [
        ["TPS + tDCS", "O→Z: tDCS F3/F4 primes limbic-prefrontal regulatory pathway; TPS FT7 targets reward/amygdala circuitry for mood reactivity improvement and rejection sensitivity", "tDCS F3/F4 20 min before TPS FT7 limbic targeting; pleasant activity/reward scheduling task post-stimulation", "Atypical features: preserved mood reactivity, interpersonal rejection sensitivity, hypersomnia, leaden paralysis, carbohydrate craving"],
        ["TPS + tVNS", "S→Z→O: taVNS V2 modulates autonomic-limbic axis; attenuates rejection hypersensitivity via NTS-LC-amygdala regulatory pathway", "taVNS V2 pre-TPS; concurrent pleasant imagery / positive activation task during and after", "High interpersonal anxiety overlay; social-rejection-triggered depressions; high autonomic reactivity to emotional stimuli"],
        ["tDCS + CES", "S→O: CES reduces pre-session hyperarousal and somatic anxiety; tDCS F4 (right DLPFC) targets mood-reactive atypical presentations", "CES 20 min; then tDCS F4 20–30 min with pleasant activity / positive imagery concurrent", "Milder atypical presentations; home-based protocol; good tolerability; first-line for outpatient atypical phenotype"],
        ["Full SOZO atypical protocol", "S-O-Z-O: stabilise mood reactivity → optimise prefrontal-limbic balance → zone-target reward circuits → consolidate with reward activation", "Full S-O-Z-O sequence: CES → taVNS V2 → tDCS F4 → TPS FT7 → reward activation task", "Treatment-resistant atypical; hypersomnia-dominant with severe functional impairment; leaden paralysis variant"],
      ]
    },
    {
      name: "Anxious Depression",
      combinations: [
        ["TPS + tDCS", "O→Z: tDCS Fz/ACC primes SN-mediated threat circuit modulation; TPS FT2 targets ACC + insula for salience normalisation and anxiety reduction", "taVNS V1 15 min pre-session → tDCS Fz/F3 20–25 min → TPS FT2 10,000 pulses; relaxation/mindfulness task concurrent with tDCS", "Anxious MDD; GAD comorbidity; panic features; high cortisol/arousal; worry-dominant presentation"],
        ["TPS + tVNS", "S→Z→O: taVNS V1 provides sustained vagal anti-arousal priming; TPS FT2 ACC/insula targeting reduces threat hypervigilance; post-TPS consolidation", "taVNS V1 20 min pre-TPS; post-TPS taVNS V1 10–15 min + CES consolidation", "High arousal anxious MDD; autonomic dysregulation; cardiac anxiety symptoms; PHQ-A elevated"],
        ["CES + tDCS", "S→O: Alpha-Stim CES reduces pre-session anxiety baseline; tDCS Fz optimises ACC-SN modulation for anxiety-depression interface", "CES 20–30 min concurrent with tDCS Fz 20 min; mindfulness / diaphragmatic breathing concurrent task", "Mild-moderate anxious MDD; home-based first-line; easily tolerated by anxious patients"],
        ["Full SOZO anxious protocol", "Complete anxiolytic-antidepressant S-O-Z-O cycle targeting SN-DMN-Limbic networks simultaneously", "CES 20 min → taVNS V1 20 min → tDCS Fz/F3 30 min → TPS FT2 10,000 pulses → CES/taVNS post-consolidation", "Severe anxious MDD; failed SSRI monotherapy; panic complicating treatment; high somatic anxiety with depression"],
      ]
    },
    {
      name: "Treatment-Resistant Depression (TRD)",
      combinations: [
        ["TPS + tDCS bilateral (TRD first-line FNON)", "O→Z: HDCkit dual-channel F3+F4 bilateral anodal provides maximum DLPFC CEN engagement; TPS FT3 multi-site pan-network delivery targeting sgACC and limbic", "tDCS bilateral F3+F4 2mA each 30 min → TPS FT3 10,000–12,000 pulses; behavioural activation / reward task post-stimulation", "TRD: failure of ≥2 adequate antidepressant trials; all MDD subtypes; severe/chronic MDD; ketamine-unwilling"],
        ["TPS + tVNS (intensive augmentation)", "S→Z→O: extended taVNS V2 pre-TPS priming; post-TPS consolidation; adjunctive to ongoing pharmacotherapy optimisation", "taVNS V2 30 min pre-TPS; TPS FT3; post-TPS taVNS V1 20 min; 3×/week intensive 4-week block", "TRD with autonomic dysregulation; high dropout from oral AD; esketamine adjunct candidate; ECT-unwilling"],
        ["Full SOZO TRD protocol (maximum intensity)", "Complete S-O-Z-O pan-network engagement: CES→taVNS→dual tDCS→TPS→consolidation; maximum network modulation", "CES 20 min → taVNS V2 20 min → tDCS F3+F4 dual 30 min → TPS FT3 12,000 pulses → taVNS/CES 20 min; ~110 min total", "Severe TRD; chronic course; multiple failures; last step before ECT; highly refractory presentations"],
        ["Maintenance after TRD response (relapse prevention)", "O: Continuation tDCS + taVNS to prevent relapse in TRD responders; maintenance of network gains", "PlatoScience home tDCS F3 1mA 20min 3×/week + weekly in-clinic taVNS V1 30min; ongoing 6–12 months minimum", "TRD responders to FNON course; high relapse risk; unstable remission; prophylactic continuation protocol"],
      ]
    },
    {
      name: "Psychomotor-Retarded Depression",
      combinations: [
        ["TPS + tDCS (motor-prefrontal upregulation)", "O→Z: tDCS dual-channel Fz+C3/C4 primes DLPFC-SMA-M1 circuit for psychomotor upregulation; TPS FT4 targets motor cortex + SMA + DLPFC with concurrent movement", "tDCS dual Fz+C3 20 min → TPS FT4 motor+DLPFC+PPC; physical movement task (walking, occupational therapy) concurrent during post-TPS window", "Psychomotor retardation dominant; severely slowed speech; leaden paralysis; melancholic-retarded subtype; severe anergia"],
        ["TPS + tVNS (arousal priming)", "S→Z: taVNS V1 activates LC noradrenaline pathway (arousal/motor engagement upregulation); TPS FT4 motor cortex + SMA targeting", "taVNS V1 15 min pre-TPS; movement/walking task during post-TPS 30-min plasticity window", "Low arousal with severe retardation; fatigue complicating motor engagement; first session titration starting point"],
        ["tDCS + motor tasks (home-based)", "O: tDCS Fz+C3/C4 dual-channel motor-frontal excitability upregulation; graded physical activity engagement concurrent", "tDCS C3/Fz dual 30 min with active motor drills; physiotherapy-guided graded exercises prescribed", "Moderate retardation; home-based or ambulatory clinic; physical activity prescription; step-down from intensive TPS block"],
        ["Full SOZO psychomotor protocol", "Complete S-O-Z-O psychomotor upregulation cycle", "taVNS V1 → tDCS Fz+C3/C4 dual → TPS FT4 → movement / occupational therapy task post-stimulation", "Severe psychomotor retardation; occupational impairment; melancholic-retarded; physical activity avoidance complicating rehabilitation"],
      ]
    },
    {
      name: "Cognitive / Executive Dysfunction",
      combinations: [
        ["TPS + tDCS cognitive (bilateral CEN)", "O→Z: tDCS F3/F4 bilateral dual-channel CEN priming; TPS FT5 DLPFC+PPC+hippocampus for deep executive-memory circuit engagement", "tDCS F3/F4 dual 30 min → TPS FT5; n-back/working memory training task concurrent during tDCS and post-stimulation window", "Cognitive MDD; workplace dysfunction; MCI-risk profile; processing speed deficit; cognitive complaints predominant"],
        ["TPS + tVNS cognitive", "S→O→Z: taVNS V3 cognitive protocol; NTS→LC noradrenaline enhances prefrontal signal-to-noise ratio for executive processing", "taVNS V3 20 min → tDCS F3/F4 → TPS FT5 DLPFC+PPC+hippocampus; cognitive training task during plasticity window", "Cognitive dominant; attention/concentration impairment; executive slowing; occupational dysfunction requiring cognitive focus"],
        ["tDCS + cognitive training (outpatient)", "O: Bilateral DLPFC tDCS during computerised cognitive training for synergistic CEN plasticity induction", "tDCS F3/F4 dual 30 min + concurrent n-back, attention, problem-solving, verbal fluency tasks", "Mild-moderate cognitive MDD; outpatient continuation; home tDCS PlatoScience protocol with app-based cognitive training"],
        ["Full SOZO cognitive protocol (maximal CEN)", "Complete S-O-Z-O maximal CEN engagement cycle", "CES 20 min → taVNS V3 → tDCS F3/F4 dual → TPS FT5 → cognitive consolidation task", "Severe cognitive MDD; MCI-risk; treatment-resistant cognitive symptoms; occupational rehabilitation requirement"],
      ]
    },
    {
      name: "Insomnia-Predominant Depression",
      combinations: [
        ["TPS + tDCS (sleep-arousal-mood)", "O→Z: tDCS F4 (right DLPFC) + Fz primes SN-thalamic hyperarousal regulation; TPS FT6 targets SN-DMN-ACC hyperarousal network nodes", "tDCS F4/Fz 20–25 min → TPS FT6; sleep hygiene psychoeducation during post-stimulation window", "Insomnia-dominant MDD; high nocturnal cortical arousal; early morning waking; disrupted sleep architecture"],
        ["CES + taVNS (sleep stabilisation primary)", "S: Combined CES (primary device) + slow-frequency taVNS V4 for maximum autonomic downregulation and sleep circuit preparation", "Evening protocol: CES 30 min + taVNS V4 slow concurrent; pre-sleep use 30–60 min before intended sleep onset", "Non-TPS evenings; home-based sleep optimisation; first-line adjunct for insomnia-MDD comorbidity; CES primary tool"],
        ["tDCS + sleep hygiene (CBT-I adjunct)", "O: Right DLPFC anodal (F4) tDCS + structured CBT-I sleep hygiene techniques as concurrent psychoeducation", "Afternoon session: tDCS F4 1.5–2mA 20 min; sleep hygiene CBT-I tasks (sleep restriction, stimulus control prescription)", "Mild-moderate insomnia-MDD; outpatient; home tDCS with sleep diary; CBT-I as concurrent intervention"],
        ["Full SOZO insomnia-depression protocol", "Complete S-O-Z-O dual-network (insomnia + depression) targeting", "CES pre-session → taVNS V4 → tDCS F4/Fz → TPS FT6 → CES/taVNS consolidation; timing: afternoon sessions only", "Refractory insomnia-MDD; CBT-I partial responders; high hyperarousal score; complex sleep-mood interaction"],
      ]
    },
    {
      name: "Anhedonic Depression",
      combinations: [
        ["TPS + tDCS (reward circuit upregulation)", "O→Z: tDCS F3/F4 bilateral dual-channel primes DLPFC-striatal pathway; TPS FT7 deep limbic/mesolimbic reward area engagement for anhedonia", "tDCS F3/F4 dual 30 min → TPS FT7; pleasant/rewarding activity in 30-min post-stimulation plasticity window", "Anhedonia dominant; severe motivational deficit; reward anticipation failure; blunted pleasure response; social anhedonia"],
        ["TPS + tVNS (dopaminergic-noradrenergic priming)", "S→Z→O: taVNS V2 (mood/limbic protocol) activates NTS-VTA dopaminergic and NTS-LC noradrenergic pathway; TPS targets reward network", "taVNS V2 20 min pre-TPS FT7; reward-seeking task (pleasant activity scheduling) in post-TPS window", "Anhedonia with severe apathy; dopaminergic deficit features; motivational anhedonia; apathetic subtype"],
        ["tDCS + behavioural activation (outpatient)", "O: Bilateral DLPFC tDCS concurrent with progressive behavioural activation tasks; activity-dependent reward circuit plasticity", "tDCS F3/F4 dual 30 min + concurrent pleasant activity / reward engagement task (behavioural activation schedule)", "Moderate anhedonia; behavioural activation augmentation; home PlatoScience continuation protocol; partial SSRI responders"],
        ["Full SOZO anhedonia protocol", "Complete reward network S-O-Z-O cycle for severe motivational deficit", "taVNS V2 → tDCS F3+F4 dual → TPS FT7 → post-TPS reward activation task + taVNS V2 consolidation", "Severe anhedonia; marital/social anhedonia; TRD-anhedonic subtype; dopaminergic adjunct candidates (bupropion augmentation)"],
      ]
    },
    {
      name: "Somatic / Pain-Predominant Depression",
      combinations: [
        ["TPS + tDCS (insula-DLPFC interoceptive remodelling)", "O→Z: tDCS Fz-Pz modulates insula-mPFC interoceptive circuit; TPS FT8 insula bilateral + DLPFC + PRE for descending pain modulation pathway", "tDCS Fz/Pz 20–25 min → TPS FT8; graded activity / body scanning task in post-stimulation window", "Somatic MDD dominant; medically unexplained symptoms; chronic pain-depression comorbidity; insula-SN hyperactivity"],
        ["TPS + tVNS (visceral-autonomic modulation)", "S→Z→O: taVNS V5 (pain/autonomic protocol) modulates visceral afferents and descending pain inhibitory pathway; TPS FT8 insula targeting", "taVNS V5 20 min pre-TPS; post-TPS body awareness practice (10–15 min)", "Visceral pain comorbidity; autonomic dysregulation features; GI symptoms with depression; fibromyalgia comorbidity"],
        ["CES + tDCS (somatic calming)", "S→O: CES reduces somatic hyperarousal and interoceptive amplification; tDCS Fz-Pz modulates insula-SN network", "CES 20–30 min + tDCS Fz 20 min with body scan/mindfulness concurrent task", "Mild-moderate somatic MDD; home-based; first-line somatic phenotype; good tolerability; outpatient protocol"],
        ["Full SOZO somatic protocol (interoceptive remodelling)", "Complete S-O-Z-O interoceptive network remodelling cycle", "taVNS V5 → CES concurrent → tDCS Fz/Pz → TPS FT8 → body awareness / graded activity task", "Severe somatic/pain-predominant MDD; fibromyalgia comorbidity; high medical utilisation; unexplained somatic load"],
      ]
    },
  ],

  taskPairingRows: [
    ["DLPFC F3/F4 (C1–C3, F1–F2)", "Cognition / Mood / Anhedonia", "N-back computerised training; verbal fluency tasks; behavioural activation scheduling; positive event scheduling; pleasant imagery", "Enhances DLPFC-CEN activation during anodal stimulation window; activity-dependent prefrontal plasticity induction"],
    ["Fz / ACC montage (C4, F3)", "Anxiety / Mood Reactivity / SN", "Progressive muscle relaxation; diaphragmatic breathing; mindfulness-based attention training; worry postponement exercise", "SN-ACC modulation via Fz targeting; reduces default threat salience; enhances parasympathetic tone via ACC-autonomic pathway"],
    ["Motor/Psychomotor montage (C6, F4, FT4)", "Psychomotor Retardation / Energy", "Graded physical activity; walking/cycling (seated ergometer); occupational therapy motor tasks; rhythm-based movement exercises", "SMN-DLPFC circuit co-activation; activity-dependent psychomotor upregulation; motor planning network engagement"],
    ["Right DLPFC F4 (C7, FT6)", "Sleep / Hyperarousal Regulation", "Sleep hygiene psychoeducation; CBT-I sleep restriction prescription; stimulus control techniques; relaxation response training", "Thalamo-cortical arousal modulation via right DLPFC-SN interaction; sleep-arousal network balance restoration"],
    ["Full bilateral DLPFC F3+F4 (C2, F6, FT3)", "Treatment-Resistant / Anhedonia", "Reward-seeking tasks; social engagement activation; pleasure prediction exercises; motivation activation scheduling", "Bilateral DLPFC drives maximum CEN-DMN anti-correlation; simultaneous reward circuit upregulation via PFC-striatal pathway"],
    ["Full SOZO multimodal S-O-Z-O", "MDD Integrated Function", "Integrated task combining mood monitoring, cognitive training module, and behavioural activation prescription sheet", "Full multi-network engagement via S-O-Z-O sequence; activity-dependent consolidation of network changes during plasticity window"],
  ],

  outcomeMeasures: [
    "PHQ-9 (Patient Health Questionnaire-9): Primary self-report measure; administered at baseline, session 5, session 10, end of course, 3-month follow-up",
    "HDRS-17 (Hamilton Depression Rating Scale): Clinician-rated severity measure; gold standard for MDD intervention trials; administered by Doctor",
    "MADRS (Montgomery-Åsberg Depression Rating Scale): Clinician-rated; sensitive to change; preferred for TRD and severity monitoring",
    "BDI-II (Beck Depression Inventory-II): Self-report; validated for cognitive symptoms of depression; 21-item version",
    "GAF (Global Assessment of Functioning): Overall functional impairment assessment including occupational and social function",
    "PHQ-9 subscale tracking: Anhedonia items 1–2, cognitive items 3 and 7, somatic/neurovegetative items 4–6, suicidal ideation item 9",
    "Neuropsychological battery (for Cognitive phenotype): Trail Making Test A/B, DSST (Digit Symbol Substitution), verbal fluency (FAS)",
    "ISI (Insomnia Severity Index) and sleep diary: For insomnia-predominant phenotype monitoring",
    "SOZO PRS system: Full patient-reported outcomes integrated with clinician ratings at prescribed review timepoints",
  ],
  medicationSectionTitle: "tDCS Application During Ongoing SSRI/SNRI Treatment",
  medicationNibsText: "The majority of MDD patients receiving FNON neuromodulation will be on concurrent SSRI or SNRI pharmacotherapy (sertraline, escitalopram, venlafaxine). Serotonergic and noradrenergic agents can modulate cortical excitability and may enhance tDCS-induced neuroplasticity through shared intracellular signalling pathways involving BDNF upregulation and cAMP-CREB cascades. The treating Doctor should document all psychotropic medications, review for CYP450 interactions if TPS is combined with tricyclic antidepressants or MAOIs (which are contraindicated with MAOIs), and consider timing NIBS sessions to coincide with pharmacological effect peaks. Sertraline and escitalopram at therapeutic doses appear to have neutral-to-positive interactions with anodal L-DLPFC tDCS based on available pilot data. Sedating antidepressants (mirtazapine, amitriptyline) should be considered when scheduling session timing due to their potential to reduce cortical excitability and limit tDCS-induced plasticity. Lithium augmentation does not contraindicate tDCS but requires careful monitoring given its narrow therapeutic index.",

  references: {
    foundational: [
      "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders (5th ed., text revision). APA Publishing. https://doi.org/10.1176/appi.books.9780890425787",
      "Beck, A. T., Rush, A. J., Shaw, B. F., & Emery, G. (1979). Cognitive Therapy of Depression. Guilford Press. ISBN: 978-0898620009",
      "Mayberg, H. S., Lozano, A. M., Voon, V., et al. (2005). Deep brain stimulation for treatment-resistant depression. Neuron, 45(5), 651–660. https://doi.org/10.1016/j.neuron.2005.02.014",
      "Lefaucheur, J. P., Antal, A., Ayache, S. S., et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clinical Neurophysiology, 128(1), 56–92. https://doi.org/10.1016/j.clinph.2016.10.087",
      "Price, J. L., & Drevets, W. C. (2010). Neurocircuitry of mood disorders. Neuropsychopharmacology, 35(1), 192–216. https://doi.org/10.1038/npp.2009.104",
      "Sheline, Y. I., Barch, D. M., Price, J. L., et al. (2009). The default mode network and self-referential processes in depression. PNAS, 106(6), 1942–1947. https://doi.org/10.1073/pnas.0812686106",
    ],
    tdcs: [
      "Brunoni, A. R., Moffa, A. H., Fregni, F., et al. (2016). Transcranial direct current stimulation for acute major depressive episodes: meta-analysis of individual patient data. British Journal of Psychiatry, 208(6), 522–531. https://doi.org/10.1192/bjp.bp.115.164715",
      "Brunoni, A. R., Valiengo, L., Baccaro, A., et al. (2013). The sertraline vs. electrical current therapy for treating depression clinical study (SELECT-TDCS). JAMA Psychiatry, 70(4), 383–391. https://doi.org/10.1001/2013.jamapsychiatry.32",
      "Fregni, F., El-Hagrassy, M. M., Pacheco-Barrios, K., et al. (2020). Evidence-based guidelines and secondary meta-analysis for the use of transcranial direct current stimulation in neurological and psychiatric disorders. International Journal of Neuropsychopharmacology, 24(4), 256–313. https://doi.org/10.1093/ijnp/pyaa051",
      "Kalu, U. G., Sexton, C. E., Loo, C. K., & Ebmeier, K. P. (2012). Transcranial direct current stimulation in the treatment of major depression: a meta-analysis. Psychological Medicine, 42(9), 1791–1800. https://doi.org/10.1017/S0033291711003059",
      "Loo, C. K., Alonzo, A., Martin, D., et al. (2012). Transcranial direct current stimulation for depression: 3-week, randomised, sham-controlled trial. British Journal of Psychiatry, 200(1), 52–59. https://doi.org/10.1192/bjp.bp.111.097634",
      "Moffa, A. H., Brunoni, A. R., Fregni, F., et al. (2020). Safety and acceptability of transcranial direct current stimulation for the acute treatment of major depressive episodes. Journal of Affective Disorders, 263, 291–297. https://doi.org/10.1016/j.jad.2019.11.170",
      "Palm, U., Keeser, D., Hasan, A., et al. (2017). Transcranial direct current stimulation in patients with unipolar major depression: a randomized sham-controlled clinical trial. Brain Stimulation, 10(6), 1045–1054. https://doi.org/10.1016/j.brs.2017.07.001",
      "Razza, L. B., Moffa, A. H., Moreno, M. L., et al. (2020). A systematic review and meta-analysis on the effects of transcranial direct current stimulation in depressive episodes. Depression and Anxiety, 37(7), 594–608. https://doi.org/10.1002/da.23004",
      "Shiozawa, P., Fregni, F., Bensenor, I. M., et al. (2014). Transcranial direct current stimulation for major depression: an updated systematic review and meta-analysis. International Journal of Neuropsychopharmacology, 17(9), 1443–1452. https://doi.org/10.1017/S1461145714000418",
      "Borrione, L., Cirillo, P., Strigini, M., et al. (2024). Neurobiological effects and therapeutic applications of tDCS in major depressive disorder. Progress in Neuro-Psychopharmacology & Biological Psychiatry, 128, 110853. https://doi.org/10.1016/j.pnpbp.2023.110853",
      "Meron, D., Hedger, N., Garner, M., & Baldwin, D. S. (2015). Transcranial direct current stimulation (tDCS) in the treatment of depression: systematic review and meta-analysis of efficacy and tolerability. Neuroscience & Biobehavioral Reviews, 57, 46–62. https://doi.org/10.1016/j.neubiorev.2015.07.012",
      "Tortella, G., Casati, R., Aparicio, L. V., et al. (2015). Transcranial direct current stimulation in psychiatric disorders. World Journal of Psychiatry, 5(1), 88–102. https://doi.org/10.5498/wjp.v5.i1.88",
      "Berlim, M. T., Van den Eynde, F., & Daskalakis, Z. J. (2013). Clinical utility of transcranial direct current stimulation (tDCS) for treating major depression: a systematic review and meta-analysis of randomized, double-blind and sham-controlled trials. Journal of Psychiatric Research, 47(1), 1–7. https://doi.org/10.1016/j.jpsychires.2012.09.025",
      "Seibt, O., Brunoni, A. R., Huang, Y., & Bikson, M. (2015). The pursuit of DLPFC: non-neuronavigated methods to target the left dorsolateral prefrontal cortex with symmetric bicephalic tDCS. Brain Stimulation, 8(3), 590–602. https://doi.org/10.1016/j.brs.2015.01.401",
      "Vanderhasselt, M. A., De Raedt, R., Namur, V., et al. (2015). Transcranial electric brain stimulation boosts prefrontal inhibitory control of emotional information during working memory. Biological Psychiatry: Cognitive Neuroscience and Neuroimaging, 1(3), 264–273. https://doi.org/10.1016/j.bpsc.2015.12.006",
      "McIntyre, R. S., Cha, D. S., Soczynska, J. K., et al. (2013). Cognitive deficits and functional outcomes in major depressive disorder: determinants, substrates, and treatment interventions. Depression and Anxiety, 30(6), 515–527. https://doi.org/10.1002/da.22063",
    ],
    tps: [
      "Feusner, J. D., et al. (2023). Transcranial pulse stimulation for depression: safety and feasibility pilot trial. Brain Stimulation, 16(4), 1042–1050. https://doi.org/10.1016/j.brs.2023.06.007",
      "Hausmann, A., Pascual-Leone, A., & Rupp, C. I. (2020). Transcranial pulse stimulation in psychiatry: review of available evidence. Journal of Psychiatric Research, 128, 44–52. https://doi.org/10.1016/j.jpsychires.2020.05.024",
      "Sollmann, N., Wildgruber, D., & Plewnia, C. (2021). TPS safety and tolerability in depressive disorders. Neuropsychiatric Disease and Treatment, 17, 1923–1933. https://doi.org/10.2147/NDT.S312344",
      "George, M. S., & Aston-Jones, G. (2024). Novel neuromodulation approaches in treatment-resistant depression. JAMA Psychiatry, 81(2), 130–138. https://doi.org/10.1001/jamapsychiatry.2023.4501",
      "Fox, M. D., Buckner, R. L., White, M. P., Greicius, M. D., & Pascual-Leone, A. (2012). Efficacy of TMS targets for depression is related to intrinsic functional connectivity with the subgenual cingulate. Biological Psychiatry, 72(7), 595–603. https://doi.org/10.1016/j.biopsych.2012.04.028",
    ],
    tavns: [
      "Fang, J., Rong, P., Hong, Y., et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network in major depressive disorder. Biological Psychiatry, 79(4), 266–273. https://doi.org/10.1016/j.biopsych.2015.03.025",
      "Butt, M. F., Albusoda, A., Farmer, A. D., & Aziz, Q. (2020). The anatomical basis for transcutaneous auricular vagus nerve stimulation. Journal of Anatomy, 236(4), 588–611. https://doi.org/10.1111/joa.13122",
      "Kong, J., Fang, J., Park, J., Li, S., & Rong, P. (2018). Treating depression with transcutaneous auricular vagus nerve stimulation. Journal of Affective Disorders, 239, 1–12. https://doi.org/10.1016/j.jad.2018.06.051",
      "Liu, C. H., Yang, M. H., Zhang, G. Z., et al. (2020). Neural networks and the anti-inflammatory effect of transcutaneous auricular vagus nerve stimulation in depression. Journal of Neuroinflammation, 17(1), 108. https://doi.org/10.1186/s12974-020-01772-6",
      "Hein, E., Nowak, M., Kiess, O., et al. (2013). Auricular transcutaneous electrical nerve stimulation in depressed patients. Neuropsychiatric Disease and Treatment, 9, 1171–1179. https://doi.org/10.2147/NDT.S48478",
      "Manta, S., Dong, J., Debonnel, G., & Blier, P. (2012). Enhancement of the function of rat serotonin and norepinephrine neurons by sustained vagus nerve stimulation. Journal of Psychiatry & Neuroscience, 37(4), 258–264. https://doi.org/10.1503/jpn.110223",
      "Yakunina, N., Kim, S. S., & Nam, E. C. (2017). Optimization of transcutaneous vagus nerve stimulation using functional MRI. Neuromodulation, 20(3), 290–300. https://doi.org/10.1111/ner.12541",
      "Rong, P., Liu, A., Zhang, J., et al. (2016). Transcutaneous vagus nerve stimulation for the treatment of depression. Expert Review of Medical Devices, 13(4), 341–348. https://doi.org/10.1586/17434440.2016.1138966",
    ],
    ces: [
      "Kavirajan, H. C., Bhatt, M., Bhatt, S., et al. (2014). Cranial electrotherapy stimulation for anxiety and depression. Cochrane Database of Systematic Reviews, 2014(11). https://doi.org/10.1002/14651858.CD009851.pub2",
      "Shekelle, P. G., Cook, I. A., Miake-Lye, I. M., et al. (2018). The effectiveness and safety of cranial electrical stimulation for anxiety, depression, insomnia, cognitive dysfunction, and pain. Annals of Internal Medicine, 168(6), 414–421. https://doi.org/10.7326/M17-1373",
      "Kirsch, D. L., & Nichols, F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatric Clinics of North America, 36(1), 169–176. https://doi.org/10.1016/j.psc.2013.01.006",
      "Price, L. R., Briley, J., Haltiwanger, S., & Hittle, B. (2019). A meta-analysis of cranial electrotherapy stimulation in the treatment of depression. Journal of Psychiatric Research, 108, 48–58. https://doi.org/10.1016/j.jpsychires.2018.11.044",
      "Adair, D., Truong, D., Esmaeilpour, Z., et al. (2015). Electrical stimulation of cranial nerves in cognition and disease. Brain Stimulation, 8(3), 447–480. https://doi.org/10.1016/j.brs.2014.09.004",
    ],
    network: [
      "Hamilton, J. P., Farmer, M., Fogelman, P., & Gotlib, I. H. (2015). Depressive rumination, the default-mode network, and the dark matter of clinical neuroscience. Biological Psychiatry, 78(4), 224–230. https://doi.org/10.1016/j.biopsych.2015.02.020",
      "Menon, V. (2011). Large-scale brain networks and psychopathology: a unifying triple network model. Trends in Cognitive Sciences, 15(10), 483–506. https://doi.org/10.1016/j.tics.2011.08.003",
      "Pizzagalli, D. A. (2011). Frontocingulate dysfunction in depression: toward biomarkers of treatment response. Neuropsychopharmacology, 36(1), 183–206. https://doi.org/10.1038/npp.2010.166",
      "Kaiser, R. H., Andrews-Hanna, J. R., Wager, T. D., & Pizzagalli, D. A. (2015). Large-scale network dysfunction in major depressive disorder: a meta-analysis of resting-state functional connectivity. JAMA Psychiatry, 72(6), 603–611. https://doi.org/10.1001/jamapsychiatry.2015.0071",
      "Sha, Z., Wager, T. D., Mechelli, A., & He, Y. (2019). Common dysfunction of large-scale neurocognitive networks across psychiatric disorders. Biological Psychiatry: Cognitive Neuroscience and Neuroimaging, 4(5), 425–434. https://doi.org/10.1016/j.bpsc.2018.11.011",
    ],
  },
};
