'use strict';
module.exports = {
  conditionFull: "Obsessive-Compulsive Disorder (OCD)",
  conditionShort: "OCD",
  conditionSlug: "ocd",
  documentNumber: "SOZO-OCD-PROT-001",
  offLabelCoverText: "tDCS and TPS use in OCD is INVESTIGATIONAL / OFF-LABEL. Level B evidence supports cathodal tDCS targeting the supplementary motor area (SMA) and orbitofrontal cortex for OCD symptom reduction.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level B evidence for OCD (cathodal SMA/OFC approach)', 'Standard informed consent + off-label note'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; exploratory evidence for OCD and compulsive behaviour', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia; off-label for OCD', 'Standard informed consent + off-label note'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of OCD (DSM-5 / ICD-11) by a qualified psychiatrist or clinical psychologist",
    "Y-BOCS score ≥16 (moderate-severe OCD) at baseline assessment",
    "Age 18–65 years (exceptions at Doctor discretion with documented rationale)",
    "Engaged with or referred for ERP (Exposure and Response Prevention) therapy — FNON is adjunctive to ERP",
    "Stable pharmacological treatment for ≥8 weeks prior to enrolment (OCD requires longer trials than other conditions)",
    "Capacity to provide informed consent",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS) — DBS is used in severe refractory OCD; if implanted, contraindication",
    "Active psychotic episode requiring urgent management",
    "Active suicidal ideation with intent or plan",
    "Hoarding disorder as primary presentation without OCD core symptoms (different neurobiological profile)",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Comorbid depression (common in OCD) — adapt montage to address both; SMA cathodal for OCD + DLPFC anodal for MDD",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment",
    "Epilepsy or seizure history — formal risk assessment; note that cathodal stimulation reduces excitability (lower seizure risk than anodal)",
    "Tic disorder or Tourette syndrome comorbidity — adapted SMA protocol may benefit tics as well",
    "Body dysmorphic disorder (BDD) comorbidity — similar neurobiological profile; adapted protocol",
    "OCD spectrum conditions (trichotillomania, skin-picking) — SMA-related protocol may apply",
    "Severe personality disorder — psychological stability assessment required",
    "Pregnancy — taVNS/CES preferred; tDCS/TPS at Doctor discretion",
    "Eating disorder comorbidity — careful assessment; OFC-compulsive eating overlap",
  ],

  overviewParagraph: "Obsessive-Compulsive Disorder (OCD) is a highly disabling condition affecting approximately 2–3% of the population worldwide. It is characterised by intrusive, unwanted obsessional thoughts and/or repetitive compulsive behaviours performed to reduce anxiety. OCD produces significant functional impairment — disrupting occupational function, interpersonal relationships, and quality of life. It is associated with high rates of comorbid depression, anxiety, and tic disorders. Despite the effectiveness of evidence-based treatments — Exposure and Response Prevention (ERP) and SSRIs at high doses — approximately 40–60% of patients do not achieve adequate remission, and many relapse. Severe treatment-refractory OCD has DBS as a last-resort intervention targeting the ventral striatum. Non-invasive brain stimulation, particularly inhibitory tDCS protocols targeting the SMA and OFC, has emerged as a meaningful adjunct to ERP with Level B evidence from multiple RCTs.",
  fnonNetworkParagraph: "OCD is fundamentally a disorder of the cortico-striato-thalamo-cortical (CSTC) loop — specifically, hyperactivity in the orbitofrontal cortex (OFC)-caudate-thalamus-OFC circuit that drives the intrusive obsessional thinking and compulsive urge-response cycle. The FNON framework targets this hyperactivity via inhibitory (cathodal) tDCS/TPS to the SMA and OFC, combined with anodal DLPFC stimulation to enhance prefrontal cognitive control over compulsive impulses. taVNS and CES modulate the anxiety-driven perpetuation of OCD by addressing the autonomic substrate of obsessional distress.",
  networkDisorderParagraphs: [
    "The hallmark neuroimaging finding in OCD is hyperactivity within the OFC-caudate-thalamus circuit — the direct pathway of the cortico-striato-thalamo-cortical (CSTC) loop — which drives compulsive behaviour by generating excessive 'error' signals and feelings of incompleteness that are only temporarily relieved by compulsions. PET and fMRI studies consistently show OFC and caudate hyperactivation at rest and during symptom provocation, with normalisation after successful ERP therapy or SRI pharmacotherapy.",
    "The supplementary motor area (SMA) is implicated in OCD via its role in action suppression and the urge-to-act that precedes compulsive motor behaviours. The pre-SMA shows hyperactivation during symptom provocation in OCD patients, and inhibitory rTMS/tDCS to the SMA reduces OCD symptom severity by disrupting the compulsion-urge motor circuit. The DLPFC, conversely, is hypoactivated in OCD relative to controls, failing to provide adequate top-down cognitive control over OFC-generated obsessional content.",
    "The SN-OFC-caudate circuit in OCD is characterised by excessive 'error monitoring' — the ACC and OFC generate sustained threat and error signals that drive compulsive responding. This hyperactive error monitoring circuit is responsive to inhibitory neuromodulation (cathodal tDCS, low-frequency rTMS) targeting the SMA and OFC, which reduces the compulsive urge to perform rituals. Simultaneously, upregulating DLPFC activity enhances cognitive inhibitory control over compulsive behaviours.",
  ],

  pathophysiologyText: "OCD pathophysiology involves: (1) CSTC loop hyperactivity — direct OFC-caudate-thalamus-OFC pathway drives compulsive behaviours via excessive 'not just right' experiences and error monitoring; (2) serotonergic dysregulation — primary evidence for SRI mechanism; 5-HT2A and 5-HT1D receptors in OFC/caudate; high-dose SSRI required for OCD (unlike depression); (3) dopaminergic dysfunction — D2 receptor involvement in caudate; explains augmentation with antipsychotics (aripiprazole, risperidone); (4) glutamatergic excess — elevated striatal glutamate in OCD on MRS; CSTC loop overactivation driven by glutamate; explains ketamine/NAC evidence; (5) SMA hyperactivation — pre-SMA/SMA generates excessive premotor urge-to-act signals preceding compulsions; (6) prefrontal-striatal inhibitory control failure — DLPFC hypoactivation reduces top-down inhibitory regulation of OFC and striatum; (7) anxiety-compulsion maintenance cycle — autonomic anxiety drives obsessional distress maintained by avoidance/compulsion.",
  cardinalSymptoms: [
    ["Obsessions", "Recurrent, persistent, unwanted intrusive thoughts, images, or urges; experienced as alien/ego-dystonic; generate significant distress; attempts to suppress or neutralise", "Core criterion (100% by DSM-5 definition)", "American Psychiatric Association, 2022"],
    ["Compulsions", "Repetitive behaviours (checking, washing, ordering) or mental acts (counting, praying) performed to reduce distress or prevent feared outcome; excessive; not realistically connected to feared event", "Core criterion (100%)", "American Psychiatric Association, 2022"],
    ["Anxiety / Distress", "High anxiety around obsessional triggers; intolerable distress driving compulsive response; anxiety temporarily relieved by compulsions — perpetuating cycle", "~95% of OCD", "Salkovskis, 1985"],
    ["Thought-Action Fusion (TAF)", "Belief that having a thought is equivalent to acting on it (likelihood TAF) or morally equivalent (moral TAF); cognitive distortion driving severity", "~70%", "Shafran & Rachman, 2004"],
    ["Incompleteness / 'Not Just Right' Experiences", "Pervasive sense of things being wrong, incomplete, or imperfect; requires compulsive symmetry, ordering, or repeating until 'just right'", "~70%", "Ferrão et al., 2006"],
    ["Magical Thinking / Superstition", "Rituals to prevent harm; belief that mental acts or rituals can prevent feared outcomes; harm-related OCD subtype", "~60%", "Einstein & Menzies, 2004"],
    ["Avoidance", "Extensive avoidance of OCD triggers; restricts daily activities; maintains OCD by preventing exposure and habituation", "~80%", "Abramowitz et al., 2003"],
    ["Mental Rituals / Covert Compulsions", "Mental reviewing, praying, counting, reassurance-seeking; hidden compulsions that maintain OCD; difficult to target in standard ERP", "~60%", "Williams et al., 2012"],
    ["Reassurance-Seeking", "Repeated seeking of reassurance from others or self; maintains OCD through temporary anxiety reduction and avoidance of uncertainty", "~70%", "Parrish & Radomsky, 2010"],
    ["Time-Consuming Rituals", "Significant daily time (>1 hour/day DSM threshold) consumed by obsessions and compulsions; functional impairment", "~85% moderate-severe OCD", "American Psychiatric Association, 2022"],
    ["Family Accommodation", "Family members participating in or enabling compulsive rituals; OCD extends into interpersonal system; maintains disorder", "~75%", "Calvocoressi et al., 1995"],
    ["Shame/Ego-Dystonia", "Significant shame about obsessional content; secretiveness about symptoms; delays help-seeking; self-stigma", "~60%", "Olatunji et al., 2010"],
    ["Comorbid Depression", "Depression secondary to OCD-related functional impairment; social isolation; hopelessness about recovery; requires co-management", "~40–50%", "Torres et al., 2006"],
  ],
  standardGuidelinesText: [
    "Evidence-based first-line treatment for OCD (NICE 2005/2020, APA 2007, IOCDF 2021) is Exposure and Response Prevention (ERP) therapy — a structured cognitive-behavioural approach involving graduated, deliberate exposure to obsessional triggers while withholding compulsive responses. ERP directly targets the OCD maintenance cycle and has the strongest evidence base (Level A), with response rates of 60–70% in motivated patients. CBT with cognitive interventions (ACT, inference-based CBT) may supplement ERP.",
    "First-line pharmacotherapy: SSRIs at OCD-specific doses (typically 2–4× the dose used for depression): sertraline 200mg, fluoxetine 60–80mg, fluvoxamine 300mg, paroxetine 60mg, escitalopram 40mg. Clomipramine (TCA) remains the most effective single agent for OCD but has poorer tolerability. Augmentation strategies for non-responders include antipsychotics (aripiprazole Level A, risperidone Level A) particularly for tic-comorbid OCD, and N-acetylcysteine (NAC — glutamate modulator, Level C). For severe treatment-refractory OCD, DBS targeting ventral striatum/ALIC is used.",
    "SOZO FNON protocols for OCD are designed as adjuncts to ERP therapy, targeting the SMA-OFC hyperactivity and DLPFC hypoactivation that characterise OCD neurobiology. The critical principle is that FNON stimulation — particularly cathodal SMA or cathodal OFC — paired with ERP practice reduces the compulsive urge signal, lowering the subjective distress threshold during exposure and improving ERP response rates. The Doctor coordinates closely with the treating OCD therapist.",
  ],

  fnonFrameworkParagraph: "The FNON framework for OCD inverts the typical anodal-upregulation approach: inhibitory (cathodal) tDCS to the hyperactive SMA and OFC directly reduces the cortico-striato-thalamo-cortical hyperactivation that generates compulsive urge signals. Simultaneously, anodal DLPFC stimulation upregulates prefrontal inhibitory control over compulsive impulses. TPS can target the OFC and striatum at depth for enhanced circuit-level modulation. taVNS and CES address the autonomic anxiety that drives obsessional distress, lowering the urge-to-ritualise threshold and improving ERP engagement.",
  keyBrainRegions: [
    ["Supplementary Motor Area (SMA) / pre-SMA", "Hyperactivation; generates premotor urge-to-act preceding compulsions; action suppression failure; OCD motor ritual substrate; primary inhibitory target", "PRIMARY OCD TARGET: cathodal tDCS SMA (Cz) — Level B evidence for OCD symptom reduction; inhibits hyperactive SMA compulsion-urge circuit; TPS SMA", "Mantovani et al., 2010; Gomes et al., 2012"],
    ["Orbitofrontal Cortex (OFC)", "CSTC loop hyperactivation node; excessive 'error' and 'threat' signalling; drives intrusive obsessional content; normalises with successful ERP/SRI treatment", "Cathodal tDCS OFC (via Fp1/Fp2 or F7/F8); TPS OFC deep targeting — reduces OFC hyperactivation; paired with ERP exposure", "Saxena & Rauch, 2001; Rotge et al., 2008"],
    ["Dorsolateral Prefrontal Cortex (DLPFC)", "Hypoactivation; insufficient top-down inhibitory control over OFC and SMA; impaired cognitive flexibility; anodal upregulation enhances inhibitory control", "Anodal tDCS F3 (left DLPFC) — enhances prefrontal inhibitory control; combined cathodal SMA + anodal DLPFC is the evidence-based OCD tDCS montage", "Abramowitz et al., 2009; Gomes et al., 2012"],
    ["Caudate Nucleus", "CSTC loop hyperactivity node; direct pathway to thalamus; compulsive repetition substrate; normalises with successful treatment; reduced volume with IVERsion", "Indirect modulation via OFC-cathodal tDCS and DLPFC-anodal; TPS deep caudate/striatum for severe OCD", "Saxena & Rauch, 2001; Rotge et al., 2008"],
    ["Anterior Cingulate Cortex (ACC)", "Hyperactive error monitoring; generates excessive 'something is wrong' signals; drives obsessional checking; theta oscillation hypersynchrony in OCD", "tDCS Fz for ACC modulation; taVNS modulates ACC via vagal-cingulate pathway; combined with error monitoring tasks during ERP", "Carter et al., 1998; Bush et al., 2000"],
    ["Thalamus", "CSTC loop relay; impaired gating allows OFC signals to perpetuate; thalamic hyperactivation in OCD; thalamo-cortical dysrhythmia", "TPS thalamic deep targeting for severe/refractory OCD; indirect modulation via OFC-striatal-thalamic pathway reduction", "Saxena & Rauch, 2001"],
    ["Anterior Insula", "Disgust and contamination processing; hyperactivation in contamination/washing OCD subtype; interoceptive amplification of 'not just right'", "TPS anterior insula for contamination-dominant OCD; taVNS modulates insula via NTS pathway; disgust-based ERP concurrent", "Phillips et al., 2000"],
    ["Prefrontal Cortex Medial (vmPFC)", "Perseverative threat evaluation; safety signal deficit; avoidance-maintenance; OCD safety learning impairment; contributes to obsessional doubt", "TPS vmPFC; anodal tDCS vmPFC (via Fz) for safety signal upregulation; paired with inhibitory ERP learning", "Milad & Rauch, 2012"],
    ["Hippocampus", "Extinction and safety memory; OCD extinction learning impairment similar to anxiety disorders; contextual safety discrimination failure", "TPS hippocampal for contextual safety learning; taVNS BDNF for extinction memory consolidation; paired with ERP graduated exposure", "Milad & Rauch, 2012"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Primary vagal relay; mediates taVNS anxiety reduction; entry point for autonomic modulation of OCD distress", "taVNS NTS activation reduces autonomic anxiety driving OCD maintenance cycle; modulates amygdala via NTS-amygdala pathway", "Fang et al., 2016"],
    ["Ventral Striatum / Nucleus Accumbens", "Reward-punishment prediction error; compulsion 'relief' encoded as reward signal in ventral striatum; DBS target for refractory OCD", "Indirect modulation via OFC-caudate cathodal pathway; TPS deep ventral striatum for refractory OCD", "Rotge et al., 2008"],
    ["Internal Capsule / ALIC", "DBS target (anterior limb — ALIC) for refractory OCD; connects OFC-striatum-thalamus pathway; deep white matter", "TPS trajectory may engage ALIC corridor; theoretical deep WM modulation — specialist use only", "Greenberg et al., 2010"],
    ["Amygdala", "Fear and disgust conditioning; OCD obsessional fear memories; anxiety-OCD perpetuation; hyperreactivity to OCD triggers", "Indirect modulation via anodal DLPFC and taVNS NTS-amygdala; TPS temporal for contamination-fear OCD", "Rotge et al., 2008"],
    ["Locus Coeruleus (LC)", "NE arousal; hyperactivation in OCD anxiety perpetuation; taVNS normalises LC-NE tone contributing to anxiety reduction", "taVNS→NTS→LC pathway — reduces NE-mediated anxiety perpetuating OCD compulsive cycle", "Millan, 2003"],
    ["Raphe Nuclei", "Serotonergic regulation — SRI mechanism; insufficient 5-HT in OCD perpetuates checking and incompleteness experiences", "taVNS modulates raphe 5-HT via brainstem connections; CES may enhance serotonergic tone — synergistic with SSRI", "Zohar et al., 2009"],
    ["Subthalamic Nucleus (STN)", "Motor and cognitive-limbic circuits; DBS target for OCD; plays role in response inhibition and stopping compulsive behaviours", "Indirect modulation via fronto-striatal pathway; relevant for motor-compulsion phenotypes", "Mallet et al., 2008"],
  ],
  keyFunctionalNetworks: [
    ["Cortico-Striato-Thalamo-Cortical (CSTC) Direct Pathway", "OFC, caudate (dorsomedial), thalamus (mediodorsal), OFC (loop)", "Hyperactivity driving compulsive loop; excessive OFC error signalling perpetuating compulsions; PRIMARY OCD pathological circuit", "Cathodal tDCS SMA + OFC INHIBIT; TPS OFC/caudate deep; anodal DLPFC enhance inhibitory control OVER this loop", "Saxena & Rauch, 2001"],
    ["Error Monitoring Network", "ACC, OFC, DLPFC, caudate", "Hyperactive error/threat detection; excessive 'not just right' signals; checking and repeating behaviours; theta hypersynchrony", "tDCS Fz cathodal (ACC suppression) combined with DLPFC anodal; paired with ERP prevention of checking", "Carter et al., 1998"],
    ["Action Suppression Network", "Pre-SMA, SMA, DLPFC, IFG, basal ganglia", "SMA/pre-SMA hyperactivation generating excessive premotor urge-to-act; impaired response inhibition", "PRIMARY: cathodal tDCS SMA (Cz) — reduces SMA urge-to-act signal; combined with DLPFC anodal for inhibitory control", "Mantovani et al., 2010"],
    ["Default Mode Network (DMN)", "mPFC, PCC, hippocampus, angular gyrus", "Hyperconnected with OFC in OCD; rumination about obsessional content; self-referential obsessional thinking", "Cathodal Pz (DMN suppression); combined with cathodal SMA + anodal DLPFC protocol", "Stern et al., 2012"],
    ["Anxiety/Limbic Network", "Amygdala, insula, ACC, OFC, BNST", "Anxiety perpetuating OCD maintenance cycle; obsessional distress drives compulsive response; hyperreactivity to OCD triggers", "taVNS PRIMARY for anxiety reduction — breaks anxiety-compulsion cycle; CES for broad arousal reduction; combined with ERP", "Saxena & Rauch, 2001"],
    ["Salience Network (SN)", "dACC, anterior insula, amygdala", "Hyperactivation detecting OCD-relevant 'threats'; excessive salience assignment to obsessional triggers; contamination/disgust processing", "taVNS SN-modulation; tDCS Fz (cathodal for OCD — reduces dACC error hypersynchrony)", "Seeley et al., 2007"],
    ["Reward/Habit Network", "Striatum, OFC, vmPFC, VTA", "Compulsion-relief encoded as reward signal perpetuating habit; habit-based compulsion automatisation; anxiety relief = reward", "Cathodal OFC + TPS deep striatum; ERP withholding provides extinction of compulsion-relief association", "Gillan et al., 2011"],
  ],
  networkAbnormalities: "OCD is characterised by CSTC direct pathway hyperactivity (OFC-caudate-thalamus loop), SMA hyperactivation (urge-to-act), ACC error monitoring hypersynchrony, DLPFC hypoactivation (insufficient inhibitory control), and anxiety-OCD maintenance cycle. Cathodal SMA/OFC tDCS is the evidence-based approach for reducing hyperactivity.",
  conceptualFramework: "SOZO FNON OCD protocol: (1) Inhibit SMA/pre-SMA compulsion urge via cathodal tDCS (primary OCD approach); (2) Inhibit OFC/ACC error monitoring via cathodal frontal stimulation; (3) Upregulate DLPFC inhibitory control via anodal tDCS; (4) Reduce anxiety-OCD cycle via taVNS and CES; (5) Pair with ERP therapy — stimulation during ERP exposure reduces urge signal and improves response prevention.",

  clinicalPhenotypes: [
    ["Contamination/Washing OCD", "Contamination obsessions, washing/cleaning compulsions; disgust-dominant; anterior insula hyperactivation; SMA cathodal + insula TPS; disgusted ERP concurrent", "Rasmussen & Eisen, 1992"],
    ["Checking OCD", "Harm-prevention obsessions; checking compulsions; OFC-CSTC loop hyperactivation; SMA + OFC cathodal; checking ERP concurrent", "Abramowitz et al., 2003"],
    ["Symmetry/Ordering OCD", "Symmetry obsessions; ordering/arranging compulsions; 'not just right' experiences; SMA hyperactivation dominant; SMA cathodal primary", "Miguel et al., 2000"],
    ["Intrusive Thoughts (Pure-O)", "Intrusive harm/sexual/religious obsessions; primarily mental rituals; cognitive OCD; prefrontal-SMA combined; cognitive ERP/ACT concurrent", "Williams et al., 2012"],
    ["Hoarding OCD", "Persistent difficulty discarding; accumulation; emotional attachment to objects; distinct CSTC variant; vmPFC-ACC; adapted ERP; adapted tDCS bilateral frontal", "Frost & Hartl, 1996"],
    ["Harm OCD with Moral Injury", "Fear of harming others; hypervigilant; moral-OCD; vmPFC moral circuit + DLPFC; taVNS primary for moral anxiety; ACT-based ERP", "Rachman, 2003"],
    ["OCD + Depression Comorbidity", "OCD with significant depressive comorbidity; cathodal SMA for OCD + anodal DLPFC for depression; SSRI at OCD dose; combined ERP+BA", "Torres et al., 2006"],
    ["Treatment-Resistant OCD", "Non-responder to ≥2 SRI trials + adequate ERP; maximum SMA+OFC cathodal + DLPFC anodal; intensive taVNS; ERP intensification; DBS referral consideration", "Denys et al., 2010"],
    ["OCD + Tic Disorder (Tourette)", "OCD + motor/vocal tics; SMA hyperactivation shared; cathodal SMA addresses both OCD and tics; haloperidol or aripiprazole coordination", "Cath et al., 2011"],
  ],
  symptomNetworkMapping: [
    ["Obsessions", "CSTC loop hyperactivity", "OFC-ACC error monitoring excess", "Cathodal tDCS SMA (Cz) PRIMARY", "ERP — exposure to obsessional triggers concurrent"],
    ["Compulsions / Urge-to-Ritualise", "SMA/pre-SMA hyperactivation", "Compulsive motor urge circuit", "Cathodal tDCS SMA (Cz) + DLPFC anodal (F3)", "ERP — response prevention concurrent (withhold ritual)"],
    ["Anxiety / Distress", "SN/amygdala hyperreactivity", "Autonomic anxiety driving OCD cycle", "taVNS PRIMARY + CES (break anxiety-compulsion cycle)", "Relaxation during ERP; anxiety monitoring"],
    ["Checking Compulsions", "OFC-CSTC error monitoring loop", "Checking repetition as error resolution", "Cathodal OFC (F7/F8) + SMA cathodal (Cz)", "ERP checking prevention + timer-based response delay"],
    ["Contamination/Disgust", "Insula-OFC-SN disgust circuit", "Anterior insula hyperactivation", "TPS anterior insula + cathodal SMA", "ERP contamination exposure without washing concurrent"],
    ["Intrusive Thoughts", "DMN-CSTC hyperconnectivity", "OFC self-referential obsessional content", "Cathodal Pz (DMN) + cathodal SMA + anodal F3", "Defusion techniques + ERP mental ritual prevention"],
    ["Symmetry/Ordering", "SMA hyperactivation — not-just-right", "Pre-SMA incompleteness signal", "Cathodal SMA (Cz) PRIMARY", "Resist ordering rituals; tolerance-of-disorder ERP"],
    ["Avoidance", "CEN hypoactivation + OFC fear avoidance", "DLPFC insufficient inhibitory control", "Anodal DLPFC (F3) + cathodal SMA", "Graduated ERP approach to avoided situations"],
    ["Depression Comorbidity", "DLPFC hypoactivation (MDD)", "Frontal-limbic disruption", "Anodal F3 + taVNS + CES for mood", "Behavioural activation integrated with ERP"],
    ["OCD Tics", "SMA hyperactivation (shared mechanism)", "Pre-SMA tic-urge circuit", "Cathodal SMA (Cz) — addresses both OCD and tic urges", "Habit reversal training + OCD ERP concurrent"],
  ],
  montageSelectionRows: [
    ["OCD primary — cathodal SMA (Level B)", "Cathodal Cz (SMA) + anodal F3 (DLPFC) — 2mA 20min (OCD standard montage)"],
    ["OCD checking variant (OFC cathodal)", "Cathodal F7/F8 (OFC) + anodal F3 (DLPFC) — 1.5mA 20min"],
    ["OCD + SMA (combined SMA + OFC)", "Cathodal Cz (SMA) + cathodal F7 (OFC) + anodal F3 — dual cathodal OCD protocol"],
    ["OCD contamination (insula + SMA)", "Cathodal Cz + TPS anterior insula + taVNS"],
    ["Intrusive thoughts (DMN suppression)", "Cathodal Cz + cathodal Pz + anodal F3 — triple montage"],
    ["OCD + depression comorbidity", "Cathodal Cz (SMA) + anodal F3 (DLPFC) — addresses both OCD and depression"],
    ["taVNS anxiety reduction (primary)", "taVNS bilateral cymba 0.5mA 30min (anxiety-compulsion cycle breaker)"],
    ["CES for anxiety and sleep", "Alpha-Stim AID 0.5mA 60min — anxiety and sleep in OCD"],
    ["TPS SMA deep inhibitory", "NEUROLITH® SMA (Cz region) 0.2mJ/mm² 3000 pulses"],
    ["TPS OFC deep inhibitory", "NEUROLITH® OFC/frontal polar 0.2mJ/mm² 3000 pulses"],
    ["Treatment-resistant OCD (maximal)", "HDCkit cathodal Cz+F7 + anodal F3 + TPS OFC+SMA + taVNS 40min"],
    ["OCD + tics (SMA primary)", "Cathodal Cz (SMA) + anodal F3 — SMA primary for combined OCD-tic"],
    ["Maintenance phase", "Cathodal SMA tDCS 2×/week; taVNS 3×/week; CES daily home"],
  ],
  polarityPrincipleText: "OCD polarity is INVERSE to most psychiatric conditions: cathodal (inhibitory) stimulation over the hyperactive SMA and OFC is the primary approach, not anodal upregulation. This reflects the OCD neurobiology of circuit HYPERACTIVITY rather than hypoactivation. The combined cathodal SMA + anodal DLPFC montage simultaneously inhibits the compulsion urge circuit and upregulates inhibitory control — the Level B evidence OCD tDCS approach.",
  polarityTable: [
    ["Cathodal Cz (SMA)", "PRIMARY OCD target — inhibits SMA hyperactivation driving compulsion urge signals; Level B evidence for OCD symptom reduction"],
    ["Anodal F3 (left DLPFC)", "Upregulates prefrontal inhibitory control over compulsive impulses; combined with cathodal SMA for standard OCD montage"],
    ["Cathodal F7/F8 (OFC)", "Inhibits OFC hyperactivation driving error monitoring and obsessional content; particularly effective for checking and intrusive thought OCD"],
    ["Cathodal Pz", "DMN suppression — reduces rumination on obsessional content; added for intrusive thought/pure-O phenotype"],
    ["taVNS bilateral cymba", "Anxiety reduction — breaks anxiety-compulsion maintenance cycle via NTS-amygdala and autonomic modulation"],
  ],

  classicTdcsProtocols: [
    ["C1", "OCD primary / SMA", "Cz cathodal (SMA)", "F3 anodal (DLPFC)", "2mA 20min, 10 sessions", "Level B"],
    ["C2", "OCD checking / OFC", "F7 cathodal (left OFC)", "F3 anodal (DLPFC)", "1.5mA 20min", "Level B"],
    ["C3", "OCD symmetry / SMA primary", "Cz cathodal (SMA)", "F4 anodal (right DLPFC)", "2mA 20min", "Level B"],
    ["C4", "OCD + depression comorbidity", "Cz cathodal (SMA) + F3 anodal", "Fz", "2mA 20min", "Level B/C combined"],
    ["C5", "Intrusive thoughts / pure-O", "Cz + Pz cathodal (dual)", "F3 anodal (DLPFC)", "1.5mA 20min", "Emerging"],
    ["C6", "OCD + tics (SMA combined)", "Cz cathodal (SMA primary)", "F3 anodal", "2mA 20min", "Level B (OCD) + Emerging (tics)"],
    ["C7", "Contamination OCD", "Cz cathodal + TPS insula", "F3 anodal", "2mA 20min + TPS", "Emerging"],
    ["C8", "Mild OCD (reduced)", "Cz cathodal", "F3 anodal", "1.5mA 20min", "Level B (lower intensity)"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Classic OCD (SMA-DLPFC)", "SMA hyperactivation + DLPFC hypoactivation", "Cathodal Cz (SMA) + anodal F3 (DLPFC) — primary OCD FNON montage", "Simultaneously inhibit compulsion urge and upregulate inhibitory control"],
    ["F2", "Checking OCD (OFC focus)", "OFC-CSTC hyperactivation", "Cathodal F7 (OFC) + cathodal Cz (SMA) + anodal F3 (dual cathodal)", "Combined OFC and SMA inhibition for checking and error-monitoring hyperactivity"],
    ["F3", "Intrusive thoughts (Pure-O)", "CSTC + DMN hyperconnectivity", "Cathodal Cz + Pz + anodal F3 (triple montage)", "Maximum circuit and DMN inhibition for ruminating intrusive thought OCD"],
    ["F4", "OCD + depression", "SMA hyperactivity + DLPFC hypoactivation (dual)", "Cathodal Cz (SMA OCD) + anodal F3 strong (DLPFC depression+OCD)", "Cathodal OCD component + strong anodal for comorbid depression component"],
    ["F5", "Contamination OCD (insula)", "Insula-OFC disgust circuit", "Cathodal Cz + TPS anterior insula + taVNS primary", "SMA inhibition + deep insula disgust circuit + autonomic anxiety modulation"],
    ["F6", "Treatment-resistant OCD", "Multi-CSTC hyperactivation", "HDCkit cathodal Cz+F7+F8 + anodal F3 + TPS OFC/SMA + taVNS 40min", "Maximum multi-site inhibitory OCD protocol"],
  ],
  classicTpsProtocols: [
    ["T1", "OCD / SMA inhibitory", "SMA (Cz region)", "0.2mJ/mm² (inhibitory effect at this parameter)", "3000 pulses", "Emerging"],
    ["T2", "OCD / OFC inhibitory", "OFC / frontal polar region", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T3", "OCD / caudate deep", "Caudate/striatum deep", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T4", "Contamination / insula", "Anterior insula", "0.2mJ/mm²", "2500 pulses", "Exploratory"],
    ["T5", "TRD-OCD / combined CSTC", "OFC + SMA + caudate sequential", "0.2mJ/mm²", "6000 total pulses", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Classic OCD — SMA deep", "SMA compulsion urge circuit", "SMA (Cz) 0.2mJ/mm² × 3000 — deep SMA inhibitory stimulation", "Deep SMA inhibitory circuit modulation during ERP session"],
    ["FT2", "Checking OCD — OFC deep", "OFC-CSTC error loop", "OFC/frontal polar 0.2mJ/mm² × 3000 — deep OFC inhibitory", "Deep OFC inhibitory circuit for checking and error monitoring OCD"],
    ["FT3", "CSTC loop — caudate deep", "Caudate CSTC node", "Caudate deep 0.2mJ/mm² × 3000 — deep striatum inhibitory", "Deep caudate inhibitory targeting for CSTC loop disruption"],
    ["FT4", "Contamination OCD — insula", "Anterior insula disgust circuit", "Anterior insula 0.2mJ/mm² × 2500 — deep disgust circuit", "Deep anterior insula inhibitory for contamination/disgust OCD"],
    ["FT5", "Treatment-resistant OCD", "Multi-CSTC", "OFC + SMA + caudate sequential 0.2mJ/mm² × 6000 total", "Maximum sequential deep CSTC circuit inhibitory stimulation"],
    ["FT6", "OCD + tics", "SMA-pre-SMA tic-OCD shared circuit", "SMA 0.2mJ/mm² × 3000 — shared SMA target for OCD + tic urge circuit", "Single deep SMA target addressing both OCD and tic urge circuit"],
    ["FT7", "OCD + depression (DLPFC add)", "SMA inhibitory + DLPFC upregulatory", "SMA 0.2mJ/mm² × 2500 inhibitory + DLPFC anodal 0.2mJ/mm² × 2000 excitatory", "Deep combined OCD-SMA inhibitory then DLPFC antidepressant excitatory"],
    ["FT8", "Intrusive thoughts / hippocampal", "Extinction memory + DMN suppression", "Hippocampal 0.2mJ/mm² × 2500 + SMA 0.2mJ/mm² × 2500 combined", "Deep extinction memory support + SMA inhibitory for pure-O"],
    ["FT9", "Maintenance OCD protocol", "SMA monthly maintenance", "SMA 0.2mJ/mm² × 1500 monthly", "Monthly deep SMA inhibitory maintenance post-acute treatment"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Contamination/Washing OCD",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 30min — anxiety-compulsion cycle reduction before ERP", "Reduce baseline anxiety and disgust-driven autonomic arousal before contamination ERP exposure"],
        ["O — Optimise", "tDCS cathodal Cz (SMA) + anodal F3 2mA 20min — primary OCD montage", "Inhibit SMA urge-to-wash circuit; upregulate DLPFC inhibitory control over washing compulsion"],
        ["Z — Zone", "TPS anterior insula 0.2mJ/mm² 2500 — deep disgust circuit inhibitory", "Deep anterior insula modulation for disgust-based contamination processing"],
        ["O — Outcome", "ERP contamination exposure (progressive hierarchy) concurrent — withhold washing", "Contamination exposure (dirty objects, public spaces) with response prevention during primed circuit"],
      ],
    },
    {
      phenotype: "Checking OCD",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 30min — reduce checking anxiety baseline", "Reduce OFC-driven error monitoring baseline anxiety before targeted OFC inhibition"],
        ["O — Optimise", "tDCS cathodal F7 (OFC) + cathodal Cz (SMA) + anodal F3 1.5mA 20min", "Combined OFC and SMA inhibition with DLPFC upregulation — checking OCD triple montage"],
        ["Z — Zone", "TPS OFC 0.2mJ/mm² 3000 — deep OFC error monitoring inhibitory circuit", "Deep OFC inhibitory stimulation during ERP checking prevention"],
        ["O — Outcome", "ERP checking prevention concurrent — timed departure without checking; delayed return", "Checking prevention hierarchy; time locks; exposure to uncertainty during primed circuit"],
      ],
    },
    {
      phenotype: "Symmetry/Ordering OCD",
      combinations: [
        ["S — Stabilise", "taVNS 20min — autonomic preparation; reduce 'not just right' distress baseline", "Reduce autonomic distress driving symmetry compulsive urge"],
        ["O — Optimise", "tDCS cathodal Cz (SMA) + anodal F4 2mA 20min — right DLPFC for symmetry variant", "Primary SMA inhibition; right DLPFC for spatial-symmetry variant of OCD"],
        ["Z — Zone", "TPS SMA 0.2mJ/mm² 3000 — deep SMA incompleteness urge circuit", "Deep SMA inhibitory for not-just-right urge reduction"],
        ["O — Outcome", "ERP asymmetry tolerance exposure concurrent — deliberate asymmetry without ordering", "Deliberate disorder exposure with response prevention; tolerance of incompleteness training"],
      ],
    },
    {
      phenotype: "Intrusive Thoughts (Pure-O)",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — reduce anxiety underlying thought-action fusion", "Broad-spectrum anxiety reduction for thought-intrusion anxiety distress"],
        ["O — Optimise", "tDCS cathodal Cz + cathodal Pz + anodal F3 1.5mA 20min — triple montage", "SMA inhibition + DMN suppression + DLPFC upregulation for intrusive thought circuit"],
        ["Z — Zone", "TPS SMA 0.2mJ/mm² 2500 + hippocampal 0.2mJ/mm² 2000 — extinction support", "SMA inhibitory + hippocampal extinction memory support for mental ritual prevention"],
        ["O — Outcome", "ACT defusion + ERP mental ritual prevention concurrent — cognitive ERP for pure-O", "Cognitive defusion from intrusive thoughts + mental ritual prevention during primed circuit"],
      ],
    },
    {
      phenotype: "OCD + Depression Comorbidity",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 60min — mood and anxiety stabilisation", "Address both OCD anxiety and depressive mood dysregulation"],
        ["O — Optimise", "tDCS cathodal Cz (SMA for OCD) + strong anodal F3 (DLPFC for MDD) 2mA 20min", "Combined OCD inhibitory and antidepressant upregulatory approach — same electrode serves dual purpose"],
        ["Z — Zone", "TPS SMA 0.2mJ/mm² 2500 + DLPFC 0.2mJ/mm² 2000 combined", "Deep OCD-SMA inhibitory then antidepressant DLPFC upregulatory"],
        ["O — Outcome", "ERP concurrent + behavioural activation for depression — integrated protocol", "Integrated OCD ERP and depression behavioural activation in primed state"],
      ],
    },
    {
      phenotype: "Hoarding OCD",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 60min — reduce emotional distress about discarding", "Reduce the intense emotional distress that prevents hoarding OCD patients from discarding"],
        ["O — Optimise", "tDCS anodal F3+F4 bilateral 1.5mA 20min (OFC inhibitory component via Fp montage adapted)", "Bilateral frontal approach for hoarding — vmPFC-OFC complex adapted; DLPFC bilateral for decision-making", ],
        ["Z — Zone", "TPS bilateral frontal OFC/vmPFC 0.2mJ/mm² 4000 — deep frontal hoarding circuit", "Deep bilateral frontal circuit for hoarding-specific OFC-vmPFC-emotional attachment circuit"],
        ["O — Outcome", "Hoarding-adapted ERP (decision-making practice, discarding hierarchy) concurrent", "Graduated discarding practice with decision-making support during primed frontal circuit"],
      ],
    },
    {
      phenotype: "Treatment-Resistant OCD",
      combinations: [
        ["S — Stabilise", "taVNS 40min bilateral + CES 60min — maximum anxiety-compulsion cycle disruption", "Maximum autonomic stabilisation for intensive multi-site inhibitory stimulation"],
        ["O — Optimise", "HDCkit cathodal Cz+F7+F8 + anodal F3 2mA — maximum OCD multi-site protocol", "Maximum bilateral OFC and SMA cathodal inhibition with DLPFC upregulation"],
        ["Z — Zone", "TPS OFC + SMA + caudate 0.2mJ/mm² × 6000 total sequential — maximum CSTC", "Maximum sequential deep CSTC inhibitory circuit stimulation"],
        ["O — Outcome", "Intensive ERP (daily sessions) + DBS consultation if still no response", "Maximum frequency ERP concurrent; if still non-responsive consider specialist DBS referral"],
      ],
    },
    {
      phenotype: "OCD + Tic Disorder",
      combinations: [
        ["S — Stabilise", "taVNS 20min + CES 30min — reduce tic-anxiety and compulsion-anxiety baseline", "Shared autonomic substrate for tic urges and OCD compulsion urges"],
        ["O — Optimise", "tDCS cathodal Cz (SMA) + anodal F3 2mA 20min — SMA addresses both OCD and tics", "Single primary SMA target addresses shared SMA-pre-SMA hyperactivation in both OCD and tics"],
        ["Z — Zone", "TPS SMA 0.2mJ/mm² 3000 — deep SMA for dual OCD-tic benefit", "Deep SMA inhibitory stimulation — dual benefit for OCD compulsion urge and tic urge circuit"],
        ["O — Outcome", "ERP (OCD) + habit reversal training (HRT — tics) concurrent", "Concurrent OCD and tic-specific behavioural therapies in primed SMA state"],
      ],
    },
    {
      phenotype: "Harm OCD with Moral Injury",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min + taVNS 30min — moral anxiety and autonomic stabilisation", "Reduce the intense moral-religious anxiety driving harm obsessions and checking"],
        ["O — Optimise", "tDCS cathodal Cz + anodal Fz/F3 2mA 20min — SMA inhibit + vmPFC moral circuit", "SMA inhibitory for compulsion urge; vmPFC/Fz upregulation for moral appraisal flexibility"],
        ["Z — Zone", "TPS vmPFC/OFC 0.2mJ/mm² 3000 — deep moral appraisal circuit modulation", "Deep vmPFC-OFC moral circuit for harm OCD obsessional content"],
        ["O — Outcome", "ACT-based ERP (values clarification) + acceptance of uncertainty concurrent", "ACT values-based exposure; acceptance of intrusive harm thoughts without ritualising; moral flexibility training"],
      ],
    },
  ],

  taskPairingRows: [
    ["ERP — Contamination Hierarchy", "Contamination/washing OCD", "tDCS cathodal Cz + SMA active + taVNS concurrent", "Progressive contamination exposure; withhold washing; anxiety habituation during stimulation"],
    ["ERP — Checking Prevention", "Checking OCD", "tDCS cathodal F7+Cz active", "Timed departures without checking; delayed return; uncertainty tolerance training"],
    ["ERP — Symmetry Tolerance", "Symmetry/ordering OCD", "tDCS cathodal Cz active", "Deliberate asymmetry arrangement; resist ordering; incompleteness tolerance exposure"],
    ["ACT Defusion", "Intrusive thoughts (pure-O)", "tDCS cathodal Cz + Pz + anodal F3 active", "Thought defusion exercises; observe thoughts as mental events; no neutralisation"],
    ["Habit Reversal Training", "OCD + tics", "tDCS cathodal Cz active (SMA)", "Competing response training for tics during SMA-primed inhibitory state"],
    ["Discarding Practice", "Hoarding OCD", "tDCS bilateral frontal active", "Graduated discarding hierarchy with decision-making support during primed frontal circuits"],
  ],
  outcomeMeasures: "Primary: Yale-Brown Obsessive Compulsive Scale (Y-BOCS; session 1, 5, 10, 1-month follow-up); OCD Symptom Inventory. Secondary: PHQ-9 (depression comorbidity), Obsessive Beliefs Questionnaire (OBQ), ERP homework compliance diary, Sheehan Disability Scale (functional impairment), GAD-7 (anxiety), PSQI (sleep). Safety: monitor for paradoxical anxiety increase (rare with cathodal); skin inspection; crisis plan if suicidal ideation comorbidity.",

  medicationSectionTitle: "Pharmacotherapy Context for OCD",
  medicationSectionText: "OCD pharmacotherapy requires higher doses than depression: sertraline 200mg/day, fluoxetine 60–80mg/day, fluvoxamine 300mg/day, paroxetine 60mg/day, escitalopram 40mg/day, clomipramine 250mg/day. An adequate SRI trial for OCD is 8–12 weeks at maximum tolerated dose (unlike depression's 4–6 weeks). Non-response to ≥2 adequate SRI trials qualifies as treatment-resistant OCD. Augmentation strategies: aripiprazole (Level A; 5–15mg/day), risperidone (Level A; 0.5–2mg/day — particularly for tic-comorbid OCD), olanzapine (Level B). N-acetylcysteine (NAC; 2400–3000mg/day) has Level C evidence as a glutamate modulator. The Doctor coordinates FNON timing with pharmacotherapy: SSRIs do not adversely interact with any FNON modality. Note that cathodal tDCS (the primary OCD approach) has a theoretically lower seizure risk than anodal, as it reduces rather than increases cortical excitability.",

  references: {
    foundational: [
      "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR). APA Publishing.",
      "Saxena S, Rauch SL. (2001). Functional neuroimaging and the neuroanatomy of obsessive-compulsive disorder. Psychiatr Clin North Am, 24(3), 663–686. doi:10.1016/S0193-953X(05)70248-9",
      "Abramowitz JS, Taylor S, McKay D. (2009). Obsessive-compulsive disorder. Lancet, 374(9688), 491–499. doi:10.1016/S0140-6736(09)60240-3",
      "Rotge JY, Guehl D, Dilharreguy B, et al. (2008). Provocation of obsessive-compulsive symptoms: A quantitative voxel-based meta-analysis of functional neuroimaging studies. J Psychiatry Neurosci, 33(5), 405–412.",
      "Milad MR, Rauch SL. (2012). Obsessive-compulsive disorder: Beyond segregated cortico-striatal pathways. Trends Cogn Sci, 16(1), 43–51. doi:10.1016/j.tics.2011.11.003",
      "Foa EB, Yadin E, Lichner TK. (2012). Exposure and Response Prevention for Obsessive-Compulsive Disorder (2nd ed.). Oxford University Press.",
    ],
    tdcs: [
      "Gomes PV, Brasil-Neto JP, Allam N, Rodrigues RC. (2012). A randomized, double-blind clinical trial of transcranial direct current stimulation in obsessive-compulsive disorder. Int J Neuropsychopharmacol, 15(4), 495–504. doi:10.1017/S1461145711001290",
      "Mondino M, Haesebaert F, Poulet E, Saoud M, Brunelin J. (2015). Focal transcranial direct current stimulation of the supplementary motor area (SMA) reduces the severity of tics in Tourette syndrome. Brain Stimul, 8(6), 1194–1196. doi:10.1016/j.brs.2015.07.043",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with NIBS. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with tDCS. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Mantovani A, Simpson HB, Fallon BA, Rossi S, Lisanby SH. (2010). Randomized sham-controlled trial of repetitive TMS in treatment-resistant OCD. Int J Neuropsychopharmacol, 13(2), 217–227. doi:10.1017/S1461145709990435",
      "Nitsche MA, Paulus W. (2000). Excitability changes in the human motor cortex by weak tDCS. J Physiol, 527(3), 633–639.",
      "Volpato C, Piccione F, Cavinato M, et al. (2013). Modulation of affective decision making in a gambling task with tDCS over the prefrontal cortex. Brain Stimul, 6(2), 180–187. doi:10.1016/j.brs.2012.04.003",
      "Guarienti F, Caumo W, Shiozawa P, Cordeiro Q, Boggio PS. (2015). Noninvasive brain stimulation in obsessive-compulsive disorder: A systematic review and meta-analysis. Neuromodulation, 18(4), 265–274. doi:10.1111/ner.12247",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and NIBS. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Bikson M, et al. (2016). Safety of tDCS. Brain Stimul, 9(5), 641–661.",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930.",
      "Peterchev AV, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335.",
    ],
    tavns: [
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Farmer AD, Strzelczyk A, Finisguerra A, et al. (2020). International consensus on taVNS reporting standards. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of brain-gut axis. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Rong P, et al. (2016). Effect of taVNS on major depressive disorder. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
      "Steenbergen L, et al. (2015). tVNS enhances response inhibition via norepinephrine. Brain Stimul, 8(6), 1155–1160. doi:10.1016/j.brs.2015.09.001",
      "Burger AM, et al. (2020). taVNS reduces startle response in anxious individuals. Biol Psychol, 149, 107800.",
      "Manta S, et al. (2012). Enhancement of serotonin and NE neuron function by VNS. J Psychiatry Neurosci, 37(3), 181–191.",
      "Borges U, et al. (2019). Influence of taVNS on cardiac vagal activity. Brain Stimul, 12(3), 727–729.",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of CES for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Kavirajan HC, Lueck K, Cho K. (2014). CES use in outpatient psychiatric and pain treatment. J Psychiatr Pract, 20(5), 332–343.",
      "Overcash SJ. (2005). Narrative literature review: CES for anxiety, insomnia, depression. Am J Electromed, 22(2), 22–28.",
    ],
    network: [
      "Saxena S, Rauch SL. (2001). Functional neuroimaging and the neuroanatomy of OCD. Psychiatr Clin North Am, 24(3), 663–686.",
      "Rotge JY, et al. (2008). Provocation of OCD symptoms: A quantitative voxel-based meta-analysis. J Psychiatry Neurosci, 33(5), 405–412.",
      "Milad MR, Rauch SL. (2012). OCD: Beyond segregated cortico-striatal pathways. Trends Cogn Sci, 16(1), 43–51. doi:10.1016/j.tics.2011.11.003",
      "Mantovani A, et al. (2010). Randomized sham-controlled trial of rTMS in treatment-resistant OCD. Int J Neuropsychopharmacol, 13(2), 217–227.",
      "Carter CS, Braver TS, Barch DM, Botvinick MM, Noll D, Cohen JD. (1998). Anterior cingulate cortex, error detection, and the online monitoring of performance. Science, 280(5364), 747–749. doi:10.1126/science.280.5364.747",
    ],
  },
  // ── FNON Protocol Data (SOZO_Brain_Networks_qEEG_FNON.xlsx, April 2026) ──
  fnonPrimaryNetwork: 'Salience (dACC) + CSTC Circuit',
  fnonSecondaryNetwork: 'CSTC OFC-caudate',
  fnonFBand: 'Theta normalisation (error monitoring)',
  fnonEegNodes: 'Fz/AFz(dACC/mPFC)+F3/F4(DLPFC)+deep caudate',
  fnonOscillationGoal: 'Normalise ACC theta; reduce CSTC hyperactivity; suppress OFC-caudate beta loop',
  fnonPrimaryModalityParams: 'Deep TMS BrainsWay H7: 20Hz, 100%rMT, 2000 pulses, 29 sessions. Symptom provocation pre-session. FDA cleared.',
  fnonAddonModality: 'LIFU (caudate nucleus); tDCS bilateral OFC cathodal; TPS (Fz/AFz+F3/F4)',
  fnonSessions: '29 sessions',
  fnonEvidenceLevel: 'RCT, Meta-analysis',
  fnonLitCount: '100+ TMS; 5+ LIFU; 50+ DBS',
  fnonKeyReferences: 'Carmi 2019 Am J Psychiatry; Roth 2021; Greenberg 2010 DBS; Connectomic OCD 2022',
  fnonNotes: 'FNON: Theta excess ACC (ERN hyperactivation) + beta OFC. H7 gold standard. LIFU noninvasive caudate option.',
  fnonQeegBiomarker: '↑Theta ACC; ↑Beta OFC',
  fnonPaperCounts: {
    tps: null, tms: 100, tdcs: 10,
    tavns: 5, ces: null, tacs: null,
    pbm: null, lifu: 5, pemf: null, dbs: 50,
  },
  fnonBestFirstLine: 'TMS Deep H7 (FDA cleared)',
  fnonBestSecondLine: 'LIFU caudate + TPS',
  fnonScore: 4,

};
