'use strict';
module.exports = {
  conditionFull: "Parkinson's Disease",
  conditionShort: "Parkinson's",
  conditionSlug: "parkinsons",
  documentNumber: "SOZO-PD-PROT-001",
  offLabelCoverText: "TPS and tDCS use in Parkinson's Disease is INVESTIGATIONAL / OFF-LABEL in some applications. tDCS has Level B evidence for PD motor facilitation (M1 anodal). TPS is investigational off-label.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Level B evidence; M1 anodal motor facilitation for PD established', 'Standard informed consent'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Emerging evidence for PD autonomic and motor symptoms', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'Supportive for PD depression, anxiety, and sleep', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of Parkinson's Disease (UK Brain Bank or MDS diagnostic criteria) by a qualified neurologist",
    "H&Y Stage 1–3 (ambulatory with or without assistance)",
    "Stable PD medication regimen (levodopa / dopamine agonist) for ≥4 weeks prior to enrolment",
    "UPDRS-III ≥15 at baseline assessment (motor symptoms warrant neuromodulation)",
    "Age 40–85 years (exceptions at Doctor discretion with documented rationale)",
    "No active DBS implant (absolute TPS contraindication)",
    "Capacity to provide informed consent (or supported consent with carer)",
    "Willing and able to attend sessions as prescribed",
  ],
  exclusionCriteria: [
    "Active deep brain stimulator (DBS) — ABSOLUTE contraindication to TPS",
    "Intracranial metallic hardware in the stimulation field",
    "Cardiac pacemaker or ICD",
    "Active psychosis or dopamine dysregulation syndrome",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
    "Pregnancy",
    "Recent neurosurgical procedure or skull defect over target area",
  ],
  conditionsRequiringDiscussion: [
    "Atypical Parkinsonian syndromes (PSP, MSA, CBS) — distinct protocol required; refer to specialist",
    "Levodopa wearing-off — assess in defined ON state; document timing of last dose precisely",
    "Cognitive impairment (MoCA <21) — supported consent; caregiver present; simplified protocol",
    "Orthostatic hypotension — supine or supported-seated session; blood pressure monitoring pre/post",
    "REM Sleep Behaviour Disorder — CES evening protocol; sleep specialist concurrent",
    "Comorbid essential tremor — clarify PD vs ET component; differentiated protocol",
    "Impulse control disorder on dopamine agonist — psychiatry input; monitor closely",
    "Severe dysarthria — speech therapy concurrent; AAC support for cognitive task components",
    "Elderly (≥75) — reduce tDCS intensity to 1–1.5 mA; shorter sessions; fall risk assessment before motor tasks",
  ],

  overviewParagraph: "Parkinson's Disease (PD) is the second most common neurodegenerative disorder worldwide, affecting approximately 10 million people globally and over 145,000 in the United Kingdom. It is characterised by a progressive loss of dopaminergic neurons in the substantia nigra pars compacta, resulting in the cardinal motor features of resting tremor, rigidity, bradykinesia, and postural instability. Beyond motor symptoms, PD involves a broad spectrum of non-motor features including cognitive impairment (PD-MCI in 20–40%; PD dementia in 80% after 20 years), depression (30–40%), anxiety (30–40%), autonomic dysfunction (orthostatic hypotension, constipation), sleep disorders (RBD, insomnia), fatigue, and pain. Disease burden is substantial and progressive, with conventional pharmacotherapy (levodopa, dopamine agonists, MAO-B inhibitors) and DBS providing symptomatic relief but not modifying the underlying neurodegenerative process. FNON neuromodulation offers an adjunctive approach targeting the network-level circuit dysfunction that persists despite optimal pharmacological management.",
  fnonNetworkParagraph: "Parkinson's Disease is fundamentally a disorder of large-scale motor and cognitive network disruption driven by dopaminergic denervation and progressive Lewy body pathology. The FNON framework identifies four core circuit abnormalities: (1) Primary Motor Network hypoactivation (M1, SMA, premotor cortex) secondary to basal ganglia-thalamic circuit failure and beta-band oscillatory excess; (2) Executive Control Network (DLPFC-PPC) hypofunction driving cognitive impairment in PD-MCI; (3) Default Mode Network disruption in advanced PD and PD-MCI; and (4) Salience Network dysregulation contributing to non-motor symptom burden. SOZO targets these abnormalities through multi-modal neuromodulation: tDCS and TPS facilitate motor and prefrontal cortex excitability; taVNS modulates autonomic-brainstem circuits; CES addresses non-motor symptom burden including anxiety, sleep, and mood.",
  networkDisorderParagraphs: [
    "The motor circuit pathology in PD is best understood as a failure of the direct and indirect striatal pathways to modulate thalamo-cortical output appropriately. Loss of dopaminergic tone in the striatum leads to hyperactivation of the indirect pathway (striatum → GPe → STN → GPi/SNr), resulting in excessive inhibition of the thalamo-cortical motor relay. This manifests as reduced motor cortex (M1) and supplementary motor area (SMA) excitability — measurable by TMS as reduced motor evoked potential amplitude and impaired cortical plasticity (LTP-like response). The resulting beta-band (13–30 Hz) oscillatory excess in the BG-thalamic circuit represents the neurophysiological correlate of bradykinesia and rigidity.",
    "Cognitive network disruption in PD-MCI involves hypoactivation of the DLPFC and posterior parietal cortex (PPC) — the backbone of the Central Executive Network (CEN) — with concomitant disruption of default mode network (DMN) deactivation during cognitive tasks. Cholinergic denervation (nucleus basalis of Meynert) contributes to CEN hypofunction and attentional deficits. Resting-state fMRI studies consistently demonstrate reduced DLPFC-PPC functional connectivity in PD-MCI compared to cognitively normal PD patients, with the degree of connectivity reduction predicting conversion to dementia.",
    "The FNON multi-modal approach for PD simultaneously targets the motor and cognitive network deficits. Motor network protocols (anodal M1 tDCS, TPS targeting M1+SMA at 4 Hz) facilitate cortical excitability by upregulating GABAergic interneuron plasticity and reducing beta-band oscillatory dominance. Cognitive network protocols (DLPFC bilateral tDCS, TPS DLPFC) restore prefrontal executive function. taVNS provides autonomic modulation via the NTS-brainstem pathway, with emerging evidence for anti-inflammatory and neuroprotective effects relevant to PD pathophysiology.",
  ],

  networkCitationKeys: [
    { authors: "Cantello et al.", year: 2002, citations: 210, title: "Abnormal cortical excitability in Parkinson's disease", doi: "" },
    { authors: "Lefaucheur et al.", year: 2017, citations: 850, title: "Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation", doi: "10.1016/j.clinph.2016.10.087" },
    { authors: "Benninger et al.", year: 2010, citations: 180, title: "Transcranial direct current stimulation for the treatment of Parkinson's disease", doi: "" },
    { authors: "Broeder et al.", year: 2015, citations: 95, title: "Transcranial direct current stimulation in Parkinson's disease", doi: "" },
    { authors: "Fang et al.", year: 2016, citations: 110, title: "Transcutaneous vagus nerve stimulation modulates default mode network", doi: "" },
  ],
  fnonEvidenceStrength: "Moderate",

  pathophysiologyText: "PD pathophysiology centres on the progressive loss of dopaminergic neurons in the substantia nigra pars compacta (SNpc), with Lewy body (alpha-synuclein aggregate) pathology staging from the brainstem (Stages 1–2: medulla, pons, locus coeruleus — explaining autonomic, sleep, and olfactory prodromal features) to midbrain (Stage 3–4: SNpc — explaining motor features) to limbic and neocortex (Stage 5–6 — explaining cognitive, psychiatric, and cortical features). The resulting dopaminergic denervation disrupts the cortico-striatal-thalamo-cortical (CSTC) motor loop, generating beta-band oscillatory excess (13–30 Hz) that suppresses movement initiation and causes bradykinesia and rigidity. Cholinergic denervation (nucleus basalis, pedunculopontine nucleus) contributes to cognitive decline, gait disturbance, and falls. Noradrenergic loss (locus coeruleus) drives mood, autonomic, and attentional deficits. Serotonergic involvement (raphe nuclei) contributes to depression and pain. Beyond motor symptoms, neuroinflammation (activated microglia, elevated TNF-α, IL-1β), impaired mitochondrial function, oxidative stress, and disrupted protein clearance (ubiquitin-proteasome and autophagy systems) accelerate neurodegeneration and network dysfunction across all FNON-relevant circuits.",
  cardinalSymptoms: [
    ["Resting Tremor", "Pill-rolling tremor at rest (4–6 Hz); diminished with movement; typically asymmetric onset; hands, forearms, jaw, lips affected", "~70–75% of PD patients; not universal — tremor-dominant subtype", "Bhidayasiri, 2005; Zach et al., 2020"],
    ["Rigidity", "Lead-pipe or cogwheel (tremor superimposed) resistance to passive movement; affects all limb muscle groups and axial muscles", "~90%; one of the most consistent motor features", "Bhidayasiri, 2005"],
    ["Bradykinesia", "Slowness of movement initiation and execution; reduced amplitude and speed of repetitive movements; impaired dexterity", "Core diagnostic criterion (MDS); ~95%", "MDS Diagnostic Criteria, 2015"],
    ["Postural Instability", "Impaired postural reflexes; loss of balance on pull test; major fall risk; typically later feature (H&Y 3+)", "~80% with disease progression; key disability driver", "Bloem et al., 2004"],
    ["Freezing of Gait (FoG)", "Sudden inability to initiate or continue walking (feet feel glued to floor); often triggered by narrow spaces, turns, thresholds", "~50%; high fall risk; responds to rhythmic auditory cueing", "Nutt et al., 2011"],
    ["Hypomimia / Masked Face", "Reduced facial expression; infrequent blinking; diminished prosody; misread as emotional blunting by caregivers", "~90%; impacts communication quality", "Bologna et al., 2013"],
    ["Micrographia", "Progressively smaller handwriting; impaired fine motor control; reflects bradykinesia in hand motor circuits", "~65%; often early marker", "Rosenblum et al., 2013"],
    ["Cognitive Impairment (PD-MCI)", "Executive dysfunction (planning, working memory, cognitive flexibility); visuospatial deficits; attention impairment; MoCA <26", "~20–40% at diagnosis; ~80% after 20 years dementia risk", "Litvan et al., 2012"],
    ["Depression", "Anhedonia, low mood, fatigue, apathy; often precedes motor symptoms; distinct from reactive sadness", "~30–40% of PD patients; underdiagnosed", "Reijnders et al., 2008"],
    ["Autonomic Dysfunction", "Orthostatic hypotension, constipation, bladder dysfunction, seborrhoea, anosmia; often precedes motor phase", "~80% with disease progression; major QoL impact", "Goldstein, 2003"],
    ["REM Sleep Behaviour Disorder (RBD)", "Vocalisation, acting out dreams, complex motor behaviours during REM sleep; prodromal PD marker", "~70% will develop PD/DLB/MSA within 10 years", "Postuma et al., 2013"],
    ["Pain and Sensory Symptoms", "Musculoskeletal, dystonic, central neuropathic, radicular pain; sensory disturbances; often underrecognised", "~40–60% of PD patients", "Ford, 2010"],
  ],
  standardGuidelinesText: [
    "Current evidence-based management of Parkinson's Disease follows NICE guidelines (NG71, 2017), European Academy of Neurology (EAN), and Movement Disorder Society (MDS) guidelines, positioning levodopa (co-careldopa / co-beneldopa) as the gold-standard motor treatment for most patients, with dopamine agonists (pramipexole, ropinirole, rotigotine) as initial therapy in younger patients or as adjuncts. MAO-B inhibitors (rasagiline, safinamide) are used as monotherapy or adjuncts. For motor complications (wearing-off, dyskinesia), COMT inhibitors (entacapone, opicapone), amantadine, and continuous drug delivery systems (apomorphine infusion, levodopa-carbidopa intestinal gel) are indicated in specialist centres.",
    "Deep Brain Stimulation (DBS) of the subthalamic nucleus (STN) or globus pallidus interna (GPi) is the most evidence-based surgical intervention for advanced PD with motor complications, providing sustained motor benefit and reducing medication burden. Focused ultrasound (FUS) thalamotomy is CE/FDA-approved for tremor-dominant PD. Physiotherapy (gait training, balance exercises, LSVT LOUD/BIG programmes), occupational therapy, and speech and language therapy are integral components of PD management and should be coordinated with neuromodulation protocols.",
    "SOZO FNON protocols are designed to complement and enhance standard-of-care PD management, not replace dopaminergic pharmacotherapy. The treating neurologist/Doctor coordinates FNON neuromodulation with the patient's PD medication regimen, physiotherapy programme, and any DBS management (DBS is an absolute TPS contraindication). Session scheduling should be coordinated with medication timing to assess patients in a defined ON state for UPDRS-III outcome measurement.",
  ],

  fnonFrameworkParagraph: "The FNON framework for PD targets the basal ganglia-thalamo-cortical motor circuit failure at two accessible cortical nodes: M1 (primary motor cortex) and SMA (supplementary motor area) — the final common motor output destinations where reduced excitability manifests as bradykinesia and impaired movement initiation. Anodal tDCS and TPS at 4 Hz upregulate cortical excitability through LTP-like plasticity mechanisms, reducing beta-band dominance and facilitating motor output. Parallel DLPFC targeting addresses the cognitive-motor integration deficit and PD-MCI component. taVNS and CES provide autonomic modulation and non-motor symptom support across the full PD symptom spectrum.",
  keyBrainRegions: [
    ["Primary Motor Cortex (M1) — C3/C4", "Reduced excitability and impaired LTP-like cortical plasticity; reduced MEP amplitude on TMS; hypoactivation on fMRI during movement initiation", "PRIMARY MOTOR TARGET: anodal tDCS M1 bilateral (C3/C4); TPS M1 at 4 Hz 0.25 mJ/mm²; facilitates LTP-like plasticity and reduces beta-band excess", "Lefaucheur et al., 2017; Benninger et al., 2010; Broeder et al., 2015"],
    ["Supplementary Motor Area (SMA) — Cz", "Impaired motor sequence planning and initiation; SMA-M1 disconnection contributes to freezing of gait and movement initiation failure; reduced SMA activation on fMRI", "Anodal tDCS Cz; TPS SMA at 4 Hz; facilitates gait initiation circuits; combine with rhythmic auditory stimulation (RAS) for FoG", "Nachev et al., 2008; Lewis & Barker, 2009"],
    ["Dorsolateral Prefrontal Cortex (DLPFC) — F3/F4", "Executive dysfunction; reduced working memory, cognitive flexibility, and dual-task performance; DLPFC hypoactivation on fMRI in PD-MCI", "Bilateral DLPFC anodal tDCS (F3/F4); TPS DLPFC at 4 Hz; enhances cognitive-motor integration and executive function for PD-MCI", "Brugger et al., 2010; Dimitrova et al., 2004"],
    ["Substantia Nigra pars compacta (SNpc)", "Primary site of dopaminergic neurodegeneration; loss of >60-70% of SNpc neurons before motor symptoms appear; not directly stimulable by surface NIBS", "Indirect benefit via cortical network facilitation; taVNS anti-inflammatory mechanisms may attenuate neuroinflammation relevant to dopaminergic circuit preservation", "Hornykiewicz, 2001; Poewe et al., 2017"],
    ["Basal Ganglia (Striatum, GPi, STN)", "Dopaminergic denervation disrupts direct/indirect pathway balance; STN hyperactivity drives GPi inhibition of thalamo-cortical motor output; beta-band oscillatory excess", "Indirect modulation via cortical inputs; tDCS and TPS reduce cortico-striatal beta-band drive indirectly; taVNS modulates striatal dopamine release via vagal-brainstem-mesocortical pathway", "DeLong & Wichmann, 2007; Bergman et al., 1998"],
    ["Thalamus (VL/VA nuclei)", "Receives excessive GPi inhibitory output; reduced thalamo-cortical motor relay; impaired motor timing signals to M1/SMA", "TPS thalamic proxy targeting (Cz approach); taVNS modulates thalamo-cortical synchrony via brainstem-thalamic relays", "Marsden & Obeso, 1994; Wichmann & DeLong, 2006"],
    ["Cerebellum", "Compensatory overactivation in early PD (cerebellar motor compensation); disrupted cerebello-thalamo-cortical pathway in tremor; cerebellar-thalamic dysrhythmia in tremor-dominant subtype", "TPS cerebellar targeting (Oz approach) for tremor-dominant PD; tDCS cerebellar electrode (Cbz); modulates cerebellar-thalamo-cortical timing circuit", "Lewis et al., 2007; Bhidayasiri, 2005"],
    ["Insula", "Autonomic interoception hub; disrupted in PD autonomic phenotype; insula-ACC connectivity impaired; contributes to orthostatic hypotension and cardiovascular dysregulation", "TPS insular targeting (C3/C4 approach); taVNS modulates insula via NTS-insular visceral afferent pathway", "Craig, 2009; Goldstein, 2003"],
    ["Anterior Cingulate Cortex (ACC)", "Impaired cognitive control, attention, and autonomic regulation; ACC-M1 connectivity reduced in freezing of gait; error monitoring impaired in PD", "tDCS Fz montage for ACC engagement; taVNS ACC modulation; TPS ACC proxy for FoG phenotype", "Woollacott & Braver, 2015; Shine et al., 2013"],
    ["Hippocampus", "Volume reduction in PD dementia; impaired memory consolidation and spatial navigation; cholinergic denervation accelerates hippocampal degeneration", "taVNS via NTS-LC-hippocampal pathway promotes BDNF and neuroplasticity; TPS temporal approach for memory phenotype", "Hattori et al., 2012; Litvan et al., 2012"],
  ],
  additionalBrainStructures: [
    ["Locus Coeruleus (LC)", "Noradrenergic nucleus; degenerated early in PD Lewy body staging (Stage 2); reduced NE tone drives mood, autonomic, and attentional deficits; sleep-wake dysregulation", "taVNS activates NTS→LC pathway; modulates NE release throughout cortex; may enhance LC neuronal survival via BDNF upregulation", "Benarroch, 2009; Szabadi, 2013"],
    ["Nucleus Tractus Solitarius (NTS)", "Primary vagal afferent relay; mediates all taVNS effects; anti-inflammatory pathway (NTS→vagal-splenic axis) may attenuate neuroinflammation in PD", "Primary target of taVNS; NTS-mediated anti-inflammatory effects may reduce microglial activation and neuroinflammatory burden in PD", "Fang et al., 2016; Bonaz et al., 2017"],
    ["Nucleus Basalis of Meynert (nbM)", "Cholinergic nucleus; degenerated in PD-dementia; provides cortical acetylcholine; impairment drives cognitive symptoms, falls, and gait freezing", "Indirect support via DLPFC facilitation; taVNS via NTS-basal forebrain pathway may modulate cholinergic tone", "Bohnen et al., 2006; Perry et al., 1985"],
    ["Pedunculopontine Nucleus (PPN)", "Cholinergic midbrain nucleus; regulates gait, posture, and arousal; degenerated in PD; deep brain PPN stimulation emerging for gait", "taVNS via brainstem-PPN pathway may modulate gait circuits; TPS posterior approach targets brainstem-PPN region indirectly", "Mazzone et al., 2005; Thevathasan et al., 2018"],
    ["Raphe Nuclei", "Serotonergic nuclei; degenerated in PD Lewy staging; reduced serotonin tone contributes to PD depression, pain, and autonomic symptoms", "taVNS modulates serotonergic raphe via brainstem projections; CES may enhance serotonergic tone for PD depression subtype", "Braak et al., 2004; Schlaepfer et al., 2014"],
  ],
  keyFunctionalNetworks: [
    ["Primary Motor Network (PMN)", "M1, SMA, premotor cortex, thalamus (VL/VA), basal ganglia motor loop", "HYPOACTIVATION; reduced M1/SMA excitability; impaired LTP-like plasticity; beta-band (13-30 Hz) oscillatory excess in BG-thalamic circuit", "PRIMARY TARGET: anodal tDCS M1 bilateral (C3/C4) 2 mA 20 min; TPS M1+SMA 4 Hz 0.25 mJ/mm² 10,000 pulses 12 sessions", "Lefaucheur 2017; Benninger 2010"],
    ["Executive Control Network (CEN)", "DLPFC (F3/F4), PPC, anterior PFC", "HYPOACTIVATION; impaired working memory, cognitive flexibility, and dual-task performance in PD-MCI; DLPFC-PPC disconnection", "Anodal tDCS DLPFC bilateral (F3/F4); TPS DLPFC 4 Hz; cognitive training concurrent; prioritise in Cognitive/MCI phenotype", "Brugger 2010; Litvan 2012"],
    ["Default Mode Network (DMN)", "mPFC, PCC, precuneus, angular gyrus, hippocampus", "DISRUPTED in PD-MCI; impaired deactivation during cognitive tasks; pathological DMN activation during motor tasks", "Cathodal tDCS Pz (DMN hub suppression); TPS mPFC targeting; cognitive engagement tasks to suppress DMN intrusion during motor tasks", "Tessitore et al., 2012"],
    ["Salience Network (SN)", "ACC, anterior insula, amygdala", "ALTERED; impaired network switching; SN-motor network dysregulation in FoG; autonomic SN dysfunction in autonomic phenotype", "tDCS Fz-Cz montage; taVNS for insula-ACC-autonomic modulation; TPS ACC targeting for FoG phenotype", "Shine et al., 2013"],
    ["Sensorimotor Network (SMN)", "M1, SMA, premotor cortex, somatosensory cortex S1, cerebellum", "Beta-band excess (13-30 Hz) in SMN; reduced gamma-band motor facilitation; impaired motor timing; dyskinesia risk with excess stimulation", "PRIMARY NETWORK: tDCS C3/C4 bilateral anodal; TPS M1+SMA; pair with active physiotherapy for optimal motor cortex LTP", "Kühn et al., 2006; DeLong & Wichmann 2007"],
    ["Dorsal Attention Network (DAN)", "FEF, IPS, DLPFC, parietal cortex", "IMPAIRED in PD-MCI; reduced visuospatial attention; impaired dual-task performance; contributes to falls and freezing of gait", "tDCS F4/P4 anodal; TPS parietal approach; visuospatial training concurrent with stimulation", "Shine et al., 2014"],
    ["Autonomic / Limbic Network", "Insula, ACC, vmPFC, hypothalamus, brainstem autonomic nuclei", "DYSREGULATED; reduced vagal tone; orthostatic hypotension; cardiac sympathetic denervation; LIMBIC-motor overlap in depression-motor PD", "taVNS primary for autonomic; CES daily supportive; tDCS insula (C3/C4) for autonomic phenotype; combined approach for depression-motor PD", "Goldstein 2003; Braak 2004"],
  ],
  networkAbnormalities: [
    "Primary Motor Network (PMN): Beta-band (13–30 Hz) oscillatory excess in the basal ganglia-thalamic circuit is the neurophysiological hallmark of PD motor features, directly measurable in local field potential recordings from STN-DBS electrodes. This excess beta-band synchronisation suppresses movement initiation (bradykinesia) and maintains muscle tone (rigidity). Levodopa and DBS both reduce beta-band power, correlating with motor improvement. tDCS anodal M1 facilitates LTP-like plasticity that modulates this circuit indirectly through cortico-striatal projections. TPS at 4 Hz targets the primary motor cortex and SMA to upregulate gamma-band facilitation of motor circuits.",
    "Executive Control Network (CEN): DLPFC-PPC hypoactivation is the defining neuroimaging feature of PD-MCI, with the degree of DLPFC functional connectivity reduction predicting conversion to PD dementia. Cholinergic denervation from the nucleus basalis accelerates CEN deterioration. Resting-state EEG studies demonstrate increased alpha-band (8–12 Hz) and theta-band (4–8 Hz) power in PD-MCI, reflecting reduced DLPFC-PPC network efficiency. Bilateral DLPFC anodal tDCS reverses these frequency-domain abnormalities and improves performance on executive function tasks in PD-MCI.",
    "Default Mode Network (DMN): Unlike depression where DMN is hyperactive, in PD the DMN shows characteristic disruption particularly in PD-MCI — with reduced PCC-DLPFC anti-correlation and abnormal DMN activation during cognitive tasks. This 'DMN intrusion' during motor and cognitive task performance reflects the executive-motor disconnection of PD. TPS and DLPFC tDCS targeting the CEN partially restores DMN suppression during task performance, improving dual-task gait and cognitive-motor integration.",
    "Salience Network (SN): SN dysregulation in PD contributes to freezing of gait (ACC-SMA dysregulation), autonomic dysfunction (insula-ACC-hypothalamic axis impairment), and non-motor symptom burden. Abnormal SN-motor network coupling has been identified as a neuroimaging predictor of freezing of gait in resting-state fMRI studies. taVNS directly modulates the SN via NTS-insula-ACC vagal afferent projections, offering a mechanism for non-motor symptom improvement beyond motor facilitation.",
    "Autonomic / Limbic Network: Lewy body pathology in early PD stages (Braak stages 1–2) affects the medulla oblongata, locus coeruleus, and autonomic nuclei before reaching the SNpc. This explains the prodromal non-motor features of PD (anosmia, constipation, RBD, orthostatic hypotension) and suggests that early autonomic circuit modulation via taVNS may target PD pathology at its earliest network stage. Extended taVNS protocols (40 min) are the primary FNON modality for autonomic-predominant PD.",
  ],
  conceptualFramework: "PD is best understood as a multi-circuit network excitability disorder driven by dopaminergic denervation, with primary motor circuit failure (BG-thalamo-cortical beta excess, M1/SMA hypoactivation) and secondary cognitive circuit disruption (DLPFC-PPC CEN hypofunction) as the dominant FNON-targetable abnormalities. The SOZO S-O-Z-O sequence for PD: S — Stabilise autonomic system (taVNS/CES); O — Optimise motor cortex excitability (tDCS M1+SMA); Z — Zone Target (TPS M1+SMA+DLPFC 4 Hz 10,000 pulses); O2 — Outcome consolidation (motor rehabilitation concurrent task). Medication timing is critical: sessions coordinated with levodopa ON state maximise cortical excitability for plasticity induction.",

  clinicalPhenotypes: [
    ["Motor Predominant", "Tremor, rigidity, bradykinesia dominant; M1+SMA hypoactivation; beta-band excess; UPDRS-III primary target; H&Y 1–3", "Jankovic, 2008"],
    ["Cognitive / MCI Predominant", "MoCA <26; executive dysfunction (DLPFC-PPC CEN hypo); visuospatial deficits; memory impairment; PD-MCI or early PDD risk", "Litvan et al., 2012; Brugger et al., 2010"],
    ["Autonomic Predominant", "Orthostatic hypotension, POTS, constipation, bladder; Lewy body brainstem stage 1–2 pathology; taVNS primary modality", "Goldstein, 2003; Braak et al., 2004"],
    ["Depression / Mood Comorbid", "PHQ-9 ≥10; L-DLPFC hypoactivation; LIMBIC-motor overlap; often refractory to SSRI; PD depression burden high", "Reijnders et al., 2008; Starkstein & Merello, 2002"],
    ["Freezing of Gait", "FoG-Q >7; SMA-BG circuit failure; cueing-responsive; high fall risk; SMA tDCS primary; RAS concurrent", "Nutt et al., 2011; Shine et al., 2013"],
    ["Tremor Predominant", "Resting tremor dominant; cerebellar-thalamic involvement; bilateral M1 tDCS; DBS referral if refractory", "Bhidayasiri, 2005; Louis, 2005"],
  ],
  symptomNetworkMapping: [
    ["Bradykinesia / rigidity", "PMN (M1-SMA hypo); BG beta-band excess", "SMN; BG-thalamic", "tDCS M1 bilateral (C3/C4 anodal) + TPS M1+SMA 4 Hz + physiotherapy concurrent", "Moderate (Lefaucheur 2017; Benninger 2010; Broeder 2015)"],
    ["Freezing of gait", "SMA-BG circuit; ACC-SMA dysregulation", "PMN; SN", "tDCS SMA (Cz anodal) + DLPFC + TPS SMA+M1 + RAS gait training concurrent", "Emerging (Giladi 2008; Shine 2013)"],
    ["Cognitive impairment (PD-MCI)", "CEN (DLPFC-PPC hypo); cholinergic deficit", "DMN; DAN", "tDCS DLPFC bilateral (F3/F4 anodal) + TPS DLPFC + cognitive training (N-back, verbal fluency)", "Moderate (Brugger 2010; Litvan 2012)"],
    ["Depression / apathy", "DLPFC L hypo; LIMBIC-motor overlap", "SN; DMN", "tDCS L-DLPFC (F3 anodal) + taVNS + CES daily + behavioural activation", "Emerging (Reijnders 2008; Brunoni 2016)"],
    ["Autonomic dysfunction", "Insula-ACC-brainstem autonomic", "Limbic; SN", "taVNS extended 40 min + CES daily + HRV biofeedback concurrent", "Emerging (Goldstein 2003; Fang 2016)"],
    ["Tremor", "Cerebellar-thalamic dysrhythmia; M1", "PMN; SMN", "tDCS M1 bilateral (C3/C4) + TPS M1 bilateral low energy + taVNS supportive", "Emerging (Bhidayasiri 2005; Lefaucheur 2017)"],
    ["Sleep disturbance (RBD, insomnia)", "Brainstem sleep regulation; LC/raphe degeneration", "SN; Limbic", "CES evening primary + taVNS 30 min + sleep hygiene + sleep specialist concurrent", "Emerging (Postuma 2013; Braak 2004)"],
    ["Pain / sensory", "Insula; SN; descending pain modulation", "Limbic; PMN", "taVNS + tDCS M1 (C3/C4) + CES + pain management concurrent", "Emerging (Ford 2010)"],
  ],

  montageSelectionRows: [
    ["Motor predominant (Tremor/Rigidity/Bradykinesia)", "tDCS M1 bilateral (C3/C4 anodal 2 mA) + TPS M1+SMA 4 Hz 10,000 pulses + physiotherapy concurrent; S-O-Z-O motor sequence"],
    ["Cognitive / MCI dominant (PD-MCI phenotype)", "tDCS DLPFC bilateral (F3/F4 anodal 2 mA) + TPS DLPFC 4 Hz 1,000 pulses + cognitive training (N-back, verbal fluency) concurrent"],
    ["Autonomic dominant (Orthostasis / POTS)", "taVNS extended 40 min primary + CES daily + tDCS M1 low-intensity (1.5 mA) supportive; TPS deferred until autonomic stable"],
    ["Freezing of gait (FoG phenotype)", "tDCS SMA (Cz anodal 2 mA) + DLPFC + TPS SMA+M1 4 Hz 10,000 pulses + RAS gait training and physiotherapy concurrent"],
    ["Depression / mood comorbid (Depression phenotype)", "tDCS L-DLPFC (F3 anodal 2 mA) + TPS DLPFC L 4 Hz 800 pulses + taVNS 30 min + CES daily + antidepressant concurrent"],
    ["Tremor predominant (Tremor phenotype)", "tDCS M1 bilateral (C3/C4 1.5 mA) + TPS M1 bilateral 4 Hz 800 pulses (low energy) + taVNS 30 min; DBS referral if refractory"],
    ["Advanced PD (H&Y 4-5)", "CES primary daily + taVNS 20 min + tDCS DLPFC (1 mA 15 min); TPS deferred; caregiver-supported; physiotherapy bed/chair programme"],
    ["Motor + cognitive combined (all phenotypes)", "Full S-O-Z-O: taVNS 30 min → tDCS M1+DLPFC dual-channel → TPS M1+SMA+DLPFC 4 Hz 10,000 pulses → physiotherapy + cognitive training O2"],
    ["Maintenance / prevention of decline (stable PD)", "PlatoScience home tDCS C3/C4 1 mA 20 min 3×/week + weekly taVNS + home physiotherapy exercise programme"],
  ],

  polarityPrincipleText: "In PD according to the SOZO FNON concept: Anode is applied over M1 bilateral (C3/C4) to facilitate the hypoactive motor cortex, counteracting beta-band excess in the cortico-striatal motor loop. This is the most evidence-based and replicated tDCS montage for PD across multiple RCTs and meta-analyses. For cognitive/MCI phenotype, bilateral DLPFC anodal stimulation (F3/F4) is used. For freezing of gait, SMA (Cz) anodal is added or substituted. The cathode is placed extracephalically (Oz or shoulder) to avoid competing inhibition of motor targets. Bilateral M1 stimulation (C3/C4 anodal simultaneously) is preferred for PD given the bilateral motor circuit involvement, even when clinical symptoms are asymmetric.",
  polarityTable: [
    ["Hypoactive M1 bilateral (motor predominant)", "Anodes C3/C4 bilateral; Cathode Oz or extracephalic"],
    ["Hypoactive SMA (freezing of gait dominant)", "Anode Cz (SMA); Cathode Oz or extracephalic; combine with C3/C4 if motor also impaired"],
    ["Hypoactive DLPFC (cognitive / MCI phenotype)", "Bilateral anodes F3+F4 (HDCkit dual-channel at 2 mA each); Cathode Oz"],
    ["Depression comorbid (L-DLPFC dominant)", "Anode F3; Cathode F4 or Fp2 (classical antidepressant montage)"],
    ["Autonomic/insula dominant (autonomic phenotype)", "Anode C3/C4 (insula-M1); Cathode Oz; taVNS primary"],
  ],
  classicTdcsProtocols: [
    ["C1", "Motor facilitation bilateral (Motor Predominant)", "C3/C4 bilateral (M1)", "Oz or extracephalic bilateral", "2 mA, 20 min, 10–12 sessions; coordinate with levodopa ON state", "Level B; multiple RCTs and meta-analysis (Lefaucheur 2017; Benninger 2010; Broeder 2015)"],
    ["C2", "Anodal L-DLPFC cognitive (Cognitive/MCI Phenotype)", "F3 (L-DLPFC)", "Fp2 or extracephalic", "2 mA, 20 min, 10 sessions; cognitive tasks concurrent", "Level B; PD-MCI evidence (Brugger 2010; Nombela 2016)"],
    ["C3", "SMA gait initiation (FoG Phenotype)", "Cz (SMA)", "Oz or extracephalic", "2 mA, 20 min; RAS gait training concurrent during stimulation", "Level C; emerging FoG evidence (Giladi 2008; Naro 2019)"],
    ["C4", "Bilateral DLPFC cognitive (MCI/Advanced Cognitive)", "F3/F4 bilateral (HDCkit dual-channel)", "Oz", "2 mA/channel, 20–25 min, 10 sessions", "Level B; dual-channel superior for bilateral DLPFC (Brugger 2010)"],
    ["C5", "Motor + cognitive unified (Full SOZO M1+DLPFC)", "C3/F3 anodes (M1 L + DLPFC L) — HDCkit dual", "Oz/C4", "2 mA each channel, 20 min; dual-task exercise concurrent", "Level C; motor-cognitive unified approach (Benninger 2010; Nombela 2016)"],
    ["C6", "L-DLPFC antidepressant (Depression Comorbid)", "F3 (L-DLPFC)", "F4 (R-DLPFC) or Fp2", "2 mA, 20–30 min, 10–15 sessions; antidepressant montage", "Level B; PD depression evidence (Rosenblum 2013; Brunoni 2016)"],
    ["C7", "M1 bilateral low-intensity (Advanced / Tremor)", "C3/C4 bilateral (M1)", "Oz or extracephalic", "1–1.5 mA, 15 min, 10 sessions; for tremor or H&Y 4 patients", "Level C; tolerability-adapted protocol (Benninger 2010)"],
    ["C8", "Maintenance M1 (home-based protocol)", "C3/C4 (M1) — PlatoScience home device", "Oz or shoulder", "1 mA, 20 min, 3× per week (home protocol prescribed by Doctor)", "Level C; maintenance of motor benefit (Broeder 2015)"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Motor predominant (PMN hypo dominant)", "Primary Motor Network hypoactivation — M1/SMA beta-band excess and cortical excitability deficit", "Anodes C3/C4 bilateral (M1; HDCkit dual-channel 2 mA each); Cathode Oz; physiotherapy concurrent during stimulation", "Upregulate M1 bilateral excitability; reduce beta-band dominance; facilitate corticospinal motor output; pair with active motor tasks for LTP potentiation"],
    ["F2", "Executive / cognitive PD (CEN hypo dominant)", "Executive Control Network hypoactivation — DLPFC-PPC disconnection in PD-MCI; cholinergic deficit", "Bilateral anodes F3+F4 (HDCkit dual-channel 2 mA each); Cathode Pz or Oz; N-back and executive tasks concurrent", "Restore DLPFC-PPC CEN connectivity; improve working memory and cognitive flexibility; reduce DMN intrusion during cognitive-motor dual tasks"],
    ["F3", "Gait freezing / SMA circuit (FoG dominant)", "SMA-BG circuit failure — reduced SMA excitability and SMA-M1 coupling for movement initiation", "Anode Cz (SMA) + C3/C4 (M1) dual-channel; Cathode Oz; RAS (Rhythmic Auditory Stimulation) gait training concurrent", "Facilitate SMA and M1 bilateral for movement initiation; reduce FoG episodes; pair with cueing-based gait training for SMA-motor circuit LTP"],
    ["F4", "Autonomic / insula dominant (Autonomic phenotype)", "Autonomic Network dysregulation — insula-ACC-brainstem impairment; reduced vagal tone; orthostatic hypotension", "Anode C3/C4 (insula-M1 approach); Cathode Oz; taVNS extended 40 min primary; HRV biofeedback concurrent", "Modulate insula-autonomic circuit; taVNS is primary modality; tDCS supportive for central autonomic regulation; HRV biofeedback enhances vagal tone"],
    ["F5", "Depression-motor PD (LIMBIC-motor overlap)", "L-DLPFC hypoactivation + LIMBIC-motor overlap in PD depression — distinct from MDD; dopaminergic-serotonergic interaction", "Anode F3 (L-DLPFC); Cathode F4 or Fp2; taVNS 30 min; CES daily; antidepressant medication concurrent", "L-DLPFC facilitation for PD depression; taVNS serotonergic modulation; CES supportive; coordinate with antidepressant regime and PD medication timing"],
    ["F6", "Full motor + cognitive SOZO protocol (all phenotypes)", "Multi-network dysfunction — PMN + CEN combined deficit; both motor and cognitive symptoms warrant simultaneous addressing", "HDCkit dual: Anode C3+F3 (M1 L + DLPFC L) 2 mA each; Cathode C4+Oz; physiotherapy + cognitive training concurrent dual-task", "Simultaneous M1 and DLPFC facilitation; dual-task motor-cognitive training maximises LTP across both motor and executive networks; optimal for PD with motor + MCI comorbidity"],
  ],
  classicTpsProtocols: [
    ["T1", "Motor predominant PD", "M1 bilateral + SMA", "4 Hz; 0.25 mJ/mm²; 12 sessions/4 weeks (3 sessions/week)", "5,000 M1 bilateral (2,500 each) + 5,000 SMA/premotor = 10,000 total; 25–30 min/session", "Emerging (Feusner 2023; TPS PD pilot data)"],
    ["T2", "Cognitive / MCI dominant", "DLPFC bilateral + PPC", "4 Hz; 0.25 mJ/mm²; 12 sessions", "5,000 DLPFC bilateral (2,500 each) + 3,000 PPC + 2,000 SMA = 10,000 total", "Emerging"],
    ["T3", "Freezing of gait dominant", "SMA + M1 + DLPFC", "4 Hz; 0.25 mJ/mm²; 12 sessions", "4,000 SMA/premotor + 3,500 M1 bilateral + 2,500 DLPFC = 10,000 total", "Emerging"],
    ["T4", "Depression comorbid PD", "L-DLPFC + M1 bilateral", "4 Hz; 0.25 mJ/mm²; 12 sessions", "4,000 L-DLPFC + 3,000 M1 bilateral + 3,000 M1+SMA = 10,000 total", "Emerging"],
    ["T5", "Comprehensive PD (motor + cognitive + mood)", "M1 + SMA + DLPFC bilateral (Holocranial approach)", "4 Hz; 0.25 mJ/mm²; 12 sessions", "3,000 M1 bilateral + 3,000 SMA + 2,000 DLPFC L + 2,000 DLPFC R = 10,000 total", "Emerging"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Motor Predominant", "Primary Motor Network hypoactivation — M1/SMA bilateral", "M1 bilateral (C3/C4) + SMA (Cz)", "2,500 M1 L + 2,500 M1 R + 5,000 SMA/premotor = 10,000 total; 4 Hz 0.25 mJ/mm²", "12 sessions/4 wks"],
    ["FT2", "Cognitive / MCI Dominant", "CEN hypofunction — DLPFC-PPC", "DLPFC bilateral (F3/F4) + PPC (P3/P4)", "2,500 DLPFC L + 2,500 DLPFC R + 2,500 PPC L + 2,500 PPC R = 10,000 total; 4 Hz 0.25 mJ/mm²", "12 sessions/4 wks"],
    ["FT3", "Freezing of Gait", "SMA-BG circuit failure; SMA-M1 disconnection", "SMA (Cz) + M1 bilateral + DLPFC", "3,500 SMA + 3,500 M1 bilateral + 3,000 DLPFC = 10,000 total; 4 Hz 0.25 mJ/mm²", "12 sessions/4 wks"],
    ["FT4", "Depression Comorbid", "DLPFC L hypo + LIMBIC-motor overlap", "DLPFC L (F3) + M1 bilateral + LIMBIC", "4,000 DLPFC L + 3,000 M1 bilateral + 3,000 LIMBIC/temporal = 10,000 total; 4 Hz 0.25 mJ/mm²", "12 sessions/4 wks"],
    ["FT5", "Comprehensive PD Protocol", "Multi-network: PMN + CEN + all phenotypes", "M1 bilateral + SMA + DLPFC bilateral (NEUROLITH 4 Hz full protocol)", "2,500 M1 L + 2,500 M1 R + 2,500 SMA + 1,500 DLPFC L + 1,000 DLPFC R = 10,000 total; 4 Hz 0.25 mJ/mm²; 25–30 min", "12 sessions/4 wks"],
  ],
};
