'use strict';
module.exports = {
  conditionFull: "Post-Traumatic Stress Disorder (PTSD)",
  conditionShort: "PTSD",
  conditionSlug: "ptsd",
  documentNumber: "SOZO-PTSD-PROT-001",
  offLabelCoverText: "tDCS and TPS use in PTSD is INVESTIGATIONAL / OFF-LABEL. Level C–B emerging evidence supports tDCS targeting DLPFC for PTSD symptom reduction.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level C–B emerging evidence for PTSD', 'Standard informed consent + off-label note; trauma-informed approach'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; growing evidence for PTSD and anxiety/arousal', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia — directly relevant to PTSD symptoms', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of PTSD (DSM-5 / ICD-11) by a qualified psychiatrist or clinical psychologist",
    "PCL-5 score ≥33 or CAPS-5 indicating at least moderate PTSD severity at baseline",
    "Age 18–70 years (exceptions at Doctor discretion with documented rationale)",
    "Engaged with or referred for evidence-based trauma therapy (PE, CPT, EMDR) — FNON is adjunctive to trauma therapy",
    "Stable pharmacological treatment for ≥4 weeks prior to enrolment, or actively managed by prescribing Doctor",
    "Capacity to provide informed consent in a stabilised state (not in acute dissociation or crisis)",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Active acute suicidal ideation with intent requiring inpatient management",
    "Active substance misuse disorder in acute phase — stabilise before enrolment",
    "Active psychosis or severe dissociative disorder incompatible with safe participation",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Complex PTSD (ICD-11) — may require extended stabilisation phase; DBT or phase-based trauma therapy preferred",
    "Comorbid borderline personality disorder — careful assessment; stabilisation phase required",
    "Comorbid MDD with active suicidal ideation — psychiatric management review before enrolment",
    "Cardiac pacemaker or defibrillator — individual risk-benefit assessment",
    "Epilepsy or seizure history — formal risk assessment required",
    "Military/combat PTSD with traumatic brain injury comorbidity — see TBI protocol; dual protocol consideration",
    "Dissociative PTSD subtype — grounding techniques essential; taVNS may initially worsen dissociation — monitor carefully",
    "Childhood trauma / complex developmental trauma — longer stabilisation phase; trauma-informed modifications throughout",
    "Substance misuse remission — careful assessment of triggers and coping strategies",
  ],

  overviewParagraph: "Post-Traumatic Stress Disorder (PTSD) affects approximately 20% of trauma-exposed individuals, with lifetime prevalence of approximately 7–8% in the general population and substantially higher rates in military veterans, first responders, and survivors of sexual assault or serious accidents. PTSD is characterised by four symptom clusters: intrusive re-experiencing (flashbacks, nightmares), avoidance, negative alterations in cognition and mood, and hyperarousal/hyperreactivity. PTSD produces significant disability, impairs quality of life, and is associated with high rates of depression, anxiety, substance use disorders, and suicide risk. Evidence-based psychotherapies (Prolonged Exposure — PE, Cognitive Processing Therapy — CPT, EMDR) are effective for approximately 50–60% of patients but leave a substantial proportion with residual or treatment-refractory symptoms. Non-invasive brain stimulation, particularly tDCS and taVNS, is emerging as a promising adjunct to trauma-focused psychotherapy by directly modulating the fear extinction and emotional regulation circuits that underlie PTSD recovery.",
  fnonNetworkParagraph: "PTSD is a disorder of fear memory dysregulation and impaired extinction learning. The FNON framework identifies the core circuit-level pathology: hyperactive amygdala-SN threat detection circuit, insufficient vmPFC/DLPFC extinction recall and top-down regulatory control, and hippocampal contextual fear generalisation impairment. SOZO targets this triad by upregulating prefrontal-vmPFC regulatory control via tDCS/TPS, directly modulating the amygdala-autonomic axis via taVNS, and using CES to reduce hyperarousal. The critical principle is that tDCS/taVNS administered during concurrent trauma-focused therapy amplifies extinction learning and consolidation.",
  networkDisorderParagraphs: [
    "Neuroimaging research has established the core circuit-level model of PTSD: amygdala hyperreactivity to trauma cues and safety signals alike (failure to discriminate between threat and safety contexts), reduced vmPFC activation (impaired extinction memory recall and fear inhibition), reduced hippocampal volume and function (contextual fear generalisation — cannot identify safe contexts), and hyperactive dACC (persistent threat monitoring and error signalling). This triad — amygdala hyperactivation, vmPFC hypoactivation, and hippocampal contextual processing impairment — maps directly onto the neurobiology of impaired fear extinction that underlies PTSD persistence.",
    "The Salience Network (SN) in PTSD is chronically biased toward threat detection: the dACC-insula-amygdala circuit shows enhanced reactivity to ambiguous stimuli and impaired habituation. The Central Executive Network (CEN) — particularly the DLPFC and vmPFC — shows reduced activation during emotional regulation and extinction recall, failing to provide adequate top-down suppression of amygdala reactivity. This CEN hypoactivation-SN hyperactivation imbalance is the neurophysiological architecture of PTSD symptomatology.",
    "Chronic PTSD is associated with autonomic nervous system dysregulation — elevated sympathetic tone, reduced HRV, hyperactivation of the LC-NE arousal system, and impaired parasympathetic recovery. This autonomic hyperarousal is both a symptom of PTSD (hyperarousal cluster) and a perpetuating mechanism that reinforces fear conditioning and reduces capacity for extinction learning. taVNS directly targets this autonomic dysregulation via the NTS-LC pathway, promoting parasympathetic recovery and reducing amygdala reactivity via the NTS-amygdala projection, providing a dual neurophysiological mechanism for PTSD treatment.",
  ],

  pathophysiologyText: "PTSD pathophysiology involves dysregulation across multiple neurobiological systems: (1) HPA axis hyperactivation — elevated CRF, enhanced cortisol stress reactivity, and glucocorticoid hypersensitivity; (2) noradrenergic hyperactivity — LC-NE hyperactivation perpetuating hyperarousal, startle responses, and sleep disturbance; (3) amygdala hyperreactivity — enhanced fear conditioning and threat generalisation via LTP-like synaptic potentiation; (4) hippocampal volume reduction — bilateral hippocampal atrophy impairing contextual fear discrimination and extinction memory consolidation; (5) vmPFC/DLPFC hypoactivation — reduced top-down regulatory control of amygdala and impaired extinction recall; (6) impaired endocannabinoid signalling — CB1 receptor deficits in amygdala and PFC impairing extinction; (7) epigenetic modifications — trauma-induced gene expression changes in glucocorticoid receptor genes and BDNF affecting plasticity; (8) serotonergic dysregulation affecting mood, sleep, and impulse control.",
  cardinalSymptoms: [
    ["Re-experiencing / Intrusions", "Involuntary traumatic memories, nightmares, flashbacks, psychological and physiological reactivity to trauma cues; uncontrolled memory activation", "Core criterion Cluster B (100% by DSM-5 definition)", "American Psychiatric Association, 2022"],
    ["Avoidance", "Effortful avoidance of trauma-related memories, thoughts, feelings, external reminders; functional impairment; safety behaviours perpetuating PTSD", "Core criterion Cluster C (100%)", "American Psychiatric Association, 2022"],
    ["Negative Cognitions/Mood", "Persistent negative beliefs about self/world; distorted blame; persistent negative emotions; diminished interest; emotional numbing; estrangement", "Core criterion Cluster D (100%)", "American Psychiatric Association, 2022"],
    ["Hyperarousal", "Hypervigilance, exaggerated startle, sleep disturbance, irritability/anger, reckless behaviour, concentration difficulties; chronic sympathetic activation", "Core criterion Cluster E (100%)", "American Psychiatric Association, 2022"],
    ["Dissociation", "Depersonalisation, derealisation, emotional numbing; dissociative subtype in 15–30% PTSD; amygdala-vmPFC oscillation disruption", "~25–30% PTSD (dissociative subtype)", "Lanius et al., 2010"],
    ["Sleep Disturbance", "Trauma-related nightmares; insomnia; night sweats; hyperarousal preventing sleep; REM sleep abnormalities; sleep terror", "~70–90%", "Pigeon et al., 2011"],
    ["Anger/Irritability", "Persistent irritability; anger outbursts; reactive aggression; emotional dysregulation; OFC-amygdala pathway dysfunction", "~60–70%", "Orth & Wieland, 2006"],
    ["Concentration Difficulty", "Difficulty sustaining attention; impaired working memory; CEN hypoactivation competing with intrusive memories and hyperarousal", "~60–70%", "Scott et al., 2015"],
    ["Guilt/Shame", "Excessive guilt about traumatic event; shame about reactions; self-blame; perpetuating cognitive distortions; DLPFC-limbic circuit", "~50–70%", "Bryan et al., 2018"],
    ["Emotional Numbing", "Restricted range of emotions; inability to experience positive emotions; emotional anhedonia; limbic suppression variant", "~50–60%", "Foa et al., 1999"],
    ["Social Isolation", "Withdrawal from relationships; avoidance of social situations as trauma reminders; interpersonal estrangement; functional social impairment", "~60%", "Taft et al., 2007"],
    ["Physical Symptoms", "Chronic pain, headaches, GI symptoms, cardiovascular; somatisation of trauma; autonomic dysregulation; central sensitisation overlap", "~40–60%", "Boscarino, 2004"],
    ["Moral Injury", "Profound distress from acts that violate personal moral code; guilt, shame, spiritual crisis; particularly military PTSD; frontal-limbic moral circuit", "~20–30% combat PTSD", "Litz et al., 2009"],
  ],
  standardGuidelinesText: [
    "Evidence-based psychotherapies for PTSD have the strongest evidence and are recommended as first-line by NICE (2018), VA/DoD (2017), ISTSS (2019), and APA (2017). Trauma-focused cognitive behavioural therapies — Prolonged Exposure (PE), Cognitive Processing Therapy (CPT), and Trauma-Focused CBT (TF-CBT) for children — have the most robust evidence base (Level A). EMDR (Eye Movement Desensitisation and Reprocessing) also has Level A evidence. These therapies directly target the fear memory dysregulation and avoidance maintenance that perpetuate PTSD.",
    "Pharmacotherapy with SSRIs (sertraline — FDA-approved; paroxetine — FDA-approved) and SNRIs (venlafaxine — recommended by multiple guidelines) provides symptom reduction as an adjunct to psychotherapy or when psychotherapy is unavailable. Prazosin (alpha-1 adrenergic antagonist) has evidence for PTSD nightmares. Benzodiazepines are not recommended for PTSD. Emerging treatments include MDMA-assisted therapy (Breakthrough Therapy Designation), ketamine, and stellate ganglion block.",
    "SOZO FNON protocols are adjuncts to evidence-based trauma-focused psychotherapy, not standalone treatments. The critical FNON principle for PTSD is pairing stimulation with extinction learning during trauma therapy: tDCS/TPS during PE or CPT exposure components amplifies extinction memory consolidation, while taVNS reduces sympathetic hyperarousal to improve trauma processing window. The Doctor coordinates closely with the treating trauma therapist.",
  ],

  fnonFrameworkParagraph: "The FNON framework for PTSD directly targets the three-node PTSD circuit: (1) anodal tDCS/TPS to vmPFC and DLPFC upregulates extinction recall and top-down amygdala regulation; (2) taVNS modulates the amygdala directly via NTS-amygdala projections and reduces LC-NE hyperarousal underlying hypervigilance and startle; (3) CES provides broad-spectrum hyperarousal reduction. All modalities are timed around trauma therapy sessions to maximise extinction consolidation in the post-stimulation plasticity window.",
  keyBrainRegions: [
    ["Ventromedial Prefrontal Cortex (vmPFC)", "Extinction memory recall; fear inhibition; safety signal encoding; hypoactivation impairs ability to recall safety in threatening contexts; IL-vmPFC conditioned inhibition of amygdala", "PRIMARY EXTINCTION TARGET: anodal tDCS F3/Fz (vmPFC-mPFC region); TPS vmPFC for deep extinction circuit; critical for PE/CPT therapy enhancement", "Milad & Quirk, 2012; Rauch et al., 2006"],
    ["Amygdala", "Fear memory storage and expression; hyperreactivity to trauma cues; bilateral hyperactivation; impaired extinction; conditioned fear perpetuation", "Indirect suppression via vmPFC anodal tDCS top-down regulation; TPS temporal-amygdala region; taVNS NTS-amygdala modulation — primary direct amygdala modulatory mechanism", "Shin et al., 2006; Etkin & Wager, 2007"],
    ["Dorsolateral Prefrontal Cortex (DLPFC)", "Cognitive control of fear responses; working memory under threat; impaired top-down regulation; conflict resolution between safety and threat appraisal", "Anodal tDCS F3 (left DLPFC) for cognitive control enhancement; bilateral F3/F4 for combined hyperarousal + cognitive; TPS DLPFC", "Shin et al., 2006; Hariri et al., 2003"],
    ["Hippocampus", "Contextual fear conditioning; contextual safety discrimination; extinction memory consolidation; bilateral volume reduction in PTSD", "TPS hippocampal targeting for contextual fear discrimination; taVNS BDNF hippocampal neuroplasticity; promotes extinction context specificity", "Bremner, 2006; Kitayama et al., 2005"],
    ["Dorsal Anterior Cingulate Cortex (dACC)", "Threat monitoring; conditioned fear expression; hyperactivation in PTSD; startle response potentiation; moral injury processing", "tDCS Fz for dACC normalisation; taVNS modulates dACC via vagal-cingulate pathway; combined with fear expression reduction during PE", "Shin et al., 2001"],
    ["Anterior Insula", "Interoceptive fear amplification; threat-related bodily sensations; SN hyperactivity; body-based PTSD symptoms", "TPS anterior insula; taVNS insular modulation via NTS pathway; body-focused trauma approaches (somatic experiencing) concurrent", "Paulus & Stein, 2006; Etkin & Wager, 2007"],
    ["Posterior Hippocampus", "Spatial context memory; extinction context specificity — PTSD patients generalise fear across safe contexts due to posterior hippocampal impairment", "TPS posterior hippocampal region; taVNS promotes hippocampal neuroplasticity for context discrimination recovery", "Ji & Bhagya, 2017"],
    ["Orbitofrontal Cortex (OFC)", "Reward-threat value updating; flexible appraisal of threat vs. safety; impaired in PTSD contributing to perseverative threat evaluation", "TPS OFC; anodal tDCS bilateral prefrontal includes OFC modulation; OFC-IL pathway for extinction consolidation", "Milad & Quirk, 2012"],
    ["Locus Coeruleus (LC)", "Hyperactivation in PTSD; excessive NE release perpetuating hyperarousal, hypervigilance, and startle; sleep disturbance substrate", "taVNS→NTS→LC — normalises NE tone via adaptive LC downregulation with repeated stimulation; prazosin mechanism comparison", "Bremner et al., 1996; Southwick et al., 1999"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Primary vagal relay; direct connection to amygdala via NTS-amygdala pathway; primary taVNS mechanism for PTSD fear modulation", "taVNS NTS activation → NTS-amygdala → direct amygdala fear modulation; most direct neuromodulatory pathway for PTSD", "Fang et al., 2016; Rembado et al., 2021"],
    ["Bed Nucleus of Stria Terminalis (BNST)", "Sustained anxiety and contextual fear; 'anxiety' versus phasic 'fear' of amygdala; key PTSD hyperarousal substrate; extends amygdala complex", "Indirect modulation via taVNS and amygdala projections; TPS deep temporal-BNST targeting", "Davis et al., 2010"],
    ["Subgenual ACC (sgACC)", "Negative affect processing; DMN emotional node; antidepressant target — hyperactive in PTSD depression comorbidity", "TPS sgACC via vmPFC trajectory; taVNS modulates sgACC via NTS-LC-sgACC pathway", "Mayberg et al., 2005"],
    ["Periaqueductal Gray (PAG)", "Defensive responses (freeze, flight, fight); activated in PTSD trauma cue responses; moral injury processing", "Indirect modulation via taVNS NTS-PAG pathway; reduces defensive state reactivity over repeated sessions", "Bandler et al., 2000"],
    ["Raphe Nuclei", "Serotonergic mood and impulse regulation; reduced 5-HT tone in PTSD contributing to aggression and mood dysregulation", "taVNS modulates serotonergic raphe via brainstem connections; CES may enhance 5-HT tone", "Davis et al., 2010"],
    ["Thalamus", "Sensory relay; 'sensory gating' impairment in PTSD allows trauma-related stimuli to overwhelm cortical processing", "TPS thalamic indirect targeting; taVNS modulates thalamo-cortical synchrony; improved sensory gating with regular stimulation", "Bhagya et al., 2015"],
    ["Stellate Ganglion", "Cervical sympathetic ganglion; proposed mechanism for stellate ganglion block (SGB) in military PTSD — indirect taVNS analogy", "taVNS provides a non-invasive alternative to SGB via cervical vagal trunk-sympathetic interactions", "Mulvaney et al., 2014"],
  ],
  keyFunctionalNetworks: [
    ["Salience Network (SN) / Threat Circuit", "dACC, anterior insula, amygdala, BNST, thalamus", "Hyperactivation; excessive threat detection; generalised threat reactivity; impaired habituation; hypervigilance substrate", "taVNS PRIMARY for SN-amygdala modulation; tDCS Fz (dACC); TPS temporal; cathodal right temporal reduces SN hyperactivity", "Lanius et al., 2010; Etkin & Wager, 2007"],
    ["Central Executive Network (CEN)", "DLPFC, vmPFC, PPC, OFC", "Hypoactivation; insufficient top-down suppression of amygdala; impaired extinction recall; cognitive fear regulation deficit", "PRIMARY: anodal tDCS F3/Fz (vmPFC+DLPFC); TPS vmPFC+DLPFC; bilateral for combined hyperarousal+cognitive PTSD", "Shin et al., 2006; Hariri et al., 2003"],
    ["Default Mode Network (DMN)", "mPFC, PCC, hippocampus, angular gyrus", "Disrupted in PTSD; intrusive memories involve DMN activation; trauma-relevant self-referential processing", "Cathodal Pz (if DMN intrusion dominant); anodal vmPFC supports DMN reorganisation around safety memories", "Lanius et al., 2015"],
    ["Fear Extinction Circuit", "vmPFC (IL), hippocampus, amygdala (BA)", "Core PTSD neurophysiological deficit — impaired extinction memory consolidation and recall; safety learning impairment", "PRIMARY MECHANISTIC TARGET: anodal vmPFC+DLPFC tDCS during PE/CPT exposure; TPS vmPFC for deep extinction circuit; hippocampal TPS for contextual specificity", "Milad & Quirk, 2012; Rauch et al., 2006"],
    ["Autonomic Network", "NTS, LC, amygdala, insula, ACC, hypothalamus, BNST", "Chronic sympathetic hyperactivation; reduced HRV; impaired parasympathetic recovery; NE hyperarousal perpetuating PTSD", "taVNS PRIMARY for autonomic rebalancing — restores vagal tone, reduces LC-NE hyperarousal; CES for broad arousal modulation", "Bremner et al., 1996; Thayer et al., 2012"],
    ["Memory Consolidation Network", "Hippocampus, amygdala, PCC, mPFC, thalamus", "Trauma memory dysregulation; intrusive trauma memory re-activation; impaired extinction memory consolidation; hippocampal-amygdala balance", "TPS hippocampal for extinction memory consolidation; taVNS BDNF for hippocampal neuroplasticity; paired with trauma therapy exposure sessions", "Bremner, 2006; Kitayama et al., 2005"],
    ["Interoceptive Network", "Anterior insula, mid-insula, ACC, brainstem", "Hyperactivation; amplified body-based fear responses; somatic PTSD symptoms; body-scan hypervigilance", "TPS anterior insula; taVNS via NTS-insular pathway; somatic-focused therapy concurrent (somatic experiencing)", "Paulus & Stein, 2006"],
  ],
  networkAbnormalities: "PTSD is characterised by amygdala-SN hyperactivation (threat circuit hyperreactivity), vmPFC/CEN hypoactivation (extinction recall and top-down regulation failure), hippocampal volume reduction and contextual fear generalisation, and chronic autonomic hyperarousal via LC-NE overactivation. The fear extinction circuit impairment is the primary FNON target.",
  conceptualFramework: "SOZO FNON PTSD protocol: (1) Upregulate vmPFC/DLPFC extinction recall circuit via anodal tDCS/TPS (timed during exposure therapy); (2) Modulate amygdala-autonomic hyperreactivity via taVNS; (3) Reduce hyperarousal via CES; (4) Pair stimulation with trauma-focused therapy exposure to amplify extinction learning and consolidation in the post-stimulation plasticity window.",

  clinicalPhenotypes: [
    ["Classic PTSD (All 4 Clusters)", "Full PTSD presentation; vmPFC/DLPFC primary target; taVNS primary for hyperarousal; paired with PE or CPT therapy", "American Psychiatric Association, 2022"],
    ["Hyperarousal-Dominant PTSD", "Hypervigilance, exaggerated startle, irritability, sleep disruption primary; LC-NE hyperactivation dominant; taVNS + CES primary; careful tDCS parameters", "Bremner et al., 1996"],
    ["Dissociative PTSD Subtype", "Depersonalisation/derealisation; emotional numbing; over-regulation of amygdala by vmPFC; different neurobiology to hyperarousal type; taVNS careful introduction; grounding first", "Lanius et al., 2010"],
    ["Complex PTSD (ICD-11)", "Disturbed self-organisation; affect dysregulation; negative self-concept; interpersonal difficulties; longer stabilisation; phase-based approach; DBT foundation", "Herman, 1992"],
    ["Military/Combat PTSD", "Combat trauma; moral injury; TBI comorbidity common; isolation; cultural considerations; bilateral DLPFC+vmPFC; taVNS primary; see TBI protocol if applicable", "Hoge et al., 2004"],
    ["PTSD + MDD Comorbidity", "Dual diagnosis; anhedonia + PTSD symptoms; bilateral DLPFC (MDD component) + vmPFC (PTSD extinction); combined pharmacotherapy", "Brady & Clancy, 2018"],
    ["PTSD + Substance Use Comorbidity", "Addiction-trauma comorbidity; stabilisation required; taVNS helpful for craving and autonomic dysregulation; trauma therapy modified", "Brady et al., 2004"],
    ["Treatment-Resistant PTSD", "Non-responder to ≥2 adequate trauma therapy trials; bilateral DLPFC+vmPFC maximum; intensive taVNS + CES; consider MDMA-assisted therapy referral", "Steenkamp et al., 2015"],
    ["Childhood Trauma / Complex Developmental", "Early adverse experiences; chronic complex trauma; long stabilisation phase; gentle approach; build safety before exposure; CES/taVNS primary initially", "Teicher et al., 2016"],
  ],
  symptomNetworkMapping: [
    ["Intrusions / Flashbacks", "Fear extinction circuit failure", "Hippocampal-amygdala dysregulation", "tDCS vmPFC/F3 anodal during PE exposure", "Prolonged Exposure (PE) concurrent — extinction consolidation"],
    ["Avoidance", "CEN hypoactivation + amygdala avoidance drive", "vmPFC-amygdala inhibition failure", "tDCS F3/Fz anodal + taVNS", "PE/CPT exposure therapy concurrent"],
    ["Negative Cognitions", "CEN-vmPFC hypoactivation", "DLPFC cognitive appraisal deficit", "tDCS F3 anodal bilateral", "CPT cognitive restructuring concurrent"],
    ["Hyperarousal / Hypervigilance", "SN/LC hyperactivation", "Amygdala-BNST sustained threat circuit", "taVNS PRIMARY + CES (primary for hyperarousal)", "Relaxation + grounding concurrent"],
    ["Sleep Disturbance", "LC hyperactivation + autonomic dysregulation", "HPA-NE hyperarousal at night", "CES 60min evening + taVNS pre-sleep", "Sleep hygiene + imagery rehearsal therapy"],
    ["Anger/Irritability", "Amygdala-OFC dysregulation", "Frontal-limbic top-down deficit", "tDCS F3+F4 bilateral anodal", "Anger management + DBT emotional regulation"],
    ["Dissociation", "vmPFC over-regulation of amygdala", "Limbic-cortical oscillation disruption", "taVNS gradual introduction + CES (careful with tDCS)", "Grounding techniques; somatic stabilisation first"],
    ["Concentration", "CEN hypoactivation", "SN-intrusion competing with attention", "tDCS F3 anodal + Pz cathodal", "Attention training concurrent"],
    ["Autonomic Dysregulation", "Autonomic network (LC-NE-ANS)", "Parasympathetic suppression", "taVNS PRIMARY 40min + CES 60min", "HRV biofeedback concurrent"],
    ["Moral Injury / Guilt", "vmPFC-OFC moral circuit", "Frontal-limbic self-referential moral processing", "TPS vmPFC/OFC + tDCS F3 anodal", "CPT trauma account and cognitive restructuring"],
  ],
  montageSelectionRows: [
    ["Classic PTSD (vmPFC + DLPFC focus)", "Anodal F3/Fz + Pz cathodal — 2mA 20min (vmPFC-DLPFC upregulation)"],
    ["Hyperarousal-dominant (taVNS primary)", "taVNS bilateral cymba 0.5mA 30–40min (PRIMARY for hyperarousal)"],
    ["Hyperarousal with cognitive component", "taVNS 30min + tDCS F4 anodal 1.5mA 15min (conservative)"],
    ["CES for hyperarousal and sleep", "Alpha-Stim AID 0.5mA 60min (evening for sleep; daytime for hyperarousal)"],
    ["Dissociative subtype (careful)", "CES 0.5mA 30min first; taVNS low intensity gradual; tDCS deferred until stable"],
    ["Military/Combat PTSD (bilateral)", "Anodal F3+F4 bilateral 1.5mA 20min + taVNS + CES"],
    ["TPS vmPFC (extinction circuit)", "NEUROLITH® vmPFC/mPFC region 0.2mJ/mm² 3000 pulses (during PE session)"],
    ["TPS hippocampal (contextual fear)", "NEUROLITH® hippocampal region 0.2mJ/mm² 3000 pulses + taVNS"],
    ["Complex PTSD (stabilisation phase)", "CES + taVNS ONLY until stabilised; tDCS/TPS deferred to Phase 2"],
    ["Treatment-resistant PTSD (maximal)", "HDCkit bilateral F3+Fz + TPS vmPFC+DLPFC + taVNS 40min"],
    ["PTSD + MDD comorbidity", "tDCS bilateral F3+F4 + taVNS + CES (combined PTSD-MDD protocol)"],
    ["Paired trauma therapy (during PE)", "tDCS F3/Fz anodal 2mA 20min DURING exposure session (concurrent)"],
    ["Maintenance phase", "taVNS 3×/week; CES daily home; tDCS 2×/week during therapy sessions"],
  ],
  polarityPrincipleText: "PTSD stimulation polarity targets the extinction recall and emotional regulation deficit. vmPFC/medial-frontal anodal stimulation (Fz/F3) is the primary approach — upregulating extinction memory consolidation and top-down amygdala regulation. For hyperarousal-dominant, taVNS takes primacy with conservative tDCS. For dissociative subtype, cathodal vmPFC is CONTRAINDICATED (would worsen over-inhibition) — anodal prefrontal only.",
  polarityTable: [
    ["Anodal Fz/F3 (vmPFC/DLPFC)", "Primary extinction circuit upregulation — enhances extinction memory consolidation during concurrent PE/CPT exposure therapy"],
    ["Anodal F3+F4 bilateral", "Military/complex PTSD and TRD-PTSD — bilateral prefrontal for combined hyperarousal and cognitive components"],
    ["Cathodal Pz", "DMN suppression for intrusion-dominant PTSD — combined with anodal frontal to reduce trauma-memory rumination"],
    ["taVNS bilateral cymba", "Primary for hyperarousal phenotype — amygdala modulation via NTS, LC-NE normalisation, vagal tone restoration"],
    ["CES earclip", "Broad hyperarousal reduction — FDA-cleared for anxiety; primary for sleep disruption cluster; safe for all PTSD phenotypes"],
  ],

  classicTdcsProtocols: [
    ["C1", "PTSD — vmPFC/extinction circuit", "Fz/F3 anodal (vmPFC/DLPFC)", "Pz cathodal", "2mA 20min during trauma therapy session", "Level C-B"],
    ["C2", "Hyperarousal dominant", "F4 anodal (right DLPFC)", "Pz cathodal", "1.5mA 15min + taVNS primary", "Emerging"],
    ["C3", "Bilateral for complex PTSD", "F3+F4 bilateral anodal", "Temporal bilateral cathodal", "1.5mA 20min", "Emerging"],
    ["C4", "PTSD + MDD comorbidity", "F3 anodal + Fz anodal", "Pz cathodal", "2mA 20min", "Level C (MDD component)"],
    ["C5", "Military/combat PTSD", "F3+F4 bilateral anodal", "Bilateral SO cathodal", "2mA 20min", "Exploratory"],
    ["C6", "Intrusion reduction (PE paired)", "Fz anodal during PE exposure", "Pz cathodal", "2mA 20min concurrent with exposure", "Emerging"],
    ["C7", "Nightmares / sleep disruption", "Fz anodal (daytime) + CES evening", "Pz cathodal", "1.5mA 20min + CES 60min", "Exploratory"],
    ["C8", "Dissociative subtype (cautious)", "F3 anodal only (conservative)", "Fz cathodal (avoid Pz)", "1mA 15min (conservative)", "Exploratory"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Classic PTSD (fear extinction)", "vmPFC hypoactivation — extinction recall deficit", "Fz/F3 anodal + Pz cathodal + taVNS concurrent during PE", "Extinction circuit upregulation paired with exposure therapy — primary PTSD protocol"],
    ["F2", "Hyperarousal dominant", "SN/LC hyperactivation — autonomic dysregulation", "taVNS PRIMARY + CES 60min + F4 anodal (conservative, secondary)", "Autonomic-first approach for hyperarousal phenotype"],
    ["F3", "Dissociative subtype", "vmPFC over-inhibition of amygdala", "CES + taVNS (stabilisation) — grounded tDCS F3 only if stable", "Stabilisation-first for dissociative; careful phased introduction of tDCS"],
    ["F4", "Complex PTSD (phased)", "Multi-domain dysregulation", "Phase 1: CES+taVNS stabilise. Phase 2: add F3 anodal. Phase 3: TPS", "Phased FNON protocol for complex PTSD — stabilise before stimulate"],
    ["F5", "PTSD + MDD comorbidity", "Bilateral CEN + limbic", "F3+F4 bilateral anodal + taVNS + CES — combined protocol", "Combined PTSD extinction circuit + MDD antidepressant network"],
    ["F6", "Treatment-resistant PTSD", "Multi-network resistance", "HDCkit bilateral Fz+F3+F4 + TPS vmPFC + taVNS 40min", "Maximum multi-modal PTSD network normalisation"],
  ],
  classicTpsProtocols: [
    ["T1", "PTSD extinction circuit", "vmPFC/mPFC deep", "0.2mJ/mm²", "3000 pulses (during or post-PE session)", "Emerging"],
    ["T2", "Hippocampal contextual fear", "Hippocampal region", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T3", "DLPFC cognitive control", "Left DLPFC (F3 region)", "0.2mJ/mm²", "3000 pulses", "Emerging"],
    ["T4", "Combined vmPFC + hippocampal", "vmPFC + hippocampus sequential", "0.2mJ/mm²", "5000 total pulses", "Exploratory"],
    ["T5", "Amygdala-temporal region", "Temporal-amygdala (indirect)", "0.2mJ/mm²", "2000 pulses (conservative)", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Classic PTSD — extinction circuit", "vmPFC extinction recall circuit", "vmPFC/mPFC 0.2mJ/mm² × 3000 during PE session — deep extinction consolidation", "Time with PE exposure session for maximum extinction amplification"],
    ["FT2", "Hippocampal contextual fear", "Hippocampal-fear discrimination circuit", "Hippocampal 0.2mJ/mm² × 3000 + taVNS concurrent", "Deep hippocampal contextual fear discrimination enhancement"],
    ["FT3", "PTSD + MDD comorbidity", "Bilateral CEN + vmPFC", "DLPFC bilateral + vmPFC 0.2mJ/mm² × 5000 total", "Deep bilateral prefrontal for combined PTSD-MDD"],
    ["FT4", "Treatment-resistant PTSD", "Multi-network", "vmPFC + DLPFC bilateral 0.2mJ/mm² × 5000 + hippocampal 2000 = 7000 total", "Maximum deep multi-network PTSD circuit normalisation"],
    ["FT5", "Hyperarousal dominant", "amygdala-temporal (conservative)", "Temporal-amygdala 0.15mJ/mm² × 2000 + taVNS primary", "Conservative temporal with taVNS primary for hyperarousal"],
    ["FT6", "Military/Combat PTSD", "Bilateral vmPFC + DLPFC", "Bilateral DLPFC + vmPFC 0.2mJ/mm² × 5000 + taVNS + CES", "Maximum bilateral combined for combat PTSD with hyperarousal and moral injury"],
    ["FT7", "Complex PTSD (Phase 2 onwards)", "vmPFC-amygdala circuit", "vmPFC 0.2mJ/mm² × 2000 (conservative Phase 2 introduction)", "Phase 2 conservative introduction of TPS after stabilisation"],
    ["FT8", "Sleep-disrupted PTSD", "vmPFC + autonomic", "vmPFC 0.2mJ/mm² × 2000 + CES 60min evening", "Mild deep extinction circuit support + evening autonomic for sleep"],
    ["FT9", "Maintenance PTSD protocol", "vmPFC maintenance", "vmPFC 0.2mJ/mm² × 1500 monthly maintenance", "Monthly extinction circuit maintenance post-active treatment phase"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Classic PTSD (All 4 Clusters)",
      combinations: [
        ["S — Stabilise", "taVNS 30min (pre-therapy session) + CES 30min — establish autonomic window for trauma therapy", "Create therapeutic window by reducing LC-NE hyperarousal and restoring vagal tone before trauma processing"],
        ["O — Optimise", "tDCS Fz/F3 anodal 2mA 20min — upregulate vmPFC extinction circuit", "Prime extinction memory recall and consolidation circuit during or before PE/CPT exposure components"],
        ["Z — Zone", "TPS vmPFC 0.2mJ/mm² 3000 + hippocampal 0.2mJ/mm² 2000 during PE session", "Deep extinction circuit stimulation during active trauma processing — maximum consolidation opportunity"],
        ["O — Outcome", "Prolonged Exposure (PE) or CPT session post-stimulation — consolidation", "Trauma-focused therapy in post-stimulation plasticity window; taVNS during exposure for ongoing autonomic support"],
      ],
    },
    {
      phenotype: "Hyperarousal-Dominant PTSD",
      combinations: [
        ["S — Stabilise", "taVNS 40min — PRIMARY modality for hyperarousal; NTS-LC-NE normalisation and amygdala modulation", "Reduce baseline LC-NE hyperarousal before any cortical stimulation; taVNS is primary intervention for this phenotype"],
        ["O — Optimise", "CES 0.5mA 60min — broad-spectrum hyperarousal and sleep preparation", "Systematic arousal reduction across the session; prepare patient for any cognitive processing"],
        ["Z — Zone", "tDCS F4 anodal 1.5mA 15min (conservative) — right DLPFC emotional regulation", "Conservative cortical stimulation added only after adequate autonomic stabilisation"],
        ["O — Outcome", "HRV biofeedback concurrent + grounding techniques — consolidate", "Autonomic self-regulation training during stabilised state; grounding practices for hypervigilance"],
      ],
    },
    {
      phenotype: "Dissociative PTSD Subtype",
      combinations: [
        ["S — Stabilise", "CES 0.25mA 30min — gentle; grounding-concurrent; assess dissociation level before each session", "VERY gentle stabilisation; assess Window of Tolerance before and during each session; prioritise safety"],
        ["O — Optimise", "taVNS 0.25mA 15min — low intensity introduction; increase gradually over sessions", "Gradual taVNS introduction; monitor for increased dissociation; may need 3–5 sessions at very low intensity before optimising"],
        ["Z — Zone", "tDCS F3 anodal 1mA 10min — conservative; only if stable, grounded", "Very conservative tDCS only if patient firmly grounded; defer TPS to Phase 2 of stabilised treatment"],
        ["O — Outcome", "Somatic grounding techniques concurrent — titrated exposure only when stable", "Grounding, body-based stabilisation; titrated exposure work only when fully stabilised"],
      ],
    },
    {
      phenotype: "Complex PTSD (ICD-11) — Phase 1",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min daily home — primary stabilisation modality Phase 1", "Phase 1: stabilisation only; CES and taVNS for safety, self-regulation, and affect stability"],
        ["O — Optimise", "taVNS 30min 3×/week — autonomic stabilisation and emotional regulation foundation", "Build autonomic regulation capacity as foundation for Phase 2 trauma processing"],
        ["Z — Zone", "No tDCS/TPS in Phase 1 — stabilisation phase only", "Phase 1 FNON = autonomic modulation only; tDCS/TPS introduction deferred to Phase 2 when stable"],
        ["O — Outcome", "DBT skills training concurrent (distress tolerance, mindfulness, emotion regulation) — consolidate", "DBT foundation for self-regulation concurrent with autonomic stabilisation"],
      ],
    },
    {
      phenotype: "Military/Combat PTSD",
      combinations: [
        ["S — Stabilise", "taVNS 40min + CES 60min — maximum autonomic stabilisation for combat hyperarousal", "Address the pronounced LC-NE hyperarousal and sympathetic dominance characteristic of combat PTSD"],
        ["O — Optimise", "tDCS F3+F4 bilateral anodal 1.5mA 20min — bilateral prefrontal for complex combat trauma", "Bilateral approach for combined hyperarousal + moral injury + cognitive PTSD components"],
        ["Z — Zone", "TPS bilateral DLPFC + vmPFC 0.2mJ/mm² 5000 — deep bilateral extinction + cognitive circuit", "Deep bilateral stimulation for comprehensive combat PTSD network normalisation"],
        ["O — Outcome", "PE or CPT adapted for combat trauma concurrent + peer support integration", "Evidence-based combat trauma therapy with moral injury modules concurrent"],
      ],
    },
    {
      phenotype: "PTSD + MDD Comorbidity",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 60min — combined autonomic and mood stabilisation", "Address both PTSD autonomic dysregulation and MDD mood dysregulation"],
        ["O — Optimise", "tDCS F3+F4 bilateral 2mA 20min — bilateral for combined PTSD + MDD", "Bilateral prefrontal approach: left DLPFC for MDD; bilateral Fz/vmPFC for PTSD extinction"],
        ["Z — Zone", "TPS bilateral DLPFC + vmPFC 0.2mJ/mm² 5000 — deep bilateral", "Deep bilateral prefrontal-limbic combined PTSD-MDD circuit normalisation"],
        ["O — Outcome", "Integrated PTSD+MDD therapy concurrent (e.g. CPT with behavioural activation) + pharmacotherapy coordination", "Integrated therapy addressing both PTSD and depression components; SSRI/SNRI coordination"],
      ],
    },
    {
      phenotype: "Treatment-Resistant PTSD",
      combinations: [
        ["S — Stabilise", "taVNS 40min bilateral — maximum autonomic preparation", "Maximum autonomic and amygdala modulation preparation"],
        ["O — Optimise", "HDCkit bilateral Fz+F3+F4 anodal 2mA 20min — maximum bilateral vmPFC+DLPFC", "Maximum bilateral extinction circuit and cognitive control upregulation"],
        ["Z — Zone", "TPS vmPFC + DLPFC bilateral + hippocampal 0.2mJ/mm² × 7000 total — maximum protocol", "Maximum multi-network deep stimulation for TRD-PTSD"],
        ["O — Outcome", "Intensive PE/CPT concurrent + CES daily home + consider MDMA-assisted therapy referral", "Maximum evidence-based therapy concurrent; consider emerging therapies for true treatment resistance"],
      ],
    },
    {
      phenotype: "PTSD + Substance Use",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 60min — primary stabilisation; taVNS also addresses craving via vagal-striatal pathway", "Dual benefit: autonomic stabilisation for PTSD AND craving modulation for SUD"],
        ["O — Optimise", "tDCS F3 anodal 1.5mA 20min — conservative left DLPFC", "Conservative prefrontal upregulation; cognitive control for both PTSD and SUD decision-making"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 2000 — conservative deep stimulation", "Conservative deep stimulation for dual-diagnosis"],
        ["O — Outcome", "Seeking Safety therapy concurrent (SUD-PTSD integrated therapy)", "Evidence-based integrated SUD-PTSD therapy concurrent with stabilised neural state"],
      ],
    },
    {
      phenotype: "Childhood Trauma / Complex Developmental",
      combinations: [
        ["S — Stabilise", "CES 0.25mA 30min — gentle; body-safe; longer stabilisation phase (6–12 sessions CES/taVNS only)", "Extended stabilisation: gentle autonomic foundation over many sessions before trauma processing"],
        ["O — Optimise", "taVNS 0.25mA 20min — gradual introduction; assess somatic tolerance", "Slow taVNS titration; monitor somatic responses; prioritise felt safety throughout"],
        ["Z — Zone", "tDCS F3 anodal 1mA 15min — conservative; Phase 2 introduction only", "Conservative cortical stimulation only after extensive stabilisation; defer TPS to Phase 3"],
        ["O — Outcome", "Phase-based trauma therapy (Herman 3-phase model) + somatic/body-based approaches concurrent", "Phase 1 stabilisation → Phase 2 trauma processing → Phase 3 reconnection, each with adapted FNON"],
      ],
    },
  ],

  taskPairingRows: [
    ["Prolonged Exposure (PE) Session", "Classic PTSD — intrusion/avoidance", "tDCS Fz/F3 anodal DURING PE session + taVNS concurrent", "In-vivo or imaginal exposure during primed extinction circuit — maximum consolidation"],
    ["CPT Trauma Account + Stuck Points", "Negative cognitions / classic PTSD", "tDCS F3 anodal active before and during", "Cognitive restructuring of maladaptive PTSD cognitions during primed DLPFC"],
    ["HRV Biofeedback", "Hyperarousal dominant", "taVNS active concurrent", "Real-time autonomic regulation training; improve vagal tone during taVNS"],
    ["Grounding Techniques", "Dissociative PTSD / hyperarousal", "CES active", "5-senses grounding, 4-7-8 breathing, safe place visualisation during CES"],
    ["Sleep Imagery Rehearsal Therapy", "Nightmare / sleep disruption", "CES active (evening)", "IRT nightmare rescripting during CES arousal normalisation"],
    ["DBT Emotion Regulation Skills", "Complex PTSD / emotional dysregulation", "tDCS F3+F4 bilateral active", "Distress tolerance and emotion regulation practice during primed prefrontal circuits"],
  ],
  outcomeMeasures: "Primary: PCL-5 (PTSD Checklist for DSM-5; session 1, 5, 10, 1-month, 3-month follow-up); CAPS-5 (Clinician-Administered PTSD Scale) at baseline and 10-session. Secondary: PHQ-9 (depression comorbidity), GAD-7 (anxiety), PSQI (sleep quality), PCL-5 subscale scores (intrusion, avoidance, negative cognitions, hyperarousal), Peritraumatic Distress Inventory, WHO-5, Sheehan Disability Scale. Safety: assess dissociation level before each session (Dissociation Tensor Scale); monitor for symptom exacerbation; safeguarding check-in; crisis plan in place.",

  medicationSectionTitle: "Pharmacotherapy Context for PTSD",
  medicationSectionText: "First-line PTSD pharmacotherapy: FDA-approved SSRIs sertraline (Zoloft) and paroxetine (Paxil). SNRI venlafaxine (Effexor) is recommended by multiple international guidelines. SSRIs/SNRIs reduce hyperarousal, re-experiencing, and avoidance symptoms with modest effect sizes. Prazosin (alpha-1 antagonist, 1–4mg nocte) has evidence for PTSD-related nightmares and may complement taVNS by addressing complementary components of LC-NE hyperactivation. Benzodiazepines are NOT recommended for PTSD — they impair extinction learning mechanisms that both trauma therapy and FNON protocols target; their use should be reviewed and tapering considered. Emerging pharmacotherapy: MDMA-assisted therapy has Breakthrough Therapy Designation and positive Phase 3 trial data; patients with treatment-resistant PTSD may be candidates for referral. Ketamine infusions have emerging evidence for rapid PTSD symptom reduction. The Doctor coordinates FNON timing with medications — SSRIs/SNRIs do not adversely interact with any FNON modality.",

  references: {
    foundational: [
      "American Psychiatric Association. (2022). Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision (DSM-5-TR). APA Publishing.",
      "Milad MR, Quirk GJ. (2012). Fear extinction as a model for translational neuroscience: Ten years of progress. Annu Rev Psychol, 63, 129–151. doi:10.1146/annurev.psych.121208.131631",
      "Rauch SL, Shin LM, Phelps EA. (2006). Neurocircuitry models of posttraumatic stress disorder and extinction: Human neuroimaging research — past, present, and future. Biol Psychiatry, 60(4), 376–382. doi:10.1016/j.biopsych.2006.06.004",
      "Etkin A, Wager TD. (2007). Functional neuroimaging of anxiety. Am J Psychiatry, 164(10), 1476–1488. doi:10.1176/appi.ajp.2007.07030504",
      "Lanius RA, Vermetten E, Loewenstein RJ, et al. (2010). Emotion modulation in PTSD: Clinical and neurobiological evidence for a dissociative subtype. Am J Psychiatry, 167(6), 640–647. doi:10.1176/appi.ajp.2009.09081168",
      "Bremner JD. (2006). Traumatic stress: Effects on the brain. Dialogues Clin Neurosci, 8(4), 445–461. doi:10.31887/DCNS.2006.8.4/jbremner",
    ],
    tdcs: [
      "Boggio PS, Rocha M, Oliveira MO, et al. (2010). Noninvasive brain stimulation with high-frequency and low-intensity repetitive transcranial magnetic stimulation treatment for posttraumatic stress disorder. J Clin Psychiatry, 71(8), 992–999. doi:10.4088/JCP.08m04638blu",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with non-invasive brain stimulation. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with tDCS. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Nitsche MA, Paulus W. (2000). Excitability changes in the human motor cortex by weak tDCS. J Physiol, 527(3), 633–639. doi:10.1111/j.1469-7793.2000.t01-1-00633.x",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and NIBS. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Bikson M, et al. (2016). Safety of transcranial direct current stimulation. Brain Stimul, 9(5), 641–661.",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930.",
      "Peterchev AV, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335.",
    ],
    tavns: [
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Burger AM, Van der Does W, Brosschot JF, Verkuil B. (2020). Transcutaneous vagus nerve stimulation reduces the startle response in anxious individuals. Biol Psychol, 149, 107800. doi:10.1016/j.biopsycho.2019.107800",
      "Thayer JF, Åhs F, Fredrikson M, Sollers JJ, Wager TD. (2012). A meta-analysis of heart rate variability and neuroimaging studies. Neurosci Biobehav Rev, 36(2), 747–756. doi:10.1016/j.neubiorev.2011.11.009",
      "Farmer AD, Strzelczyk A, Finisguerra A, et al. (2020). International consensus on taVNS reporting standards. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of brain-gut axis. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Rong P, Liu J, Wang L, et al. (2016). Effect of taVNS on major depressive disorder. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
      "Steenbergen L, et al. (2015). tVNS enhances response inhibition via norepinephrine on prefrontal cortex. Brain Stimul, 8(6), 1155–1160. doi:10.1016/j.brs.2015.09.001",
      "Borges U, et al. (2019). Influence of taVNS on cardiac vagal activity. Brain Stimul, 12(3), 727–729. doi:10.1016/j.brs.2019.01.015",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of CES for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Kavirajan HC, Lueck K, Cho K. (2014). CES use in outpatient psychiatric and pain treatment. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Overcash SJ. (2005). Narrative literature review: CES for anxiety, insomnia, depression. Am J Electromed, 22(2), 22–28.",
    ],
    network: [
      "Milad MR, Quirk GJ. (2012). Fear extinction as a model for translational neuroscience. Annu Rev Psychol, 63, 129–151. doi:10.1146/annurev.psych.121208.131631",
      "Lanius RA, Vermetten E, Loewenstein RJ, et al. (2010). Emotion modulation in PTSD. Am J Psychiatry, 167(6), 640–647. doi:10.1176/appi.ajp.2009.09081168",
      "Shin LM, Rauch SL, Pitman RK. (2006). Amygdala, medial prefrontal cortex, and hippocampal function in PTSD. Ann N Y Acad Sci, 1071, 67–79. doi:10.1196/annals.1364.007",
      "Etkin A, Wager TD. (2007). Functional neuroimaging of anxiety. Am J Psychiatry, 164(10), 1476–1488. doi:10.1176/appi.ajp.2007.07030504",
      "Thayer JF, Åhs F, Fredrikson M, Sollers JJ, Wager TD. (2012). Heart rate variability and neuroimaging meta-analysis. Neurosci Biobehav Rev, 36(2), 747–756. doi:10.1016/j.neubiorev.2011.11.009",
    ],
  },
};
