'use strict';
module.exports = {
  conditionFull: "Post-Stroke Rehabilitation",
  conditionShort: "Stroke Rehab",
  conditionSlug: "stroke_rehab",
  documentNumber: "SOZO-STR-PROT-001",
  offLabelCoverText: "tDCS and TPS use in Post-Stroke Rehabilitation is INVESTIGATIONAL / OFF-LABEL in some applications. tDCS has Level B evidence for post-stroke motor and language rehabilitation.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level B evidence for post-stroke motor and aphasia rehabilitation', 'Standard informed consent + off-label note'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; Level B evidence for post-stroke aphasia (VNS paired therapy)', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia; off-label for post-stroke mood/sleep', 'Standard informed consent'],
  ],

  inclusionCriteria: [
    "Confirmed history of ischaemic or haemorrhagic stroke (CT/MRI evidence) with residual neurological deficit",
    "Post-acute phase: minimum 2 weeks post-stroke for initiating FNON (earlier with Doctor assessment)",
    "Age 18–80 years (exceptions at Doctor discretion with documented rationale)",
    "Stable neurological status — no evidence of ongoing ischaemia, haemorrhagic expansion, or evolving oedema",
    "Capacity to provide informed consent, or supported consent process with legally authorised representative",
    "Able to participate in rehabilitation activities concurrently with FNON sessions",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field (post-craniotomy clips etc.)",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Acute phase stroke (<2 weeks) — except under specialist supervision",
    "Active haemorrhagic transformation or haemorrhagic stroke with unstable haematoma",
    "Uncontrolled epilepsy post-stroke — formal neurological assessment required",
    "Skull defect or craniotomy site over target area",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Post-stroke epilepsy — formal neurological risk assessment; adjust parameters; avoid high-intensity protocols until seizure-free ≥3 months",
    "Cardiac pacemaker or defibrillator (relevant particularly for taVNS) — individual risk-benefit assessment",
    "Atrial fibrillation (common post-stroke) — note anticoagulation; no direct contraindication to stimulation",
    "Significant post-stroke cognitive impairment — adapted consent process; carer involvement",
    "Shoulder subluxation or complex regional pain syndrome — consider upper limb tDCS adaptation",
    "Severe aphasia — adapted consent process; use augmentative communication; SLT input required",
    "Post-stroke depression — monitor closely; CES/taVNS for mood; consider co-management with psychiatry",
    "Recent thrombolysis or thrombectomy — minimum 2 weeks before tDCS/TPS; Doctor assessment required",
    "Vascular risk factor management — optimise blood pressure, diabetes, lipids in collaboration with stroke team",
  ],

  overviewParagraph: "Stroke is a leading cause of adult disability worldwide, with approximately 12.2 million new strokes occurring annually. Despite advances in acute stroke care — including IV thrombolysis (alteplase, tenecteplase) and mechanical thrombectomy — the majority of stroke survivors are left with persistent neurological deficits including motor weakness, aphasia, cognitive impairment, dysphagia, and psychological sequelae such as post-stroke depression. Approximately 50–70% of survivors have residual motor deficits affecting quality of life and independence, and 20–40% develop post-stroke aphasia. Rehabilitation is the primary treatment for chronic stroke deficits, but the intensity and duration achievable within healthcare systems is often insufficient to maximise recovery. Non-invasive brain stimulation — particularly tDCS — has emerged as an important adjunct to stroke rehabilitation with Level B evidence, capable of enhancing neuroplasticity when paired with task-specific training.",
  fnonNetworkParagraph: "Post-stroke neurological deficits reflect the disruption of large-scale brain networks whose key nodes have been damaged by infarction. The FNON framework maps residual network function and targets the perilesional cortex and contralesional adaptive plasticity with precisely directed neuromodulation. For motor recovery, the disrupted M1-CST-SMA motor circuit is targeted by upregulating ipsilesional M1 activity and reducing contralesional interhemispheric inhibition. For aphasia, the disrupted left-hemisphere language network is targeted to support perilesional reorganisation and engage right hemisphere compensatory language circuits. The taVNS-VNS paired stimulation approach represents a compelling evidence-based mechanism for driving axonal sprouting and synaptic reorganisation in perilesional zones.",
  networkDisorderParagraphs: [
    "Stroke produces focal network disruption with wide-ranging effects on connected brain systems. The immediate consequence is loss of function in the infarcted tissue and diaschisis — widespread metabolic depression and reduced excitability in areas connected to but remote from the infarct. This includes both ipsilesional perilesional areas (which retain structural integrity and plasticity potential) and contralesional homologous areas (which undergo compensatory activation changes).",
    "The contralesional hemisphere — particularly contralesional M1 in unilateral motor stroke — exhibits increased excitability through reduced transcallosal inhibition from the damaged ipsilesional hemisphere. This contralesional hyperexcitability can interfere with ipsilesional motor recovery by sending excessive inhibitory signals via the corpus callosum. The interhemispheric competition model provides the rationale for cathodal tDCS to the contralesional hemisphere (reducing its inhibitory drive on the recovering side) or anodal tDCS to the ipsilesional hemisphere (directly upregulating perilesional excitability).",
    "For aphasia, the left hemisphere perisylvian language network (Broca's-Wernicke's circuit) is partially or fully disrupted. Recovery involves reorganisation within perilesional left-hemisphere tissue (primary mechanism for good outcomes) and recruitment of right hemisphere homologous language areas (compensatory but less efficient). tDCS applied to perilesional left-hemisphere language zones upregulates neuroplasticity during speech-language therapy, while cathodal stimulation to the contralesional right hemisphere reduces inhibition of recovering left hemisphere language circuits. taVNS paired with aphasia therapy has Level B evidence from VIVID and MicroTransponder trials.",
  ],

  pathophysiologyText: "Post-stroke pathophysiology relevant to rehabilitation includes: (1) ischaemic penumbral salvage — tissue surrounding the infarct core that may recover with reperfusion or neuroprotective approaches; (2) diaschisis — widespread metabolic depression in connected but structurally intact brain regions; (3) neuroplastic reorganisation — axonal sprouting, dendritic remodelling, and synaptic reweighting in perilesional and contralesional regions over weeks-months; (4) interhemispheric imbalance — contralesional hyperexcitability due to reduced transcallosal inhibition; (5) maladaptive neuroplasticity — contralesional compensation that may limit optimal recovery in some contexts; (6) post-stroke neuroinflammation — chronic inflammatory processes that limit neuroplasticity; and (7) neurotransmitter dysregulation — reduced dopamine and noradrenaline in perilesional regions impairs learning-dependent plasticity. The therapeutic window for plasticity-based interventions extends months-to-years post-stroke, with greater neuroplasticity in the subacute phase (weeks-months).",
  cardinalSymptoms: [
    ["Motor Weakness (Hemiplegia/Hemiparesis)", "Contralateral weakness affecting face, arm, and/or leg; spastic or flaccid depending on stage; most common stroke deficit", "~80% of stroke survivors", "Langhorne et al., 2009"],
    ["Aphasia", "Expressive (Broca's) aphasia — non-fluent speech with preserved comprehension; receptive (Wernicke's) — fluent but incomprehensible; global — severe both", "~20–40% of all stroke; left hemisphere stroke", "Engelter et al., 2006; Berthier, 2005"],
    ["Dysphagia", "Swallowing difficulties; aspiration risk; bilateral and unilateral cortical/subcortical involvement", "~50% acute stroke; ~20% persists", "Martino et al., 2005"],
    ["Cognitive Impairment", "Post-stroke dementia or mild cognitive impairment; attention, memory, processing speed, executive function deficits", "~30–40%", "Pendlebury & Rothwell, 2009"],
    ["Post-Stroke Depression", "Depressive symptoms within 3 months; apathy; reduced rehabilitation motivation; frontal-limbic circuit disruption", "~30–35%", "Hackett et al., 2005"],
    ["Spatial Neglect", "Hemispatial neglect following right parietal stroke; inattention to left hemispace; anosognosia; parietal-SN circuit disruption", "~20–30% right hemisphere stroke", "Heilman et al., 1993"],
    ["Spasticity", "Increased muscle tone and spasms; painful; limits rehabilitation; UMN syndrome; onset weeks-months post-stroke", "~30–40% chronic stroke", "Watkins et al., 2002"],
    ["Pain (Central Post-Stroke Pain)", "Neuropathic pain affecting paretic limbs; central sensitisation; thalamo-cortical pathway disruption; burning/allodynia", "~10–20%", "Klit et al., 2009"],
    ["Fatigue", "Post-stroke fatigue; one of most disabling chronic symptoms; poorly understood mechanism; reduced motivation for rehabilitation", "~50–70%", "Duncan et al., 2012"],
    ["Ataxia", "Cerebellar stroke — ipsilateral ataxia, dysmetria, gait instability, dysarthria", "~20% of posterior circulation stroke", "Caplan et al., 2004"],
    ["Visual Field Defects", "Homonymous hemianopia following occipital/optic radiation stroke; affects reading, driving, mobility", "~30–40% with visual symptoms", "Zhang et al., 2006"],
    ["Emotional Lability", "Pathological laughing or crying; pseudobulbar affect; bilateral corticobulbar tract involvement", "~10–20%", "Morris et al., 1993"],
    ["Gait Impairment", "Hemiparetic gait with circumduction, foot drop, and reduced stride length; functional independence impact", "~50% chronic stroke survivors", "Perry et al., 1995"],
  ],
  standardGuidelinesText: [
    "Post-stroke rehabilitation guidelines (NICE 2023, AHA/ASA 2016, RCP SSNAP 2020) recommend a comprehensive interdisciplinary rehabilitation programme including physiotherapy (motor relearning, constraint-induced movement therapy, task-specific training), speech and language therapy (aphasia therapy, dysarthria, dysphagia management), occupational therapy (ADL retraining, splinting), and neuropsychology (cognitive rehabilitation, post-stroke depression management). Evidence-based motor rehabilitation approaches include robot-assisted therapy, functional electrical stimulation (FES), and mirror therapy as adjuncts to task-specific physiotherapy.",
    "For post-stroke aphasia, high-intensity aphasia therapy and communication partner training have the strongest evidence. Melodic intonation therapy, constraint-induced aphasia therapy (CIAT), and semantic feature analysis are evidence-based approaches. Non-invasive brain stimulation — particularly tDCS and implanted VNS (MicroTransponder/Serenity system) — have Level B evidence as adjuncts to aphasia therapy.",
    "SOZO FNON protocols are designed to maximise neuroplasticity during concurrent rehabilitation sessions. The critical principle is that FNON stimulation without concurrent rehabilitation practice has limited benefit — the stimulation is designed to prime the target network circuits during active task practice. Doctor coordinates FNON with the rehabilitation team to ensure concurrent stimulation-task timing.",
  ],

  fnonFrameworkParagraph: "The FNON framework for post-stroke rehabilitation is based on two complementary principles: (1) enhance perilesional and ipsilesional neuroplasticity by upregulating excitability in areas adjacent to the infarct via anodal tDCS/TPS; and (2) reduce contralesional interhemispheric inhibition via cathodal stimulation of the contralesional hemisphere. Both mechanisms promote greater functional use of the damaged hemisphere during rehabilitation practice. taVNS enhances the release of BDNF, ACh, and NE during paired rehabilitation practice, directly driving the axonal sprouting and synaptic remodelling that underlies motor and language recovery.",
  keyBrainRegions: [
    ["Ipsilesional Primary Motor Cortex (M1)", "Damaged or diaschisis-depressed excitability; motor output via corticospinal tract; primary motor recovery target", "PRIMARY MOTOR TARGET: anodal tDCS ipsilesional M1 (contralateral to paretic limb); TPS ipsilesional M1; paired with physiotherapy", "Nitsche & Paulus, 2000; Lefaucheur et al., 2017; Flöel et al., 2012"],
    ["Contralesional M1", "Hyperexcitable due to reduced transcallosal inhibition from damaged hemisphere; inhibits ipsilesional recovery via interhemispheric competition", "Cathodal tDCS contralesional M1 — reduces inhibitory drive on recovering hemisphere; bilateral tDCS alternates approaches", "Fregni et al., 2005; Nitsche et al., 2008"],
    ["Supplementary Motor Area (SMA)", "Motor planning and initiation; ipsilesional SMA supports corticospinal compensation when M1 is damaged", "Anodal tDCS ipsilesional SMA; TPS SMA for motor initiation and sequencing", "Lotze et al., 2006"],
    ["Left Broca's Area (IFG)", "Language production; primary target for non-fluent aphasia; perilesional left IFG tissue for reorganisation", "Anodal tDCS F7 (left IFG); TPS left IFG; combined with speech-language therapy concurrent", "Monti et al., 2008; Fridriksson et al., 2011"],
    ["Left Wernicke's Area (STG/MTG)", "Language comprehension; target for receptive aphasia; perilesional left superior temporal tissue", "Anodal tDCS T3/T5 (left temporal); TPS left temporal for comprehension deficits", "Fridriksson et al., 2011"],
    ["Posterior Parietal Cortex (PPC)", "Spatial attention and neglect; right PPC damage causes left hemispatial neglect; praxis and visuospatial function", "Cathodal tDCS contralesional PPC; anodal ipsilesional PPC; TPS parietal for neglect rehabilitation", "Kerkhoff & Schenk, 2012"],
    ["Cerebellum", "Ataxia and coordination recovery; ipsilateral cerebellar stroke; tDCS Cbz for cerebellar rehabilitation", "tDCS Cbz (cerebellar transcranial stimulation) for ipsilateral ataxia; TPS cerebellar for dysmetria", "Ferrucci et al., 2012"],
    ["Thalamus", "Relay for sensory and motor signals; thalamic stroke produces sensory, motor, and cognitive deficits; thalamo-cortical reorganisation", "TPS thalamic targeting (indirect); restoration of thalamo-cortical relay via targeted stimulation", "Mishkin et al., 1997"],
    ["Prefrontal Cortex (DLPFC)", "Post-stroke cognitive deficits and post-stroke depression; preserved DLPFC targeted for cognitive rehabilitation and mood", "Anodal tDCS F3 for post-stroke depression and cognitive deficits; TPS DLPFC for executive function recovery", "Jorge et al., 2004; Flöel et al., 2012"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Primary relay for taVNS; mediates BDNF release and ACh upregulation critical for neuroplasticity during paired motor/aphasia therapy", "taVNS paired with rehabilitation practice — NTS→LC→ACh/NE→cortex neuroplasticity drive", "Hays et al., 2014"],
    ["Locus Coeruleus (LC)", "Noradrenergic arousal and plasticity modulation; NE promotes LTP in perilesional regions during training", "taVNS→NTS→LC→NE release during rehabilitation sessions; temporal pairing with task practice is critical", "Dorr & Bhagya, 2017"],
    ["Nucleus Basalis of Meynert", "Cholinergic neuromodulation for cortical plasticity; ACh release during VNS paired therapy drives map reorganisation", "taVNS activates basal forebrain ACh via NTS pathway; critical for aphasia and motor map reorganisation", "Kilgard & Merzenich, 1998"],
    ["Corpus Callosum", "Transcallosal inhibition; damaged pathways reduce inhibitory balance; bilateral stimulation protocols address callosal imbalance", "Bilateral tDCS bihemispheric protocol addresses transcallosal inhibition in motor recovery", "Ward & Cohen, 2004"],
    ["Corticospinal Tract (CST)", "Primary motor output pathway; extent of CST damage predicts motor recovery; DTI assessment valuable for protocol selection", "Anodal tDCS/TPS ipsilesional M1 enhances surviving CST axon function and sprouting", "Stinear et al., 2012"],
    ["Basal Ganglia", "Motor sequencing and automatisation; involvement in post-stroke motor recovery compensation", "Indirect modulation via M1-basal ganglia pathway; TPS deep targeting for basal ganglia-involved strokes", "Khedr et al., 2006"],
    ["Hippocampus", "Post-stroke cognitive impairment and memory; hippocampal diaschisis after distant strokes", "TPS hippocampal targeting for post-stroke cognitive rehabilitation; taVNS BDNF for hippocampal recovery", "Sachdev et al., 2009"],
  ],
  keyFunctionalNetworks: [
    ["Motor Network", "M1, PMC, SMA, cerebellum, basal ganglia, thalamus, CST", "Ipsilesional hypoactivation + contralesional compensatory hyperactivation; interhemispheric imbalance; CST integrity variable", "PRIMARY: anodal tDCS ipsilesional M1; cathodal contralesional M1 (bihemispheric); TPS ipsilesional M1; paired physiotherapy concurrent", "Fregni et al., 2005; Hummel & Cohen, 2006"],
    ["Language Network", "Left IFG (Broca's), left STG (Wernicke's), left MTG, arcuate fasciculus, SMA", "Disrupted perilesional left hemisphere language circuitry; perilesional reorganisation vs. right hemisphere compensation", "Anodal tDCS F7/T3 (left hemisphere, perilesional); TPS left language areas; taVNS paired with SLT; cathodal right IFG for contralesional inhibition", "Monti et al., 2008; Turkeltaub et al., 2012"],
    ["Attention Network (Neglect)", "Right PPC, TPJ, IPS, FEF, ACC", "Right hemisphere dominance for spatial attention; disruption causes left hemispatial neglect; bilateral attention impairments post-stroke", "Cathodal contralesional PPC; anodal ipsilesional PPC; visuospatial training concurrent", "Kerkhoff & Schenk, 2012"],
    ["Cognitive/Executive Network (CEN)", "DLPFC, PPC, ACC", "Post-stroke cognitive impairment and executive dysfunction; preserved DLPFC circuits targeted for compensation", "Anodal tDCS F3 (preserved ipsilesional DLPFC); TPS DLPFC; cognitive training concurrent", "Flöel et al., 2012"],
    ["Emotional/Mood Network", "PFC, amygdala, ACC, limbic circuit", "Post-stroke depression affecting rehabilitation engagement and outcomes; frontal-limbic circuit disruption", "CES + taVNS for post-stroke depression; anodal tDCS F3 (left DLPFC); coordinate with psychiatric management", "Hackett et al., 2005"],
    ["Cerebellar-Motor Network", "Cerebellum, thalamus, M1, SMA, basal ganglia", "Ipsilateral ataxia following cerebellar stroke; timing, coordination deficits", "tDCS Cbz (ipsilateral cerebellar target); TPS cerebellar; balance and coordination tasks concurrent", "Ferrucci et al., 2012"],
    ["Autonomic/Vagal Network", "Brainstem, NTS, LC, insula, ACC, autonomic cortex", "Post-stroke autonomic dysregulation; reduced HRV; relevant for recovery capacity and post-stroke fatigue", "taVNS restores autonomic balance; improves HRV; reduces post-stroke fatigue; promotes neuroplasticity via NE/ACh release", "Hays et al., 2014"],
  ],
  networkAbnormalities: "Post-stroke network abnormalities include ipsilesional network hypoactivation (diaschisis), contralesional compensatory hyperactivation (interhemispheric competition), disrupted corticospinal and language network connectivity, and impaired thalamo-cortical relay. The FNON approach targets these imbalances via directional stimulation (anodal ipsilesional + cathodal contralesional) paired with concurrent rehabilitation practice.",
  conceptualFramework: "SOZO FNON Stroke protocol is built on activity-dependent plasticity: stimulation MUST be paired with concurrent rehabilitation practice to be effective. (1) Prime ipsilesional circuits (anodal/TPS); (2) Reduce contralesional inhibitory interference (cathodal); (3) Drive axonal sprouting and ACh/NE-dependent plasticity via taVNS during task practice; (4) Consolidate gains with daily home CES and continued practice.",

  clinicalPhenotypes: [
    ["Motor Hemiparesis — Upper Limb", "Contralateral arm/hand weakness; ipsilesional M1 target primary; paired CIMT or task-specific training; physiotherapy integration", "Langhorne et al., 2009"],
    ["Motor Hemiparesis — Lower Limb / Gait", "Contralateral leg weakness and gait impairment; ipsilesional M1/SMA + cerebellar targets; treadmill/gait training concurrent", "Perry et al., 1995"],
    ["Non-fluent Aphasia (Broca's)", "Expressive aphasia; preserved comprehension; perilesional left IFG target; anodal tDCS F7; paired intensive speech therapy", "Fridriksson et al., 2011"],
    ["Fluent/Receptive Aphasia (Wernicke's)", "Receptive aphasia; comprehension deficit primary; perilesional left temporal (T3/T5); TPS left temporal; paired comprehension therapy", "Fridriksson et al., 2011"],
    ["Post-Stroke Cognitive Impairment", "Executive dysfunction, attention, memory; DLPFC target; tDCS F3; cognitive rehabilitation concurrent; coordinate with neuropsychology", "Pendlebury & Rothwell, 2009"],
    ["Post-Stroke Depression", "Depressive symptoms; reduced rehabilitation motivation; CES + taVNS primary; anodal tDCS F3; coordinate with psychiatry", "Hackett et al., 2005"],
    ["Hemispatial Neglect", "Left neglect post right parietal stroke; cathodal right PPC; anodal left PPC; visuospatial rehabilitation concurrent", "Kerkhoff & Schenk, 2012"],
    ["Cerebellar Stroke (Ataxia)", "Ipsilateral ataxia, dysmetria, gait instability; tDCS Cbz ipsilateral; TPS cerebellar; balance training concurrent", "Ferrucci et al., 2012"],
    ["Post-Stroke Fatigue", "Persistent fatigue; impairs rehabilitation participation; taVNS + CES for autonomic-neurotrophic support; graded exercise and energy management", "Duncan et al., 2012"],
  ],
  symptomNetworkMapping: [
    ["Motor Weakness — Upper Limb", "Motor network — ipsilesional hypoactivation", "Contralesional M1 inhibitory excess", "Anodal tDCS ipsilesional M1 OR cathodal contralesional M1", "Concurrent upper limb task-specific training"],
    ["Aphasia — Expressive", "Language network — left IFG disruption", "Right IFG compensatory inhibition", "Anodal tDCS F7 (left IFG) + cathodal right F8", "Concurrent speech-language therapy (SLT)"],
    ["Aphasia — Receptive", "Language network — left temporal disruption", "Perilesional left temporal reorganisation", "Anodal tDCS T3/T5 (left temporal)", "Comprehension therapy concurrent"],
    ["Cognitive Impairment", "CEN hypoactivation — preserved DLPFC", "Post-stroke frontal diaschisis", "Anodal tDCS F3 (left DLPFC)", "Cognitive training concurrent"],
    ["Post-Stroke Depression", "Frontal-limbic circuit disruption", "SN/autonomic dysregulation", "CES + taVNS + anodal F3", "Structured pleasant activity + carer support"],
    ["Spatial Neglect", "Right PPC overactivation inhibiting left attention", "Left-right PPC interhemispheric imbalance", "Cathodal right PPC + anodal left PPC", "Visual scanning training concurrent"],
    ["Gait Impairment", "Motor network — SMA/cerebellar-motor", "Ipsilesional SMA-M1 circuit", "Anodal tDCS ipsilesional M1/SMA + tDCS Cbz", "Treadmill/gait training concurrent"],
    ["Post-Stroke Fatigue", "Autonomic-arousal network disruption", "LC noradrenergic deficit post-stroke", "taVNS + CES for autonomic restoration", "Graded activity scheduling concurrent"],
    ["Spasticity", "Upper motor neuron — ipsilesional M1 area disruption", "Maladaptive corticospinal compensation", "tDCS M1 ipsilesional (inhibitory circuit upregulation)", "Stretching and anti-spasticity rehabilitation concurrent"],
    ["Ataxia (Cerebellar)", "Cerebellar motor network", "Ipsilateral cerebellar deafferentation", "tDCS Cbz + TPS cerebellar ipsilateral", "Balance and coordination training concurrent"],
  ],
  montageSelectionRows: [
    ["Motor hemiparesis — ipsilesional M1 focus", "Anodal ipsilesional M1, cathodal contralesional M1 — 2mA 20min"],
    ["Motor hemiparesis — bihemispheric protocol", "Anodal ipsilesional M1 + cathodal contralesional M1 simultaneously — 1mA each"],
    ["Non-fluent aphasia (Broca's)", "Anodal F7 (left IFG) + cathodal right F8 — 1.5mA 20min"],
    ["Receptive aphasia (Wernicke's)", "Anodal T3/T5 (left temporal) + cathodal right T4 — 1.5mA 20min"],
    ["Post-stroke cognitive impairment", "Anodal F3 (left DLPFC) + cathodal Pz — 2mA 20min"],
    ["Post-stroke depression", "CES 0.5mA 60min + taVNS 30min + anodal F3 tDCS"],
    ["Hemispatial neglect", "Cathodal right P4/PPC + anodal left P3 — 1.5mA 20min"],
    ["Cerebellar ataxia", "tDCS Cbz (ipsilateral) anodal — 2mA 20min + TPS cerebellar"],
    ["taVNS paired therapy (aphasia/motor)", "taVNS left cymba 0.5mA during SLT/physiotherapy session"],
    ["Post-stroke fatigue protocol", "taVNS 30min + CES 60min (primary modalities)"],
    ["TPS motor phenotype", "NEUROLITH® ipsilesional M1 — 0.2mJ/mm² 4000 pulses paired with physio"],
    ["TPS aphasia phenotype", "NEUROLITH® left temporal/IFG — 0.2mJ/mm² 3000 pulses paired with SLT"],
    ["Maintenance phase", "tDCS 2×/week during rehabilitation; CES daily home; taVNS during home exercises"],
  ],
  polarityPrincipleText: "Post-stroke stimulation polarity is guided by the interhemispheric competition model: anodal stimulation of ipsilesional (damaged hemisphere) motor/language areas upregulates perilesional excitability for neuroplasticity. Cathodal stimulation of contralesional homologous areas reduces transcallosal inhibitory interference. Bihemispheric protocols (simultaneous ipsilesional anodal + contralesional cathodal) maximise interhemispheric rebalancing. CRITICAL: stimulation must be concurrent with rehabilitation practice for effectiveness.",
  polarityTable: [
    ["Anodal ipsilesional M1/language areas", "Upregulates perilesional excitability; promotes motor map reorganisation and language network reorganisation"],
    ["Cathodal contralesional M1/language areas", "Reduces transcallosal inhibitory interference; releases ipsilesional hemisphere from competitive inhibition"],
    ["Bihemispheric simultaneous protocol", "Combines anodal ipsilesional + cathodal contralesional for maximum interhemispheric rebalancing"],
    ["taVNS during rehabilitation", "Activity-dependent plasticity driver — BDNF/ACh/NE release during paired task practice amplifies neuroplasticity"],
    ["CES post-session", "Consolidation and post-stroke depression management; evening autonomic stabilisation"],
  ],

  classicTdcsProtocols: [
    ["C1", "Motor recovery / ipsilesional M1", "Ipsilesional M1 anodal", "Contralesional M1 cathodal", "1mA 20min; 2mA 20min (advanced)", "Level B"],
    ["C2", "Motor recovery / bihemispheric", "Ipsilesional M1 anodal", "Contralesional M1 cathodal (simultaneous)", "1mA each 20min", "Level B"],
    ["C3", "Non-fluent aphasia", "F7 (left IFG) anodal", "Right F8 cathodal", "1.5mA 20min", "Level B"],
    ["C4", "Receptive aphasia", "T3/T5 (left temporal) anodal", "Right temporal cathodal", "1.5mA 20min", "Level C-B"],
    ["C5", "Post-stroke cognitive impairment", "F3 (DLPFC) anodal", "Pz cathodal", "2mA 20min", "Level C"],
    ["C6", "Post-stroke depression", "F3 anodal + CES + taVNS", "Pz cathodal", "2mA 20min", "Level C"],
    ["C7", "Hemispatial neglect", "Cathodal right P4", "Anodal left P3", "1.5mA 20min", "Level C"],
    ["C8", "Cerebellar ataxia", "Cbz anodal (ipsilateral)", "Contralateral Cbz cathodal", "2mA 20min", "Emerging"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Motor hemiparesis — standard", "Interhemispheric motor imbalance", "Anodal ipsilesional M1 + cathodal contralesional M1", "Rebalance motor network during paired physiotherapy"],
    ["F2", "Motor hemiparesis — bihemispheric", "Interhemispheric motor imbalance (severe)", "Simultaneous bihemispheric 1mA each + taVNS", "Maximum interhemispheric rebalancing + neuroplasticity drive"],
    ["F3", "Non-fluent aphasia (Broca's)", "Left IFG circuit disruption + right IFG overcompensation", "Anodal F7 + cathodal right F8 + taVNS during SLT", "Language network reorganisation with paired speech therapy"],
    ["F4", "Post-stroke cognitive + depression", "Bilateral CEN + limbic circuit", "F3 anodal + CES + taVNS — combined cognitive-mood protocol", "Cognitive and mood recovery combined with autonomic modulation"],
    ["F5", "Neglect (right parietal)", "Interhemispheric attention imbalance", "Cathodal right P4 + anodal left P3", "Rebalance attention network for left neglect rehabilitation"],
    ["F6", "Comprehensive motor + aphasia", "Multiple network disruption", "Anodal ipsilesional M1 + F7; TPS motor + language; taVNS throughout", "Multi-network approach for strokes affecting both motor and language"],
  ],
  classicTpsProtocols: [
    ["T1", "Motor recovery / ipsilesional M1", "Ipsilesional M1", "0.2mJ/mm²", "4000 pulses", "Emerging"],
    ["T2", "Aphasia / left language areas", "Left IFG/temporal", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T3", "Post-stroke cognitive", "Left DLPFC", "0.2mJ/mm²", "3000 pulses", "Exploratory"],
    ["T4", "Cerebellar ataxia", "Ipsilateral cerebellar", "0.2mJ/mm²", "4000 pulses", "Emerging"],
    ["T5", "Motor + cognitive combined", "M1 + DLPFC sequential", "0.2mJ/mm²", "5000 total pulses", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Motor hemiparesis — ipsilesional M1", "Corticospinal tract motor circuit", "Ipsilesional M1 0.2mJ/mm² × 4000 pulses paired with physiotherapy", "Deep ipsilesional motor cortex — CST axon sprouting stimulation"],
    ["FT2", "Non-fluent aphasia", "Perilesional left IFG language circuit", "Left IFG/F7 region 0.2mJ/mm² × 3000 pulses paired with SLT", "Deep perilesional language circuit stimulation during speech therapy"],
    ["FT3", "Receptive aphasia", "Perilesional left temporal language", "Left temporal 0.2mJ/mm² × 3000 pulses paired with SLT", "Deep left temporal language comprehension circuit"],
    ["FT4", "Post-stroke cognitive", "DLPFC-executive circuit", "Left DLPFC 0.2mJ/mm² × 3000 + hippocampal 0.2mJ/mm² × 2000", "Deep cognitive circuit stimulation during cognitive rehabilitation"],
    ["FT5", "Cerebellar ataxia", "Ipsilateral cerebellum", "Ipsilateral cerebellar 0.2mJ/mm² × 4000 paired with balance therapy", "Deep cerebellar stimulation for ataxia and coordination rehabilitation"],
    ["FT6", "Hemispatial neglect", "Right parietal + left parietal", "Right PPC cathodal 0.2mJ/mm² × 2000 + left PPC 0.2mJ/mm² × 2000", "Bilateral parietal rebalancing for hemispatial neglect"],
    ["FT7", "Comprehensive motor + aphasia", "Motor + language networks", "M1 + F7 sequential 0.2mJ/mm² × 5000 total + taVNS throughout", "Multi-area sequential TPS for combined motor-language stroke"],
    ["FT8", "Post-stroke fatigue / depression", "Autonomic + prefrontal", "F3 DLPFC 0.2mJ/mm² × 2000 + CES + taVNS (fatigue protocol)", "Mild prefrontal stimulation + maximal autonomic support for fatigue/depression"],
    ["FT9", "Maintenance motor/aphasia protocol", "Residual motor/language circuit", "Monthly ipsilesional M1 or F7 0.2mJ/mm² × 2000", "Monthly maintenance stimulation to consolidate rehabilitation gains"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Motor Hemiparesis — Upper Limb",
      combinations: [
        ["S — Stabilise", "taVNS 30min (pre-session or concurrent during physiotherapy) — neuroplasticity drive via NTS-LC-ACh/NE", "Prime neuroplasticity mechanisms before and during motor task practice — critical for activity-dependent recovery"],
        ["O — Optimise", "tDCS ipsilesional M1 anodal 1–2mA 20min + cathodal contralesional M1 (bihemispheric)", "Simultaneous upregulation of impaired hemisphere and reduction of inhibitory contralesional interference"],
        ["Z — Zone", "TPS ipsilesional M1 0.2mJ/mm² 4000 pulses — deep motor cortex penetration", "Deep cortical motor circuit stimulation; axon sprouting in perilesional M1 and CST"],
        ["O — Outcome", "Task-specific upper limb training concurrent (CIMT principles) + home exercise programme", "Constraint-induced movement therapy paired with primed motor circuits; daily home exercises with CES"],
      ],
    },
    {
      phenotype: "Non-Fluent Aphasia (Broca's)",
      combinations: [
        ["S — Stabilise", "taVNS left cymba 0.5mA 30min (during SLT session) — primary neuroplasticity drive for aphasia recovery", "VNS paired therapy principle — ACh/NE release during speech production reinforces language circuit reorganisation"],
        ["O — Optimise", "tDCS F7 anodal 1.5mA 20min + right F8 cathodal — perilesional left IFG upregulation", "Prime perilesional left IFG during concurrent speech therapy; reduce right IFG inhibition"],
        ["Z — Zone", "TPS left IFG 0.2mJ/mm² 3000 pulses during/after SLT session", "Deep perilesional language circuit neuroplasticity induction"],
        ["O — Outcome", "High-intensity SLT concurrent (CIAT principles) — constraint-induced aphasia therapy", "Intensive speech production tasks during primed language circuits; meaningful communicative practice"],
      ],
    },
    {
      phenotype: "Post-Stroke Cognitive Impairment",
      combinations: [
        ["S — Stabilise", "taVNS 30min — noradrenergic-BDNF priming for cognitive rehabilitation", "Prepare prefrontal cognitive circuit for cognitive training; promote neuroplasticity in post-stroke frontal areas"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min — left DLPFC CEN upregulation", "Prime left prefrontal cognitive circuits for working memory and executive training"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 3000 — deep prefrontal cognitive circuit", "Deep cognitive circuit stimulation for executive and working memory rehabilitation"],
        ["O — Outcome", "Cognitive rehabilitation tasks concurrent (working memory, attention, executive) + CES", "Evidence-based cognitive rehabilitation concurrent with primed circuits; CES for mood and sleep"],
      ],
    },
    {
      phenotype: "Post-Stroke Depression",
      combinations: [
        ["S — Stabilise", "taVNS 40min + CES 60min — primary mood modality combination for post-stroke depression", "Autonomic-limbic stabilisation and mood support; taVNS/CES preferred primary approach for PSD"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min — left DLPFC upregulation for depression", "Prefrontal antidepressant circuit upregulation — coordinates with antidepressant pharmacotherapy"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 3000 — deep prefrontal limbic circuit", "Deep prefrontal circuit stimulation for post-stroke depression"],
        ["O — Outcome", "Structured pleasant activity scheduling + rehabilitation engagement monitoring", "Behavioural activation concurrent with mood priming; improved mood enhances rehabilitation engagement"],
      ],
    },
    {
      phenotype: "Hemispatial Neglect",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 30min — reduce anxiety and stabilise before lateralised stimulation", "Prepare patient for unilateral parietal stimulation"],
        ["O — Optimise", "tDCS cathodal right P4 + anodal left P3 1.5mA 20min — parietal rebalancing", "Reduce right PPC overactivation; upregulate left PPC attention network"],
        ["Z — Zone", "TPS right PPC + left PPC rebalancing 0.2mJ/mm² × 2000 each side", "Deep bilateral parietal stimulation for interhemispheric attention rebalancing"],
        ["O — Outcome", "Visual scanning training concurrent (top-down prism adaptation, TENS) + taVNS", "Evidence-based neglect rehabilitation concurrent with primed parietal circuits"],
      ],
    },
    {
      phenotype: "Cerebellar Stroke (Ataxia)",
      combinations: [
        ["S — Stabilise", "taVNS 30min — neuroplasticity preparation for cerebellar circuit", "Prime cerebellar-brainstem neuroplasticity mechanisms before targeted cerebellar stimulation"],
        ["O — Optimise", "tDCS Cbz anodal 2mA 20min (ipsilateral cerebellar)", "Upregulate ipsilateral cerebellar excitability for balance and coordination training"],
        ["Z — Zone", "TPS cerebellar (ipsilateral) 0.2mJ/mm² 4000 — deep cerebellar stimulation", "Deep cerebellar circuit stimulation paired with balance therapy"],
        ["O — Outcome", "Balance training concurrent (Frenkel exercises, proprioceptive training) — consolidate", "Cerebellar-specific rehabilitation concurrent with primed cerebellar circuits"],
      ],
    },
    {
      phenotype: "Post-Stroke Fatigue",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — primary fatigue modality; broad-spectrum arousal modulation", "Address chronic fatigue via autonomic and arousal circuit modulation"],
        ["O — Optimise", "taVNS 40min — noradrenergic arousal restoration via NTS-LC pathway", "Restore LC-NE arousal signalling depleted in post-stroke fatigue"],
        ["Z — Zone", "tDCS F3 anodal 1.5mA 15min — mild prefrontal upregulation (conservative for fatigue)", "Gentle prefrontal upregulation to improve motivational and arousal circuits without exhausting depleted reserves"],
        ["O — Outcome", "Graded energy management programme concurrent + sleep hygiene", "Evidence-based fatigue management with neural priming; avoid over-stimulation"],
      ],
    },
    {
      phenotype: "Receptive Aphasia (Wernicke's)",
      combinations: [
        ["S — Stabilise", "taVNS left cymba 0.5mA 30min during SLT — paired therapy for language comprehension", "VNS paired therapy for receptive aphasia — ACh release during comprehension training"],
        ["O — Optimise", "tDCS T3/T5 anodal 1.5mA 20min — perilesional left temporal upregulation", "Prime perilesional left temporal comprehension circuit during SLT"],
        ["Z — Zone", "TPS left temporal 0.2mJ/mm² 3000 — deep temporal comprehension circuit", "Deep perilesional left temporal stimulation for comprehension rehabilitation"],
        ["O — Outcome", "Comprehension-focused SLT concurrent (semantic feature analysis, supported communication)", "Language comprehension tasks during primed temporal circuits"],
      ],
    },
    {
      phenotype: "Comprehensive Multi-Domain Stroke",
      combinations: [
        ["S — Stabilise", "taVNS 40min — broad neuroplasticity priming across all impaired networks", "Maximum neuroplasticity preparation for multi-domain stroke rehabilitation"],
        ["O — Optimise", "tDCS ipsilesional M1 + F7 sequential 2mA 20min each — motor and language", "Sequential ipsilesional motor then language circuit upregulation"],
        ["Z — Zone", "TPS M1 + F7/temporal sequential — 0.2mJ/mm² 5000 total pulses", "Sequential deep motor and language circuit stimulation"],
        ["O — Outcome", "Alternating physiotherapy and SLT sessions post-stimulation + CES daily", "Maximise rehabilitation across motor and language domains in post-stimulation plasticity window"],
      ],
    },
  ],

  taskPairingRows: [
    ["Upper Limb Task-Specific Training", "Motor hemiparesis — upper limb", "tDCS ipsilesional M1 active + taVNS concurrent", "Reaching, grasping, functional task practice during stimulation"],
    ["Intensive SLT / CIAT", "Non-fluent aphasia", "tDCS F7 anodal active + taVNS concurrent", "High-intensity speech production; constraint-induced aphasia therapy principles"],
    ["Comprehension Therapy", "Receptive aphasia", "tDCS T3/T5 anodal active + taVNS concurrent", "Semantic feature tasks; sentence-picture matching; supported comprehension"],
    ["Cognitive Rehabilitation Tasks", "Post-stroke cognitive impairment", "tDCS F3 anodal active", "Attention, working memory, planning tasks during stimulation"],
    ["Visual Scanning Training", "Hemispatial neglect", "tDCS parietal rebalancing active", "Prism adaptation, scanning exercises, compensatory strategy training"],
    ["Balance and Coordination Training", "Cerebellar ataxia", "tDCS Cbz anodal active", "Frenkel exercises, dynamic balance training, proprioceptive retraining"],
  ],
  outcomeMeasures: "Primary: Fugl-Meyer Assessment (FMA — motor; baseline, 5, 10, 1-month); Western Aphasia Battery Revised (WAB-R) for aphasia; MoCA for cognitive impairment; PHQ-9 for post-stroke depression; PSQI for sleep. Secondary: Barthel Index / modified Rankin Scale (functional independence); 10-metre walk test (gait); grip strength dynamometry; NIHSS (stroke severity); stroke-specific QoL (SS-QoL); Carer Strain Index. Safety: monitor for seizure activity; skin inspection; blood pressure monitoring pre/post-session.",

  medicationSectionTitle: "Pharmacotherapy Context for Post-Stroke Rehabilitation",
  medicationSectionText: "Post-stroke pharmacotherapy includes secondary prevention medications (anticoagulants for AF — warfarin, DOACs; antiplatelets for non-cardioembolic stroke — aspirin, clopidogrel, dipyridamole; statins; antihypertensives) which do not directly interact with FNON. Spasticity management with oral baclofen, tizanidine, or botulinum toxin injections is coordinated with tDCS — combining motor tDCS with botulinum toxin is a recognised approach (tDCS post-botulinum injection during rehabilitation). Post-stroke depression is managed with SSRIs (sertraline, fluoxetine — FLAME trial supports fluoxetine for motor recovery, though this remains controversial) and SNRIs. Cognitive symptoms may be treated with cholinesterase inhibitors in some cases. The Doctor ensures no pharmacological contraindications to FNON modalities — noting that anticoagulation does not contraindicate scalp electrode placement but requires careful skin monitoring.",

  references: {
    foundational: [
      "Langhorne P, Bernhardt J, Kwakkel G. (2011). Stroke rehabilitation. Lancet, 377(9778), 1693–1702. doi:10.1016/S0140-6736(11)60325-5",
      "Feigin VL, Roth GA, Naghavi M, et al. (2016). Global burden of stroke and risk factors in 188 countries. Lancet Neurol, 15(9), 913–924. doi:10.1016/S1474-4422(16)30073-4",
      "Stinear C. (2010). Prediction of recovery of motor function after stroke. Lancet Neurol, 9(12), 1228–1232. doi:10.1016/S1474-4422(10)70247-7",
      "Hummel FC, Cohen LG. (2006). Non-invasive brain stimulation: A new strategy to improve neurorehabilitation after stroke? Lancet Neurol, 5(8), 708–712. doi:10.1016/S1474-4422(06)70525-7",
      "Thiel A, Zumbansen A. (2016). The pathophysiology of post-stroke aphasia: A network approach. Restor Neurol Neurosci, 34(4), 507–518. doi:10.3233/RNN-150658",
      "Wardlaw JM, Murray V, Berge E, del Zoppo GJ. (2014). Thrombolysis for acute ischaemic stroke. Cochrane Database Syst Rev, 7, CD000213. doi:10.1002/14651858.CD000213.pub3",
    ],
    tdcs: [
      "Fregni F, Boggio PS, Valle AC, et al. (2006). A sham-controlled trial of a 5-day course of repetitive transcranial magnetic stimulation of the unaffected hemisphere in stroke patients. Stroke, 37(8), 2115–2122. doi:10.1161/01.STR.0000231390.58967.6b",
      "Nitsche MA, Schauenburg A, Lang N, et al. (2003). Facilitation of implicit motor learning by weak transcranial direct current stimulation of the primary motor cortex in the human. J Cogn Neurosci, 15(4), 619–626. doi:10.1162/089892903321662994",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Flöel A, Meinzer M, Kirstein R, et al. (2011). Short-term anomia training and electrical brain stimulation. Stroke, 42(7), 2065–2067. doi:10.1161/STROKEAHA.110.609032",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with non-invasive brain stimulation. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Nitsche MA, Paulus W. (2000). Excitability changes induced in the human motor cortex by weak transcranial direct current stimulation. J Physiol, 527(3), 633–639. doi:10.1111/j.1469-7793.2000.t01-1-00633.x",
      "Monti A, Ferrucci R, Fumagalli M, et al. (2013). Transcranial direct current stimulation (tDCS) and language. J Neurol Neurosurg Psychiatry, 84(8), 832–842. doi:10.1136/jnnp-2012-302825",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with transcranial direct current stimulation (tDCS): Challenges and future directions. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Nair DG, Renga V, Lindenberg R, Bhagya V, Schlaug G. (2011). Optimizing recovery potential through simultaneous occupational therapy and non-invasive brain-stimulation using tDCS. Restor Neurol Neurosci, 29(6), 411–420. doi:10.3233/RNN-2011-0612",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease — a new navigated focal brain therapy. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and non-invasive brain stimulation: A tale of two loops. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930. doi:10.1016/j.tics.2016.09.007",
      "Peterchev AV, Wagner TA, Miranda PC, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335. doi:10.1111/j.1525-1403.2011.00378.x",
    ],
    tavns: [
      "Hays SA, Khodaparast N, Hulsey DR, et al. (2014). Transient stimulation of vagus nerve during motor learning enhances long-term cortical reorganization. Brain Stimul, 7(5), 704–711. doi:10.1016/j.brs.2014.06.009",
      "Dawson J, Pierce D, Dixit A, et al. (2016). Safety, feasibility, and efficacy of vagus nerve stimulation paired with upper-limb rehabilitation after ischemic stroke. Stroke, 47(1), 143–150. doi:10.1161/STROKEAHA.115.010477",
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network in major depressive disorder. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Kilgard MP, Merzenich MM. (1998). Cortical map reorganization enabled by nucleus basalis activity. Science, 279(5357), 1714–1718. doi:10.1126/science.279.5357.1714",
      "Dorr AE, Bhagya V. (2017). Acute and Persistent Increase in CSF-BDNF Following Vagus Nerve Stimulation. J Neuroimmunol, 302, 23–27.",
      "Farmer AD, Strzelczyk A, Finisguerra A, et al. (2020). International consensus based review and recommendations for minimum reporting standards in research on transcutaneous vagus nerve stimulation. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of the brain-gut axis in psychiatric and inflammatory disorders. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Rong P, Liu J, Wang L, et al. (2016). Effect of transcutaneous auricular vagus nerve stimulation on major depressive disorder. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review: A safer alternative to psychopharmaceuticals in the treatment of depression. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of cranial electrotherapy stimulation for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Kavirajan HC, Lueck K, Cho K. (2014). Alternating current cranial electrotherapy stimulation (CES) use in outpatient psychiatric and pain treatment. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Cork RC, Wood P, Ming N, Shepherd C, Eddy J, Price L. (2004). The effect of cranial electrotherapy stimulation (CES) on pain associated with fibromyalgia. Internet J Anesthesiol, 8(2).",
    ],
    network: [
      "Ward NS, Cohen LG. (2004). Mechanisms underlying recovery of motor function after stroke. Arch Neurol, 61(12), 1844–1848. doi:10.1001/archneur.61.12.1844",
      "Weiller C, Chollet F, Friston KJ, et al. (1992). Functional reorganization of the brain in recovery from striatocapsular infarction in man. Ann Neurol, 31(5), 463–472. doi:10.1002/ana.410310502",
      "Fregni F, Boggio PS, Mansur CG, et al. (2005). Transcranial direct current stimulation of the unaffected hemisphere in stroke patients. NeuroReport, 16(14), 1551–1555. doi:10.1097/01.wnr.0000177010.44602.5e",
      "Pascual-Leone A, Tormos JM, Keenan J, Tarazona F, Canete C, Catala MD. (1998). Study and modulation of human cortical excitability with transcranial magnetic stimulation. J Clin Neurophysiol, 15(4), 333–343. doi:10.1097/00004691-199807000-00005",
      "Schlaug G, Renga V, Nair D. (2008). Transcranial direct current stimulation in stroke recovery. Arch Neurol, 65(12), 1571–1576. doi:10.1001/archneur.65.12.1571",
    ],
  },
};
