'use strict';
module.exports = {
  conditionFull: "Traumatic Brain Injury (TBI)",
  conditionShort: "TBI",
  conditionSlug: "tbi",
  documentNumber: "SOZO-TBI-PROT-001",
  offLabelCoverText: "tDCS and TPS use in TBI rehabilitation is INVESTIGATIONAL / OFF-LABEL. Emerging Level C evidence supports tDCS for cognitive and motor rehabilitation in mild-moderate TBI.",

  offLabelTable: [
    ['tDCS', 'CE-marked (Class IIa)', 'Off-label; Level C emerging evidence for TBI cognitive/motor rehabilitation', 'Standard informed consent + off-label note'],
    ['TPS', 'CE-marked (Class IIa)', 'INVESTIGATIONAL / OFF-LABEL', 'Mandatory off-label disclosure; Doctor signature required'],
    ['taVNS', 'CE-marked (Class IIa)', 'Off-label; exploratory evidence for TBI cognitive and mood symptoms', 'Standard informed consent + off-label note'],
    ['CES (Alpha-Stim)', 'FDA-cleared; CE-marked', 'FDA-cleared for anxiety/depression/insomnia; off-label for TBI', 'Standard informed consent + off-label note'],
  ],

  inclusionCriteria: [
    "Confirmed diagnosis of TBI (mild, moderate, or severe — stable phase) by neurologist or rehabilitation physician",
    "Post-acute phase: minimum 3 months post-injury for cognitive/behavioural protocols",
    "Age 18–70 years (exceptions at Doctor discretion with documented rationale)",
    "Stable neurological status — no evidence of active haemorrhage, oedema, or raised intracranial pressure",
    "Capacity to provide informed consent, or supported consent with legally authorised representative",
    "Willing and able to participate in rehabilitation activities concurrent with FNON sessions",
    "No absolute contraindications to any planned modality",
  ],
  exclusionCriteria: [
    "Intracranial metallic hardware in the stimulation field (surgical clips, shrapnel)",
    "Cochlear implant",
    "Active deep brain stimulator (DBS)",
    "Acute phase TBI (<3 months for standard protocols; specialist review for subacute)",
    "Uncontrolled post-traumatic epilepsy — formal neurological assessment; formal risk assessment required",
    "Active substance misuse complicating rehabilitation engagement",
    "Skull defect without cranial protection (craniotomy/craniectomy flap area) — requires capping/protection before TBI tDCS",
    "Open scalp wound or infection at electrode site",
  ],
  conditionsRequiringDiscussion: [
    "Post-traumatic epilepsy — formal risk assessment; modified parameters; seizure-free period required",
    "Moderate-severe TBI with significant cognitive impairment — adapted consent process; supported decision-making",
    "PTSD comorbidity (common in mTBI) — trauma-informed approach; coordinate with trauma-specialist",
    "Post-concussion syndrome — particular consideration for symptom monitoring; avoid over-stimulation",
    "Cardiac pacemaker — individual risk-benefit assessment by Doctor",
    "Hydrocephalus with VP shunt — neurological review; no direct contraindication but monitoring required",
    "Behavioural dysregulation post-TBI — ensure session safety procedures; adapted approach",
    "Substance misuse history — sobriety and capacity assessment",
    "Ongoing litigation/medico-legal proceedings — awareness of context; objective outcome documentation",
  ],

  overviewParagraph: "Traumatic Brain Injury (TBI) is a leading cause of death and disability globally, with an estimated 69 million individuals sustaining a TBI each year. TBI encompasses a spectrum from mild concussion (mTBI — the majority of cases) to moderate-severe injuries involving loss of consciousness, structural brain damage, and prolonged post-traumatic amnesia. The sequelae of TBI include cognitive impairment (attention, memory, executive dysfunction, processing speed), emotional and behavioural dysregulation, motor deficits, fatigue, headache, sleep disturbance, and significant psychiatric comorbidities including depression, anxiety, and PTSD. Chronic traumatic encephalopathy (CTE) represents the neurodegenerative sequela of repetitive mTBI in contact sport athletes. While acute TBI management has advanced significantly, the rehabilitation of chronic TBI sequelae remains a major unmet need, with non-invasive brain stimulation emerging as a promising adjunct to cognitive and motor rehabilitation.",
  fnonNetworkParagraph: "TBI produces diffuse axonal injury and focal contusions that disrupt large-scale brain networks across multiple domains simultaneously. Unlike focal stroke, TBI preferentially affects white matter tracts connecting network hubs, producing widespread network disconnection that manifests as cognitive slowing, attention deficits, executive dysfunction, and emotional dysregulation. The FNON framework targets the most consistently impaired networks in TBI — CEN hypoactivation (cognitive and executive deficits), SN dysregulation (emotional and behavioural symptoms), and default mode network disruption — with a particular emphasis on rebuilding network connectivity rather than isolated node stimulation.",
  networkDisorderParagraphs: [
    "The hallmark neuropathology of TBI is diffuse axonal injury (DAI) — widespread shearing of white matter axons at the grey-white matter interface and within subcortical white matter tracts during the acceleration-deceleration forces of injury. DAI preferentially affects the corpus callosum, fornix, corona radiata, and brainstem white matter — precisely the pathways connecting the prefrontal cortex, thalamus, hippocampus, and parietal networks that constitute the CEN, DMN, and SN.",
    "Advanced neuroimaging demonstrates that TBI produces widespread resting-state functional connectivity reductions across all major brain networks, with the severity of network disruption correlating with symptom severity. The CEN (DLPFC-PPC) shows the most consistent reduction in task-related activation, explaining the characteristic cognitive slowing and executive dysfunction. The default mode network shows disrupted deactivation, explaining poor task focus and sustained attention deficits. The SN (dACC-insula) shows dysregulated activation, contributing to emotional lability and behavioural dyscontrol.",
    "The chronic inflammatory response to TBI — involving activated microglia, astrogliosis, and elevated pro-inflammatory cytokines including IL-1β, TNF-α, and IL-6 — perpetuates secondary neurodegeneration months-to-years post-injury. This neuroinflammatory burden impairs synaptic plasticity and limits recovery. The anti-inflammatory effects of taVNS (via the cholinergic anti-inflammatory pathway through the vagus nerve-NTS-nucleus ambiguus-spleen axis) represent a mechanistically relevant complementary approach for TBI rehabilitation.",
  ],

  pathophysiologyText: "TBI pathophysiology involves primary injury (mechanical disruption at impact — contusions, haemorrhages, DAI) and secondary injury cascades including excitotoxicity (glutamate excess, NMDA overactivation), mitochondrial dysfunction, neuroinflammation (microglial activation, astrogliosis, cytokine release), axonal swelling and Wallerian degeneration, and cerebral blood flow dysregulation. Chronic effects include cortical thinning, white matter volume reduction, neurodegeneration (particularly in medial temporal and frontal regions), and progressive functional network disconnection. The cholinergic septohippocampal pathway is particularly vulnerable, explaining prominent memory deficits post-TBI. Neuroplasticity is paradoxically both impaired (by the inflammatory and metabolic milieu) and amplified (by injury-induced neurotrophin upregulation in the early post-injury period), creating a complex window for neuromodulation.",
  cardinalSymptoms: [
    ["Attention Deficits", "Reduced sustained attention, divided attention, and working memory capacity; cognitive slowing; easily distracted; primary CEN deficit", "~80% moderate-severe TBI; ~50% mTBI", "Mathias & Wheaton, 2007"],
    ["Executive Dysfunction", "Impaired planning, organisation, problem-solving, cognitive flexibility, inhibitory control; frontal lobe vulnerability in TBI", "~70% moderate-severe", "Stuss & Alexander, 2007"],
    ["Memory Impairment", "Post-traumatic amnesia; retrograde and anterograde amnesia; working memory and episodic memory deficits; hippocampal-fornix vulnerability", "~70%", "Vakil, 2005"],
    ["Processing Speed Reduction", "Globally slowed information processing; reaction time prolongation; most sensitive neuropsychological marker of TBI", "~85% moderate-severe", "Frencham et al., 2005"],
    ["Post-TBI Depression", "Depressive symptoms; apathy; anhedonia; frontal-limbic disruption; PTSD overlap; significantly reduces rehabilitation engagement", "~30–50% all TBI severity", "Bombardier et al., 2010"],
    ["Emotional Dysregulation", "Irritability, frustration intolerance, emotional lability, anger outbursts; OFC-amygdala pathway vulnerability", "~40–65%", "Baguley et al., 2006"],
    ["Post-Traumatic Headache", "Persistent headache post-TBI; most common physical sequela; central sensitisation; trigeminal-vascular involvement", "~80% within 3 months mTBI", "Walker, 2009"],
    ["Post-TBI Fatigue", "Pervasive fatigue; mental and physical; not proportional to exertion; most common and disabling chronic symptom", "~50–70%", "Ponsford et al., 2012"],
    ["Sleep Disturbance", "Sleep onset insomnia, hypersomnolence, circadian rhythm disruption, hypersomnia, REM sleep disorder", "~50–70%", "Baumann et al., 2007"],
    ["PTSD Symptoms", "Intrusive memories, avoidance, hyperarousal, negative cognitions; common in mTBI from violent trauma", "~15–30% mTBI with trauma context", "Hoge et al., 2008"],
    ["Motor Deficits", "Hemiparesis, incoordination, gait instability following focal motor cortex injury or brainstem TBI", "~30–40% moderate-severe", "Tagliaferri et al., 2006"],
    ["Anxiety", "Generalised anxiety, health anxiety, social anxiety; hyperarousal; SN hyperreactivity", "~25–40%", "Whelan-Goodinson et al., 2009"],
    ["Post-Concussion Syndrome", "Constellation of symptoms persisting >3 months after mTBI: headache, dizziness, cognitive symptoms, mood disturbance", "~15–30% mTBI", "Ruff et al., 2009"],
  ],
  standardGuidelinesText: [
    "TBI rehabilitation guidelines (WHO 2016, INCOG 2023, DoD/VA 2016, ABISTBI 2020) recommend a comprehensive interdisciplinary rehabilitation programme including neuropsychological rehabilitation (attention training, memory compensation, executive function training), physiotherapy, occupational therapy, and speech-language therapy as appropriate for the deficits profile. Cognitive rehabilitation approaches with robust evidence include Attention Process Training (APT), Goal Management Training (GMT), and errorless learning for memory deficits.",
    "Post-TBI psychiatric management includes antidepressants (SSRIs preferred; avoid TCAs due to seizure threshold lowering), mood stabilisers for emotional dysregulation and irritability, and non-pharmacological approaches (CBT adapted for TBI, mindfulness). Stimulants (methylphenidate, amantadine) have evidence for TBI-related cognitive deficits — methylphenidate for attention, amantadine for states of disordered consciousness in severe TBI.",
    "SOZO FNON protocols for TBI target the diffuse network dysfunction with particular emphasis on the cognitive (CEN) and emotional (limbic/SN) networks most impaired. The Doctor coordinates FNON with the interdisciplinary rehabilitation team, ensuring concurrent task practice during stimulation. Post-TBI irritability and behavioural dysregulation are assessed before each session; if elevated, stimulation parameters are reduced or session postponed.",
  ],

  fnonFrameworkParagraph: "The FNON framework for TBI addresses the diffuse network disconnection characteristic of DAI by targeting the key network hubs with residual plasticity: left DLPFC (CEN upregulation for cognitive deficits), bilateral prefrontal (emotional regulation), and autonomous modulation (taVNS for neuroinflammation, autonomic dysregulation, and BDNF release). The anti-inflammatory cholinergic pathway activated by taVNS is particularly relevant in TBI given the role of persistent neuroinflammation in limiting recovery.",
  keyBrainRegions: [
    ["Dorsolateral Prefrontal Cortex (DLPFC)", "Hypoactivation due to frontal contusions or white matter disconnection; primary cognitive and executive deficit substrate; most common focal injury site in frontal TBI", "PRIMARY COGNITIVE TARGET: anodal tDCS F3 (left DLPFC) for cognitive rehabilitation; bilateral F3/F4 for executive + emotional; TPS DLPFC", "Stuss & Alexander, 2007; Keeser et al., 2011"],
    ["Prefrontal Medial / OFC", "Emotional dysregulation, impulsivity, social judgment; OFC-amygdala pathway vulnerability in frontal TBI; personality change", "tDCS Fz/bilateral frontal; TPS mPFC/OFC for emotional dysregulation phenotype; taVNS limbic modulation", "Baguley et al., 2006"],
    ["Hippocampus", "Post-traumatic amnesia substrate; hippocampal atrophy and volume loss post-TBI; memory consolidation disruption; fornix DAI", "TPS hippocampal targeting for memory rehabilitation; taVNS BDNF hippocampal neuroplasticity", "Tate & Bigler, 2000"],
    ["Anterior Cingulate Cortex (ACC)", "Attention control, error monitoring, emotional regulation; vulnerable white matter in cingulate bundle; post-TBI attention deficit", "tDCS Fz montage; taVNS ACC modulation via vagal projections; combined with attention training", "Devinsky et al., 1995"],
    ["Thalamus", "Thalamic injuries in moderate-severe TBI; thalamo-cortical disconnection; impaired cognitive gating and arousal", "TPS thalamic indirect targeting; taVNS modulates thalamo-cortical synchrony; critical for chronic moderate-severe TBI", "Bhagya et al., 2015"],
    ["Parietal Cortex", "Attention and working memory deficits; DAI affecting parietal white matter; visuospatial and motor deficits", "Anodal tDCS P3/P4; TPS parietal for visuospatial and attention deficits", "Dosenbach et al., 2008"],
    ["Amygdala", "PTSD symptoms, emotional hyperreactivity, fear conditioning; amygdala contusions in temporal TBI", "TPS temporal-amygdala; taVNS NTS-amygdala modulation for PTSD symptoms and emotional dysregulation", "Etkin & Wager, 2007"],
    ["Cerebellum", "Ataxia and coordination deficits in posterior fossa TBI; cerebellar contusions; timing impairment", "tDCS Cbz for cerebellar TBI rehabilitation; TPS cerebellar", "Ferrucci et al., 2012"],
    ["Brainstem", "Consciousness and arousal; severe TBI brainstem injury; autonomic regulation impairment; taVNS entry point via NTS", "taVNS modulates brainstem autonomic and arousal circuits; primary route for autonomic and neuroinflammatory modulation", "Giacino et al., 2014"],
  ],
  additionalBrainStructures: [
    ["Nucleus Tractus Solitarius (NTS)", "Primary vagal relay; anti-inflammatory pathway entry point; modulates neuroinflammation via cholinergic anti-inflammatory reflex", "taVNS NTS activation — cholinergic anti-inflammatory pathway reduces TBI neuroinflammation; BDNF release", "Hays et al., 2014"],
    ["Locus Coeruleus (LC)", "Noradrenergic arousal; often depleted post-TBI; contributes to chronic fatigue and cognitive slowing", "taVNS→NTS→LC pathway restores NE tone; addresses cognitive slowing and fatigue of TBI", "Mather & Harley, 2016"],
    ["Corpus Callosum", "Most common DAI site; interhemispheric disconnection; bilateral processing deficits; marker of TBI severity", "Bilateral tDCS protocols address callosal disconnection effects; TPS for white matter repair mechanisms", "Adams et al., 1989"],
    ["Fornix", "Critical hippocampal-thalamic-cingulate memory circuit; vulnerable DAI site; memory deficit predictor", "TPS hippocampal targeting engages fornix circuit; taVNS promotes hippocampal-fornix neuroplasticity", "Gentry et al., 1988"],
    ["Basal Ganglia", "Cognitive sequencing and automatisation; DAI affecting striatal white matter; motor control; emotional regulation", "Indirect modulation via DLPFC-striatal pathway; TPS deep basal ganglia for severe TBI", "Bhagya et al., 2015"],
    ["Splenium / Corona Radiata", "White matter tracts connecting parietal-temporal-occipital; key DAI site; processing speed reduction substrate", "No direct target but tDCS/TPS of connected cortical nodes; bilateral stimulation for diffuse white matter damage", "Bigler & Maxwell, 2012"],
    ["Raphe Nuclei", "Serotonergic modulation; post-TBI depression and sleep disturbance mechanism; vulnerable to brainstem TBI", "taVNS and CES modulate serotonergic raphe via brainstem connections; particularly relevant for post-TBI depression", "Bhagya et al., 2015"],
  ],
  keyFunctionalNetworks: [
    ["Central Executive Network (CEN)", "DLPFC, PPC, lateral PFC, ACC", "Hypoactivation due to frontal contusions and DAI; cognitive slowing, executive dysfunction, attention deficits; primary rehabilitation target", "PRIMARY: anodal tDCS F3 (left DLPFC); bilateral F3/F4 for combined; TPS DLPFC; cognitive training concurrent", "Stuss & Alexander, 2007; Keeser et al., 2011"],
    ["Default Mode Network (DMN)", "mPFC, PCC, hippocampus, angular gyrus", "Failure to deactivate during cognitive tasks; intrusion during attention tasks; disrupted DMN-CEN anti-correlation", "Cathodal Pz (DMN suppression); anodal F3/F4; combined push-pull TBI approach", "Bonnelle et al., 2011"],
    ["Salience Network (SN)", "dACC, insula, amygdala", "Dysregulated — often hyperactive contributing to emotional lability, PTSD hyperarousal; impaired network switching", "taVNS for SN-autonomic modulation; tDCS Fz (dACC); TPS temporal for amygdala-SN engagement in PTSD/emotional phenotype", "Menon & Uddin, 2010"],
    ["Default Mode Network Suppression", "Thalamus, basal ganglia, anterior insula, ACC", "Failure to suppress irrelevant processing during cognitive tasks — SN gating failure post-TBI", "tDCS Fz + F3 combined; TPS SN hubs; paired attention training to maximise suppression during stimulation", "Bonnelle et al., 2012"],
    ["Reward/Motivation Network", "vmPFC, OFC, striatum, VTA", "Apathy, anhedonia, post-TBI motivational deficits; OFC vulnerability in frontal TBI", "TPS mPFC/OFC; tDCS Fz/F3 anodal; reward-contingent rehabilitation tasks", "Baguley et al., 2006"],
    ["Autonomic/Anti-inflammatory Network", "NTS, LC, brainstem, insula, ACC, vagus", "Post-TBI autonomic dysregulation; neuroinflammation; reduced HRV; fatigue; impaired recovery", "taVNS PRIMARY for anti-inflammatory and autonomic effects; CES for global arousal modulation", "Hays et al., 2014"],
    ["Memory Network", "Hippocampus, entorhinal, parahippocampal, TPJ, PCC", "Post-traumatic amnesia; encoding deficits; fornix DAI; hippocampal atrophy", "TPS hippocampal for memory rehabilitation; tDCS T3/P3 anodal; taVNS BDNF for hippocampal recovery", "Vakil, 2005"],
  ],
  networkAbnormalities: "TBI produces diffuse CEN hypoactivation, DMN failure-to-deactivate, SN dysregulation, and memory network disconnection via DAI-mediated white matter disruption. Neuroinflammation perpetuates secondary network dysfunction. The FNON approach targets CEN upregulation (tDCS/TPS) and neuroinflammation reduction (taVNS anti-inflammatory pathway).",
  conceptualFramework: "SOZO FNON TBI protocol: (1) Upregulate CEN (left/bilateral DLPFC) via tDCS/TPS during cognitive rehabilitation; (2) Modulate SN dysregulation via taVNS and targeted stimulation; (3) Reduce neuroinflammation and promote BDNF via taVNS anti-inflammatory pathway; (4) Address post-TBI mood/autonomic dysregulation via CES; (5) Concurrent rehabilitation tasks are essential.",

  clinicalPhenotypes: [
    ["Cognitive-Dominant mTBI (PCS)", "Post-concussion syndrome with cognitive slowing, attention, and memory deficits; CEN primary; left DLPFC tDCS; cognitive rehabilitation concurrent", "Ruff et al., 2009"],
    ["Executive-Dyscontrol Phenotype", "Frontal contusion pattern; impulsivity, disinhibition, poor planning; bilateral frontal + OFC target; adapted consent and session management", "Stuss & Alexander, 2007"],
    ["Post-TBI Depression/Anxiety", "Significant mood comorbidity limiting rehabilitation; CES + taVNS primary for mood; anodal tDCS F3; coordinate with psychiatry", "Bombardier et al., 2010"],
    ["Post-TBI PTSD Overlap", "mTBI + PTSD constellation; SN/amygdala hyperreactivity; trauma-informed approach; taVNS primary for limbic modulation; avoid rapid escalation", "Hoge et al., 2008"],
    ["Severe Cognitive TBI Rehabilitation", "Moderate-severe TBI; supported consent; adapted protocol; lower parameters; longer sessions; carer involvement", "Mathias & Wheaton, 2007"],
    ["Post-TBI Fatigue Dominant", "Pervasive fatigue; most limiting symptom; taVNS + CES primary; graded rehabilitation; energy management concurrent", "Ponsford et al., 2012"],
    ["Motor Deficits Post-TBI", "Hemiparesis or cerebellar deficits from focal TBI; ipsilesional M1/cerebellar target; paired physiotherapy", "Tagliaferri et al., 2006"],
    ["Sleep-Disrupted TBI", "Severe sleep disruption; hypersomnolence or insomnia; CES evening; taVNS; circadian rhythm intervention", "Baumann et al., 2007"],
    ["Chronic Severe TBI", "Prolonged rehabilitation phase (>12 months); lower neuroplasticity; maintenance approach; maximise taVNS BDNF; realistic expectations", "Giacino et al., 2014"],
  ],
  symptomNetworkMapping: [
    ["Attention Deficits", "CEN hypoactivation", "DMN failure-to-deactivate", "tDCS F3 anodal + Pz cathodal", "Attention Process Training concurrent"],
    ["Executive Dysfunction", "CEN + OFC hypoactivation", "Frontal DAI", "tDCS F3+F4 bilateral anodal", "Goal Management Training concurrent"],
    ["Memory Impairment", "Memory network disconnection", "Hippocampal-fornix DAI", "TPS hippocampal + tDCS T3/P3", "Memory encoding tasks concurrent"],
    ["Processing Speed", "White matter network disconnection", "DAI — global slowing", "tDCS bilateral F3+F4", "Speed-of-processing training concurrent"],
    ["Post-TBI Depression", "Frontal-limbic disruption", "SN/autonomic dysregulation", "CES + taVNS + anodal F3", "Structured pleasant activity concurrent"],
    ["Emotional Dysregulation", "OFC-amygdala pathway", "Frontal-limbic disconnection", "tDCS bilateral frontal + taVNS", "Emotion regulation training concurrent"],
    ["PTSD Symptoms", "SN/Amygdala hyperreactivity", "LC/NE hyperarousal", "taVNS + CES (primary); right DLPFC anodal", "Trauma-informed CBT concurrent"],
    ["Fatigue", "Autonomic + arousal network deficit", "LC NE depletion", "taVNS + CES", "Graded activity + energy management"],
    ["Sleep Disturbance", "Autonomic + circadian disruption", "LC/raphe involvement", "CES 60min evening + taVNS", "Sleep hygiene + circadian protocol"],
    ["Motor Deficits", "Motor network disruption", "Focal cortical or cerebellar damage", "tDCS ipsilesional M1/Cbz anodal", "Physiotherapy concurrent"],
  ],
  montageSelectionRows: [
    ["Cognitive-dominant mTBI (left DLPFC focus)", "Anodal F3 + Pz cathodal — 2mA 20min (push-pull)"],
    ["Executive-dyscontrol (bilateral frontal)", "Anodal F3+F4 bilateral + temporal cathodal — 1.5mA 20min"],
    ["Post-TBI depression / fatigue", "CES 0.5mA 60min + taVNS 30min + anodal F3"],
    ["PTSD-TBI overlap", "taVNS bilateral + CES (primary); conservative tDCS F4 anodal"],
    ["Memory rehabilitation", "TPS hippocampal + anodal tDCS T3/P3 — memory network"],
    ["Motor deficits (focal)", "Anodal tDCS ipsilesional M1 ± cathodal contralesional — 2mA 20min"],
    ["Cerebellar TBI", "tDCS Cbz anodal + TPS cerebellar"],
    ["Sleep-disrupted TBI", "CES 0.5mA 60min evening + taVNS pre-sleep"],
    ["Severe TBI (reduced parameters)", "tDCS 1mA 15min; CES primary; TPS 0.15mJ/mm²"],
    ["TPS — cognitive phenotype", "NEUROLITH® left DLPFC 0.2mJ/mm² 4000 pulses"],
    ["TPS — memory phenotype", "NEUROLITH® hippocampal 0.25mJ/mm² 4000 pulses"],
    ["Anti-inflammatory protocol (all phenotypes)", "taVNS bilateral 0.5mA 40min (anti-inflammatory primary)"],
    ["Maintenance phase", "tDCS 2×/week during rehabilitation; CES daily home; taVNS 3×/week"],
  ],
  polarityPrincipleText: "TBI stimulation polarity targets residual functional cortex with upregulating anodal stimulation. For diffuse cognitive deficits, bilateral DLPFC anodal is most appropriate. For focal deficits (motor, language), ipsilesional anodal with contralesional cathodal follows stroke-like principles. Cathodal Pz suppresses DMN intrusion for attention rehabilitation. For PTSD/emotional phenotype, right DLPFC anodal is prioritised with taVNS primary.",
  polarityTable: [
    ["Anodal F3 (left DLPFC)", "Primary cognitive rehabilitation target — working memory, attention, processing speed upregulation"],
    ["Anodal F3+F4 bilateral", "Executive dyscontrol and combined cognitive-emotional phenotype; bilateral frontal upregulation"],
    ["Cathodal Pz", "DMN suppression for attention deficits — combined with anodal frontal push-pull"],
    ["Anodal ipsilesional M1 (motor)", "Motor deficit rehabilitation — stroke-like approach for focal TBI motor injury"],
    ["taVNS bilateral cymba", "Anti-inflammatory, BDNF, and autonomic modulation — foundational for all TBI phenotypes"],
  ],

  classicTdcsProtocols: [
    ["C1", "Cognitive-attention TBI", "F3 (left DLPFC) anodal", "Pz cathodal", "2mA 20min, 10 sessions", "Level C"],
    ["C2", "Executive dyscontrol", "F3+F4 bilateral anodal", "Bilateral temporal cathodal", "1.5mA 20min", "Emerging"],
    ["C3", "Working memory / memory", "F3 anodal + T3/P3", "Pz cathodal", "2mA 20min", "Level C"],
    ["C4", "Post-TBI depression", "F3 anodal + CES/taVNS", "Pz cathodal", "2mA 20min", "Level C"],
    ["C5", "PTSD-TBI overlap", "F4 anodal (right DLPFC)", "Pz cathodal", "1.5mA 20min + taVNS", "Exploratory"],
    ["C6", "Motor deficits (focal)", "Ipsilesional M1 anodal", "Contralesional M1 cathodal", "2mA 20min", "Level B (stroke data)"],
    ["C7", "Cerebellar ataxia TBI", "Cbz anodal", "Contralateral Cbz cathodal", "2mA 20min", "Emerging"],
    ["C8", "Severe TBI (reduced)", "F3 anodal", "Pz cathodal", "1mA 15min", "Exploratory"],
  ],
  fnonTdcsProtocols: [
    ["F1", "Cognitive-dominant mTBI/PCS", "CEN hypoactivation + DMN intrusion", "F3 anodal + Pz cathodal (push-pull)", "Bilateral network rebalancing for cognitive rehabilitation"],
    ["F2", "Executive dyscontrol", "Bilateral frontal CEN + OFC deficit", "F3+F4 bilateral anodal + taVNS", "Maximum bilateral frontal upregulation + neuroplasticity drive"],
    ["F3", "Post-TBI depression/anxiety", "Frontal-limbic + SN dysregulation", "F3 anodal + CES + taVNS combined", "Mood and autonomic combined approach"],
    ["F4", "PTSD-TBI overlap", "SN/amygdala hyperreactivity", "taVNS PRIMARY + F4 anodal (conservative) + CES", "Limbic-autonomic stabilisation with cautious prefrontal upregulation"],
    ["F5", "Memory rehabilitation", "Hippocampal-memory network", "T3/P3 anodal + TPS hippocampal + taVNS", "Multi-modal memory circuit targeting"],
    ["F6", "Severe TBI multi-domain", "Multi-network diffuse damage", "Bilateral F3+F4 moderate + CES + taVNS (conservative)", "Cautious multi-modal approach for severe TBI"],
  ],
  classicTpsProtocols: [
    ["T1", "Cognitive / DLPFC", "Left DLPFC", "0.2mJ/mm²", "3000 pulses", "Emerging"],
    ["T2", "Memory", "Hippocampal region", "0.25mJ/mm²", "4000 pulses", "Exploratory"],
    ["T3", "Motor (focal TBI)", "Ipsilesional M1", "0.2mJ/mm²", "4000 pulses", "Emerging"],
    ["T4", "Cerebellar TBI", "Cerebellar hemisphere", "0.2mJ/mm²", "3000 pulses", "Emerging"],
    ["T5", "Combined cognitive-memory", "DLPFC + hippocampal sequential", "0.2mJ/mm²", "5000 pulses total", "Exploratory"],
  ],
  fnonTpsProtocols: [
    ["FT1", "Cognitive-dominant mTBI", "CEN DLPFC circuit", "Left DLPFC 0.2mJ/mm² × 3000 + taVNS concurrent", "Deep prefrontal cognitive circuit during cognitive rehabilitation"],
    ["FT2", "Memory rehabilitation", "Hippocampal-memory circuit", "Hippocampal 0.25mJ/mm² × 4000 + tDCS T3/P3 concurrent", "Deep memory circuit stimulation"],
    ["FT3", "Motor rehabilitation", "Ipsilesional M1", "Ipsilesional M1 0.2mJ/mm² × 4000 paired with physio", "Deep motor cortex paired physiotherapy"],
    ["FT4", "Cerebellar TBI", "Ipsilateral cerebellum", "Ipsilateral cerebellar 0.2mJ/mm² × 3000 paired with balance therapy", "Deep cerebellar stimulation for ataxia"],
    ["FT5", "Executive dyscontrol", "Bilateral frontal circuit", "Bilateral DLPFC 0.2mJ/mm² × 4000 total + taVNS", "Deep bilateral frontal executive circuit"],
    ["FT6", "Post-TBI PTSD", "Amygdala-prefrontal circuit", "Right DLPFC 0.2mJ/mm² × 2000 + taVNS primary", "Conservative prefrontal with taVNS primary for PTSD"],
    ["FT7", "Memory + executive combined", "Hippocampal + DLPFC", "Sequential hippocampal 0.25mJ/mm² × 3000 + DLPFC 0.2mJ/mm² × 2000", "Sequential memory then executive deep stimulation"],
    ["FT8", "Severe TBI conservative", "DLPFC only (conservative)", "Left DLPFC 0.15mJ/mm² × 2000 + CES primary", "Conservative deep stimulation for severe TBI"],
    ["FT9", "Maintenance protocol", "DLPFC monthly", "Left DLPFC 0.2mJ/mm² × 2000 monthly", "Monthly maintenance for TBI cognitive rehabilitation"],
  ],

  multimodalPhenotypes: [
    {
      phenotype: "Cognitive-Dominant mTBI (PCS)",
      combinations: [
        ["S — Stabilise", "taVNS 30min — noradrenergic + anti-inflammatory preparation", "Prime LC-NE arousal and reduce neuroinflammation before cognitive training"],
        ["O — Optimise", "tDCS F3 anodal + Pz cathodal 2mA 20min — push-pull CEN-DMN", "Upregulate left DLPFC and suppress DMN during cognitive rehabilitation"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 3000 — deep prefrontal circuit", "Deep prefrontal cognitive circuit stimulation"],
        ["O — Outcome", "Attention Process Training concurrent (APT) + CES evening", "Evidence-based attention training during primed CEN; evening CES for sleep and headache"],
      ],
    },
    {
      phenotype: "Executive-Dyscontrol Phenotype",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 30min — reduce irritability baseline before frontal stimulation", "Reduce behavioural dysregulation threshold; stabilise before bilateral prefrontal stimulation"],
        ["O — Optimise", "tDCS F3+F4 bilateral 1.5mA 20min — bilateral frontal upregulation", "Bilateral prefrontal CEN and OFC upregulation for executive and emotional control"],
        ["Z — Zone", "TPS bilateral DLPFC 0.2mJ/mm² 4000 total — deep bilateral frontal", "Deep bilateral frontal executive circuit stimulation"],
        ["O — Outcome", "Goal Management Training (GMT) concurrent — metacognitive rehabilitation", "Evidence-based executive rehabilitation concurrent with primed bilateral frontal circuits"],
      ],
    },
    {
      phenotype: "Post-TBI Depression/Anxiety",
      combinations: [
        ["S — Stabilise", "taVNS 40min + CES 60min — primary mood and autonomic modalities", "Maximum autonomic-limbic stabilisation for post-TBI mood comorbidity"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min — left DLPFC antidepressant circuit", "Prime prefrontal antidepressant circuit; coordinate with pharmacotherapy"],
        ["Z — Zone", "TPS left DLPFC 0.2mJ/mm² 3000 + limbic deep — mood circuit", "Deep prefrontal-limbic mood circuit stimulation"],
        ["O — Outcome", "Structured pleasant activity + graded rehabilitation engagement — consolidate", "Behavioural activation with improved mood; enhanced rehabilitation motivation"],
      ],
    },
    {
      phenotype: "Post-TBI PTSD Overlap",
      combinations: [
        ["S — Stabilise", "taVNS 40min — primary limbic modulation; gradual approach", "Trauma-informed: taVNS PRIMARY for autonomic regulation before any cortical stimulation"],
        ["O — Optimise", "CES 0.5mA 60min — arousal downregulation for PTSD hyperarousal", "Reduce SN hyperreactivity and hyperarousal baseline"],
        ["Z — Zone", "tDCS F4 anodal 1.5mA 15min (conservative) — right DLPFC inhibitory control", "Conservative right prefrontal upregulation for emotional regulation of PTSD symptoms"],
        ["O — Outcome", "Trauma-informed CBT concurrent — PE or CPT elements adapted for TBI", "Trauma processing therapy concurrent with stabilised autonomic state"],
      ],
    },
    {
      phenotype: "Severe Cognitive TBI Rehabilitation",
      combinations: [
        ["S — Stabilise", "taVNS 30min + CES 30min — gentle autonomic and neuroplasticity preparation", "Gentle combined preparation; assess tolerance; longer acclimatisation phase"],
        ["O — Optimise", "tDCS F3 anodal 1mA 15min (conservative) — reduced parameters for severe TBI", "Conservative DLPFC upregulation; slower parameter build-up"],
        ["Z — Zone", "TPS left DLPFC 0.15mJ/mm² 2000 — conservative for severe TBI", "Conservative deep stimulation adapted for severe TBI with carer supervision"],
        ["O — Outcome", "Carer-supported cognitive activities + errorless learning approach", "Structured, carer-supported cognitive tasks using errorless learning principles"],
      ],
    },
    {
      phenotype: "Post-TBI Fatigue Dominant",
      combinations: [
        ["S — Stabilise", "CES 0.5mA 60min — primary fatigue modality; broad-spectrum arousal", "Address fatigue via autonomic and arousal circuit modulation as primary approach"],
        ["O — Optimise", "taVNS 40min — noradrenergic restoration; anti-inflammatory", "Restore LC-NE arousal signalling; reduce neuroinflammatory burden perpetuating fatigue"],
        ["Z — Zone", "tDCS F3 anodal 1.5mA 15min — mild prefrontal upregulation (conservative)", "Gentle prefrontal upregulation; avoid over-stimulation that worsens fatigue"],
        ["O — Outcome", "Graded energy management + sleep hygiene concurrent — consolidate", "Evidence-based fatigue management concurrent with neural priming"],
      ],
    },
    {
      phenotype: "Motor Deficits Post-TBI",
      combinations: [
        ["S — Stabilise", "taVNS 30min — neuroplasticity priming for motor rehabilitation", "Prime neuroplasticity via NTS-LC pathway before motor cortex stimulation"],
        ["O — Optimise", "tDCS ipsilesional M1 anodal 2mA 20min ± cathodal contralesional", "Perilesional motor cortex excitability upregulation"],
        ["Z — Zone", "TPS ipsilesional M1 0.2mJ/mm² 4000 — deep motor circuit", "Deep motor cortex paired with physiotherapy"],
        ["O — Outcome", "Task-specific physiotherapy concurrent + home exercise programme", "Motor rehabilitation concurrent with primed motor circuits"],
      ],
    },
    {
      phenotype: "Sleep-Disrupted TBI",
      combinations: [
        ["S — Stabilise", "taVNS afternoon 20min — pre-evening autonomic preparation", "Shift autonomic balance toward parasympathetic dominance pre-sleep"],
        ["O — Optimise", "tDCS F3 anodal 2mA 20min (daytime) — address daytime cognitive component", "Daytime cognitive priming; avoid evening stimulation that may worsen sleep"],
        ["Z — Zone", "CES 0.5mA 60min evening — primary sleep facilitation modality", "Evening autonomic downregulation; sleep-onset facilitation"],
        ["O — Outcome", "Sleep restriction therapy + light therapy morning — consolidate", "Evidence-based sleep therapy with circadian anchors"],
      ],
    },
    {
      phenotype: "Memory Rehabilitation",
      combinations: [
        ["S — Stabilise", "taVNS 30min — BDNF and neuroplasticity priming for memory circuit", "Hippocampal BDNF preparation via NTS-LC pathway"],
        ["O — Optimise", "tDCS T3/P3 anodal 2mA 20min — temporal-parietal memory circuit", "Prime temporal-parietal memory encoding circuit"],
        ["Z — Zone", "TPS hippocampal 0.25mJ/mm² 4000 — deep hippocampal circuit", "Deep hippocampal memory circuit stimulation"],
        ["O — Outcome", "Memory encoding/recall tasks concurrent + spaced retrieval practice", "Evidence-based memory rehabilitation concurrent with primed circuits"],
      ],
    },
  ],

  taskPairingRows: [
    ["Attention Process Training (APT)", "Cognitive-dominant mTBI/PCS", "tDCS F3 anodal + Pz cathodal active", "Hierarchical attention training — alerting, sustained, selective, alternating, divided"],
    ["Goal Management Training (GMT)", "Executive dyscontrol", "tDCS F3+F4 bilateral active", "Metacognitive stop-pause-check strategy training for daily executive tasks"],
    ["Memory Encoding Tasks", "Memory rehabilitation", "TPS post-session (plasticity window)", "Word-list learning, face-name association, prospective memory tasks"],
    ["Processing Speed Training", "mTBI cognitive slowing", "tDCS F3 active", "Speed-of-processing computerised training (e.g. Useful Field of View)"],
    ["Energy Management / Pacing", "Post-TBI fatigue", "CES + taVNS active", "Graded activity scheduling; fatigue log; pacing strategy practice"],
    ["Physiotherapy Motor Tasks", "Motor deficits", "tDCS ipsilesional M1 active + taVNS concurrent", "Task-specific motor relearning concurrent with stimulation"],
  ],
  outcomeMeasures: "Primary: Montreal Cognitive Assessment (MoCA), Trail Making Test A/B (attention/processing speed), BRIEF-A (executive function; self and carer report), at baseline, 5-session, 10-session, 1-month follow-up. Secondary: digit span, California Verbal Learning Test (CVLT-II for memory), Rivermead Post-Concussion Symptoms Questionnaire, PHQ-9 (depression), GAD-7 (anxiety), PSQI (sleep), Fatigue Severity Scale (FSS), Sheehan Disability Scale. Safety: monitor for post-TBI seizure; headache increase; skin inspection.",

  medicationSectionTitle: "Pharmacotherapy Context for TBI",
  medicationSectionText: "Pharmacotherapy for TBI cognitive and psychiatric sequelae includes: stimulants for attention and cognitive speed (methylphenidate — evidence-based for attention in TBI; amantadine — FDA-approved for disorders of consciousness in severe TBI; also cognitive benefit in chronic TBI); SSRIs for post-TBI depression and anxiety (sertraline preferred; note seizure risk with some antidepressants); mood stabilisers for emotional dysregulation and irritability (valproate, carbamazepine — also anticonvulsant relevant given post-TBI seizure risk); melatonin for sleep disturbance (preferred over benzodiazepines). The Doctor coordinates FNON timing with stimulant administration — tDCS may show additive effects with methylphenidate on DLPFC upregulation. Anticholinergic medications should be avoided where possible as they impair the cholinergic plasticity mechanisms targeted by taVNS.",

  references: {
    foundational: [
      "Dewan MC, Rattani A, Gupta S, et al. (2018). Estimating the global incidence of traumatic brain injury. J Neurosurg, 130(4), 1080–1097. doi:10.3171/2017.10.JNS17352",
      "Maas AI, Stocchetti N, Bullock R. (2008). Moderate and severe traumatic brain injury in adults. Lancet Neurol, 7(8), 728–741. doi:10.1016/S1474-4422(08)70164-9",
      "Stuss DT, Alexander MP. (2007). Is there a dysexecutive syndrome? Philos Trans R Soc Lond B Biol Sci, 362(1481), 901–915. doi:10.1098/rstb.2007.2096",
      "Bigler ED. (2007). Anterior and middle cranial fossa in traumatic brain injury. Neuropsychology, 21(5), 515–531. doi:10.1037/0894-4105.21.5.515",
      "Mathias JL, Wheaton P. (2007). Changes in attention and information-processing speed following severe traumatic brain injury. Neuropsychology, 21(2), 212–223. doi:10.1037/0894-4105.21.2.212",
      "Bonnelle V, Leech R, Kinnunen KM, et al. (2011). Default mode network connectivity predicts sustained attention deficits after traumatic brain injury. J Neurosci, 31(38), 13442–13451. doi:10.1523/JNEUROSCI.1163-11.2011",
    ],
    tdcs: [
      "Keeser D, Meindl T, Bor J, et al. (2011). Prefrontal transcranial direct current stimulation changes connectivity of resting-state networks during fMRI. J Neurosci, 31(43), 15284–15293. doi:10.1523/JNEUROSCI.0542-11.2011",
      "Lefaucheur JP, Antal A, Ayache SS, et al. (2017). Evidence-based guidelines on the therapeutic use of transcranial direct current stimulation (tDCS). Clin Neurophysiol, 128(1), 56–92. doi:10.1016/j.clinph.2016.10.087",
      "Bikson M, Grossman P, Thomas C, et al. (2016). Safety of transcranial direct current stimulation: Evidence based update 2016. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Polanía R, Nitsche MA, Ruff CC. (2018). Studying and modifying brain function with non-invasive brain stimulation. Nat Neurosci, 21(2), 174–187. doi:10.1038/s41593-017-0054-4",
      "Brunoni AR, Nitsche MA, Bolognini N, et al. (2012). Clinical research with transcranial direct current stimulation (tDCS): Challenges and future directions. Brain Stimul, 5(3), 175–195. doi:10.1016/j.brs.2011.03.002",
      "Nitsche MA, Paulus W. (2000). Excitability changes induced in the human motor cortex by weak transcranial direct current stimulation. J Physiol, 527(3), 633–639. doi:10.1111/j.1469-7793.2000.t01-1-00633.x",
    ],
    tps: [
      "Beisteiner R, Matt E, Fan C, et al. (2020). Transcranial pulse stimulation with ultrasound in Alzheimer's disease. Adv Sci, 7(3), 1902583. doi:10.1002/advs.201902583",
      "Zrenner C, Belardinelli P, Müller-Dahlhaus F, Ziemann U. (2016). Closed-loop neuroscience and non-invasive brain stimulation. Front Cell Neurosci, 10, 92. doi:10.3389/fncel.2016.00092",
      "Bikson M, et al. (2016). Safety of transcranial direct current stimulation. Brain Stimul, 9(5), 641–661. doi:10.1016/j.brs.2016.06.004",
      "Helfrich RF, Knight RT. (2016). Oscillatory dynamics of prefrontal cognitive control. Trends Cogn Sci, 20(12), 916–930. doi:10.1016/j.tics.2016.09.007",
      "Peterchev AV, et al. (2012). Fundamentals and applications of transcranial electric and magnetic stimulation dose. Neuromodulation, 15(4), 314–335. doi:10.1111/j.1525-1403.2011.00378.x",
    ],
    tavns: [
      "Hays SA, Khodaparast N, Hulsey DR, et al. (2014). Transient stimulation of vagus nerve during motor learning enhances long-term cortical reorganization. Brain Stimul, 7(5), 704–711. doi:10.1016/j.brs.2014.06.009",
      "Fang J, Rong P, Hong Y, et al. (2016). Transcutaneous vagus nerve stimulation modulates default mode network. Biol Psychiatry, 79(4), 266–273. doi:10.1016/j.biopsych.2015.03.025",
      "Farmer AD, et al. (2020). International consensus based review on transcutaneous vagus nerve stimulation. Front Hum Neurosci, 14, 568051. doi:10.3389/fnhum.2020.568051",
      "Breit S, Kupferberg A, Rogler G, Hasler G. (2018). Vagus nerve as modulator of brain-gut axis. Front Psychiatry, 9, 44. doi:10.3389/fpsyt.2018.00044",
      "Mather M, Harley CW. (2016). The locus coeruleus: Essential for maintaining cognitive function and the aging brain. Trends Cogn Sci, 20(3), 214–226. doi:10.1016/j.tics.2016.01.001",
      "Steenbergen L, et al. (2015). Transcutaneous vagus nerve stimulation (tVNS) enhances response inhibition via norepinephrine on prefrontal cortex. Brain Stimul, 8(6), 1155–1160. doi:10.1016/j.brs.2015.09.001",
      "Burger AM, et al. (2020). Transcutaneous vagus nerve stimulation reduces the startle response in anxious individuals. Biol Psychol, 149, 107800. doi:10.1016/j.biopsycho.2019.107800",
      "Rong P, et al. (2016). Effect of transcutaneous auricular vagus nerve stimulation on major depressive disorder. J Affect Disord, 195, 172–179. doi:10.1016/j.jad.2016.02.031",
    ],
    ces: [
      "Kirsch DL, Nichols F. (2013). Cranial electrotherapy stimulation for treatment of anxiety, depression, and insomnia. Psychiatr Clin North Am, 36(1), 169–176. doi:10.1016/j.psc.2013.01.006",
      "Gilula MF, Kirsch DL. (2005). Cranial electrotherapy stimulation review. J Neurother, 9(2), 7–26. doi:10.1300/J184v09n02_02",
      "Bystritsky A, Kerwin L, Feusner J. (2008). A pilot study of CES for generalized anxiety disorder. J Clin Psychiatry, 69(3), 412–417. doi:10.4088/JCP.v69n0311",
      "Kavirajan HC, Lueck K, Cho K. (2014). Alternating current CES use in outpatient psychiatric and pain treatment. J Psychiatr Pract, 20(5), 332–343. doi:10.1097/01.pra.0000454776.71069.18",
      "Cork RC, Wood P, Ming N, Shepherd C, Eddy J, Price L. (2004). The effect of CES on pain associated with fibromyalgia. Internet J Anesthesiol, 8(2).",
    ],
    network: [
      "Bonnelle V, Leech R, Kinnunen KM, et al. (2011). Default mode network connectivity predicts sustained attention deficits after TBI. J Neurosci, 31(38), 13442–13451. doi:10.1523/JNEUROSCI.1163-11.2011",
      "Bonnelle V, Ham TE, Leech R, et al. (2012). Salience network integrity predicts default mode network function after traumatic brain injury. Proc Natl Acad Sci USA, 109(12), 4690–4695. doi:10.1073/pnas.1113455109",
      "Sharp DJ, Beckmann CF, Greenwood R, et al. (2011). Default mode network functional and structural connectivity after traumatic brain injury. Brain, 134(8), 2233–2247. doi:10.1093/brain/awr175",
      "Menon V, Uddin LQ. (2010). Saliency, switching, attention and control: A network model of insula function. Brain Struct Funct, 214(5–6), 655–667. doi:10.1007/s00429-010-0262-0",
      "Mather M, Harley CW. (2016). The locus coeruleus: Essential for maintaining cognitive function and the aging brain. Trends Cogn Sci, 20(3), 214–226. doi:10.1016/j.tics.2016.01.001",
    ],
  },
};
