"""Append stroke_rehab, tbi, chronic_pain to partners_all_in_one_data.py"""
import os
data_file = os.path.join(os.path.dirname(__file__), 'partners_all_in_one_data.py')

def _ph(code, name, s1, s2, s3, s4, nl1, nl2, nl3, nr1, nr2, nr3, nr4,
        bt, combos, task, hyp):
    return {
        'code': code, 'name': name,
        'sozo_bar': [s1, s2, s3, s4],
        'card_left': [nl1, nl2, nl3],
        'card_right': [nr1, nr2, nr3, nr4],
        'brain_targets': bt,
        'combinations': combos,
        'task_pairing': task,
        'fnon_hypothesis': hyp,
    }

stroke_chunk = '''
PARTNERS_CONDITIONS['stroke_rehab'] = {
    'condition_full': 'Stroke Rehabilitation & Motor Recovery',
    'condition_short': 'Stroke',
    'condition_slug': 'stroke_rehab',
    'fnon_classification': 'SMN asymmetry / CEN hypofunction / LIMBIC depression-overlap',
    'fnon_montage_selection': [
        ['Motor dominant (UE paresis)', 'HDCstim tDCS C3 anode (ipsilesional M1)'],
        ['Language (Broca/Wernicke)', 'HDCstim tDCS F5 anode / cathodal contra'],
        ['Cognitive impairment', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Depression post-stroke', 'tDCS F3 anode / F4 cathode DLPFC LH'],
        ['Pain post-stroke', 'tDCS C3/C4 anodes + CES'],
    ],
    'tps': [
        ['T1', 'Motor cortex excitability (ipsilesional)', 'M1 ipsilesional (C3/C4)', '0.25 mJ/mm²', '1200 pulses', 'Evidence A'],
        ['T2', 'M1 contralateral suppression', 'M1 contralesional', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T3', 'Language recovery (Broca)', 'F5 / Broca area', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'DLPFC cognitive recovery', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Post-stroke depression', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'SMN ipsilesional activation', 'SMN hypofunction', 'M1/SMA ipsilesional', 'Motor re-recruitment', '0.25 mJ/mm²', '1200 pulses', '15 sessions'],
        ['FT2', 'Contralesional inhibition', 'SMN asymmetry', 'M1 contralesional cathode', 'Interhemispheric balance', '0.20 mJ/mm²', '800 pulses', '15 sessions'],
        ['FT3', 'CEN cognitive restoration', 'CEN hypofunction', 'DLPFC F3/F4', 'Executive recovery', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT4', 'Language network', 'Language network damage', 'Broca F5 + Wernicke T5', 'Aphasia rehabilitation', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
        ['FT5', 'Attention network', 'ATTENTION hypofunction', 'IPS P3/P4', 'Neglect + attention', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT6', 'Post-stroke depression', 'LIMBIC dysregulation', 'DLPFC L + vmPFC', 'Mood recovery', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT7', 'Spasticity modulation', 'SMN hyperexcitability', 'M1 contralesional', 'Spasticity reduction', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Visual field recovery', 'Visual network', 'O1/O2 occipital', 'Visual cortex activation', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT9', 'Gait and balance', 'SMN + CEN', 'SMA Fz + M1 bilateral', 'Gait pattern restoration', '0.25 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Motor excitability', 'C3 anode (ipsilesional) / C4 cathode', '2 mA', '20 min', 'Evidence A'],
        ['C2', 'Bihemispheric motor', 'C3 anode / C4 cathode (cross)', '2 mA', '20 min', 'Evidence A'],
        ['C3', 'Language (Broca)', 'F5 anode / F6 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Post-stroke depression', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C5', 'Cognitive rehab', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C6', 'Neglect (attention)', 'P4 anode / P3 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C7', 'Pain post-stroke', 'C3/C4 bilateral / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C8', 'Swallowing (dysphagia)', 'Pharyngeal M1 / C5 electrode', '2 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'SMN rebalance', 'SMN asymmetry', 'C3 anode / C4 cathode', 'Ipsilesional motor boost', '2 mA', '20 min'],
        ['F2', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz cathode', 'Cognitive recovery', '2 mA', '20 min'],
        ['F3', 'Language network', 'Language deficit', 'F5 anode / contralateral cathode', 'Aphasia support', '2 mA', '20 min'],
        ['F4', 'Mood recovery', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Post-stroke depression', '2 mA', '20 min'],
        ['F5', 'Attention/neglect', 'ATTENTION lateralized', 'P4 anode / P3 cathode', 'Unilateral neglect', '2 mA', '20 min'],
        ['F6', 'Pain modulation', 'SN/pain network', 'C3/C4 / Oz cathode', 'Post-stroke pain', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Motor priming', 'Variant E', 'C3/C4', '1.6 mA', '20 min', 'Pre-physiotherapy'],
        ['C2-PS', 'Cognitive rehab', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Cognitive exercises'],
        ['C3-PS', 'Language support', 'Variant C', 'F5/F6', '1.4 mA', '20 min', 'Speech therapy'],
        ['C4-PS', 'Mood uplift', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Post-stroke depression'],
        ['C5-PS', 'Attention rehab', 'Variant B', 'P3/P4', '1.4 mA', '20 min', 'Neglect therapy'],
        ['C6-PS', 'Fatigue reduction', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Post-stroke fatigue'],
        ['C7-PS', 'Spasticity support', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'Combined spasticity'],
        ['C8-PS', 'Pain modulation', 'Variant E', 'Cz/C3', '1.4 mA', '20 min', 'Central pain'],
    ],
    'fnon_plato': [
        ['FP1', 'SMN activation', 'SMN hypofunction', 'Variant E', 'C3/C4', '1.6 mA', '20 min'],
        ['FP2', 'CEN recovery', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'Language', 'Language network', 'Variant C', 'F5/F6', '1.4 mA', '20 min'],
        ['FP4', 'LIMBIC mood', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP5', 'Attention network', 'ATTENTION deficit', 'Variant B', 'P3/P4', '1.4 mA', '20 min'],
        ['FP6', 'Fatigue-SMN', 'Post-stroke fatigue', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Hemiparesis (Upper Limb)',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3 ipsilesional', 'TPS M1 ipsilesional', 'Arm rehab task'],
            'card_left': ['Network: SMN asymmetry', 'Key target: M1 ipsilesional, SMA', 'Priority: Motor reactivation'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'taVNS: 20 min pre'],
            'brain_targets': [
                ['M1 ipsilesional', 'Motor output', 'Activate', 'T1 / C1 / FP1', 'Evidence A'],
                ['SMA', 'Motor planning', 'Upregulate', 'FT9 / Fz', 'Evidence B'],
                ['M1 contralesional', 'Inhibitory balance', 'Suppress', 'T2 / C2 cathode', 'Evidence A'],
                ['Cerebellum', 'Motor coordination', 'TPS bilateral', 'TPS lateral', 'Emerging'],
                ['PMC', 'Premotor', 'Activate', 'TPS F3/F4', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 ipsilesional', 'TPS M1', 'Arm physio 30 min'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS SMA', 'Mirror therapy'],
                ['taVNS 20 min', 'tDCS bihemispheric', 'TPS M1+PMC', 'Robot-assisted arm'],
                ['CES 20 min', 'tDCS C1', 'TPS M1 bilateral', 'FES combined'],
            ],
            'task_pairing': 'Arm physiotherapy, mirror therapy, robot-assisted rehabilitation, FES (functional electrical stimulation).',
            'fnon_hypothesis': 'Hemiparesis reflects SMN ipsilesional silencing with contralesional hyperexcitability. Paired tDCS + TPS + motor task drives Hebbian re-recruitment of paretic motor cortex.',
        },
        {
            'code': 'P2', 'name': 'Aphasia (Language)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F5 Broca anode', 'TPS Broca + Wernicke', 'Speech therapy task'],
            'card_left': ['Network: Language network damage', 'Key target: Broca F5, Wernicke T5', 'Priority: Language network reactivation'],
            'card_right': ['TPS: T3 + FT4', 'tDCS: C3/F3', 'PlatoScience: C3-PS/FP3', 'SLT concurrent'],
            'brain_targets': [
                ['Broca area', 'Speech production', 'Activate', 'T3 / C3 / FP3', 'Evidence B'],
                ['Wernicke area', 'Comprehension', 'Activate', 'TPS T5/T6', 'Evidence B'],
                ['SMA', 'Speech initiation', 'Support', 'TPS Fz', 'Emerging'],
                ['Right IFG', 'Compensation', 'Modulate', 'TPS F6', 'Emerging'],
                ['DLPFC', 'Verbal working mem', 'Activate', 'C5 / FP2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F5 anode', 'TPS Broca', 'SLT naming tasks'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS Wernicke', 'Comprehension exercises'],
                ['taVNS 20 min', 'tDCS C3', 'TPS Broca+SMA', 'CIAT intensive'],
                ['CES 20 min', 'tDCS F3', 'TPS bilateral language', 'Reading aloud'],
            ],
            'task_pairing': 'Constraint-Induced Aphasia Therapy (CIAT), naming tasks, reading aloud, comprehension exercises during stimulation.',
            'fnon_hypothesis': 'Aphasia reflects language network node damage with perilesional suppression. tDCS + TPS applied concurrent with SLT maximizes activity-dependent plasticity in remaining language nodes.',
        },
        {
            'code': 'P3', 'name': 'Post-Stroke Cognitive Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC', 'Cognitive rehab task'],
            'card_left': ['Network: CEN hypofunction + DMN disruption', 'Key target: DLPFC, PFC bilateral', 'Priority: Cognitive reactivation'],
            'card_right': ['TPS: T4 + FT3', 'tDCS: C5/F2', 'PlatoScience: C2-PS/FP2', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC', 'Working memory', 'Activate', 'T4 / C5 / FP2', 'Emerging'],
                ['PFC bilateral', 'Executive function', 'Upregulate', 'T1+T2 / C5', 'Emerging'],
                ['Hippocampus', 'Episodic memory', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
                ['ACC', 'Attention', 'Activate', 'TPS Fz', 'Emerging'],
                ['Parietal', 'Visuospatial', 'Activate', 'TPS P3/P4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Cognitive rehab program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS DLPFC bilateral', 'Memory training'],
                ['taVNS 20 min', 'tDCS C5', 'TPS ACC', 'Attention tasks'],
                ['CES 20 min', 'tDCS F3', 'TPS parietal', 'Visuospatial exercises'],
            ],
            'task_pairing': 'Cognitive rehabilitation program, working memory training, attention tasks, visuospatial exercises.',
            'fnon_hypothesis': 'Post-stroke cognitive impairment reflects CEN node damage reducing prefrontal executive capacity. Bilateral DLPFC stimulation rebuilds functional connectivity supporting cognitive recovery.',
        },
        {
            'code': 'P4', 'name': 'Post-Stroke Depression',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood recovery'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C4/F4', 'PlatoScience: C4-PS/FP4', 'BA protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood regulation', 'Activate', 'T5 / C4 / FP4', 'Evidence B'],
                ['vmPFC', 'Reward processing', 'Normalize', 'T3 / F3', 'Emerging'],
                ['ACC', 'Emotional processing', 'Modulate', 'T4 / C5', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation schedule'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasant events planning'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'Activity monitoring'],
                ['CES 20 min', 'tDCS F4', 'TPS bilateral DLPFC', 'Mood diary'],
            ],
            'task_pairing': 'Behavioral activation schedule, pleasant events planning, activity monitoring, mood diary.',
            'fnon_hypothesis': 'Post-stroke depression reflects LIMBIC disinhibition due to prefrontal damage. L-DLPFC tDCS + TPS rebuilds top-down mood regulation capacity.',
        },
        {
            'code': 'P5', 'name': 'Unilateral Neglect',
            'sozo_bar': ['taVNS 20 min', 'tDCS P4 anode', 'TPS parietal R', 'Neglect scanning task'],
            'card_left': ['Network: ATTENTION lateralized (R parietal)', 'Key target: IPS R, P4', 'Priority: Attention rebalancing'],
            'card_right': ['TPS: FT5 + T4', 'tDCS: C6/F5', 'PlatoScience: C5-PS/FP5', 'Scanning task'],
            'brain_targets': [
                ['IPS R (P4)', 'Spatial attention', 'Activate', 'FT5 / C6 / FP5', 'Evidence B'],
                ['IPS L (P3)', 'Competing attention', 'Inhibit (cathode)', 'C6 cathode', 'Evidence B'],
                ['FEF R', 'Eye movement', 'Activate', 'TPS F8', 'Emerging'],
                ['DLPFC R', 'Attention top-down', 'Activate', 'T2 / C2', 'Emerging'],
                ['TPJ R', 'Attention reorienting', 'Activate', 'TPS T6', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS P4 anode', 'TPS IPS R', 'Scanning training'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS FEF R', 'Prism adaptation'],
                ['taVNS 20 min', 'tDCS C6', 'TPS TPJ R', 'Visual search tasks'],
                ['CES 20 min', 'tDCS bihemispheric P', 'TPS IPS bilateral', 'Limb activation'],
            ],
            'task_pairing': 'Visual scanning training, prism adaptation therapy, limb activation exercises, visual search tasks.',
            'fnon_hypothesis': 'Unilateral neglect reflects right parietal network silencing post-stroke. Activating IPS/TPJ R while inhibiting contralesional parietal restores attentional balance.',
        },
        {
            'code': 'P6', 'name': 'Gait and Balance Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS SMA/M1 bilateral', 'TPS SMA + cerebellum', 'Gait therapy'],
            'card_left': ['Network: SMN bilateral + cerebellar', 'Key target: SMA, M1 bilateral', 'Priority: Gait pattern restoration'],
            'card_right': ['TPS: FT9 + T1', 'tDCS: C1+C2/F1', 'PlatoScience: C1-PS/FP1', 'Gait task'],
            'brain_targets': [
                ['SMA', 'Gait initiation', 'Activate', 'FT9 / Fz', 'Evidence B'],
                ['M1 bilateral', 'Leg motor', 'Activate', 'T1 / C1+C2', 'Evidence B'],
                ['Cerebellum', 'Balance/coordination', 'Activate', 'TPS lateral', 'Emerging'],
                ['Basal ganglia', 'Gait rhythm', 'Modulate (TPS)', 'TPS frontal', 'Emerging'],
                ['PMC', 'Gait planning', 'Activate', 'TPS F3/F4', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS SMA bilateral', 'TPS SMA', 'Treadmill gait therapy'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS cerebellum', 'Balance board training'],
                ['taVNS 20 min', 'tDCS C1+C2', 'TPS M1 bilateral', 'Overground gait'],
                ['CES 20 min', 'tDCS Fz', 'TPS SMA+basal G', 'Rhythmic cue gait'],
            ],
            'task_pairing': 'Treadmill gait therapy, balance board training, rhythmic auditory cue gait, overground walking tasks.',
            'fnon_hypothesis': 'Post-stroke gait impairment reflects SMA-M1 bilateral circuit disruption. SMA TPS during treadmill training restores gait initiation programming.',
        },
        {
            'code': 'P7', 'name': 'Dysphagia (Swallowing)',
            'sozo_bar': ['taVNS 20 min', 'tDCS pharyngeal M1', 'TPS Cz swallowing', 'Swallowing therapy'],
            'card_left': ['Network: Swallowing motor network', 'Key target: Pharyngeal M1, Cz', 'Priority: Swallowing reflex restoration'],
            'card_right': ['TPS: T1 bilateral + FT1', 'tDCS: C8/F1', 'PlatoScience: C1-PS/FP1', 'SLP task'],
            'brain_targets': [
                ['Pharyngeal M1', 'Swallowing motor', 'Activate', 'T1 Cz / C8', 'Evidence B'],
                ['Insula', 'Swallowing integration', 'Activate', 'TPS C3', 'Emerging'],
                ['SMA', 'Swallowing planning', 'Support', 'TPS Fz', 'Emerging'],
                ['Brainstem', 'Reflex arc (taVNS)', 'Modulate', 'taVNS protocol', 'Emerging'],
                ['M1 ipsilesional', 'Compensation', 'Activate', 'T1 / C1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS Cz bilateral', 'TPS pharyngeal M1', 'Swallowing exercises SLP'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS insula', 'Texture progression'],
                ['taVNS 20 min', 'tDCS C8', 'TPS Cz', 'Neuromuscular E-stim'],
                ['CES 20 min', 'tDCS F1', 'TPS SMA', 'Pharyngeal maneuvers'],
            ],
            'task_pairing': 'SLP swallowing exercises, texture progression protocols, neuromuscular electrical stimulation, pharyngeal maneuvers.',
            'fnon_hypothesis': 'Dysphagia reflects pharyngeal motor cortex silencing. Bilateral Cz tDCS + TPS during SLP exercises activates both hemispheric swallowing representations.',
        },
        {
            'code': 'P8', 'name': 'Spasticity & Tone Management',
            'sozo_bar': ['taVNS 20 min', 'tDCS M1 contralesional', 'TPS contralesional M1', 'Stretching program'],
            'card_left': ['Network: SMN hyperexcitability contralesional', 'Key target: M1 contralesional', 'Priority: Interhemispheric balance'],
            'card_right': ['TPS: T2 + FT7', 'tDCS: C2/F1', 'PlatoScience: C7-PS/FP6', 'Stretch + splint'],
            'brain_targets': [
                ['M1 contralesional', 'Spasticity drive', 'Suppress', 'T2 / C2 cathode', 'Evidence B'],
                ['M1 ipsilesional', 'Voluntary control', 'Activate', 'T1 / C1', 'Evidence B'],
                ['SMA', 'Movement initiation', 'Balance', 'FT9 / Fz', 'Emerging'],
                ['Thalamus', 'Motor relay', 'Modulate (taVNS)', 'taVNS', 'Emerging'],
                ['Cerebellum', 'Tone modulation', 'Activate', 'TPS lateral', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS M1 contra cathode', 'TPS contralesional', 'Stretching + splinting'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS M1 balance', 'Botox timing support'],
                ['taVNS 20 min', 'tDCS C2', 'TPS SMA', 'Active movement practice'],
                ['CES 20 min', 'tDCS bihemispheric', 'TPS cerebellum', 'Constraint therapy'],
            ],
            'task_pairing': 'Passive stretching, splinting program, constraint-induced movement therapy, active range of motion exercises.',
            'fnon_hypothesis': 'Spasticity reflects contralesional M1 disinhibition dominating the paretic limb. Suppressing contralesional M1 via cathodal tDCS + inhibitory TPS restores interhemispheric balance.',
        },
        {
            'code': 'P9', 'name': 'Post-Stroke Fatigue',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Energy conservation'],
            'card_left': ['Network: CEN hypofunction + DMN overlap', 'Key target: DLPFC bilateral, SMA', 'Priority: Fatigue circuit modulation'],
            'card_right': ['TPS: T4 + FT3', 'tDCS: C5/F2', 'PlatoScience: C6-PS/FP6', 'Graded activity'],
            'brain_targets': [
                ['DLPFC bilateral', 'Effort regulation', 'Activate', 'T4 / C5 / FP2', 'Emerging'],
                ['SMA', 'Motor effort', 'Upregulate', 'FT9 / Fz', 'Emerging'],
                ['ACC', 'Effort monitoring', 'Modulate', 'T4 / C5', 'Emerging'],
                ['Thalamus', 'Arousal gating', 'Support (CES)', 'CES protocol', 'Emerging'],
                ['Insula', 'Fatigue perception', 'Normalize', 'T5 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Graded activity therapy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS SMA', 'Energy conservation training'],
                ['taVNS 20 min', 'tDCS C5', 'TPS ACC', 'Pacing techniques'],
                ['CES 20 min', 'tDCS Fz', 'TPS insula', 'Fatigue diary'],
            ],
            'task_pairing': 'Graded activity therapy, energy conservation training, pacing techniques, fatigue diary.',
            'fnon_hypothesis': 'Post-stroke fatigue reflects CEN inefficiency with excessive effort required for routine cognitive and motor tasks. DLPFC stimulation reduces perceived effort cost.',
        },
    ],
    'task_pairing_rows': [
        ['Motor physio', 'Concurrent tDCS', 'Motor rehab', 'P1, P6'],
        ['Speech therapy', 'Concurrent tDCS', 'Language', 'P2'],
        ['Cognitive rehab', 'Post-TPS', 'Cognitive', 'P3'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P4'],
        ['Visual scanning', 'Concurrent tDCS', 'Neglect', 'P5'],
        ['Gait therapy', 'Concurrent tDCS', 'Motor', 'P6'],
        ['SLP exercises', 'Concurrent tDCS', 'Swallowing', 'P7'],
        ['Stretching', 'Post-TPS', 'Spasticity', 'P8'],
        ['Graded activity', 'Post-TPS', 'Fatigue', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'FMA, NIHSS', 'Motor + stroke severity', 'Adjust motor protocol'],
        ['Week 4', 'FMA, MoCA, PHQ-9', 'Motor + cognition + mood', 'Add cognitive track if needed'],
        ['Week 6', 'FMA, WAB, BBS', 'Motor + language + balance', 'Phase 2 intensification'],
        ['Week 10', 'Full battery + FIM', 'Function + ADL', 'Discharge planning'],
        ['Month 4', 'FMA, MoCA, QoL', 'Long-term recovery', 'Maintenance protocol'],
        ['Month 6', 'Full reassessment', 'All domains', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('stroke_rehab'),
}
'''

tbi_chunk = '''
PARTNERS_CONDITIONS['tbi'] = {
    'condition_full': 'Traumatic Brain Injury Rehabilitation',
    'condition_short': 'TBI',
    'condition_slug': 'tbi',
    'fnon_classification': 'Diffuse axonal injury / CEN hypofunction / DMN disruption / LIMBIC dysregulation',
    'fnon_montage_selection': [
        ['Cognitive dominant', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Attention/executive', 'HDCstim tDCS F3 anode / Fpz'],
        ['Post-TBI depression', 'tDCS F3 anode / F4 cathode'],
        ['Sleep-TBI overlap', 'tDCS F3/Fz + CES protocol'],
        ['Chronic pain TBI', 'tDCS C3/C4 + CES'],
    ],
    'tps': [
        ['T1', 'DLPFC cognitive recovery', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T2', 'Bilateral PFC', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T3', 'mPFC mood regulation', 'Fpz / mPFC', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'ACC attention', 'Fz / ACC', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Post-TBI depression', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN reactivation', 'CEN hypofunction', 'F3/F4 bilateral', 'Restore executive network', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT2', 'DMN disruption repair', 'DMN dysregulation', 'mPFC Fp1 + PCC Pz', 'Default mode reset', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT3', 'SN threshold restore', 'SN dysregulation', 'Cz + insula', 'Salience recalibration', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT4', 'Attention network', 'ATTENTION hypofunction', 'IPS P3/P4', 'Sustained attention', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT5', 'Limbic stabilize', 'LIMBIC dysregulation', 'vmPFC + amygdala temporal', 'Emotional regulation', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT6', 'Sleep-wake circuit', 'Hyperarousal insomnia', 'F3 + Cz', 'Sleep architecture', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT7', 'Post-TBI pain', 'Central sensitization', 'M1 bilateral Cz', 'Pain modulation', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT8', 'Social cognition', 'Social network damage', 'DMPFC + TPJ', 'Social reintegration', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT9', 'Neuroplasticity max', 'Multi-network', 'Rotating multisite', 'Global recovery', '0.22 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Cognitive recovery', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C2', 'Attention', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Post-TBI depression', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Working memory', 'F3/F4 bilateral / Oz', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Sleep', 'Fz anode / Oz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Pain central', 'C3/C4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C7', 'PTSD comorbid', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C8', 'Fatigue TBI', 'F3/F4 anodes / Cz', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Executive recovery', '2 mA', '20 min'],
        ['F2', 'DMN reset', 'DMN dysregulation', 'Fp1 cathode / Pz cathode', 'Default mode calm', '1.5 mA', '20 min'],
        ['F3', 'Attention network', 'ATTENTION hypofunction', 'F3 anode / Cz cathode', 'Sustained attention', '2 mA', '20 min'],
        ['F4', 'Limbic stabilize', 'LIMBIC dysregulation', 'Fp1 anode / mastoid', 'Emotion regulation', '1.5 mA', '20 min'],
        ['F5', 'Sleep circuit', 'Sleep disruption', 'Fz anode / Oz cathode', 'Sleep restoration', '1.5 mA', '20 min'],
        ['F6', 'Pain modulation', 'Central pain', 'C3/C4 anodes / Oz', 'Pain suppression', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Cognitive boost', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'TBI cognitive tasks'],
        ['C2-PS', 'Focus', 'Variant B', 'F3/Cz', '1.4 mA', '20 min', 'Attention rehab'],
        ['C3-PS', 'Mood', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Post-TBI depression'],
        ['C4-PS', 'Memory', 'Variant C', 'F3/F4', '1.4 mA', '20 min', 'Memory training'],
        ['C5-PS', 'Sleep prep', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'TBI insomnia'],
        ['C6-PS', 'Pain relief', 'Variant E', 'C3/C4', '1.4 mA', '20 min', 'Central pain'],
        ['C7-PS', 'Social cognition', 'Variant C', 'F3/TP9', '1.4 mA', '20 min', 'Social reintegration'],
        ['C8-PS', 'Fatigue', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'TBI fatigue'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN activate', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'DMN calm', 'DMN dysregulation', 'Variant G', 'Fp1/Pz', '1.2 mA', '20 min'],
        ['FP3', 'Attention', 'ATTENTION deficit', 'Variant B', 'F3/Cz', '1.4 mA', '20 min'],
        ['FP4', 'Limbic', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP5', 'Sleep', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min'],
        ['FP6', 'Pain', 'Central sensitization', 'Variant E', 'C3/C4', '1.4 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Cognitive Impairment (Post-TBI)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC bilateral', 'Cognitive rehab'],
            'card_left': ['Network: CEN diffuse hypofunction', 'Key target: DLPFC bilateral', 'Priority: Executive reactivation'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Working memory', 'Activate', 'T2 / C1 / FP1', 'Evidence B'],
                ['ACC', 'Attention', 'Activate', 'T4 / C2', 'Emerging'],
                ['PFC lateral', 'Executive function', 'Upregulate', 'T1 / C4', 'Emerging'],
                ['Hippocampus', 'New learning', 'Support (taVNS)', 'taVNS', 'Emerging'],
                ['Thalamus', 'Arousal gating', 'Normalize (CES)', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Cognitive training program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Working memory tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS bilateral PFC', 'Attention training'],
                ['CES 20 min', 'tDCS C4', 'TPS hippocampus proxy', 'Memory encoding tasks'],
            ],
            'task_pairing': 'Computerized cognitive rehabilitation, working memory n-back tasks, attention training, memory encoding exercises.',
            'fnon_hypothesis': 'Post-TBI cognitive impairment reflects diffuse axonal injury disrupting CEN white matter integrity. Bilateral DLPFC stimulation compensates for reduced network efficiency.',
        },
        {
            'code': 'P2', 'name': 'Post-TBI Depression',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood circuit restoration'],
            'card_right': ['TPS: T5 + FT5', 'tDCS: C3/F4', 'PlatoScience: C3-PS/FP4', 'BA protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood upregulation', 'Activate', 'T5 / C3 / FP4', 'Evidence B'],
                ['vmPFC', 'Reward', 'Normalize', 'T3 / F3', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['ACC', 'Emotional control', 'Modulate', 'T4 / C2', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasurable activity'],
                ['taVNS 20 min', 'tDCS C3', 'TPS ACC', 'Mood diary'],
                ['CES 20 min', 'tDCS F4', 'TPS amygdala temporal', 'CBT negative thoughts'],
            ],
            'task_pairing': 'Behavioral activation schedule, pleasurable activity planning, mood diary, CBT for negative cognitions.',
            'fnon_hypothesis': 'Post-TBI depression reflects LIMBIC circuit dysregulation compounded by PFC damage. L-DLPFC TPS + taVNS rebuilds mood regulation while taVNS supports hippocampal neuroplasticity.',
        },
        {
            'code': 'P3', 'name': 'Post-Concussion Syndrome',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 low intensity', 'TPS low-dose DLPFC', 'Graded return'],
            'card_left': ['Network: Multi-network sensitivity', 'Key target: DLPFC, Cz, mild protocol', 'Priority: Gradual neural recalibration'],
            'card_right': ['TPS: T1 low + FT1 reduced', 'tDCS: C8/F1 low', 'PlatoScience: C6-PS/FP6', 'REST protocol'],
            'brain_targets': [
                ['DLPFC', 'Cognitive function', 'Gentle activate', 'T1 reduced / C1', 'Emerging'],
                ['SN nodes', 'Symptom sensitivity', 'Normalize', 'FT3 low / Cz', 'Emerging'],
                ['Vestibular cortex', 'Dizziness', 'Modulate', 'TPS T3/T4', 'Emerging'],
                ['ACC', 'Headache circuit', 'Modulate', 'T4 / C5', 'Emerging'],
                ['Brainstem', 'Autonomic', 'Modulate (taVNS)', 'taVNS protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C8 low', 'TPS DLPFC low-dose', 'Graded return to activity'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS Cz low', 'Symptom monitoring'],
                ['taVNS 20 min', 'tDCS F1 low', 'TPS vestibular', 'Vestibular rehab'],
                ['CES 20 min', 'tDCS low 1 mA', 'TPS ACC low', 'Headache diary'],
            ],
            'task_pairing': 'Graded return-to-activity protocol, symptom monitoring diary, vestibular rehabilitation, paced activity.',
            'fnon_hypothesis': 'Post-concussion syndrome reflects neural hypersensitivity with SN threshold lowering. Low-dose graduated stimulation recalibrates network thresholds without provoking symptoms.',
        },
        {
            'code': 'P4', 'name': 'Post-TBI PTSD',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1/F4', 'TPS vmPFC+amygdala', 'Trauma-focused task'],
            'card_left': ['Network: LIMBIC hyperactivation + CEN hypo', 'Key target: vmPFC, amygdala, DLPFC', 'Priority: Fear extinction'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C7/F4', 'PlatoScience: C3-PS/FP4', 'CPT task'],
            'brain_targets': [
                ['vmPFC', 'Fear extinction', 'Strengthen', 'T3 / C7', 'Evidence B'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['Hippocampus', 'Context memory', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
                ['DLPFC', 'Top-down control', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Conflict monitoring', 'Modulate', 'T4 / C2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7', 'TPS vmPFC', 'CPT trauma processing'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS amygdala', 'Grounding exercises'],
                ['taVNS 30 min', 'tDCS F4', 'TPS DLPFC', 'Safety cue conditioning'],
                ['CES 20 min', 'tDCS Fp1', 'TPS ACC', 'Trauma narrative'],
            ],
            'task_pairing': 'Cognitive Processing Therapy (CPT), grounding exercises, safety signal conditioning, trauma narrative reprocessing.',
            'fnon_hypothesis': 'TBI-comorbid PTSD reflects dual pathology: structural vmPFC damage reducing fear inhibition + traumatic hyperactivation of amygdala. Combined TPS + taVNS targets both mechanisms.',
        },
        {
            'code': 'P5', 'name': 'Post-TBI Insomnia',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz/F3', 'TPS DLPFC+ACC', 'Sleep hygiene'],
            'card_left': ['Network: Hyperarousal + sleep circuit damage', 'Key target: Thalamus, DLPFC, ACC', 'Priority: Sleep architecture repair'],
            'card_right': ['TPS: T4 + FT6', 'tDCS: C5/F5', 'PlatoScience: C5-PS/FP5', 'CBT-I'],
            'brain_targets': [
                ['DLPFC', 'Sleep cognitive control', 'Balance', 'T4 / C5', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Suppress', 'T4 / C2', 'Emerging'],
                ['Thalamus', 'Sleep gating', 'Support (CES)', 'CES', 'Emerging'],
                ['Hypothalamus', 'Circadian', 'Normalize (CES)', 'CES', 'Emerging'],
                ['mPFC', 'Pre-sleep rumination', 'Downregulate', 'FT2 / F2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C5', 'TPS DLPFC', 'CBT-I protocol'],
                ['CES 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction'],
                ['taVNS 20 min', 'tDCS F5', 'TPS thalamus proxy Cz', 'Stimulus control'],
                ['CES 20 min', 'tDCS Fz', 'TPS mPFC', 'Progressive relaxation'],
            ],
            'task_pairing': 'CBT-I (cognitive behavioral therapy for insomnia), sleep restriction, stimulus control protocol, relaxation training.',
            'fnon_hypothesis': 'Post-TBI insomnia reflects hyperarousal from thalamic damage + cortical hyperexcitability. CES-thalamic protocol + prefrontal tDCS reduces arousal threshold for sleep onset.',
        },
        {
            'code': 'P6', 'name': 'Chronic Pain (Post-TBI)',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 bilateral', 'TPS M1 bilateral', 'Pain management'],
            'card_left': ['Network: Central sensitization', 'Key target: M1 bilateral, ACC', 'Priority: Pain gate modulation'],
            'card_right': ['TPS: FT7 + T4', 'tDCS: C6/F6', 'PlatoScience: C6-PS/FP6', 'Pain rehab'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'FT7 / C6 / FP6', 'Evidence B'],
                ['DLPFC', 'Pain modulation', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Pain affect', 'Modulate', 'T4 / C2', 'Emerging'],
                ['Insula', 'Pain integration', 'Normalize', 'T5 / C6', 'Emerging'],
                ['Thalamus', 'Pain relay (CES)', 'Modulate', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3/C4', 'TPS M1', 'Pain management program'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS ACC', 'Acceptance pain ACT'],
                ['taVNS 20 min', 'tDCS C6', 'TPS insula', 'Graded motor imagery'],
                ['CES 20 min', 'tDCS F6', 'TPS DLPFC', 'Pain education'],
            ],
            'task_pairing': 'Pain management program, graded motor imagery, acceptance-based pain therapy (ACT), pain education.',
            'fnon_hypothesis': 'Post-TBI central pain reflects sensitized pain networks without adequate descending inhibition. M1 TPS activates corticospinal pain inhibitory pathways.',
        },
        {
            'code': 'P7', 'name': 'Executive Dysfunction (Severe)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Executive tasks'],
            'card_left': ['Network: CEN severe hypofunction', 'Key target: DLPFC bilateral, OFC', 'Priority: Frontal executive circuit'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Problem-solving task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Executive planning', 'Activate', 'T2 / C1 / FP1', 'Evidence B'],
                ['OFC', 'Decision making', 'Modulate', 'TPS Fp2', 'Emerging'],
                ['ACC', 'Error monitoring', 'Activate', 'T4 / C2', 'Emerging'],
                ['Frontal-striatal', 'Response inhibition', 'Restore', 'TPS frontal lateral', 'Emerging'],
                ['PFC medial', 'Goal-directed', 'Activate', 'TPS Fz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC bilateral', 'Problem-solving therapy'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS OFC', 'Planning tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Stop-signal task'],
                ['CES 20 min', 'tDCS C4', 'TPS frontal', 'Goal management training'],
            ],
            'task_pairing': 'Goal Management Training (GMT), problem-solving therapy, planning tasks, response inhibition training.',
            'fnon_hypothesis': 'Severe executive dysfunction post-TBI reflects bilateral frontal network disruption. Bilateral DLPFC + OFC stimulation during GMT tasks promotes goal-directed behavior recovery.',
        },
        {
            'code': 'P8', 'name': 'Social Cognition Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/TP9', 'TPS DMPFC+TPJ', 'Social task'],
            'card_left': ['Network: Social brain network', 'Key target: DMPFC, TPJ, STS', 'Priority: Theory of mind recovery'],
            'card_right': ['TPS: FT8 + FT4', 'tDCS: C7/F6', 'PlatoScience: C7-PS/FP6', 'Social interaction'],
            'brain_targets': [
                ['DMPFC', 'Mentalizing', 'Activate', 'FT8 / C7 / FP6', 'Emerging'],
                ['TPJ', 'Theory of mind', 'Activate', 'TPS P3/T5', 'Emerging'],
                ['STS', 'Social perception', 'Activate', 'TPS T5/T6', 'Emerging'],
                ['Amygdala', 'Social emotion', 'Normalize', 'FT5 / temporal', 'Emerging'],
                ['OFC', 'Social reward', 'Activate', 'TPS Fp2', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C7', 'TPS DMPFC', 'Emotion recognition training'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS TPJ', 'Perspective-taking tasks'],
                ['taVNS 20 min', 'tDCS F6', 'TPS STS', 'Social video scenarios'],
                ['CES 20 min', 'tDCS F3/TP9', 'TPS bilateral social', 'Role-play therapy'],
            ],
            'task_pairing': 'Emotion recognition training, perspective-taking exercises, role-play social scenarios, social video analysis.',
            'fnon_hypothesis': 'TBI social cognition impairment reflects DMPFC-TPJ network damage disrupting mentalizing. TPS during social tasks drives activity-dependent plasticity in remaining social nodes.',
        },
        {
            'code': 'P9', 'name': 'Fatigue & Motivation Deficit',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fz', 'TPS DLPFC+ACC', 'Graded activation'],
            'card_left': ['Network: CEN inefficiency + motivation circuit', 'Key target: DLPFC, mPFC, ACC', 'Priority: Effort-reward recalibration'],
            'card_right': ['TPS: T4 + FT9', 'tDCS: C8/F1', 'PlatoScience: C8-PS/FP6', 'Activation task'],
            'brain_targets': [
                ['DLPFC', 'Effort regulation', 'Activate', 'T4 / C8 / FP6', 'Emerging'],
                ['ACC', 'Motivation monitoring', 'Modulate', 'T4 / C2', 'Emerging'],
                ['Striatum', 'Reward processing', 'Activate (TPS)', 'TPS lateral frontal', 'Emerging'],
                ['mPFC', 'Motivation drive', 'Upregulate', 'T3 / F4', 'Emerging'],
                ['Thalamus', 'Arousal (CES)', 'Activate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/Fz', 'TPS DLPFC', 'Graded activity therapy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', 'Motivation diary'],
                ['taVNS 20 min', 'tDCS C8', 'TPS mPFC', 'Pleasant activity schedule'],
                ['CES 20 min', 'tDCS F1', 'TPS striatal proxy', 'Goal-setting session'],
            ],
            'task_pairing': 'Graded activity therapy, goal-setting sessions, motivation diary, pleasant activity scheduling.',
            'fnon_hypothesis': 'Post-TBI fatigue reflects disrupted effort-reward valuation circuits. DLPFC + striatal TPS during graded activation recalibrates perceived effort cost.',
        },
    ],
    'task_pairing_rows': [
        ['Cognitive training', 'Post-TPS', 'Cognitive', 'P1, P7'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P2'],
        ['Graded return', 'During tDCS', 'Activity', 'P3'],
        ['CPT trauma', 'Post-TPS', 'PTSD', 'P4'],
        ['CBT-I sleep', 'Evening session', 'Sleep', 'P5'],
        ['Pain management', 'Concurrent tDCS', 'Pain', 'P6'],
        ['GMT executive', 'Concurrent tDCS', 'Executive', 'P7'],
        ['Social training', 'Post-TPS', 'Social', 'P8'],
        ['Graded activation', 'Post-TPS', 'Fatigue', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'MoCA, PHQ-9, NSI', 'Cognitive + mood + symptoms', 'Adjust protocol if <15% improvement'],
        ['Week 4', 'Full TBI battery', 'All domains', 'Phase 2 consideration'],
        ['Week 6', 'MoCA, PCSS, GAS', 'Comprehensive assessment', 'Goal attainment check'],
        ['Week 10', 'Full battery + FIM', 'Function + ADL', 'Discharge planning'],
        ['Month 4', 'MoCA, QoL, return-to-work', 'Long-term recovery', 'Maintenance protocol'],
        ['Month 6', 'Full reassessment', 'All domains', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('tbi'),
}
'''

chronic_pain_chunk = '''
PARTNERS_CONDITIONS['chronic_pain'] = {
    'condition_full': 'Chronic Pain Syndromes',
    'condition_short': 'Chronic Pain',
    'condition_slug': 'chronic_pain',
    'fnon_classification': 'Central sensitization / SN hyperactivation / descending inhibition failure / DMN pain overlap',
    'fnon_montage_selection': [
        ['Fibromyalgia dominant', 'HDCstim tDCS C3/C4 anodes + Cz / Oz cathode'],
        ['CRPS / neuropathic', 'tDCS M1 contralateral C3/C4 anode'],
        ['Central sensitization', 'HDCstim Cz anode + DLPFC F3/F4'],
        ['Pain + depression', 'tDCS F3 anode / F4 cathode + C3 anode'],
        ['Headache / migraine', 'tDCS Oz anode + C3/C4 + CES'],
    ],
    'tps': [
        ['T1', 'M1 pain gate (contralateral)', 'C3/C4 motor cortex', '0.25 mJ/mm²', '1200 pulses', 'Evidence A'],
        ['T2', 'DLPFC descending inhibition', 'F3/F4 DLPFC', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'ACC pain affect', 'Fz / ACCproxy', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'Insula pain integration', 'C3 insula proxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Occipital (migraine)', 'Oz bilateral', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'M1 analgesic', 'Pain gate failure', 'C3/C4 bilateral', 'Cortical pain inhibition', '0.25 mJ/mm²', '1200 pulses', '10 sessions'],
        ['FT2', 'CEN descending inhibition', 'CEN hypofunction', 'F3/F4 DLPFC', 'Top-down pain control', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT3', 'SN desensitization', 'SN hyperactivation', 'Cz + ACC Fz', 'Threat salience reduction', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT4', 'DMN pain rumination', 'DMN-pain overlap', 'mPFC Fp1 + PCC Pz', 'Break pain catastrophizing', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT5', 'Limbic pain-affect', 'LIMBIC pain sensitization', 'Amygdala temporal + vmPFC', 'Emotional pain component', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Occipital migraine', 'Visual cortex sensitization', 'Oz bilateral', 'Migraine prophylaxis', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Spinal facilitation block', 'Ascending facilitation', 'M1 + SMA Fz', 'Descending inhibitory tracts', '0.25 mJ/mm²', '1200 pulses', '10 sessions'],
        ['FT8', 'Autonomic pain modulation', 'Autonomic sensitization', 'Insula C3 + vagal', 'Parasympathetic dominance', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Multimodal pain protocol', 'Multi-network', 'Rotating M1/DLPFC/ACC', 'Comprehensive pain network', '0.22 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'M1 analgesic', 'C3/C4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence A'],
        ['C2', 'DLPFC pain control', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'ACC modulation', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Fibromyalgia protocol', 'C3/C4 bilateral / Oz', '2 mA', '20 min', 'Evidence B'],
        ['C5', 'Neuropathic pain', 'M1 contralateral / shoulder', '2 mA', '20 min', 'Evidence B'],
        ['C6', 'Insula central pain', 'C3 anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Pain + depression', 'F3 anode / Fp2 cathode + C3', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Migraine occipital', 'Oz anode / Cz cathode', '2 mA', '20 min', 'Evidence B'],
    ],
    'fnon_tdcs': [
        ['F1', 'M1 pain gate', 'Pain gate failure', 'C3/C4 anodes / Oz', 'Motor cortex analgesia', '2 mA', '20 min'],
        ['F2', 'Descending inhibition', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Top-down pain inhibition', '2 mA', '20 min'],
        ['F3', 'SN desensitize', 'SN hyperactivation', 'Cz anode / Oz cathode', 'Salience recalibration', '2 mA', '20 min'],
        ['F4', 'DMN pain break', 'DMN-pain rumination', 'Fz cathode / Pz cathode', 'Catastrophizing reduction', '1.5 mA', '20 min'],
        ['F5', 'Insula normalize', 'Insula hyperactivation', 'C3 anode / shoulder', 'Interoceptive recalibration', '2 mA', '20 min'],
        ['F6', 'Migraine prophylaxis', 'Occipital sensitization', 'Oz anode / Cz cathode', 'Visual cortex inhibition', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Pain + focus', 'Variant B', 'C3/C4', '1.6 mA', '20 min', 'M1 analgesic + attention'],
        ['C2-PS', 'Central pain relief', 'Variant E', 'Cz/C3', '1.4 mA', '20 min', 'Central sensitization'],
        ['C3-PS', 'Pain mood comorbid', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Depression + pain'],
        ['C4-PS', 'Sleep-pain', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'Sleep with pain'],
        ['C5-PS', 'Neuropathic', 'Variant E', 'C3/C4', '1.6 mA', '20 min', 'Neuropathic pain'],
        ['C6-PS', 'Catastrophizing', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Pain catastrophizing'],
        ['C7-PS', 'Fibromyalgia', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'Fibromyalgia protocol'],
        ['C8-PS', 'Migraine', 'Variant G', 'Oz/Cz', '1.2 mA', '20 min', 'Migraine prevention'],
    ],
    'fnon_plato': [
        ['FP1', 'M1 analgesic', 'Pain gate failure', 'Variant E', 'C3/C4', '1.6 mA', '20 min'],
        ['FP2', 'CEN pain control', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'SN desensitize', 'SN hyperactivation', 'Variant F', 'Cz/C3', '1.4 mA', '20 min'],
        ['FP4', 'DMN break', 'DMN-pain overlap', 'Variant G', 'F3/Pz', '1.2 mA', '20 min'],
        ['FP5', 'Limbic pain', 'LIMBIC sensitization', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP6', 'Migraine', 'Occipital sensitization', 'Variant G', 'Oz/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Fibromyalgia',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 bilateral', 'TPS M1+DLPFC', 'Graded exercise'],
            'card_left': ['Network: Central sensitization + SN hyperactivation', 'Key target: M1 bilateral, DLPFC', 'Priority: Descending inhibition restore'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C4/F1', 'PlatoScience: C7-PS/FP1', 'Exercise therapy'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C4 / FP1', 'Evidence A'],
                ['DLPFC', 'Descending inhibition', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Pain integration', 'Normalize', 'T4 / C6', 'Emerging'],
                ['ACC', 'Pain affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['Thalamus', 'Pain relay (CES)', 'Modulate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3/C4', 'TPS M1', 'Graded aerobic exercise'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS DLPFC', 'Pain education + exercise'],
                ['taVNS 20 min', 'tDCS C4', 'TPS insula', 'Body scan mindfulness'],
                ['CES 20 min', 'tDCS F1', 'TPS ACC', 'Acceptance pain ACT'],
            ],
            'task_pairing': 'Graded aerobic exercise (aqua therapy or low-impact), pain education, acceptance-based therapy, body scan.',
            'fnon_hypothesis': 'Fibromyalgia reflects widespread central sensitization with M1 analgesic circuit failure. M1 TPS activates endogenous opioid descending inhibitory systems, validated by neuroimaging.',
        },
        {
            'code': 'P2', 'name': 'CRPS / Neuropathic Pain',
            'sozo_bar': ['taVNS 30 min', 'tDCS M1 contralateral', 'TPS M1+DLPFC', 'Graded motor imagery'],
            'card_left': ['Network: Cortical reorganization + SN hyperactivation', 'Key target: M1 contralateral, insula', 'Priority: Cortical map normalization'],
            'card_right': ['TPS: T1 + FT7', 'tDCS: C5/F1', 'PlatoScience: C5-PS/FP1', 'GMI task'],
            'brain_targets': [
                ['M1 contralateral', 'Motor-pain map', 'Normalize', 'T1 / C5 / FP1', 'Evidence A'],
                ['Insula', 'Pain-autonomic', 'Normalize', 'T4 / C6', 'Emerging'],
                ['S1 contralateral', 'Sensory map', 'Reorganize', 'TPS C3/C4', 'Evidence B'],
                ['DLPFC', 'Top-down', 'Activate', 'T2 / C2', 'Evidence B'],
                ['ACC', 'Affective pain', 'Modulate', 'T3 / C3', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C5 M1', 'TPS M1 contralateral', 'Graded motor imagery'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS insula', 'Mirror visual feedback'],
                ['taVNS 20 min', 'tDCS C1', 'TPS S1 contralateral', 'Tactile desensitization'],
                ['CES 20 min', 'tDCS F1', 'TPS DLPFC', 'Pain rehabilitation'],
            ],
            'task_pairing': 'Graded Motor Imagery (GMI), mirror visual feedback therapy, tactile desensitization, pain rehabilitation program.',
            'fnon_hypothesis': 'CRPS reflects maladaptive cortical reorganization with M1/S1 map distortion amplifying pain signals. TPS + GMI drives corrective sensorimotor plasticity.',
        },
        {
            'code': 'P3', 'name': 'Chronic Low Back Pain',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3/C4 anodes', 'TPS M1+SMA', 'Movement therapy'],
            'card_left': ['Network: Motor-pain integration', 'Key target: M1 bilateral, SMA, ACC', 'Priority: Movement fear reduction'],
            'card_right': ['TPS: T1 + T3', 'tDCS: C1/F2', 'PlatoScience: C1-PS/FP1', 'Exercise therapy'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C1 / FP1', 'Evidence A'],
                ['SMA', 'Movement planning', 'Normalize', 'FT7 / Fz', 'Emerging'],
                ['ACC', 'Pain affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['DLPFC', 'Fear-avoidance', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Body perception', 'Normalize', 'T4 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3/C4', 'TPS M1', 'Graded movement therapy'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS SMA', 'Core stabilization'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Fear-avoidance CBT'],
                ['CES 20 min', 'tDCS F2', 'TPS DLPFC', 'Pain education'],
            ],
            'task_pairing': 'Graded movement therapy, core stabilization, fear-avoidance CBT, pain neuroscience education.',
            'fnon_hypothesis': 'Chronic low back pain reflects fear-avoidance behavior driven by SMA-ACC hypervigilance to movement. M1 TPS normalizes motor-pain coupling during movement tasks.',
        },
        {
            'code': 'P4', 'name': 'Migraine / Headache Disorders',
            'sozo_bar': ['CES 20 min', 'tDCS Oz anode', 'TPS occipital', 'Migraine diary'],
            'card_left': ['Network: Occipital hyperexcitability + trigeminovascular', 'Key target: Occipital cortex, ACC', 'Priority: Cortical spreading depression prevention'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C8/F6', 'PlatoScience: C8-PS/FP6', 'Migraine protocol'],
            'brain_targets': [
                ['Occipital cortex', 'Migraine generator', 'Modulate', 'T5 / C8 / FP6', 'Evidence B'],
                ['Trigeminovascular', 'Pain signal', 'Reduce (taVNS)', 'taVNS extended', 'Evidence B'],
                ['ACC', 'Headache affect', 'Modulate', 'T3 / C3', 'Emerging'],
                ['DLPFC', 'Pain control', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Thalamus', 'Pain relay (CES)', 'Modulate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS Oz anode', 'TPS occipital', 'Migraine diary + triggers'],
                ['taVNS 40 min', 'PlatoScience Variant G', 'TPS ACC', 'Relaxation protocol'],
                ['CES 20 min', 'tDCS C8', 'TPS DLPFC', 'Behavioral migraine mgmt'],
                ['taVNS 30 min', 'tDCS F6', 'TPS Oz bilateral', 'Biofeedback thermal'],
            ],
            'task_pairing': 'Migraine diary, trigger avoidance training, thermal biofeedback, relaxation protocol during inter-ictal period.',
            'fnon_hypothesis': 'Migraine reflects occipital cortex hyperexcitability with failure of cortical inhibitory networks. Inter-ictal occipital tDCS + TPS restores inhibitory tone preventing cortical spreading depression.',
        },
        {
            'code': 'P5', 'name': 'Central Sensitization Syndrome',
            'sozo_bar': ['taVNS 30 min', 'tDCS Cz/F3/F4', 'TPS M1+DLPFC+ACC', 'Pain education'],
            'card_left': ['Network: Whole-brain sensitization', 'Key target: M1, DLPFC, ACC, SN nodes', 'Priority: System-wide desensitization'],
            'card_right': ['TPS: FT9 multisite', 'tDCS: C4/F1', 'PlatoScience: C2-PS/FP3', 'CSS protocol'],
            'brain_targets': [
                ['M1 bilateral', 'Analgesic gate', 'Activate', 'T1 / C4 / FP1', 'Evidence A'],
                ['DLPFC', 'Descending inhibition', 'Activate', 'T2 / C2', 'Evidence B'],
                ['SN nodes', 'Sensitization hub', 'Reduce', 'FT3 / F3', 'Emerging'],
                ['ACC', 'Pain amplification', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['Insula', 'Central sensitization', 'Normalize', 'T4 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C4 bilateral', 'TPS M1+DLPFC', 'Pain education program'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS ACC', 'Pacing techniques'],
                ['taVNS 20 min', 'tDCS F1', 'TPS insula', 'Graded activity'],
                ['CES 20 min', 'tDCS Cz', 'TPS SN nodes', 'Acceptance therapy'],
            ],
            'task_pairing': 'Pain neuroscience education, pacing techniques, graded activity program, acceptance-based pain therapy.',
            'fnon_hypothesis': 'Central sensitization reflects network-wide amplification of pain signals with insufficient descending inhibition. Multi-site TPS protocol simultaneously targets M1, DLPFC, and ACC inhibitory pathways.',
        },
        {
            'code': 'P6', 'name': 'Pain + Depression Comorbidity',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode + C3', 'TPS DLPFC+M1', 'BA + movement'],
            'card_left': ['Network: Pain + LIMBIC dysregulation', 'Key target: DLPFC L, M1, amygdala', 'Priority: Unified pain-mood circuit'],
            'card_right': ['TPS: T2+T1 + FT5', 'tDCS: C7/F2', 'PlatoScience: C3-PS/FP5', 'Combined protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood + pain control', 'Activate', 'T2 / C7 / FP5', 'Evidence B'],
                ['M1', 'Pain gate', 'Activate', 'T1 / C1', 'Evidence A'],
                ['ACC', 'Pain-mood junction', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['Amygdala', 'Affect-pain amplify', 'Downregulate', 'FT5 / temporal', 'Emerging'],
                ['vmPFC', 'Reward + pain', 'Normalize', 'T3 / F3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 F3+C3', 'TPS DLPFC+M1', 'BA + graded movement'],
                ['CES 20 min', 'PlatoScience Variant A+E', 'TPS ACC', 'Pain diary + mood diary'],
                ['taVNS 20 min', 'tDCS F2', 'TPS DLPFC', 'Pleasant activity scheduling'],
                ['CES 20 min', 'tDCS C1', 'TPS M1+amygdala', 'CBT pain-mood'],
            ],
            'task_pairing': 'Behavioral activation combined with graded movement therapy, CBT targeting pain-mood linkages, pleasant activity scheduling.',
            'fnon_hypothesis': 'Pain-depression comorbidity reflects shared DLPFC-ACC circuit dysfunction amplifying both mood and pain signals. Targeting L-DLPFC simultaneously reduces both pain severity and depression.',
        },
        {
            'code': 'P7', 'name': 'Pelvic / Visceral Pain',
            'sozo_bar': ['taVNS 40 min', 'tDCS Cz/insula', 'TPS ACC+insula', 'Pelvic PT'],
            'card_left': ['Network: Visceral-cortical sensitization', 'Key target: Insula, ACC, S1 midline', 'Priority: Visceral cortex desensitization'],
            'card_right': ['TPS: T4 + FT8', 'tDCS: C6/F5', 'PlatoScience: C2-PS/FP5', 'PT + mindfulness'],
            'brain_targets': [
                ['Insula', 'Visceral integration', 'Normalize', 'T4 / C6 / FP5', 'Emerging'],
                ['ACC', 'Visceral affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['S1 midline (Cz)', 'Pelvic somatosensory', 'Normalize', 'TPS Cz', 'Emerging'],
                ['DLPFC', 'Top-down modulation', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Thalamus (CES)', 'Visceral relay', 'Modulate', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C6 insula', 'TPS ACC', 'Pelvic floor PT'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS insula', 'Mindfulness body scan'],
                ['taVNS 40 min', 'tDCS Cz', 'TPS S1 midline', 'Pelvic sensory retraining'],
                ['CES 20 min', 'tDCS F5', 'TPS DLPFC', 'Visceral pain education'],
            ],
            'task_pairing': 'Pelvic floor physiotherapy, mindfulness body scan, visceral pain education, pelvic sensory retraining.',
            'fnon_hypothesis': 'Visceral pain reflects insula-ACC hyperactivation to interoceptive signals. Extended taVNS + insula TPS recalibrates visceral afferent processing threshold.',
        },
        {
            'code': 'P8', 'name': 'Post-Surgical / Cancer Pain',
            'sozo_bar': ['taVNS 30 min', 'tDCS M1 contralateral', 'TPS M1+DLPFC', 'Comfort care task'],
            'card_left': ['Network: Peripheral + central sensitization', 'Key target: M1 contralateral, DLPFC', 'Priority: Analgesic optimization'],
            'card_right': ['TPS: T1+T2 + FT1', 'tDCS: C5/F1', 'PlatoScience: C5-PS/FP1', 'Pain QoL'],
            'brain_targets': [
                ['M1 contralateral', 'Pain gate', 'Activate', 'T1 / C5 / FP1', 'Evidence A'],
                ['DLPFC', 'Opioid-sparing', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Pain affect', 'Normalize', 'T4 / C6', 'Emerging'],
                ['ACC', 'Suffering component', 'Modulate', 'T3 / C3', 'Emerging'],
                ['vmPFC', 'Meaning + hope', 'Support', 'T3 / F3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C5', 'TPS M1', 'Comfort care program'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS DLPFC', 'Meaning-centered therapy'],
                ['taVNS 20 min', 'tDCS F1', 'TPS insula', 'Relaxation + imagery'],
                ['CES 20 min', 'tDCS C1', 'TPS ACC', 'Mindfulness-based pain'],
            ],
            'task_pairing': 'Comfort care program, meaning-centered therapy, relaxation and imagery, mindfulness-based pain management.',
            'fnon_hypothesis': 'Post-surgical pain reflects peripheral sensitization driving central amplification. M1 + DLPFC TPS activates endogenous opioid and serotonergic descending inhibitory pathways.',
        },
        {
            'code': 'P9', 'name': 'Chronic Headache (Tension-Type)',
            'sozo_bar': ['CES 20 min', 'tDCS C3/C4 + Fz', 'TPS M1+ACC', 'Relaxation protocol'],
            'card_left': ['Network: Pericranial sensitization + SN activation', 'Key target: M1, ACC, trigeminovascular', 'Priority: Sensitization reversal'],
            'card_right': ['TPS: T3+T1 + FT3', 'tDCS: C3/F3', 'PlatoScience: C7-PS/FP3', 'Relaxation task'],
            'brain_targets': [
                ['M1 bilateral', 'Pericranial pain gate', 'Activate', 'T1 / C3 / FP3', 'Evidence B'],
                ['ACC', 'Headache affect', 'Modulate', 'T3 / C3', 'Evidence B'],
                ['SN nodes', 'Sensitization threshold', 'Reduce', 'FT3 / Cz', 'Emerging'],
                ['Trigeminovascular (taVNS)', 'Pain input', 'Block', 'taVNS extended', 'Evidence B'],
                ['DLPFC', 'Analgesic control', 'Activate', 'T2 / C2', 'Evidence B'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C3/Fz', 'TPS M1+ACC', 'Progressive muscle relaxation'],
                ['taVNS 30 min', 'PlatoScience Variant F', 'TPS DLPFC', 'Biofeedback EMG'],
                ['CES 20 min', 'tDCS F3', 'TPS ACC', 'Headache diary + triggers'],
                ['taVNS 20 min', 'tDCS C3', 'TPS M1 bilateral', 'Mindfulness-based stress'],
            ],
            'task_pairing': 'Progressive muscle relaxation, EMG biofeedback, headache diary, trigger identification and avoidance protocol.',
            'fnon_hypothesis': 'Tension-type headache reflects pericranial muscle sensitization with central ACC amplification. M1 TPS + taVNS addresses both peripheral and central components.',
        },
    ],
    'task_pairing_rows': [
        ['Graded exercise', 'Concurrent tDCS', 'Motor', 'P1, P3'],
        ['GMI therapy', 'Post-TPS', 'Motor imagery', 'P2'],
        ['Movement therapy', 'Concurrent tDCS', 'Rehabilitation', 'P3'],
        ['Migraine diary', 'Post-session', 'Monitoring', 'P4'],
        ['Pain education', 'Post-TPS', 'Education', 'P5'],
        ['BA + movement', 'Combined session', 'Dual', 'P6'],
        ['Pelvic PT', 'Concurrent tDCS', 'Physiotherapy', 'P7'],
        ['Comfort care', 'Post-TPS', 'Palliative', 'P8'],
        ['Relaxation', 'During taVNS', 'Behavioral', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'NRS, BPI, PHQ-9', 'Pain intensity + mood', 'Adjust protocol if <20% reduction'],
        ['Week 4', 'NRS, BPI, PSQI', 'Pain + sleep', 'Add sleep protocol if needed'],
        ['Week 6', 'Full pain battery + WHODAS', 'Function + pain', 'Phase 2 decision'],
        ['Week 10', 'NRS, BPI, QoL', 'Long-term pain trajectory', 'Maintenance planning'],
        ['Month 4', 'Full reassessment', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'NRS, BPI, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('chronic_pain'),
}
'''

with open(data_file, 'a', encoding='utf-8') as f:
    f.write(stroke_chunk)
    f.write(tbi_chunk)
    f.write(chronic_pain_chunk)

import os
size = os.path.getsize(data_file)
print(f"Appended stroke_rehab, tbi, chronic_pain. File size: {size // 1024} KB")
