"""Append asd, long_covid to partners_all_in_one_data.py"""
import os
data_file = os.path.join(os.path.dirname(__file__), 'partners_all_in_one_data.py')

asd_chunk = '''
PARTNERS_CONDITIONS['asd'] = {
    'condition_full': 'Autism Spectrum Disorder',
    'condition_short': 'ASD',
    'condition_slug': 'asd',
    'fnon_classification': 'Social brain network hypofunction / atypical DMN / SN dysregulation / CEN variability',
    'fnon_montage_selection': [
        ['Social communication dominant', 'HDCstim tDCS F3/TP9 anodes / Oz cathode'],
        ['Repetitive behaviors', 'HDCstim F3/Fp2 anode/cathode + SMA Fz cathode'],
        ['Sensory overload', 'tDCS Cz cathode / F3/F4 anodes'],
        ['Executive dysfunction', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Anxiety comorbid', 'tDCS F3/F4 + taVNS extended'],
    ],
    'tps': [
        ['T1', 'DLPFC executive', 'F3/F4 bilateral', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T2', 'DMPFC social', 'F3 medial proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T3', 'TPJ social cognition', 'P3/T5 bilateral', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'SMA repetitive behaviors', 'Fz / SMA-proxy', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T5', 'ACC sensory/social', 'Fz / ACC-proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'Social brain activation', 'Social network hypofunction', 'DMPFC F3 + TPJ P3/T5', 'Social engagement capacity', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT2', 'CEN executive restore', 'CEN variability', 'F3/F4 bilateral', 'Executive function improve', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT3', 'RRB reduction (SMA)', 'SMA hyperactivation', 'Fz SMA-proxy', 'Repetitive behavior reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'DMN calibration', 'Atypical DMN', 'mPFC Fp1 + PCC Pz', 'Self-other processing', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'Sensory modulation SN', 'SN dysregulation', 'Cz + insula C3', 'Sensory threshold normalize', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Language-social', 'Language + social overlap', 'Broca F5 + TPJ', 'Social language capacity', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Anxiety comorbid', 'SN hyperactivation', 'F3/F4 + Cz cathode', 'Anxiety reduction', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Attention joint', 'ATTENTION network', 'IPS P3/P4 + FEF', 'Joint attention support', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT9', 'Comprehensive ASD', 'Multi-network', 'Social + CEN + SN rotating', 'Holistic ASD protocol', '0.20 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Social DLPFC', 'F3/F4 anodes / Oz cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'DMPFC social', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C3', 'RRB SMA', 'Fz cathode / F3 anode', '1.5 mA', '20 min', 'Evidence B'],
        ['C4', 'Sensory modulation', 'Cz cathode / F3/F4 anodes', '1.5 mA', '20 min', 'Emerging'],
        ['C5', 'Executive function', 'F3/F4 bilateral / Oz', '1.5 mA', '20 min', 'Evidence B'],
        ['C6', 'Anxiety comorbid', 'F3 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Language-social', 'F5 anode / F6 cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C8', 'Attention network', 'P3/P4 bilateral / Oz', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'Social brain', 'Social network hypofunction', 'F3/F4 anodes / Oz', 'Social engagement', '1.5 mA', '20 min'],
        ['F2', 'CEN executive', 'CEN variability', 'F3/F4 bilateral / Oz', 'Executive restore', '1.5 mA', '20 min'],
        ['F3', 'SMA RRB', 'SMA hyperactivation', 'Fz cathode / F3 anode', 'Repetitive behavior reduce', '1.5 mA', '20 min'],
        ['F4', 'SN sensory', 'SN dysregulation', 'Cz cathode / F3/F4', 'Sensory threshold', '1.5 mA', '20 min'],
        ['F5', 'Language social', 'Language network', 'F5 anode / F6 cathode', 'Social language', '1.5 mA', '20 min'],
        ['F6', 'Anxiety ASD', 'Anxiety comorbid', 'F3 anode / Cz cathode', 'Anxiety reduction', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Focus social', 'Variant C', 'F3/TP9', '1.2 mA', '20 min', 'Social tasks'],
        ['C2-PS', 'Executive', 'Variant B', 'F3/F4', '1.2 mA', '20 min', 'EF training'],
        ['C3-PS', 'Calm sensory', 'Variant D', 'Cz/F3', '1.2 mA', '20 min', 'Sensory protocol'],
        ['C4-PS', 'Anxiety ASD', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Anxiety comorbid'],
        ['C5-PS', 'Language-social', 'Variant C', 'F5/F3', '1.2 mA', '20 min', 'Language support'],
        ['C6-PS', 'Attention', 'Variant B', 'P3/P4', '1.2 mA', '20 min', 'Joint attention'],
        ['C7-PS', 'RRB reduce', 'Variant D', 'Fz/F3', '1.2 mA', '20 min', 'Repetitive behavior'],
        ['C8-PS', 'Sleep ASD', 'Variant G', 'Fp1/Cz', '1.0 mA', '20 min', 'ASD insomnia'],
    ],
    'fnon_plato': [
        ['FP1', 'Social network', 'Social hypofunction', 'Variant C', 'F3/TP9', '1.2 mA', '20 min'],
        ['FP2', 'CEN executive', 'CEN variability', 'Variant B', 'F3/F4', '1.2 mA', '20 min'],
        ['FP3', 'SMA RRB', 'SMA hyperactivation', 'Variant D', 'Fz/F3', '1.2 mA', '20 min'],
        ['FP4', 'SN sensory', 'SN dysregulation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP5', 'Anxiety ASD', 'Anxiety comorbid', 'Variant D', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP6', 'Sleep ASD', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.0 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Social Communication Difficulties',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/TP9', 'TPS DMPFC+TPJ', 'Social skills task'],
            'card_left': ['Network: Social brain hypofunction', 'Key target: DMPFC, TPJ, STS', 'Priority: Social cognition activation'],
            'card_right': ['TPS: T2+T3 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Social task'],
            'brain_targets': [
                ['DMPFC', 'Social cognition', 'Activate', 'T2 / C2 / FP1', 'Evidence B'],
                ['TPJ', 'Mentalizing', 'Upregulate', 'T3 / C8', 'Emerging'],
                ['STS', 'Biological motion', 'Activate', 'TPS T5/T6', 'Emerging'],
                ['Broca (F5)', 'Social language', 'Support', 'T2 / C7', 'Emerging'],
                ['Amygdala', 'Social emotion', 'Normalize', 'FT4 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1 F3/F4', 'TPS DMPFC', 'Social stories task'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS TPJ', 'Perspective-taking exercises'],
                ['taVNS 20 min', 'tDCS F1', 'TPS STS bilateral', 'Video social scenarios'],
                ['CES 20 min', 'tDCS C7', 'TPS Broca F5', 'Conversation skills practice'],
            ],
            'task_pairing': 'Social stories, perspective-taking exercises, video social scenario analysis, conversation skills practice.',
            'fnon_hypothesis': 'ASD social communication reflects DMPFC-TPJ hypoactivation during social processing. TPS during social tasks drives activity-dependent plasticity in mentalizing network nodes.',
        },
        {
            'code': 'P2', 'name': 'Repetitive & Restricted Behaviors',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz cathode/F3', 'TPS SMA+DLPFC', 'Flexibility task'],
            'card_left': ['Network: SMA hyperactivation + habit circuit', 'Key target: SMA, DLPFC, caudate', 'Priority: Behavioral flexibility'],
            'card_right': ['TPS: T4+T1 + FT3', 'tDCS: C3/F2', 'PlatoScience: C7-PS/FP3', 'Flexibility task'],
            'brain_targets': [
                ['SMA', 'Repetitive urge', 'Inhibit', 'T4 / C3 / FP3', 'Evidence B'],
                ['DLPFC', 'Cognitive flexibility', 'Activate', 'T1 / C5', 'Evidence B'],
                ['ACC', 'Inflexibility monitoring', 'Recalibrate', 'T5 / C4', 'Emerging'],
                ['Caudate', 'Habit circuit', 'Modulate', 'FT3 / lateral F', 'Emerging'],
                ['Putamen', 'Motor routine', 'Normalize', 'TPS C3/C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 Fz cathode', 'TPS SMA', 'Flexibility training'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', 'Set-shifting tasks'],
                ['taVNS 20 min', 'tDCS F2', 'TPS caudate', 'Routine variation program'],
                ['CES 20 min', 'tDCS C5', 'TPS ACC', 'CBT flexibility exercises'],
            ],
            'task_pairing': 'Cognitive flexibility training, set-shifting tasks, routine variation exercises, behavioral flexibility CBT.',
            'fnon_hypothesis': 'RRBs reflect SMA-caudate habit circuit hyperactivation with DLPFC flexibility deficit. SMA TPS + flexibility tasks targets both the compulsive drive and the cognitive control deficit.',
        },
        {
            'code': 'P3', 'name': 'Sensory Processing Difficulties',
            'sozo_bar': ['taVNS 20 min', 'tDCS Cz cathode/F3', 'TPS SN suppress', 'Sensory integration'],
            'card_left': ['Network: SN dysregulation + sensory over/under', 'Key target: SN nodes, insula, Cz', 'Priority: Sensory threshold calibration'],
            'card_right': ['TPS: T5 + FT5', 'tDCS: C4/F4', 'PlatoScience: C3-PS/FP4', 'OT sensory task'],
            'brain_targets': [
                ['SN nodes (Cz)', 'Sensory salience', 'Recalibrate', 'FT5 / C4 / FP4', 'Emerging'],
                ['Insula', 'Sensory integration', 'Normalize', 'T5 / C4', 'Emerging'],
                ['ACC', 'Sensory distress', 'Modulate', 'T5 / C5', 'Emerging'],
                ['S1/S2', 'Sensory cortex', 'Normalize', 'TPS C3/C4', 'Emerging'],
                ['DLPFC', 'Top-down filter', 'Activate', 'T1 / C5', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C4 Cz cathode', 'TPS SN suppress', 'Sensory integration OT'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS insula', 'Sensory desensitization'],
                ['taVNS 20 min', 'tDCS F4', 'TPS S1 bilateral', 'Tactile graduated exposure'],
                ['CES 20 min', 'tDCS C5', 'TPS DLPFC', 'Sensory coping strategies'],
            ],
            'task_pairing': 'Sensory integration OT (occupational therapy), graduated sensory exposure, tactile desensitization, sensory coping strategies.',
            'fnon_hypothesis': 'ASD sensory difficulties reflect SN threshold dysregulation causing atypical salience responses to sensory input. SN-targeted TPS recalibrates sensory gate without suppressing awareness.',
        },
        {
            'code': 'P4', 'name': 'Executive Dysfunction (ASD)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'EF training'],
            'card_left': ['Network: CEN variability / DLPFC inconsistency', 'Key target: DLPFC bilateral', 'Priority: Executive consistency'],
            'card_right': ['TPS: T1 + FT2', 'tDCS: C5/F2', 'PlatoScience: C2-PS/FP2', 'EF task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Executive function', 'Stabilize', 'T1 / C5 / FP2', 'Evidence B'],
                ['ACC', 'Performance monitoring', 'Normalize', 'T5 / C4', 'Emerging'],
                ['OFC', 'Decision flexibility', 'Modulate', 'TPS Fp2', 'Emerging'],
                ['Frontal-parietal', 'WM network', 'Activate', 'TPS F3+P3', 'Emerging'],
                ['Thalamus (CES)', 'Arousal gating', 'Normalize', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Executive function training'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Planning and organization'],
                ['taVNS 20 min', 'tDCS C5', 'TPS frontal-parietal', 'Working memory n-back'],
                ['CES 20 min', 'tDCS F2', 'TPS OFC', 'Flexibility set-shifting'],
            ],
            'task_pairing': 'Executive function training, planning and organization tasks, working memory training, set-shifting exercises.',
            'fnon_hypothesis': 'ASD executive dysfunction reflects CEN variability with inconsistent DLPFC engagement. Bilateral DLPFC TPS increases neural activation consistency supporting executive task performance.',
        },
        {
            'code': 'P5', 'name': 'Anxiety Comorbidity (ASD)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC+vmPFC', 'CBT adapted ASD'],
            'card_left': ['Network: SN hyperactivation + social anxiety', 'Key target: DLPFC, vmPFC, amygdala', 'Priority: Anxiety circuit modulation'],
            'card_right': ['TPS: T1 + FT7', 'tDCS: C6/F1', 'PlatoScience: C4-PS/FP5', 'CBT-A task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety regulation', 'Activate', 'T1 / C6 / FP5', 'Evidence B'],
                ['vmPFC', 'Safety signal', 'Strengthen', 'FT7 / F1', 'Emerging'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT4 / temporal', 'Emerging'],
                ['SN nodes', 'Anxiety salience', 'Reduce', 'FT7 / Cz', 'Emerging'],
                ['ACC', 'Worry circuit', 'Modulate', 'T5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C6 F3/F4', 'TPS DLPFC', 'CBT adapted for ASD'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Worry reduction ASD'],
                ['taVNS 20 min', 'tDCS F1', 'TPS SN suppress', 'Exposure hierarchy ASD'],
                ['CES 20 min', 'tDCS C6', 'TPS amygdala', 'Relaxation ASD-adapted'],
            ],
            'task_pairing': 'CBT adapted for ASD, visual worry reduction tools, graduated exposure hierarchy, ASD-adapted relaxation.',
            'fnon_hypothesis': 'ASD anxiety reflects SN hyperactivation amplified by social prediction error processing. DLPFC TPS strengthens top-down anxiety regulation concurrent with ASD-adapted CBT.',
        },
        {
            'code': 'P6', 'name': 'Attention & ADHD Comorbidity',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Attention task'],
            'card_left': ['Network: ATTENTION hypofunction + CEN', 'Key target: DLPFC bilateral, IPS', 'Priority: Sustained attention'],
            'card_right': ['TPS: T1 + FT8', 'tDCS: C1/F2', 'PlatoScience: C2-PS/FP2', 'Attention task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Attention control', 'Activate', 'T1 / C1 / FP2', 'Evidence B'],
                ['IPS bilateral', 'Spatial attention', 'Upregulate', 'FT8 / C8', 'Emerging'],
                ['ACC', 'Attention monitoring', 'Normalize', 'T5 / C4', 'Emerging'],
                ['FEF', 'Top-down attention', 'Activate', 'TPS F8', 'Emerging'],
                ['SN nodes', 'Attention salience', 'Balance', 'FT5 / Cz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Attention training program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS IPS', 'Sustained attention tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS FEF', 'Visual attention training'],
                ['CES 20 min', 'tDCS F2', 'TPS ACC', 'Mindfulness attention'],
            ],
            'task_pairing': 'Attention training program, sustained attention exercises, visual attention training, mindfulness attention practice.',
            'fnon_hypothesis': 'ASD-ADHD comorbidity reflects dual DLPFC inconsistency and ATTENTION network hypofunction. Bilateral DLPFC TPS stabilizes executive attention while IPS activation supports sustained focus.',
        },
        {
            'code': 'P7', 'name': 'Emotional Regulation Difficulties',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/Fp1', 'TPS DLPFC+vmPFC', 'Emotion task'],
            'card_left': ['Network: LIMBIC hyperactivation + CEN regulation deficit', 'Key target: DLPFC, vmPFC, insula', 'Priority: Emotional regulation capacity'],
            'card_right': ['TPS: T1+T2 + FT7', 'tDCS: C1/F1', 'PlatoScience: C4-PS/FP5', 'ER task'],
            'brain_targets': [
                ['DLPFC', 'ER strategy application', 'Activate', 'T1 / C1 / FP5', 'Evidence B'],
                ['vmPFC', 'Emotion safety', 'Strengthen', 'T2 / F1', 'Emerging'],
                ['Insula', 'Emotional awareness', 'Normalize', 'FT7 / C4', 'Emerging'],
                ['Amygdala', 'Emotional reactivity', 'Downregulate', 'FT4 / temporal', 'Emerging'],
                ['ACC', 'Conflict emotion', 'Modulate', 'T5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C1 F3/Fp1', 'TPS DLPFC+vmPFC', 'Emotion regulation skills'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS insula', 'Emotion recognition training'],
                ['taVNS 20 min', 'tDCS F1', 'TPS amygdala', 'DBT-adapted skills'],
                ['CES 20 min', 'tDCS C6', 'TPS ACC', 'Emotional thermometer task'],
            ],
            'task_pairing': 'Emotion regulation skills program, emotion recognition training, DBT-adapted skills for ASD, emotional thermometer tool.',
            'fnon_hypothesis': 'ASD emotional dysregulation reflects insufficient DLPFC-vmPFC modulation of amygdala reactivity. TPS increases prefrontal capacity for in-the-moment emotion regulation strategy application.',
        },
        {
            'code': 'P8', 'name': 'Sleep Difficulties (ASD)',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Cz low', 'TPS DLPFC low-dose', 'Sleep routine'],
            'card_left': ['Network: Hyperarousal + circadian dysregulation', 'Key target: Thalamus (CES), DLPFC', 'Priority: Sleep onset and maintenance'],
            'card_right': ['TPS: T1 low + FT7', 'tDCS: C8/F6 low', 'PlatoScience: C8-PS/FP6', 'Sleep routine'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep regulation', 'Balance', 'T1 low / C8', 'Emerging'],
                ['Thalamus (CES)', 'Sleep gating', 'Support', 'CES protocol', 'Emerging'],
                ['Hypothalamus', 'Circadian', 'Normalize (CES)', 'CES protocol', 'Emerging'],
                ['ACC', 'Nighttime hyperarousal', 'Reduce', 'T5 / C4', 'Emerging'],
                ['Insula', 'Sensory sleep onset', 'Normalize', 'FT5 / C4', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C8 low', 'TPS DLPFC low', 'Visual sleep schedule'],
                ['taVNS 20 min low', 'PlatoScience Variant G', 'TPS ACC low', 'Sleep routine ASD-adapted'],
                ['CES 20 min', 'tDCS F6 low', 'TPS Cz thalamus', 'Sensory sleep environment'],
                ['CES 20 min', 'tDCS F3 low', 'TPS mPFC', 'Social story sleep'],
            ],
            'task_pairing': 'Visual sleep schedule, ASD-adapted sleep routine, sensory sleep environment optimization, social story about sleep.',
            'fnon_hypothesis': 'ASD sleep difficulties reflect hyperarousal from SN dysregulation + sensory sensitivity at sleep onset. CES + gentle tDCS reduces cortical arousal without exacerbating sensory sensitivities.',
        },
        {
            'code': 'P9', 'name': 'Minimally Verbal ASD',
            'sozo_bar': ['taVNS 20 min', 'tDCS F5/F3 language', 'TPS language network', 'AAC + SLT task'],
            'card_left': ['Network: Language + social network severe hypofunction', 'Key target: Broca F5, SMA, DMPFC', 'Priority: Communication support'],
            'card_right': ['TPS: FT6 + T4', 'tDCS: C7/F1', 'PlatoScience: C5-PS/FP1', 'AAC task'],
            'brain_targets': [
                ['Broca (F5)', 'Speech output', 'Activate', 'FT6 / C7 / FP1', 'Emerging'],
                ['SMA', 'Speech initiation', 'Support', 'T4 / C3', 'Emerging'],
                ['DMPFC', 'Communicative intent', 'Activate', 'T2 / C2', 'Emerging'],
                ['Premotor', 'Articulatory', 'Activate', 'TPS F3/F4', 'Emerging'],
                ['Cerebellum', 'Speech coordination', 'Support', 'TPS lateral', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C7 F5/F3', 'TPS Broca F5', 'AAC device training'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS SMA', 'SLT intensive'],
                ['taVNS 20 min', 'tDCS F1', 'TPS DMPFC', 'Communicative intent tasks'],
                ['CES 20 min', 'tDCS C5', 'TPS premotor', 'Verbal imitation tasks'],
            ],
            'task_pairing': 'AAC (Augmentative and Alternative Communication) training, SLT intensive, communicative intent tasks, verbal imitation exercises.',
            'fnon_hypothesis': 'Minimally verbal ASD reflects severe language + social network hypofunction. Low-intensity Broca + SMA TPS during AAC/SLT sessions supports residual communication circuit activation.',
        },
    ],
    'task_pairing_rows': [
        ['Social stories', 'Post-TPS', 'Social', 'P1'],
        ['Flexibility training', 'Concurrent tDCS', 'Behavioral', 'P2'],
        ['Sensory OT', 'Concurrent tDCS', 'Sensory', 'P3'],
        ['EF training', 'Post-TPS', 'Cognitive', 'P4'],
        ['CBT-A', 'Post-TPS', 'Anxiety', 'P5'],
        ['Attention program', 'Post-TPS', 'Attention', 'P6'],
        ['ER skills', 'During tDCS', 'Emotional', 'P7'],
        ['Sleep routine', 'Evening CES', 'Sleep', 'P8'],
        ['AAC + SLT', 'Concurrent tDCS', 'Communication', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'VABS, SRS-2', 'Adaptive + social', 'Safety + tolerance check'],
        ['Week 4', 'SRS-2, BRIEF, CGAS', 'Social + executive + function', 'Protocol compliance'],
        ['Week 6', 'Full ASD battery', 'Comprehensive', 'Phase 2 readiness'],
        ['Week 10', 'SRS-2, QoL, family report', 'Social trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment + school', 'All domains', 'Education coordination'],
        ['Month 6', 'Yearly reassessment', 'Developmental trajectory', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('asd'),
}
'''

long_covid_chunk = '''
PARTNERS_CONDITIONS['long_covid'] = {
    'condition_full': 'Long COVID — Neurological & Cognitive Symptoms',
    'condition_short': 'Long COVID',
    'condition_slug': 'long_covid',
    'fnon_classification': 'Neuroinflammation-driven CEN hypofunction / DMN disruption / fatigue circuit / autonomic dysregulation',
    'fnon_montage_selection': [
        ['Brain fog dominant', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Fatigue dominant', 'HDCstim tDCS F3/Fz + CES protocol'],
        ['Autonomic (POTS)', 'tDCS C3/C4 + taVNS extended'],
        ['Mood dysregulation', 'tDCS F3 anode / F4 cathode'],
        ['Pain long COVID', 'tDCS C3/C4 + CES bilateral'],
    ],
    'tps': [
        ['T1', 'DLPFC brain fog', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T2', 'Fatigue circuit', 'F3 + Fz', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T3', 'Autonomic insula', 'C3 insula proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'Mood long COVID', 'DLPFC L F3', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T5', 'ACC attention', 'Fz / ACC-proxy', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN reactivation', 'CEN hypofunction (neuroinflam)', 'F3/F4 bilateral', 'Cognitive circuit restore', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT2', 'Fatigue network', 'Fatigue circuit disruption', 'F3/Fz bilateral', 'Neural efficiency restore', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT3', 'DMN normalize', 'DMN disruption', 'mPFC + PCC', 'Default mode reset', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'SN dysregulation', 'SN hyperactivation', 'Cz + insula C3', 'Symptom salience reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'Autonomic restoration', 'Autonomic dysregulation', 'Insula C3 + C4', 'HRV and POTS support', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT6', 'Mood circuit', 'LIMBIC dysregulation', 'DLPFC L + vmPFC', 'Long COVID depression', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Sleep disruption', 'Sleep-wake dysregulation', 'F3 + Cz', 'Sleep restoration', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT8', 'Headache long COVID', 'Central sensitization', 'Cz + Oz bilateral', 'Headache circuit', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Comprehensive long COVID', 'Multi-network', 'Rotating CEN+fatigue+autonomic', 'Holistic protocol', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Brain fog cognitive', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C2', 'Fatigue', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Emerging'],
        ['C3', 'Autonomic POTS', 'C3/C4 bilateral / Oz', '2 mA', '20 min', 'Emerging'],
        ['C4', 'Mood', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Pain long COVID', 'C3/C4 anodes / Oz', '2 mA', '20 min', 'Emerging'],
        ['C6', 'Sleep', 'Fz anode / Oz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Headache', 'Oz anode / Cz cathode', '2 mA', '20 min', 'Emerging'],
        ['C8', 'Anxiety long COVID', 'F3/F4 anodes / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN brain fog', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Cognitive circuit restore', '2 mA', '20 min'],
        ['F2', 'Fatigue circuit', 'Fatigue network', 'F3 anode / Cz cathode', 'Neural efficiency', '2 mA', '20 min'],
        ['F3', 'Autonomic', 'Autonomic dysregulation', 'C3/C4 anodes / Oz', 'HRV support', '2 mA', '20 min'],
        ['F4', 'SN suppress', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Symptom salience reduce', '2 mA', '20 min'],
        ['F5', 'Mood long COVID', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Mood restoration', '2 mA', '20 min'],
        ['F6', 'Sleep', 'Sleep disruption', 'Fz anode / Oz cathode', 'Sleep circuit', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Cognitive fog', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Brain fog tasks'],
        ['C2-PS', 'Energy', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Fatigue long COVID'],
        ['C3-PS', 'Mood', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Long COVID depression'],
        ['C4-PS', 'Sleep', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'Long COVID insomnia'],
        ['C5-PS', 'Autonomic', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'POTS + HRV'],
        ['C6-PS', 'Pain', 'Variant E', 'C3/C4', '1.4 mA', '20 min', 'Long COVID pain'],
        ['C7-PS', 'Anxiety', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Long COVID anxiety'],
        ['C8-PS', 'Headache', 'Variant G', 'Oz/Cz', '1.2 mA', '20 min', 'Post-COVID headache'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN brain fog', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'Fatigue', 'Fatigue circuit', 'Variant D', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP3', 'Autonomic', 'Autonomic dysregulation', 'Variant F', 'C3/C4', '1.4 mA', '20 min'],
        ['FP4', 'SN symptom', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP5', 'LIMBIC mood', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP6', 'Sleep', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Brain Fog / Cognitive Impairment',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Cognitive rehab'],
            'card_left': ['Network: CEN neuroinflammatory disruption', 'Key target: DLPFC bilateral', 'Priority: Cognitive circuit reactivation'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Working memory', 'Activate', 'T1 / C1 / FP1', 'Emerging'],
                ['ACC', 'Attention/processing', 'Activate', 'T5 / C2', 'Emerging'],
                ['Hippocampus', 'Memory encoding', 'Support (taVNS)', 'taVNS', 'Emerging'],
                ['Thalamus (CES)', 'Arousal gating', 'Normalize', 'CES', 'Emerging'],
                ['PFC bilateral', 'Executive', 'Upregulate', 'FT1 / C8', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Cognitive rehabilitation program'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS bilateral', 'Working memory tasks'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Processing speed training'],
                ['CES 20 min', 'tDCS C8', 'TPS hippocampus', 'Memory encoding exercises'],
            ],
            'task_pairing': 'Cognitive rehabilitation program, working memory n-back, processing speed training, memory encoding tasks.',
            'fnon_hypothesis': 'Long COVID brain fog reflects neuroinflammatory disruption of CEN white matter and synaptic efficiency. DLPFC TPS bypasses inflammatory downregulation by directly activating cortical circuits.',
        },
        {
            'code': 'P2', 'name': 'Post-COVID Fatigue',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fz', 'TPS FT2 fatigue', 'Pacing program'],
            'card_left': ['Network: Fatigue circuit + CEN inefficiency', 'Key target: DLPFC, SMA, ACC', 'Priority: Energy regulation'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C2/F2', 'PlatoScience: C2-PS/FP2', 'Pacing task'],
            'brain_targets': [
                ['DLPFC', 'Effort regulation', 'Activate', 'T2 / C2 / FP2', 'Emerging'],
                ['ACC', 'Fatigue monitoring', 'Normalize', 'T5 / C5', 'Emerging'],
                ['Insula', 'Fatigue perception', 'Normalize', 'T3 / C3', 'Emerging'],
                ['Thalamus (CES)', 'Arousal level', 'Support', 'CES protocol', 'Emerging'],
                ['SMA', 'Motor effort', 'Upregulate', 'FT2 / Fz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/Fz', 'TPS fatigue DLPFC', 'Energy pacing program'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', 'Activity management'],
                ['taVNS 20 min', 'tDCS C2', 'TPS insula', 'Graded return to activity'],
                ['CES 20 min', 'tDCS F2', 'TPS SMA', 'Fatigue diary optimization'],
            ],
            'task_pairing': 'Energy pacing program, activity management, graded return to activity (avoid PEM), fatigue diary.',
            'fnon_hypothesis': 'Post-COVID fatigue reflects insula hypervigilance to exertion combined with ACC metabolic dysregulation. Graduated pacing + tDCS reduces perceived effort while avoiding post-exertional malaise.',
        },
        {
            'code': 'P3', 'name': 'Autonomic Dysregulation (POTS)',
            'sozo_bar': ['taVNS 40 min', 'tDCS C3/C4 insula', 'TPS insula FT5', 'HRV biofeedback'],
            'card_left': ['Network: Autonomic + insula dysregulation', 'Key target: Insula, vagal axis, C3/C4', 'Priority: HRV and POTS management'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C3/F3', 'PlatoScience: C5-PS/FP3', 'HRV task'],
            'brain_targets': [
                ['Insula', 'Autonomic integration', 'Normalize', 'T3 / C3 / FP3', 'Emerging'],
                ['ACC', 'Autonomic control', 'Activate', 'T5 / C5', 'Emerging'],
                ['vmPFC', 'Cardiac safety', 'Strengthen', 'FT6 / F5', 'Emerging'],
                ['Brainstem (taVNS)', 'Vagal tone', 'Increase', 'taVNS extended', 'Evidence B'],
                ['Hypothalamus', 'Autonomic balance', 'Normalize (CES)', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C3/C4', 'TPS insula', 'HRV biofeedback daily'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS ACC', 'Cardiac coherence breathing'],
                ['taVNS 40 min', 'tDCS F3', 'TPS vmPFC', 'Orthostatic training program'],
                ['CES 20 min', 'tDCS C3', 'TPS insula bilateral', 'Compression + conditioning'],
            ],
            'task_pairing': 'HRV biofeedback, cardiac coherence breathing (6 cpm), orthostatic conditioning program, compression garments during sessions.',
            'fnon_hypothesis': 'Long COVID POTS reflects autonomic nervous system dysregulation with impaired vagal tone. Extended taVNS directly targets vagal-cardiac axis while insula TPS normalizes cortical autonomic representation.',
        },
        {
            'code': 'P4', 'name': 'Mood Dysregulation (Long COVID)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood circuit support'],
            'card_right': ['TPS: T4 + FT6', 'tDCS: C4/F5', 'PlatoScience: C3-PS/FP5', 'BA task'],
            'brain_targets': [
                ['DLPFC L', 'Mood regulation', 'Activate', 'T4 / C4 / FP5', 'Emerging'],
                ['vmPFC', 'Positive affect', 'Restore', 'FT6 / F5', 'Emerging'],
                ['ACC', 'Mood monitoring', 'Modulate', 'T5 / C5', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['Hippocampus', 'Mood circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Meaning + illness acceptance'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'Mood diary'],
                ['CES 20 min', 'tDCS F5', 'TPS amygdala', 'CBT for illness'],
            ],
            'task_pairing': 'Behavioral activation, illness acceptance therapy, mood diary, CBT for chronic illness adaptation.',
            'fnon_hypothesis': 'Long COVID mood dysregulation reflects neuroinflammatory LIMBIC circuit disruption. L-DLPFC TPS provides mood uplift while taVNS supports neuroplasticity recovery.',
        },
        {
            'code': 'P5', 'name': 'Headache & Pain (Post-COVID)',
            'sozo_bar': ['taVNS 30 min', 'tDCS Oz/C3/C4', 'TPS FT8 headache', 'Pain education'],
            'card_left': ['Network: Central sensitization post-COVID', 'Key target: Cz, Oz, M1 bilateral', 'Priority: Pain gate restoration'],
            'card_right': ['TPS: T5+T3 + FT8', 'tDCS: C7/F6', 'PlatoScience: C8-PS/FP6', 'Pain mgmt'],
            'brain_targets': [
                ['Occipital (Oz)', 'Headache', 'Modulate', 'T5 / C7 / FP6', 'Emerging'],
                ['M1 bilateral', 'Pain gate', 'Activate', 'T1 / C5', 'Emerging'],
                ['Insula', 'Pain integration', 'Normalize', 'T3 / C3', 'Emerging'],
                ['ACC', 'Pain affect', 'Modulate', 'T5 / C5', 'Emerging'],
                ['DLPFC', 'Top-down pain', 'Activate', 'T1 / C1', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 Oz anode', 'TPS Oz bilateral', 'Headache management plan'],
                ['CES 20 min', 'PlatoScience Variant G', 'TPS M1', 'Pain pacing'],
                ['taVNS 20 min', 'tDCS C5', 'TPS insula', 'Body scan ACT pain'],
                ['CES 20 min', 'tDCS F6', 'TPS DLPFC', 'Pain education long COVID'],
            ],
            'task_pairing': 'Headache management plan, pain pacing program, body scan ACT for pain, long COVID pain education.',
            'fnon_hypothesis': 'Post-COVID pain reflects central sensitization driven by neuroinflammation. M1 + occipital TPS activates analgesic pathways while taVNS reduces neuroinflammatory cytokine signaling.',
        },
        {
            'code': 'P6', 'name': 'Sleep Disruption (Long COVID)',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Fz', 'TPS FT7 sleep', 'CBT-I adapted'],
            'card_left': ['Network: Hyperarousal + circadian disruption', 'Key target: Thalamus (CES), DLPFC', 'Priority: Sleep architecture repair'],
            'card_right': ['TPS: T2+T5 + FT7', 'tDCS: C6/F6', 'PlatoScience: C4-PS/FP6', 'CBT-I'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep control', 'Balance', 'T2 / C6 / FP6', 'Emerging'],
                ['Thalamus (CES)', 'Sleep gating', 'Support', 'CES protocol', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Suppress', 'T5 / C5', 'Emerging'],
                ['mPFC', 'Rumination', 'Downregulate', 'FT3 / F3', 'Emerging'],
                ['Hypothalamus', 'Circadian reset', 'Normalize (CES)', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C6', 'TPS DLPFC sleep', 'CBT-I adapted long COVID'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction protocol'],
                ['CES 20 min', 'tDCS F6', 'TPS thalamus Cz', 'Stimulus control'],
                ['taVNS 20 min', 'tDCS F3', 'TPS mPFC', 'Progressive relaxation'],
            ],
            'task_pairing': 'CBT-I adapted for long COVID, sleep restriction therapy, stimulus control, progressive muscle relaxation.',
            'fnon_hypothesis': 'Long COVID sleep disruption reflects thalamic function impairment by neuroinflammation. CES directly targets thalamic sleep gating circuits while prefrontal tDCS reduces hyperarousal.',
        },
        {
            'code': 'P7', 'name': 'Anxiety & Mental Health (Long COVID)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC+vmPFC', 'Illness CBT'],
            'card_left': ['Network: SN + LIMBIC dysregulation', 'Key target: DLPFC, vmPFC, SN', 'Priority: Illness-related anxiety'],
            'card_right': ['TPS: T1 + FT4', 'tDCS: C8/F1', 'PlatoScience: C7-PS/FP4', 'CBT task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety regulation', 'Activate', 'T1 / C8 / FP4', 'Emerging'],
                ['vmPFC', 'Safety signal', 'Strengthen', 'FT6 / F1', 'Emerging'],
                ['SN nodes', 'Symptom anxiety', 'Reduce', 'FT4 / Cz', 'Emerging'],
                ['Amygdala', 'Health fear', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['ACC', 'Worry circuit', 'Modulate', 'T5 / C5', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC', 'CBT illness anxiety'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Illness acceptance ACT'],
                ['taVNS 20 min', 'tDCS F1', 'TPS SN suppress', 'Symptom diary rational'],
                ['CES 20 min', 'tDCS C8', 'TPS amygdala', 'Breathing + grounding'],
            ],
            'task_pairing': 'CBT for illness anxiety, illness acceptance ACT, rational symptom diary, breathing and grounding exercises.',
            'fnon_hypothesis': 'Long COVID anxiety reflects illness-specific SN hyperactivation amplifying symptom fear. DLPFC TPS during illness acceptance work strengthens reappraisal pathways.',
        },
        {
            'code': 'P8', 'name': 'Dyspnea & Breathlessness',
            'sozo_bar': ['taVNS 40 min', 'tDCS C3 insula', 'TPS insula FT5', 'Breathing retraining'],
            'card_left': ['Network: Insula + autonomic dyspnea circuit', 'Key target: Insula, ACC, brainstem', 'Priority: Dyspnea threshold recalibration'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C3/F3', 'PlatoScience: C5-PS/FP3', 'Breathing task'],
            'brain_targets': [
                ['Insula', 'Dyspnea integration', 'Normalize', 'T3 / C3 / FP3', 'Emerging'],
                ['ACC', 'Dyspnea distress', 'Modulate', 'T5 / C5', 'Emerging'],
                ['vmPFC', 'Safety breathing', 'Strengthen', 'FT6 / F3', 'Emerging'],
                ['Brainstem (taVNS)', 'Respiratory-vagal', 'Modulate', 'taVNS extended', 'Evidence B'],
                ['M1 respiratory', 'Breathing motor', 'Support', 'TPS Cz', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C3 insula', 'TPS insula', 'Breathing retraining physio'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS ACC', 'Dysfunctional breathing CBT'],
                ['taVNS 40 min', 'tDCS F3', 'TPS vmPFC', 'Paced breathing 6 cpm'],
                ['CES 20 min', 'tDCS C3', 'TPS insula bilateral', 'Respiratory physiotherapy'],
            ],
            'task_pairing': 'Breathing retraining physiotherapy, dysfunctional breathing CBT, paced breathing 6 cpm, respiratory physiotherapy.',
            'fnon_hypothesis': 'Post-COVID dyspnea reflects insula hypervigilance to respiratory sensations with ACC amplification. Insula TPS recalibrates dyspnea threshold while taVNS modulates vagal-respiratory coupling.',
        },
        {
            'code': 'P9', 'name': 'Comprehensive Long COVID',
            'sozo_bar': ['taVNS 30 min', 'HDCstim F3/F4+C3/C4', 'TPS FT9 rotating', 'Holistic rehab'],
            'card_left': ['Network: Multi-system neurological disruption', 'Key target: Full network rehabilitation', 'Priority: Holistic recovery'],
            'card_right': ['TPS: FT9 comprehensive', 'tDCS: C1+C3/F1+F3', 'PlatoScience: C1-PS/FP1', 'Holistic program'],
            'brain_targets': [
                ['DLPFC bilateral', 'Cognitive + mood', 'Maximize', 'T1 / C1 / FP1', 'Emerging'],
                ['Insula', 'Autonomic + fatigue', 'Normalize', 'T3 / C3', 'Emerging'],
                ['ACC', 'Attention + pain', 'Modulate', 'T5 / C5', 'Emerging'],
                ['vmPFC', 'Mood + safety', 'Strengthen', 'FT6 / F3', 'Emerging'],
                ['Hippocampus', 'Memory recovery', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'HDCstim F3/F4', 'TPS DLPFC rotating', 'Long COVID rehab program'],
                ['CES 20 min', 'PlatoScience Variant B+D', 'TPS rotating cognitive+autonomic', 'Multi-disciplinary MDT'],
                ['taVNS 20 min', 'tDCS C1+C3', 'TPS comprehensive rotating', 'Pacing + cognitive'],
                ['CES 20 min', 'HDCstim C3/C4', 'TPS insula+DLPFC', 'Holistic wellness protocol'],
            ],
            'task_pairing': 'Long COVID comprehensive rehabilitation, multi-disciplinary team approach, pacing + cognitive + autonomic combined.',
            'fnon_hypothesis': 'Comprehensive long COVID reflects multi-system neurological disruption requiring holistic network targeting. Rotating SOZO protocol addresses CEN, autonomic, fatigue, and mood circuits in coordinated sessions.',
        },
    ],
    'task_pairing_rows': [
        ['Cognitive rehab', 'Post-TPS', 'Cognitive', 'P1'],
        ['Pacing program', 'Post-session', 'Fatigue', 'P2'],
        ['HRV biofeedback', 'During taVNS', 'Autonomic', 'P3'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P4'],
        ['Pain education', 'Post-TPS', 'Pain', 'P5'],
        ['CBT-I sleep', 'Evening CES', 'Sleep', 'P6'],
        ['Illness CBT', 'Post-TPS', 'Anxiety', 'P7'],
        ['Breathing retraining', 'Concurrent tDCS', 'Respiratory', 'P8'],
        ['MDT rehab', 'Full session', 'Comprehensive', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'PCFS, PROMIS fatigue', 'Function + fatigue', 'PEM monitoring'],
        ['Week 4', 'PCFS, MoCA, PHQ-9', 'Cognition + mood + function', 'Adjust if PEM triggered'],
        ['Week 6', 'Full long COVID battery', 'All domains', 'Phase 2 decision'],
        ['Week 10', 'PCFS, PROMIS, QoL', 'Long-term trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment', 'All domains', 'Recovery trajectory'],
        ['Month 6', 'Full reassessment + work capacity', 'Return to function', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('long_covid'),
}
'''

with open(data_file, 'a', encoding='utf-8') as f:
    f.write(asd_chunk)
    f.write(long_covid_chunk)

import os
size = os.path.getsize(data_file)
print(f"Appended asd, long_covid. File size: {size // 1024} KB")
