"""Append ptsd, ocd, ms to partners_all_in_one_data.py"""
import os
data_file = os.path.join(os.path.dirname(__file__), 'partners_all_in_one_data.py')

ptsd_chunk = '''
PARTNERS_CONDITIONS['ptsd'] = {
    'condition_full': 'Post-Traumatic Stress Disorder',
    'condition_short': 'PTSD',
    'condition_slug': 'ptsd',
    'fnon_classification': 'LIMBIC hyperactivation / vmPFC hypofunction / CEN hypo / amygdala dysregulation',
    'fnon_montage_selection': [
        ['vmPFC extinction dominant', 'HDCstim tDCS Fp1 anode / Cz cathode'],
        ['DLPFC executive control', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Hyperarousal dominant', 'tDCS Cz cathode + taVNS extended'],
        ['Flashback/intrusion', 'tDCS Fp1 + F4 bilateral'],
        ['Sleep PTSD', 'tDCS F3/Fz + CES protocol'],
    ],
    'tps': [
        ['T1', 'vmPFC extinction recall', 'Fp1 / vmPFC', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T2', 'DLPFC cognitive control', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'ACC threat monitoring', 'Fz / ACCproxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T4', 'Amygdala via temporal', 'T3/T4 temporal', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T5', 'Hippocampal contextual', 'T5/T6 hippocampus', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'vmPFC extinction strengthen', 'vmPFC hypofunction', 'Fp1 / Fpz bilateral', 'Fear extinction memory', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT2', 'CEN activation', 'CEN hypofunction', 'F3/F4 DLPFC', 'Cognitive reappraisal capacity', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT3', 'Amygdala inhibition', 'LIMBIC hyperactivation', 'Temporal T3/T4 bilateral', 'Fear response dampening', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT4', 'Hippocampal context', 'Memory contextualization failure', 'T5/T6 hippocampus proxy', 'Trauma context discrimination', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT5', 'Hyperarousal SN suppress', 'SN hyperactivation', 'Cz + insula C3', 'Threat salience reduction', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT6', 'DMN intrusion break', 'DMN-trauma rumination', 'mPFC Fp1 + PCC Pz', 'Intrusive memory reduction', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Autonomic regulation', 'Autonomic hyperarousal', 'Insula C3 + vagal', 'HRV restoration', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT8', 'Sleep-PTSD circuit', 'Nightmare-hyperarousal', 'F3 + Cz', 'Sleep architecture repair', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Trauma processing enhancement', 'Multi-network', 'vmPFC+DLPFC+amygdala rotating', 'CPT/PE augmentation', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'vmPFC strengthen', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'DLPFC cognitive', 'F3/F4 anodes / Oz', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Hyperarousal reduce', 'Cz cathode / F3 anode', '2 mA', '20 min', 'Emerging'],
        ['C4', 'Amygdala indirect', 'F4 anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Sleep PTSD', 'F3 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Emotional regulation', 'Fp1 anode / mastoid cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C7', 'Depression comorbid', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Dissociation', 'F4 anode / F3 cathode', '1.5 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'vmPFC extinction', 'vmPFC hypofunction', 'Fp1 anode / Cz cathode', 'Fear extinction strengthen', '1.5 mA', '20 min'],
        ['F2', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Cognitive control restore', '2 mA', '20 min'],
        ['F3', 'Amygdala inhibit', 'LIMBIC hyperactivation', 'F4 anode / shoulder', 'Emotional dampening', '2 mA', '20 min'],
        ['F4', 'SN suppress hyperarousal', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Arousal threshold', '2 mA', '20 min'],
        ['F5', 'DMN intrusion', 'DMN rumination', 'Fp1 cathode / Pz cathode', 'Intrusive thought reduction', '1.5 mA', '20 min'],
        ['F6', 'Sleep circuit', 'PTSD-insomnia', 'F3 anode / Cz cathode', 'Nightmare reduction', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Calm regulation', 'Variant D', 'Fp1/Cz', '1.2 mA', '20 min', 'Pre-trauma therapy'],
        ['C2-PS', 'Cognitive control', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'CPT/PE augmentation'],
        ['C3-PS', 'Mood stabilize', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Comorbid depression'],
        ['C4-PS', 'Sleep', 'Variant G', 'F3/Cz', '1.2 mA', '20 min', 'PTSD nightmares'],
        ['C5-PS', 'Grounding', 'Variant D', 'F3/Fp1', '1.2 mA', '20 min', 'Grounding exercises'],
        ['C6-PS', 'Autonomic balance', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'HRV support'],
        ['C7-PS', 'Social reconnection', 'Variant C', 'F3/TP9', '1.4 mA', '20 min', 'Social engagement'],
        ['C8-PS', 'Dissociation support', 'Variant B', 'F4/F3', '1.4 mA', '20 min', 'Grounding + present'],
    ],
    'fnon_plato': [
        ['FP1', 'vmPFC support', 'vmPFC hypofunction', 'Variant D', 'Fp1/Cz', '1.2 mA', '20 min'],
        ['FP2', 'CEN activate', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'LIMBIC calm', 'LIMBIC hyperactivation', 'Variant F', 'F3/C3', '1.2 mA', '20 min'],
        ['FP4', 'SN suppress', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP5', 'DMN break', 'DMN intrusion', 'Variant G', 'Fp1/Pz', '1.2 mA', '20 min'],
        ['FP6', 'Sleep-PTSD', 'PTSD insomnia', 'Variant G', 'F3/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Hyperarousal Dominant',
            'sozo_bar': ['taVNS 40 min', 'tDCS Cz cathode/F3 anode', 'TPS FT5 SN suppress', 'Grounding task'],
            'card_left': ['Network: SN hyperactivation + autonomic', 'Key target: SN nodes, insula, ACC', 'Priority: Arousal threshold normalization'],
            'card_right': ['TPS: T3 + FT5', 'tDCS: C3/F4', 'PlatoScience: C1-PS/FP4', 'Grounding'],
            'brain_targets': [
                ['SN nodes (Cz)', 'Threat detection', 'Suppress', 'FT5 / C3 / FP4', 'Emerging'],
                ['Insula', 'Autonomic', 'Normalize', 'T3 / C6', 'Emerging'],
                ['Amygdala', 'Fear hyperreactivity', 'Downregulate', 'FT3 / T4', 'Emerging'],
                ['ACC', 'Threat monitoring', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Brainstem (taVNS)', 'Autonomic tone', 'Activate vagal', 'taVNS extended', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C3 cathode', 'TPS SN suppress Cz', 'Grounding exercises'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', '5-4-3-2-1 sensory grounding'],
                ['taVNS 40 min', 'tDCS F4', 'TPS insula', 'HRV biofeedback'],
                ['CES 20 min', 'tDCS F4', 'TPS amygdala temporal', 'Breathing 4-7-8'],
            ],
            'task_pairing': 'Grounding exercises (5-4-3-2-1 sensory), HRV biofeedback, diaphragmatic breathing, body-based stabilization.',
            'fnon_hypothesis': 'Hyperarousal PTSD reflects SN hyperactivation with lowered threat detection threshold. Extended taVNS restores vagal brake while tDCS reduces SN excitability.',
        },
        {
            'code': 'P2', 'name': 'Re-experiencing / Intrusions',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1 anode', 'TPS vmPFC+hippocampus', 'Trauma narrative'],
            'card_left': ['Network: vmPFC hypo + hippocampal context failure', 'Key target: vmPFC, hippocampus, PCC', 'Priority: Extinction memory + context'],
            'card_right': ['TPS: T1 + FT4', 'tDCS: C1/F1', 'PlatoScience: C2-PS/FP1', 'CPT session'],
            'brain_targets': [
                ['vmPFC', 'Extinction recall', 'Strengthen', 'T1 / C1 / FP1', 'Evidence B'],
                ['Hippocampus', 'Context memory', 'Activate', 'T5 / FT4', 'Emerging'],
                ['PCC', 'Self-referential', 'Modulate', 'FT6 / Pz', 'Emerging'],
                ['ACC', 'Conflict monitoring', 'Activate', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Fear tag removal', 'Downregulate', 'FT3 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS Fp1 anode', 'TPS vmPFC', 'CPT written accounts'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS hippocampus', 'Trauma narrative'],
                ['taVNS 30 min', 'tDCS C1', 'TPS vmPFC+hippo', 'Extinction exposure'],
                ['CES 20 min', 'tDCS F1', 'TPS PCC', 'Memory reconsolidation'],
            ],
            'task_pairing': 'CPT written accounts, prolonged exposure narrative, extinction learning tasks, memory reconsolidation exercises.',
            'fnon_hypothesis': 'Re-experiencing reflects vmPFC failure to inhibit amygdala during trauma cue encounters. vmPFC TPS during extinction tasks strengthens fear inhibition pathways.',
        },
        {
            'code': 'P3', 'name': 'Avoidance & Emotional Numbing',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC+vmPFC', 'Approach task'],
            'card_left': ['Network: CEN hypo + emotional blunting', 'Key target: DLPFC bilateral, vmPFC', 'Priority: Emotional processing reactivation'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C2/F2', 'PlatoScience: C5-PS/FP2', 'Approach task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Approach motivation', 'Activate', 'T2 / C2 / FP2', 'Evidence B'],
                ['vmPFC', 'Positive affect', 'Restore', 'T1 / F1', 'Emerging'],
                ['Striatum', 'Reward processing', 'Activate (TPS)', 'TPS frontal lateral', 'Emerging'],
                ['Insula', 'Emotional sensing', 'Normalize', 'T3 / C6', 'Emerging'],
                ['ACC', 'Emotional engagement', 'Activate', 'T3 / C3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS vmPFC', 'Approach hierarchy'],
                ['taVNS 20 min', 'tDCS C2', 'TPS striatal', 'Pleasant activities'],
                ['CES 20 min', 'tDCS F2', 'TPS insula', 'Emotion labeling task'],
            ],
            'task_pairing': 'Behavioral activation, approach behavior hierarchy, emotion labeling tasks, positive experience scheduling.',
            'fnon_hypothesis': 'Avoidance/numbing reflects CEN hypofunction reducing approach motivation and vmPFC suppression of positive affect. DLPFC activation restores approach-avoidance balance.',
        },
        {
            'code': 'P4', 'name': 'Negative Cognitions & Mood',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L+vmPFC', 'CPT cognitive task'],
            'card_left': ['Network: CEN hypo + LIMBIC dysregulation', 'Key target: DLPFC L, vmPFC, ACC', 'Priority: Negative belief restructuring'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C7/F2', 'PlatoScience: C3-PS/FP2', 'CPT task'],
            'brain_targets': [
                ['DLPFC L', 'Cognitive restructuring', 'Activate', 'T2 / C7 / FP2', 'Evidence B'],
                ['vmPFC', 'Self-concept', 'Normalize', 'T1 / F1', 'Emerging'],
                ['ACC', 'Negative monitoring', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['Hippocampus', 'Episodic reframing', 'Support', 'FT4 / taVNS', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'CPT stuck point worksheets'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Cognitive challenging task'],
                ['taVNS 20 min', 'tDCS C7', 'TPS ACC', 'Thought records'],
                ['CES 20 min', 'tDCS F2', 'TPS amygdala', 'Self-compassion exercise'],
            ],
            'task_pairing': 'CPT stuck point worksheets, cognitive challenging tasks, thought records, self-compassion exercises.',
            'fnon_hypothesis': 'Negative cognitions in PTSD reflect DLPFC L hypofunction allowing unchecked negative belief schemas. L-DLPFC TPS during CPT enhances cognitive restructuring capacity.',
        },
        {
            'code': 'P5', 'name': 'Complex PTSD (C-PTSD)',
            'sozo_bar': ['taVNS 40 min', 'tDCS F3/Fp1', 'TPS vmPFC+DLPFC', 'Phase-based therapy'],
            'card_left': ['Network: Multi-network chronic dysregulation', 'Key target: vmPFC, DLPFC, amygdala, insula', 'Priority: Safety-first stabilization'],
            'card_right': ['TPS: T1+T2 + FT9', 'tDCS: C6/F1+F2', 'PlatoScience: C1-PS/FP1', 'Phase 1 safety'],
            'brain_targets': [
                ['vmPFC', 'Safety signal', 'Strengthen', 'T1 / C1 / FP1', 'Evidence B'],
                ['DLPFC bilateral', 'Executive regulation', 'Activate', 'T2 / C2', 'Evidence B'],
                ['Insula', 'Body safety', 'Normalize', 'FT7 / C6', 'Emerging'],
                ['Amygdala', 'Chronic fear', 'Progressively inhibit', 'FT3 / temporal', 'Emerging'],
                ['Hippocampus', 'Autobiographic memory', 'Restore', 'FT4 / taVNS', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS Fp1 anode', 'TPS vmPFC', 'Phase 1: stabilization'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', 'Distress tolerance skills'],
                ['taVNS 30 min', 'tDCS F1', 'TPS amygdala (gradual)', 'Phase 2: trauma processing'],
                ['CES 20 min', 'tDCS C6', 'TPS insula', 'Body-based therapy'],
            ],
            'task_pairing': 'Phase-based trauma therapy (stabilization → processing → integration), distress tolerance DBT skills, body-based therapy.',
            'fnon_hypothesis': 'C-PTSD reflects chronic multi-network dysregulation requiring phase-based approach. vmPFC stabilization must precede trauma processing to avoid retraumatization.',
        },
        {
            'code': 'P6', 'name': 'PTSD with Dissociation',
            'sozo_bar': ['taVNS 20 min', 'tDCS F4/Fp1', 'TPS DLPFC R+vmPFC', 'Grounding + present'],
            'card_left': ['Network: Excessive limbic inhibition + derealization', 'Key target: DLPFC R, insula, temporal', 'Priority: Present-moment anchoring'],
            'card_right': ['TPS: FT1 + FT4', 'tDCS: C8/F2', 'PlatoScience: C8-PS/FP2', 'Grounding task'],
            'brain_targets': [
                ['DLPFC R', 'Present orientation', 'Activate', 'T2 R / C8 / FP2', 'Emerging'],
                ['Insula', 'Body awareness', 'Activate', 'FT7 / C6', 'Emerging'],
                ['Temporal cortex', 'Time orientation', 'Activate', 'FT4 / T5 area', 'Emerging'],
                ['vmPFC', 'Reality monitoring', 'Normalize', 'T1 / F1', 'Emerging'],
                ['ACC', 'Self-monitoring', 'Activate', 'T3 / C3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F4', 'TPS DLPFC R', 'Grounding + orientation tasks'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS insula', 'Body sensation scan'],
                ['taVNS 20 min', 'tDCS C8', 'TPS temporal', 'Present-focus mindfulness'],
                ['CES 20 min', 'tDCS Fp1', 'TPS vmPFC', 'Reality anchoring exercises'],
            ],
            'task_pairing': 'Grounding and orientation tasks, body sensation awareness, present-focus mindfulness, reality anchoring exercises.',
            'fnon_hypothesis': 'Dissociative PTSD reflects excessive limbic inhibition reducing emotional engagement with reality. R-DLPFC + insula activation restores present-moment embodied awareness.',
        },
        {
            'code': 'P7', 'name': 'PTSD-Insomnia / Nightmares',
            'sozo_bar': ['CES 20 min', 'tDCS F3/Cz', 'TPS FT8 sleep circuit', 'IRT protocol'],
            'card_left': ['Network: Hyperarousal + REM disruption', 'Key target: DLPFC, ACC, thalamus', 'Priority: Sleep architecture + nightmare'],
            'card_right': ['TPS: FT8 + T3', 'tDCS: C5/F6', 'PlatoScience: C4-PS/FP6', 'IRT task'],
            'brain_targets': [
                ['DLPFC', 'Pre-sleep control', 'Activate', 'T2 / C5 / FP6', 'Emerging'],
                ['ACC', 'Hyperarousal', 'Suppress', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Nightmare generation', 'Downregulate', 'FT8 / temporal', 'Emerging'],
                ['Thalamus', 'REM gating (CES)', 'Normalize', 'CES protocol', 'Emerging'],
                ['vmPFC', 'Nightmare content', 'Modulate', 'T1 / F1', 'Emerging'],
            ],
            'combinations': [
                ['CES 20 min', 'tDCS C5', 'TPS FT8 sleep', 'IRT nightmare rescripting'],
                ['taVNS 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Sleep restriction protocol'],
                ['CES 20 min', 'tDCS F6', 'TPS DLPFC', 'CBT-I adapted PTSD'],
                ['taVNS 20 min', 'tDCS F3', 'TPS thalamus proxy', 'Relaxation pre-sleep'],
            ],
            'task_pairing': 'Image Rehearsal Therapy (IRT) for nightmares, CBT-I adapted for PTSD, relaxation protocol pre-sleep.',
            'fnon_hypothesis': 'PTSD nightmares reflect amygdala-REM hyperactivation replaying fear memories. Evening CES + amygdala TPS reduces fear network activity during REM sleep.',
        },
        {
            'code': 'P8', 'name': 'Moral Injury / Guilt',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp1/F3', 'TPS vmPFC+mPFC', 'Adaptive disclosure'],
            'card_left': ['Network: mPFC self-judgment + LIMBIC', 'Key target: mPFC, vmPFC, ACC', 'Priority: Self-referential processing'],
            'card_right': ['TPS: T1 + FT6', 'tDCS: C6/F1', 'PlatoScience: C3-PS/FP1', 'AD task'],
            'brain_targets': [
                ['mPFC', 'Self-evaluation', 'Normalize', 'FT6 / Fp1 / FP1', 'Emerging'],
                ['vmPFC', 'Self-forgiveness', 'Activate', 'T1 / C6', 'Emerging'],
                ['ACC', 'Moral monitoring', 'Modulate', 'T3 / C3', 'Emerging'],
                ['Amygdala', 'Guilt/shame affect', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['Insula', 'Shame embodiment', 'Normalize', 'FT7 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS Fp1', 'TPS vmPFC', 'Adaptive Disclosure therapy'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS mPFC', 'Self-compassion letter'],
                ['taVNS 20 min', 'tDCS F1', 'TPS ACC', 'Moral injury narrative'],
                ['CES 20 min', 'tDCS C6', 'TPS insula', 'Forgiveness meditation'],
            ],
            'task_pairing': 'Adaptive Disclosure Therapy (ADT), self-compassion exercises, moral injury narrative processing, forgiveness meditation.',
            'fnon_hypothesis': 'Moral injury reflects hyperactivated self-judgment circuits in mPFC-insula with failure of vmPFC self-compassion pathways. vmPFC TPS during forgiveness tasks activates self-acceptance networks.',
        },
        {
            'code': 'P9', 'name': 'Combat/First Responder PTSD',
            'sozo_bar': ['taVNS 40 min', 'tDCS F3/Fp1', 'TPS vmPFC+amygdala', 'PE augmentation'],
            'card_left': ['Network: Severe LIMBIC hyperactivation + CEN collapse', 'Key target: vmPFC, amygdala, DLPFC', 'Priority: Full SOZO trauma protocol'],
            'card_right': ['TPS: FT9 full + T1+T2', 'tDCS: C2/F1+F2', 'PlatoScience: C2-PS/FP2', 'PE/CPT combined'],
            'brain_targets': [
                ['vmPFC', 'Fear extinction', 'Maximize', 'T1 / F1 / FP1', 'Evidence B'],
                ['DLPFC bilateral', 'Executive regulation', 'Maximize', 'T2 / C2 / FP2', 'Evidence B'],
                ['Amygdala bilateral', 'Combat fear', 'Progressively inhibit', 'FT3 / bilateral temporal', 'Emerging'],
                ['Hippocampus', 'Memory contextualization', 'Restore', 'FT4 / taVNS extended', 'Emerging'],
                ['Insula', 'Embodied safety', 'Normalize', 'FT7 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS F3/Fp1', 'TPS vmPFC+DLPFC', 'PE intensive protocol'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS amygdala bilateral', 'CPT + EMDR combined'],
                ['taVNS 30 min', 'tDCS C2', 'TPS hippocampus', 'Context discrimination tasks'],
                ['CES 20 min', 'HDCstim F3/F4', 'TPS rotating multisite', 'Trauma narrative intensive'],
            ],
            'task_pairing': 'PE (Prolonged Exposure) intensive, CPT + EMDR combined protocol, context discrimination tasks, unit cohesion group therapy.',
            'fnon_hypothesis': 'Combat PTSD reflects maximal LIMBIC hyperactivation with CEN collapse. Full SOZO sequence targeting vmPFC, DLPFC, and amygdala simultaneously provides the strongest neurobiological augmentation of PE/CPT.',
        },
    ],
    'task_pairing_rows': [
        ['Grounding exercises', 'During taVNS', 'Stabilization', 'P1, P6'],
        ['CPT worksheets', 'Post-TPS', 'Trauma processing', 'P2, P4'],
        ['Behavioral activation', 'Post-TPS', 'Approach', 'P3'],
        ['PE narrative', 'Post-TPS', 'Exposure', 'P2, P9'],
        ['IRT nightmares', 'Evening session', 'Sleep', 'P7'],
        ['Adaptive disclosure', 'Post-TPS', 'Moral injury', 'P8'],
        ['Distress tolerance', 'During tDCS', 'DBT skills', 'P5'],
        ['HRV biofeedback', 'During taVNS', 'Autonomic', 'P1'],
    ],
    'followup_rows': [
        ['Week 2', 'PCL-5, PHQ-9', 'PTSD severity + mood', 'Safety check + protocol adjust'],
        ['Week 4', 'PCL-5, CAPS, sleep diary', 'Full PTSD + sleep', 'Phase 2 readiness'],
        ['Week 6', 'PCL-5, WHO-5, GAF', 'Functional assessment', 'Therapy integration check'],
        ['Week 10', 'PCL-5 + PTSD remission', 'Remission trajectory', 'Maintenance planning'],
        ['Month 4', 'Full battery + QoL', 'Long-term recovery', 'Maintenance protocol'],
        ['Month 6', 'PCL-5, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('ptsd'),
}
'''

ocd_chunk = '''
PARTNERS_CONDITIONS['ocd'] = {
    'condition_full': 'Obsessive-Compulsive Disorder',
    'condition_short': 'OCD',
    'condition_slug': 'ocd',
    'fnon_classification': 'Cortico-striato-thalamo-cortical (CSTC) hyperactivation / OFC-ACC error signal / DLPFC hypofunction',
    'fnon_montage_selection': [
        ['OFC dominant', 'HDCstim tDCS Fp2 cathode / F3 anode'],
        ['ACC dominant', 'HDCstim Cz cathode / F3/F4 anodes'],
        ['DLPFC augmentation', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Caudate-SMA circuit', 'tDCS Fz cathode + F3 anode'],
        ['Contamination OCD', 'tDCS F3/Fp2 + TPS OFC'],
    ],
    'tps': [
        ['T1', 'SMA/pre-SMA inhibition', 'Fz / SMA-proxy', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T2', 'OFC modulation', 'Fp2 / OFC-proxy', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T3', 'DLPFC activation', 'F3 / DLPFC L', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T4', 'ACC modulation', 'Fz / ACC-proxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Bilateral DLPFC', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'OFC error signal suppress', 'OFC hyperactivation', 'Fp2 bilateral', 'Obsessive appraisal reduction', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT2', 'SMA-compulsion disrupt', 'SMA hyperactivation', 'Fz SMA-proxy', 'Compulsive urge inhibition', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT3', 'DLPFC augment', 'CEN hypofunction', 'F3/F4 bilateral', 'Inhibitory control restore', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT4', 'ACC error normalize', 'ACC hyperactivation', 'Fz ACC-proxy', 'Error signal recalibration', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT5', 'Caudate circuit', 'Caudate hyperactivation', 'Lateral frontal C3/C4', 'Habit-compulsion break', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Thalamic gating', 'CSTC loop', 'SMA + Cz bilateral', 'Thalamic loop disruption', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT7', 'Insula contamination', 'Disgust-insula', 'C3 insula proxy', 'Disgust response reduction', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT8', 'Checking compulsions', 'OFC-DLPFC mismatch', 'Fp2 + F3', 'Certainty signal restore', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT9', 'Treatment-resistant OCD', 'Full CSTC', 'Rotating OFC/SMA/DLPFC', 'Multi-node CSTC targeting', '0.22 mJ/mm²', '1200 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'OFC inhibit', 'Fp2 cathode / F3 anode', '1.5 mA', '20 min', 'Evidence B'],
        ['C2', 'DLPFC augment', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'SMA suppress', 'Fz cathode / F3 anode', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'ACC modulation', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C5', 'Bilateral inhibitory', 'Fp2 cathode / F3/F4 anodes', '1.5 mA', '20 min', 'Emerging'],
        ['C6', 'Contamination insula', 'C3 cathode / F3 anode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Comorbid depression', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C8', 'Hoarding phenotype', 'F3/F4 bilateral anodes', '2 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'OFC suppress', 'OFC hyperactivation', 'Fp2 cathode / F3 anode', 'Obsessive appraisal down', '1.5 mA', '20 min'],
        ['F2', 'SMA break', 'SMA compulsion', 'Fz cathode / F3 anode', 'Compulsive urge inhibition', '2 mA', '20 min'],
        ['F3', 'DLPFC control', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Inhibitory control', '2 mA', '20 min'],
        ['F4', 'Insula disgust', 'Insula hyperactivation', 'C3 cathode / F3 anode', 'Disgust reduction', '2 mA', '20 min'],
        ['F5', 'ACC normalize', 'ACC error signal', 'Fz anode / Oz cathode', 'Error recalibration', '2 mA', '20 min'],
        ['F6', 'Comorbid anxiety', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Anxiety component', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Focus + inhibit', 'Variant B', 'F3/Fp2', '1.4 mA', '20 min', 'ERP augmentation'],
        ['C2-PS', 'OFC calm', 'Variant D', 'Fp2/F3', '1.2 mA', '20 min', 'Pre-ERP session'],
        ['C3-PS', 'Mood comorbid', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Depression comorbid'],
        ['C4-PS', 'Anxiety calm', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Anxiety comorbid'],
        ['C5-PS', 'Cognitive control', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Inhibitory tasks'],
        ['C6-PS', 'Insula calm', 'Variant F', 'C3/F3', '1.4 mA', '20 min', 'Contamination OCD'],
        ['C7-PS', 'Checking circuit', 'Variant B', 'F3/Fp2', '1.4 mA', '20 min', 'Checking rituals'],
        ['C8-PS', 'Hoarding', 'Variant C', 'F3/F4', '1.4 mA', '20 min', 'Hoarding phenotype'],
    ],
    'fnon_plato': [
        ['FP1', 'OFC suppress', 'OFC hyperactivation', 'Variant D', 'Fp2/F3', '1.2 mA', '20 min'],
        ['FP2', 'DLPFC control', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP3', 'SMA break', 'SMA compulsion', 'Variant D', 'Fz/F3', '1.2 mA', '20 min'],
        ['FP4', 'Insula disgust', 'Insula hyperactivation', 'Variant F', 'C3/F3', '1.4 mA', '20 min'],
        ['FP5', 'Anxiety comorbid', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP6', 'Mood comorbid', 'LIMBIC', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Contamination OCD',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp2 cathode/F3', 'TPS OFC+insula', 'ERP contamination'],
            'card_left': ['Network: OFC + insula disgust circuit', 'Key target: OFC Fp2, insula C3', 'Priority: Disgust-obsession circuit'],
            'card_right': ['TPS: T2 + FT7', 'tDCS: C1/F4', 'PlatoScience: C6-PS/FP4', 'ERP task'],
            'brain_targets': [
                ['OFC', 'Contamination appraisal', 'Suppress', 'T2 / C1 / FP1', 'Evidence B'],
                ['Insula', 'Disgust signal', 'Downregulate', 'FT7 / C6 / FP4', 'Emerging'],
                ['DLPFC', 'Inhibitory control', 'Activate', 'T3 / C2', 'Evidence B'],
                ['ACC', 'Error monitoring', 'Modulate', 'T4 / C4', 'Emerging'],
                ['Caudate', 'Compulsive habit', 'Disrupt', 'FT5 / lateral frontal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1 Fp2 cathode', 'TPS OFC', 'ERP contamination hierarchy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS insula', 'Disgust habituation'],
                ['taVNS 20 min', 'tDCS F4', 'TPS OFC+insula', 'Ritual prevention 30 min'],
                ['CES 20 min', 'tDCS C6', 'TPS DLPFC', 'Cognitive defusion'],
            ],
            'task_pairing': 'ERP contamination hierarchy, disgust habituation tasks, ritual prevention, cognitive defusion for contamination thoughts.',
            'fnon_hypothesis': 'Contamination OCD reflects OFC-insula disgust circuit hyperactivation creating false-alarm contamination signals. TPS + ERP drives habituation through direct neural desensitization.',
        },
        {
            'code': 'P2', 'name': 'Checking Compulsions',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp2 cathode/F3', 'TPS OFC+DLPFC', 'ERP checking'],
            'card_left': ['Network: OFC-DLPFC mismatch / certainty failure', 'Key target: OFC, DLPFC, ACC', 'Priority: Certainty signal restoration'],
            'card_right': ['TPS: T2+T3 + FT8', 'tDCS: C1/F3', 'PlatoScience: C7-PS/FP2', 'Checking ERP'],
            'brain_targets': [
                ['OFC', 'False incomplete signal', 'Suppress', 'T2 / C1 / FP1', 'Evidence B'],
                ['DLPFC', 'Certainty recall', 'Activate', 'T3 / C2 / FP2', 'Evidence B'],
                ['ACC', 'Incompleteness', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['SMA', 'Action urge', 'Inhibit', 'T1 / C3', 'Evidence B'],
                ['Memory circuits', 'Reality monitoring', 'Strengthen', 'taVNS + TPS T5', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1', 'TPS OFC+DLPFC', 'Checking ERP with memory'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Certainty tolerance exercise'],
                ['taVNS 20 min', 'tDCS F3', 'TPS SMA', 'Action urge surfing'],
                ['CES 20 min', 'tDCS C5', 'TPS bilateral', 'Reality monitoring tasks'],
            ],
            'task_pairing': 'Checking ERP with memory confidence tasks, certainty tolerance exercises, urge surfing, reality monitoring training.',
            'fnon_hypothesis': 'Checking OCD reflects OFC false-incomplete signals overwhelming DLPFC certainty recall. DLPFC TPS strengthens memory confidence to resist re-checking urges.',
        },
        {
            'code': 'P3', 'name': 'Intrusive Thoughts (Pure O)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fp2', 'TPS DLPFC+OFC', 'ACT defusion'],
            'card_left': ['Network: Thought-action fusion / ACC hyperactivation', 'Key target: DLPFC, OFC, ACC', 'Priority: Thought-reality distinction'],
            'card_right': ['TPS: T3+T2 + FT3', 'tDCS: C2/F1', 'PlatoScience: C5-PS/FP2', 'Defusion task'],
            'brain_targets': [
                ['DLPFC', 'Thought inhibition', 'Activate', 'T3 / C2 / FP2', 'Evidence B'],
                ['OFC', 'Thought danger appraisal', 'Suppress', 'T2 / C1', 'Evidence B'],
                ['ACC', 'Thought monitoring', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['mPFC', 'Self-referential thought', 'Normalize', 'FT6 / Fp1', 'Emerging'],
                ['Amygdala', 'Thought-affect fusion', 'Downregulate', 'FT3 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C2', 'TPS DLPFC', 'ACT defusion exercises'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS OFC', 'Intrusive thought ERP'],
                ['taVNS 20 min', 'tDCS F1', 'TPS ACC', 'Thought-record CBT'],
                ['CES 20 min', 'tDCS C5', 'TPS mPFC', 'Mindfulness thought labeling'],
            ],
            'task_pairing': 'ACT defusion exercises, intrusive thought ERP (imaginal), CBT thought records, mindfulness thought labeling.',
            'fnon_hypothesis': 'Pure-O OCD reflects thought-action fusion driven by OFC danger appraisal and ACC hypermonitoring. DLPFC TPS during defusion tasks weakens the thought-threat linkage.',
        },
        {
            'code': 'P4', 'name': 'Hoarding Disorder',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC+vmPFC', 'Sorting task'],
            'card_left': ['Network: DLPFC decision deficit + vmPFC over-attachment', 'Key target: DLPFC bilateral, vmPFC', 'Priority: Decision-making restoration'],
            'card_right': ['TPS: T5 + FT3', 'tDCS: C8/F3', 'PlatoScience: C8-PS/FP2', 'Sorting task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Decision making', 'Activate', 'T5 / C8 / FP2', 'Evidence B'],
                ['vmPFC', 'Object attachment', 'Normalize', 'T2 / F1', 'Emerging'],
                ['ACC', 'Discarding distress', 'Modulate', 'T4 / C4', 'Emerging'],
                ['Insula', 'Loss aversion', 'Normalize', 'FT7 / C6', 'Emerging'],
                ['OFC', 'Acquisition urge', 'Suppress', 'T2 / C1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C8 bilateral', 'TPS DLPFC', 'Sorting and discarding ERP'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS vmPFC', 'Decision-making training'],
                ['taVNS 20 min', 'tDCS F3', 'TPS OFC', 'Acquisition ban ERP'],
                ['CES 20 min', 'tDCS C4', 'TPS insula', 'Loss tolerance exercise'],
            ],
            'task_pairing': 'Sorting and discarding ERP, decision-making training, acquisition ban exercises, loss tolerance practice.',
            'fnon_hypothesis': 'Hoarding reflects DLPFC decision-making deficit combined with vmPFC over-attribution of emotional value to objects. Bilateral DLPFC TPS during sorting tasks improves discarding decisions.',
        },
        {
            'code': 'P5', 'name': 'Symmetry / Ordering OCD',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz cathode/F3', 'TPS SMA+DLPFC', 'ERP ordering'],
            'card_left': ['Network: SMA hyperactivation + incompleteness', 'Key target: SMA, DLPFC, ACC', 'Priority: "Not just right" signal'],
            'card_right': ['TPS: T1+T3 + FT2', 'tDCS: C3/F3', 'PlatoScience: C1-PS/FP3', 'Asymmetry ERP'],
            'brain_targets': [
                ['SMA', 'Action urge generation', 'Inhibit', 'T1 / C3 / FP3', 'Evidence B'],
                ['DLPFC', 'Resist urge', 'Activate', 'T3 / C2', 'Evidence B'],
                ['ACC', '"Not just right"', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['Somatosensory', 'Tactile incompleteness', 'Normalize', 'TPS C3/C4', 'Emerging'],
                ['Caudate', 'Habit ordering', 'Disrupt', 'FT5 / lateral', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 Fz cathode', 'TPS SMA', 'Asymmetry tolerance ERP'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS DLPFC', '"Good enough" cognitive task'],
                ['taVNS 20 min', 'tDCS F3', 'TPS ACC', 'Urge surfing symmetry'],
                ['CES 20 min', 'tDCS C5', 'TPS bilateral SMA', 'Incompleteness habituation'],
            ],
            'task_pairing': 'Asymmetry tolerance ERP, "good enough" cognitive training, urge surfing, incompleteness habituation exercises.',
            'fnon_hypothesis': 'Symmetry OCD reflects SMA hyperactivation generating persistent "not just right" incompleteness signals. SMA TPS + ERP extinguishes the sensorimotor incompleteness circuit.',
        },
        {
            'code': 'P6', 'name': 'OCD + Depression Comorbidity',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode/Fp2', 'TPS DLPFC+OFC', 'BA + ERP combined'],
            'card_left': ['Network: OFC + LIMBIC dysregulation', 'Key target: DLPFC L, OFC, ACC', 'Priority: Mood-OCD unified protocol'],
            'card_right': ['TPS: T3+T2 + FT3', 'tDCS: C7/F1', 'PlatoScience: C3-PS/FP6', 'Combined task'],
            'brain_targets': [
                ['DLPFC L', 'Mood + inhibitory', 'Activate', 'T3 / C7 / FP6', 'Evidence B'],
                ['OFC', 'Obsessive appraisal', 'Suppress', 'T2 / C1', 'Evidence B'],
                ['ACC', 'Mood-OCD junction', 'Modulate', 'T4 / C4', 'Emerging'],
                ['Amygdala', 'Affective amplification', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['vmPFC', 'Reward restoration', 'Activate', 'FT1 / F1', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7 F3+Fp2', 'TPS DLPFC+OFC', 'BA + ERP session'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS ACC', 'Combined mood-OCD CBT'],
                ['taVNS 20 min', 'tDCS F1', 'TPS DLPFC', 'Pleasant activity + ERP'],
                ['CES 20 min', 'tDCS C3', 'TPS OFC', 'Thought record + ritual prevention'],
            ],
            'task_pairing': 'Combined BA + ERP sessions, mood-OCD CBT integration, pleasant activity scheduling with ritual prevention.',
            'fnon_hypothesis': 'OCD-depression comorbidity shares DLPFC hypofunction as common substrate. L-DLPFC TPS simultaneously augments ERP effectiveness and behavioral activation outcomes.',
        },
        {
            'code': 'P7', 'name': 'OCD with Tic Disorder',
            'sozo_bar': ['taVNS 20 min', 'tDCS SMA cathode/F3', 'TPS SMA+caudate', 'HRT protocol'],
            'card_left': ['Network: SMA-basal ganglia hyperactivation', 'Key target: SMA Fz, caudate proxy', 'Priority: Motor urge suppression'],
            'card_right': ['TPS: T1 + FT2', 'tDCS: C3/F3', 'PlatoScience: C3-PS/FP3', 'HRT task'],
            'brain_targets': [
                ['SMA', 'Tic + compulsion urge', 'Inhibit', 'T1 / C3 / FP3', 'Evidence B'],
                ['Caudate', 'Habit-motor circuit', 'Modulate', 'FT5 / lateral frontal', 'Emerging'],
                ['DLPFC', 'Urge control', 'Activate', 'T3 / C2', 'Evidence B'],
                ['ACC', 'Monitoring both', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['Putamen', 'Motor sequence', 'Normalize', 'TPS C3/C4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3 SMA cathode', 'TPS SMA', 'HRT habit reversal'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS caudate', 'Competing response training'],
                ['taVNS 20 min', 'tDCS F3', 'TPS DLPFC', 'ERP + tic suppression'],
                ['CES 20 min', 'tDCS C5', 'TPS ACC', 'CBIT comprehensive behavioral'],
            ],
            'task_pairing': 'HRT (Habit Reversal Training), CBIT (Comprehensive Behavioral Intervention for Tics), competing response training, ERP combined.',
            'fnon_hypothesis': 'OCD + Tourette reflects shared SMA-basal ganglia hyperactivation driving both tic and compulsion urges. SMA TPS + HRT addresses both motor symptoms simultaneously.',
        },
        {
            'code': 'P8', 'name': 'Scrupulosity / Religious OCD',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fp2 cathode/F3', 'TPS OFC+mPFC', 'Scrupulosity ERP'],
            'card_left': ['Network: OFC moral + mPFC self-judgment', 'Key target: OFC, mPFC, ACC', 'Priority: Moral error signal reduction'],
            'card_right': ['TPS: T2 + FT1', 'tDCS: C1/F1', 'PlatoScience: C2-PS/FP1', 'ERP task'],
            'brain_targets': [
                ['OFC', 'Moral transgression fear', 'Suppress', 'T2 / C1 / FP1', 'Evidence B'],
                ['mPFC', 'Self-condemnation', 'Normalize', 'FT6 / Fp1', 'Emerging'],
                ['ACC', 'Moral monitoring', 'Recalibrate', 'T4 / C4', 'Emerging'],
                ['DLPFC', 'Cognitive flexibility', 'Activate', 'T3 / C2', 'Evidence B'],
                ['Amygdala', 'Fear of divine punishment', 'Downregulate', 'FT3 / temporal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C1', 'TPS OFC', 'Scrupulosity ERP with clergy'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS mPFC', 'ACT values clarification'],
                ['taVNS 20 min', 'tDCS F1', 'TPS ACC', 'Cognitive defusion for guilt'],
                ['CES 20 min', 'tDCS C5', 'TPS DLPFC', 'Flexible thinking training'],
            ],
            'task_pairing': 'Scrupulosity ERP, ACT values clarification, cognitive defusion for guilt thoughts, flexible religious interpretation exercises.',
            'fnon_hypothesis': 'Scrupulosity reflects OFC moral appraisal hyperactivation with mPFC self-condemnation loop. OFC TPS during ERP reduces false-alarm moral threat signals.',
        },
        {
            'code': 'P9', 'name': 'Treatment-Resistant OCD',
            'sozo_bar': ['taVNS 20 min', 'HDCstim F3/Fp2', 'TPS FT9 rotating', 'Intensive ERP'],
            'card_left': ['Network: Full CSTC hyperactivation', 'Key target: All CSTC nodes', 'Priority: Maximum CSTC disruption'],
            'card_right': ['TPS: FT9 multisite', 'tDCS: C5/F1+F2', 'PlatoScience: C5-PS/FP2', 'Intensive ERP'],
            'brain_targets': [
                ['OFC bilateral', 'Error signal maximal', 'Suppress bilateral', 'T2 bilateral / C5', 'Evidence B'],
                ['SMA', 'Compulsion drive', 'Inhibit', 'T1 / C3', 'Evidence B'],
                ['DLPFC bilateral', 'Inhibitory deficit', 'Maximize', 'T5 / C2', 'Evidence B'],
                ['Caudate bilateral', 'Habit loop', 'Disrupt', 'FT5+FT6 rotating', 'Emerging'],
                ['Thalamus (taVNS)', 'CSTC relay', 'Modulate', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'HDCstim F3/Fp2', 'TPS OFC+SMA', 'Intensive ERP daily'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS DLPFC bilateral', 'Meta-cognitive therapy'],
                ['taVNS 20 min', 'tDCS C5', 'TPS rotating CSTC', 'ACT + ERP combined'],
                ['CES 20 min', 'HDCstim Cz cathode', 'TPS caudate + thalamus', 'D-cycloserine adjunct protocol'],
            ],
            'task_pairing': 'Intensive daily ERP, meta-cognitive therapy, ACT + ERP combined, consider adjunct pharmacological support.',
            'fnon_hypothesis': 'Treatment-resistant OCD requires maximum CSTC circuit disruption. Rotating multisite TPS across OFC, SMA, DLPFC, and caudate provides comprehensive loop disruption not achievable with single-site approaches.',
        },
    ],
    'task_pairing_rows': [
        ['ERP hierarchy', 'Post-TPS', 'Behavioral', 'All phenotypes'],
        ['ACT defusion', 'During tDCS', 'ACT', 'P3, P6, P8'],
        ['HRT tic', 'Post-TPS', 'Behavioral', 'P7'],
        ['Sorting task', 'Concurrent tDCS', 'Behavioral', 'P4'],
        ['Asymmetry tolerance', 'Post-TPS', 'Behavioral', 'P5'],
        ['Scrupulosity ERP', 'Post-TPS', 'Behavioral', 'P8'],
        ['Urge surfing', 'During taVNS', 'Mindfulness', 'P2, P5'],
        ['Decision training', 'During tDCS', 'Cognitive', 'P4'],
    ],
    'followup_rows': [
        ['Week 2', 'Y-BOCS, GAD-7', 'OCD severity + anxiety', 'ERP compliance check'],
        ['Week 4', 'Y-BOCS, PHQ-9, QOLI', 'OCD + function', 'Intensify if <25% reduction'],
        ['Week 6', 'Y-BOCS, CGI', 'Clinical global improvement', 'Phase 2 decision'],
        ['Week 10', 'Y-BOCS + QoL', 'Long-term OCD trajectory', 'Maintenance planning'],
        ['Month 4', 'Full OCD battery', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'Y-BOCS, QoL', 'Long-term outcome', 'Annual review'],
    ],
    'plato_programs': _plato_programs_default('ocd'),
}
'''

ms_chunk = '''
PARTNERS_CONDITIONS['ms'] = {
    'condition_full': 'Multiple Sclerosis — Symptom Management',
    'condition_short': 'MS',
    'condition_slug': 'ms',
    'fnon_classification': 'Demyelination-driven network inefficiency / CEN hypofunction / SMN asymmetry / LIMBIC-fatigue overlap',
    'fnon_montage_selection': [
        ['Cognitive impairment dominant', 'HDCstim F3/F4 anodes / Oz cathode'],
        ['Fatigue dominant', 'HDCstim tDCS F3/Fz / CES protocol'],
        ['Spasticity / motor', 'tDCS C3/C4 anodes bilateral'],
        ['Depression MS', 'tDCS F3 anode / F4 cathode'],
        ['Pain MS', 'tDCS C3/C4 + CES'],
    ],
    'tps': [
        ['T1', 'DLPFC cognitive', 'F3/F4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T2', 'M1 motor (spasticity)', 'C3/C4 bilateral', '0.22 mJ/mm²', '1000 pulses', 'Evidence B'],
        ['T3', 'Fatigue circuit', 'F3 + Fz', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
        ['T4', 'ACC attention', 'Fz / ACC-proxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Post-MS depression', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN cognitive restore', 'CEN hypofunction', 'F3/F4 bilateral', 'Cognitive compensation', '0.22 mJ/mm²', '1000 pulses', '12 sessions'],
        ['FT2', 'SMN spasticity', 'SMN hyperexcitability', 'C3/C4 bilateral', 'Spasticity reduction', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT3', 'Fatigue-CEN overlap', 'Fatigue circuit', 'F3/Fz bilateral', 'Neural efficiency', '0.20 mJ/mm²', '800 pulses', '12 sessions'],
        ['FT4', 'DMN normalize', 'DMN disruption', 'mPFC + PCC', 'Default mode stability', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'SN dysregulation', 'SN hyperactivation', 'Cz + insula', 'Fatigue salience reduce', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT6', 'Depression-MS', 'LIMBIC dysregulation', 'DLPFC + vmPFC', 'Mood restoration', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Pain MS central', 'Central sensitization', 'M1 bilateral Cz', 'Pain modulation', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT8', 'Bladder/autonomic', 'Autonomic dysregulation', 'Cz + C3/C4', 'Cortical bladder control', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT9', 'Comprehensive MS', 'Multi-network', 'Rotating cognitive+motor', 'Holistic MS protocol', '0.22 mJ/mm²', '1000 pulses', '15 sessions'],
    ],
    'tdcs': [
        ['C1', 'Cognitive MS', 'F3/F4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C2', 'Fatigue', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'Spasticity M1', 'C3/C4 bilateral / Oz', '2 mA', '20 min', 'Evidence B'],
        ['C4', 'Depression MS', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C5', 'Pain MS', 'C3/C4 anodes / Oz cathode', '2 mA', '20 min', 'Evidence B'],
        ['C6', 'Attention', 'F3 anode / Cz cathode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Walking/balance', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C8', 'Bladder function', 'Cz anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN activate', 'CEN hypofunction', 'F3/F4 anodes / Oz', 'Cognitive compensation', '2 mA', '20 min'],
        ['F2', 'Fatigue circuit', 'Fatigue network', 'F3 anode / Cz cathode', 'Neural efficiency', '2 mA', '20 min'],
        ['F3', 'SMN spasticity', 'SMN hyperexcitability', 'C3/C4 bilateral', 'Motor tone normalize', '2 mA', '20 min'],
        ['F4', 'Depression-MS', 'LIMBIC dysregulation', 'F3 anode / Fp2 cathode', 'Mood restoration', '2 mA', '20 min'],
        ['F5', 'Pain central MS', 'Central pain', 'C3/C4 anodes / Oz', 'Pain gate activation', '2 mA', '20 min'],
        ['F6', 'Autonomic', 'Autonomic dysregulation', 'Cz anode / shoulder', 'Bladder + autonomic', '2 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Cognitive boost', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'MS cognitive tasks'],
        ['C2-PS', 'Energy management', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'MS fatigue'],
        ['C3-PS', 'Mood uplift', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'MS depression'],
        ['C4-PS', 'Focus', 'Variant B', 'F3/Cz', '1.4 mA', '20 min', 'Attention MS'],
        ['C5-PS', 'Pain support', 'Variant E', 'C3/C4', '1.4 mA', '20 min', 'MS pain'],
        ['C6-PS', 'Sleep MS', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'MS insomnia'],
        ['C7-PS', 'Spasticity support', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'Spasticity + tDCS'],
        ['C8-PS', 'Balance/gait', 'Variant E', 'Cz/C3', '1.4 mA', '20 min', 'Gait MS'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN cognitive', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'Fatigue', 'Fatigue circuit', 'Variant D', 'F3/Cz', '1.2 mA', '20 min'],
        ['FP3', 'SMN motor', 'SMN dysfunction', 'Variant F', 'C3/C4', '1.4 mA', '20 min'],
        ['FP4', 'LIMBIC mood', 'LIMBIC dysregulation', 'Variant A', 'F3/F4', '1.4 mA', '20 min'],
        ['FP5', 'Pain MS', 'Central pain', 'Variant E', 'C3/C4', '1.4 mA', '20 min'],
        ['FP6', 'Sleep MS', 'Sleep disruption', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Cognitive Impairment (MS)',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/F4 bilateral', 'TPS DLPFC bilateral', 'Cognitive rehab'],
            'card_left': ['Network: CEN white matter inefficiency', 'Key target: DLPFC bilateral', 'Priority: Cognitive compensation'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C1-PS/FP1', 'Cognitive task'],
            'brain_targets': [
                ['DLPFC bilateral', 'Working memory', 'Activate', 'T1 / C1 / FP1', 'Evidence B'],
                ['PFC bilateral', 'Executive function', 'Upregulate', 'FT1 / C6', 'Emerging'],
                ['Hippocampus', 'Learning', 'Support (taVNS)', 'taVNS', 'Emerging'],
                ['ACC', 'Attention', 'Activate', 'T4 / C6', 'Emerging'],
                ['Thalamus', 'Arousal (CES)', 'Normalize', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/F4', 'TPS DLPFC', 'Computerized cognitive rehab'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS bilateral PFC', 'Working memory training'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Attention and processing speed'],
                ['CES 20 min', 'tDCS C6', 'TPS hippocampus', 'Memory encoding tasks'],
            ],
            'task_pairing': 'Computerized cognitive rehabilitation, working memory n-back, processing speed training, memory encoding tasks.',
            'fnon_hypothesis': 'MS cognitive impairment reflects white matter disconnection reducing CEN efficiency. Bilateral DLPFC TPS compensates by activating residual cortical tissue and promoting alternative neural routing.',
        },
        {
            'code': 'P2', 'name': 'MS-Related Fatigue',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Fz', 'TPS FT3 fatigue', 'Energy pacing'],
            'card_left': ['Network: Fatigue-CEN overlap / neural inefficiency', 'Key target: DLPFC, SMA, ACC', 'Priority: Neural efficiency restoration'],
            'card_right': ['TPS: T3 + FT3', 'tDCS: C2/F2', 'PlatoScience: C2-PS/FP2', 'Pacing task'],
            'brain_targets': [
                ['DLPFC', 'Effort regulation', 'Activate', 'T3 / C2 / FP2', 'Evidence B'],
                ['SMA', 'Motor effort', 'Upregulate', 'FT2 / Fz', 'Emerging'],
                ['ACC', 'Fatigue monitoring', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Thalamus (CES)', 'Arousal', 'Activate', 'CES protocol', 'Emerging'],
                ['Insula', 'Fatigue perception', 'Normalize', 'FT5 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS F3/Fz', 'TPS DLPFC fatigue', 'Energy conservation training'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS ACC', 'Pacing program'],
                ['taVNS 20 min', 'tDCS C2', 'TPS SMA', 'Graded exercise program'],
                ['CES 20 min', 'tDCS F2', 'TPS insula', 'Fatigue diary'],
            ],
            'task_pairing': 'Energy conservation training, pacing program, graded exercise therapy, fatigue diary with activity optimization.',
            'fnon_hypothesis': 'MS fatigue reflects increased neural effort required for routine tasks due to demyelination. DLPFC TPS reduces perceived effort cost, while CES restores thalamic arousal tone.',
        },
        {
            'code': 'P3', 'name': 'Spasticity (MS)',
            'sozo_bar': ['taVNS 20 min', 'tDCS C3/C4 bilateral', 'TPS M1 bilateral', 'Stretching program'],
            'card_left': ['Network: SMN hyperexcitability bilateral', 'Key target: M1 bilateral, SMA', 'Priority: Motor tone normalization'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C3/F3', 'PlatoScience: C7-PS/FP3', 'Stretch + physio'],
            'brain_targets': [
                ['M1 bilateral', 'Spasticity drive', 'Normalize', 'T2 / C3 / FP3', 'Evidence B'],
                ['SMA', 'Tonic motor', 'Balance', 'FT2 / Fz', 'Emerging'],
                ['Cerebellum', 'Coordination', 'Activate', 'TPS lateral', 'Emerging'],
                ['Thalamus (taVNS)', 'Motor relay', 'Modulate', 'taVNS', 'Emerging'],
                ['Spinal (descending)', 'Inhibitory tracts', 'Activate (TPS)', 'TPS M1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C3/C4 bilateral', 'TPS M1 bilateral', 'Stretching + physiotherapy'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS SMA', 'Active movement tasks'],
                ['taVNS 20 min', 'tDCS C3', 'TPS cerebellum', 'Balance training'],
                ['CES 20 min', 'tDCS F3', 'TPS M1+SMA', 'Constraint movement'],
            ],
            'task_pairing': 'Passive and active stretching, physiotherapy, balance training, active movement tasks.',
            'fnon_hypothesis': 'MS spasticity reflects demyelination of descending inhibitory tracts allowing unchecked M1 excitability. Bilateral M1 TPS restores cortical-spinal inhibitory balance.',
        },
        {
            'code': 'P4', 'name': 'Depression (MS)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
            'card_left': ['Network: LIMBIC dysregulation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: Mood circuit support'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C4/F4', 'PlatoScience: C3-PS/FP4', 'BA protocol'],
            'brain_targets': [
                ['DLPFC L', 'Mood upregulation', 'Activate', 'T5 / C4 / FP4', 'Evidence B'],
                ['vmPFC', 'Positive affect', 'Restore', 'FT6 / F4', 'Emerging'],
                ['ACC', 'Mood monitoring', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Amygdala', 'Negative affect', 'Downregulate', 'FT6 / temporal', 'Emerging'],
                ['Hippocampus', 'Depression circuit', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'Behavioral activation'],
                ['CES 20 min', 'PlatoScience Variant A', 'TPS vmPFC', 'Pleasant activity planning'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'CBT for MS mood'],
                ['CES 20 min', 'tDCS F4', 'TPS amygdala', 'Meaning-focused therapy'],
            ],
            'task_pairing': 'Behavioral activation schedule, pleasant activity planning, CBT adapted for MS, meaning-focused intervention.',
            'fnon_hypothesis': 'MS depression reflects both disease burden and direct LIMBIC circuit disruption from lesion load. L-DLPFC TPS provides mood uplift independent of pharmacological pathways.',
        },
        {
            'code': 'P5', 'name': 'Pain (MS — Central)',
            'sozo_bar': ['taVNS 30 min', 'tDCS C3/C4 bilateral', 'TPS M1+DLPFC', 'Pain education'],
            'card_left': ['Network: Central sensitization + demyelination', 'Key target: M1 bilateral, DLPFC, ACC', 'Priority: Pain gate restoration'],
            'card_right': ['TPS: T2+T1 + FT7', 'tDCS: C5/F5', 'PlatoScience: C5-PS/FP5', 'Pain mgmt'],
            'brain_targets': [
                ['M1 bilateral', 'Pain gate', 'Activate', 'T2 / C5 / FP5', 'Evidence B'],
                ['DLPFC', 'Top-down pain', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Pain affect', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Insula', 'Pain integration', 'Normalize', 'FT7 / C6', 'Emerging'],
                ['Thalamus (CES)', 'Pain relay', 'Modulate', 'CES', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C3/C4', 'TPS M1', 'Pain management program'],
                ['CES 20 min', 'PlatoScience Variant E', 'TPS DLPFC', 'Acceptance pain ACT'],
                ['taVNS 20 min', 'tDCS C5', 'TPS ACC', 'Graded motor imagery'],
                ['CES 20 min', 'tDCS F5', 'TPS insula', 'Pain education MS'],
            ],
            'task_pairing': 'Pain management program, acceptance-based pain therapy, graded motor imagery, MS-specific pain education.',
            'fnon_hypothesis': 'MS central pain reflects demyelination disrupting descending inhibitory tracts. M1 TPS activates remaining corticospinal inhibitory pathways compensating for tract damage.',
        },
        {
            'code': 'P6', 'name': 'Walking & Balance (MS)',
            'sozo_bar': ['taVNS 20 min', 'tDCS Fz/C3/C4', 'TPS SMA+M1', 'Gait therapy'],
            'card_left': ['Network: SMN + cerebellar disruption', 'Key target: SMA, M1 bilateral', 'Priority: Gait efficiency'],
            'card_right': ['TPS: T2 + FT2', 'tDCS: C7/F3', 'PlatoScience: C8-PS/FP3', 'Gait task'],
            'brain_targets': [
                ['SMA', 'Gait initiation', 'Activate', 'FT2 / Fz / FP3', 'Evidence B'],
                ['M1 bilateral', 'Leg motor', 'Upregulate', 'T2 / C3', 'Evidence B'],
                ['Cerebellum', 'Balance', 'Activate', 'TPS lateral', 'Emerging'],
                ['PMC', 'Gait planning', 'Activate', 'TPS F3/F4', 'Emerging'],
                ['Basal ganglia', 'Rhythm', 'Support', 'TPS frontal', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS Fz/C3/C4', 'TPS SMA', 'Treadmill gait therapy'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS cerebellum', 'Balance training'],
                ['taVNS 20 min', 'tDCS C7', 'TPS M1 bilateral', 'FES-gait combined'],
                ['CES 20 min', 'tDCS F3', 'TPS PMC', 'Rhythmic cue walking'],
            ],
            'task_pairing': 'Treadmill gait therapy, balance training, FES-gait combined therapy, rhythmic auditory cue walking.',
            'fnon_hypothesis': 'MS gait impairment reflects SMA-M1 circuit disruption from lesion load. SMA TPS during treadmill training maximizes gait program benefit through activity-dependent plasticity.',
        },
        {
            'code': 'P7', 'name': 'Anxiety (MS-Related)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC+vmPFC', 'CBT MS-anxiety'],
            'card_left': ['Network: SN hyperactivation + disease anxiety', 'Key target: DLPFC, vmPFC, amygdala', 'Priority: MS-specific worry'],
            'card_right': ['TPS: T1 + FT5', 'tDCS: C1/F1', 'PlatoScience: C4-PS/FP1', 'CBT task'],
            'brain_targets': [
                ['DLPFC', 'Anxiety regulation', 'Activate', 'T1 / C1 / FP1', 'Evidence B'],
                ['vmPFC', 'Safety signal', 'Strengthen', 'FT6 / F4', 'Emerging'],
                ['SN nodes', 'Disease worry', 'Reduce', 'FT5 / Cz', 'Emerging'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT3 / temporal', 'Emerging'],
                ['ACC', 'Worry monitoring', 'Modulate', 'T4 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC', 'MS-specific CBT anxiety'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Acceptance MS condition'],
                ['taVNS 20 min', 'tDCS C1', 'TPS SN suppress', 'Worry postponement'],
                ['CES 20 min', 'tDCS F1', 'TPS amygdala', 'Disease-anxiety exposure'],
            ],
            'task_pairing': 'MS-specific CBT for health anxiety, acceptance of disease condition, worry postponement, disease-related exposure tasks.',
            'fnon_hypothesis': 'MS anxiety reflects SN hyperactivation amplifying disease-specific fears. DLPFC + vmPFC TPS provides cognitive reappraisal capacity for illness-related anxiety.',
        },
        {
            'code': 'P8', 'name': 'Bladder / Autonomic Dysfunction',
            'sozo_bar': ['taVNS 40 min', 'tDCS Cz/C3', 'TPS FT8 bladder', 'Pelvic floor PT'],
            'card_left': ['Network: Cortical bladder control + autonomic', 'Key target: Cz, insula, SMA', 'Priority: Cortical bladder pathway'],
            'card_right': ['TPS: FT8 + T2', 'tDCS: C8/F6', 'PlatoScience: C6-PS/FP6', 'Bladder PT'],
            'brain_targets': [
                ['Cz (bladder M1)', 'Bladder motor control', 'Activate', 'FT8 / C8 / FP6', 'Emerging'],
                ['Insula', 'Bladder sensation', 'Normalize', 'FT5 / C6', 'Emerging'],
                ['SMA', 'Voiding planning', 'Regulate', 'FT2 / Fz', 'Emerging'],
                ['ACC', 'Urgency control', 'Modulate', 'T4 / C6', 'Emerging'],
                ['Brainstem (taVNS)', 'Vagal-bladder', 'Modulate', 'taVNS extended', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS Cz bilateral', 'TPS bladder Cz', 'Pelvic floor PT'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS insula', 'Bladder training protocol'],
                ['taVNS 40 min', 'tDCS C8', 'TPS SMA', 'Timed voiding schedule'],
                ['CES 20 min', 'tDCS F6', 'TPS ACC urgency', 'Urgency suppression training'],
            ],
            'task_pairing': 'Pelvic floor physiotherapy, bladder training protocol, timed voiding schedule, urgency suppression techniques.',
            'fnon_hypothesis': 'MS bladder dysfunction reflects demyelination of cortical bladder pathways. Cortical bladder area (Cz) TPS activates residual descending bladder control circuits.',
        },
        {
            'code': 'P9', 'name': 'Progressive MS — Comprehensive',
            'sozo_bar': ['taVNS 20 min', 'HDCstim multisite', 'TPS FT9 rotating', 'Adaptive rehab'],
            'card_left': ['Network: Multi-network progressive disruption', 'Key target: Full network compensation', 'Priority: Functional preservation'],
            'card_right': ['TPS: FT9 comprehensive', 'tDCS: C1+C3/F1+F3', 'PlatoScience: C1-PS/FP1', 'Adaptive rehab'],
            'brain_targets': [
                ['DLPFC bilateral', 'Cognitive preservation', 'Maximize', 'T1 / C1 / FP1', 'Evidence B'],
                ['M1 bilateral', 'Motor preservation', 'Support', 'T2 / C3', 'Evidence B'],
                ['SMA', 'Functional motor', 'Upregulate', 'FT2 / Fz', 'Emerging'],
                ['Hippocampus', 'Memory preservation', 'Support (taVNS)', 'taVNS extended', 'Emerging'],
                ['vmPFC', 'Quality of life', 'Maintain', 'FT6 / F4', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'HDCstim F3/F4+C3/C4', 'TPS rotating cognitive+motor', 'Adaptive rehabilitation'],
                ['CES 20 min', 'PlatoScience Variant B+E', 'TPS DLPFC+M1 alternating', 'Goal-directed therapy'],
                ['taVNS 20 min', 'tDCS C1+C3', 'TPS comprehensive rotating', 'Quality of life focus'],
                ['CES 20 min', 'HDCstim Cz+F3', 'TPS multisite', 'Functional preservation program'],
            ],
            'task_pairing': 'Adaptive rehabilitation, goal-directed therapy, quality of life focus program, functional preservation training.',
            'fnon_hypothesis': 'Progressive MS requires preservation strategy across all networks. SOZO comprehensive rotating protocol maintains maximal functional capacity against progressive demyelination.',
        },
    ],
    'task_pairing_rows': [
        ['Cognitive rehab', 'Post-TPS', 'Cognitive', 'P1'],
        ['Energy pacing', 'Post-session', 'Fatigue', 'P2'],
        ['Stretching', 'Concurrent tDCS', 'Spasticity', 'P3'],
        ['Behavioral activation', 'Post-TPS', 'Mood', 'P4'],
        ['Pain education', 'Post-TPS', 'Pain', 'P5'],
        ['Gait therapy', 'Concurrent tDCS', 'Motor', 'P6'],
        ['CBT anxiety', 'Post-TPS', 'Anxiety', 'P7'],
        ['Bladder training', 'Post-TPS', 'Autonomic', 'P8'],
        ['Adaptive rehab', 'Full session', 'Comprehensive', 'P9'],
    ],
    'followup_rows': [
        ['Week 2', 'MFIS, MSSS, MoCA', 'Fatigue + symptoms + cognition', 'Adjust fatigue protocol'],
        ['Week 4', 'MFIS, T25FW, PHQ-9', 'Fatigue + walk + mood', 'Motor protocol review'],
        ['Week 6', 'Full MS battery + QoL', 'Comprehensive assessment', 'Phase 2 decision'],
        ['Week 10', 'MFIS, MSSS, EDSS', 'Disability trajectory', 'Maintenance planning'],
        ['Month 4', 'Full assessment', 'All domains', 'Maintenance protocol'],
        ['Month 6', 'MRI review + QoL', 'Disease activity + function', 'Annual neuro review'],
    ],
    'plato_programs': _plato_programs_default('ms'),
}
'''

with open(data_file, 'a', encoding='utf-8') as f:
    f.write(ptsd_chunk)
    f.write(ocd_chunk)
    f.write(ms_chunk)

import os
size = os.path.getsize(data_file)
print(f"Appended ptsd, ocd, ms. File size: {size // 1024} KB")
