"""Append anxiety (condition 2) to partners_all_in_one_data.py"""
import os
data_file = os.path.join(os.path.dirname(__file__), 'partners_all_in_one_data.py')

chunk = '''
PARTNERS_CONDITIONS['anxiety'] = {
    'condition_full': 'Generalized Anxiety Disorder & Anxiety Spectrum',
    'condition_short': 'Anxiety',
    'condition_slug': 'anxiety',
    'fnon_classification': 'SN hyperactivation / mPFC-amygdala dysregulation / CEN hypofunction',
    'fnon_montage_selection': [
        ['SN hyperactivation dominant', 'HDCstim tDCS Cz cathode + F3/F4 anodes'],
        ['mPFC-amygdala dominant', 'tDCS F3 anode (DLPFC L) / Fp1 cathode'],
        ['Autonomic dominant', 'taVNS + HDCstim C3/C4 anodes'],
        ['Mixed CEN/SN', 'HDCstim F3/F4 + PlatoScience Variant D'],
        ['Comorbid depression', 'F3 anode / F4 cathode + TPS DLPFC L'],
    ],
    'tps': [
        ['T1', 'Core anxiety reduction', 'DLPFC L (F3)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T2', 'Prefrontal inhibitory control', 'DLPFC R (F4)', '0.20 mJ/mm²', '800 pulses', 'Evidence B'],
        ['T3', 'Amygdala modulation via vmPFC', 'Fp1/Fp2', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T4', 'ACC worry circuit', 'Cz / ACCproxy', '0.22 mJ/mm²', '1000 pulses', 'Emerging'],
        ['T5', 'Autonomic regulation (insula)', 'C3 (insula proxy)', '0.20 mJ/mm²', '800 pulses', 'Emerging'],
    ],
    'fnon_tps': [
        ['FT1', 'CEN upregulation', 'CEN hypofunction', 'F3/F4 bilateral', 'Restore PFC executive control', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT2', 'SN downregulation', 'SN hyperactivation', 'Cz + insula C3', 'Reduce threat salience', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT3', 'DMN rumination suppression', 'DMN overactivation', 'mPFC Fp1 + PCC Pz', 'Interrupt worry loops', '0.22 mJ/mm²', '1000 pulses', '8 sessions'],
        ['FT4', 'Limbic circuit calming', 'LIMBIC hyperactivation', 'Amygdala via temporal T3/T4', 'Fear circuit inhibition', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT5', 'Attention reorientation', 'ATTENTION dysregulation', 'IPS P3/P4', 'Shift from threat bias', '0.22 mJ/mm²', '1000 pulses', '8 sessions'],
        ['FT6', 'Autonomic tone restoration', 'Autonomic imbalance', 'Insula C3 + vagal F7', 'HRV improvement', '0.20 mJ/mm²', '800 pulses', '10 sessions'],
        ['FT7', 'Sleep-anxiety cycle', 'DMN/LIMBIC co-activation', 'Fpz + C3', 'Reduce hyperarousal', '0.20 mJ/mm²', '800 pulses', '8 sessions'],
        ['FT8', 'Social anxiety phenotype', 'SN + LIMBIC', 'DMPFC F3 + TP9', 'Social threat reappraisal', '0.22 mJ/mm²', '1000 pulses', '10 sessions'],
        ['FT9', 'Comorbid depression track', 'CEN/DMN dysregulation', 'F3 anode dominant', 'Mood-anxiety unified', '0.22 mJ/mm²', '1200 pulses', '12 sessions'],
    ],
    'tdcs': [
        ['C1', 'Anxiolytic', 'F3 anode / Fp2 cathode', '2 mA', '20 min', 'Evidence B'],
        ['C2', 'Bilateral PFC balance', 'F3/F4 anodes / mastoids', '2 mA', '20 min', 'Evidence B'],
        ['C3', 'SN inhibition', 'Cz cathode / F3 anode', '2 mA', '20 min', 'Emerging'],
        ['C4', 'vmPFC calming', 'Fp1 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C5', 'ACC modulation', 'Fz anode / Oz cathode', '2 mA', '20 min', 'Emerging'],
        ['C6', 'Autonomic (C3 insula)', 'C3 anode / shoulder cathode', '2 mA', '20 min', 'Emerging'],
        ['C7', 'Sleep comorbidity', 'F3 anode / Cz cathode', '1.5 mA', '20 min', 'Emerging'],
        ['C8', 'Social anxiety bilateral', 'F3/F4 anodes / Oz cathode', '2 mA', '25 min', 'Emerging'],
    ],
    'fnon_tdcs': [
        ['F1', 'CEN restore bilateral', 'CEN hypofunction', 'F3/F4 anodes / Oz cathode', 'Executive reactivation', '2 mA', '20 min'],
        ['F2', 'SN suppress via Cz', 'SN hyperactivation', 'Cz cathode / F3 anode', 'Threat salience reduction', '2 mA', '20 min'],
        ['F3', 'mPFC-amygdala balance', 'LIMBIC dysregulation', 'Fp1 anode / mastoid cathode', 'Emotion regulation', '1.5 mA', '20 min'],
        ['F4', 'DMN suppress rumination', 'DMN overactivation', 'Fz cathode / Pz cathode bilateral', 'Break worry loops', '2 mA', '20 min'],
        ['F5', 'Autonomic vagal', 'Autonomic imbalance', 'C3 anode / right shoulder', 'Parasympathetic upregulation', '2 mA', '20 min'],
        ['F6', 'Sleep-wake circuit', 'Sleep-anxiety overlap', 'F3 anode / Cz cathode', 'Hyperarousal reduction', '1.5 mA', '20 min'],
    ],
    'plato': [
        ['C1-PS', 'Focus & calm', 'Variant B', 'F3/F4', '1.4 mA', '20 min', 'Anxiety + attention'],
        ['C2-PS', 'Relaxation', 'Variant D', 'F3/Cz', '1.2 mA', '20 min', 'Baseline anxiety'],
        ['C3-PS', 'Mood stabilize', 'Variant A', 'F3/F4', '1.4 mA', '20 min', 'Comorbid mood'],
        ['C4-PS', 'Sleep prep', 'Variant G', 'Fp1/Cz', '1.2 mA', '20 min', 'Sleep-anxiety'],
        ['C5-PS', 'Social engagement', 'Variant C', 'F3/TP9', '1.4 mA', '20 min', 'Social anxiety'],
        ['C6-PS', 'Autonomic balance', 'Variant F', 'C3/C4', '1.4 mA', '20 min', 'HRV support'],
        ['C7-PS', 'Cognitive clarity', 'Variant B', 'F3/F4', '1.6 mA', '20 min', 'GAD with brain fog'],
        ['C8-PS', 'Comorbid pain-anxiety', 'Variant E', 'Cz/F3', '1.4 mA', '20 min', 'Somatic anxiety'],
    ],
    'fnon_plato': [
        ['FP1', 'CEN activation', 'CEN hypofunction', 'Variant B', 'F3/F4', '1.4 mA', '20 min'],
        ['FP2', 'SN calm', 'SN hyperactivation', 'Variant D', 'Cz/F3', '1.2 mA', '20 min'],
        ['FP3', 'Limbic regulation', 'LIMBIC hyperactivation', 'Variant F', 'Fp1/Cz', '1.2 mA', '20 min'],
        ['FP4', 'DMN quiet', 'DMN overactivation', 'Variant G', 'F3/Pz', '1.2 mA', '20 min'],
        ['FP5', 'Autonomic tone', 'Autonomic imbalance', 'Variant F', 'C3/C4', '1.4 mA', '20 min'],
        ['FP6', 'Social phenotype', 'SN + LIMBIC', 'Variant C', 'F3/TP9', '1.4 mA', '20 min'],
    ],
    'phenotypes': [
        {
            'code': 'P1', 'name': 'Generalized Anxiety (GAD)',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/F4', 'TPS DLPFC L', 'CBT worry log'],
            'card_left': ['Network: SN hyperactivation + CEN hypo', 'Key target: DLPFC L, vmPFC', 'Priority: SN suppress → CEN activate'],
            'card_right': ['TPS: T1 + FT1', 'tDCS: C1/F1', 'PlatoScience: C2-PS/FP2', 'taVNS: 30 min pre'],
            'brain_targets': [
                ['DLPFC L', 'CEN anchor', 'Activate', 'T1 / C1 / FP1', 'Evidence B'],
                ['vmPFC', 'Worry suppression', 'Modulate', 'T3 / F3', 'Emerging'],
                ['ACC', 'Rumination hub', 'Inhibit', 'T4 / C5', 'Emerging'],
                ['Amygdala', 'Fear signal', 'Downregulate', 'FT4 / F3', 'Emerging'],
                ['Insula', 'Interoception', 'Balance', 'FT6 / C6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS F3 anode', 'TPS DLPFC L', 'CBT worry log'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS vmPFC', 'Mindfulness 10 min'],
                ['taVNS 20 min', 'tDCS C1', 'TPS ACC', 'Breathing exercise'],
                ['taVNS 30 min', 'HDCstim F3/F4', 'TPS bilateral DLPFC', 'Anxiety diary'],
            ],
            'task_pairing': 'Cognitive reappraisal tasks, worry postponement diary, slow-paced breathing during stimulation.',
            'fnon_hypothesis': 'GAD reflects SN hyperactivation driving persistent threat detection with insufficient CEN top-down modulation. Targeting DLPFC restores prefrontal inhibitory control over amygdala-SN axis.',
        },
        {
            'code': 'P2', 'name': 'Panic Disorder',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1/Cz', 'TPS insula C3', 'Interoception task'],
            'card_left': ['Network: SN hyperactivation + autonomic dysregulation', 'Key target: Insula, vmPFC', 'Priority: Autonomic → interoception normalize'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C4/F3', 'PlatoScience: C6-PS/FP5', 'taVNS: 30 min'],
            'brain_targets': [
                ['Insula', 'Interoception alarm', 'Downregulate', 'T5 / C6 / FP5', 'Evidence B'],
                ['vmPFC', 'Safety signal', 'Upregulate', 'T3 / C4', 'Emerging'],
                ['ACC', 'Error monitoring', 'Modulate', 'T4 / C5', 'Emerging'],
                ['DLPFC L', 'Cognitive control', 'Activate', 'T1 / C1', 'Evidence B'],
                ['Locus coeruleus', 'NE arousal', 'Modulate (taVNS)', 'taVNS protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS Fp1 anode', 'TPS insula C3', 'Body scan exercise'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS vmPFC', 'Slow breathing 4-7-8'],
                ['taVNS 20 min', 'tDCS C4', 'TPS ACC', 'Panic diary'],
                ['CES 20 min', 'tDCS F3', 'TPS DLPFC L', 'Cognitive defusion'],
            ],
            'task_pairing': 'Interoception awareness tasks, diaphragmatic breathing, safety behavior reduction exposure.',
            'fnon_hypothesis': 'Panic disorder involves insula hyperactivation misinterpreting benign interoceptive signals as catastrophic. taVNS + insula TPS normalizes autonomic-interoceptive threshold.',
        },
        {
            'code': 'P3', 'name': 'Social Anxiety Disorder',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/TP9', 'TPS DLPFC + amygdala', 'Social exposure task'],
            'card_left': ['Network: SN + LIMBIC hyperactivation', 'Key target: DLPFC, amygdala, TPJ', 'Priority: Threat reappraisal → social engagement'],
            'card_right': ['TPS: T1 + FT8', 'tDCS: C8/F6', 'PlatoScience: C5-PS/FP6', 'taVNS: 20 min'],
            'brain_targets': [
                ['DLPFC L', 'Reappraisal', 'Activate', 'T1 / C1 / FP1', 'Evidence B'],
                ['Amygdala', 'Social threat', 'Inhibit', 'FT4 / temporal', 'Emerging'],
                ['TPJ', 'Mentalizing', 'Upregulate', 'TPS P3/T5', 'Emerging'],
                ['DMPFC', 'Self-referential', 'Modulate', 'FT8 / F3', 'Emerging'],
                ['STS', 'Social perception', 'Activate', 'TPS T5/T6', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C8', 'TPS DLPFC+amygdala', 'Social exposure hierarchy'],
                ['CES 20 min', 'PlatoScience Variant C', 'TPS TPJ', 'Perspective-taking task'],
                ['taVNS 30 min', 'tDCS F6', 'TPS temporal', 'Video social scenarios'],
                ['CES 20 min', 'tDCS F3/TP9', 'TPS DMPFC', 'Attention training'],
            ],
            'task_pairing': 'Graduated social exposure tasks, perspective-taking exercises, attention retraining away from social threat cues.',
            'fnon_hypothesis': 'Social anxiety reflects amygdala-SN hyperresponsiveness to social evaluation cues, with DLPFC failing to provide adequate top-down reappraisal. TPJ targeting enhances mentalizing.',
        },
        {
            'code': 'P4', 'name': 'Health Anxiety (Somatic)',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1/C3', 'TPS vmPFC+insula', 'Body neutrality task'],
            'card_left': ['Network: Insula hyperactivation + DMN rumination', 'Key target: vmPFC, insula, mPFC', 'Priority: Interoceptive reappraisal'],
            'card_right': ['TPS: T3 + FT3', 'tDCS: C4/F5', 'PlatoScience: C8-PS/FP4', 'taVNS: 30 min'],
            'brain_targets': [
                ['Insula', 'Body monitoring', 'Normalize', 'T5 / C6', 'Emerging'],
                ['vmPFC', 'Safety memory', 'Strengthen', 'T3 / F3', 'Emerging'],
                ['mPFC', 'Rumination', 'Reduce', 'FT3 / C5', 'Emerging'],
                ['ACC', 'Pain/health worry', 'Modulate', 'T4 / C5', 'Emerging'],
                ['DLPFC', 'Cognitive control', 'Activate', 'T1 / C1', 'Evidence B'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C4', 'TPS vmPFC', 'Body neutrality meditation'],
                ['CES 20 min', 'PlatoScience Variant G', 'TPS insula', 'Acceptance body scan'],
                ['taVNS 20 min', 'tDCS F3', 'TPS mPFC', 'Attention defusion'],
                ['CES 20 min', 'tDCS Fp1', 'TPS ACC', 'Health diary cognitive'],
            ],
            'task_pairing': 'Body-neutral attention tasks, acceptance-based interoception, health anxiety diary with cognitive defusion.',
            'fnon_hypothesis': 'Health anxiety involves insula hypervigilance to benign bodily signals amplified by mPFC rumination. vmPFC strengthening via TPS rebuilds safety signal pathways.',
        },
        {
            'code': 'P5', 'name': 'OCD-Spectrum Anxiety',
            'sozo_bar': ['taVNS 20 min', 'tDCS F3/Cz', 'TPS OFC+ACC', 'ERP task'],
            'card_left': ['Network: Cortico-striatal-thalamic hyperactivation', 'Key target: OFC, ACC, DLPFC', 'Priority: Habit loop disruption'],
            'card_right': ['TPS: T4 + FT2', 'tDCS: C5/F2', 'PlatoScience: C7-PS/FP2', 'taVNS: 20 min'],
            'brain_targets': [
                ['OFC', 'Threat appraisal', 'Inhibit', 'TPS Fp2', 'Emerging'],
                ['ACC', 'Error signal', 'Modulate', 'T4 / C5', 'Emerging'],
                ['DLPFC', 'Inhibitory control', 'Activate', 'T1 / C1', 'Evidence B'],
                ['Caudate', 'Habit circuit', 'Disrupt', 'TPS lateral F', 'Emerging'],
                ['Thalamus', 'Gating', 'Normalize', 'taVNS protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 20 min', 'tDCS C5', 'TPS OFC', 'ERP exposure exercise'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS ACC', 'Ritual prevention task'],
                ['taVNS 30 min', 'tDCS F2', 'TPS DLPFC', 'Cognitive defusion'],
                ['CES 20 min', 'tDCS Cz cathode', 'TPS caudate proxy', 'Acceptance task'],
            ],
            'task_pairing': 'ERP (Exposure Response Prevention) tasks, ritual delay practice, obsessive thought defusion exercises.',
            'fnon_hypothesis': 'OCD-spectrum anxiety reflects cortico-striatal hyperactivation creating compulsive loops. Disrupting OFC-ACC error signal via TPS reduces compulsive urge intensity.',
        },
        {
            'code': 'P6', 'name': 'PTSD-Comorbid Anxiety',
            'sozo_bar': ['taVNS 30 min', 'tDCS Fp1/F4', 'TPS vmPFC+amygdala', 'Trauma narrative task'],
            'card_left': ['Network: LIMBIC hyperactivation + CEN hypo', 'Key target: vmPFC, amygdala, DLPFC', 'Priority: Fear extinction + safety'],
            'card_right': ['TPS: T3 + FT4', 'tDCS: C4/F3', 'PlatoScience: C3-PS/FP3', 'taVNS: 30 min'],
            'brain_targets': [
                ['vmPFC', 'Extinction recall', 'Strengthen', 'T3 / C4', 'Evidence B'],
                ['Amygdala', 'Fear response', 'Downregulate', 'FT4 / temporal', 'Emerging'],
                ['Hippocampus', 'Context memory', 'Support', 'taVNS + TPS T6', 'Emerging'],
                ['DLPFC', 'Emotional regulation', 'Activate', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Conflict monitoring', 'Modulate', 'T4 / C5', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C4', 'TPS vmPFC', 'Trauma narrative CPT'],
                ['CES 20 min', 'PlatoScience Variant D', 'TPS amygdala', 'EMDR-adjacent task'],
                ['taVNS 30 min', 'tDCS F3', 'TPS DLPFC', 'Safety cue exposure'],
                ['CES 20 min', 'tDCS Fp1', 'TPS hippocampus proxy', 'Context discrimination'],
            ],
            'task_pairing': 'Trauma narrative reprocessing, safety signal learning, context discrimination tasks, grounding exercises.',
            'fnon_hypothesis': 'PTSD-comorbid anxiety reflects vmPFC failure to inhibit amygdala fear responses. vmPFC TPS during extinction tasks strengthens inhibitory pathways.',
        },
        {
            'code': 'P7', 'name': 'Autonomic/Cardiac Anxiety',
            'sozo_bar': ['taVNS 40 min', 'tDCS C3 insula', 'TPS insula', 'HRV biofeedback'],
            'card_left': ['Network: Autonomic dysregulation + insula hyperactivation', 'Key target: Insula, vagal-cardiac axis', 'Priority: HRV restoration'],
            'card_right': ['TPS: T5 + FT6', 'tDCS: C6/F5', 'PlatoScience: C6-PS/FP5', 'taVNS: 40 min'],
            'brain_targets': [
                ['Insula', 'Cardiac interoception', 'Normalize', 'T5 / C6', 'Emerging'],
                ['ACC', 'Autonomic control', 'Upregulate', 'T4 / C5', 'Emerging'],
                ['vmPFC', 'Cardiac safety signal', 'Strengthen', 'T3 / C4', 'Emerging'],
                ['Brainstem NTS', 'Vagal output', 'Stimulate (taVNS)', 'taVNS extended', 'Emerging'],
                ['Amygdala', 'Cardiovascular fear', 'Inhibit', 'FT4 / F3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'tDCS C6', 'TPS insula', 'HRV biofeedback 20 min'],
                ['CES 20 min', 'PlatoScience Variant F', 'TPS vmPFC', 'Cardiac coherence breathing'],
                ['taVNS 40 min', 'tDCS F5', 'TPS ACC', 'Heart-focused meditation'],
                ['CES 20 min', 'tDCS C3', 'TPS insula bilateral', 'Paced breathing 6 cpm'],
            ],
            'task_pairing': 'HRV biofeedback, cardiac coherence breathing (6 cpm), heart-focused meditation, safety signal conditioning.',
            'fnon_hypothesis': 'Cardiac anxiety involves insula hypervigilance to heartbeat variability with insufficient vagal tone. taVNS extended protocol directly targets vagal-cardiac axis.',
        },
        {
            'code': 'P8', 'name': 'Comorbid Anxiety-Insomnia',
            'sozo_bar': ['taVNS 30 min', 'tDCS F3/Cz', 'TPS DLPFC+ACC', 'Sleep hygiene protocol'],
            'card_left': ['Network: Hyperarousal + DMN activation at sleep onset', 'Key target: DLPFC, ACC, Cz', 'Priority: Nighttime hyperarousal reduction'],
            'card_right': ['TPS: T4 + FT7', 'tDCS: C7/F6', 'PlatoScience: C4-PS/FP4', 'taVNS: 30 min'],
            'brain_targets': [
                ['DLPFC', 'Sleep cognitive control', 'Balance', 'T1 / C1', 'Evidence B'],
                ['ACC', 'Nighttime rumination', 'Suppress', 'T4 / C5', 'Emerging'],
                ['mPFC', 'Worry before sleep', 'Downregulate', 'FT3 / C5', 'Emerging'],
                ['Thalamus', 'Sleep gating', 'Support (CES)', 'CES protocol', 'Emerging'],
                ['Hypothalamus', 'Circadian anchor', 'Normalize (CES)', 'CES protocol', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 30 min', 'tDCS C7', 'TPS DLPFC', 'Sleep restriction therapy'],
                ['CES 20 min', 'PlatoScience Variant G', 'TPS ACC', 'Progressive muscle relaxation'],
                ['taVNS 20 min', 'tDCS F6', 'TPS mPFC', 'Stimulus control protocol'],
                ['CES 20 min', 'tDCS Fz', 'TPS Cz', 'Cognitive shuffle technique'],
            ],
            'task_pairing': 'Sleep restriction therapy, stimulus control, cognitive shuffle for sleep onset, worry postponement journal.',
            'fnon_hypothesis': 'Anxiety-insomnia comorbidity reflects ACC-mPFC hyperarousal preventing sleep onset. Evening CES + tDCS session reduces cortical excitability for sleep initiation.',
        },
        {
            'code': 'P9', 'name': 'Treatment-Resistant Anxiety',
            'sozo_bar': ['taVNS 40 min', 'HDCstim F3/F4 bilateral', 'TPS multisite', 'Combined CBT task'],
            'card_left': ['Network: Multi-network dysregulation', 'Key target: Full SOZO sequence', 'Priority: Sequential multi-modal'],
            'card_right': ['TPS: FT9 multisite', 'tDCS: F1+F2 bilateral', 'PlatoScience: C7-PS/FP1', 'Full SOZO P1-P9'],
            'brain_targets': [
                ['DLPFC bilateral', 'Executive control', 'Activate bilateral', 'T1+T2 / C2 / FP1', 'Evidence B'],
                ['vmPFC', 'Extinction', 'Strengthen', 'T3 / F3', 'Emerging'],
                ['SN nodes', 'Threat processing', 'Downregulate', 'FT2 / F2', 'Emerging'],
                ['DMN', 'Rumination', 'Suppress', 'FT3 / F4', 'Emerging'],
                ['Limbic', 'Affect regulation', 'Normalize', 'FT4 / F3', 'Emerging'],
            ],
            'combinations': [
                ['taVNS 40 min', 'HDCstim F3/F4', 'TPS DLPFC+vmPFC', 'Combined CBT 45 min'],
                ['CES 20 min', 'PlatoScience Variant B', 'TPS SN suppress', 'ACT defusion session'],
                ['taVNS 30 min', 'tDCS F1', 'TPS bilateral DLPFC', 'Exposure hierarchy'],
                ['CES 20 min', 'HDCstim Cz cathode', 'TPS ACC+OFC', 'Mindfulness MBSR'],
            ],
            'task_pairing': 'Full combined CBT protocol, ACT defusion, exposure hierarchy with neuromodulation priming, MBSR integration.',
            'fnon_hypothesis': 'Treatment-resistant anxiety requires multi-network simultaneous targeting. SOZO full-sequence protocol addresses CEN hypo, SN hyper, DMN rumination, and LIMBIC dysregulation in coordinated sessions.',
        },
    ],
    'task_pairing_rows': [
        ['Worry postponement', 'During tDCS', 'CBT', 'All phenotypes'],
        ['Breathing (4-7-8)', 'During taVNS', 'Autonomic', 'P2, P7'],
        ['ERP exposure', 'Post-TPS', 'Behavioral', 'P5'],
        ['HRV biofeedback', 'During taVNS', 'Biofeedback', 'P7'],
        ['Sleep hygiene', 'Evening session', 'Behavioral', 'P8'],
        ['Social exposure', 'Post-TPS', 'Behavioral', 'P3'],
        ['Interoception awareness', 'During tDCS', 'Mindfulness', 'P2, P4'],
        ['Cognitive reappraisal', 'During tDCS', 'CBT', 'P1, P6'],
    ],
    'followup_rows': [
        ['Week 2', 'GAD-7, STAI', 'Anxiety scores', 'Adjust intensity if <20% reduction'],
        ['Week 4', 'GAD-7, STAI, PSQI', 'Anxiety + sleep', 'Add sleep protocol if needed'],
        ['Week 6', 'Full battery + HRV', 'Autonomic + mood', 'Phase 2 intensification'],
        ['Week 10', 'GAD-7, STAI, WSAS', 'Function + anxiety', 'Maintenance planning'],
        ['Month 4', 'Full reassessment', 'All domains', 'Maintenance protocol decision'],
        ['Month 6', 'GAD-7, QoL scale', 'Long-term outcome', 'Annual review schedule'],
    ],
    'plato_programs': _plato_programs_default('anxiety'),
}
'''

with open(data_file, 'a', encoding='utf-8') as f:
    f.write(chunk)

print(f"Appended anxiety to {data_file}")
