"""
Appends conditions 3-14 to partners_all_in_one_data.py
Run once: python scripts/_append_partners_data.py
"""
import sys
from pathlib import Path

data_file = Path(__file__).parent / "partners_all_in_one_data.py"

CONDITIONS_CODE = r'''

# ════════════════════════════════════════════════════════════════════════════════
# 3. ADHD
# ════════════════════════════════════════════════════════════════════════════════
PARTNERS_CONDITIONS["adhd"] = {
    "display_name": "Attention-Deficit/Hyperactivity Disorder (ADHD)",
    "short": "ADHD",
    "icd10": "F90",
    "tps_warning": (
        "TPS use in ADHD is INVESTIGATIONAL / OFF-LABEL. Evidence is preliminary. "
        "NEUROLITH® is CE-marked for musculoskeletal indications. Informed consent and "
        "Doctor supervision mandatory. Not approved as treatment for ADHD in any jurisdiction."
    ),
    "tps": [
        {"code": "T1", "symptom": "R-DLPFC — Attention & Vigilance",
         "targets": ["F4", "F8"], "evidence": "Emerging",
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * R-DLPFC",
         "rationale": "Right DLPFC is a key attention hub (DAN). Upregulation improves sustained attention and vigilance. Evidence: Breitling 2016, Westwood 2021 tDCS/ADHD meta-analysis framework."},
        {"code": "T2", "symptom": "L-DLPFC — Executive Function",
         "targets": ["F3", "F7"], "evidence": "Emerging",
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * L-DLPFC",
         "rationale": "Left DLPFC upregulation improves working memory and planning. Bilateral DLPFC approach addresses the executive dysfunction core of ADHD."},
        {"code": "T3", "symptom": "R-IFG — Inhibitory Control",
         "targets": ["F8", "F4"], "evidence": "Pilot",
         "params": "0.22 mJ/mm2 * 800 pulses * 5 Hz * R-IFG",
         "rationale": "Right inferior frontal gyrus (rIFG) is the primary motor inhibition node. ADHD features rIFG hypoactivation causing response inhibition failure. TPS directly targets rIFG via lateral frontal approach."},
        {"code": "T4", "symptom": "ACC — Conflict Monitoring & Impulse Control",
         "targets": ["Cz", "FCz"], "evidence": "Experimental",
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * midline ACC",
         "rationale": "ACC conflict monitoring is impaired in ADHD, contributing to poor impulse control and error monitoring. Midline TPS targets dACC to improve conflict detection and behavioural adjustment."},
        {"code": "T5", "symptom": "Striatal/Caudate — Reward Processing",
         "targets": ["F3", "F4", "Cz"], "evidence": "Experimental",
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * prefrontal-striatal",
         "rationale": "Frontostriatal circuit dysfunction underlies reward insensitivity and preference for immediate rewards in ADHD. Frontal TPS indirectly modulates striatal dopaminergic circuits via corticostriatal pathways."},
    ],
    "fnon_tps": [
        {"code": "FT1", "name": "Inattentive Network Protocol", "network": "ATTENTION + CEN",
         "phenotype": "P1 - Inattentive", "targets": ["F4", "F3", "Cz"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + ACC",
         "sozo_integration": "CES -> tDCS C1 (R-DLPFC) -> TPS FT1 -> sustained attention tasks",
         "rationale": "Inattentive ADHD reflects ATTENTION network (DAN) hypoactivation combined with CEN executive deficits. FT1 targets bilateral DLPFC and ACC to restore the attention-executive coupling."},
        {"code": "FT2", "name": "Hyperactive-Impulsive Protocol", "network": "CEN + SN",
         "phenotype": "P2 - Hyperactive-Impulsive", "targets": ["F4", "F8", "FCz"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * R-IFG + ACC",
         "sozo_integration": "taVNS -> tDCS C3 (R-IFG) -> TPS FT2 -> inhibition stop-signal task",
         "rationale": "Hyperactive-impulsive presentation features rIFG inhibitory failure and SN hyperreactivity. FT2 upregulates rIFG inhibitory circuits and ACC conflict monitoring to reduce impulsivity."},
        {"code": "FT3", "name": "Combined ADHD Protocol", "network": "CEN + ATTENTION",
         "phenotype": "P3 - Combined", "targets": ["F3", "F4", "Cz"],
         "params": "0.25 mJ/mm2 * 1,200 pulses * 5 Hz * bilateral DLPFC + ACC",
         "sozo_integration": "CES -> tDCS C2 bilateral -> TPS FT3 -> dual task (attention + inhibition)",
         "rationale": "Combined ADHD requires targeting both attention and inhibition networks simultaneously. Bilateral DLPFC + ACC approach provides the broadest coverage for combined presentation."},
        {"code": "FT4", "name": "Executive Dysfunction Protocol", "network": "CEN",
         "phenotype": "P4 - Executive Dysfunction", "targets": ["F3", "F4", "P3"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + PPC",
         "sozo_integration": "tDCS C4 WM -> TPS FT4 -> executive function tasks (planning, set-shifting)",
         "rationale": "Executive ADHD involves DLPFC-PPC CEN backbone dysfunction. FT4 targets the full CEN for working memory, planning, and cognitive flexibility deficits."},
        {"code": "FT5", "name": "Emotional Dysregulation Protocol", "network": "SN + LIMBIC",
         "phenotype": "P5 - Emotional Dysreg", "targets": ["F3", "F4", "T4"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + right temporal",
         "sozo_integration": "taVNS -> tDCS C6 emotional -> TPS FT5 -> emotion regulation tasks",
         "rationale": "Emotional dysregulation in ADHD involves SN-LIMBIC hyperreactivity. Right temporal approach modulates amygdala emotional reactivity while bilateral DLPFC upregulates top-down emotional control."},
        {"code": "FT6", "name": "SCT/Sluggish Cognitive Tempo Protocol", "network": "ATTENTION + CEN",
         "phenotype": "P6 - SCT", "targets": ["F3", "F4", "Oz"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC",
         "sozo_integration": "CES 200uA -> tDCS C1 bilateral -> TPS FT6 -> alertness tasks",
         "rationale": "SCT features excessive daydreaming and sluggishness distinct from inattentive ADHD. FT6 targets bilateral DLPFC for global arousal upregulation. CES pre-session addresses the low-arousal substrate."},
        {"code": "FT7", "name": "Working Memory Deficit Protocol", "network": "CEN",
         "phenotype": "P7 - Working Memory", "targets": ["F3", "F4", "P3", "P4"],
         "params": "0.22 mJ/mm2 * 1,200 pulses * 5 Hz * DLPFC + bilateral PPC",
         "sozo_integration": "tDCS C4 WM -> TPS FT7 -> N-back WM training",
         "rationale": "Working memory ADHD involves CEN backbone (DLPFC-PPC) hypoactivation. FT7 targets the full CEN circuit including bilateral PPC for visuospatial and verbal WM enhancement."},
        {"code": "FT8", "name": "Reward Processing Protocol", "network": "LIMBIC + CEN",
         "phenotype": "P8 - Reward Processing", "targets": ["Fp1", "Fp2", "F3"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * OFC + DLPFC",
         "sozo_integration": "CES -> tDCS C5 motivation -> TPS FT8 -> delayed reward tasks",
         "rationale": "Reward delay aversion in ADHD reflects OFC-DLPFC motivational circuit dysfunction. FT8 targets OFC (reward valuation) and DLPFC (goal-directed behaviour) to restore preference for delayed but larger rewards."},
        {"code": "FT9", "name": "Comorbid Anxiety-ADHD Protocol", "network": "CEN + SN",
         "phenotype": "P9 - Comorbid Anxiety", "targets": ["F3", "F4", "Fz"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC bilateral + vmPFC",
         "sozo_integration": "taVNS -> tDCS C1 -> TPS FT9 -> anxiety management + attention training",
         "rationale": "ADHD-anxiety comorbidity requires targeting both CEN (attention) and SN (anxiety) simultaneously. Bilateral DLPFC + vmPFC approach addresses executive deficits while modulating anxiety circuits."},
    ],
    "tdcs": [
        {"code": "C1", "symptom": "R-DLPFC — Sustained Attention",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params": "2 mA * 20 min | R-DLPFC (F4) anode, left supraorbital cathode",
         "rationale": "Right DLPFC is a key DAN hub for sustained attention. Anodal excitation improves vigilance and response speed. Evidence: Breitling 2016, Westwood 2021 systematic review."},
        {"code": "C2", "symptom": "Bilateral DLPFC — Combined ADHD",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | Bilateral DLPFC (F3+F4) anode, occipital cathode",
         "rationale": "Bilateral frontal upregulation for combined ADHD presentation. Addresses both attention and executive function deficits simultaneously."},
        {"code": "C3", "symptom": "R-IFG — Inhibitory Control",
         "anodes": ["F8"], "cathodes": ["Fp2"],
         "params": "2 mA * 20 min | R-IFG (F8 area) anode, right supraorbital cathode",
         "rationale": "Right IFG (F8 area) is the primary motor inhibition node in stop-signal tasks. Anodal stimulation reduces commission errors and improves stop-signal reaction time in ADHD."},
        {"code": "C4", "symptom": "Working Memory — DLPFC",
         "anodes": ["F3", "P3"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | F3+P3 anode, occipital cathode | Pair with N-back",
         "rationale": "Frontoparietal dual anode targets both DLPFC (executive) and PPC (visuospatial WM) nodes. Use-dependent plasticity when paired with N-back training during stimulation."},
        {"code": "C5", "symptom": "Motivation & Reward Delay Tolerance",
         "anodes": ["F3", "Cz"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | DLPFC + SMA dual anode",
         "rationale": "DLPFC+SMA dual anode for motivation and action initiation. Addresses delay aversion and motivational impersistence characteristic of ADHD reward processing deficit."},
        {"code": "C6", "symptom": "Emotional Regulation — Prefrontal",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "2 mA * 20 min | F3 anode, F4 cathode | Asymmetric emotional regulation",
         "rationale": "Asymmetric prefrontal montage for emotional dysregulation in ADHD. Left facilitation + right cathodal inhibition reduces emotional reactivity and frustration intolerance."},
        {"code": "C7", "symptom": "Processing Speed — Cz",
         "anodes": ["Cz"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | Vertex (Cz) anode, occipital cathode",
         "rationale": "Vertex stimulation targets SMA and ACC for faster response initiation. Improves processing speed and reduces reaction time variability — a key ADHD cognitive marker."},
        {"code": "C8", "symptom": "Cognitive Flexibility — Frontal",
         "anodes": ["F3"], "cathodes": ["Pz"],
         "params": "2 mA * 20 min | L-DLPFC anode, parietal cathode | Pair with WCST",
         "rationale": "F3-Pz montage for cognitive flexibility: DLPFC facilitation + parietal cathodal reduces DMN perseveration. Pair with Wisconsin Card Sort or similar set-shifting tasks."},
    ],
    "fnon_tdcs": [
        {"code": "F1", "name": "ATTENTION Upregulation", "network": "ATTENTION + CEN",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params": "2 mA * 20 min | R-DLPFC DAN upregulation",
         "rationale": "DAN upregulation via R-DLPFC for inattentive phenotype. Improves sustained attention and vigilance across all ADHD subtypes."},
        {"code": "F2", "name": "Inhibitory Control Network", "network": "CEN + SN",
         "anodes": ["F8"], "cathodes": ["Fp2"],
         "params": "2 mA * 20 min | R-IFG anode for inhibitory network",
         "rationale": "rIFG-based inhibitory control network facilitation. Primary FNON protocol for hyperactive-impulsive and combined presentations."},
        {"code": "F3", "name": "CEN Executive Circuit", "network": "CEN",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | Bilateral DLPFC for CEN upregulation",
         "rationale": "Bilateral CEN upregulation for executive ADHD. Addresses working memory, planning, and cognitive flexibility through bilateral frontal facilitation."},
        {"code": "F4", "name": "LIMBIC Reward Circuit", "network": "LIMBIC + CEN",
         "anodes": ["Fp1", "F3"], "cathodes": ["Oz"],
         "params": "1.5 mA * 20 min | OFC + DLPFC dual anode",
         "rationale": "OFC+DLPFC approach for reward processing deficit. Targets delay aversion and motivational impersistence via combined reward-executive circuit facilitation."},
        {"code": "F5", "name": "SN Emotional Regulation", "network": "SN + LIMBIC",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params": "2 mA * 20 min | Asymmetric prefrontal emotional regulation",
         "rationale": "Prefrontal asymmetry for emotional dysregulation in ADHD. Reduces frustration intolerance and emotional impulsivity through SN-LIMBIC recalibration."},
        {"code": "F6", "name": "DMN Suppression — Daydreaming", "network": "DMN + ATTENTION",
         "anodes": ["F3", "F4"], "cathodes": ["Pz"],
         "params": "2 mA * 20 min | Bilateral DLPFC, parietal cathode",
         "rationale": "DMN suppression for SCT/inattentive daydreaming. Bilateral DLPFC + parietal cathode reduces mind-wandering and improves task engagement."},
    ],
    "plato": [
        {"code": "C1-PS", "symptom": "R-DLPFC Attention", "variant": "Variant B (Fp2-F4)", "program": "Focus",
         "anodes": ["F4"], "cathodes": ["Fp2"], "params": "1.5 mA * 20 min | Variant B",
         "rationale": "Right prefrontal Focus program for sustained attention. Variant B targets R-DLPFC DAN hub."},
        {"code": "C2-PS", "symptom": "Bilateral Executive", "variant": "Variant C (F3-F4)", "program": "Focus",
         "anodes": ["F3"], "cathodes": ["F4"], "params": "1.5 mA * 20 min | Variant C",
         "rationale": "Bilateral executive control via Variant C for combined ADHD."},
        {"code": "C3-PS", "symptom": "Inhibitory Control", "variant": "Variant B (Fp2-F4)", "program": "Performance",
         "anodes": ["F4"], "cathodes": ["Fp2"], "params": "1.5 mA * 20 min | Variant B right frontal",
         "rationale": "Right frontal Performance program for inhibitory control. Pairs with stop-signal tasks."},
        {"code": "C4-PS", "symptom": "Working Memory", "variant": "Variant D (F3-P3)", "program": "Memory",
         "anodes": ["F3"], "cathodes": ["P3"], "params": "1.5 mA * 20 min | Variant D frontoparietal",
         "rationale": "Frontoparietal WM training via Variant D + Memory program. Combine with N-back during session."},
        {"code": "C5-PS", "symptom": "Motivation", "variant": "Variant A (Fp1-F3)", "program": "Performance",
         "anodes": ["F3"], "cathodes": ["Fp1"], "params": "1.5 mA * 20 min | Variant A",
         "rationale": "Left prefrontal motivation upregulation via Performance program."},
        {"code": "C6-PS", "symptom": "Emotional Regulation", "variant": "Variant C (F3-F4)", "program": "Calm",
         "anodes": ["F3"], "cathodes": ["F4"], "params": "1.5 mA * 20 min | Variant C",
         "rationale": "Asymmetric Calm program for emotional dysregulation and frustration tolerance."},
        {"code": "C7-PS", "symptom": "Processing Speed", "variant": "Variant E (C3-Cz)", "program": "Performance",
         "anodes": ["Cz"], "cathodes": ["C3"], "params": "1.5 mA * 20 min | Variant E",
         "rationale": "Vertex/SMA stimulation for processing speed improvement."},
        {"code": "C8-PS", "symptom": "Cognitive Flexibility", "variant": "Variant D (F3-P3)", "program": "Focus",
         "anodes": ["F3"], "cathodes": ["P3"], "params": "1.5 mA * 20 min | Variant D",
         "rationale": "Frontoparietal Focus program for set-shifting and cognitive flexibility."},
    ],
    "fnon_plato": [
        {"code": "FP1", "name": "ATTENTION Upregulation", "derived": "F1", "variant": "Variant B", "program": "Focus", "network": "ATTENTION + CEN", "params": "1.5 mA * 20 min", "rationale": "R-DLPFC Focus for home attention maintenance."},
        {"code": "FP2", "name": "Inhibitory Control", "derived": "F2", "variant": "Variant B", "program": "Performance", "network": "CEN + SN", "params": "1.5 mA * 20 min", "rationale": "Right frontal Performance for home inhibitory control training."},
        {"code": "FP3", "name": "CEN Executive", "derived": "F3", "variant": "Variant C", "program": "Focus", "network": "CEN", "params": "1.5 mA * 20 min", "rationale": "Bilateral Focus via Variant C for home executive maintenance."},
        {"code": "FP4", "name": "LIMBIC Reward", "derived": "F4", "variant": "Variant G", "program": "Performance", "network": "LIMBIC + CEN", "params": "1.5 mA * 20 min", "rationale": "Midline Variant G for OFC reward circuit home protocol."},
        {"code": "FP5", "name": "SN Emotional Reg", "derived": "F5", "variant": "Variant C", "program": "Calm", "network": "SN + LIMBIC", "params": "1.5 mA * 20 min", "rationale": "Asymmetric Calm for home emotional dysregulation management."},
        {"code": "FP6", "name": "DMN Suppression", "derived": "F6", "variant": "Variant D", "program": "Focus", "network": "DMN + ATTENTION", "params": "1.5 mA * 20 min", "rationale": "Frontoparietal Focus to suppress daydreaming at home."},
    ],
    "plato_programs": _plato_programs_default(
        "Sustained attention; inattentive ADHD; vigilance tasks",
        "Working memory training; N-back concurrent",
        "Motivation; reward delay; avolition in ADHD",
        "Emotional regulation; frustration tolerance",
        "Processing speed; alertness; morning ADHD activation",
        "Evening wind-down; insomnia comorbidity in ADHD",
        "Headache; tension comorbidity",
        "Cognitive performance; exam/task performance",
        "Post-task recovery; hyperactive fatigue",
    ),
    "phenotypes": [
        {
            "code": "P1", "ft_code": "FT1", "name": "Inattentive",
            "sozo_bar": {
                "S": "CES 200 uA * 15 min\nIncrease cortical arousal; reduce mind-wandering baseline",
                "O": "tDCS C1 (R-DLPFC) * 20 min\nDAN upregulation; sustained attention priming",
                "Z": "TPS FT1 * 1,000 pulses * 5 Hz\nBilateral DLPFC + ACC attention-executive reset",
                "O2": "Sustained attention tasks * 30 min\nContinuous performance tasks; attention training",
            },
            "card_left": "P1 - Inattentive\nFT1 Protocol\n\nModalities:\ntDCS C1\nTPS FT1\nCES\n\nTargets:\nATTENTION (DAN)\nCEN (DLPFC)\nACC monitoring",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + ACC\ntDCS: C1 - 2 mA * 20 min * F4 anode (R-DLPFC), Fp1 cathode\nCES: 200 uA * 15 min S-phase arousal activation\nSession: 5x/week x 3 weeks\nPrimary scale: CAARS-A * Conners CPT",
            "brain_targets": [
                ("R-DLPFC (F4)", "Primary DAN hub - sustained attention and vigilance; hypoactive in inattentive ADHD"),
                ("L-DLPFC (F3)", "Working memory and executive support; bilateral engagement for comprehensive attention support"),
                ("dACC (Cz/FCz)", "Conflict monitoring and sustained focus; ACC hypofunction allows mind-wandering in inattentive ADHD"),
                ("PPC / IPS (P3/P4)", "Dorsal attention network posterior nodes; visuospatial attention anchoring"),
                ("LC-NE (taVNS/CES target)", "Noradrenergic arousal system; CES upregulates LC-NE to increase cortical arousal and alertness"),
            ],
            "combinations": [
                ("tDCS C1 + CPT task (concurrent)", "R-DLPFC facilitation during attention task for use-dependent DAN plasticity", "tDCS 20 min during continuous performance test", "Inattentive ADHD; primary attentional deficit"),
                ("TPS FT1 + tDCS C1 (sequential)", "Deep attention-executive network reset after DAN priming", "tDCS 20 min -> TPS 20 min", "Moderate-severe inattentive ADHD"),
                ("CES + attention training (daily)", "CES arousal support during at-home attention training", "CES 15 min pre-training daily", "Home maintenance protocol for inattentive ADHD"),
                ("Full quad + neuropsychological rehab", "Complete cascade with structured attention rehabilitation", "90-min session 3x/week", "Severe inattentive ADHD with functional impairment"),
            ],
            "task_pairing": "Sustained attention tasks during O-outcome: continuous performance test (AX-CPT), 1-back task progressing to 2-back, timed reading tasks with comprehension checks, ADHD-specific attention training (e.g., QbTest). Duration 30 min. Progress monitoring weekly.",
            "fnon_hypothesis": "Inattentive ADHD reflects ATTENTION network (DAN: R-DLPFC, FEF, IPS) hypoactivation combined with DMN intrusion during task performance: mind-wandering occurs because DMN is not properly suppressed when DAN is engaged. TPS FT1 targets bilateral DLPFC and ACC to restore the DAN-DMN anticorrelation essential for sustained attention.",
        },
        {
            "code": "P2", "ft_code": "FT2", "name": "Hyperactive-Impulsive",
            "sozo_bar": {
                "S": "taVNS 0.5 mA * 15 min\nActivate vagal brake; reduce motor restlessness baseline",
                "O": "tDCS C3 (R-IFG) * 20 min\nInhibitory control priming; rIFG upregulation",
                "Z": "TPS FT2 * 1,000 pulses * 5 Hz\nR-IFG + ACC inhibitory network reset",
                "O2": "Stop-signal tasks * 30 min\nInhibitory control training; response inhibition practice",
            },
            "card_left": "P2 - Hyperactive-Impulsive\nFT2 Protocol\n\nModalities:\ntDCS C3\nTPS FT2\ntaVNS\n\nTargets:\nCEN (R-IFG)\nSN (ACC)\nMotor inhibition circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * R-IFG + ACC\ntDCS: C3 - 2 mA * 20 min * F8 anode (R-IFG), Fp2 cathode\ntaVNS: 0.5 mA * 15 min (motor restlessness reduction)\nSession: 5x/week x 3 weeks\nPrimary scale: CAARS-B (hyperactivity) * stop-signal task RT",
            "brain_targets": [
                ("R-IFG (F8 area)", "Primary motor inhibition node - critical for stop-signal performance; severely hypoactive in hyperactive-impulsive ADHD"),
                ("pre-SMA / SMA (FCz/Cz)", "Motor preparation and cancellation; SMA hyperactivity drives motor restlessness and fidgeting"),
                ("dACC (FCz)", "Response monitoring and conflict detection; impaired in impulsive ADHD leading to commission error blindness"),
                ("Caudate / striatum (frontal approach)", "BG inhibitory gating failure; frontostriatal dysfunction releases motor programs prematurely"),
                ("R-DLPFC (F4)", "Top-down inhibitory control support; DLPFC executive oversight of impulsive response tendencies"),
            ],
            "combinations": [
                ("tDCS C3 + stop-signal task (concurrent)", "rIFG facilitation during active inhibitory control task for use-dependent plasticity", "tDCS 20 min during stop-signal paradigm", "Hyperactive-impulsive ADHD"),
                ("TPS FT2 + tDCS C3 (sequential)", "Deep R-IFG + ACC inhibitory network reset", "tDCS 20 min -> TPS 20 min", "Moderate-severe hyperactivity and impulsivity"),
                ("taVNS + motor inhibition training", "Vagal tone improvement reduces motor restlessness", "taVNS 15 min pre + 30 min concurrent with tasks", "Motor hyperactivity with autonomic dysregulation"),
                ("Full quad + CBT impulse control", "Complete cascade with impulse management CBT in O-outcome", "90-min session", "Severe hyperactive-impulsive ADHD with conduct comorbidity"),
            ],
            "task_pairing": "Inhibitory control tasks during O-outcome: stop-signal paradigm (computerised), go/no-go task, response inhibition card game, red-light green-light motor control game, mindful movement (yoga, tai chi). Duration 30 min. Gamified format improves engagement.",
            "fnon_hypothesis": "Hyperactive-impulsive ADHD reflects rIFG hypoactivation and SMA hyperactivity: the motor inhibition node cannot suppress the premature motor release driven by overactive motor preparation circuits. TPS FT2 simultaneously upregulates rIFG (inhibitory control) and modulates SMA/ACC (conflict monitoring) to restore the STOP mechanism in the frontostriatal circuit.",
        },
        {
            "code": "P3", "ft_code": "FT3", "name": "Combined ADHD",
            "sozo_bar": {
                "S": "CES 200 uA * 15 min\nGlobal arousal; prepare combined attention + inhibition network",
                "O": "tDCS C2 (bilateral DLPFC) * 20 min\nComprehensive bilateral priming",
                "Z": "TPS FT3 * 1,200 pulses * 5 Hz\nBilateral DLPFC + ACC + R-IFG network reset",
                "O2": "Dual task (attention + inhibition) * 30 min\nCombined cognitive training",
            },
            "card_left": "P3 - Combined ADHD\nFT3 Protocol\n\nModalities:\ntDCS C2\nTPS FT3\nCES\n\nTargets:\nCEN + ATTENTION\nR-IFG inhibition\nACC monitoring",
            "card_right": "TPS: 0.25 mJ/mm2 * 1,200 pulses * 5 Hz * bilateral DLPFC + R-IFG + ACC\ntDCS: C2 - 2 mA * 20 min * bilateral F3+F4 anode, Oz cathode\nCES: 200 uA * 15 min S-phase\nSession: Daily x 10, then 3x/week\nPrimary scale: CAARS total * DIVA interview",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Combined executive and attention upregulation; addresses both inattentive and hyperactive-impulsive dimensions"),
                ("R-IFG (F8)", "Inhibitory control - critical for the hyperactive-impulsive component of combined ADHD"),
                ("dACC (Cz/FCz)", "Conflict monitoring bridge between attention and inhibition demands; essential for dual-task performance"),
                ("PPC bilateral (P3/P4)", "Posterior attention network nodes; visuospatial attention for inattentive dimension"),
                ("Striatum / BG (frontal approach)", "Frontostriatal loop governing both attention regulation and motor inhibition via dopaminergic gating"),
            ],
            "combinations": [
                ("tDCS C2 bilateral + dual task", "Bilateral priming during combined attention-inhibition task", "tDCS 20 min during dual task", "Combined ADHD - primary approach"),
                ("TPS FT3 + tDCS C2 (sequential)", "Comprehensive bilateral ADHD network reset", "tDCS 20 min -> TPS 25 min", "Moderate-severe combined ADHD"),
                ("CES daily + home training", "Daily CES for arousal maintenance with home cognitive training", "CES 15 min pre home tasks daily", "Maintenance protocol for combined ADHD"),
                ("Full quad + multimodal rehab", "Complete cascade with combined attention and inhibition training", "90-min session", "Severe combined ADHD with functional impairment"),
            ],
            "task_pairing": "Dual-task paradigms during O-outcome: combined CPT + stop-signal paradigm, task-switching protocols (colour/number WCST variant), computerised ADHD training programmes (e.g., Cogmed, CogniFit ADHD). Duration 30 min.",
            "fnon_hypothesis": "Combined ADHD involves simultaneous DAN hypoactivation (inattentive dimension) and rIFG inhibitory failure (hyperactive-impulsive dimension), both driven by global dopaminergic-noradrenergic prefrontal-striatal circuit dysfunction. TPS FT3 applies the broadest coverage approach to simultaneously address both dimensions.",
        },
        {
            "code": "P4", "ft_code": "FT4", "name": "Executive Dysfunction",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nFrontal noise reduction; prepare executive circuits",
                "O": "tDCS C4 (F3+P3 WM) * 20 min\nCEN backbone priming: DLPFC + PPC",
                "Z": "TPS FT4 * 1,000 pulses * 5 Hz\nFull CEN circuit reset: DLPFC + PPC + ACC",
                "O2": "Executive function tasks * 35 min\nPlanning, set-shifting, working memory training",
            },
            "card_left": "P4 - Executive Dysfunction\nFT4 Protocol\n\nModalities:\ntDCS C4\nTPS FT4\nCES\n\nTargets:\nCEN (DLPFC+PPC)\nACC planning\nWM circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + PPC\ntDCS: C4 - 2 mA * 20 min * F3+P3 anode, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: BRIEF-A (executive functions) * CANTAB",
            "brain_targets": [
                ("L-DLPFC (F3)", "Planning, working memory, goal-directed behaviour; primary executive hub"),
                ("PPC / superior parietal (P3)", "Spatial WM and task-set maintenance; critical for complex executive task performance"),
                ("dACC (FCz)", "Error monitoring and task-switching; dACC dysfunction causes perseveration and difficulty shifting sets"),
                ("Lateral PFC (F7)", "Verbal reasoning and language-based executive function; critical for verbal WM"),
                ("Hippocampus (temporal)", "Prospective memory and complex multi-step planning via PFC-hippocampal prospective memory circuit"),
            ],
            "combinations": [
                ("tDCS C4 + WCST (concurrent)", "CEN facilitation during executive task maximises use-dependent plasticity", "tDCS 20 min during Wisconsin Card Sort", "Executive ADHD; poor planning, set-shifting"),
                ("TPS FT4 + tDCS C4 (sequential)", "Full CEN circuit reset for executive dysfunction", "tDCS 20 min -> TPS 20 min", "Moderate-severe executive ADHD"),
                ("Neuropsychological rehab programme", "Structured executive function rehabilitation with NIBS augmentation", "NIBS + weekly neuropsych sessions", "Executive ADHD with occupational/academic impairment"),
                ("Full quad + metacognitive strategy training", "Complete cascade with metacognitive strategy instruction", "90-min session", "Executive ADHD in adults; workplace impairment"),
            ],
            "task_pairing": "Executive function tasks during O-outcome: Tower of London (planning), WCST (set-shifting), verbal fluency (category + letter switching), Trails B (task-switching), time management training. Duration 35 min. Neuropsychologist involvement recommended.",
            "fnon_hypothesis": "Executive ADHD involves CEN backbone (DLPFC-PPC) hypoactivation with particular ACC error-monitoring deficit, creating a pattern of poor planning, set rigidity, and metacognitive deficits. TPS FT4 targets the DLPFC-PPC CEN backbone to restore the executive processing capacity needed for complex, multi-step goal-directed behaviour.",
        },
        {
            "code": "P5", "ft_code": "FT5", "name": "Emotional Dysregulation",
            "sozo_bar": {
                "S": "taVNS 0.5 mA * 15 min\nVagal brake; reduce emotional reactivity baseline",
                "O": "tDCS C6 (F3 anode, F4 cathode) * 20 min\nPrefrontal emotional regulation priming",
                "Z": "TPS FT5 * 1,000 pulses * 5 Hz\nDLPFC + amygdala emotional dysregulation reset",
                "O2": "taVNS + emotion regulation tasks * 30 min\nDistress tolerance; frustration exposure",
            },
            "card_left": "P5 - Emotional Dysreg\nFT5 Protocol\n\nModalities:\ntDCS C6\nTPS FT5\ntaVNS\n\nTargets:\nSN (amygdala)\nCEN (DLPFC)\nLIMBIC circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + right temporal\ntDCS: C6 - 2 mA * 20 min * F3 anode, F4 cathode\ntaVNS: 0.5 mA * 15 min + 30 min\nPrimary scale: DERS (Difficulties in Emotion Regulation) * ERC",
            "brain_targets": [
                ("L-DLPFC (F3)", "Top-down emotional control; prefrontal regulation of amygdala frustration and anger responses"),
                ("R-DLPFC (F4) - cathodal", "Inhibit right prefrontal hyperreactivity driving emotional impulsivity and rejection sensitivity"),
                ("Amygdala (T3/T4)", "Emotional threat reactivity; amygdala hyperreactivity in ADHD emotional dysregulation"),
                ("ACC (Cz)", "Emotional conflict monitoring; ACC regulates the interference between emotional reactivity and goal-directed behavior"),
                ("insula (C3/C4)", "Somatic emotional experience; interoceptive awareness of frustration and emotional arousal"),
            ],
            "combinations": [
                ("taVNS + tDCS C6 (concurrent)", "Vagal + asymmetric prefrontal emotional regulation", "Simultaneous 20 min", "ADHD emotional dysregulation; frustration intolerance"),
                ("TPS FT5 + tDCS C6 (sequential)", "Amygdala-DLPFC emotional circuit reset", "tDCS 20 min -> TPS 20 min", "Moderate-severe emotional ADHD"),
                ("DBT-informed tasks + NIBS", "Dialectical behaviour therapy skills with NIBS augmentation", "tDCS during DBT skills practice", "ADHD with emotional dysregulation; borderline features"),
                ("Full quad + emotion regulation training", "Complete cascade with structured DBT/emotion regulation skills", "90-min session", "Severe ADHD emotional dysregulation"),
            ],
            "task_pairing": "Emotion regulation tasks during O-outcome: distress tolerance skills (TIPP: Temperature, Intense exercise, Paced breathing, Progressive relaxation), brief frustration exposure tasks, STOP skill (Stop, Take a step back, Observe, Proceed mindfully). Duration 30 min.",
            "fnon_hypothesis": "Emotional dysregulation in ADHD reflects DLPFC failure to inhibit amygdala hyperreactivity combined with SN hypersensitivity to social and task frustration. Unlike primary mood disorders, the emotional dysregulation is episodic, rapid-onset, and directly linked to immediate stimuli. TPS FT5 addresses both the DLPFC top-down control deficit and the amygdala hyperreactivity via temporal approach.",
        },
        {
            "code": "P6", "ft_code": "FT6", "name": "Sluggish Cognitive Tempo (SCT)",
            "sozo_bar": {
                "S": "CES 200 uA * 15 min\nArousal upregulation; reduce daydreaming baseline",
                "O": "tDCS C2 (bilateral DLPFC) * 20 min\nGlobal frontal arousal priming",
                "Z": "TPS FT6 * 1,000 pulses * 5 Hz\nBilateral DLPFC arousal upregulation",
                "O2": "Alertness tasks * 30 min\nVigilance training; engagement tasks",
            },
            "card_left": "P6 - SCT\nFT6 Protocol\n\nModalities:\ntDCS C2\nTPS FT6\nCES 200 uA\n\nTargets:\nATTENTION network\nCEN arousal\nDMN suppression",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC\ntDCS: C2 - 2 mA * 20 min * bilateral F3+F4 anode, Oz cathode\nCES: 200 uA * 15 min (high arousal CES)\nPrimary scale: BIS-SCT (SCT scale) * vigilance CPT",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Global arousal upregulation; addresses the low-activation substrate of SCT distinct from classic ADHD"),
                ("ACC (Cz)", "Task engagement monitoring; ACC hypofunction allows excessive mind-wandering in SCT"),
                ("PCC / precuneus (Pz)", "DMN hub - hyperactive in SCT daydreaming; bilateral DLPFC indirectly suppresses PCC via anticorrelation"),
                ("LC-NE (CES target)", "Noradrenergic arousal - CES upregulates LC to provide the tonic arousal missing in SCT"),
                ("Thalamus (indirect via Cz)", "Thalamocortical arousal regulation; reduced thalamic gating contributes to SCT low-activation state"),
            ],
            "combinations": [
                ("CES + tDCS C2 (concurrent)", "Dual arousal upregulation: CES global + tDCS bilateral frontal", "CES 15 min concurrent with tDCS 20 min", "SCT - primary low-arousal ADHD variant"),
                ("TPS FT6 + CES (daily)", "Bilateral arousal TPS + daily CES for SCT", "TPS 3x/week + CES daily", "Persistent SCT with daydreaming impairment"),
                ("Morning protocol: CES + tasks", "Daily morning CES before demanding cognitive tasks", "CES 15 min before school/work tasks", "SCT academic/occupational impairment"),
                ("Full quad arousal protocol", "Complete cascade with arousal optimisation", "90-min session", "Severe SCT with functional impairment"),
            ],
            "task_pairing": "Alertness and vigilance tasks during O-outcome: vigilance CPT (respond to rare target), alertness apps (Lumosity attention), brief physical movement (jumping jacks, brisk walking to increase arousal), environmental enrichment tasks. Duration 30 min. Morning sessions preferred.",
            "fnon_hypothesis": "SCT represents a distinct ADHD variant with global low-arousal state rather than hyperactivity: ATTENTION network (DAN) is globally underactivated and DMN is persistently dominant. TPS FT6 uses high-frequency bilateral stimulation to achieve global cortical arousal upregulation. CES provides the noradrenergic LC-NE support needed for the tonic arousal deficit.",
        },
        {
            "code": "P7", "ft_code": "FT7", "name": "Working Memory Deficit",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nCognitive noise reduction; prepare WM circuits",
                "O": "tDCS C4 (F3+P3) * 20 min\nDLPFC-PPC WM circuit priming",
                "Z": "TPS FT7 * 1,200 pulses * 5 Hz\nFull CEN WM network: DLPFC + bilateral PPC",
                "O2": "N-back WM training * 35 min\nAdaptive WM training concurrent with plasticity",
            },
            "card_left": "P7 - Working Memory\nFT7 Protocol\n\nModalities:\ntDCS C4\nTPS FT7\nCES\n\nTargets:\nCEN (DLPFC+bilateral PPC)\nWM circuit\nVerbal + visuospatial WM",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,200 pulses * 5 Hz * DLPFC + bilateral PPC\ntDCS: C4 - 2 mA * 20 min * F3+P3 anode, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: CANTAB SWM * Digit Span * N-back performance",
            "brain_targets": [
                ("L-DLPFC (F3)", "Verbal WM maintenance and manipulation; primary DLPFC working memory hub"),
                ("Superior parietal / PPC (P3)", "Visuospatial WM and phonological loop; posterior CEN working memory storage"),
                ("R-DLPFC (F4)", "Right DLPFC visuospatial WM; bilateral DLPFC for comprehensive WM coverage"),
                ("R-PPC (P4)", "Right parietal visuospatial WM; bilateral parietal targeting for full WM network"),
                ("ACC (Cz/FCz)", "WM gating and updating; ACC regulates which information enters and exits working memory"),
            ],
            "combinations": [
                ("tDCS C4 + N-back (concurrent)", "Frontoparietal facilitation during WM training - gold standard for ADHD WM improvement", "tDCS 20 min concurrent with adaptive N-back", "Working memory ADHD"),
                ("TPS FT7 + tDCS C4 (sequential)", "Full CEN WM network deep reset after priming", "tDCS 20 min -> TPS 20 min", "Severe WM deficit in ADHD"),
                ("Cogmed + NIBS (augmented programme)", "NIBS-augmented commercial WM training programme", "tDCS during Cogmed sessions", "WM ADHD; academic/occupational impairment"),
                ("Full quad + WM rehabilitation", "Complete cascade with structured WM rehabilitation", "90-min session", "Severe WM ADHD; ADHD + learning disability"),
            ],
            "task_pairing": "Working memory training during O-outcome: adaptive N-back (starting at 1-back, progressing to 2-3-back), Digit Span practice (forward and backward), visuospatial WM tasks (Corsi blocks), computerised WM training (Cogmed, Jungle Memory). Duration 35 min.",
            "fnon_hypothesis": "Working memory deficit in ADHD reflects CEN backbone (DLPFC-PPC) hypoactivation with reduced maintenance of information in prefrontal buffers. The deficit spans verbal WM (L-DLPFC/parietal) and visuospatial WM (R-DLPFC/R-parietal), requiring bilateral CEN targeting. TPS FT7 provides the most comprehensive bilateral CEN coverage with DLPFC + bilateral PPC approach.",
        },
        {
            "code": "P8", "ft_code": "FT8", "name": "Reward Processing Deficit",
            "sozo_bar": {
                "S": "CES 200 uA * 10 min\nBaseline arousal and reward sensitivity upregulation",
                "O": "tDCS C5 (F3+Cz motivation) * 20 min\nOFC + DLPFC reward circuit priming",
                "Z": "TPS FT8 * 1,000 pulses * 5 Hz\nOFC + DLPFC reward-motivation reset",
                "O2": "Reward-based tasks * 30 min\nDelayed gratification training; reward contingency tasks",
            },
            "card_left": "P8 - Reward Processing\nFT8 Protocol\n\nModalities:\ntDCS C5\nTPS FT8\nCES\n\nTargets:\nLIMBIC (OFC/NAc)\nCEN (DLPFC)\nReward-motivation circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * OFC + DLPFC\ntDCS: C5 - 2 mA * 20 min * F3+Cz anode, Oz cathode\nCES: 200 uA * 10 min\nPrimary scale: Delay Discounting task * BIS-11 (impulsivity)",
            "brain_targets": [
                ("OFC (Fp1/Fp2)", "Reward valuation and delay discounting; OFC hypofunction causes immediate-reward bias in ADHD"),
                ("DLPFC (F3)", "Goal-directed reward pursuit; DLPFC modulates delay tolerance and future-oriented decision-making"),
                ("Cz / SMA", "Action initiation for reward-directed behaviour; motivational persistence during delayed reward tasks"),
                ("Nucleus accumbens (indirect)", "Striatal reward prediction; frontostriatal OFC-NAc pathway governs reward learning"),
                ("Ventral tegmental area (indirect)", "Dopaminergic reward signal source; tDCS/TPS indirectly modulates VTA via prefrontal-striatal circuits"),
            ],
            "combinations": [
                ("tDCS C5 + reward tasks (concurrent)", "OFC+DLPFC facilitation during delay discounting training", "tDCS 20 min during reward training", "Reward processing ADHD; delay aversion"),
                ("TPS FT8 + tDCS C5 (sequential)", "OFC+DLPFC deep reward circuit reset", "tDCS 20 min -> TPS 20 min", "Moderate-severe reward deficit ADHD"),
                ("CES + gamified reward training", "CES arousal support during gamified reward conditioning tasks", "CES pre + gamified tasks concurrent", "ADHD with significant delay aversion"),
                ("Full quad + behavioural economics tasks", "Complete cascade with structured reward sensitivity training", "90-min session", "Severe reward deficit; addiction comorbidity risk"),
            ],
            "task_pairing": "Reward and delayed gratification tasks during O-outcome: delay discounting paradigm (choose between immediate small vs delayed large reward), token economy engagement, marshmallow test variants, monetary incentive delay task. Duration 30 min.",
            "fnon_hypothesis": "Reward processing deficit in ADHD reflects OFC-DLPFC-striatum circuit dysfunction causing preference for immediate over delayed rewards (delay aversion) and impaired reward learning. TPS FT8 targets the OFC (reward valuation node) via frontal pole approach combined with DLPFC for goal-directed reward pursuit restoration.",
        },
        {
            "code": "P9", "ft_code": "FT9", "name": "ADHD with Comorbid Anxiety",
            "sozo_bar": {
                "S": "taVNS 0.5 mA * 15 min\nReduce anxiety baseline; activate vagal brake",
                "O": "tDCS C1 (F4 anode, Fp1 cathode) * 20 min\nBalanced attention + anxiety modulation",
                "Z": "TPS FT9 * 1,000 pulses * 5 Hz\nDLPFC bilateral + vmPFC dual-target",
                "O2": "taVNS + integrated tasks * 30 min\nAnxiety management + attention training combined",
            },
            "card_left": "P9 - ADHD + Anxiety\nFT9 Protocol\n\nModalities:\ntDCS C1\nTPS FT9\ntaVNS\n\nTargets:\nCEN (DLPFC bilateral)\nSN (vmPFC)\nDual-disorder network",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + vmPFC\ntDCS: C1 - 2 mA * 20 min * F4 anode (R-DLPFC), Fp1 cathode\ntaVNS: 0.5 mA * 15 min + 30 min\nPrimary scale: CAARS + GAD-7 combined",
            "brain_targets": [
                ("R-DLPFC (F4)", "Attention upregulation (ADHD target) without excessive right activation that worsens anxiety"),
                ("vmPFC (Fz)", "Fear extinction and anxiety regulation; vmPFC facilitation addresses the anxiety comorbidity component"),
                ("L-DLPFC (F3)", "Executive control for both ADHD management strategies and anxiety reappraisal"),
                ("ACC (Cz)", "Dual role: conflict monitoring (ADHD) and worry generation (anxiety); balanced ACC modulation"),
                ("Amygdala (temporal)", "Anxiety fear circuit; hyperreactive amygdala in ADHD-anxiety comorbidity requires temporal TPS"),
            ],
            "combinations": [
                ("taVNS + tDCS C1 (concurrent)", "Vagal anxiety reduction + R-DLPFC attention upregulation", "Simultaneous 20 min", "ADHD-anxiety comorbidity"),
                ("TPS FT9 + tDCS C1 (sequential)", "Bilateral DLPFC + vmPFC dual-target network reset", "tDCS 20 min -> TPS 20 min", "Moderate ADHD + moderate anxiety"),
                ("Integrated CBT + NIBS", "CBT for ADHD and anxiety integrated with NIBS augmentation", "NIBS during integrated CBT session", "ADHD-anxiety; both clinically significant"),
                ("Full quad + unified protocol", "Complete cascade with transdiagnostic ADHD-anxiety treatment", "90-min session", "Severe ADHD-anxiety comorbidity"),
            ],
            "task_pairing": "Integrated ADHD-anxiety tasks during O-outcome: attention training concurrent with worry management (attention retraining + worry postponement), mindfulness-based attention training (MBAT), anxiety management strategies that don't worsen ADHD (avoid pure relaxation that increases mind-wandering). Duration 30 min.",
            "fnon_hypothesis": "ADHD-anxiety comorbidity involves paradoxical network interactions: ADHD drives CEN hypoactivation (attention failure) while anxiety drives SN hyperactivation, and the two conditions are maintained by partially overlapping but distinct network pathologies. TPS FT9 addresses both via DLPFC bilateral (ADHD attention) + vmPFC (anxiety extinction) dual targeting.",
        },
    ],
    "task_pairing_rows": [
        ("C1 R-DLPFC (F4 anode)", "Sustained attention", "Continuous performance test; vigilance tasks", "DAN upregulation during attention task - use-dependent DLPFC plasticity"),
        ("C3 R-IFG (F8 area)", "Inhibitory control", "Stop-signal task; go/no-go", "rIFG facilitation during active inhibitory control training"),
        ("C4 F3+P3 WM", "Working memory", "N-back (2-back); Corsi blocks", "CEN facilitation during WM training - standard ADHD WM protocol"),
        ("C6 emotional regulation", "Emotional dysregulation", "Distress tolerance skills; emotion exposure", "Asymmetric prefrontal during emotion regulation skills training"),
        ("C2 bilateral DLPFC", "Combined/executive", "Dual task; WCST set-shifting", "Bilateral priming for comprehensive ADHD executive training"),
        ("F1-F6 FNON", "Phenotype-specific ADHD targets", "FNON-matched tasks per phenotype", "Network-level ADHD plasticity via task-conditioned stimulation"),
    ],
    "followup_rows": [
        ("Phase 1 - Induction (Sessions 1-10)", "Daily or 5x/week", "CAARS, Conners CPT at baseline and session 10", "Confirm ADHD subtype; adjust protocol; add cognitive training if needed"),
        ("Phase 2 - Consolidation (Sessions 11-20)", "3-5x/week", "CAARS weekly; CANTAB mid-treatment", "Introduce FNON protocol; escalate to TPS if insufficient; add CBT"),
        ("Phase 3 - Maintenance (Month 2-3)", "2-3x/week", "CAARS biweekly; CPT monthly", "Begin PlatoScience home protocol; structured at-home training programme"),
        ("Phase 4 - Long-Term (Month 3+)", "Weekly booster", "Quarterly CAARS + CANTAB + functional assessment", "Maintenance; re-induce at academic transitions or life stressors"),
    ],
    "fnon_classification": [
        ("ATTENTION (DAN)", "Sustained attention deficit", "Inattention, mind-wandering, vigilance failure", "F1 - ATTENTION Upregulation (F4 anode R-DLPFC)"),
        ("CEN", "Executive control hypoactivation", "WM deficit, poor planning, set rigidity", "F3 - CEN Executive (bilateral DLPFC anode)"),
        ("SN", "Inhibitory failure + impulsivity", "Hyperactivity, impulsivity, response disinhibition", "F2 - Inhibitory Control (F8/R-IFG anode)"),
        ("LIMBIC", "Reward circuit dysfunction", "Delay aversion, reward insensitivity, motivational deficit", "F4 - LIMBIC Reward (OFC+DLPFC anode)"),
        ("DMN", "Inadequate suppression", "Mind-wandering, SCT, task disengagement", "F6 - DMN Suppression (bilateral DLPFC + Pz cathode)"),
        ("SMN", "Emotional-motor dysregulation", "Emotional impulsivity, physical restlessness, tics", "F5 - SN Emotional Regulation (F3 anode, F4 cathode)"),
    ],
    "fnon_montage_selection": [
        ("Inattentive dominant", "C1: F4 anode (R-DLPFC), Fp1 cathode (2 mA, 20 min)", "DAN ATTENTION upregulation"),
        ("Hyperactive-impulsive dominant", "C3: F8 anode (R-IFG), Fp2 cathode (2 mA, 20 min)", "CEN inhibitory control circuit"),
        ("Combined ADHD", "C2: bilateral F3+F4 anode, Oz cathode (2 mA, 20 min)", "CEN + ATTENTION bilateral"),
        ("Executive deficit", "C4: F3+P3 anode, Oz cathode (2 mA, 20 min)", "CEN backbone DLPFC-PPC"),
        ("SCT low-arousal", "C2: bilateral + CES 200 uA concurrent (2 mA, 20 min)", "Global arousal + bilateral CEN"),
        ("Emotional dysreg", "C6: F3 anode, F4 cathode (2 mA, 20 min) + taVNS", "SN + LIMBIC recalibration"),
    ],
}

# ════════════════════════════════════════════════════════════════════════════════
# 4. ALZHEIMER'S DISEASE / MCI
# ════════════════════════════════════════════════════════════════════════════════
PARTNERS_CONDITIONS["alzheimers"] = {
    "display_name": "Alzheimer's Disease / Mild Cognitive Impairment (MCI)",
    "short": "Alzheimer's",
    "icd10": "G30 / F06.7",
    "tps_warning": (
        "TPS use in Alzheimer's Disease and MCI is INVESTIGATIONAL / OFF-LABEL. "
        "Evidence is emerging from feasibility studies. Not approved as AD treatment. "
        "Patient and surrogate consent required. Doctor supervision mandatory at all times."
    ),
    "tps": [
        {"code": "T1", "symptom": "DLPFC - Cognitive Control & Memory Encoding",
         "targets": ["F3", "F4"], "evidence": "Emerging - Feasibility RCTs",
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC",
         "rationale": "DLPFC upregulation supports cognitive control and memory encoding networks. Evidence: Alcala-Lozano 2018, Benussi 2021 TPS-AD feasibility. Improves MMSE and ADAS-Cog in pilot studies."},
        {"code": "T2", "symptom": "PPC - Visuospatial & Attentional Processing",
         "targets": ["P3", "P4"], "evidence": "Emerging",
         "params": "0.22 mJ/mm2 * 800 pulses * 5 Hz * bilateral PPC",
         "rationale": "Posterior parietal cortex supports visuospatial processing and attentional control - impaired across AD subtypes. PPC TPS may enhance cortical connectivity in early AD."},
        {"code": "T3", "symptom": "Hippocampal Network - Episodic Memory",
         "targets": ["T3", "T4", "T5"], "evidence": "Experimental",
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * temporal approach",
         "rationale": "Temporal TPS targets hippocampal-entorhinal network for episodic memory. BDNF pathway stimulation may support neuroplasticity. Evidence: Koch 2018 parieto-frontal stimulation."},
        {"code": "T4", "symptom": "Lateral Temporal - Semantic & Language Memory",
         "targets": ["T5", "T6"], "evidence": "Experimental",
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * temporal cortex bilateral",
         "rationale": "Lateral temporal cortex is critical for semantic memory and language. Particularly relevant for logopenic and semantic variant presentations."},
        {"code": "T5", "symptom": "Precuneus - Default Mode Network Hub",
         "targets": ["Pz", "P3"], "evidence": "Experimental / Pilot",
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * parieto-occipital",
         "rationale": "Precuneus is a key DMN hub with early amyloid deposition in AD. TPS modulation may reduce pathological DMN hyperconnectivity and improve memory network function."},
    ],
    "fnon_tps": [
        {"code": "FT1", "name": "Amnestic MCI Protocol", "network": "CEN + LIMBIC",
         "phenotype": "P1 - Amnestic MCI", "targets": ["F3", "T3", "T4"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + temporal",
         "sozo_integration": "tDCS C1 (L-DLPFC) -> TPS FT1 -> episodic memory encoding tasks",
         "rationale": "Amnestic MCI involves hippocampal-DLPFC encoding network disruption. FT1 targets DLPFC (CEN executive encoding support) combined with temporal approach for hippocampal network priming."},
        {"code": "FT2", "name": "Multi-Domain MCI Protocol", "network": "CEN + ATTENTION",
         "phenotype": "P2 - Multi-Domain MCI", "targets": ["F3", "F4", "P3", "P4"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + PPC",
         "sozo_integration": "tDCS C4 (bilateral DLPFC) -> TPS FT2 -> multidomain cognitive training",
         "rationale": "Multi-domain MCI requires targeting CEN across frontal and parietal nodes. FT2 uses maximal bilateral DLPFC + PPC coverage for comprehensive cognitive network upregulation."},
        {"code": "FT3", "name": "Early-Onset AD Protocol", "network": "CEN + DMN",
         "phenotype": "P3 - Early-Onset AD", "targets": ["F3", "F4", "Pz"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC bilateral + precuneus",
         "sozo_integration": "tDCS C4 -> TPS FT3 -> cognitive rehabilitation programme",
         "rationale": "Early-onset AD has prominent frontal and posterior parietal involvement. FT3 targets both DLPFC (CEN) and precuneus (DMN hub) for combined network modulation."},
        {"code": "FT4", "name": "Late-Onset AD Maintenance Protocol", "network": "CEN + LIMBIC",
         "phenotype": "P4 - Late-Onset AD", "targets": ["F3", "F4", "T3"],
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * bilateral DLPFC + temporal",
         "sozo_integration": "tDCS C1 -> TPS FT4 -> ADL and orientation training",
         "rationale": "Late-onset AD maintenance protocol - lower intensity to accommodate age-related changes. DLPFC + temporal approach preserves remaining cognitive network function."},
        {"code": "FT5", "name": "Posterior Cortical Atrophy Protocol", "network": "SMN + ATTENTION",
         "phenotype": "P5 - PCA", "targets": ["P3", "P4", "O1", "O2"],
         "params": "0.20 mJ/mm2 * 800 pulses * 3 Hz * posterior cortex",
         "sozo_integration": "tDCS C6 (parietal) -> TPS FT5 -> visuospatial tasks",
         "rationale": "PCA involves occipitoparietal network atrophy. FT5 targets posterior cortex to preserve visuospatial and visual-constructive functions. Pair with visuospatial rehabilitation tasks."},
        {"code": "FT6", "name": "Logopenic Variant Protocol", "network": "CEN + ATTENTION",
         "phenotype": "P6 - Logopenic", "targets": ["T3", "P3", "F3"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * temporal-parietal + DLPFC",
         "sozo_integration": "tDCS C5 (language) -> TPS FT6 -> language therapy tasks",
         "rationale": "Logopenic variant involves left temporoparietal network degeneration. FT6 targets temporal-parietal junction (phonological loop) and DLPFC (sentence repetition) for language maintenance."},
        {"code": "FT7", "name": "Behavioral Variant Protocol", "network": "LIMBIC + CEN",
         "phenotype": "P7 - Behavioral Variant", "targets": ["F3", "F4", "Fp1", "Fp2"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + OFC",
         "sozo_integration": "tDCS C4 -> TPS FT7 -> behavioral management + caregiver support",
         "rationale": "Behavioral variant involves frontal-limbic circuit deterioration causing agitation, apathy, and disinhibition. FT7 targets OFC + DLPFC for behavioral symptom management."},
        {"code": "FT8", "name": "Mixed Dementia Protocol", "network": "CEN + SMN",
         "phenotype": "P8 - Mixed Dementia", "targets": ["F3", "F4", "Cz", "C3"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + M1/SMA",
         "sozo_integration": "tDCS C8 (ADL) -> TPS FT8 -> functional ADL training",
         "rationale": "Mixed dementia (AD + vascular) requires combined cognitive and motor network targeting. FT8 adds motor circuit (Cz/C3) to cognitive protocol for combined cognitive-motor rehabilitation."},
        {"code": "FT9", "name": "Apathy-Predominant Protocol", "network": "CEN + LIMBIC",
         "phenotype": "P9 - Apathy-Predominant", "targets": ["F3", "F4", "Cz"],
         "params": "0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + SMA",
         "sozo_integration": "tDCS C7 (executive) -> TPS FT9 -> motivational activation tasks",
         "rationale": "Apathy in AD reflects DLPFC-SMA motivation circuit degeneration. FT9 targets DLPFC (goal-directed behavior) and SMA (action initiation) to reduce apathy severity."},
    ],
    "tdcs": [
        {"code": "C1", "symptom": "L-DLPFC - Memory Encoding",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params": "2 mA * 25 min | L-DLPFC anode - episodic memory encoding support",
         "rationale": "L-DLPFC anodal tDCS supports verbal memory encoding. Multiple RCTs show benefit for MCI and early AD. Evidence: Ferrucci 2008, Boggio 2012, Cotelli 2014."},
        {"code": "C2", "symptom": "Temporal - Semantic Memory",
         "anodes": ["T3", "T4"], "cathodes": ["Fp1"],
         "params": "2 mA * 20 min | Bilateral temporal anode - semantic network",
         "rationale": "Bilateral temporal stimulation targets semantic memory networks and language circuits. Relevant for logopenic and semantic variant presentations."},
        {"code": "C3", "symptom": "Parietal - Visuospatial & Attention",
         "anodes": ["P3", "P4"], "cathodes": ["Fp1"],
         "params": "2 mA * 20 min | Bilateral parietal anode",
         "rationale": "Bilateral parietal upregulation for visuospatial processing and attentional networks. Key for PCA variant and attention-dominant MCI presentations."},
        {"code": "C4", "symptom": "Bilateral DLPFC - Global Cognitive Support",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params": "2 mA * 25 min | Bilateral DLPFC - comprehensive cognitive support",
         "rationale": "Bilateral DLPFC for multi-domain cognitive support. Addresses executive function, attention, and working memory simultaneously. Used for multi-domain MCI and combined presentations."},
        {"code": "C5", "symptom": "Language - Broca/Temporal",
         "anodes": ["T3", "F3"], "cathodes": ["Cz"],
         "params": "2 mA * 20 min | Left temporal + L-DLPFC for language",
         "rationale": "Combined temporal-frontal approach for language function preservation. Targets both Broca-like frontal language areas and temporal semantic storage for logopenic variant."},
        {"code": "C6", "symptom": "Visuospatial - Parieto-Occipital",
         "anodes": ["P3", "P4"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | Bilateral parietal anode - visuospatial processing",
         "rationale": "Parieto-occipital stimulation for visuospatial and visual-constructive function. Particularly important for posterior cortical atrophy."},
        {"code": "C7", "symptom": "Executive Function - Frontal",
         "anodes": ["F3"], "cathodes": ["Pz"],
         "params": "2 mA * 25 min | L-DLPFC anode, parietal cathode - CEN backbone",
         "rationale": "DLPFC-PPC montage for executive function and working memory. Supports daily living activities requiring planning and organisation."},
        {"code": "C8", "symptom": "ADL Function - Frontomotor",
         "anodes": ["F3", "Cz"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | DLPFC + SMA dual anode - functional motor-cognitive",
         "rationale": "Combined frontal-motor stimulation to support activities of daily living. DLPFC (planning) + SMA (motor initiation) for functional task performance. Pair with ADL training tasks."},
    ],
    "fnon_tdcs": [
        {"code": "F1", "name": "CEN Memory Encoding Network", "network": "CEN + LIMBIC",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params": "2 mA * 25 min | L-DLPFC memory encoding",
         "rationale": "CEN encoding network facilitation for amnestic MCI and early AD. Most evidence-based tDCS montage for AD cognitive symptoms."},
        {"code": "F2", "name": "Frontoparietal CEN Network", "network": "CEN",
         "anodes": ["F3", "P3"], "cathodes": ["Oz"],
         "params": "2 mA * 25 min | F3+P3 dual anode CEN backbone",
         "rationale": "Full CEN backbone for multi-domain MCI. Addresses both DLPFC executive and parietal working memory/attention nodes."},
        {"code": "F3", "name": "DMN Modulation - Precuneus", "network": "DMN + CEN",
         "anodes": ["F3", "F4"], "cathodes": ["Pz"],
         "params": "2 mA * 20 min | Bilateral DLPFC + parietal cathode for DMN",
         "rationale": "Bilateral DLPFC upregulation with parietal cathode disrupts pathological DMN-precuneus hyperconnectivity associated with amyloid deposition patterns."},
        {"code": "F4", "name": "Temporal Language Network", "network": "CEN + LIMBIC",
         "anodes": ["T3", "T4"], "cathodes": ["Fp1"],
         "params": "2 mA * 20 min | Bilateral temporal for semantic-language network",
         "rationale": "Temporal language network facilitation for logopenic variant and semantic memory preservation."},
        {"code": "F5", "name": "Limbic Memory Consolidation", "network": "LIMBIC + CEN",
         "anodes": ["T3"], "cathodes": ["Cz"],
         "params": "1.5 mA * 20 min | L-temporal anode for hippocampal network",
         "rationale": "Left temporal stimulation targets hippocampal-entorhinal memory consolidation network for episodic memory support."},
        {"code": "F6", "name": "Apathy-Motivation Circuit", "network": "CEN + LIMBIC",
         "anodes": ["F3", "Cz"], "cathodes": ["Oz"],
         "params": "2 mA * 20 min | DLPFC+SMA dual anode for apathy",
         "rationale": "Frontal-SMA dual activation for apathy reduction in AD. Addresses the motivational circuit degeneration causing functional impairment."},
    ],
    "plato": [
        {"code": "C1-PS", "symptom": "Memory Encoding", "variant": "Variant A (Fp1-F3)", "program": "Memory",
         "anodes": ["F3"], "cathodes": ["Fp1"], "params": "1.5 mA * 20 min | Variant A",
         "rationale": "L-DLPFC Memory program for episodic memory support at home. Pair with memory exercises."},
        {"code": "C2-PS", "symptom": "Temporal Semantic Memory", "variant": "Variant F (T3-Cz)", "program": "Memory",
         "anodes": ["T3"], "cathodes": ["Cz"], "params": "1.5 mA * 20 min | Variant F",
         "rationale": "Temporal Memory program for semantic network support."},
        {"code": "C3-PS", "symptom": "Parietal Attention", "variant": "Variant D (F3-P3)", "program": "Focus",
         "anodes": ["F3"], "cathodes": ["P3"], "params": "1.5 mA * 20 min | Variant D",
         "rationale": "Frontoparietal Focus for attention and visuospatial support."},
        {"code": "C4-PS", "symptom": "Bilateral Cognitive Support", "variant": "Variant C (F3-F4)", "program": "Memory",
         "anodes": ["F3"], "cathodes": ["F4"], "params": "1.5 mA * 20 min | Variant C",
         "rationale": "Bilateral cognitive support via Memory program."},
        {"code": "C5-PS", "symptom": "Language Support", "variant": "Variant F (T3-Cz)", "program": "Focus",
         "anodes": ["T3"], "cathodes": ["Cz"], "params": "1.5 mA * 20 min | Variant F",
         "rationale": "Temporal Focus for language function maintenance."},
        {"code": "C6-PS", "symptom": "Visuospatial", "variant": "Variant D (F3-P3)", "program": "Performance",
         "anodes": ["P3"], "cathodes": ["F3"], "params": "1.5 mA * 20 min | Variant D posterior",
         "rationale": "Posterior parietal Performance for visuospatial support."},
        {"code": "C7-PS", "symptom": "Executive Function", "variant": "Variant D (F3-P3)", "program": "Focus",
         "anodes": ["F3"], "cathodes": ["P3"], "params": "1.5 mA * 20 min | Variant D",
         "rationale": "Frontoparietal Focus for executive and working memory support."},
        {"code": "C8-PS", "symptom": "ADL Function", "variant": "Variant E (C3-Cz)", "program": "Performance",
         "anodes": ["Cz"], "cathodes": ["C3"], "params": "1.5 mA * 20 min | Variant E",
         "rationale": "Motor-cognitive Performance via Variant E for ADL function."},
    ],
    "fnon_plato": [
        {"code": "FP1", "name": "CEN Memory Network", "derived": "F1", "variant": "Variant A", "program": "Memory", "network": "CEN + LIMBIC", "params": "1.5 mA * 20 min", "rationale": "Home L-DLPFC Memory for episodic memory maintenance."},
        {"code": "FP2", "name": "Frontoparietal CEN", "derived": "F2", "variant": "Variant D", "program": "Focus", "network": "CEN", "params": "1.5 mA * 20 min", "rationale": "Home frontoparietal Focus for multi-domain support."},
        {"code": "FP3", "name": "DMN Modulation", "derived": "F3", "variant": "Variant C", "program": "Memory", "network": "DMN + CEN", "params": "1.5 mA * 20 min", "rationale": "Bilateral home Memory for DMN-CEN balance."},
        {"code": "FP4", "name": "Temporal Language", "derived": "F4", "variant": "Variant F", "program": "Memory", "network": "CEN + LIMBIC", "params": "1.5 mA * 20 min", "rationale": "Home temporal Memory for language network."},
        {"code": "FP5", "name": "Hippocampal Memory", "derived": "F5", "variant": "Variant F", "program": "Memory", "network": "LIMBIC + CEN", "params": "1.5 mA * 20 min", "rationale": "Home temporal Memory for hippocampal support."},
        {"code": "FP6", "name": "Apathy-Motivation", "derived": "F6", "variant": "Variant E", "program": "Performance", "network": "CEN + LIMBIC", "params": "1.5 mA * 20 min", "rationale": "Home motor-cognitive Performance for apathy."},
    ],
    "plato_programs": _plato_programs_default(
        "Executive function support; working memory in MCI",
        "Episodic and semantic memory; encoding training",
        "Apathy reduction; motivation in AD",
        "Agitation and anxiety in behavioral AD",
        "Fatigue in caregivers and early AD patients",
        "Sleep disturbance in AD; sundowning prevention",
        "Pain comorbidity in advanced AD",
        "Cognitive performance; ADL preparation",
        "Post-session recovery; fatigue management",
    ),
    "phenotypes": [
        {
            "code": "P1", "ft_code": "FT1", "name": "Amnestic MCI",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nNoise reduction; prepare encoding circuits",
                "O": "tDCS C1 (L-DLPFC) * 25 min\nMemory encoding network priming",
                "Z": "TPS FT1 * 1,000 pulses * 5 Hz\nDLPFC + hippocampal temporal network reset",
                "O2": "Memory encoding tasks * 30 min\nList learning; visual-verbal association tasks",
            },
            "card_left": "P1 - Amnestic MCI\nFT1 Protocol\n\nModalities:\ntDCS C1\nTPS FT1\nCES\n\nTargets:\nCEN (L-DLPFC)\nLIMBIC (hippocampus)\nEncoding network",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + temporal\ntDCS: C1 - 2 mA * 25 min * F3 anode, Fp2 cathode\nCES: 100 uA * 15 min\nPrimary scale: RAVLT * MMSE * MoCA",
            "brain_targets": [
                ("L-DLPFC (F3)", "Memory encoding executive control; DLPFC supports encoding strategy and top-down hippocampal gating"),
                ("Hippocampus (temporal T3/T5)", "Episodic memory encoding site; primary pathology in amnestic MCI; TPS temporal approach"),
                ("Entorhinal cortex (T3/T4)", "Hippocampal gatekeeper; earliest site of tau pathology in AD; temporal TPS indirect modulation"),
                ("PPC (P3)", "Visual-spatial encoding; parietal memory network node; visual-verbal memory binding"),
                ("Precuneus (Pz)", "DMN hub - episodic memory and self-referential processing; early amyloid deposition in MCI"),
            ],
            "combinations": [
                ("tDCS C1 + memory encoding tasks (concurrent)", "L-DLPFC facilitation during active encoding - use-dependent plasticity for memory", "tDCS 25 min during word-list or visual paired-associate learning", "Amnestic MCI - primary episodic memory deficit"),
                ("TPS FT1 + tDCS C1 (sequential)", "Deep temporal-DLPFC network reset after encoding priming", "tDCS 25 min -> TPS 20 min", "Moderate amnestic MCI; progressing to AD"),
                ("taVNS + memory training daily", "Vagal-BDNF pathway support for hippocampal neuroplasticity", "taVNS 20 min concurrent with memory tasks", "Amnestic MCI with inflammatory markers or metabolic risk"),
                ("Full quad + memory rehabilitation", "Complete cascade with structured memory rehabilitation programme", "90-min session", "Amnestic MCI progressing toward AD conversion"),
            ],
            "task_pairing": "Memory encoding tasks during O-outcome: word-list learning (RAVLT administration), visual-verbal paired-associate learning, face-name association tasks, spaced retrieval practice, errorless learning techniques. Duration 30 min. Neuropsychologist involvement recommended.",
            "fnon_hypothesis": "Amnestic MCI reflects hippocampal-entorhinal encoding failure combined with DLPFC-hippocampal connectivity reduction. The CEN (DLPFC) can no longer provide effective executive support for encoding strategy, and the LIMBIC network (hippocampus) has reduced neuroplastic capacity. TPS FT1 targets this combined CEN-LIMBIC encoding circuit.",
        },
        {
            "code": "P2", "ft_code": "FT2", "name": "Multi-Domain MCI",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nGlobal cognitive noise reduction",
                "O": "tDCS C4 (bilateral DLPFC) * 25 min\nComprehensive bilateral cognitive priming",
                "Z": "TPS FT2 * 1,000 pulses * 5 Hz\nBilateral DLPFC + PPC full CEN reset",
                "O2": "Multi-domain cognitive training * 30 min\nMulti-domain cognitive rehabilitation",
            },
            "card_left": "P2 - Multi-Domain MCI\nFT2 Protocol\n\nModalities:\ntDCS C4\nTPS FT2\nCES\n\nTargets:\nCEN bilateral\nATTENTION + WM\nPPC visuospatial",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + bilateral PPC\ntDCS: C4 - 2 mA * 25 min * F3+F4 bilateral, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: MoCA * ADAS-Cog * neuropsychological battery",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Comprehensive executive and memory encoding support across multiple cognitive domains"),
                ("Bilateral PPC (P3+P4)", "Visuospatial, attentional, and posterior memory network nodes"),
                ("Temporal bilateral (T3/T4)", "Semantic and episodic memory; language networks"),
                ("ACC (Cz)", "Cognitive control and task-monitoring; multiple domain coordination"),
                ("Precuneus (Pz)", "Central DMN-memory hub; multi-domain memory integration"),
            ],
            "combinations": [
                ("tDCS C4 bilateral + multidomain training", "Bilateral cognitive facilitation during multi-domain tasks", "tDCS 25 min during multidomain programme", "Multi-domain MCI"),
                ("TPS FT2 + tDCS C4 (sequential)", "Full bilateral CEN reset for multi-domain MCI", "tDCS 25 min -> TPS 25 min", "Moderate multi-domain MCI; high conversion risk"),
                ("Comprehensive cognitive rehab + NIBS", "Structured multi-domain cognitive rehabilitation with NIBS augmentation", "NIBS 3x/week + weekly neuro rehab", "Multi-domain MCI with functional impairment"),
                ("Full quad + comprehensive programme", "Complete cascade with multi-domain rehabilitation", "90-min session", "Multi-domain MCI approaching mild dementia threshold"),
            ],
            "task_pairing": "Multi-domain cognitive tasks during O-outcome: memory (word list), executive (verbal fluency, Trails B), language (naming), visuospatial (clock drawing, figure copying), processing speed (digit symbol). Duration 30 min. Use standardised test battery with practice forms.",
            "fnon_hypothesis": "Multi-domain MCI reflects diffuse CEN network degradation extending beyond the hippocampal memory system to include frontal executive, parietal attentional, and temporal language networks. TPS FT2 applies the most comprehensive bilateral coverage to preserve function across multiple vulnerable networks simultaneously.",
        },
        {
            "code": "P3", "ft_code": "FT3", "name": "Early-Onset AD",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nNeuroplasticity support; reduce cortical noise",
                "O": "tDCS C4 (bilateral DLPFC) * 25 min\nCognitive preservation priming",
                "Z": "TPS FT3 * 1,000 pulses * 5 Hz\nBilateral DLPFC + precuneus network reset",
                "O2": "Cognitive rehabilitation * 35 min\nError-based and errorless learning combined",
            },
            "card_left": "P3 - Early-Onset AD\nFT3 Protocol\n\nModalities:\ntDCS C4\nTPS FT3\nCES\n\nTargets:\nCEN + DMN\nBilateral DLPFC\nPrecuneus",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + precuneus\ntDCS: C4 - 2 mA * 25 min * bilateral F3+F4, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: MMSE * CDR * ADAS-Cog",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Cognitive reserve support; bilateral engagement addresses the broader frontal involvement in early-onset AD"),
                ("Precuneus (Pz)", "Early amyloid accumulation site; DMN hub - precuneus modulation targets the AD pathology network"),
                ("Temporal bilateral", "Hippocampal and semantic memory preservation in early-onset AD"),
                ("Frontal associative cortex", "Early-onset AD has prominent frontal involvement versus typical late-onset; bilateral frontal targeting essential"),
                ("Parietal cortex (P3/P4)", "Posterior parietal atrophy prominent in early-onset AD; visuospatial and attention preservation"),
            ],
            "combinations": [
                ("tDCS C4 + errorless learning", "Bilateral DLPFC facilitation during errorless learning maximises encoding without error reinforcement", "tDCS 25 min during errorless learning programme", "Early-onset AD; preserved insight"),
                ("TPS FT3 + cognitive rehabilitation", "Broad network reset to support rehabilitation programme", "TPS 3x/week + weekly cognitive rehabilitation sessions", "Early-onset AD; functional preservation priority"),
                ("taVNS + BDNF support protocol", "Vagal BDNF pathway activation for neuroprotection", "taVNS 20 min daily during tasks", "Early-onset AD with preserved insight; maximise neuroprotection window"),
                ("Full quad + caregiver training", "Complete cascade with caregiver cognitive rehabilitation support", "90-min session", "Early-onset AD with caregiver involvement"),
            ],
            "task_pairing": "Cognitive rehabilitation tasks during O-outcome: errorless learning (vanishing cues for name-face, medication schedule), spaced retrieval, prospective memory training, orientation training, daily routine practice. Duration 35 min. Carer involvement essential.",
            "fnon_hypothesis": "Early-onset AD has more aggressive frontal and posterior parietal involvement than late-onset, with early precuneus amyloid deposition disrupting the DMN-CEN anticorrelation. TPS FT3 targets both CEN (DLPFC bilateral) and DMN hub (precuneus) to slow the network disconnection characterising early-onset AD.",
        },
        {
            "code": "P4", "ft_code": "FT4", "name": "Late-Onset AD",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nGentle arousal; adapt for age-related cortical changes",
                "O": "tDCS C1 (L-DLPFC) * 20 min\nMemory encoding support (lower intensity)",
                "Z": "TPS FT4 * 800 pulses * 3 Hz\nGentle DLPFC + temporal maintenance protocol",
                "O2": "ADL and orientation tasks * 30 min\nOrientate; daily routine; procedural memory",
            },
            "card_left": "P4 - Late-Onset AD\nFT4 Protocol\n\nModalities:\ntDCS C1\nTPS FT4\nCES\n\nTargets:\nCEN maintenance\nHippocampal circuit\nADL function",
            "card_right": "TPS: 0.20 mJ/mm2 * 800 pulses * 3 Hz * bilateral DLPFC + temporal (gentle)\ntDCS: C1 - 1.5 mA * 20 min * F3 anode, Fp2 cathode (lower intensity)\nCES: 100 uA * 15 min\nPrimary scale: MMSE * CDR * Barthel ADL Index",
            "brain_targets": [
                ("L-DLPFC (F3)", "Residual cognitive reserve; gentle facilitation to preserve remaining encoding capacity"),
                ("Hippocampal network (temporal)", "Preserve remaining episodic memory capacity; slow progression of temporal atrophy"),
                ("Parietal (P3/P4)", "Attentional support; visuospatial navigation; spatial orientation for ADL function"),
                ("OFC/frontal (Fp1)", "Social and emotional cognition preservation; personalisation and carers recognition"),
                ("Primary sensorimotor (Cz)", "Motor-cognitive integration for ADL performance; preserved procedural memory support"),
            ],
            "combinations": [
                ("tDCS C1 + orientation tasks", "DLPFC facilitation during orientation and daily routine practice", "tDCS 20 min during ADL orientation programme", "Late-onset AD - functional preservation focus"),
                ("TPS FT4 (gentle protocol) + reminiscence", "Low-intensity network maintenance + reminiscence therapy", "TPS 2x/week + weekly reminiscence sessions", "Moderate late-onset AD"),
                ("CES + structured routine", "Daily CES for arousal support during structured daily routine", "CES 15 min morning daily", "Late-onset AD with apathy and daytime somnolence"),
                ("Full quad + person-centred care", "Complete cascade with person-centred activities", "90-min session", "Late-onset AD with moderate functional impairment"),
            ],
            "task_pairing": "ADL and orientation tasks during O-outcome: orientation to time/place/person, procedural memory tasks (grooming sequence, familiar recipe), reminiscence therapy (meaningful photographs, music), errorless ADL practice (dressing, eating). Duration 30 min. Carer-assisted preferred.",
            "fnon_hypothesis": "Late-onset AD involves progressive CEN degradation beginning with hippocampal-entorhinal LIMBIC failure and extending to DLPFC. The preserved procedural (SMN) and habitual (BG) memory systems provide the therapeutic window. TPS FT4 uses gentle, low-frequency parameters appropriate for age-related changes in cortical excitability.",
        },
        {
            "code": "P5", "ft_code": "FT5", "name": "Posterior Cortical Atrophy (PCA)",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nPosterior cortical activation support",
                "O": "tDCS C6 (parietal bilateral) * 20 min\nVisuospatial network priming",
                "Z": "TPS FT5 * 800 pulses * 3 Hz\nPosterior cortex - parieto-occipital network",
                "O2": "Visuospatial rehabilitation * 30 min\nVisual scanning, constructional tasks",
            },
            "card_left": "P5 - PCA\nFT5 Protocol\n\nModalities:\ntDCS C6\nTPS FT5\nCES\n\nTargets:\nSMN (parieto-occipital)\nATTENTION (parietal)\nVisuospatial network",
            "card_right": "TPS: 0.20 mJ/mm2 * 800 pulses * 3 Hz * posterior cortex P3/P4/O1\ntDCS: C6 - 2 mA * 20 min * bilateral P3+P4 anode, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: VOSP * Rey Figure * clock drawing",
            "brain_targets": [
                ("Bilateral PPC (P3/P4)", "Primary PCA pathology site; visuospatial processing and visual attention"),
                ("Occipital cortex (O1/O2)", "Visual processing; posterior TPS targets occipital-parietal integration"),
                ("Superior parietal (P3/P4)", "Spatial attention and visual-motor integration; Balint syndrome components"),
                ("Temporal-parietal junction (T5/T6)", "Visual-object recognition; visual agnosia component of PCA"),
                ("Frontal eye fields (F8/F7)", "Oculomotor control; visual scanning; FEF-parietal attention network"),
            ],
            "combinations": [
                ("tDCS C6 + visuospatial tasks (concurrent)", "Parietal facilitation during visuospatial rehabilitation", "tDCS 20 min during visual scanning/construction tasks", "PCA - primary visuospatial deficit"),
                ("TPS FT5 + occupational therapy", "Posterior cortex network reset supporting OT visuospatial rehabilitation", "TPS 3x/week + OT sessions", "PCA with functional impairment"),
                ("Environmental adaptation + NIBS", "NIBS supports visual compensation strategy training", "tDCS during compensatory visual strategy training", "PCA with ADL impairment"),
                ("Full quad + vision rehabilitation", "Complete cascade with specialist vision rehabilitation", "90-min session", "Severe PCA with Balint syndrome components"),
            ],
            "task_pairing": "Visuospatial rehabilitation tasks during O-outcome: visual scanning exercises (cancellation tasks), block construction (simple to complex), clock drawing practice, face recognition, visual search training, environmental navigation tasks. Duration 30 min. OT/vision specialist involvement.",
            "fnon_hypothesis": "Posterior Cortical Atrophy involves progressive atrophy of the parieto-occipital network (SMN and ATTENTION posterior nodes) while frontal/hippocampal regions are relatively preserved. TPS FT5 targets the posterior cortex where maximum functional preservation benefit can be achieved, supporting the residual visual-attentional network capacity.",
        },
        {
            "code": "P6", "ft_code": "FT6", "name": "Logopenic Variant",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nLanguage network noise reduction",
                "O": "tDCS C5 (left temporal + DLPFC) * 20 min\nLanguage network priming",
                "Z": "TPS FT6 * 1,000 pulses * 5 Hz\nTemporal-parietal + DLPFC language reset",
                "O2": "Language therapy tasks * 35 min\nPhonological loop; sentence repetition",
            },
            "card_left": "P6 - Logopenic\nFT6 Protocol\n\nModalities:\ntDCS C5\nTPS FT6\nCES\n\nTargets:\nCEN (temporal-parietal)\nLanguage network\nPhonological loop",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * L-temporal + L-PPC + DLPFC\ntDCS: C5 - 2 mA * 20 min * T3+F3 anode, Cz cathode\nCES: 100 uA * 15 min\nPrimary scale: WAB (Western Aphasia Battery) * BNT",
            "brain_targets": [
                ("Left temporal (T3/T5)", "Phonological short-term buffer; primary site of logopenic variant atrophy"),
                ("Left PPC (P3)", "Phonological loop storage; sentence repetition impairment node"),
                ("L-DLPFC (F3)", "Language executive control; sentence planning and complex utterance generation"),
                ("Broca area / L-IFG (F3/F7)", "Speech production planning; sentence-level language output"),
                ("Wernicke area / superior temporal (T3)", "Phonological processing and lexical retrieval; word-finding deficit hub"),
            ],
            "combinations": [
                ("tDCS C5 + language therapy (concurrent)", "Language network facilitation during SLT session - maximum use-dependent plasticity", "tDCS 20 min during speech-language therapy", "Logopenic variant - primary language deficit"),
                ("TPS FT6 + SLT programme", "Temporal-parietal network reset supporting language therapy", "TPS 3x/week + weekly SLT sessions", "Moderate logopenic variant"),
                ("AAC training + NIBS", "NIBS supports AAC (augmentative communication) device learning", "tDCS during AAC training", "Logopenic with severe word-finding impairment"),
                ("Full quad + intensive SLT", "Complete cascade with intensive speech-language therapy", "90-min session", "Severe logopenic variant; communication-critical impairment"),
            ],
            "task_pairing": "Language therapy tasks during O-outcome: sentence repetition exercises (short to complex), phonological naming tasks (confrontation naming with phonemic cues), reading aloud, word-finding facilitation techniques, cueing hierarchy. Duration 35 min. Speech-Language Therapist involvement essential.",
            "fnon_hypothesis": "Logopenic variant AD involves progressive left temporo-parietal network atrophy disrupting the phonological loop (T3-P3) and sentence-level language processing. Unlike Broca or Wernicke aphasia, the deficit is at the level of phonological short-term memory failure. TPS FT6 targets the left temporal-parietal junction to support residual phonological processing capacity.",
        },
        {
            "code": "P7", "ft_code": "FT7", "name": "Behavioral Variant",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nBehavioral stabilisation; reduce agitation baseline",
                "O": "tDCS C4 (bilateral DLPFC) * 20 min\nFrontal-OFC behavioral circuit priming",
                "Z": "TPS FT7 * 1,000 pulses * 5 Hz\nDLPFC + OFC behavioral network reset",
                "O2": "Behavioral management tasks * 30 min\nStructured routine; behavioral activation",
            },
            "card_left": "P7 - Behavioral Variant\nFT7 Protocol\n\nModalities:\ntDCS C4\nTPS FT7\nCES\n\nTargets:\nCEN (DLPFC+OFC)\nLIMBIC (frontal-limbic)\nBehavioral circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + OFC\ntDCS: C4 - 2 mA * 20 min * bilateral F3+F4 anode, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: NPI * FBI * Cambridge Behavioural Inventory",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Social-executive control; behavioral inhibition; personalisation; social awareness"),
                ("OFC (Fp1/Fp2)", "Social reward and punishment processing; disinhibition node; OFC degeneration causes social inappropriateness"),
                ("vmPFC (Fz)", "Empathy and social cognition; vmPFC atrophy causes apathy and loss of social interest"),
                ("Anterior cingulate (Cz/FCz)", "Motivation and behavioral initiation; ACC degeneration drives apathy"),
                ("Insula (C3/C4)", "Empathic resonance and social emotion; insula atrophy causes loss of empathy in behavioral AD"),
            ],
            "combinations": [
                ("tDCS C4 + structured routine", "Bilateral DLPFC facilitation during structured behavioral programme", "tDCS 20 min during structured daily activities", "Behavioral AD with apathy"),
                ("TPS FT7 + caregiver-guided sessions", "Network reset supporting caregiver-managed behavioral programme", "TPS 3x/week + caregiver-facilitated activities", "Behavioral AD with agitation or disinhibition"),
                ("CES + behavioural activation", "CES for apathy reduction during behavioural activation programme", "CES 15 min pre-activities", "Behavioral AD with prominent apathy"),
                ("Full quad + person-centred behavioural plan", "Complete cascade with individualised behavioural management plan", "90-min session", "Severe behavioral variant; caregiver burden"),
            ],
            "task_pairing": "Behavioral management tasks during O-outcome: structured meaningful activity schedule, reminiscence with familiar photographs, social engagement tasks (familiar visitors, group activities), apathy activation schedule, sensory stimulation (music, nature). Duration 30 min. Caregiver involvement essential.",
            "fnon_hypothesis": "Behavioral variant AD (bvAD/bvFTD-AD overlap) involves frontal-limbic network degeneration: OFC and vmPFC atrophy causes social disinhibition and empathy loss, while anterior cingulate degeneration drives apathy. TPS FT7 targets OFC + DLPFC to support the residual social-behavioral network capacity.",
        },
        {
            "code": "P8", "ft_code": "FT8", "name": "Mixed Dementia",
            "sozo_bar": {
                "S": "CES 100 uA * 15 min\nVascular + neurodegenerative stabilisation",
                "O": "tDCS C8 (DLPFC + SMA) * 20 min\nCombined cognitive-motor priming",
                "Z": "TPS FT8 * 1,000 pulses * 5 Hz\nDLPFC + M1/SMA mixed dementia reset",
                "O2": "ADL + motor tasks * 30 min\nFunctional cognitive-motor rehabilitation",
            },
            "card_left": "P8 - Mixed Dementia\nFT8 Protocol\n\nModalities:\ntDCS C8\nTPS FT8\nCES\n\nTargets:\nCEN (DLPFC)\nSMN (M1/SMA)\nCognitive-motor circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * bilateral DLPFC + M1/SMA\ntDCS: C8 - 2 mA * 20 min * F3+Cz anode, Oz cathode\nCES: 100 uA * 15 min\nPrimary scale: MMSE * Barthel * gait assessment",
            "brain_targets": [
                ("Bilateral DLPFC (F3+F4)", "Cognitive preservation component; AD-related executive and memory circuits"),
                ("SMA (Cz)", "Motor initiative and gait; vascular component affecting frontal subcortical circuits and SMA"),
                ("M1 (C3/C4)", "Motor output; vascular lesions affecting corticospinal tract; motor rehabilitation target"),
                ("Periventricular white matter (indirect)", "Vascular component; TPS may support perilesional plasticity via frontal approach"),
                ("Hippocampus (T3/T4)", "AD memory component; hippocampal atrophy in mixed dementia"),
            ],
            "combinations": [
                ("tDCS C8 + ADL training (concurrent)", "Cognitive-motor facilitation during functional ADL tasks", "tDCS 20 min during ADL practice", "Mixed dementia with both cognitive and motor impairment"),
                ("TPS FT8 + physiotherapy", "Motor-cognitive network reset supporting physiotherapy", "TPS 3x/week + weekly physio", "Mixed dementia with gait disorder"),
                ("CES + motor-cognitive dual task", "CES arousal support during combined cognitive-motor training", "CES pre + dual task during O-outcome", "Mixed dementia with fatigue"),
                ("Full quad + rehabilitation team", "Complete cascade with multidisciplinary rehabilitation", "90-min session", "Severe mixed dementia; rehabilitation priority"),
            ],
            "task_pairing": "Functional ADL + motor tasks during O-outcome: dual-task walking (counting backwards while walking), timed up-and-go with cognitive distractor, functional reaching tasks, ADL practice with cognitive load (setting table while remembering shopping list). Duration 30 min.",
            "fnon_hypothesis": "Mixed dementia (AD + vascular) involves overlapping CEN (AD neurodegeneration) and SMN (vascular white matter) network pathologies. The vascular component disrupts frontal-subcortical circuits essential for motor initiation, while AD degrades hippocampal and temporal networks. TPS FT8 targets both components simultaneously.",
        },
        {
            "code": "P9", "ft_code": "FT9", "name": "Apathy-Predominant",
            "sozo_bar": {
                "S": "CES 200 uA * 15 min\nMotivational arousal upregulation",
                "O": "tDCS C7 (L-DLPFC + Cz) * 20 min\nMotivation circuit priming: DLPFC + SMA",
                "Z": "TPS FT9 * 1,000 pulses * 5 Hz\nDLPFC + SMA apathy-motivation network reset",
                "O2": "Motivational activation tasks * 30 min\nMeaningful activity engagement",
            },
            "card_left": "P9 - Apathy-Predominant\nFT9 Protocol\n\nModalities:\ntDCS C7\nTPS FT9\nCES 200 uA\n\nTargets:\nCEN (DLPFC)\nSMN (SMA/Cz)\nMotivation circuit",
            "card_right": "TPS: 0.22 mJ/mm2 * 1,000 pulses * 5 Hz * DLPFC + SMA\ntDCS: C7 - 2 mA * 20 min * F3+Cz dual anode, Oz cathode\nCES: 200 uA * 15 min (high arousal)\nPrimary scale: NPI-apathy * AES (Apathy Evaluation Scale)",
            "brain_targets": [
                ("L-DLPFC (F3)", "Motivational drive and goal-directed behavior; DLPFC degeneration drives apathy in AD"),
                ("SMA (Cz)", "Action initiation; SMA hypofunction prevents voluntary activity despite patient's residual desire"),
                ("ACC (FCz)", "Motivation and effort allocation; anterior cingulate degeneration is the proximal cause of apathy"),
                ("OFC (Fp1/Fp2)", "Reward processing; OFC hypofunction reduces perceived reward value of activities"),
                ("Striatum (indirect)", "BG reward-motivation gating; frontostriatal circuit degeneration contributes to apathy in AD"),
            ],
            "combinations": [
                ("tDCS C7 + meaningful activity", "DLPFC+SMA facilitation during personally meaningful activity", "tDCS 20 min during chosen meaningful activity", "AD apathy - primary motivational deficit"),
                ("TPS FT9 + caregiver-guided activation", "Apathy circuit reset supporting structured activation programme", "TPS 3x/week + daily caregiver activation", "Moderate-severe apathy in AD"),
                ("CES + activity scheduling", "High-arousal CES before activities to reduce initiation barrier", "CES 15 min immediately before scheduled activity", "Severe apathy; cannot initiate any activities"),
                ("Full quad + behavioural activation", "Complete cascade with structured behavioural activation plan", "90-min session", "Severe apathy dominating AD presentation"),
            ],
            "task_pairing": "Motivational activation tasks during O-outcome: individualised meaningful activity engagement (based on premorbid interests), positive reminiscence (past achievements, family events), goal-setting for meaningful activities, social engagement with familiar persons. Duration 30 min. Carer-facilitated essential.",
            "fnon_hypothesis": "Apathy-predominant AD reflects DLPFC-ACC-SMA motivation circuit degeneration: DLPFC loses capacity to generate goal-directed intentions, ACC fails to allocate effortful pursuit, and SMA cannot initiate voluntary actions. This is distinct from depression apathy (which responds to antidepressants) and requires direct stimulation of the motor-motivational circuit. TPS FT9 targets the DLPFC-SMA junction.",
        },
    ],
    "task_pairing_rows": [
        ("C1 L-DLPFC (F3 anode)", "Episodic memory encoding", "Word-list learning; face-name association", "DLPFC facilitation during encoding maximises memory consolidation benefit"),
        ("C4 bilateral DLPFC", "Multi-domain cognitive support", "CANTAB tasks; multi-domain battery", "Bilateral priming for comprehensive cognitive domain maintenance"),
        ("C5 temporal + DLPFC", "Language and semantic memory", "Naming tasks; sentence repetition; SLT tasks", "Language network facilitation concurrent with speech therapy"),
        ("C7 executive function", "Planning and ADL", "Tower of London; ADL simulation tasks", "CEN backbone for functional task support"),
        ("C8 DLPFC + SMA", "Motor-cognitive ADL function", "Dual-task walking; ADL with cognitive load", "Combined cognitive-motor facilitation for functional independence"),
        ("FT/F FNON protocols", "Phenotype-specific AD targets", "Phenotype-matched rehabilitation tasks", "Network-level support for specific AD variant network pathology"),
    ],
    "followup_rows": [
        ("Phase 1 - Assessment & Induction (Sessions 1-10)", "3-5x/week", "MMSE, MoCA, NPI, Barthel, CDR at baseline and session 10", "Confirm AD phenotype; select appropriate protocol; assess tolerability"),
        ("Phase 2 - Consolidation (Sessions 11-20)", "3x/week", "ADAS-Cog monthly; caregiver NPI; functional assessment", "Adjust protocol based on phenotype response; introduce home PlatoScience"),
        ("Phase 3 - Maintenance (Month 2-3)", "2x/week", "MMSE monthly; caregiver burden scale", "Maintenance protocol; maximise time on evidence-based home programme"),
        ("Phase 4 - Long-Term (Ongoing)", "Weekly or 2x/week", "Quarterly MMSE + CDR + Barthel", "Ongoing maintenance; reassess phenotype as disease progresses"),
    ],
    "fnon_classification": [
        ("CEN", "Executive-memory encoding failure", "Memory deficit, executive impairment, ADL difficulties", "F1 - CEN Memory Network (L-DLPFC anode)"),
        ("DMN", "Amyloid-related hyperconnectivity", "Memory and self-referential processing deterioration", "F3 - DMN Modulation (bilateral DLPFC + Pz cathode)"),
        ("LIMBIC", "Hippocampal-temporal degeneration", "Episodic memory loss, semantic degradation, orientation failure", "F5 - Limbic Memory (L-temporal anode)"),
        ("ATTENTION", "Posterior parietal atrophy", "Visuospatial impairment, attention deficit, PCA features", "F2 - Frontoparietal CEN (F3+P3 anode)"),
        ("SMN", "Motor-frontal disconnection", "Motor impairment, ADL decline, mixed dementia", "F6 - Apathy-Motivation (F3+Cz anode)"),
        ("SN", "Behavioral-frontal network", "Apathy, agitation, behavioral symptoms", "F6 - Apathy-Motivation (F3+Cz anode)"),
    ],
    "fnon_montage_selection": [
        ("Amnestic MCI / memory dominant", "C1: F3 anode, Fp2 cathode (2 mA, 25 min)", "CEN memory encoding network"),
        ("Multi-domain MCI", "C4: bilateral F3+F4 anode, Oz cathode (2 mA, 25 min)", "Comprehensive bilateral CEN"),
        ("PCA / visuospatial dominant", "C6: bilateral P3+P4 anode, Oz cathode (2 mA, 20 min)", "ATTENTION posterior network"),
        ("Logopenic / language dominant", "C5: T3+F3 anode, Cz cathode (2 mA, 20 min)", "Language-CEN network"),
        ("Behavioral / apathy dominant", "C7: F3+Cz dual anode, Oz cathode (2 mA, 20 min)", "Frontal motivation circuit"),
        ("Mixed dementia with motor", "C8: F3+Cz dual anode, Oz cathode (2 mA, 20 min)", "CEN + SMN combined"),
    ],
}
'''

# Write to file
with open(data_file, 'a', encoding='utf-8') as f:
    f.write(CONDITIONS_CODE)

print(f"Appended conditions 3-4 (ADHD + Alzheimers) to {data_file}")
print(f"File size: {data_file.stat().st_size // 1024} KB")
