"""Condition data for Partners Clinical Examination Checklist generator."""
CB = "\u2610"

CONDITIONS = [

# ─── 1. DEPRESSION ────────────────────────────────────────────────────────────
{
  "slug":"depression","display_name":"Major Depressive Disorder (MDD)","short_name":"Depression",
  "network_relevance":{
    "dmn":  "HYPER-active. Rumination drives sustained mPFC/PCC hyperactivation with over-processing of negative autobiographical memories. Failure to disengage DMN underlies repetitive negative thinking loops.",
    "cen":  "HYPO-active. Impaired DLPFC recruitment reduces top-down regulation of rumination. Working memory and attentional control deficits reflect reduced CEN engagement during emotional challenge.",
    "sn":   "Dysregulated DMN\u2194CEN switching. Blunted interoception produces anhedonia. Reduced anterior insula activity impairs emotional awareness; dACC dysfunction disrupts motivational salience.",
    "smn":  "HYPO-active. Psychomotor retardation reflects reduced SMA and premotor output. Slowed speech, reduced gesture, stooped posture, and bradyphrenia are direct SMN hypoactivation signatures.",
    "limbic":"PRIMARY NETWORK IN MDD. Amygdala hyperactivation + OFC dysregulation drive sustained low mood, anhedonia, and emotional dysregulation. Hippocampal atrophy correlates with episode duration.",
    "attn": "HYPO-active. Concentration impairment and difficulty sustaining attention reflect DAN hypoactivation. Attentional bias toward negative stimuli is mediated by VAN hyperresponsivity to sad/negative cues.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous negative self-referential speech","0=Normal, 1=Absent/withdrawn, 2=Excessive/ruminating"),
      ("Autobiographical memory negative bias","0=Balanced, 1=Reduced access, 2=Strongly negative-toned"),
      ("Mind-wandering / ruminative thinking","0=Normal, 1=Absent, 2=Intrusive rumination"),
      ("Future thinking (hopelessness probe)","0=Normal, 1=Slightly negative, 2=Hopeless/catastrophic"),
      ("Self-awareness of depression severity","0=Normal insight, 1=Poor, 2=Excessive self-criticism"),
      ("Cognitive fluctuations","0=Consistent, 1=Slowed throughout, 2=Variable/dissociated"),
      ("Narrative coherence (life story)","0=Coherent, 1=Fragmented, 2=Globally negative"),
    ],
    "cen":[
      ("Serial 7s / mental calculation","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced span, 2=Unable"),
      ("Trail Making A to B equivalent","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency (animals/letters)","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting / cognitive flexibility","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Blunted, 2=Exaggerated"),
      ("Interoception (heartbeat awareness)","0=Normal, 1=Absent/reduced, 2=Excessive/distressing"),
      ("Emotional reactivity (affect probe)","0=Normal, 1=Flat/anhedonic, 2=Labile"),
      ("Anhedonia probe (pleasure anticipation)","0=Normal, 1=Reduced, 2=Absent"),
      ("Task switching ability","0=Normal, 1=Slow, 2=Stuck in rumination"),
      ("Error monitoring (go/no-go)","0=Normal, 1=Misses, 2=Over-correction"),
      ("Autonomic signs (HR, sweating, BP)","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Psychomotor speed (finger tapping)","0=Normal, 1=Slow/decrement, 2=Severely slowed"),
      ("Spontaneous movement / gesture","0=Normal, 1=Reduced, 2=Absent"),
      ("Speech rate and volume","0=Normal, 1=Slow/quiet, 2=Mute/whisper"),
      ("Facial expression (hypomimia)","0=Normal, 1=Reduced, 2=Masked/absent"),
      ("Posture (stooped / withdrawn)","0=Normal, 1=Mild stoop, 2=Severe slump"),
      ("Gait speed and arm swing","0=Normal, 1=Slow, 2=Shuffling"),
      ("Fine motor (writing sample)","0=Normal, 1=Slow/small, 2=Unable"),
      ("Muscle tone","0=Normal, 1=Hypotonic, 2=Increased tension"),
    ],
    "limbic":[
      ("Affect observation (facial)","0=Normal, 1=Flat/masked, 2=Tearful/distressed"),
      ("Mood screening (PHQ-2 equivalent)","0=Normal, 1=Low, 2=Severely depressed"),
      ("Anxiety co-screening (GAD-2)","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / apathy","0=Normal, 1=Reduced drive, 2=Absent motivation"),
      ("Reward sensitivity / anhedonia","0=Normal, 1=Anhedonia, 2=Complete loss"),
      ("Stress response pattern","0=Normal, 1=Blunted, 2=Reactive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated/crying"),
    ],
    "attn":[
      ("Sustained attention (continuous task)","0=Normal, 1=Lapses, 2=Unable to sustain"),
      ("Selective attention (Stroop-type)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search / scanning","0=Normal, 1=Slow, 2=Cannot complete"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting response","0=Normal, 1=Delayed, 2=Absent"),
      ("Attentional bias to negative stimuli","0=None, 1=Mild, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness / vigilance","0=Normal, 1=Drowsy/slowed, 2=Hypervigilant"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS / CES to dampen DMN hyperactivity",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 to upregulate CEN",
    "sn":   "taVNS / CES for DMN/CEN switching normalisation",
    "smn":  "Anodal M1/SMA tDCS for psychomotor retardation",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 limbic modulation",
    "attn": "Anodal parietal tDCS / TPS FT5 for DAN",
  },
  "phenotype_options": CB+" Melancholic  "+CB+" Atypical  "+CB+" Anxious  "+CB+" Psychomotor-retarded  "+CB+" Treatment-resistant  "+CB+" Cognitive",
},

# ─── 2. ANXIETY ───────────────────────────────────────────────────────────────
{
  "slug":"anxiety","display_name":"Generalized Anxiety Disorder (GAD)","short_name":"Anxiety",
  "network_relevance":{
    "dmn":  "HYPER. Chronic worry drives persistent future-oriented catastrophic simulation via mPFC. Excessive self-referential threat processing locks DMN in anticipatory anxiety mode, preventing task engagement.",
    "cen":  "Compromised. CEN is engaged in worry maintenance rather than effective problem-solving. DLPFC fails to down-regulate amygdala activation, impairing top-down anxiolytic control over threat appraisal.",
    "sn":   "HYPER. PRIMARY NETWORK IN GAD. Anterior insula and dACC hyperactivation amplify interoceptive threat signals. Autonomic overdrive (palpitations, sweating, dyspnoea) reflects sustained SN hyperactivation.",
    "smn":  "HYPER-tension. Chronic muscle tension, tremulousness, motor restlessness, and fidgeting reflect sustained SMA/M1 activation driven by continuous autonomic and limbic overflow into somatic pathways.",
    "limbic":"HYPER. Amygdala hyperactivation drives sustained fear-state without discrete threat. HPA axis overdrive, reduced hippocampal GABAergic inhibition, and OFC worry-loop maintenance perpetuate the disorder.",
    "attn": "Threat-biased. DAN shows attentional capture by threat-relevant stimuli. VAN hyperresponsivity drives hyperorienting to potential threats. Disengagement from non-threatening stimuli is critically impaired.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous worry/threat content in speech","0=Normal, 1=Absent, 2=Excessive catastrophising"),
      ("Autobiographical memory threat bias","0=Balanced, 1=Normal, 2=Strongly threat-focused"),
      ("Mind-wandering to worry topics","0=Normal, 1=Absent, 2=Uncontrollable worry loops"),
      ("Future thinking catastrophic simulation","0=Normal, 1=Slightly negative, 2=Catastrophic"),
      ("Self-awareness of anxiety irrationality","0=Normal insight, 1=Reduced, 2=None/fixed"),
      ("Cognitive fluctuations with anxiety","0=Consistent, 1=Slowed, 2=Fluctuates with panic"),
      ("Repetitive thought content","0=None, 1=Occasional, 2=Constant loops"),
    ],
    "cen":[
      ("Serial 7s / mental calculation","0=Normal, 1=Slow/errors, 2=Unable due to anxiety"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency (animals/letters)","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting / cognitive flexibility","0=Normal, 1=Worry-locked, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Freezes under load"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated/prolonged"),
      ("Pain/discomfort sensitivity","0=Normal, 1=Hypo, 2=Hyper"),
      ("Interoception (heartbeat awareness)","0=Normal, 1=Absent, 2=Excessive/distressing"),
      ("Emotional reactivity to stressor","0=Normal, 1=Flat, 2=Panic-level"),
      ("Task switching ability","0=Normal, 1=Slow, 2=Stuck on threat"),
      ("Error monitoring (go/no-go)","0=Normal, 1=Misses, 2=Over-corrects"),
      ("Autonomic signs (HR, sweating, BP)","0=Normal, 1=Hypo, 2=Hyper/tachycardia"),
    ],
    "smn":[
      ("Muscle tension neck/shoulder palpation","0=Normal, 1=Mild, 2=Severe/rigid"),
      ("Fine tremor (hands outstretched)","0=Absent, 1=Mild, 2=Moderate action tremor"),
      ("Motor restlessness / fidgeting","0=None, 1=Occasional, 2=Constant"),
      ("Breathing pattern (rate/depth)","0=Normal, 1=Shallow/fast, 2=Hyperventilation"),
      ("Posture (tension/guarding)","0=Normal, 1=Tense, 2=Rigid/braced"),
      ("Gait (tension/stiffness)","0=Normal, 1=Stiff, 2=Restricted"),
      ("Coordination under task stress","0=Normal, 1=Mildly impaired, 2=Disorganised"),
      ("Jaw clenching / bruxism","0=Absent, 1=Mild, 2=Severe"),
    ],
    "limbic":[
      ("Affect facial anxiety expression","0=Normal, 1=Tense/worried, 2=Panicked"),
      ("Mood screening anxiety (GAD-2)","0=Normal, 1=Mild, 2=Severe"),
      ("Depression co-screen (PHQ-2)","0=Normal, 1=Low, 2=Severe"),
      ("Motivation / avoidance","0=Normal, 1=Avoidance, 2=Housebound"),
      ("Reward sensitivity","0=Normal, 1=Reduced, 2=Anhedonia"),
      ("Stress response","0=Normal, 1=Blunted, 2=Hyperactive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated"),
    ],
    "attn":[
      ("Sustained attention","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop-type)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search / threat scanning","0=Normal, 1=Slow, 2=Hypervigilant scan"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Hypervigilant to sounds"),
      ("Orienting to threat cues","0=Normal, 1=Delayed, 2=Locked-on/cannot disengage"),
      ("Disengagement from threat","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness / vigilance","0=Normal, 1=Normal, 2=Hypervigilant"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS to reduce worry-loop DMN hyperactivity",
    "cen":  "Anodal L-DLPFC tDCS for top-down anxiolytic control",
    "sn":   "taVNS / CES for anterior insula/dACC downregulation",
    "smn":  "Cathodal SMA tDCS to reduce somatic tension",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for amygdala regulation",
    "attn": "Cathodal rTPJ tDCS to reduce threat attentional bias",
  },
  "phenotype_options": CB+" Cognitive-worry  "+CB+" Somatic-tension  "+CB+" Mixed  "+CB+" Panic-prone  "+CB+" Social overlap  "+CB+" Insomnia-linked",
},

# ─── 3. ADHD ──────────────────────────────────────────────────────────────────
{
  "slug":"adhd","display_name":"Attention Deficit Hyperactivity Disorder (ADHD)","short_name":"ADHD",
  "network_relevance":{
    "dmn":  "Cannot suppress. ADHD is characterised by failure to deactivate DMN during goal-directed tasks. mPFC-PCC connectivity is reduced, allowing task-unrelated thoughts and daydreaming to intrude continuously.",
    "cen":  "HYPO. PRIMARY NETWORK IN ADHD. DLPFC underactivation underpins working memory deficits, poor planning, and impaired inhibitory control. Reduced CEN-DMN anticorrelation is the ADHD network signature.",
    "sn":   "Dysregulated switching. Impaired SN gating between DMN and CEN produces unstable task engagement. Reward sensitivity and impulse control failures reflect dACC and anterior insula dysfunction.",
    "smn":  "HYPER. Hyperactivity and motor overflow reflect excessive SMA/M1 excitability. Fidgeting, motor restlessness, and impaired timing/rhythm reflect disrupted cortico-striatal motor circuits.",
    "limbic":"Dysregulated. Dopamine-mediated reward pathway disruption drives impulsivity, emotional dysregulation (rejection-sensitive dysphoria), and inability to delay gratification via OFC dysfunction.",
    "attn": "HYPO/dysregulated. DAN hypoactivation produces inattention and failure to sustain goal-directed attention. VAN hyperresponsivity causes distractibility to task-irrelevant stimuli (attentional capture).",
  },
  "network_tests":{
    "dmn":[
      ("Task-unrelated thought intrusion during tasks","0=None, 1=Occasional, 2=Constant mind-wandering"),
      ("Daydreaming during interview","0=None, 1=Occasional, 2=Frequent/obvious"),
      ("Self-referential thought during tasks","0=Normal, 1=Reduced self-awareness, 2=Excessive"),
      ("Future planning awareness","0=Normal, 1=Impaired, 2=No future orientation"),
      ("Self-awareness of ADHD impact","0=Good insight, 1=Poor, 2=Absent"),
      ("Cognitive fluctuations","0=Consistent, 1=Variable, 2=Hyperfocus/absent alternation"),
      ("Mental restlessness","0=None, 1=Mild, 2=Uncontrollable"),
    ],
    "cen":[
      ("Serial 7s / mental calculation","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced span, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting (perseveration test)","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Impulsivity: interrupting/blurting","0=None, 1=Occasional, 2=Constant"),
      ("Interoception","0=Normal, 1=Reduced, 2=Excessive restlessness"),
      ("Emotional reactivity","0=Normal, 1=Flat, 2=Labile/explosive"),
      ("Reward sensitivity (immediate vs delayed)","0=Normal, 1=Reduced, 2=Hypersensitive/impulsive"),
      ("Task switching ability","0=Normal, 1=Impulsive switching, 2=Stuck in hyperfocus"),
      ("Error monitoring (go/no-go)","0=Normal, 1=Commission errors, 2=Severe impulsivity"),
      ("Autonomic signs","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Motor restlessness / hyperactivity","0=None, 1=Fidgeting, 2=Cannot remain seated"),
      ("Fidgeting (hands/feet/objects)","0=None, 1=Mild, 2=Constant"),
      ("Fine motor control (tapping rhythm)","0=Normal, 1=Irregular, 2=Disorganised"),
      ("Handwriting quality","0=Normal, 1=Inconsistent, 2=Illegible"),
      ("Motor overflow (mirror movements)","0=Absent, 1=Mild, 2=Prominent"),
      ("Coordination (tandem walk)","0=Normal, 1=Mild impairment, 2=Cannot perform"),
      ("Response inhibition motor (stop-signal)","0=Normal, 1=Slow SSRT, 2=Cannot inhibit"),
      ("Timing and rhythm (tap to beat)","0=Normal, 1=Slightly off, 2=Cannot maintain"),
    ],
    "limbic":[
      ("Affect observation","0=Normal, 1=Flat, 2=Labile/explosive"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe"),
      ("Emotional dysregulation probe","0=None, 1=Mild, 2=Severe RSD-type"),
      ("Motivation / task initiation","0=Normal, 1=Reduced, 2=Cannot initiate"),
      ("Reward sensitivity","0=Normal, 1=Anhedonia, 2=Impulsive reward-seeking"),
      ("Frustration tolerance","0=Normal, 1=Low, 2=Explosive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated"),
    ],
    "attn":[
      ("Sustained attention (continuous task)","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search / distractor filtering","0=Normal, 1=Distracted, 2=Cannot filter"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting to irrelevant stimuli","0=Normal, 1=Occasional, 2=Constant capture"),
      ("Re-orienting back to task","0=Normal, 1=Slow, 2=Cannot refocus"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness variability","0=Stable, 1=Variable, 2=Extreme fluctuation"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC/PCC tDCS to suppress DMN task-time intrusion",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 — primary ADHD target",
    "sn":   "taVNS / CES for DMN/CEN switch normalisation",
    "smn":  "Cathodal SMA tDCS to reduce motor overflow",
    "limbic":"taVNS / OFC-targeting tDCS for reward dysregulation",
    "attn": "Anodal R-parietal tDCS / TPS FT5 for DAN enhancement",
  },
  "phenotype_options": CB+" Inattentive  "+CB+" Hyperactive-Impulsive  "+CB+" Combined  "+CB+" Executive dysfunction  "+CB+" Emotional dysregulation  "+CB+" SCT",
},

# ─── 4. ALZHEIMER'S ───────────────────────────────────────────────────────────
{
  "slug":"alzheimers","display_name":"Alzheimer's Disease / MCI","short_name":"Alzheimer's",
  "network_relevance":{
    "dmn":  "PRIMARY NETWORK IN AD. Amyloid-beta preferentially deposits in DMN hubs (mPFC, PCC, precuneus) decades before symptoms. Episodic memory failure, loss of autobiographical narrative, and identity degradation are direct DMN degeneration signatures.",
    "cen":  "HYPO progressive. DLPFC and PPC involvement increases with disease stage. Executive dysfunction, impaired working memory, and reduced cognitive flexibility emerge as CEN atrophy progresses from MCI to moderate AD.",
    "sn":   "HYPO. Reduced salience detection underlies apathy, disinhibition, and social appropriateness failures. Anterior insula atrophy impairs interoception; dACC dysfunction contributes to motivation loss and error unawareness.",
    "smn":  "Relatively spared early; increasingly affected in moderate-severe AD. Ideomotor apraxia, impaired motor sequencing, and gait changes emerge as parietal-premotor involvement increases with Braak staging.",
    "limbic":"HYPO/atrophic. Hippocampal degeneration is the anatomical hallmark; entorhinal cortex is earliest affected. Emotional flattening, apathy, and depression reflect limbic network progressive failure and disconnection.",
    "attn": "HYPO early. Reduced processing speed and sustained attention are among the earliest cognitive changes in MCI-AD transition. DAN disruption contributes to visuospatial navigation failures and getting lost.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous self-referential speech","0=Normal, 1=Reduced/tangential, 2=Confabulatory"),
      ("Autobiographical memory recent events","0=Normal, 1=Impaired recent only, 2=Remote only/confabulation"),
      ("Mind-wandering / disorientation","0=Normal, 1=Occasional confusion, 2=Persistent disorientation"),
      ("Daydreaming / visual phenomena","0=Normal, 1=None, 2=Hallucinations"),
      ("Self-awareness of memory deficits","0=Normal insight, 1=Anosognosia mild, 2=Anosognosia severe"),
      ("Future planning ability","0=Normal, 1=Impaired, 2=Absent"),
      ("Narrative coherence","0=Coherent, 1=Fragmented, 2=Incoherent/circular"),
    ],
    "cen":[
      ("Serial 7s / mental arithmetic","0=Normal, 1=Errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=<6"),
      ("Clock drawing (executive)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task","0=Normal, 1=Impaired, 2=Unable"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Blunted, 2=Disinhibited"),
      ("Pain sensitivity","0=Normal, 1=Hypo, 2=Hyper"),
      ("Interoception","0=Normal, 1=Absent, 2=Distorted"),
      ("Emotional reactivity","0=Normal, 1=Flat/apathetic, 2=Disinhibited"),
      ("Task switching","0=Normal, 1=Slow, 2=Stuck"),
      ("Error monitoring","0=Normal, 1=Reduced awareness, 2=Absent"),
      ("Autonomic signs","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Ideomotor apraxia pantomime to command","0=Normal, 1=Mild errors, 2=Severe apraxia"),
      ("Motor sequencing (Luria fist-edge-palm)","0=Normal, 1=Errors, 2=Unable"),
      ("Gait speed and step length","0=Normal, 1=Slowed, 2=Shuffling/apractic"),
      ("Postural stability","0=Normal, 1=Mild instability, 2=Falls risk"),
      ("Tool use pantomime","0=Normal, 1=Impaired, 2=Unable"),
      ("Writing (micrographia/perseveration)","0=Normal, 1=Impaired, 2=Unable"),
      ("Dressing apraxia (clinical observation)","0=Normal, 1=Mild, 2=Severe"),
      ("Proprioception (position sense)","0=Normal, 1=Impaired, 2=Absent"),
    ],
    "limbic":[
      ("Affect observation","0=Normal, 1=Flat/apathetic, 2=Disinhibited"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / apathy","0=Normal, 1=Reduced, 2=Complete apathy"),
      ("Reward / pleasure response","0=Normal, 1=Anhedonia, 2=Absent"),
      ("Stress response","0=Normal, 1=Blunted, 2=Catastrophic/catastrophisation"),
      ("Emotional regulation","0=Normal, 1=Labile, 2=Severely dysregulated"),
    ],
    "attn":[
      ("Sustained attention","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search / scanning","0=Normal, 1=Slow/neglect, 2=Cannot complete"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting response","0=Normal, 1=Delayed, 2=Absent"),
      ("Reorienting after distraction","0=Normal, 1=Slow, 2=Absent"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness / vigilance","0=Normal, 1=Drowsy, 2=Fluctuating"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal PCC tDCS / Anodal temporal for memory encoding",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for executive support",
    "sn":   "taVNS for apathy and salience normalisation",
    "smn":  "Anodal parietal tDCS for apraxia / praxis support",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 hippocampal support",
    "attn": "Anodal parietal/temporal tDCS / TPS FT5",
  },
  "phenotype_options": CB+" Amnestic MCI  "+CB+" Multi-domain MCI  "+CB+" Early-onset AD  "+CB+" Late-onset AD  "+CB+" PCA  "+CB+" Logopenic variant",
},

# ─── 5. STROKE REHAB ──────────────────────────────────────────────────────────
{
  "slug":"stroke_rehab","display_name":"Post-Stroke Rehabilitation","short_name":"Stroke",
  "network_relevance":{
    "dmn":  "Disrupted by lesion and diaschisis. Right-hemisphere strokes impair self-awareness (anosognosia) via PCC/precuneus disconnection. Post-stroke depression and identity disruption reflect chronic DMN failure.",
    "cen":  "Disrupted especially with frontal/parietal lesions. Post-stroke executive dysfunction, working memory impairment, and cognitive inflexibility reflect CEN damage or disrupted inter-hemispheric CEN connectivity.",
    "sn":   "Asymmetrically disrupted. Right-hemisphere lesions impair the VAN, producing hemispatial neglect. Post-stroke emotional dysregulation and attention allocation failure reflect anterior insula/dACC damage.",
    "smn":  "PRIMARY NETWORK IN STROKE REHAB. Corticospinal tract disruption produces contralateral hemiparesis. Ipsilesional M1 may be hyperexcitable; contralesional M1 hypoexcitable (interhemispheric imbalance model).",
    "limbic":"Post-stroke depression (30-40%) and emotional lability reflect limbic network disruption. Amygdala involvement or disconnection from prefrontal regulation drives emotional dysregulation and grief response.",
    "attn": "Frequently disrupted. Right MCA strokes cause hemispatial neglect via DAN/VAN imbalance. IPS and FEF lesions impair voluntary orienting; sustained attention deficits are common in frontal stroke territory.",
  },
  "network_tests":{
    "dmn":[
      ("Self-awareness of deficits (anosognosia)","0=Normal, 1=Mild denial, 2=Complete anosognosia"),
      ("Autobiographical memory (personal events)","0=Normal, 1=Impaired, 2=Confabulation"),
      ("Mind-wandering / resting state awareness","0=Normal, 1=Absent, 2=Perseverative"),
      ("Post-stroke identity adjustment","0=Adapting, 1=Struggling, 2=Complete denial"),
      ("Self-awareness of emotional changes","0=Normal, 1=Reduced, 2=Absent"),
      ("Future planning","0=Normal, 1=Impaired, 2=Absent"),
      ("Cognitive fluctuations","0=Consistent, 1=Slowed, 2=Fluctuating"),
    ],
    "cen":[
      ("Serial 7s","0=Normal, 1=Errors, 2=Unable"),
      ("Digit span","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced, 2=Unable"),
      ("Clock drawing","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Unable"),
    ],
    "sn":[
      ("Hemispatial neglect screen line bisection","0=None, 1=Mild, 2=Severe neglect"),
      ("Pain sensitivity","0=Normal, 1=Hypo, 2=Hyper/central pain"),
      ("Interoception","0=Normal, 1=Reduced, 2=Disturbed"),
      ("Emotional reactivity post-stroke","0=Normal, 1=Flat, 2=Labile"),
      ("Task switching","0=Normal, 1=Slow, 2=Stuck"),
      ("Error awareness","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic signs","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Upper limb strength affected side MRC","0=5/5 Normal, 1=3-4/5, 2=0-2/5 Plegic"),
      ("Lower limb strength affected side MRC","0=5/5 Normal, 1=3-4/5, 2=0-2/5 Plegic"),
      ("Spasticity (Modified Ashworth Scale)","0=None, 1=Mild MAS 1-2, 2=Severe MAS 3-4"),
      ("Gait pattern and speed","0=Normal, 1=Hemiplegic gait, 2=Non-ambulant"),
      ("Balance (standing/Berg)","0=Normal, 1=Impaired, 2=Cannot stand independently"),
      ("Fine motor / dexterity","0=Normal, 1=Impaired, 2=Unable"),
      ("Facial asymmetry (VII nerve)","0=None, 1=Mild, 2=Severe"),
      ("Proprioception affected side","0=Normal, 1=Impaired, 2=Absent"),
    ],
    "limbic":[
      ("Affect post-stroke depression","0=Normal, 1=Low, 2=Severely depressed"),
      ("Mood screening (PHQ-2)","0=Normal, 1=Low, 2=Severe"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation for rehabilitation","0=Motivated, 1=Reduced, 2=Refuses therapy"),
      ("Pathological laughing/crying (PLC)","0=None, 1=Mild, 2=Severe"),
      ("Stress response","0=Normal, 1=Blunted, 2=Catastrophic"),
      ("Emotional regulation","0=Normal, 1=Labile, 2=Severely dysregulated"),
    ],
    "attn":[
      ("Hemispatial neglect (visual)","0=None, 1=Mild, 2=Severe"),
      ("Sustained attention (continuous task)","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search (cancellation test)","0=Normal, 1=Slow/omissions, 2=Severe neglect"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting response","0=Normal, 1=Delayed, 2=Absent"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness","0=Normal, 1=Drowsy, 2=Hypervigilant"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal unaffected-hemisphere / anodal affected-hemisphere tDCS",
    "cen":  "Anodal L-DLPFC tDCS (ipsilesional) / TPS FT3",
    "sn":   "Anodal right parietal tDCS for neglect / taVNS",
    "smn":  "Anodal M1 contralesional tDCS / TPS FT1 (primary target)",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for post-stroke depression",
    "attn": "Anodal contralesional parietal tDCS / TPS FT5",
  },
  "phenotype_options": CB+" Motor UL dominant  "+CB+" Motor LL dominant  "+CB+" Aphasia  "+CB+" Hemispatial neglect  "+CB+" Cognitive  "+CB+" Spasticity-predominant",
},

# ─── 6. TBI ───────────────────────────────────────────────────────────────────
{
  "slug":"tbi","display_name":"Traumatic Brain Injury (TBI)","short_name":"TBI",
  "network_relevance":{
    "dmn":  "Disrupted by diffuse axonal injury (DAI) affecting PCC-mPFC white matter tracts. Identity disruption, self-monitoring failure, and poor self-awareness of deficits (anosognosia) reflect DMN connectivity breakdown.",
    "cen":  "HYPO. DLPFC is particularly vulnerable to both focal and blast injury. Executive dysfunction, working memory impairment, and impaired problem-solving reflect disrupted CEN after TBI of any severity.",
    "sn":   "HYPER/dysregulated. Emotional lability, stimulus sensitivity, and impulsivity reflect SN hyperexcitability post-TBI. Post-traumatic stress responses may develop as a SN sensitisation phenomenon.",
    "smn":  "Variable by lesion. Vestibular/balance disruption, oculomotor abnormalities, fine motor slowing, and post-concussive motor speed reduction reflect SMN and cerebellar involvement post-TBI.",
    "limbic":"Dysregulated. Irritability, aggression, depression, and apathy are among the most common sequelae of TBI. Amygdala hyperreactivity, hippocampal vulnerability, and OFC disruption drive behavioural changes.",
    "attn": "HYPO. Post-concussive attentional deficits are the most common and persistent cognitive symptom. DAN disruption causes poor sustained attention; processing speed reduction is a hallmark across severities.",
  },
  "network_tests":{
    "dmn":[
      ("Self-awareness of cognitive deficits","0=Normal, 1=Mild anosognosia, 2=Severe anosognosia"),
      ("Autobiographical memory continuity","0=Normal, 1=PTA-related gaps, 2=Dense retrograde"),
      ("Mind-wandering / disorientation","0=Normal, 1=Occasional, 2=Persistent"),
      ("Identity coherence post-injury","0=Intact, 1=Struggling, 2=Fragmented/denied"),
      ("Self-monitoring during tasks","0=Normal, 1=Reduced, 2=Absent"),
      ("Future planning","0=Normal, 1=Impaired, 2=Absent"),
      ("Cognitive fluctuations","0=Consistent, 1=Slowed, 2=Fluctuating badly"),
    ],
    "cen":[
      ("Serial 7s","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Unable"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated"),
      ("Pain / headache sensitivity","0=Normal, 1=Hypo, 2=Hyper/photophobia"),
      ("Interoception","0=Normal, 1=Reduced, 2=Excessive/distress"),
      ("Emotional reactivity / lability","0=Normal, 1=Blunted, 2=Explosive/labile"),
      ("Task switching","0=Normal, 1=Slow, 2=Impulsive switching"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic signs","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Balance (Romberg/tandem)","0=Normal, 1=Mild impairment, 2=Cannot perform"),
      ("Coordination (finger-to-nose)","0=Normal, 1=Mild dysmetria, 2=Severe ataxia"),
      ("Gait stability (tandem walk)","0=Normal, 1=Unsteady, 2=Cannot perform"),
      ("Fine motor speed (tapping)","0=Normal, 1=Slow, 2=Severely slowed"),
      ("Oculomotor exam (smooth pursuit)","0=Normal, 1=Saccadic pursuit, 2=Cannot track"),
      ("Grip strength (dynamometer)","0=Normal, 1=Reduced, 2=Severely reduced"),
      ("Dual-task motor (walk + cognitive)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
      ("Proprioception (position sense)","0=Normal, 1=Impaired, 2=Absent"),
    ],
    "limbic":[
      ("Affect (irritability/lability)","0=Normal, 1=Irritable, 2=Explosive/aggressive"),
      ("Mood screening","0=Normal, 1=Low/depressed, 2=Severe"),
      ("Anxiety / PTSD symptoms","0=Normal, 1=Mild, 2=Severe/PTSD"),
      ("Motivation / apathy","0=Normal, 1=Reduced, 2=Absent"),
      ("Reward sensitivity / impulsivity","0=Normal, 1=Reduced, 2=Risk-seeking"),
      ("Frustration tolerance","0=Normal, 1=Low, 2=Explosive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Severely dysregulated"),
    ],
    "attn":[
      ("Sustained attention (continuous task)","0=Normal, 1=Lapses, 2=Unable"),
      ("Processing speed (Stroop)","0=Normal, 1=Slow, 2=Severely slowed"),
      ("Visual search / scanning","0=Normal, 1=Slow, 2=Cannot complete"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting response","0=Normal, 1=Delayed, 2=Absent"),
      ("Reorienting after distraction","0=Normal, 1=Slow, 2=Cannot refocus"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness (fatigue-related fluctuation)","0=Normal, 1=Drowsy, 2=Severe fatigue"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS for anosognosia / self-monitoring",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for executive function",
    "sn":   "taVNS / CES for emotional lability and SN normalisation",
    "smn":  "Anodal cerebellar tDCS for vestibular/coordination",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for behavioural regulation",
    "attn": "Anodal parietal tDCS / TPS FT5 for processing speed",
  },
  "phenotype_options": CB+" Mild/Concussion  "+CB+" Moderate  "+CB+" Severe  "+CB+" Executive dominant  "+CB+" Post-traumatic headache  "+CB+" Behavioural  "+CB+" DOC",
},

# ─── 7. CHRONIC PAIN ──────────────────────────────────────────────────────────
{
  "slug":"chronic_pain","display_name":"Chronic Pain / Fibromyalgia","short_name":"Chronic Pain",
  "network_relevance":{
    "dmn":  "HYPER. Pain catastrophising and rumination about pain drive mPFC hyperactivation. Distorted body schema and excessive self-referential processing of pain sensations reflect DMN hyperactivity amplifying the pain experience.",
    "cen":  "Compromised. Impaired descending pain modulation from DLPFC reduces conditioned pain modulation (CPM) efficacy. Cognitive interference from pain reduces available CEN resources for working memory and planning.",
    "sn":   "HYPER. PRIMARY NETWORK IN CHRONIC PAIN. Central sensitisation reflects anterior insula and dACC hyperactivation that amplifies nociceptive salience. Interoceptive error signals perpetuate pain catastrophising.",
    "smn":  "Reorganised. Pain-avoidance motor patterns, protective guarding, and altered proprioceptive processing reflect chronic SMN reorganisation. Reduced motor cortex excitability is observed in fibromyalgia.",
    "limbic":"Dysregulated. Emotional amplification of pain via amygdala-insula circuits drives the affective component of chronic pain. Comorbid depression and anxiety reflect limbic network involvement in pain perpetuation.",
    "attn": "Hypervigilant to pain. Attentional bias toward pain-related stimuli reflects DAN hyperresponsivity to nociceptive cues. VAN-driven orienting to any bodily sensation perpetuates pain hyperawareness.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous pain-focused self-referential speech","0=Normal, 1=Absent, 2=Constant pain rumination"),
      ("Pain catastrophising (verbal probe)","0=None, 1=Mild, 2=Severe catastrophising"),
      ("Body schema distortion (body map)","0=Normal, 1=Slightly distorted, 2=Severely distorted"),
      ("Mind-wandering to pain topics","0=Normal, 1=Absent, 2=Constant pain focus"),
      ("Self-awareness of catastrophising","0=Good insight, 1=Limited, 2=None"),
      ("Future thinking (pain-related hopelessness)","0=Normal, 1=Mild pessimism, 2=Hopeless"),
      ("Narrative coherence (pain history)","0=Coherent, 1=Fragmented, 2=Catastrophic narrative"),
    ],
    "cen":[
      ("Serial 7s / mental calculation","0=Normal, 1=Slow/errors, 2=Unable due to pain"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Pain threshold (tender point pressure)","0=Normal, 1=Hypo, 2=Hyper/allodynia"),
      ("Allodynia to light touch","0=Absent, 1=Mild, 2=Severe"),
      ("Interoception (pain signal amplification)","0=Normal, 1=Reduced, 2=Excessive/amplified"),
      ("Emotional reactivity to pain discussion","0=Normal, 1=Flat, 2=Distressed/labile"),
      ("Task switching when in pain","0=Normal, 1=Slow, 2=Cannot switch"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic signs (sweating, HR)","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Pain-guarding posture (observation)","0=None, 1=Mild guarding, 2=Severe antalgic posture"),
      ("Tender point examination (ACR sites)","0=Normal, 1=4-10 tender, 2=11+ tender points"),
      ("Range of motion (spine/limbs)","0=Normal, 1=Mildly limited, 2=Severely limited"),
      ("Grip strength (dynamometer)","0=Normal, 1=Reduced, 2=Severely reduced"),
      ("Gait compensation patterns","0=Normal, 1=Antalgic gait, 2=Severely abnormal"),
      ("Functional reach test","0=Normal, 1=Reduced, 2=Unable"),
      ("Muscle tone (palpation)","0=Normal, 1=Hypotonic, 2=Hypertonic/spasm"),
      ("Sensory testing (allodynia map)","0=Normal, 1=Regional, 2=Widespread allodynia"),
    ],
    "limbic":[
      ("Affect (pain-related distress)","0=Normal, 1=Distressed, 2=Severely distressed"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation to engage in activity","0=Normal, 1=Reduced, 2=Avoidance/kinesiophobia"),
      ("Reward sensitivity / pleasure","0=Normal, 1=Anhedonia, 2=Complete loss"),
      ("Stress response to pain","0=Normal, 1=Blunted, 2=Catastrophic"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated"),
    ],
    "attn":[
      ("Sustained attention (during pain)","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Attentional bias to pain/body cues","0=None, 1=Mild, 2=Cannot disengage from body"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting to pain stimuli","0=Normal, 1=Delayed, 2=Hypervigilant"),
      ("Disengagement from pain focus","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness (fatigue/insomnia)","0=Normal, 1=Drowsy, 2=Severely fatigued"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS to reduce pain catastrophising / rumination",
    "cen":  "Anodal L-DLPFC tDCS for descending pain modulation",
    "sn":   "taVNS / CES for central sensitisation / insula downregulation",
    "smn":  "Anodal M1 tDCS / TPS FT1 for motor cortex pain modulation",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for affective pain component",
    "attn": "Anodal parietal tDCS for attentional bias reduction",
  },
  "phenotype_options": CB+" Nociceptive  "+CB+" Neuropathic  "+CB+" Nociplastic/central sensitisation  "+CB+" Fibromyalgia  "+CB+" CRPS  "+CB+" Mixed",
},

# ─── 8. PTSD ──────────────────────────────────────────────────────────────────
{
  "slug":"ptsd","display_name":"Post-Traumatic Stress Disorder (PTSD)","short_name":"PTSD",
  "network_relevance":{
    "dmn":  "Trauma-invaded. Trauma-related intrusive memories and flashbacks hijack DMN self-referential processing. Dissociation reflects DMN fragmentation. Peri-traumatic identity disruption persists as DMN reorganisation around trauma narrative.",
    "cen":  "HYPO. Impaired prefrontal executive control over trauma memories prevents extinction of fear responses. Reduced DLPFC activity impairs emotion regulation and inability to contextualise trauma memories as past events.",
    "sn":   "HYPER. PRIMARY NETWORK IN PTSD. Amygdala hyperactivation drives threat hypervigilance. Anterior insula hyperactivity produces interoceptive hyperarousal. dACC hyperactivity maintains the chronic hyperarousal state.",
    "smn":  "Trauma-encoded. Startle responses, muscle tension, freezing/fight/flight motor activations, and motor agitation are SMN hyperactivation signatures. Somatic trauma memories are stored in sensorimotor circuits.",
    "limbic":"HYPER. PRIMARY CO-NETWORK. Amygdala fear conditioning drives all re-experiencing symptoms. Hippocampal contextualisation failure prevents trauma memories from being stored as non-threatening past events.",
    "attn": "Threat-biased. Hypervigilant threat scanning reflects DAN hyperresponsivity to danger cues. VAN over-activation produces exaggerated orienting to trauma-related stimuli. Sustained attention to non-threat is severely impaired.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous trauma-content intrusions in speech","0=None, 1=Occasional, 2=Constant/flashbacks"),
      ("Autobiographical memory (trauma vs pre-trauma)","0=Normal, 1=Trauma dominates, 2=Pre-trauma lost"),
      ("Mind-wandering to trauma content","0=Normal, 1=Occasional, 2=Constant intrusions"),
      ("Dissociation (depersonalisation screen)","0=None, 1=Mild, 2=Severe/derealization"),
      ("Self-awareness and identity coherence","0=Normal, 1=Disrupted, 2=Fragmented identity"),
      ("Future thinking (hopelessness/foreshortened)","0=Normal, 1=Limited, 2=No sense of future"),
      ("Cognitive fluctuations","0=Consistent, 1=Slowed, 2=Flashback-induced disruption"),
    ],
    "cen":[
      ("Serial 7s","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated/prolonged"),
      ("Pain sensitivity","0=Normal, 1=Hypo-dissociated, 2=Hyper/hyperalgesia"),
      ("Interoception (body-threat monitoring)","0=Normal, 1=Absent, 2=Excessive/distressing"),
      ("Emotional reactivity to trauma cue","0=Normal, 1=Numbed, 2=Panic/flashback"),
      ("Task switching (vigilance maintenance)","0=Normal, 1=Slow, 2=Cannot leave threat-focus"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Over-correcting/hypervigilant"),
      ("Autonomic signs (HR, diaphoresis, BP)","0=Normal, 1=Hypo, 2=Hyper/tachycardia"),
    ],
    "smn":[
      ("Startle reflex motor amplitude","0=Normal, 1=Absent, 2=Exaggerated/full body"),
      ("Muscle tension (neck/shoulders)","0=None, 1=Mild, 2=Rigid/painful"),
      ("Breathing pattern (hyperventilation)","0=Normal, 1=Shallow/fast, 2=Hyperventilation"),
      ("Motor agitation / restlessness","0=None, 1=Mild, 2=Cannot sit still"),
      ("Freezing episodes (trauma cue)","0=None, 1=Brief, 2=Prolonged freezing"),
      ("Tremor (anxiety-mediated)","0=Absent, 1=Mild, 2=Visible tremor"),
      ("Avoidance body movements","0=None, 1=Mild, 2=Severe restriction"),
      ("Autonomic motor (flushing/pallor)","0=Normal, 1=Mild, 2=Severe"),
    ],
    "limbic":[
      ("Affect (numbing vs lability)","0=Normal, 1=Numbed/flat, 2=Labile/panicked"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety / hyperarousal screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / social withdrawal","0=Normal, 1=Reduced, 2=Complete isolation"),
      ("Reward sensitivity","0=Normal, 1=Anhedonia, 2=Absent"),
      ("Fear response to trauma cues","0=None, 1=Mild, 2=Severe panic/flashback"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated/rage"),
    ],
    "attn":[
      ("Sustained attention (non-threat tasks)","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Hypervigilant threat scanning","0=None, 1=Mild, 2=Constant/cannot stop"),
      ("Auditory attention (startle to sounds)","0=Normal, 1=Reduced, 2=Hypervigilant"),
      ("Orienting to potential threats","0=Normal, 1=Delayed, 2=Locked onto threat"),
      ("Disengagement from trauma cues","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness (hyperarousal)","0=Normal, 1=Normal, 2=Constant hyperarousal"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Anodal vmPFC tDCS for fear extinction / trauma reconsolidation",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for prefrontal fear regulation",
    "sn":   "taVNS / CES for amygdala/insula hyperactivation (primary)",
    "smn":  "Cathodal SMA tDCS to reduce somatic hyperarousal",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for amygdala fear circuit",
    "attn": "Cathodal rTPJ tDCS to reduce threat attentional bias",
  },
  "phenotype_options": CB+" Re-experiencing dominant  "+CB+" Avoidance dominant  "+CB+" Hyperarousal dominant  "+CB+" Dissociative subtype  "+CB+" Complex PTSD  "+CB+" Military/combat",
},

# ─── 9. OCD ───────────────────────────────────────────────────────────────────
{
  "slug":"ocd","display_name":"Obsessive-Compulsive Disorder (OCD)","short_name":"OCD",
  "network_relevance":{
    "dmn":  "Obsession-invaded. Obsessive rumination, mental rituals, and thought-action fusion hijack DMN self-referential processing. Intrusive ego-dystonic thoughts represent DMN content that cannot be suppressed by prefrontal inhibition.",
    "cen":  "Misdirected. DLPFC is engaged in maintaining and responding to obsessional content rather than adaptive problem-solving. Cognitive inflexibility and inability to shift from obsessional thought reflects aberrant CEN-OFC loops.",
    "sn":   "HYPER. PRIMARY NETWORK IN OCD. dACC error-signal hyperactivity generates the persistent sense that things are not right (just-right perception). Anterior insula hyperactivation drives interoceptive discomfort compelling compulsions.",
    "smn":  "Compulsion-organised. Repetitive motor rituals, compulsive checking movements, motor tics, and avoidance gestures are SMN activations driven by OFC-caudate-thalamic loop hyperactivity.",
    "limbic":"Dysregulated. OFC-caudate-thalamic circuit hyperactivation is the neurobiological hallmark of OCD. Anxiety driving compulsions and brief relief post-compulsion reflect aberrant limbic-striatal reward/punishment signalling.",
    "attn": "HYPER-obsessional. Attention is locked onto obsessional content (threat/contamination/harm) with severe impairment in disengaging. VAN hyperresponsivity drives orienting to obsessional triggers in the environment.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous obsessive content in speech","0=None, 1=Occasional, 2=Constant obsessive themes"),
      ("Intrusive thought frequency (self-report)","0=None, 1=Occasional, 2=Constant"),
      ("Mind-wandering to obsessional topics","0=Normal, 1=Absent, 2=Dominated by obsessions"),
      ("Thought-action fusion tendency","0=None, 1=Mild, 2=Cannot separate thought from action"),
      ("Self-awareness of obsessions as irrational","0=Good insight, 1=Limited, 2=None/overvalued"),
      ("Future thinking (contamination/harm)","0=Normal, 1=Slightly catastrophic, 2=Catastrophic"),
      ("Mental neutralisation rituals observable","0=None, 1=Occasional, 2=Constant during session"),
    ],
    "cen":[
      ("Serial 7s","0=Normal, 1=Slow/errors, 2=Unable due to obsessions"),
      ("Digit span","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting (perseveration)","0=Normal, 1=Perseverative, 2=Unable to shift"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated"),
      ("Disgust / contamination sensitivity","0=Normal, 1=Hypo, 2=Hyper/extreme disgust"),
      ("Interoception (not-right feeling)","0=Normal, 1=Absent, 2=Constant discomfort"),
      ("Emotional reactivity to triggers","0=Normal, 1=Flat, 2=Severe anxiety/urge"),
      ("Task switching away from obsessions","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Error monitoring (over-detection)","0=Normal, 1=Normal, 2=Constant error detection"),
      ("Autonomic signs to triggers","0=Normal, 1=Hypo, 2=Hyper/sympathetic surge"),
    ],
    "smn":[
      ("Compulsive checking movements (observable)","0=None, 1=Occasional, 2=Constant"),
      ("Motor tics (if present)","0=Absent, 1=Occasional, 2=Frequent"),
      ("Ritualistic body movements","0=None, 1=Mild, 2=Severe stereotyped rituals"),
      ("Motor sequencing rigidity in tasks","0=Normal, 1=Rigid, 2=Cannot deviate from ritual"),
      ("Psychomotor slowing (depression comorbidity)","0=Normal, 1=Slow, 2=Severely slow"),
      ("Avoidance movements (contamination)","0=None, 1=Mild, 2=Severe restriction"),
      ("Compulsive ordering/arranging movements","0=None, 1=Occasional, 2=Constant"),
      ("Handwashing / cleaning behaviours","0=Normal, 1=Excessive, 2=Disabling"),
    ],
    "limbic":[
      ("Affect (anxiety vs flat)","0=Normal, 1=Anxious, 2=Severe anxiety/panic"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("OCD-specific anxiety (Y-BOCS estimate)","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / quality of life","0=Normal, 1=Reduced, 2=Absent/housebound"),
      ("Post-compulsion relief (reward signal)","0=No relief, 1=Partial, 2=Full relief (reinforcer)"),
      ("Stress response","0=Normal, 1=Blunted, 2=Hyperactive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated"),
    ],
    "attn":[
      ("Sustained attention (during obsessions)","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Attentional capture by OCD triggers","0=None, 1=Mild, 2=Cannot disengage"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting to OCD triggers in environment","0=Normal, 1=Delayed, 2=Locked-on"),
      ("Disengagement from obsessional focus","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness","0=Normal, 1=Drowsy, 2=Hypervigilant to triggers"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS to reduce obsessive rumination content",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for cognitive flexibility",
    "sn":   "Cathodal dACC / taVNS for error-signal hyperactivity (primary)",
    "smn":  "Cathodal SMA tDCS for compulsive motor urge reduction",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 OFC-caudate circuit",
    "attn": "Cathodal rTPJ tDCS to reduce obsessional attentional bias",
  },
  "phenotype_options": CB+" Contamination  "+CB+" Symmetry/ordering  "+CB+" Harm/checking  "+CB+" Hoarding  "+CB+" Pure obsessional  "+CB+" Treatment-resistant  "+CB+" Tic-related",
},

# ─── 10. MS ───────────────────────────────────────────────────────────────────
{
  "slug":"ms","display_name":"Multiple Sclerosis (MS)","short_name":"MS",
  "network_relevance":{
    "dmn":  "Disrupted by white matter lesion load. DMN hub disconnection causes processing speed reduction and cognitive fatigue episodes. Lesions in PCC/precuneus white matter tracts impair autobiographical and self-referential processing.",
    "cen":  "HYPO. Periventricular and frontal white matter lesions disconnect DLPFC from PPC, causing the hallmark MS cognitive syndrome: reduced processing speed, working memory impairment, and cognitive fatigue.",
    "sn":   "Disrupted. Fatigue-related network switching failure reflects impaired SN function. MS fatigue is partly a SN phenomenon: the network cannot efficiently switch between DMN and task-positive networks under load.",
    "smn":  "PRIMARY NETWORK IN MS. Lesions anywhere along the corticospinal tract produce motor symptoms. Cerebellar lesions produce ataxia; spinal cord lesions produce spasticity. SMN impairment varies by lesion location.",
    "limbic":"Dysregulated. MS depression (50% lifetime prevalence) is the most common psychiatric comorbidity. Emotional lability, pathological laughing/crying, and apathy reflect limbic network demyelination or disconnection.",
    "attn": "HYPO. Symbol Digit Modalities Test (SDMT) impairment is the most sensitive marker of MS cognitive change. DAN disruption produces processing speed decline; divided attention is particularly vulnerable to lesion load.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous self-referential speech","0=Normal, 1=Reduced/slowed, 2=Disorganised"),
      ("Autobiographical memory","0=Normal, 1=Slowed retrieval, 2=Impaired"),
      ("Mind-wandering / cognitive fatigue episodes","0=Normal, 1=Occasional, 2=Frequent lapses"),
      ("Daydreaming / visual phenomena (Uhthoff)","0=Normal, 1=Heat-induced blurring, 2=Visual loss"),
      ("Self-awareness of cognitive change","0=Normal, 1=Mild anosognosia, 2=Severe"),
      ("Future planning","0=Normal, 1=Impaired, 2=Absent"),
      ("Cognitive fluctuations (good/bad days)","0=Consistent, 1=Variable, 2=Severe variability"),
    ],
    "cen":[
      ("Serial 7s / processing speed","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency (COWAT)","0=18+, 1=Reduced <12, 2=Unable"),
      ("Clock drawing","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting / cognitive flexibility","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Unable"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated"),
      ("Pain sensitivity (neuropathic)","0=Normal, 1=Hypo, 2=Hyper/allodynia"),
      ("Interoception","0=Normal, 1=Absent, 2=Distorted"),
      ("Emotional reactivity","0=Normal, 1=Flat, 2=Labile/PLC"),
      ("Task switching under fatigue","0=Normal, 1=Slowed, 2=Cannot switch"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic signs","0=Normal, 1=Hypo, 2=Hyper"),
    ],
    "smn":[
      ("Upper limb weakness (MRC grade)","0=5/5 Normal, 1=3-4/5, 2=0-2/5"),
      ("Lower limb spasticity (Ashworth)","0=None, 1=Mild MAS 1-2, 2=Severe MAS 3-4"),
      ("Coordination (finger-to-nose)","0=Normal, 1=Mild dysmetria, 2=Severe ataxia"),
      ("Gait pattern (ataxic/spastic)","0=Normal, 1=Spastic/ataxic, 2=Requires aid"),
      ("Balance (tandem/Romberg)","0=Normal, 1=Impaired, 2=Cannot perform"),
      ("Fine motor 9HPT (dominant hand)","0=<50s, 1=50-70s, 2=>70s/Unable"),
      ("Babinski sign","0=Absent, 1=Equivocal, 2=Present bilateral"),
      ("Tremor (cerebellar intention)","0=Absent, 1=Mild, 2=Severe/disabling"),
    ],
    "limbic":[
      ("Affect (depression/lability)","0=Normal, 1=Low/flat, 2=Depressed/PLC"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation (fatigue-related apathy)","0=Normal, 1=Reduced, 2=Absent"),
      ("Reward sensitivity","0=Normal, 1=Anhedonia, 2=Absent"),
      ("Stress response","0=Normal, 1=Blunted, 2=Hyperactive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=PLC/severe dysregulation"),
    ],
    "attn":[
      ("SDMT-equivalent (processing speed)","0=Normal >44, 1=Reduced 30-44, 2=<30"),
      ("Sustained attention","0=Normal, 1=Lapses, 2=Unable"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search / scanning","0=Normal, 1=Slow, 2=Cannot complete"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting response","0=Normal, 1=Delayed, 2=Absent"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness (fatigue-related)","0=Normal, 1=Drowsy, 2=Severely fatigued"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal PCC tDCS for fatigue-related DMN dysregulation",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for processing speed",
    "sn":   "taVNS / CES for fatigue and network switching",
    "smn":  "Anodal M1/SMA tDCS / TPS FT1 for motor function",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for MS depression",
    "attn": "Anodal parietal tDCS / TPS FT5 for processing speed",
  },
  "phenotype_options": CB+" RRMS  "+CB+" SPMS  "+CB+" PPMS  "+CB+" Fatigue-predominant  "+CB+" Cognitive-predominant  "+CB+" Motor/spastic  "+CB+" Cerebellar",
},

# ─── 11. ASD ──────────────────────────────────────────────────────────────────
{
  "slug":"asd","display_name":"Autism Spectrum Disorder (ASD)","short_name":"ASD",
  "network_relevance":{
    "dmn":  "Atypical social mentalizing. Theory of mind, mentalizing, and social cognition — core DMN functions — are fundamentally different in ASD. mPFC-PCC connectivity is atypical, impairing self-other distinction and social prediction.",
    "cen":  "Variable. Executive dysfunction is present in many individuals with ASD. Cognitive rigidity (insistence on sameness) reflects CEN inflexibility. Working memory may be preserved for rote material but impaired for social/contextual content.",
    "sn":   "Atypical social salience. Social stimuli are not automatically detected as salient. Anterior insula differences produce atypical interoceptive processing. Sensory filtering differences reflect altered SN gating of sensory input.",
    "smn":  "Atypical motor. Motor stereotypies, coordination difficulties, motor planning difficulties (developmental coordination disorder overlap), and unusual gait patterns reflect atypical SMN organisation and cortico-cerebellar connectivity.",
    "limbic":"Atypical emotional processing. Amygdala hyperreactivity to social stimuli may drive social anxiety. Interoceptive differences produce alexithymia. Sensory sensitivities reflect atypical limbic-sensory integration.",
    "attn": "Atypical profile. Hyper-focus on restricted interests contrasts with impaired shifting to other stimuli. Over-selective attention to detail (local processing bias) reflects atypical DAN/VAN organisation in ASD.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous self-referential speech","0=Normal, 1=Absent/monotone, 2=Excessive/scripted"),
      ("Theory of mind (false belief estimate)","0=Normal, 1=Impaired, 2=Unable"),
      ("Mind-wandering (restricted interests)","0=Normal, 1=Absent, 2=Fixed on restricted interest"),
      ("Self-other distinction in conversation","0=Normal, 1=Reduced, 2=Unable to perspective-take"),
      ("Self-awareness of ASD traits","0=Good insight, 1=Limited, 2=Absent"),
      ("Future thinking / planning","0=Normal, 1=Rigid/routine-bound, 2=Cannot plan flexibly"),
      ("Social narrative coherence","0=Normal, 1=Tangential, 2=Incoherent/monologue"),
    ],
    "cen":[
      ("Serial 7s / mental calculation","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting / cognitive flexibility","0=Normal, 1=Perseverative/rigid, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Blunted, 2=Exaggerated/prolonged"),
      ("Sensory sensitivity (pain/touch)","0=Normal, 1=Hypo, 2=Hyper/allodynia"),
      ("Interoception (bodily awareness)","0=Normal, 1=Absent/alexithymia, 2=Distorted"),
      ("Social emotional reactivity","0=Normal, 1=Flat/alexithymic, 2=Overwhelmed"),
      ("Task switching (restricted interests)","0=Normal, 1=Slow, 2=Cannot switch off interest"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic response to social stimuli","0=Normal, 1=Hypo, 2=Hyper/shutdown"),
    ],
    "smn":[
      ("Motor stereotypies (stimming)","0=Absent, 1=Mild/infrequent, 2=Constant/disruptive"),
      ("Coordination (finger-to-nose)","0=Normal, 1=Mild impairment, 2=Dyspraxia"),
      ("Fine motor (tapping/writing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Motor planning (novel sequences)","0=Normal, 1=Slow, 2=Severely impaired"),
      ("Postural control / balance","0=Normal, 1=Mildly impaired, 2=Significantly impaired"),
      ("Gait pattern observation","0=Normal, 1=Unusual pattern, 2=Significantly atypical"),
      ("Motor imitation","0=Normal, 1=Delayed/impaired, 2=Cannot imitate"),
      ("Body awareness (proprioception)","0=Normal, 1=Impaired, 2=Seeking"),
    ],
    "limbic":[
      ("Affect (flat vs overwhelmed)","0=Normal, 1=Flat/alexithymic, 2=Overwhelmed/meltdown"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation for social interaction","0=Normal, 1=Reduced, 2=Avoidant"),
      ("Reward sensitivity (interests vs social)","0=Balanced, 1=Restricted interest only, 2=Social completely absent"),
      ("Stress response to routine change","0=Normal, 1=Distress, 2=Meltdown/shutdown"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Meltdown/shutdown"),
    ],
    "attn":[
      ("Sustained attention (preferred topic)","0=Normal, 1=Normal, 2=Hyperfocused/cannot stop"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search (local vs global)","0=Balanced, 1=Local bias, 2=Cannot globalise"),
      ("Auditory attention (filtering noise)","0=Normal, 1=Reduced, 2=Hypersensitive"),
      ("Orienting to social stimuli","0=Normal, 1=Reduced, 2=Absent"),
      ("Disengagement from restricted interest","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness variability","0=Normal, 1=Variable, 2=Extreme over/under-arousal"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Anodal mPFC/temporal tDCS for social mentalizing support",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for cognitive flexibility",
    "sn":   "taVNS / CES for sensory sensitivity normalisation",
    "smn":  "Cathodal SMA tDCS for stereotypy reduction",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for anxiety/regulation",
    "attn": "Anodal parietal tDCS for attention flexibility / TPS FT5",
  },
  "phenotype_options": CB+" Social communication dominant  "+CB+" Restricted/repetitive dominant  "+CB+" Language delay  "+CB+" Sensory processing  "+CB+" Executive dysfunction  "+CB+" ADHD comorbidity",
},

# ─── 12. LONG COVID ───────────────────────────────────────────────────────────
{
  "slug":"long_covid","display_name":"Long COVID (Post-Acute Sequelae of SARS-CoV-2)","short_name":"Long COVID",
  "network_relevance":{
    "dmn":  "HYPO. Brain fog is characterised by mPFC-PCC disconnection and impaired default mode processing. Concentration lapses, word-finding difficulties, and loss of identity/motivation reflect chronic DMN hypoperfusion and neuroinflammatory disruption.",
    "cen":  "HYPO. Executive function impairment, reduced working memory, and cognitive fatigue reflect DLPFC hypometabolism and neuroinflammatory CEN disruption. SDMT and processing speed tasks are most sensitive to Long COVID CEN impairment.",
    "sn":   "Dysregulated. Autonomic dysregulation (POTS, orthostatic intolerance) is a primary Long COVID manifestation reflecting SN-ANS axis dysfunction. Post-exertional malaise (PEM) may involve SN hyperexcitability to metabolic signals.",
    "smn":  "HYPO-fatigued. Exercise intolerance, fatigue-related motor decline, reduced grip strength, and post-exertional motor deterioration reflect SMN vulnerability to energy depletion. Gait endurance is limited by PEM threshold.",
    "limbic":"Dysregulated. Mood disturbance (depression, anxiety), emotional lability, and loss of motivation are highly prevalent in Long COVID. Neuroinflammatory effects on limbic circuits and HPA axis dysregulation drive these symptoms.",
    "attn": "HYPO. Sustained attention impairment and inability to maintain concentration are core brain fog symptoms. DAN disruption reflects reduced cortical activation capacity. Fatigue-related attention failures worsen with exertion.",
  },
  "network_tests":{
    "dmn":[
      ("Spontaneous self-referential speech","0=Normal, 1=Reduced/effortful, 2=Word-finding failures"),
      ("Autobiographical memory (pre/post COVID)","0=Normal, 1=Post-COVID gap, 2=Significant impairment"),
      ("Mind-wandering / concentration lapses","0=Normal, 1=Occasional, 2=Constant brain fog"),
      ("Motivation and identity loss","0=Normal, 1=Reduced, 2=Profound identity/motivation loss"),
      ("Self-awareness of cognitive change","0=Normal, 1=Limited, 2=Absent"),
      ("Future thinking / planning","0=Normal, 1=Impaired, 2=Cannot plan"),
      ("Cognitive fluctuations (good/bad days)","0=Consistent, 1=Variable, 2=Severe variability"),
    ],
    "cen":[
      ("Serial 7s / processing speed","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span (forward & backward)","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Clock drawing","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated"),
      ("Interoceptive awareness (dysautonomia)","0=Normal, 1=Absent, 2=Excessive/distressing"),
      ("Emotional reactivity","0=Normal, 1=Flat/blunted, 2=Labile"),
      ("Task switching","0=Normal, 1=Slow, 2=Cognitively exhausting"),
      ("POTS screen (symptom report)","0=None, 1=Mild orthostatic sx, 2=Severe POTS symptoms"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic signs (HR standing, sweating)","0=Normal, 1=Hypo, 2=Hyper/tachycardia"),
    ],
    "smn":[
      ("Exercise tolerance (1-min STS test)","0=Normal, 1=Reduced, 2=Unable due to PEM"),
      ("Gait endurance (6MWT estimate)","0=>400m, 1=200-400m, 2=<200m"),
      ("Fine motor speed (tapping)","0=Normal, 1=Slow, 2=Severely slowed"),
      ("Coordination (finger-to-nose)","0=Normal, 1=Mild impairment, 2=Dysmetria"),
      ("Grip strength (dynamometer)","0=Normal, 1=Reduced, 2=Severely reduced"),
      ("Postural orthostatic stability","0=Normal, 1=Mild unsteady standing, 2=Cannot stand >1 min"),
      ("Balance (Romberg)","0=Normal, 1=Mild sway, 2=Falls"),
      ("Post-exertional motor decline","0=None, 1=Mild, 2=Severe PEM crash"),
    ],
    "limbic":[
      ("Affect (depression/flat)","0=Normal, 1=Low/flat, 2=Severely depressed"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / anhedonia","0=Normal, 1=Reduced, 2=Absent"),
      ("Reward sensitivity","0=Normal, 1=Anhedonia, 2=Complete loss"),
      ("Stress response (PEM trigger)","0=Normal, 1=Blunted, 2=PEM crash after stress"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Severely dysregulated"),
    ],
    "attn":[
      ("Sustained attention (brain fog)","0=Normal, 1=Lapses, 2=Cannot sustain >5 min"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Visual search / scanning","0=Normal, 1=Slow, 2=Cannot complete"),
      ("Auditory attention","0=Normal, 1=Reduced, 2=Unable"),
      ("Orienting response","0=Normal, 1=Delayed, 2=Absent"),
      ("Reorienting after distraction","0=Normal, 1=Slow, 2=Cannot refocus"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness (fatigue-related)","0=Normal, 1=Drowsy, 2=Severely fatigued"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Anodal mPFC tDCS for brain fog / motivation restoration",
    "cen":  "Anodal L-DLPFC tDCS / TPS FT3 for processing speed",
    "sn":   "taVNS for ANS normalisation / POTS management",
    "smn":  "Gentle anodal M1 tDCS for fatigue-related motor decline",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for mood",
    "attn": "Anodal parietal tDCS / TPS FT5 for sustained attention",
  },
  "phenotype_options": CB+" Cognitive fog dominant  "+CB+" Fatigue/PEM dominant  "+CB+" Dysautonomia  "+CB+" Neuropsychiatric  "+CB+" Headache/pain  "+CB+" Multi-system",
},

# ─── 13. TINNITUS ─────────────────────────────────────────────────────────────
{
  "slug":"tinnitus","display_name":"Tinnitus","short_name":"Tinnitus",
  "network_relevance":{
    "dmn":  "Tinnitus awareness intrusion. Chronic tinnitus hijacks DMN self-referential processing: the sound becomes part of default self-awareness. mPFC hyperactivation to tinnitus-related self-referential cognitions maintains tinnitus distress.",
    "cen":  "Effortful suppression. CEN is recruited for effortful attention control to suppress tinnitus awareness. This depletes working memory capacity and contributes to concentration impairment and cognitive fatigue in tinnitus sufferers.",
    "sn":   "HYPER. PRIMARY NETWORK IN TINNITUS. Auditory salience overamplification via anterior insula and dACC prevents habituation. The SN flags tinnitus as a significant threat, maintaining emotional distress and preventing acoustic desensitisation.",
    "smn":  "Somatic component. Jaw (TMJ) and cervical muscle tension contribute to somatic tinnitus. Auditory-motor integration differences are found in tinnitus. Somatic modulation tests reveal SMN involvement in tinnitus generation.",
    "limbic":"Dysregulated. Tinnitus distress, fear/distress response to tinnitus, depression, and anxiety comorbidity reflect limbic network involvement. Amygdala hyperactivation to the tinnitus signal drives the emotional suffering component.",
    "attn": "Captured. Attentional capture by tinnitus reflects DAN hyperresponsivity to the internal auditory stimulus. VAN over-activation produces automatic orienting to tinnitus. Disengagement from tinnitus attention is a key treatment target.",
  },
  "network_tests":{
    "dmn":[
      ("Tinnitus as self-referential thought content","0=None, 1=Occasional awareness, 2=Dominates self-awareness"),
      ("Autobiographical impact of tinnitus on life narrative","0=Minimal, 1=Significant, 2=Identity consumed by tinnitus"),
      ("Mind-wandering to tinnitus-related concerns","0=Normal, 1=Occasional, 2=Constant tinnitus focus"),
      ("Daydreaming / distraction by tinnitus","0=Normal, 1=Occasional, 2=Constant"),
      ("Self-awareness of tinnitus emotional impact","0=Good insight, 1=Limited, 2=Catastrophising"),
      ("Future thinking (catastrophic re tinnitus)","0=Normal, 1=Mildly negative, 2=Catastrophic"),
      ("Identity disruption from tinnitus","0=None, 1=Mild, 2=Severe identity disruption"),
    ],
    "cen":[
      ("Serial 7s","0=Normal, 1=Slow/errors, 2=Unable"),
      ("Digit span","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Auditory startle (to unexpected sound)","0=Normal, 1=Absent, 2=Exaggerated/hyperacusis"),
      ("Loudness discomfort / hyperacusis","0=Normal LDL, 1=Mildly reduced, 2=Severe hyperacusis"),
      ("Interoception (tinnitus body response)","0=Normal, 1=Absent, 2=Excessive distress"),
      ("Emotional reactivity to tinnitus discussion","0=Normal, 1=Distressed, 2=Severe distress"),
      ("Task switching from tinnitus focus","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Absent"),
      ("Autonomic signs during tinnitus awareness","0=Normal, 1=Hypo, 2=Hyper/tachycardia"),
    ],
    "smn":[
      ("TMJ palpation (jaw tension)","0=None, 1=Mild, 2=Severe/painful"),
      ("Cervical muscle tension (suboccipital)","0=None, 1=Mild, 2=Severe"),
      ("Head posture observation","0=Normal, 1=Forward head, 2=Severe postural fault"),
      ("Somatic modulation test (jaw movement)","0=No change, 1=Mild modulation, 2=Clear modulation"),
      ("Somatic modulation test (neck rotation)","0=No change, 1=Mild modulation, 2=Clear modulation"),
      ("Balance (Romberg)","0=Normal, 1=Mild sway, 2=Falls"),
      ("Oculomotor exam (smooth pursuit)","0=Normal, 1=Saccadic, 2=Cannot track"),
      ("Auditory-motor integration (listening + tapping)","0=Normal, 1=Impaired, 2=Unable"),
    ],
    "limbic":[
      ("Affect (tinnitus distress)","0=Normal, 1=Distressed, 2=Severely distressed"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / quality of life","0=Normal, 1=Reduced, 2=Housebound/isolated"),
      ("Fear of tinnitus worsening","0=None, 1=Mild, 2=Catastrophic fear"),
      ("Stress response (tinnitus loudness spike)","0=Normal, 1=Blunted, 2=Hyperactive"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Severely dysregulated"),
    ],
    "attn":[
      ("Sustained attention (during tinnitus)","0=Normal, 1=Lapses, 2=Cannot sustain"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Attentional capture by tinnitus","0=None, 1=Mild, 2=Cannot focus on anything else"),
      ("Auditory attention selectivity","0=Normal, 1=Tinnitus intrudes, 2=Cannot filter"),
      ("Orienting to tinnitus variations","0=Normal, 1=Delayed, 2=Hypervigilant"),
      ("Disengagement from tinnitus attention","0=Normal, 1=Slow, 2=Cannot disengage"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness (sleep-deprived from tinnitus)","0=Normal, 1=Drowsy, 2=Severely fatigued"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS to reduce tinnitus self-referential intrusion",
    "cen":  "Anodal L-DLPFC tDCS for attentional control over tinnitus",
    "sn":   "Cathodal auditory cortex / taVNS for salience normalisation (primary)",
    "smn":  "Cathodal M1/temporal tDCS for somatic tinnitus component",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for tinnitus distress",
    "attn": "Cathodal auditory cortex tDCS for attentional capture reduction",
  },
  "phenotype_options": CB+" Tonal  "+CB+" Noise-like  "+CB+" Pulsatile  "+CB+" Reactive tinnitus  "+CB+" Somatic/somatosensory  "+CB+" With hyperacusis  "+CB+" With misophonia",
},

# ─── 14. INSOMNIA ─────────────────────────────────────────────────────────────
{
  "slug":"insomnia","display_name":"Insomnia Disorder","short_name":"Insomnia",
  "network_relevance":{
    "dmn":  "HYPER at bedtime. Pre-sleep rumination and worry loops drive mPFC hyperactivation when attempting sleep. Racing thoughts represent failure to deactivate the DMN, preventing the cortical downscaling required for sleep onset.",
    "cen":  "Hyperactivated pre-sleep. Unlike most conditions where CEN is hypo-active, in insomnia both CEN and DMN are co-activated at bedtime. This cortical hyperarousal prevents the transition from wake to sleep-onset EEG activity.",
    "sn":   "HYPER. PRIMARY NETWORK IN INSOMNIA. Hyperarousal is the core insomnia mechanism. Anterior insula and dACC maintain wakefulness via threat monitoring of the sleep environment. Conditioned arousal reflects SN sensitisation to bedroom cues.",
    "smn":  "Tension-held. Chronic muscle tension, jaw clenching, restless leg sensations, and somatic arousal at bedtime reflect SMN activation preventing sleep-state motor relaxation. Body-scan reveals inability to achieve motor stillness.",
    "limbic":"HYPER. Sleep anxiety, fear of sleeplessness, and conditioned arousal reflect amygdala hyperactivation to sleep-related cues. OFC-mediated safety learning is impaired, perpetuating the bed-as-threat association.",
    "attn": "Hypervigilant self-monitoring. DAN and VAN are co-activated in insomnia: hypervigilant monitoring of sleep-related internal sensations (ticking clock, own heartbeat, tinnitus) prevents sleep. Reduced sleep perception accuracy (paradoxical insomnia).",
  },
  "network_tests":{
    "dmn":[
      ("Pre-sleep ruminative thought content","0=None, 1=Mild, 2=Constant/uncontrollable"),
      ("Sleep-related autobiographical worry","0=None, 1=Occasional, 2=Dominant sleep narrative"),
      ("Mind-wandering type at bedtime","0=Normal, 1=Absent, 2=Racing thoughts"),
      ("Daydreaming / sleep-state confusion","0=Normal, 1=Occasional, 2=Cannot distinguish sleep/wake"),
      ("Self-awareness of hyperarousal","0=Good insight, 1=Limited, 2=None/paradoxical"),
      ("Future thinking (catastrophising re sleep)","0=Normal, 1=Slightly negative, 2=Catastrophic"),
      ("Narrative coherence about insomnia","0=Normal, 1=Fragmented, 2=Catastrophic narrative"),
    ],
    "cen":[
      ("Serial 7s / mental calculation","0=Normal, 1=Slow (fatigue), 2=Unable"),
      ("Digit span","0=Normal, 1=Reduced, 2=Unable"),
      ("Trail Making A to B","0=Normal, 1=Slow, 2=Unable"),
      ("Verbal fluency","0=18+, 1=Reduced <12, 2=Unable"),
      ("Planning (clock drawing)","0=Normal, 1=Impaired, 2=Unable"),
      ("Set shifting","0=Normal, 1=Perseverative, 2=Unable"),
      ("Dual-task (walk + count)","0=Normal, 1=Impaired, 2=Cannot dual-task"),
    ],
    "sn":[
      ("Startle response","0=Normal, 1=Absent, 2=Exaggerated"),
      ("Pain / discomfort sensitivity","0=Normal, 1=Hypo, 2=Hyper/hyperalgesia"),
      ("Interoception (heartbeat/body awareness)","0=Normal, 1=Absent, 2=Excessive monitoring"),
      ("Emotional reactivity to sleep discussion","0=Normal, 1=Flat, 2=Anxious/distressed"),
      ("Task switching at end of day","0=Normal, 1=Slow wind-down, 2=Cannot switch off"),
      ("Error monitoring","0=Normal, 1=Reduced, 2=Over-monitoring"),
      ("Autonomic signs (HR, temp, sweating)","0=Normal, 1=Hypo, 2=Hyper/hot/sweaty at night"),
    ],
    "smn":[
      ("Muscle tension neck/shoulders","0=None, 1=Mild, 2=Severe/rigid at bedtime"),
      ("Jaw clenching / bruxism","0=Absent, 1=Mild, 2=Severe"),
      ("Restless legs / limb movements","0=Absent, 1=Mild, 2=Severe/PLM"),
      ("Motor agitation at bedtime","0=None, 1=Mild, 2=Cannot lie still"),
      ("Breathing pattern (pre-sleep)","0=Normal, 1=Slightly irregular, 2=Hyperventilation"),
      ("Heart rate variability signs","0=Normal, 1=Reduced, 2=Tachycardia at bedtime"),
      ("Postural tension (body scan)","0=Relaxed, 1=Tense, 2=Rigid throughout"),
      ("Fatigue signs (motor slowing by day)","0=None, 1=Mild, 2=Severe daytime motor slowing"),
    ],
    "limbic":[
      ("Affect (sleep anxiety)","0=Normal, 1=Anxious re sleep, 2=Panic at bedtime"),
      ("Mood screening","0=Normal, 1=Low, 2=Severe depression"),
      ("Anxiety screening","0=Normal, 1=Mild, 2=Severe"),
      ("Motivation / daytime functioning","0=Normal, 1=Reduced, 2=Cannot function"),
      ("Conditioned arousal to bed/bedroom","0=None, 1=Mild, 2=Dread/avoidance of bed"),
      ("Stress response to sleep failure","0=Normal, 1=Blunted, 2=Catastrophic"),
      ("Emotional regulation","0=Normal, 1=Poor, 2=Dysregulated"),
    ],
    "attn":[
      ("Sustained attention (daytime)","0=Normal, 1=Lapses, 2=Cannot sustain"),
      ("Selective attention (Stroop)","0=Normal, 1=Slow, 2=Unable"),
      ("Hypervigilant self-monitoring at night","0=None, 1=Mild, 2=Constant body/clock monitoring"),
      ("Auditory hypervigilance at night","0=Normal, 1=Mild, 2=Wakes to any sound"),
      ("Orienting to sleep-related cues","0=Normal, 1=Delayed, 2=Hypervigilant"),
      ("Daytime disengagement from sleep worry","0=Normal, 1=Slow, 2=Cannot stop thinking about sleep"),
      ("Divided attention","0=Normal, 1=Impaired, 2=Unable"),
      ("Alertness / daytime sleepiness","0=Normal, 1=Drowsy, 2=Severely sleepy"),
    ],
  },
  "nibs_targets":{
    "dmn":  "Cathodal mPFC tDCS to suppress pre-sleep ruminative DMN",
    "cen":  "Cathodal DLPFC at bedtime to reduce cortical hyperarousal",
    "sn":   "taVNS / CES for hyperarousal and conditioned SN arousal (primary)",
    "smn":  "Cathodal SMA tDCS for somatic/motor tension at bedtime",
    "limbic":"taVNS / Bifrontal tDCS / TPS FT4 for sleep anxiety",
    "attn": "Cathodal right parietal tDCS for hypervigilant self-monitoring",
  },
  "phenotype_options": CB+" Sleep-onset  "+CB+" Sleep-maintenance  "+CB+" Early-morning awakening  "+CB+" Hyperarousal-predominant  "+CB+" Comorbid psychiatric  "+CB+" Paradoxical insomnia",
},

]