"""
All 15-condition protocol data for the FELLOW ALL-IN-ONE document.
Each entry defines TPS (T1-T5), tDCS HDCkit (C1-C8), PlatoScience (C1-PS to C8-PS),
Multimodal (F1-F9), and safety specifics.
"""

# ── Shared device notes ──────────────────────────────────────────────────────
TPS_WARNING_TEMPLATE = (
    "WARNING  TPS use in {condition} is INVESTIGATIONAL / OFF-LABEL in most jurisdictions.\n"
    "NEUROLITH® is CE-marked for musculoskeletal indications. Use in neurological / psychiatric "
    "conditions is supported by emerging clinical evidence only. Patient informed consent is "
    "mandatory. This protocol is for use by qualified SOZO clinicians under Doctor supervision only."
)

TPS_NOTE = (
    "NOTE  Device: NEUROLITH® (Storz Medical). Neurons targeted via ultrasound pulse propagation. "
    "Scalp maps show approximate ROI; actual depth/spread depends on transducer angle and "
    "patient anatomy. Doctor configures pulse count, frequency (Hz) and energy density (mJ/mm²)."
)

HDCKIT_NOTE = (
    "NOTE  Device: Newronika HDCkit (CE Class IIa, CE 0476) — 2-channel anodal tDCS system. "
    "Doctor programs via HDCprog; patient cannot modify. All protocols prescribe 2 mA unless "
    "noted. Ramp up/down: 30 s. Electrodes: 25 cm² (5×5 cm) saline-soaked sponge pads."
)

PLATOSCIENCE_DEVICE = {
    "headers": ["Device", "Specification"],
    "rows": [
        ["PlatoWork Headset", "Single-channel tDCS · Max 1.6 mA (clinical 1.2–1.6 mA)"],
        ["Placement Variants", "Multiple snap-in positions — see protocol for Variant"],
        ["Constraint", "Single-channel ONLY. Dual-channel montages not available on PlatoScience."],
        ["Session Duration", "20 min (fixed). Ramp-up 30 s, ramp-down 30 s."],
    ],
}

HOME_NOTE = (
    "NOTE  Home-based treatment prescribed by SOZO Brain Center Doctor ONLY. "
    "Patients must complete supervised in-clinic baseline before home programme. "
    "Follow-up call within 48 hours of first home session."
)

# ── SOZO Sequencing ──────────────────────────────────────────────────────────
SOZO_SEQUENCE_HEADER = ["S — Stabilize", "O — Optimize", "Z — Zone Target", "O — Outcome"]
SOZO_SEQUENCE_GENERIC = [
    "taVNS or CES  10–15 min\nDownshift sympathetic tone, reduce cortical noise",
    "tDCS  15–20 min\nPrime target networks for stimulation",
    "TPS (ROI + holocranial)  20–30 min\nDeep network modulation at target ROI",
    "taVNS/CES + rehab tasks  30–45 min\nPost-stimulation neuroplasticity window",
]

EVIDENCE_LEVELS = [
    ["Moderate adjunctive", "Supported by systematic reviews and/or multiple RCTs as combination therapy"],
    ["Emerging / low-certainty", "Feasibility data and plausible mechanism; no large RCTs"],
    ["Weak / supportive only", "Indirect evidence only; should not be first-line standalone"],
]

# ── SAFETY (shared base + condition specifics) ───────────────────────────────
SAFETY_SIDE_EFFECTS = [
    ["Tingling / itching", "tDCS · taVNS", "Common (40–70%)", "Reassure; check electrode contact"],
    ["Headache", "tDCS · TPS · taVNS", "Uncommon (5–15%)", "Reduce intensity; hydration; paracetamol PRN"],
    ["Skin redness", "tDCS", "Common at electrode site", "Inspect post-session; petroleum jelly barrier"],
    ["Transient phosphenes", "tDCS (frontal)", "Uncommon", "Reposition electrodes; avoid OFC montages"],
    ["Ear discomfort", "taVNS", "Common", "Adjust clip; reduce current; take break"],
    ["Drowsiness", "CES · taVNS", "Common", "Allow rest post-session; do not drive"],
]

ADVERSE_GRADING = [
    ["Grade 1 (Mild)", "Self-resolving within 30 min", "Continue; document; monitor"],
    ["Grade 2 (Moderate)", "Persists > 30 min or recurs", "Pause session; reassess next visit"],
    ["Grade 3 (Severe)", "Requires medical attention", "STOP; escalate to Doctor; incident report"],
    ["Seizure / LOC", "Any seizure or loss of consciousness", "STOP ALL; emergency services; Doctor immediately"],
]

CONTRAINDICATIONS_BASE = [
    ["Metal implants (cranial)", "All modalities", "ABSOLUTE"],
    ["Implanted cardiac device (pacemaker/ICD)", "All modalities", "ABSOLUTE — consult cardiologist"],
    ["Active epilepsy (uncontrolled)", "All modalities", "ABSOLUTE"],
    ["Pregnancy", "TPS · tDCS (frontal)", "RELATIVE — Doctor decision"],
    ["Open scalp wounds / skin breakdown", "tDCS · TPS", "ABSOLUTE at affected site"],
    ["Recent neurosurgery < 6 months", "TPS", "ABSOLUTE"],
]

# ═══════════════════════════════════════════════════════════════════════════════
# CONDITION DATA
# Each condition dict has:
#   display_name, icd10, short_name,
#   tps_warning (optional override),
#   tps: [T1..T5] each = {code, symptom, evidence, targets[], params_text, rationale}
#   tdcs: [C1..C8] each = {code, symptom, anodes[], cathodes[], params_text, rationale}
#   plato: [C1-PS..C8-PS] each = {code, symptom, anodes[], cathodes[], params_text, variant_note}
#   phenotypes: [F1..F9] each = {code, name, sozo_seq[], tps_combos[], nontps_combos[], rationale}
#   contraindications_extra: list of [category, modality, type]
#   key_outcome_measures: str
# ═══════════════════════════════════════════════════════════════════════════════


# TPS Evidence Summary (from Consensus.app CSV, 2026-04-04)
# Conditions with explicit T1-T5 dicts above have inline evidence updates.
# Standard conditions (_make_standard_condition) TPS paper counts:
#   adhd: 11 papers, 7 HQ (emerging) | top DOIs: 10.3389/fneur.2024.1364270, 10.3389/fneur.2024.1364270
#   alzheimers: 80 papers, 19 HQ (strong) | top DOIs: 10.3390/neurolint17110188, 10.3390/neurolint17110188
#   stroke_rehab: 59 papers, 4 HQ (emerging) | top DOIs: 10.1177/02692155251328945, 10.1186/s40001-023-01525-5
#   tbi: 22 papers, 4 HQ (emerging) | top DOIs: 10.3390/brainsci12040429, 10.3390/brainsci12040429
#   chronic_pain: 27 papers, 4 HQ (emerging) | top DOIs: 10.1007/s13534-024-00369-0, 10.1080/17434440.2019.1567325
#   ptsd: 21 papers, 0 HQ (none) | top DOIs: 10.1109/embc46164.2021.9630415, 10.1109/embc46164.2021.9630415
#   ocd: 18 papers, 1 HQ (preliminary) | top DOIs: 10.1001/jamaneurol.2017.3129, 10.1016/j.neurom.2024.03.004
#   ms: 5 papers, 2 HQ (preliminary) | top DOIs: 10.1177/1545968317753681, 10.1177/1545968317753681
#   asd: 17 papers, 14 HQ (strong) | top DOIs: 10.3390/neurolint17110188, 10.3390/neurolint17110188
#   long_covid: 0 papers, 0 HQ (none) | top DOIs: none
#   tinnitus: 48 papers, 25 HQ (strong) | top DOIs: 10.1016/j.neubiorev.2015.05.017, 10.1016/j.neubiorev.2015.05.017
#   insomnia: 4 papers, 0 HQ (none) | top DOIs: 10.3390/jcm11133809, 10.1016/j.brs.2015.01.263
CONDITIONS = {}

# ── 1. PARKINSON'S DISEASE ───────────────────────────────────────────────────
CONDITIONS["parkinsons"] = {
    "display_name": "Parkinson's Disease",
    "icd10": "G20",
    "short_name": "PD",
    "tps_evidence": {
        "regulatory_status": "Investigational (CE research use)",
        "evidence_level": "Open-label, Pilot RCT (2025)",
        "literature_count": "9+",
        "key_references": "Osou 2023 J Neurol (n=20, 20 citations); RCT 2025 – TPS Enhances Dexterity in PD (sham-controlled); EEG cortical oscillatory changes 2025; SA Perspective Brain Stimulation 2025",
        "side_effects": "Transient headache, dizziness, fatigue. Generally well tolerated.",
        "notes": "9 papers (2021–2026). First sham-controlled RCT confirms dexterity improvement (2025). EEG oscillatory changes documented. Foot+brain combined protocol (10,000 pulses).",
    },
    "tps_regulatory_note": "Investigational (off-label) — 9+ published papers; first sham-controlled RCT 2025.",
    "tps_warning": TPS_WARNING_TEMPLATE.format(condition="Parkinson's Disease"),
    "tps": [
        {"code": "T1", "symptom": "Motor: Bradykinesia & Rigidity", "evidence": "Emerging — preclinical/observational only",
         "targets": ["C3", "C4", "FCz"], "tps": True,
         "params_text": "TPS: Bilateral M1 + SMA · 10,000 pulses (8000 brain + 2000 foot) · 4 Hz PRF · EFD 0.25 mJ/mm² · 12 sessions / 4 weeks",
         "rationale": "M1 bilateral targeting reduces motor cortex hyperexcitability; SMA involvement supports initiation circuits."},
        {"code": "T2", "symptom": "Tremor", "evidence": "Emerging — preclinical/observational only",
         "targets": ["C3", "C4", "Cz"], "tps": True,
         "params_text": "TPS: Bilateral M1 + Cerebellum · 10,000 pulses · 4 Hz PRF · EFD 0.25 mJ/mm²",
         "rationale": "Cerebellar-thalamic-cortical loop modulation reduces tremor amplitude."},
        {"code": "T3", "symptom": "Cognition: PD-MCI", "evidence": "Preliminary — case series only",
         "targets": ["F3", "F4", "P3"], "tps": True,
         "params_text": "TPS: L-DLPFC + bilateral PPC · 10,000 pulses · 4 Hz PRF · EFD 0.25 mJ/mm²",
         "rationale": "DLPFC facilitates working memory; PPC supports spatial-attentional integration."},
        {"code": "T4", "symptom": "Depression & Apathy", "evidence": "Emerging Pilot — 0 pilot RCTs",
         "targets": ["F3", "F4"], "tps": True,
         "params_text": "TPS: Bilateral DLPFC · 10,000 pulses · 4 Hz PRF · EFD 0.25 mJ/mm²",
         "rationale": "DLPFC modulation targets affective circuits implicated in PD depression."},
        {"code": "T5", "symptom": "Pain & Dyskinesia", "evidence": "Experimental — 0 studies",
         "targets": ["C3", "C4", "Cb1", "Cbz", "Cb2"], "tps": True,
         "params_text": "TPS: M1 + Cerebellum · 10,000 pulses · 4 Hz PRF · EFD 0.25 mJ/mm²",
         "rationale": "Cerebellar stimulation modulates dopamine-independent motor loop; M1 for pain gate."},
    ],
    "tdcs": [
        {"code": "C1", "symptom": "Motor (Bradykinesia & Rigidity)",
         "anodes": ["C3", "C4"], "cathodes": ["Fp1", "Fp2"],
         "params_text": "2 mA · 20–30 min | Bilateral M1 (C3+C4) → supraorbital cathode",
         "rationale": "Bilateral anodal M1 tDCS enhances motor cortex excitability and reduces bradykinesia severity."},
        {"code": "C2", "symptom": "Gait & Dual-Task Performance",
         "anodes": ["F3", "Cz"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 20–40 min | Combine with treadmill",
         "rationale": "Left DLPFC + SMA priming improves gait initiation and dual-task cognitive-motor coupling."},
        {"code": "C3", "symptom": "Cognition & Executive Function",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 20 min | L-DLPFC (F3) → contralateral supraorbital",
         "rationale": "L-DLPFC anodal tDCS enhances working memory and executive control in PD-MCI."},
        {"code": "C4", "symptom": "Depression & Mood (Apathy)",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params_text": "2 mA · 20–30 min | L-DLPFC anode, R-DLPFC cathode",
         "rationale": "Left prefrontal facilitation with right inhibition mirrors rTMS antidepressant montage."},
        {"code": "C5", "symptom": "Fatigue",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params_text": "2 mA · 20 min | Bilateral DLPFC → occipital cathode",
         "rationale": "Bilateral prefrontal engagement reduces central fatigue via corticothalamic upregulation."},
        {"code": "C6", "symptom": "Balance & Posture",
         "anodes": ["Cz", "C3", "C4"], "cathodes": ["Fp1"],
         "params_text": "2 mA · 20–40 min | Pair with balance exercises",
         "rationale": "SMA/M1 anodal tDCS during balance tasks enhances somatosensory integration."},
        {"code": "C7", "symptom": "ON/OFF Dyskinesia",
         "anodes": ["Cb1", "Cbz", "Cb2"], "cathodes": ["Fpz"],
         "params_text": "2 mA · 20–40 min | Cerebellar anodal stimulation",
         "rationale": "Cathodal cerebellar tDCS reduces LID; anodal enhances adaptation. Protocol adapted per patient phase."},
        {"code": "C8", "symptom": "Motor Learning & Skill Acquisition",
         "anodes": ["C3"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 20 min | L-M1 during physiotherapy",
         "rationale": "L-M1 anodal tDCS during motor practice accelerates skill encoding via LTP-like plasticity."},
    ],
    "plato": [
        {"code": "C1-PS", "symptom": "Motor (Bradykinesia / Rigidity)",
         "anodes": ["C3"], "cathodes": ["Fpz"],
         "params_text": "Variant 1A · M1 Hand | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 1A: C3 (M1 Hand) | Variant 1B: Cz (M1 Leg)"},
        {"code": "C2-PS", "symptom": "Gait / Freezing of Gait (FOG)",
         "anodes": ["Fz"], "cathodes": ["Pz"],
         "params_text": "Variant 2 · SMA/Fz | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 2: Fz (SMA) — use with treadmill walking"},
        {"code": "C3-PS", "symptom": "Cognition / Executive Function",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · L-DLPFC (F3) | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 3: F3 (L-DLPFC) single-channel"},
        {"code": "C4-PS", "symptom": "Mood / Depression & Apathy",
         "anodes": ["F3"], "cathodes": ["F4"],
         "params_text": "Variant 3 · L-DLPFC | 1.2–1.6 mA · 20 min",
         "variant_note": "Same as C3-PS variant; mood/cognitive circuits overlap"},
        {"code": "C5-PS", "symptom": "Fatigue",
         "anodes": ["Fz"], "cathodes": ["Oz"],
         "params_text": "Variant 5 · Frontal-occipital | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 5: Fz anode, Oz reference"},
        {"code": "C6-PS", "symptom": "Balance & Postural Stability",
         "anodes": ["Cz"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · Cerebellar | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 4: Cbz (Cerebellar) — pair with balance board"},
        {"code": "C7-PS", "symptom": "Dyskinesia (Motor Fluctuations)",
         "anodes": ["C3"], "cathodes": ["Fpz"],
         "params_text": "Variant 1A · M1 | 1.2–1.6 mA · ON state",
         "variant_note": "Administer during ON state only. Monitor dyskinesia severity."},
        {"code": "C8-PS", "symptom": "Motor Learning — Concurrent with Physiotherapy",
         "anodes": ["C3"], "cathodes": ["Fp2"],
         "params_text": "Variant 1A · M1 | During physio session",
         "variant_note": "Time stimulation to coincide with physiotherapy practice blocks"},
    ],
    "phenotypes": [
        {"code": "F1", "name": "Bradykinetic / Rigid",
         "sozo_seq": ["taVNS / CES · 10 min pre-prime", "tDCS M1 / DLPFC · 2 mA × 20 min",
                      "TPS M1 bilat + SMA · 10,000 pulses", "Rehab + taVNS · Motor rehab 30–45 min"],
         "tps_combos": [
             ["TPS + tDCS", "tDCS primes M1 excitability before deep TPS", "tDCS 15–20 min before TPS", "Rigidity, bradykinesia", "Moderate adjunctive"],
             ["TPS + taVNS", "taVNS stabilises autonomic tone, enhances LTP window", "taVNS 10–15 min pre-TPS", "Stress-sensitive motor worsening", "Emerging"],
             ["TPS + CES", "CES reduces hyperarousal, improves stimulation tolerance", "CES evening after TPS days", "Sleep/anxiety overlay on bradykinesia", "Weak / supportive"],
         ],
         "nontps_combos": [
             ["tDCS + physiotherapy", "Bradykinesia, rigidity", "Anodal M1 tDCS enhances motor practice", "tDCS immediately before or during rehab", "Moderate adjunctive"],
             ["taVNS + standard care", "Stress-sensitive motor worsening", "taVNS feasible and safe in PD", "Non-tDCS days or pre-rehabilitation", "Emerging"],
             ["CES + standard care", "Sleep/anxiety overlay", "CES may help anxiety or sleep", "Evening use", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Restore motor initiation, reduce rigidity, improve functional mobility."},
        {"code": "F2", "name": "Tremor-Dominant",
         "sozo_seq": ["CES 20–30 min · Reduce tremor amplitude at rest", "tDCS M1 (C3/C4) · 2 mA × 20 min",
                      "TPS Cerebellum + M1 · 5,000–8,000 pulses", "taVNS + occupational therapy · 30 min"],
         "tps_combos": [
             ["TPS Cerebellum + tDCS M1", "Dual-site approach targeting CTC loop", "tDCS 20 min before cerebellar TPS", "Rest tremor, action tremor", "Emerging"],
             ["TPS + CES", "CES reduces tremor anxiety, CES+TPS overlap", "CES during waiting period", "Anxiety-amplified tremor", "Weak / supportive"],
             ["TPS + taVNS", "taVNS modulates vagal-cerebellar pathway", "taVNS concurrent with TPS", "Autonomic dysregulation with tremor", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS M1 bilateral + OT", "Tremor during ADL", "Cortical facilitation + practice", "tDCS during task practice", "Moderate adjunctive"],
             ["CES + pharmacotherapy", "Rest tremor, medication fluctuation", "CES may stabilise mood-tremor link", "Evening CES", "Weak / supportive"],
             ["taVNS + relaxation", "Stress-sensitive tremor", "Parasympathetic upregulation", "Pre-activity taVNS", "Experimental"],
         ],
         "rationale": "Clinical Target: Modulate cerebellar-thalamic-cortical loop; reduce rest and action tremor."},
        {"code": "F3", "name": "Executive Dysfunction (PD-MCI)",
         "sozo_seq": ["CES 20 min · Stabilise mood and arousal", "tDCS L-DLPFC (F3) · 2 mA × 20 min",
                      "TPS DLPFC + PPC · 4,000 pulses", "Cognitive training · 30–45 min"],
         "tps_combos": [
             ["TPS DLPFC + tDCS", "Sequential prefrontal neuromodulation", "tDCS 20 min then TPS", "Working memory, set-shifting", "Emerging"],
             ["TPS + cognitive training", "Plasticity window post-TPS", "Cognitive tasks during/after TPS", "Attention, memory", "Emerging"],
             ["TPS + taVNS", "taVNS enhances acetylcholine; boosts cognition", "taVNS concurrent or post-TPS", "Cognitive fatigue", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS DLPFC + cognitive rehab", "Executive dysfunction, working memory", "Prefrontal facilitation + training", "tDCS during training", "Moderate adjunctive"],
             ["CES + cognitive training", "Anxiety-impaired cognition", "CES reduces cognitive-anxiety", "CES before training sessions", "Weak / supportive"],
             ["taVNS + memory training", "Memory encoding deficit", "Cholinergic enhancement", "taVNS during encoding tasks", "Experimental"],
         ],
         "rationale": "Clinical Target: Improve working memory, attention, and executive control."},
        {"code": "F4", "name": "Depression / Apathy",
         "sozo_seq": ["CES 30–45 min daily · Primary mood stabilisation", "tDCS L-DLPFC · 2 mA × 20–30 min",
                      "TPS DLPFC bilateral · 3,000 pulses", "taVNS + behavioural activation · 30 min"],
         "tps_combos": [
             ["TPS DLPFC + tDCS", "Sequential left prefrontal facilitation", "tDCS before TPS", "Anhedonia, low motivation", "Emerging"],
             ["TPS + CES", "CES primary; TPS adjunctive", "CES daily; TPS 2×/week", "Depression, anxiety comorbidity", "Emerging"],
             ["TPS + taVNS", "taVNS enhances 5-HT and NE pathways", "taVNS pre or concurrent TPS", "Apathy with autonomic dysregulation", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS L-DLPFC + psychotherapy", "PD depression, anhedonia", "Prefrontal facilitation + therapy", "tDCS before sessions", "Moderate adjunctive"],
             ["CES daily + pharmacotherapy", "Mood stabilisation, sleep", "CES adjunctive to antidepressants", "Evening CES", "Moderate adjunctive"],
             ["taVNS + CBT", "Anxiety-depression comorbidity", "Parasympathetic + cognitive approach", "taVNS during CBT", "Experimental"],
         ],
         "rationale": "Clinical Target: Restore motivational and affective circuitry; reduce apathy and depression."},
        {"code": "F5", "name": "Freezing of Gait / Axial Gait",
         "sozo_seq": ["taVNS 10–15 min · Prime motor-autonomic coupling", "tDCS SMA/M1 (Fz/Cz) · 2 mA × 20 min",
                      "TPS SMA + M1 bilateral · 5,000 pulses", "Gait training + treadmill · 30–45 min"],
         "tps_combos": [
             ["TPS SMA + tDCS Cz", "SMA-M1 loop facilitation for gait", "tDCS during gait prep; TPS after", "FOG, start hesitation", "Emerging"],
             ["TPS + taVNS", "taVNS stabilises autonomic freezing response", "taVNS concurrent TPS", "Stress-triggered FOG", "Experimental"],
             ["TPS + auditory cueing", "Rhythmic cueing post-TPS", "TPS then metronome-guided walking", "Cadence-deficit gait", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS SMA + gait rehab", "FOG, step initiation", "SMA facilitation + cueing", "tDCS before gait training", "Moderate adjunctive"],
             ["taVNS + gait training", "Stress-sensitive FOG", "Autonomic stabilisation", "taVNS before walk sessions", "Emerging"],
             ["CES + standard gait rehab", "Sleep-deprived gait worsening", "Sleep/arousal optimisation", "Evening CES; morning gait", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Reduce gait freezing episodes; improve step initiation and axial mobility."},
        {"code": "F6", "name": "Dyskinesias / Motor Fluctuations",
         "sozo_seq": ["CES 20 min · Reduce LID-anxiety coupling", "tDCS Cerebellum / M1 · 2 mA × 20 min (cathodal M1 if ON LID)",
                      "TPS Cerebellum · 3,000–4,000 pulses", "Medication timing optimisation + rehab"],
         "tps_combos": [
             ["TPS Cerebellum + cathodal M1 tDCS", "Inhibit LID via cerebellum + M1 down-regulation", "cathodal tDCS 20 min; TPS after", "Peak-dose dyskinesia", "Experimental"],
             ["TPS + CES", "CES reduces anxiety that worsens LID", "CES before TPS sessions", "Anxiety-LID coupling", "Weak / supportive"],
             ["TPS + medication optimisation", "Pulse delivery in OFF phase", "TPS during medication OFF window", "Motor fluctuations", "Experimental"],
         ],
         "nontps_combos": [
             ["Cathodal M1 tDCS + physio", "Peak-dose dyskinesia", "Down-regulate M1 during ON state", "During ON state", "Emerging"],
             ["CES + pharmacotherapy", "LID + anxiety", "CES stabilises mood-motor", "Evening CES", "Weak / supportive"],
             ["taVNS + standard care", "Autonomic fluctuations", "Autonomic modulation", "Non-stimulation days", "Experimental"],
         ],
         "rationale": "Clinical Target: Reduce levodopa-induced dyskinesia; stabilise motor fluctuations."},
        {"code": "F7", "name": "Cognitive Impairment (MCI/PDD)",
         "sozo_seq": ["CES 30 min · Stabilise sleep-cognitive link", "tDCS DLPFC bilateral · 2 mA × 20 min",
                      "TPS DLPFC + temporal · 5,000 pulses", "Cognitive training + memory tasks · 45 min"],
         "tps_combos": [
             ["TPS DLPFC + temporal + tDCS", "Multi-site prefrontal-temporal approach", "tDCS 20 min; TPS after", "Memory, orientation", "Emerging"],
             ["TPS + cognitive training", "Post-plasticity training window", "Cognitive tasks immediately post-TPS", "Attention, memory", "Moderate adjunctive"],
             ["TPS + CES", "Sleep optimisation + cognitive load", "CES evening; TPS morning", "Sleep-cognitive comorbidity", "Weak / supportive"],
         ],
         "nontps_combos": [
             ["tDCS bilateral DLPFC + cognitive rehab", "PDD, PD-MCI", "Working memory facilitation", "tDCS during training", "Moderate adjunctive"],
             ["CES + sleep hygiene", "Sleep-dependent memory consolidation", "CES improves sleep quality", "Evening CES", "Moderate adjunctive"],
             ["taVNS + memory training", "Cholinergic memory pathway", "VNS enhances hippocampal encoding", "taVNS during learning", "Experimental"],
         ],
         "rationale": "Clinical Target: Maximise residual cognitive reserve; slow progression of PDD."},
        {"code": "F8", "name": "Speech Impairment",
         "sozo_seq": ["taVNS 10 min · Prime vagal-laryngeal pathway", "tDCS L-M1 speech area · 2 mA × 20 min",
                      "TPS Broca + M1 face area · 3,000 pulses", "Speech therapy + voice exercises · 45 min"],
         "tps_combos": [
             ["TPS Broca + tDCS L-M1", "Speech motor cortex facilitation", "tDCS 20 min; TPS speech therapy concurrent", "Hypophonia, dysarthria", "Experimental"],
             ["TPS + LSVT LOUD", "Neuroplasticity + intensive voice therapy", "TPS before LSVT sessions", "Hypophonia", "Experimental"],
             ["TPS + taVNS", "Vagal-laryngeal pathway priming", "taVNS concurrent TPS", "Autonomic voice fluctuation", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS L-M1 + speech therapy", "Hypophonia, rate, articulation", "Cortical priming + practice", "tDCS during speech therapy", "Emerging"],
             ["taVNS + LSVT", "Voice fatigue, loudness deficit", "Vagal modulation + intensive training", "taVNS pre-therapy", "Experimental"],
             ["CES + sleep + speech", "Fatigue-related speech decline", "Sleep optimisation", "Evening CES", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Restore speech volume, rate, and intelligibility via motor speech circuits."},
        {"code": "F9", "name": "Pain Phenotype",
         "sozo_seq": ["CES 30 min · Primary pain-anxiety modulation", "tDCS M1 contralateral · 2 mA × 20 min",
                      "TPS M1 + insula region · 4,000 pulses", "taVNS + pain management · 30 min"],
         "tps_combos": [
             ["TPS M1 + tDCS M1", "Dual corticomotor pain gate approach", "tDCS 20 min then TPS", "Central pain, musculoskeletal overlay", "Experimental"],
             ["TPS + CES", "Pain-anxiety comorbidity", "CES before TPS for anxiety component", "Pain + anxiety", "Weak / supportive"],
             ["TPS + taVNS", "taVNS modulates vagal pain pathways", "taVNS concurrent TPS", "Autonomic pain", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS M1 + physiotherapy", "Central pain, musculoskeletal", "Anodal M1 pain gate modulation", "tDCS before physio", "Moderate adjunctive"],
             ["CES + standard pain management", "Pain-anxiety comorbidity", "CES reduces anxiety-pain cycle", "Daily evening CES", "Moderate adjunctive"],
             ["taVNS + mindfulness", "Autonomic pain, central sensitisation", "Parasympathetic downregulation", "taVNS during mindfulness", "Emerging"],
         ],
         "rationale": "Clinical Target: Reduce central pain sensitisation; modulate descending pain inhibition."},
    ],
    "contraindications_extra": [
        ["Dopaminergic therapy interaction", "tDCS (frontal)", "RELATIVE — may amplify motor response"],
    ],
    "key_outcome_measures": "MDS-UPDRS III (motor), MoCA (cognition), PDQ-39 (QoL), PSQI (sleep)",
}

# ── 2. DEPRESSION ─────────────────────────────────────────────────────────────
CONDITIONS["depression"] = {
    "display_name": "Major Depressive Disorder",
    "icd10": "F32 / F33",
    "short_name": "MDD",
    "tps_evidence": {
        "regulatory_status": "Investigational",
        "evidence_level": "Pilot RCT + Multiple RCTs (2025)",
        "literature_count": "14+",
        "key_references": "Keeser 2023 IJERPH (Pilot RCT, n=30, 34 citations); 3x RCTs CINP 2025; RCT Protocol Frontiers 2022 (5 citations); NAc TRD case 2023; Asian multicenter RCT 2025",
        "side_effects": "Transient headache, mood fluctuation. Well tolerated.",
        "notes": "14 papers, 6 RCTs (2022–2026). Rapidly expanding. 3 new RCTs at CINP 2025. NAc target for TRD explored. Active NCT05551585 ongoing RCT.",
    },
    "tps_regulatory_note": "Investigational (off-label) — 14+ published papers including 6 RCTs; 3 new RCTs presented at CINP 2025.",
    "tps_warning": TPS_WARNING_TEMPLATE.format(condition="Major Depressive Disorder"),
    "tps": [
        {"code": "T1", "symptom": "Core Depression: Anhedonia & Low Mood", "evidence": "Emerging \u2014 53 RCT/SR supporting",
         "targets": ["F3", "F4"], "tps": True,
         "params_text": "TPS: Bilateral DLPFC · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm² · 6–12 sessions",
         "rationale": "Bilateral DLPFC modulation targets hypofrontality in MDD; L>R asymmetry is primary treatment target."},
        {"code": "T2", "symptom": "Rumination & Default Mode Overactivation", "evidence": "Emerging \u2014 limited RCT data (n=2)",
         "targets": ["F3", "Fz", "Pz"], "tps": True,
         "params_text": "TPS: L-DLPFC + posterior DMN · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
         "rationale": "Targeting both DLPFC and posterior DMN nodes disrupts ruminative DMN hyperactivity."},
        {"code": "T3", "symptom": "Cognitive Impairment (Depression-Related)", "evidence": "Preliminary",
         "targets": ["F3", "P3", "P4"], "tps": True,
         "params_text": "TPS: L-DLPFC + PPC · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
         "rationale": "Prefrontal-parietal network enhancement addresses concentration and working memory deficits."},
        {"code": "T4", "symptom": "Anxiety Comorbidity", "evidence": "Emerging Pilot",
         "targets": ["F4", "F3"], "tps": True,
         "params_text": "TPS: R-DLPFC (primary) + L-DLPFC · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
         "rationale": "R-DLPFC down-regulation may reduce anxiety hyperarousal; complementary to antidepressant effect."},
        {"code": "T5", "symptom": "Treatment-Resistant Depression (TRD)", "evidence": "Experimental",
         "targets": ["F3", "F4", "FC3", "FC4"], "tps": True,
         "params_text": "TPS: DLPFC + OFC bilateral · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
         "rationale": "Extended bilateral approach for TRD targets broader prefrontal network including sgACC connectivity."},
    ],
    "tdcs": [
        {"code": "C1", "symptom": "Core Depression (Primary Protocol)",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 20–30 min | L-DLPFC (F3) → R-supraorbital",
         "rationale": "Standard tDCS antidepressant montage: L-DLPFC anodal facilitates hypofrontal left hemisphere."},
        {"code": "C2", "symptom": "Anhedonia & Reward Processing",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params_text": "2 mA · 20 min | Bilateral DLPFC → occipital cathode",
         "rationale": "Bilateral prefrontal engagement targets reward circuitry and motivational systems."},
        {"code": "C3", "symptom": "Rumination Reduction",
         "anodes": ["F3"], "cathodes": ["P3"],
         "params_text": "2 mA · 20 min | L-DLPFC anode → L-parietal cathode",
         "rationale": "Cathodal parietal placement inhibits posterior DMN; reduces ruminative self-referential processing."},
        {"code": "C4", "symptom": "Anxiety & Hyperarousal",
         "anodes": ["F4"], "cathodes": ["F3"],
         "params_text": "2 mA · 20 min | R-DLPFC anode → L-DLPFC cathode",
         "rationale": "Asymmetric frontal montage targets anxiety predominant presentation; reverses standard depression montage."},
        {"code": "C5", "symptom": "Sleep & Fatigue",
         "anodes": ["F3", "F4"], "cathodes": ["Pz"],
         "params_text": "2 mA · 20 min | Bilateral DLPFC → parietal; evening session",
         "rationale": "Evening bilateral prefrontal tDCS may enhance slow-wave sleep and reduce fatigue via thalamic modulation."},
        {"code": "C6", "symptom": "Cognitive Symptoms (Brain Fog)",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 20 min | L-DLPFC · concurrent with cognitive tasks",
         "rationale": "Cognitive task performance during tDCS (online stimulation) enhances neuroplastic effects."},
        {"code": "C7", "symptom": "Treatment-Resistant Depression Augmentation",
         "anodes": ["F3", "FC3"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 30 min | Extended L-prefrontal montage",
         "rationale": "Extended 30-min sessions and larger anode field for TRD; combine with psychotherapy."},
        {"code": "C8", "symptom": "Maintenance / Relapse Prevention",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "1.5–2 mA · 20 min | Twice-weekly maintenance",
         "rationale": "Maintenance tDCS at reduced frequency for sustained antidepressant effect post-acute course."},
    ],
    "plato": [
        {"code": "C1-PS", "symptom": "Core Depression",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · L-DLPFC (F3) | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 3: F3 (L-DLPFC) — standard antidepressant montage"},
        {"code": "C2-PS", "symptom": "Anhedonia",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · L-DLPFC | 1.6 mA · 20 min",
         "variant_note": "Higher intensity (1.6 mA) for anhedonia; paired with reward-based tasks"},
        {"code": "C3-PS", "symptom": "Rumination",
         "anodes": ["F3"], "cathodes": ["Pz"],
         "params_text": "Variant 3A · L-DLPFC → parietal | 1.2–1.6 mA",
         "variant_note": "Parietal reference reduces posterior DMN activity"},
        {"code": "C4-PS", "symptom": "Anxiety Comorbidity",
         "anodes": ["F4"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · R-DLPFC (F4) | 1.2 mA · 20 min",
         "variant_note": "Lower intensity for anxiety; R-DLPFC calming effect"},
        {"code": "C5-PS", "symptom": "Sleep & Fatigue",
         "anodes": ["Fz"], "cathodes": ["Oz"],
         "params_text": "Variant 5 · Frontal | 1.2–1.6 mA · Evening",
         "variant_note": "Evening session only; Fz anode for frontal-occipital modulation"},
        {"code": "C6-PS", "symptom": "Cognitive Symptoms",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · L-DLPFC | 1.6 mA · 20 min with tasks",
         "variant_note": "Online stimulation during cognitive training tasks"},
        {"code": "C7-PS", "symptom": "TRD Augmentation",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · 30 min extended | 1.6 mA",
         "variant_note": "Extended 30-min session for TRD; Doctor-authorised only"},
        {"code": "C8-PS", "symptom": "Maintenance",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · Maintenance | 1.2 mA · 2×/week",
         "variant_note": "Reduced frequency home maintenance; weekly Doctor check"},
    ],
    "phenotypes": [
        {"code": "F1", "name": "Anhedonic / Reward-Deficit",
         "sozo_seq": ["CES 30–45 min · Baseline mood stabilisation", "tDCS L-DLPFC · 2 mA × 20 min",
                      "TPS DLPFC bilateral · 3,000 pulses", "Behavioural activation + pleasant activity scheduling · 45 min"],
         "tps_combos": [
             ["TPS DLPFC + tDCS", "Sequential prefrontal facilitation", "tDCS 20 min before TPS", "Anhedonia, reward deficit", "Emerging"],
             ["TPS + CES", "CES primary daily; TPS 2×/week", "CES morning; TPS afternoon", "Mood + sleep", "Emerging"],
             ["TPS + taVNS", "taVNS enhances serotonergic pathways", "taVNS pre-TPS", "Autonomic-mood coupling", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS + behavioural activation", "Anhedonia, apathy", "Prefrontal facilitation + reward tasks", "tDCS before pleasurable activities", "Moderate adjunctive"],
             ["CES daily + psychotherapy", "Depression, sleep disturbance", "CES adjunctive to CBT", "Evening CES", "Moderate adjunctive"],
             ["taVNS + mindfulness-based CBT", "Rumination, stress-reactivity", "Parasympathetic + cognitive", "taVNS during mindfulness", "Emerging"],
         ],
         "rationale": "Clinical Target: Restore reward processing and motivational drive via prefrontal-striatal circuits."},
        {"code": "F2", "name": "Rumination / Worry-Dominant",
         "sozo_seq": ["CES 30 min · Reduce hyperarousal", "tDCS L-DLPFC → L-parietal cathode · 2 mA × 20 min",
                      "TPS L-DLPFC + posterior DMN · 4,000 pulses", "Mindfulness + CBT-R · 45 min"],
         "tps_combos": [
             ["TPS posterior DMN + tDCS", "DMN node disruption", "tDCS 20 min; TPS posterior DMN after", "Rumination, self-referential", "Emerging"],
             ["TPS + taVNS", "taVNS reduces DMN connectivity", "taVNS concurrent TPS", "Anxiety-rumination", "Experimental"],
             ["TPS + CES", "CES reduces arousal enabling TPS effect", "CES before TPS", "Hyperarousal-rumination", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS parietal cathode + CBT-R", "Rumination, worry", "DMN inhibition + rumination-focused CBT", "tDCS during/before CBT", "Moderate adjunctive"],
             ["CES + CBT", "Anxiety-depression comorbidity", "Arousal reduction + cognitive restructuring", "CES daily", "Moderate adjunctive"],
             ["taVNS + mindfulness", "Rumination, threat-detection bias", "Parasympathetic downregulation", "taVNS during mindfulness", "Emerging"],
         ],
         "rationale": "Clinical Target: Disrupt pathological DMN hyperactivation; reduce ruminative thought patterns."},
        {"code": "F3", "name": "Psychomotor Retardation",
         "sozo_seq": ["taVNS 10–15 min · Motor-autonomic priming", "tDCS bilateral DLPFC + M1 · 2 mA × 20 min",
                      "TPS bilateral DLPFC · 3,000 pulses", "Graded activity + exercise · 30–45 min"],
         "tps_combos": [
             ["TPS DLPFC bilateral + tDCS", "Motor-prefrontal facilitation", "tDCS 20 min before TPS", "Retardation, akinesia", "Emerging"],
             ["TPS + exercise", "Post-TPS neuroplasticity + BDNF", "Exercise immediately post-TPS", "Physical inactivity", "Moderate adjunctive"],
             ["TPS + taVNS", "Autonomic activation for motor drive", "taVNS pre-TPS", "Autonomic blunting", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS bilateral + exercise", "Psychomotor slowing", "Motor cortex + aerobic BDNF", "tDCS before exercise", "Moderate adjunctive"],
             ["taVNS + graded activity", "Fatigue, low drive", "Autonomic activation", "taVNS pre-activity", "Emerging"],
             ["CES + exercise programme", "Fatigue, sleep deficit", "Sleep + energy restoration", "Evening CES", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Restore motor drive and physical activation through prefrontal-motor facilitation."},
        {"code": "F4", "name": "Anxious Depression",
         "sozo_seq": ["CES 45 min · Primary anxiety-sleep stabilisation", "tDCS R-DLPFC anode · 2 mA × 20 min",
                      "TPS R-DLPFC + L-DLPFC · 3,000 pulses", "Anxiety-focused CBT + relaxation · 45 min"],
         "tps_combos": [
             ["TPS R-DLPFC + CES", "Anxiety reduction via right prefrontal", "CES 30 min; TPS R-DLPFC after", "Anxious depression", "Emerging"],
             ["TPS + taVNS", "taVNS primary anxiolytic; TPS mood", "taVNS 15 min; TPS after", "Anxiety comorbidity", "Emerging"],
             ["TPS + DLPFC bilateral", "Balanced bilateral approach", "Bilateral TPS", "Mixed depression-anxiety", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS R-DLPFC + CBT", "Anxious depression", "Right frontal calming", "tDCS before CBT sessions", "Moderate adjunctive"],
             ["CES + pharmacotherapy", "Anxiety + sleep disturbance", "CES adjunctive to SSRI/SNRI", "Evening CES", "Moderate adjunctive"],
             ["taVNS + progressive relaxation", "Somatic anxiety", "Parasympathetic dominance", "taVNS during relaxation", "Emerging"],
         ],
         "rationale": "Clinical Target: Balance prefrontal asymmetry; reduce anxiety hyperarousal while lifting mood."},
        {"code": "F5", "name": "Cognitive / Concentration Impairment",
         "sozo_seq": ["CES 20 min · Clear cognitive fog", "tDCS L-DLPFC · 2 mA × 20 min with tasks",
                      "TPS L-DLPFC + PPC · 4,000 pulses", "Cognitive training · 45 min"],
         "tps_combos": [
             ["TPS DLPFC + PPC + tDCS", "Prefrontal-parietal cognitive enhancement", "tDCS 20 min; TPS after", "Concentration, memory", "Emerging"],
             ["TPS + cognitive training", "Post-plasticity cognitive practice", "TPS then cognitive tasks", "Working memory", "Moderate adjunctive"],
             ["TPS + CES", "Sleep-cognition link", "CES evening; TPS morning", "Sleep-dependent cognition", "Weak / supportive"],
         ],
         "nontps_combos": [
             ["tDCS DLPFC + cognitive training", "Concentration, working memory", "Online stimulation during tasks", "tDCS during training", "Moderate adjunctive"],
             ["CES + sleep hygiene", "Sleep-dependent cognition", "Sleep quality improvement", "Evening CES", "Moderate adjunctive"],
             ["taVNS + attention training", "Sustained attention deficit", "Cholinergic enhancement", "taVNS during training", "Experimental"],
         ],
         "rationale": "Clinical Target: Restore prefrontal cognitive control impaired by depressive episode."},
        {"code": "F6", "name": "Somatic / Vegetative Symptoms",
         "sozo_seq": ["taVNS 20 min · Autonomic-somatic regulation", "tDCS bilateral frontal · 2 mA × 20 min",
                      "TPS DLPFC + insula · 3,000 pulses", "Body-focused therapy + relaxation · 45 min"],
         "tps_combos": [
             ["TPS DLPFC + taVNS", "Prefrontal-autonomic coupling", "taVNS concurrent TPS", "Somatic anxiety", "Experimental"],
             ["TPS + CES", "Sleep + somatic symptoms", "CES evening; TPS morning", "Insomnia, fatigue", "Emerging"],
             ["TPS + body scan mindfulness", "Somatic awareness + cortical modulation", "TPS before mindfulness", "Bodily dissociation", "Experimental"],
         ],
         "nontps_combos": [
             ["taVNS + somatic therapy", "Somatic depression", "Autonomic regulation", "taVNS daily", "Emerging"],
             ["CES + sleep intervention", "Vegetative symptoms, insomnia", "Sleep-autonomic restoration", "Evening CES", "Moderate adjunctive"],
             ["tDCS + exercise", "Fatigue, psychomotor", "BDNF + motor activation", "tDCS before exercise", "Moderate adjunctive"],
         ],
         "rationale": "Clinical Target: Address autonomic-somatic dysfunction and vegetative features of MDD."},
        {"code": "F7", "name": "Melancholic Depression",
         "sozo_seq": ["CES 45 min · Stabilise diurnal mood variation", "tDCS L-DLPFC · 2 mA × 30 min",
                      "TPS DLPFC bilateral · 5,000 pulses", "Structured activity + light therapy · 45 min"],
         "tps_combos": [
             ["TPS DLPFC bilateral + tDCS", "Intensive bilateral prefrontal approach", "tDCS 20 min; extended TPS", "Melancholia, anhedonia", "Emerging"],
             ["TPS + light therapy", "Circadian-prefrontal coupling", "Light therapy morning; TPS afternoon", "Diurnal variation", "Emerging"],
             ["TPS + CES", "CES daily; TPS 3×/week", "Morning TPS; evening CES", "Sleep-melancholic coupling", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS 30 min + psychotherapy", "Melancholic features", "Extended tDCS for severity", "tDCS before therapy", "Moderate adjunctive"],
             ["CES + antidepressant", "Melancholic severity", "CES augments pharmacotherapy", "Daily evening CES", "Moderate adjunctive"],
             ["Light therapy + standard care", "Circadian disruption", "Circadian normalisation", "Morning light therapy", "Moderate adjunctive"],
         ],
         "rationale": "Clinical Target: Intensive bilateral prefrontal engagement for melancholic severity."},
        {"code": "F8", "name": "Atypical Depression",
         "sozo_seq": ["taVNS 15 min · Mood-reactivity regulation", "tDCS L-DLPFC · 2 mA × 20 min",
                      "TPS L-DLPFC + limbic · 3,000 pulses", "Interpersonal therapy + social activation · 45 min"],
         "tps_combos": [
             ["TPS L-DLPFC + limbic + taVNS", "Limbic-prefrontal circuit approach", "taVNS; then TPS", "Mood reactivity, rejection sensitivity", "Experimental"],
             ["TPS + IPT", "Interpersonal + neuroplasticity", "TPS before IPT sessions", "Social withdrawal", "Experimental"],
             ["TPS + CES", "Sleep hypersomnia + mood", "CES in morning; TPS afternoon", "Hypersomnia", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS + interpersonal therapy", "Rejection sensitivity, mood reactivity", "Prefrontal facilitation + IPT", "tDCS before IPT", "Moderate adjunctive"],
             ["taVNS + social activation", "Social withdrawal, mood reactivity", "Autonomic-social coupling", "taVNS before social activities", "Emerging"],
             ["CES + sleep scheduling", "Hypersomnia, fatigue", "Circadian + sleep regulation", "Morning CES to reduce hypersomnia", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Modulate mood reactivity and atypical neurovegetative features."},
        {"code": "F9", "name": "TRD — Treatment Resistant Depression",
         "sozo_seq": ["CES 60 min daily · Baseline mood stabilisation (primary)", "tDCS L-DLPFC · 2 mA × 30 min",
                      "TPS DLPFC + OFC bilateral · 5,000 pulses", "Intensive psychotherapy · 60 min"],
         "tps_combos": [
             ["TPS bilateral DLPFC/OFC + tDCS", "Intensive multi-site approach", "tDCS 30 min; TPS extended", "TRD, chronic depression", "Experimental"],
             ["TPS + ketamine protocol", "Post-ketamine plasticity window", "TPS 24h post-ketamine infusion", "TRD with ketamine access", "Experimental"],
             ["TPS + ECT preparation", "Pre-ECT neuroplasticity", "TPS during wait period", "TRD escalation", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS 30 min + intensive CBT", "TRD", "Extended sessions + psychotherapy", "tDCS 5×/week", "Moderate adjunctive"],
             ["CES + antidepressant augmentation", "TRD with medication partial response", "CES daily + medication review", "Daily CES", "Moderate adjunctive"],
             ["taVNS + standard care", "TRD with anxiety comorbidity", "Daily taVNS home device", "taVNS daily home", "Emerging"],
         ],
         "rationale": "Clinical Target: Maximise prefrontal network engagement for treatment-resistant presentations."},
    ],
    "contraindications_extra": [
        ["Bipolar disorder (manic risk)", "tDCS (L-DLPFC anodal)", "RELATIVE — screen carefully; use lower intensity"],
        ["Active suicidal ideation", "All modalities", "HOLD — safety assessment first; Doctor clearance required"],
    ],
    "key_outcome_measures": "PHQ-9, HDRS-17, BDI-II, GAD-7 (if anxiety), PSQI (sleep)",
}

# ── 3. ANXIETY ────────────────────────────────────────────────────────────────
CONDITIONS["anxiety"] = {
    "display_name": "Generalised Anxiety Disorder",
    "icd10": "F41.1",
    "short_name": "GAD",
    "tps_warning": TPS_WARNING_TEMPLATE.format(condition="Generalised Anxiety Disorder"),
    "tps": [
        {"code": "T1", "symptom": "Generalised Worry & Hyperarousal", "evidence": "Emerging \u2014 11 RCT/SR supporting",
         "targets": ["F4", "F3"], "tps": True,
         "params_text": "TPS: R-DLPFC (primary) + L-DLPFC · 3,000 pulses · 5 Hz",
         "rationale": "R-DLPFC facilitation shifts prefrontal balance away from threat-hypervigilance."},
        {"code": "T2", "symptom": "Panic & Autonomic Dysregulation", "evidence": "Emerging \u2014 preclinical/observational only",
         "targets": ["F4", "FC4"], "tps": True,
         "params_text": "TPS: R-DLPFC + R-FC · 3,000 pulses · 5 Hz",
         "rationale": "Right prefrontal targeting reduces amygdala hyperreactivity via top-down inhibition."},
        {"code": "T3", "symptom": "Cognitive Worry / Intrusive Thoughts", "evidence": "Preliminary",
         "targets": ["F3", "F4", "Pz"], "tps": True,
         "params_text": "TPS: Bilateral DLPFC + posterior · 4,000 pulses · 5 Hz",
         "rationale": "DMN-CEN balance restoration reduces cognitive worry loops."},
        {"code": "T4", "symptom": "Insomnia Comorbidity", "evidence": "Emerging Pilot",
         "targets": ["F3", "F4"], "tps": True,
         "params_text": "TPS: Bilateral DLPFC · 3,000 pulses · evening session",
         "rationale": "Evening prefrontal modulation may reduce pre-sleep hyperarousal."},
        {"code": "T5", "symptom": "Social Anxiety Overlay", "evidence": "Experimental \u2014 0 studies",
         "targets": ["F4", "F3", "T4"], "tps": True,
         "params_text": "TPS: R-DLPFC + temporal · 3,000 pulses · 5 Hz",
         "rationale": "Temporal lobe involvement addresses social threat appraisal circuits."},
    ],
    "tdcs": [
        {"code": "C1", "symptom": "Generalised Anxiety (Primary Protocol)",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params_text": "2 mA · 20 min | R-DLPFC (F4) → L-supraorbital cathode",
         "rationale": "R-DLPFC anodal tDCS increases right prefrontal inhibitory control of amygdala."},
        {"code": "C2", "symptom": "Worry & Cognitive Anxiety",
         "anodes": ["F3", "F4"], "cathodes": ["Oz"],
         "params_text": "2 mA · 20 min | Bilateral DLPFC → occipital cathode",
         "rationale": "Bilateral prefrontal engagement reduces worry network hyperactivity."},
        {"code": "C3", "symptom": "Panic Disorder Overlay",
         "anodes": ["F4"], "cathodes": ["F3"],
         "params_text": "2 mA · 20 min | R-DLPFC anode → L-DLPFC cathode",
         "rationale": "Right facilitation/left inhibition reduces panic threshold via prefrontal-amygdala top-down."},
        {"code": "C4", "symptom": "Sleep & Hyperarousal",
         "anodes": ["Fz"], "cathodes": ["Pz"],
         "params_text": "2 mA · 20 min | Frontal-parietal; evening session",
         "rationale": "Frontal-parietal montage in the evening reduces cortical hyperarousal for sleep onset."},
        {"code": "C5", "symptom": "Somatic Anxiety",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params_text": "2 mA · 20 min | R-DLPFC → interoceptive awareness tasks",
         "rationale": "Right prefrontal facilitation during body-scan exercises reduces somatic anxiety amplification."},
        {"code": "C6", "symptom": "Social Anxiety",
         "anodes": ["F4", "FC4"], "cathodes": ["Fp1"],
         "params_text": "2 mA · 20 min | R-prefrontal extended before social exposure",
         "rationale": "Right prefrontal enhancement before social exposure tasks reduces anticipatory anxiety."},
        {"code": "C7", "symptom": "Health Anxiety / OCD Features",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "2 mA · 20 min | L-DLPFC during ERP tasks",
         "rationale": "L-DLPFC facilitation during exposure-response prevention exercises (OCD overlay)."},
        {"code": "C8", "symptom": "Maintenance / Generalisation",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params_text": "1.5 mA · 20 min | Maintenance twice-weekly home",
         "rationale": "Maintenance R-DLPFC stimulation sustains anxiety reduction gains post-intensive programme."},
    ],
    "plato": [
        {"code": "C1-PS", "symptom": "Generalised Anxiety",
         "anodes": ["F4"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · R-DLPFC (F4) | 1.2–1.6 mA · 20 min",
         "variant_note": "Variant 4: F4 (R-DLPFC) — primary anxiolytic montage"},
        {"code": "C2-PS", "symptom": "Worry & Cognitive Anxiety",
         "anodes": ["F4"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · R-DLPFC | 1.2 mA · 20 min with worry postponement",
         "variant_note": "Pair with worry postponement technique during stimulation"},
        {"code": "C3-PS", "symptom": "Panic",
         "anodes": ["F4"], "cathodes": ["Fp1"],
         "params_text": "Variant 4 · R-DLPFC | 1.2 mA · 20 min",
         "variant_note": "Use lower intensity (1.2 mA) for high sensitivity patients"},
        {"code": "C4-PS", "symptom": "Sleep & Hyperarousal",
         "anodes": ["Fz"], "cathodes": ["Oz"],
         "params_text": "Variant 5 · Frontal | 1.2 mA · Evening only",
         "variant_note": "Evening session only; may reduce sleep-onset anxiety"},
        {"code": "C5-PS", "symptom": "Somatic Anxiety",
         "anodes": ["F4"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · R-DLPFC | 1.2 mA · 20 min with body scan",
         "variant_note": "Pair with interoceptive awareness or body-scan mindfulness"},
        {"code": "C6-PS", "symptom": "Social Anxiety",
         "anodes": ["F4"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · R-DLPFC | 1.6 mA before social exposure",
         "variant_note": "Administer 30 min before planned social exposure session"},
        {"code": "C7-PS", "symptom": "Health Anxiety",
         "anodes": ["F3"], "cathodes": ["Fp2"],
         "params_text": "Variant 3 · L-DLPFC | 1.2–1.6 mA with ERP",
         "variant_note": "L-DLPFC for ERP tasks (health anxiety / OCD features)"},
        {"code": "C8-PS", "symptom": "Maintenance",
         "anodes": ["F4"], "cathodes": ["Fpz"],
         "params_text": "Variant 4 · Maintenance | 1.2 mA · 2×/week",
         "variant_note": "Home maintenance programme; weekly clinician review"},
    ],
    "phenotypes": [
        {"code": "F1", "name": "Chronic Worry / Generalised",
         "sozo_seq": ["CES 30–45 min · Primary anxiolytic", "tDCS R-DLPFC · 2 mA × 20 min",
                      "TPS R-DLPFC · 3,000 pulses", "CBT worry postponement + relaxation · 45 min"],
         "tps_combos": [
             ["TPS R-DLPFC + tDCS", "Sequential right prefrontal facilitation", "tDCS 20 min before TPS", "Chronic worry", "Emerging"],
             ["TPS + CES", "CES daily; TPS adjunctive", "CES morning; TPS 2×/week", "GAD with sleep comorbidity", "Emerging"],
             ["TPS + taVNS", "taVNS parasympathetic; TPS prefrontal", "taVNS pre-TPS", "Autonomic hyperarousal", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS R-DLPFC + CBT", "Generalised worry", "Right prefrontal + worry exposure", "tDCS before CBT", "Moderate adjunctive"],
             ["CES + GAD management", "Sleep + anxiety", "Daily CES adjunctive", "Evening CES", "Moderate adjunctive"],
             ["taVNS + relaxation training", "Autonomic anxiety", "Parasympathetic upregulation", "taVNS daily", "Emerging"],
         ],
         "rationale": "Clinical Target: Restore prefrontal top-down control over pathological worry circuits."},
        {"code": "F2", "name": "Panic Disorder",
         "sozo_seq": ["taVNS 15 min · Acute autonomic stabilisation", "tDCS R-DLPFC → L-DLPFC cathode · 2 mA × 20 min",
                      "TPS R-DLPFC + FC · 3,000 pulses", "Interoceptive exposure + breathing training · 45 min"],
         "tps_combos": [
             ["TPS R-DLPFC + taVNS", "Prefrontal-vagal dual approach", "taVNS 15 min; TPS after", "Panic, palpitations", "Emerging"],
             ["TPS + CES", "CES reduces inter-panic anxiety", "CES daily; TPS 2×/week", "Anticipatory anxiety", "Emerging"],
             ["TPS + breathing biofeedback", "Respiratory-cardiac-prefrontal loop", "TPS then biofeedback", "Somatic panic", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS R-DLPFC + interoceptive exposure", "Panic disorder", "Prefrontal facilitation + exposure", "tDCS before exposure", "Moderate adjunctive"],
             ["CES + pharmacotherapy", "Panic with medication partial response", "CES augments anxiolytics", "Evening CES", "Moderate adjunctive"],
             ["taVNS + breathing training", "Autonomic panic", "Parasympathetic + respiratory", "taVNS daily", "Emerging"],
         ],
         "rationale": "Clinical Target: Reduce panic threshold via prefrontal-amygdala modulation and autonomic stabilisation."},
        {"code": "F3", "name": "Social Anxiety",
         "sozo_seq": ["CES 30 min · Reduce anticipatory anxiety", "tDCS R-DLPFC + FC4 · 2 mA × 20 min",
                      "TPS R-DLPFC + temporal · 3,000 pulses", "Social exposure + video feedback · 45 min"],
         "tps_combos": [
             ["TPS R-DLPFC + temporal + tDCS", "Social threat appraisal circuit", "tDCS 20 min; TPS before exposure", "Social fear, embarrassment", "Experimental"],
             ["TPS + social exposure therapy", "Post-TPS plasticity for exposure", "TPS then graduated exposure", "Social avoidance", "Emerging"],
             ["TPS + CES", "Pre-event anxiety", "CES 60 min before social event", "Anticipatory anxiety", "Weak / supportive"],
         ],
         "nontps_combos": [
             ["tDCS R-prefrontal + CBT-SA", "Social anxiety disorder", "Right prefrontal + exposure", "tDCS before exposure sessions", "Moderate adjunctive"],
             ["taVNS + social skills training", "Autonomic social anxiety", "Parasympathetic + skills", "taVNS before practice", "Emerging"],
             ["CES + confidence building", "Anticipatory anxiety", "Arousal reduction", "CES before social engagement", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Reduce social threat appraisal; facilitate exposure therapy engagement."},
        {"code": "F4", "name": "Health Anxiety / Illness Phobia",
         "sozo_seq": ["CES 30 min · Reduce checking urge anxiety", "tDCS L-DLPFC · 2 mA × 20 min with ERP",
                      "TPS L-DLPFC + OFC · 3,000 pulses", "ERP + ACT · 45 min"],
         "tps_combos": [
             ["TPS L-DLPFC + OFC + tDCS", "OFC-DLPFC loop for health anxiety", "tDCS 20 min; TPS OFC area", "Checking behaviour, reassurance seeking", "Experimental"],
             ["TPS + ACT", "Acceptance-based approach post-TPS", "TPS then ACT session", "Illness preoccupation", "Experimental"],
             ["TPS + CES", "CES reduces hyperarousal driving checking", "CES daily; TPS 2×/week", "Anxiety-checking cycle", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS L-DLPFC + ERP", "Health anxiety, checking", "Prefrontal facilitation + ERP", "tDCS during ERP", "Moderate adjunctive"],
             ["CES + ACT", "Illness preoccupation", "Arousal + acceptance approach", "Daily CES", "Moderate adjunctive"],
             ["taVNS + mindfulness-ACT", "Somatic checking", "Parasympathetic + acceptance", "taVNS during mindfulness", "Emerging"],
         ],
         "rationale": "Clinical Target: Modulate OFC-DLPFC circuit mediating health-threat appraisal."},
        {"code": "F5", "name": "PTSD / Trauma Anxiety",
         "sozo_seq": ["CES 45 min · Safety and stabilisation", "tDCS R-DLPFC · 2 mA × 20 min",
                      "TPS R-DLPFC + bilateral · 3,000 pulses", "Trauma-focused CBT · 45 min"],
         "tps_combos": [
             ["TPS R-DLPFC + taVNS", "Trauma-autonomic coupling", "taVNS 15 min; TPS after", "Hypervigilance, startle", "Emerging"],
             ["TPS + EMDR", "Post-TPS plasticity for trauma processing", "TPS before EMDR session", "Trauma memory", "Experimental"],
             ["TPS + CES", "CES stabilises trauma-related sleep disruption", "CES evening; TPS morning", "Trauma + insomnia", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS R-DLPFC + trauma-CBT", "PTSD hyperarousal", "Prefrontal facilitation + CBT", "tDCS before trauma session", "Moderate adjunctive"],
             ["CES + sleep hygiene", "Trauma nightmares, sleep disruption", "CES sleep restoration", "Evening CES", "Moderate adjunctive"],
             ["taVNS + grounding techniques", "Dissociation, hyperarousal", "Parasympathetic + grounding", "taVNS during stabilisation", "Emerging"],
         ],
         "rationale": "Clinical Target: Reduce hypervigilance and facilitate trauma memory processing."},
        {"code": "F6", "name": "OCD Spectrum Anxiety",
         "sozo_seq": ["CES 30 min · Reduce obsessional arousal", "tDCS L-DLPFC / pre-SMA · 2 mA × 20 min",
                      "TPS pre-SMA + OFC · 3,000 pulses", "ERP + OCD-CBT · 60 min"],
         "tps_combos": [
             ["TPS pre-SMA + OFC + tDCS", "OCD circuit disruption", "tDCS 20 min; TPS OFC/SMA", "Obsessions, compulsions", "Emerging"],
             ["TPS + ERP", "Post-TPS ERP engagement", "TPS then ERP practice", "Compulsive rituals", "Emerging"],
             ["TPS + CES", "CES reduces OCD anxiety baseline", "CES daily; TPS 2×/week", "Anxiety-OCD loop", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS pre-SMA + ERP", "OCD compulsions", "Motor inhibition + exposure", "tDCS during ERP", "Moderate adjunctive"],
             ["CES + OCD management", "OCD anxiety", "Arousal reduction + ERP", "Daily CES", "Moderate adjunctive"],
             ["taVNS + mindfulness-OCD", "OCD with autonomic arousal", "Parasympathetic + defusion", "taVNS daily", "Emerging"],
         ],
         "rationale": "Clinical Target: Disrupt cortico-striato-thalamo-cortical loop driving OCD anxiety."},
        {"code": "F7", "name": "Sleep-Anxiety Comorbidity",
         "sozo_seq": ["CES 60 min evening · Primary sleep-anxiety intervention", "tDCS frontal · 2 mA × 20 min evening",
                      "TPS DLPFC bilateral · 3,000 pulses (afternoon)", "Sleep CBT-I + relaxation · 45 min"],
         "tps_combos": [
             ["TPS (afternoon) + CES (evening)", "Temporal separation for sleep-anxiety", "TPS 2 PM; CES 8 PM", "Insomnia + anxiety", "Emerging"],
             ["TPS + sleep restriction therapy", "CBT-I integration", "TPS before sleep restriction", "Sleep anxiety", "Experimental"],
             ["TPS + taVNS", "Evening parasympathetic priming", "taVNS 30 min pre-sleep", "Pre-sleep hyperarousal", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS frontal + CBT-I", "Sleep anxiety", "Prefrontal + sleep restriction", "Evening tDCS with CBT-I", "Moderate adjunctive"],
             ["CES + sleep hygiene", "Chronic insomnia-anxiety", "CES primary sleep intervention", "Evening CES 60 min", "Moderate adjunctive"],
             ["taVNS + progressive relaxation", "Pre-sleep anxiety", "Parasympathetic + relaxation", "taVNS 30 min before bed", "Emerging"],
         ],
         "rationale": "Clinical Target: Break anxiety-sleep disruption cycle via evening frontal modulation."},
        {"code": "F8", "name": "Generalised Physical Anxiety",
         "sozo_seq": ["taVNS 20 min · Somatic anxiety stabilisation", "tDCS R-DLPFC · 2 mA × 20 min",
                      "TPS R-DLPFC · 3,000 pulses", "Physiotherapy + relaxation + biofeedback · 45 min"],
         "tps_combos": [
             ["TPS + taVNS + biofeedback", "Full autonomic-prefrontal approach", "taVNS 20 min; TPS; biofeedback", "Physical tension, hyperventilation", "Experimental"],
             ["TPS + physiotherapy", "Somatic tension release post-TPS", "TPS then stretching/physio", "Muscular tension anxiety", "Experimental"],
             ["TPS + CES", "Physical anxiety + sleep", "CES evening; TPS morning", "Fatigue-anxiety", "Emerging"],
         ],
         "nontps_combos": [
             ["tDCS + progressive muscle relaxation", "Physical tension", "Prefrontal + somatic relaxation", "tDCS then relaxation", "Moderate adjunctive"],
             ["taVNS + physiotherapy", "Somatic anxiety", "Autonomic + somatic release", "taVNS pre-physio", "Emerging"],
             ["CES + exercise", "Physical anxiety, fatigue", "Sleep + BDNF restoration", "Evening CES", "Weak / supportive"],
         ],
         "rationale": "Clinical Target: Reduce physical manifestations of anxiety through autonomic-cortical regulation."},
        {"code": "F9", "name": "Medication-Resistant Anxiety",
         "sozo_seq": ["CES 60 min daily · Intensive stabilisation", "tDCS bilateral DLPFC · 2 mA × 20 min",
                      "TPS DLPFC bilateral · 5,000 pulses", "Intensive CBT + ACT · 60 min"],
         "tps_combos": [
             ["TPS bilateral DLPFC + tDCS + taVNS", "Multi-modal intensive approach", "taVNS 15 min; tDCS 20 min; TPS", "Medication-resistant GAD", "Experimental"],
             ["TPS + intensive CBT", "Post-TPS intensive therapy window", "TPS 5×/week; CBT daily", "Treatment-resistant anxiety", "Experimental"],
             ["TPS + ketamine exploration", "Glutamatergic anxiety approach", "TPS post-ketamine (if prescribed)", "TRD-style anxiety", "Experimental"],
         ],
         "nontps_combos": [
             ["tDCS intensive + CBT", "Medication-resistant anxiety", "Extended sessions + daily CBT", "5×/week tDCS", "Moderate adjunctive"],
             ["CES intensive + pharmacotherapy review", "Medication-resistant GAD", "CES daily + medication optimisation", "Daily CES", "Moderate adjunctive"],
             ["taVNS home device + therapy", "Chronic anxiety", "Daily home taVNS + weekly therapy", "Home taVNS programme", "Emerging"],
         ],
         "rationale": "Clinical Target: Intensive multi-modal approach for medication-resistant anxiety presentations."},
    ],
    "contraindications_extra": [
        ["Acute panic attack during session", "All modalities", "PAUSE — grounding first; reassess"],
        ["Benzodiazepine intoxication", "tDCS · TPS", "POSTPONE session"],
    ],
    "key_outcome_measures": "GAD-7, HAMA, Penn State Worry Questionnaire, PSQI, PHQ-9",
}

# ── Remaining 12 conditions — abbreviated but complete structure ────────────
# (Full data follows same pattern; abbreviated for script length management)

def _make_standard_condition(
    slug, display_name, icd10, short_name,
    t1_symptom, t1_targets,
    t2_symptom, t2_targets,
    t3_symptom, t3_targets,
    t4_symptom, t4_targets,
    t5_symptom, t5_targets,
    c1_symptom, c1_anodes, c1_cathodes,
    c2_symptom, c2_anodes, c2_cathodes,
    c3_symptom, c3_anodes, c3_cathodes,
    c4_symptom, c4_anodes, c4_cathodes,
    c5_symptom, c5_anodes, c5_cathodes,
    c6_symptom, c6_anodes, c6_cathodes,
    c7_symptom, c7_anodes, c7_cathodes,
    c8_symptom, c8_anodes, c8_cathodes,
    phenotype_names,  # list of 9 phenotype names
    key_measures,
    contraindications_extra=None,
    tps_evidence=None,
    tps_regulatory_note=None,
    tps_params_texts=None,  # optional list of 5 params_text strings (T1–T5)
):
    """Helper to build a condition dict from key parameters."""
    _tps_params_defaults = [
        (t1_symptom, t1_targets, "Emerging", "3,000–5,000 pulses"),
        (t2_symptom, t2_targets, "Emerging", "3,000 pulses"),
        (t3_symptom, t3_targets, "Preliminary", "4,000 pulses"),
        (t4_symptom, t4_targets, "Emerging Pilot", "3,000 pulses"),
        (t5_symptom, t5_targets, "Experimental", "4,000 pulses"),
    ]
    tps_protocols = [
        {"code": f"T{i+1}", "symptom": s, "evidence": ev, "targets": tg, "tps": True,
         "params_text": (tps_params_texts[i] if tps_params_texts and i < len(tps_params_texts)
                         else f"TPS: {', '.join(tg)} · {pc} · 5 Hz · 0.2 mJ/mm²"),
         "rationale": f"TPS targeting of {', '.join(tg)} for {s.lower()} in {display_name}."}
        for i, (s, tg, ev, pc) in enumerate(_tps_params_defaults)
    ]

    tdcs_protocols = [
        {"code": f"C{i+1}", "symptom": s, "anodes": an, "cathodes": ca,
         "params_text": f"2 mA · 20 min | {', '.join(an)} anode → {', '.join(ca)} cathode",
         "rationale": f"Anodal {', '.join(an)} tDCS for {s.lower()} in {display_name}."}
        for i, (s, an, ca) in enumerate([
            (c1_symptom, c1_anodes, c1_cathodes),
            (c2_symptom, c2_anodes, c2_cathodes),
            (c3_symptom, c3_anodes, c3_cathodes),
            (c4_symptom, c4_anodes, c4_cathodes),
            (c5_symptom, c5_anodes, c5_cathodes),
            (c6_symptom, c6_anodes, c6_cathodes),
            (c7_symptom, c7_anodes, c7_cathodes),
            (c8_symptom, c8_anodes, c8_cathodes),
        ])
    ]

    plato_protocols = [
        {"code": f"C{i+1}-PS", "symptom": s, "anodes": an, "cathodes": [ca_single],
         "params_text": f"Variant · {an[0]} | 1.2–1.6 mA · 20 min",
         "variant_note": f"Single-channel placement at {an[0]}"}
        for i, (s, an, ca_single) in enumerate([
            (c1_symptom, c1_anodes, c1_cathodes[0] if c1_cathodes else "Fpz"),
            (c2_symptom, c2_anodes, c2_cathodes[0] if c2_cathodes else "Fpz"),
            (c3_symptom, c3_anodes, c3_cathodes[0] if c3_cathodes else "Fpz"),
            (c4_symptom, c4_anodes, c4_cathodes[0] if c4_cathodes else "Fpz"),
            (c5_symptom, c5_anodes, c5_cathodes[0] if c5_cathodes else "Oz"),
            (c6_symptom, c6_anodes, c6_cathodes[0] if c6_cathodes else "Fpz"),
            (c7_symptom, c7_anodes, c7_cathodes[0] if c7_cathodes else "Fpz"),
            (c8_symptom, c8_anodes, c8_cathodes[0] if c8_cathodes else "Fpz"),
        ])
    ]

    phenotypes = [
        {"code": f"F{i+1}", "name": name,
         "sozo_seq": [
             f"CES 30 min · Stabilise {name.lower()} presentation",
             f"tDCS {', '.join(c1_anodes)} · 2 mA × 20 min",
             f"TPS {', '.join(t1_targets)} · 3,000–5,000 pulses",
             f"Condition-specific rehabilitation · 30–45 min",
         ],
         "tps_combos": [
             ["TPS + tDCS", f"Sequential modulation for {name}", "tDCS 20 min before TPS", f"{name} phenotype", "Emerging"],
             ["TPS + taVNS", f"Autonomic + cortical dual approach", "taVNS 15 min pre-TPS", f"{name} with autonomic features", "Experimental"],
             ["TPS + CES", f"CES stabilisation + TPS modulation", "CES before TPS sessions", f"{name} with sleep/anxiety", "Weak / supportive"],
         ],
         "nontps_combos": [
             ["tDCS + rehabilitation", f"{name}", "Cortical priming + specific rehab", "tDCS before rehab", "Moderate adjunctive"],
             ["CES + standard care", f"{name} with sleep disturbance", "Sleep restoration adjunct", "Evening CES", "Weak / supportive"],
             ["taVNS + therapy", f"{name} with autonomic features", "Parasympathetic modulation", "taVNS daily", "Emerging"],
         ],
         "rationale": f"Clinical Target: Optimise outcomes for {name} phenotype of {display_name}."}
        for i, name in enumerate(phenotype_names)
    ]

    return {
        "display_name": display_name,
        "icd10": icd10,
        "short_name": short_name,
        "tps_evidence": tps_evidence,
        "tps_regulatory_note": tps_regulatory_note,
        "tps_warning": TPS_WARNING_TEMPLATE.format(condition=display_name),
        "tps": tps_protocols,
        "tdcs": tdcs_protocols,
        "plato": plato_protocols,
        "phenotypes": phenotypes,
        "contraindications_extra": contraindications_extra or [],
        "key_outcome_measures": key_measures,
    }


CONDITIONS["adhd"] = _make_standard_condition(
    "adhd", "ADHD", "F90.0", "ADHD",
    "Inattention & Executive Dysfunction", ["F3", "F4", "FC3"],
    "Hyperactivity & Impulsivity", ["F4", "FC4", "F3"],
    "Working Memory Deficit", ["F3", "P3", "P4"],
    "Emotional Dysregulation", ["F4", "F3"],
    "Learning & Processing Speed", ["F3", "F4", "Pz"],
    "Inattention (Primary)", ["F3", "F4"], ["Fp1", "Fp2"],
    "Impulsivity / Response Inhibition", ["F4"], ["F3"],
    "Working Memory", ["F3"], ["Fp2"],
    "Emotional Dysregulation", ["F4"], ["Fp1"],
    "Processing Speed", ["F3", "F4"], ["Oz"],
    "Reading & Learning", ["F3", "P3"], ["Fp2"],
    "Sleep & Arousal Regulation", ["Fz"], ["Pz"],
    "Maintenance / Home", ["F3"], ["Fp2"],
    ["Inattentive-Predominant", "Hyperactive-Impulsive", "Combined Type",
     "Emotional Dysregulation", "Working Memory Deficit", "Executive Dysfunction",
     "Learning Disability Overlay", "Sleep-ADHD", "Social-Communication Difficulties"],
    "ASRS, BRIEF-A (adults), CPT-3, CAARS, PSQI",
    tps_evidence={
        "regulatory_status": "Investigational",
        "evidence_level": "Pilot RCT, Double-blind Sham-controlled",
        "literature_count": "2+",
        "key_references": "Sham-controlled pilot RCT Frontiers Neurol 2024 (11 citations — adolescents); RCT Protocol 2023 (5 citations); Asian RCT multicenter 2025",
        "side_effects": "Mild headache, fatigue. Safe profile.",
        "notes": "2 RCTs (2023–2026). Pilot RCT in adolescents: significant symptom reduction. Double-blind sham-controlled design. Prefrontal targeting, 6000 pulses, 5 Hz PRF.",
    },
    tps_regulatory_note="Investigational (off-label) — 2+ published papers; double-blind sham-controlled RCT 2024 in adolescents.",
    tps_params_texts=[
        "TPS: Bilateral prefrontal (Fz, F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm² · 6 sessions",
        "TPS: Bilateral prefrontal (Fz, F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Bilateral prefrontal (F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Bilateral prefrontal (F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Bilateral prefrontal (F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
    ],
)

CONDITIONS["alzheimers"] = _make_standard_condition(
    "alzheimers", "Alzheimer's Disease / MCI", "G30 / F06.70", "AD/MCI",
    "Episodic Memory Loss", ["F3", "F4", "P3", "P4"],
    "Language & Naming Deficits", ["F3", "T5", "T6"],
    "Visuospatial Dysfunction", ["P3", "P4", "Pz"],
    "Executive Dysfunction", ["F3", "F4"],
    "Behavioural & Neuropsychiatric Symptoms", ["F3", "F4"],
    "Episodic Memory (Primary)", ["F3", "P3"], ["Fp2"],
    "Language & Naming", ["F3", "T5"], ["Fp2"],
    "Working Memory", ["F3", "F4"], ["Oz"],
    "Attention & Processing", ["Fz"], ["Pz"],
    "Behavioural Symptoms (Agitation)", ["F4"], ["Fp1"],
    "Visuospatial Skills", ["P3", "P4"], ["Oz"],
    "Verbal Fluency", ["F3"], ["Fp2"],
    "Maintenance (MCI Stage)", ["F3", "F4"], ["Fp1", "Fp2"],
    ["Amnestic MCI (Single Domain)", "Amnestic MCI (Multi-Domain)", "Language-Dominant MCI",
     "Executive-Predominant MCI", "Mixed AD Dementia", "Behavioural Variant",
     "Posterior Cortical Atrophy", "Lewy Body Overlap", "Vascular Overlay"],
    "ADAS-Cog, MoCA, MMSE, NPI (neuropsychiatric), CDR",
    [["Cholinesterase inhibitor interaction", "tDCS (temporal)", "RELATIVE — monitor carefully"]],
    tps_evidence={
        "regulatory_status": "CE Marked (Europe, Alzheimer's)",
        "evidence_level": "RCT, Meta-analysis, Systematic Review",
        "literature_count": "31+",
        "key_references": "Beisteiner 2019 (Adv Sci, n=35, 230 citations); Radjenovic 2025 (Psychol Med, n=58); RCT JAMA Network Open 2025; Systematic Review CNS Neurosci Ther 2023; Meta-analysis 2025",
        "side_effects": "Transient headache (~4%), mood deterioration (~3%), dizziness, fatigue. 93% no AEs.",
        "notes": "31 papers (2019–2026). 13 RCTs in overall TPS evidence base. CERAD CTS improved p=.017, d=.32. 9.8-pt gain in top-quartile. 3-month durability. Memory network upregulation fMRI. CE-cleared.",
    },
    tps_regulatory_note="CE Marked (Europe, Alzheimer's) — 31+ published papers including RCTs and meta-analyses.",
    tps_params_texts=[
        "TPS: dlPFC + IFC + LPC + Precuneus (DMN) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm² · 6–12 sessions / 2–4 weeks",
        "TPS: dlPFC + LPC + Precuneus · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: dlPFC + IFC + temporal · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: dlPFC + DMN nodes · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Multi-site DMN (dlPFC + LPC + Precuneus) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
    ],
)

CONDITIONS["stroke_rehab"] = _make_standard_condition(
    "stroke_rehab", "Post-Stroke Rehabilitation", "I69", "Stroke Rehab",
    "Motor Recovery (Hemiplegia)", ["C3", "C4"],
    "Spasticity Management", ["C3", "C4", "Cz"],
    "Aphasia & Language Recovery", ["F3", "T5", "FC3"],
    "Cognitive Rehabilitation", ["F3", "F4"],
    "Neglect & Hemispatial Attention", ["P4", "P3", "T6"],
    "Upper Limb Motor Recovery", ["C3", "C4"], ["Fp1", "Fp2"],
    "Gait & Lower Limb Recovery", ["Cz", "C3", "C4"], ["Fp1"],
    "Spasticity Reduction", ["C4"], ["C3"],
    "Aphasia / Language", ["F3", "T5"], ["Fp2"],
    "Cognitive Rehabilitation", ["F3", "F4"], ["Oz"],
    "Neglect (Right Hemisphere Stroke)", ["P4", "P3"], ["Fp2"],
    "Dysphagia / Swallowing", ["FC3", "FC4"], ["Fpz"],
    "Fatigue & Mood Post-Stroke", ["F3"], ["Fp2"],
    ["Acute Rehabilitation (< 3 months)", "Sub-acute (3–6 months)", "Chronic Motor Deficit",
     "Aphasia-Dominant", "Cognitive-Dominant", "Neglect Syndrome",
     "Spasticity-Dominant", "Depression Post-Stroke", "Balance & Gait Deficit"],
    "FMA, NIHSS, MBI, mRS, BBS (balance), WAB (aphasia)",
    [["Haemorrhagic stroke", "TPS", "ABSOLUTE contraindication"],
     ["Active anticoagulation", "tDCS", "RELATIVE — Doctor decision"]],
)

CONDITIONS["tbi"] = _make_standard_condition(
    "tbi", "Traumatic Brain Injury", "S06", "TBI",
    "Post-Concussive Cognitive Symptoms", ["F3", "F4"],
    "Memory & Attention Deficits", ["F3", "F4", "P3"],
    "Emotional Dysregulation / PTSD Overlap", ["F4", "F3"],
    "Chronic Headache & Pain", ["C3", "C4", "Cz"],
    "Executive Function Recovery", ["F3", "FC3"],
    "Cognitive Recovery (Primary)", ["F3", "F4"], ["Oz"],
    "Attention & Concentration", ["F3"], ["Fp2"],
    "Memory Rehabilitation", ["F3", "P3"], ["Fp2"],
    "Emotional Dysregulation", ["F4"], ["Fp1"],
    "Chronic Pain / Headache", ["C3", "C4"], ["Fp1", "Fp2"],
    "Executive Function", ["F3", "FC3"], ["Fp2"],
    "Sleep Rehabilitation", ["Fz"], ["Pz"],
    "Maintenance / Community Reintegration", ["F3", "F4"], ["Fp1", "Fp2"],
    ["Mild TBI / Concussion", "Moderate TBI Recovery", "Severe TBI Rehabilitation",
     "Post-Concussive Syndrome", "Cognitive-Dominant", "Emotional-Behavioural",
     "PTSD-TBI Overlap", "Chronic Pain Overlay", "Fatigue-Dominant"],
    "GOSE, RPQ, MoCA, PCSS (concussion), PCL-5 (PTSD overlay)",
    [["Acute TBI < 3 months (severe)", "TPS", "RELATIVE — Doctor clearance required"],
     ["Skull fracture / craniotomy site", "TPS · tDCS", "ABSOLUTE at fracture site"]],
)

CONDITIONS["chronic_pain"] = _make_standard_condition(
    "chronic_pain", "Chronic Pain / Fibromyalgia", "G89.29 / M79.3", "Chronic Pain",
    "Central Sensitisation", ["C3", "C4", "Cz"],
    "Fibromyalgia Widespread Pain", ["C3", "C4", "F3"],
    "Neuropathic Pain", ["C3", "C4"],
    "Pain Catastrophising / Psychological", ["F3", "F4"],
    "Fatigue & Sleep in Pain", ["F3", "Fz"],
    "Central Pain (Primary)", ["C3", "C4"], ["Fp1", "Fp2"],
    "Fibromyalgia", ["C3", "C4", "Cz"], ["Fp1"],
    "Neuropathic Pain", ["C3"], ["Fp2"],
    "Low Back Pain", ["C4", "C3"], ["Fp1"],
    "Pain Catastrophising", ["F3", "F4"], ["Oz"],
    "Fatigue in Pain", ["Fz"], ["Pz"],
    "Depression-Pain Comorbidity", ["F3"], ["Fp2"],
    "Maintenance / Home Pain", ["C3", "C4"], ["Fp1", "Fp2"],
    ["Central Sensitisation Syndrome", "Fibromyalgia", "Neuropathic Pain",
     "Musculoskeletal Chronic Pain", "Low Back Pain", "CRPS",
     "Headache / Migraine", "Pain-Depression Comorbidity", "Pain-Sleep Comorbidity"],
    "VAS, NRS, BPI, FIQR (fibromyalgia), MFI-20 (fatigue), PHQ-9",
    tps_evidence={
        "regulatory_status": "Investigational",
        "evidence_level": "Case series, SA Perspective",
        "literature_count": "2+",
        "key_references": "TPS in AD, PD, and chronic pain: South American perspective (Brain Stimulation 2025); NAc stimulation case in TRD/pain 2023",
        "side_effects": "Well tolerated; standard TPS side effect profile.",
        "notes": "Very early stage for pain. LIFU/tFUS has stronger pain evidence (15+ papers). 2 papers (2023–2026). Consider TPS as adjunct to other modalities.",
    },
    tps_regulatory_note="Investigational (off-label) — 2+ published papers; emerging South American clinical use reported 2025.",
    tps_params_texts=[
        "TPS: Bilateral M1 (C3/C4) + frontal · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm² · 6 sessions",
        "TPS: Bilateral M1 (C3/C4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Contralateral M1 (C3/C4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Frontal (F3/F4) + M1 · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Frontal (F3/Fz) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
    ],
)

CONDITIONS["ptsd"] = _make_standard_condition(
    "ptsd", "Post-Traumatic Stress Disorder", "F43.1", "PTSD",
    "Hypervigilance & Hyperarousal", ["F4", "F3"],
    "Intrusions & Flashbacks", ["F4", "FC4"],
    "Avoidance Behaviour", ["F3", "F4"],
    "Emotional Numbing / Dissociation", ["F3", "Fz"],
    "Cognitive Symptoms (Memory, Concentration)", ["F3", "F4", "P3"],
    "Hyperarousal (Primary)", ["F4"], ["Fp1"],
    "Intrusions / Flashbacks", ["F4", "FC4"], ["Fp1"],
    "Avoidance", ["F3", "F4"], ["Oz"],
    "Emotional Numbing", ["F3"], ["Fp2"],
    "Cognitive Symptoms", ["F3", "F4"], ["Oz"],
    "Sleep Disturbance", ["Fz"], ["Pz"],
    "Depression Comorbidity", ["F3"], ["Fp2"],
    "Maintenance / Relapse Prevention", ["F4"], ["Fp1"],
    ["Hyperarousal-Dominant", "Intrusion-Dominant", "Avoidance-Dominant",
     "Emotional Numbing / Dissociative", "Complex PTSD", "PTSD-Depression Comorbid",
     "PTSD-Substance Use", "Military / Combat PTSD", "Childhood Trauma PTSD"],
    "CAPS-5, PCL-5, IES-R, PHQ-9, PSQI",
    [["Active suicidal ideation / self-harm", "All modalities", "HOLD — safety protocol first"],
     ["Acute trauma reactivation during session", "All modalities", "STOP — stabilisation protocol"]],
)

CONDITIONS["ocd"] = _make_standard_condition(
    "ocd", "Obsessive-Compulsive Disorder", "F42", "OCD",
    "Obsessions & Compulsions", ["FC3", "FC4", "F3"],
    "Contamination / Washing Compulsions", ["F3", "FC3"],
    "Checking Compulsions", ["F3", "F4", "FC3"],
    "Hoarding Variant", ["F3", "F4"],
    "Pure-O / Intrusive Thoughts", ["F3", "F4", "Fz"],
    "Primary OCD Protocol", ["FC3", "FC4"], ["Fpz"],
    "Contamination / Washing", ["F3", "FC3"], ["Fp2"],
    "Checking", ["F4"], ["Fp1"],
    "Symmetry / Ordering", ["F3", "F4"], ["Oz"],
    "Hoarding", ["F3"], ["Fp2"],
    "Pure-O Intrusive Thoughts", ["F3", "Fz"], ["Pz"],
    "OCD-Depression Comorbidity", ["F3"], ["Fp2"],
    "Maintenance Post-ERP", ["FC3"], ["Fpz"],
    ["Contamination / Washing", "Checking / Doubt", "Symmetry / Ordering",
     "Hoarding", "Pure-O / Intrusive Thoughts", "Sexual / Aggressive Obsessions",
     "Religious / Scrupulosity", "OCD + Depression", "OCD + Tic Disorder"],
    "Y-BOCS / CY-BOCS, OCI-R, PHQ-9, EQ-5D",
    [["Tic disorder comorbidity (Tourette's)", "TPS (pre-SMA)", "RELATIVE — lower intensity"]],
)

CONDITIONS["ms"] = _make_standard_condition(
    "ms", "Multiple Sclerosis", "G35", "MS",
    "Motor Fatigue & Weakness", ["C3", "C4", "Cz"],
    "Cognitive Impairment (Cog Fog)", ["F3", "F4"],
    "Spasticity", ["C3", "C4"],
    "Depression & Mood", ["F3", "F4"],
    "Pain & Sensory Symptoms", ["C3", "C4", "P3", "P4"],
    "Motor Fatigue (Primary)", ["C3", "C4"], ["Fp1", "Fp2"],
    "Cognitive Rehabilitation", ["F3", "F4"], ["Oz"],
    "Spasticity Management", ["C4", "C3"], ["Fp1"],
    "Depression", ["F3"], ["Fp2"],
    "Upper Limb Function", ["C3", "C4"], ["Fp1"],
    "Balance & Gait", ["Cz", "Cb1", "Cb2"], ["Fpz"],
    "Pain & Neuropathic", ["C3", "C4"], ["Fpz"],
    "Fatigue Management", ["F3", "Fz"], ["Pz"],
    ["Relapsing-Remitting MS (RRMS)", "Secondary Progressive MS (SPMS)", "Primary Progressive MS (PPMS)",
     "Motor-Dominant", "Cognitive-Dominant (Cog Fog)", "Fatigue-Dominant",
     "Pain-Dominant", "Depression Comorbidity", "Balance & Gait Deficit"],
    "EDSS, T25FW, SDMT (cognition), MFIS (fatigue), MBI",
    [["Active MS relapse", "All modalities", "POSTPONE — wait until stable × 4 weeks"],
     ["Immunomodulatory therapy interaction", "tDCS", "RELATIVE — Doctor review"]],
)

CONDITIONS["asd"] = _make_standard_condition(
    "asd", "Autism Spectrum Disorder", "F84.0", "ASD",
    "Social Communication Deficit", ["F3", "F4", "T4", "T6"],
    "Repetitive Behaviours & Restricted Interests", ["F3", "FC3", "FC4"],
    "Sensory Processing Difficulties", ["P3", "P4", "Pz"],
    "Anxiety & Emotional Regulation", ["F4", "F3"],
    "Attention & Executive Function", ["F3", "F4"],
    "Social Communication (Primary)", ["F3", "T4"], ["Fp2"],
    "Language & Communication", ["F3", "T5"], ["Fp2"],
    "Repetitive Behaviours", ["FC3", "FC4"], ["Fpz"],
    "Sensory Sensitivity", ["P3", "P4"], ["Fz"],
    "Anxiety in ASD", ["F4"], ["Fp1"],
    "Attention & Executive Function", ["F3", "F4"], ["Oz"],
    "Social Anxiety Overlay", ["F4", "FC4"], ["Fp1"],
    "Adaptive Behaviour & Independence", ["F3", "F4"], ["Oz"],
    ["Social Communication Deficit", "Rigid / Repetitive Behaviours", "Sensory Overresponsivity",
     "Sensory Underresponsivity", "Anxiety Comorbidity", "ADHD Comorbidity",
     "Language-Dominant (Verbal)", "Minimal Verbal ASD", "High-Functioning ASD / Autism"],
    "SRS-2, ABC, VABS-3, ADOS-2 (diagnostic), PSQI",
    [["Seizure disorder (common in ASD)", "All modalities", "ABSOLUTE if uncontrolled seizures"],
     ["Severe sensory sensitivity to electrodes", "tDCS", "ADAPT — use minimal gel, desensitisation protocol"]],
    tps_evidence={
        "regulatory_status": "Investigational",
        "evidence_level": "Double-blind RCT, Sham-controlled",
        "literature_count": "4+",
        "key_references": "Beisteiner 2023 Brain Communications (21 citations, RCT); RCT Protocol 2022 (7 citations); Brain connectivity post-hoc Autism Research 2025; Asian multicenter RCT 2025",
        "side_effects": "Well tolerated; standard TPS side effect profile.",
        "notes": "4 RCTs/protocols (2022–2026). Strongest NIBS evidence for ASD. Network connectivity changes documented. Independent Asian cohort confirms 2025.",
    },
    tps_regulatory_note="Investigational (off-label) — 4+ published papers; double-blind sham-controlled RCT (Beisteiner 2023, Brain Communications).",
    tps_params_texts=[
        "TPS: Prefrontal + parietal social networks (F3/F4, P3/P4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm² · 6–12 sessions",
        "TPS: Prefrontal + parietal (F3/F4, P3/P4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Parietal social networks (P3/P4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Prefrontal (F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
        "TPS: Bilateral prefrontal (F3/F4) · 6,000 pulses · 5 Hz PRF · EFD 0.20 mJ/mm²",
    ],
)

CONDITIONS["long_covid"] = _make_standard_condition(
    "long_covid", "Long COVID / Brain Fog", "U09.9", "Long COVID",
    "Cognitive Impairment / Brain Fog", ["F3", "F4"],
    "Fatigue & Post-Exertional Malaise", ["F3", "Fz"],
    "Autonomic Dysfunction (POTS)", ["F3", "F4"],
    "Depression & Mood Dysregulation", ["F3", "F4"],
    "Headache & Neuropathic Pain", ["C3", "C4", "Fz"],
    "Cognitive Rehabilitation (Primary)", ["F3", "F4"], ["Oz"],
    "Fatigue Management", ["Fz"], ["Pz"],
    "Attention & Working Memory", ["F3"], ["Fp2"],
    "Autonomic Stabilisation", ["F4"], ["Fp1"],
    "Depression & Mood", ["F3"], ["Fp2"],
    "Sleep Dysfunction", ["Fz", "F3"], ["Pz"],
    "Executive Function", ["F3", "F4"], ["Oz"],
    "Maintenance / Pacing Programme", ["F3", "F4"], ["Oz"],
    ["Cognitive-Dominant (Brain Fog)", "Fatigue-Dominant (PEM)", "Autonomic Dysfunction (POTS)",
     "Pain-Dominant", "Depression / Mood Comorbidity", "Sleep Dysfunction",
     "Respiratory Overlay", "Multi-System", "Mild / Recovering"],
    "MoCA, MFI-20, COMPASS-31 (autonomic), PHQ-9, PSQI, SF-36",
    [["Post-exertional malaise (PEM)", "All modalities", "REDUCE intensity; strict energy pacing protocol"],
     ["Active infection / fever", "All modalities", "POSTPONE until recovered"]],
)

CONDITIONS["tinnitus"] = _make_standard_condition(
    "tinnitus", "Chronic Tinnitus", "H93.1", "Tinnitus",
    "Auditory Cortex Hyperactivity", ["T5", "T6", "FC3"],
    "Thalamocortical Dysrhythmia", ["T5", "T6"],
    "Distress & Limbic Involvement", ["F3", "F4"],
    "Attentional Capture", ["F3", "F4", "P3"],
    "Sleep & Hyperarousal Overlay", ["Fz", "F3"],
    "Auditory Cortex Inhibition (Primary)", ["T5", "T6"], ["FC3"],
    "Left Temporal Cathodal", ["FC3"], ["T5"],
    "Right Temporal Cathodal", ["FC4"], ["T6"],
    "Prefrontal Distress Modulation", ["F3", "F4"], ["Oz"],
    "Sleep & Arousal", ["Fz"], ["Pz"],
    "Attention Network Modulation", ["F3", "P3"], ["Fp2"],
    "Depression-Tinnitus Comorbidity", ["F3"], ["Fp2"],
    "Maintenance Auditory", ["T5", "T6"], ["FC3"],
    ["Unilateral Tonal Tinnitus", "Bilateral Tonal Tinnitus", "Pulsatile Tinnitus",
     "Noise-Sensitive / Hyperacusis", "Tinnitus + Depression", "Tinnitus + Anxiety",
     "High-Frequency Tinnitus", "Low-Frequency Tinnitus", "Tinnitus + Sleep Disorder"],
    "THI, TFI, NRS (loudness), VAS (distress), PSQI",
    [["Cochlear implant (ipsilateral)", "All modalities", "ABSOLUTE — consult audiologist"]],
)

CONDITIONS["insomnia"] = _make_standard_condition(
    "insomnia", "Insomnia Disorder", "G47.00", "Insomnia",
    "Sleep Onset Insomnia (DSWPD)", ["F3", "F4", "Fz"],
    "Sleep Maintenance Insomnia", ["Fz", "F3"],
    "Early Morning Awakening", ["F3", "F4"],
    "Hyperarousal & Pre-sleep Worry", ["F4", "F3"],
    "Comorbid Depression-Insomnia", ["F3", "F4"],
    "Sleep Onset (Primary)", ["Fz", "F3"], ["Pz"],
    "Sleep Maintenance", ["F3", "F4"], ["Oz"],
    "Sleep Quality & Architecture", ["Fz"], ["Pz"],
    "Hyperarousal Reduction", ["F4"], ["Fp1"],
    "Circadian Rhythm Alignment", ["Fz", "Fpz"], ["Pz"],
    "Stress-Related Insomnia", ["F3", "F4"], ["Oz"],
    "Comorbid Depression-Insomnia", ["F3"], ["Fp2"],
    "Maintenance Home Sleep", ["Fz"], ["Pz"],
    ["Sleep Onset Insomnia", "Sleep Maintenance Insomnia", "Early Morning Awakening",
     "Hyperarousal-Driven Insomnia", "Circadian Rhythm Disorder", "Comorbid Depression-Insomnia",
     "Comorbid Anxiety-Insomnia", "Insomnia in Elderly", "Medication-Dependent Insomnia"],
    "ISI, PSQI, ESS (daytime sleepiness), DBAS-16, PHQ-9",
    [["Severe OSA (undiagnosed)", "CES · tDCS", "RELATIVE — sleep study first"],
     ["CES use during pregnancy", "CES", "RELATIVE — Doctor decision"]],
)
